### ISSUE TITLE
Documentation: readme code-blocks could use an update

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#10334]
Following on from PR #10329 I hope to work through some of the slightly out dated code-blocks in various readme files.

The following files all seem like they might benefit from a bit of a face-lift (I'll track progress along side them - feel free to jump in too!).

- [ ] [blocks/upgrade-nudge-expanded/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/upgrade-nudge-expanded/README.md)
- [x] [components/animate/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/animate/README.md) (PR open @ #10513)
- [x] [components/banner/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/banner/README.md) (PR open @ #10513)
- [x] [components/bulk-select/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/bulk-select/README.md) (PR open @ #10513)
- [x] [components/button-group/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/button-group/README.md) (PR open @ #10513)
- [x] [components/button/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/button/README.md) (PR open @ #10513)
- [x] [components/card/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/card/README.md) (PR open @ #10513)
- [x] [components/chart/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/chart/README.md) (PR open @ #10513)
- [x] [components/credit-card-form-fields/README](https://github.com/Automattic/wp-calypso/blob/master/client/components/credit-card-form-fields/README.md) (PR open @ #10513)
- [x] [components/empty-content/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/components/empty-content/README.md) (#10376)
- [x] [components/forms/multi-checkbox/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/components/forms/multi-checkbox/README.md) (PR open @ #10483)
- [x] [components/forms/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/components/forms/README.md) (PR open @ #10483)
- [x] [lib/abtest/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/README.md) (#10335)
- [ ] [lib/ads/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/ads/README.md)
- [x] [lib/application-passwords-data/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/application-passwords-data/README.md) (#10338)
- [x] [lib/connected-applications-data/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/connected-applications-data/README.md) (#10335)
- [x] [lib/detect-history-navigation/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/detect-history-navigation/README.md) (#10335)
- [ ] [lib/devices/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/devices/README.md) - Seems incomplete/could be elaborated on
- [x] [lib/email-followers/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/email-followers/README.md) (PR open @ #10483)
- [x] [lib/followers/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/followers/README.md) (PR open @ #10483)
- [x] [lib/load-script/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/load-script/README.md) (PR open @ #10483)
- [ ] [lib/local-list/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/local-list/README.md) - Appears to be dead code?
- [x] [lib/local-storage/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/local-storage/README.md) (PR open @ #10483)
- [ ] [lib/localforage/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/localforage/README.md)
- [ ] [lib/mixins/dirty-linked-state/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/mixins/dirty-linked-state/README.md)
- [ ] [lib/mixins/searchable/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/mixins/searchable/README.md)
- [ ] [lib/mixins/url-search/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/mixins/url-search/README.md)
- [x] [lib/paygate-loader/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/paygate-loader/README.md) (PR open @ #10483)
- [x] [lib/plugins/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plugins/README.md) (PR open @ #10483)
- [x] [lib/plugins/wporg-data/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plugins/wporg-data/README.md) (#10337)
- [x] [lib/products-list/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/products-list/README.md) (#10335)
- [ ] [lib/react-pass-to-children/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/react-pass-to-children/README.md)
- [x] [lib/route/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/route/README.md) (PR open @ #10483)
- [x] [lib/scroll-to/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/scroll-to/README.md) (#10335)
- [x] [lib/site-stats-sticky-tab/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/site-stats-sticky-tab/README.md) (PR open @ #10483)
- [x] [lib/stats/stats-list/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/stats/stats-list/README.md) (PR open @ #10483)
- [x] [lib/store-transactions/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/store-transactions/README.md) (PR open @ #10483)
- [x] [lib/two-step-authorization/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/two-step-authorization/README.md) (#10335)
- [x] [lib/user/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/user/README.md) (PR open @ #10483)
- [x] [lib/users/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/users/README.md) (PR open @ #10483)
- [x] [lib/viewport/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/viewport/README.md) (#10335)
- [x] [my-sites/jetpack-manage-error-page/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/jetpack-manage-error-page/README.md) (#10335)
- [x] [my-sites/lib/highlight/README.md](https://github.com/Automattic/wp-calypso/blob/master/client/lib/highlight/README.md) (#10354)
