### ISSUE TITLE
Billing: Reduxify billing components

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#10554]
I've started converting billing history to use Redux, and I intend to use this issue as a master thread.

- [x] Introduce Redux actions, reducer, and selectors for billing data (with tests) - #10379.
- [x] Introduce a `QueryBillingTransactions` query component - #10555.
- [x] ES6ify and modernize the BillingHistory component and remove ESLint warnings. - #10556
- [x] ES6ify and modernize the BillingReceipt component and remove ESLint warnings. - #10556
- [x] Update the `BillingReceipt` component to use Redux. - #10654
- [x] Update the `BillingHistory` component to use Redux. - #10654
- [x] Add a basic loading placeholder to `BillingReceipt`, as the one in `BillingHistory`. - #10654
- [x] Use `DocumentHead` instead of `setDocumentHeadTitle` for document titles. - #10651 
- [x] Remove `lib/billing-history-data` as it will no longer be used. - #10683
- [x] Use [PageViewTracker](https://github.com/Automattic/wp-calypso/tree/master/client/lib/analytics/page-view-tracker) for analytics in controller - #10684
- [x] Implement more specific selectors by type of transactions - #10685
- [x] Cleanup schema to resolve state validation issues - #10732
- [x] Simplify `render()` in `me/billing-history/receipt.jsx` - https://github.com/Automattic/wp-calypso/pull/10654#discussion_r96280499 - #11031
- [x] Suggest a better placeholder for Receipt - https://github.com/Automattic/wp-calypso/pull/10654#discussion_r96282230 - #11072
- [x] Suggest a better placeholder for Billing History - https://github.com/Automattic/wp-calypso/pull/11072#pullrequestreview-19694568 - #11160
- [x] Remove unused instances of the `eventRecorder` mixin - #11161.
- [x] Implement receipt email sending in Redux - #11164.
- [x] Move `emailReceipt` of `BillingHistoryTable` to Redux - #11166.

**Comment by tyxla** [comment]
There's a lot more we can refactor in to some of the billing components (ES6ify and modernize for example), but I've achieved my goal here with reduxifying the entire Billing History section, so closing this one.
