### ISSUE TITLE
Free Trials: Implement free trial hub

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/wp-calypso#1151]
When a user has an active free trial we need should acknowledge that fact on the /plans page and display helpful information such as # of days left on the  trial.

**Todo**
- [x] Implement status box with 'days remaining' bar
- [x] Add expiring state to `PlanStatus` (#1708) #1708
- [x] Add expired state to `PlanStatus` (design: #1471) #1780
- [x] Add expired state to `PlanFeatures` (design: #1471)
- [x] Add 'Purchase Now' button to status box. Upgrading a trial to a full plan will bump the expiry of the plan to a year from the start of the trial. (#1517)
- [x] Implement static 'Your Site's Features' component (https://github.com/Automattic/wp-calypso/pull/1565)
- [x] Add mobile design @mikeshelton1503

**Comment by mikeshelton1503** [comment]
I'll provide designs for:

>When a user has an active free trial we need should acknowledge that fact on the /plans page and display helpful information such as # of days left on the trial.

**Comment by mikeshelton1503** [comment]
Here is the desktop design mockup for what we're calling the "Free Trial Hub" which should display during an active trial:

![image](https://cloud.githubusercontent.com/assets/12596797/11636566/bf82b45e-9cea-11e5-990e-15efab74c00b.png)

When the trial is <5 days away the "status box" at the top should have a few adjustments:

- Change to primary button style for `Purchase Now`.
- Change days remaining text to red.
- Change progress bar to red.

![image](https://cloud.githubusercontent.com/assets/12596797/11636479/53b97550-9cea-11e5-9da4-0e037016669c.png)

I'll provide a mobile mockup after copy is nailed down.

cc @breezyskies @danhauk

**Comment by danhauk** [comment]
Also worth noting that the "Need more power..." at the bottom would only appear if the user is on a free trial for the Premium plan.

**Comment by breezyskies** [comment]
> Change to primary button style for `Purchase Now`.

Should we also change the feature buttons to be secondary styling at this point?

Some copy feedback:
- `Give your site a custom site address.` -> `Claim your free domain name.` or `Claim your free custom site address.` I think we should emphasize the "free" part here more, not in a promotional way, but to be super clear about it. I'm also not 100% sold on using "custom site address" vs. "custom domain" here (I think we usually use "site address" to describe the *.wordpress.com one, but "domain" for anything custom).
- I would probably kill the `You can`'s from the beginning of the later feature descriptions (e.g. `Chat live with our Happiness Engineers...`).

Also, did we decide to link the checked-off features to the appropriate section (with a hover state)? The Premium Themes one, in particular, could benefit from this (or we could inline link some of the description text).

**Comment by mikeshelton1503** [comment]
> Also worth noting that the "Need more power..." at the bottom would only appear if the user is on a free trial for the Premium plan.

Thanks, Dan!

> Should we also change the feature buttons to be secondary styling at this point?

I wondered about that but wasn't sure if changing all the buttons would be too big of a change. Though strategically it would make sense. Let's do it!

> I'm also not 100% sold on using "custom site address" vs. "custom domain" here

Ran and I have discussed moving toward using "custom site address". That's what I used in the product marketing pages (and plan to change the compare page on /plans page when we launch those pages).

> did we decide to link the checked-off features to the appropriate section (with a hover state)?

I don't know if we ever decided on it. I'm hesitant to link in the used sections because we don't want users defaulting to coming to this page to navigate since it will disappear after the trial. However, for the ones that will always be checked off, an inline `learn more` link makes sense. Though `No Ads` and `VideoPress` are really the only ones that need a learn more link (Storage seems self-explanatory). So not really sure how to proceed there.

**Comment by danhauk** [comment]
> I'm hesitant to link in the used sections because we don't want users defaulting to coming to this page to navigate since it will disappear after the trial.

We _could_ keep it for all newly-upgraded users and not just for the trial. It could provide useful in educating them more about their plan and helping them get the most from the upgrade. 

It reminds me of the Carousel app from Dropbox. They have a persistent green bar at the top that takes you to a "learn how to use the app" view. Once you complete all the interactions of the app in the checklist (viewing a photo full screen, scrolling through using a timeline, etc) the green bar goes away. 

I wonder if this could be something similar. 

--
Dan Hauk
Automattic | WordPress.com

**Comment by mikeshelton1503** [comment]
> We _could_ keep it for all newly-upgraded users and not just for the trial.

Totally agree. @breezyskies and I discussed that as well but that'll be something for the future. Definitely think it will be helpful everyone that has a plan.

**Comment by mikeshelton1503** [comment]
Mobile version:

![image](https://cloud.githubusercontent.com/assets/12596797/11670440/dad955d8-9dcf-11e5-9951-694f9d1dd314.png)

**Comment by drewblaisdell** [comment]
As of #1820, the `PlanFeatures` are no longer `primary`, so I removed the 'expiring state' checkbox for that component because the expiring state is now the same as the active trial state.

**Comment by drewblaisdell** [comment]
I opened an issue for updating `PlanFeatures` based on the features the user has used and removed the corresponding checkbox in this issue: #1904

**Comment by drewblaisdell** [comment]
Each 'sub-issue' we were tracking here is finished, so we can close this.
