### ISSUE TITLE
Implement More Jetpack Module Settings

### ISSUE THREAD

**Issue by oskosk** [Automattic/wp-calypso#11676]
This task list is a follow-up to the list in #9171. The list there grew big and thus, this list is here for a more clear picture.

## UI tasks

**These tasks and notes are based on what's specified by p6TEKc-HQ-p2**

### Considerations
* When a module is disabled (via a clear toggle like Carousel), hide module options. Not necessary, but could be nice.
* When a toggle is used, it should immediately enable that thing and show a global notice to show status of enabling that thing.
* ~When checkboxes are used, clicking a save settings button is required.~ We decided to replace checkboxes for autosaving toggles everywhere.
* A user can click a save settings button at any time even if not needed (though not when a setting is being applied). Try the buttons in Calypso to see how they work.
* When a module is inactive, the form controls representing its child settings, should be disabled too.
* Every time the word setting is used here, remember that it maps to either:
  * A single WP option.
  * A key inside a serialized object saved in a WP option
* Take in account those modules that should be disabled if the site’s is in dev mode. 
* Take in account we should **probably** not modify live settings when site is in staging.
* Take in account features that are only available in some of the plans.

### General tasks

* [x] Make sure that all the toggles introduced by tasks related to #9171 update their respective settings as soon as they're toggled and not just ater clicking the *SAVE SETTINGS* button
  * [x] Add handleAutosavingToggle method to wrap-settings-form High-order component - @oskosk - #11745
  * [x] Make the carousel_display_exif setting toggle for jetpack sites autosave on toggle - @oskosk - #11744.
  * [x] Make the toggles in Writing Settings for Custom Content Types, autosave on toggle - @oskosk - #11901
  * [x] Make the toggles in Writing Settings for Theme Enhancements, autosave on toggle - @oskosk - #11898
  * [x] Make the toggles in the Discussion tab, autosave on toggle - @oskosk - #11939 
* [x] Introduce dev mode notice for settings - @tyxla - #11386.

### Writing Tab

* [ ] Make the Photon toggle enable Tiled galleries on toggle.
* [ ] Implement the Card for **Composing** settings
  * [x] Move the card in a separate component - #11192 - @tyxla
  * [x] Implement After the Deadline settings - #11231 - @tyxla
  * [ ] Implement the setting for Markdown - @oskosk - #11847
  * Includes **Default Post Category** and **Default Post Format** settings.
  * Implement toggle for _Write posts or pages in plain-text Markdown syntax_.
  * Implement toggle for _Check your spelling, style, and grammar with the After the Deadline proofreading service_.
* [x] Disable After the Deadline when in Dev mode - @tyxla - #11779
* [x] Disable Post by Email when in Dev mode - @tyxla - #11781
* [x] Disable Photon when in Dev mode - @tyxla - #11783

### Discussion Tab

* [ ] Implement the Card for **Comments** settings
  * [X] Implement a section for Comments Label and color scheme - @ryelle - #10680
    * Implement an input for _Comments label_.
    * Implement a select for _Color scheme_.
  * [x] Includes a section with the six existing settings currently under **Other comment settings** but as toggles. _Comments should be displayed with the  comments at the top of each page_ should be moved to a toggle which enables older-to-newest sorting if turned on - @ryelle - #10167.
    * [ ] Implement a toggle for _Enable pop-up business cards over commenters' Gravatars_.
    * [ ] Implement a toggle for _Enable Markdown use for comments_ - @ryelle  - #10785.
  * [x] Includes a section for *E-mail me whenever* - @ryelle - #10167
    * Includes the two current settings (_Anyone posts a comment_ and _A comment is held for moderation) but with toggles instead of checkboxes
    * Implement the new setting **Someone likes on of my posts**.
  * [x] Includes the section *Before a comment appears* which is the same as current but with toggles instead of checkboxes - @ryelle - #10167
  * Includes the section for _Comment moderation_ which is basically the same as the current one.
* [x] Improve the Subscriptions card - @tyxla - #11701
* [x] Disable Subscriptions when in Dev mode - @tyxla - #11784

### Traffic Tab

* [x] Reorganize settings a little to introduce the Traffic view as detailed in #11615.
  * [x] Introduce the Traffic section - @tyxla - #11788
  * [x] Move SEO box in a separate component - @tyxla - #11825
  * [x] Move Related Posts in a separate component - @tyxla - #11638
  * [x] Using real time Google Analytics module activation state - @tyxla - #11634
  * [x] Fixing some console warnings in SEO settings - @tyxla - #11663
  * [x] Enabling the SEO card for Jetpack sites - @tyxla - #11670
  * [x] Fix a bug with the SEO card automatically scrolling the user - @tyxla - #11671

### Security Tab

* [ ] Implement **Backups and Security** Card.
  * [ ] Implement text/notice that states the site is protected ( or not ).
  * [ ] Implement Link that reads "Configure backups and security scanning".
  * [ ] Implement Link that reads "Reveal API Key".
* [ ] Implement **Antispam** Card. - @oskosk - #12205 
  * [ ] Implement toggle "Show the number of approved comments beside each comment author".
  * [ ] Implement Link that reads "Reveal API Key".
* [x] Implement **Brute force protection** Card - @tyxla - #12105
  * [x] Either revamp or reuse this card wrapping it up with `wrap-settings-form`.
  * [x] Implement toggle for enabling BruteProtect Module
* [x] Implement **WordPress.com log in** Card - @tyxla - #11881
  * [x] Implement toggle for enabling the SSO module reading "Allow log-in using WordPress.com accounts".
  * [x] Implement sub-setting toggle "Match accounts using email addresses".
  * [x] Implement sub-setting toggle "Require two step authentication".

### Sharing 

* [ ] Make the sharing buttons tab not redirect to `/settings/sharing/undefined` if the site has the Sharing module deactivated - @oskosk - #12766.
* [ ] Make the Connections tab not redirect to sharing buttons and/or Stats if the site has the Publicize module deactivated - @oskosk - #12766.

**Comment by oskosk** [comment]
@rickybanister @MichaelArestad we could use some mockup love or guidance regarding the tasks listed under the **Traffic tab** and **Security Tab**. If the mockups in p6TEKc-HQ-p2 still apply here, a mention to them will be fine. Thanks!

**Comment by oskosk** [comment]
@rickybanister @MichaelArestad , looks like @tyxla already asked something simillar among the comments in p6TEKc-HQ-p2. Please ignore my request.

**Comment by rickybanister** [comment]
Can we close this meta issue since there are only one or two items remaining and instead open individual issues in the milestone?

**Comment by tyxla** [comment]
Sure, that makes sense. Let's open issues in the milestone for anything that remains to be done.
