### ISSUE TITLE
Migrate CommonJS to ES2015 module notation (imports and exports)

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#11688]
## Context

Porting CommonJS modules to ES2015 modules will allow us to take advantage of [Webpack 2's tree shaking optimization](https://gist.github.com/sokra/27b24881210b56bbaff7#es6-specific-optimizations).

### Completed
- [x] Improve 5to6-codemod's import comment handling
- [x] Write a codemod to generate named exports from default object import (awaiting publication)
- [x] Improve CommonJS import codemod's comment handling
- [x] Improve CommonJS import codemod's called import handling
- [x] Write a codemod to hoist imports in blocks to the top
- [x] Test running codemods on `client/` 
- [x] Enhance the named export generation codemod to transform `function`s to `export function`s
- [x] Provide easy executables for Calypso developers to ES2015-ify their modules (#12520)

### Backburner
- [ ] Integrate eslint-plugin-import into project (#12303)
- [ ] Fix Recast bug for the extra blank line between imports
- [ ] Create a streamlined way to execute codemods (previous attempt:`run-codemods` #13163)

### Initial impressions

We have many occurrences of [conditional imports](https://github.com/Automattic/wp-calypso/blob/a4068a197d12fff00f3aa7d94a78104b0c037c95/client/lib/keyboard-shortcuts/index.js#L5) and [imports inside blocks](https://github.com/Automattic/wp-calypso/blob/a4068a197d12fff00f3aa7d94a78104b0c037c95/client/me/controller.js#L23). Neither of these are allowed in [ES modules](http://www.2ality.com/2014/09/es6-modules-final.html#static-module-structure), so we'll need to migrate these eventually.
- [Dynamic](https://babeljs.io/docs/plugins/syntax-dynamic-import/) [imports](https://github.com/airbnb/babel-plugin-dynamic-import-webpack) are possible, but probably not stable enough for us to jump on.
- Hoisting imports from the blocks to the top might be straightforward solution. I would need to figure out how much of these imports have side effects before going forward with this, though. Most imports inside a block are from `controller.js` files.

### Progress - 03/01/2017

- Tested porting CommonJS imports via regex.
- Tested porting CommonJS imports/exports via [5to6-codemod](https://github.com/5to6/5to6-codemod).

### Progress - 03/24/2017

- Contributed improvements to [5to6-codemod](https://github.com/5to6/5to6-codemod) relating to both import and export transforms; currently awaiting merge & NPM publish for new version.
- PR in progress to add [5to6-codemod](https://github.com/5to6/5to6-codemod) as executable scripts inside this project. 
- PR in progress for enhancing our ESLint with eslint-plugin-import.

### Progress - 04/04/2017
- Made various improvements to 5to6-codemod, including CommonJS import hoisting and improved reliability. 
- All three codemods (`import`, `export`, and `export name generation`) run error-free for files inside `client/`.

### Progress - 04/17/2017
- Refactored `run-codemods` into a separate PR.

**Comment by jsnmoon** [comment]
Patterns I see often in our codebase are [conditional imports](https://github.com/Automattic/wp-calypso/blob/a4068a197d12fff00f3aa7d94a78104b0c037c95/client/lib/keyboard-shortcuts/index.js#L5) and [imports inside blocks](https://github.com/Automattic/wp-calypso/blob/a4068a197d12fff00f3aa7d94a78104b0c037c95/client/me/controller.js#L23). 

I'm currently leaning toward leaving both of these cases alone for the scope of this change.
- [Although](https://babeljs.io/docs/plugins/syntax-dynamic-import/) [possible](https://github.com/airbnb/babel-plugin-dynamic-import-webpack), there is no clean way to perform dynamic imports while preserving ES2015 syntax. 
- Moving imports inside blocks to the top should be straightforward from a transformation perspective, but I'd wager that some of those imports have side effects. Given that these imports are largely restricted to `controller.js` files, I think the issue is isolated enough for a straightforward fix in the future.

What do you guys think?

**Comment by jsnmoon** [comment]
Update: named export generation codemod has been enhanced.

**Comment by jsnmoon** [comment]
Update: `bin/run-codemods` has been created.

**Comment by jsnmoon** [comment]
Update: Added progress update for 04/17/2017 covering `run-codemods` PR, `react-codemods` PR, and upstream PR for `reactjs/react-codemod`.

**Comment by jsnmoon** [comment]
Update: Removed all mentions of `react-codemods`. Please refer to #13321 if you'd like to follow along the React migration project!

**Comment by jsnmoon** [comment]
This issue is in a good place to close for now. If anyone has any interest in picking up the backburner items, please ping!
