### ISSUE TITLE
Reader: Add tracking with Tracks

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#1216]
Match what we're doing in the native apps.

- [x] `reader_article_commented_on`
- [x] `reader_article_liked`
- [x] `reader_article_unliked`
- [x] `reader_article_opened`
- [x] `reader_blog_preview`
- [x] `reader_discover_viewed`
- [x] `reader_infinite_scroll_performed`
- [x] `reader_list_loaded`
- [x] `reader_reader_tag_followed`
- [x] `reader_reader_tag_unfollowed`
- [x] `reader_site_followed`
- [x] `reader_site_unfollowed`
- [x] `reader_tag_loaded`
- [x] `reader_tag_preview`
