### ISSUE TITLE
Framework: Update out-of-date modules

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#123]
_(Edited by @ockham)_

As announced during today's Calypso Hangout, I'm asking people to help check outdated dependencies for possible vulnerabilities before we go all OSS. Let's get this done by **Tue, Nov 24th**.

*tl;dr* Check if we're even still using the package -- if we aren't, file a PR to remove it. Otherwise, check if the upstream Changelog mentions any security vulnerabilities present in the version we're using. If a fix exists in a later version, update our `package.json` to use that version. Add the PR #number next to the package entry below, and CC me (@ockham) for review. If there isn't any known vulnerability, just tick the checkbox.

More detailed instructions:

* Check if the package is still in use, or possibly obsolete.
  * I haven't yet found a reliable tool to automatically detect those.
  * Do a `grep` (or `ack`, or `ag`) for the package name. If there aren't any occurrences in the code beside `package.json`, there's a good chance you can remove it. To be sure, you might want to check the blame for the relevant line of `package.json`, and online documentation for the relevant npm module. Keep in mind that some packages provide binaries (found in node_modules/.bin/) which might be named differently from the package itself, but used inside a script or `Makefile`. Also, try removing the line from `package.json`, and run `make test` to see if tests still pass.
  * If it's really unused, file a PR with the line removed from `package.json`, cc'ing me for review.
* It it's still used: 
  * Check the package's Changelog if for any security issues fixed since the version we're using. (If they don't have a Changelog, you'll have to resort to their commits log.)
  * If there were, you obviously need to update the package version.
    * Make sure that the update doesn't break anything -- check the package's Changelog, run `make test`, and test those parts of Calypso that use the package.
    * File a PR, and cc me for review.
* If there aren't any vulnerabilities, just tick the checkbox next to the package name.

I tried to assign people that I thought were already familiar with those packages (mostly based on who last touched the package inside `packages.json`), and distributing the rest among Calypso Core and Hyperion. Feel free to trade, or ping me if you're already swamped with work, but please let's all work together on keeping the deadline.

Ping me if you have any questions.

(The following list is based on the output from `ncu` -- installed via `npm install -g npm-check-updates`)

 * [x] async                      0.9.0  →   1.5.0 @blowery
 * [ ] autoprefixer               4.0.0  →   6.1.0 @mtias
 * [ ] autosize                   3.0.7  →  3.0.14 @timmyc 
 * [ ] babel                     5.8.12  →   _latest 5.x_ @ehg 
 * [ ] babel-core                5.8.12  →   _latest 5.x_ @ehg
 * [ ] babel-loader               5.3.2  →   _latest 5.x_ @ehg
 * [ ] babel-runtime             5.8.12  →   _latest 5.x_ @ehg
 * [x] browser-filesaver          1.0.0  →   1.1.0 @timmyc 
 * [x] browsernizr                1.0.2  →   2.0.1 @mcsf _removed in #12569_
 * [x] classnames                 1.1.1  →   2.2.0 @stephanethomas
 * [x] clipboard                  1.5.3  →   1.5.5 @aduth
 * [x] commander                  2.3.0  →   2.9.0 @deBhal
 * [ ] component-classes          1.2.1  →   1.2.4 @nylen
 * [ ] component-closest          0.1.4  →   1.0.0 @nylen
 * [x] component-tip              2.3.0  →   2.5.0 @ockham  ~~Automattic/wp-calypso#395~~
 * [x] cookie                     0.1.2  →   0.2.3 @seear
 * [ ] cookie-parser              1.3.2  →   1.4.0 @seear
 * [ ] creditcards                1.1.1  →   2.0.0 @rads
 * [x] detect-browser             1.1.1  →   1.2.0 @ehg
 * [x] email-validator            1.0.1  →   1.0.3 @scruffian
 * [x] estraverse                 1.5.1  →   4.1.1 @ockham #12537
 * [ ] events                     1.0.2  →   1.1.0 @nb
 * [x] express                   4.12.3  →  4.13.3 @ockham ~~Automattic/wp-calypso#394~~
 * [x] html-loader                0.2.3  →   0.3.0 @artpi
 * [x] immutable                  3.7.2  →   3.7.5 @blowery ~~Automattic/wp-calypso#503~~
 * [x] imports-loader             0.6.3  →   0.6.5 @artpi
 * [x] jade                       1.5.0  →  1.11.0 @ockham see jadejs/jade#2170 and ForbesLindesay/transformers#51
 * [x] jed                        1.0.2  →   1.1.0 @deBhal 
 * [ ] json-loader                0.5.1  →   0.5.3 @artpi
 * [x] jstimezonedetect           1.0.5  →   1.0.6 @aduth
 * [ ] lunr                       0.5.7  →   0.6.0 @gravityrail
 * [x] minimatch                  1.0.0  →   3.0.0 @gwwar #12561
 * [x] morgan                     1.2.0  →   1.6.1 @gwwar 
 * [ ] node-sass                  3.3.3  →   3.4.2 @ockham see sass/node-sass#1269
 * [x] page                       1.6.1  →   1.6.4 @blowery
 * [ ] q                          1.0.1  →   1.4.1 @rads
 * [x] qrcode.react               0.4.1  →   0.5.1 @allendav
 * [x] qs                         4.0.0  →   6.0.0 @tug
 * [x] r-dom                      1.3.0  →   2.1.0 @tug
 * [x] raf                        2.0.4  →   3.1.0 @janm6k
 * [ ] ~~react                     0.13.3  →  0.14.3~~ _too complex for now, postponed_
 * [x] react-day-picker           1.1.0  →   1.1.4 @aduth
 * [x] react-tap-event-plugin     0.1.6  →   0.2.1 @blowery
 * [ ] rtlcss                     1.6.1  →   1.7.1 @mtias
 * [x] sf                         0.1.7  →   0.1.8 @ockham #12540
 * [x] source-map                0.1.39  →   0.5.3 @gwwar 
 * [ ] source-map-support         0.3.2  →   0.3.3 @ehg
 * [ ] store                     1.3.16  →  1.3.17 @retrofox
 * [ ] superagent                 1.2.0  →   1.4.0 @retrofox
 * [x] timeout-transition-group   1.0.3  →   2.0.1 @scruffian
 * [x] tinymce                    4.2.6  →   4.2.8 @codebykat ~~Automattic/wp-calypso#565~~
 * [ ] twemoji                    1.3.2  →   1.4.1 @bluefuton
 * [ ] walk                       2.3.4  →   2.3.9 @mtias
 * [x] wpcom-unpublished           1.0.3  →   1.0.5 ~~Automattic/wp-calypso#498~~
 * [x] wpcom-proxy-request        1.0.4  →   1.0.5 @ockham ~~Automattic/wpcom-proxy-request#10~~ ~~Automattic/wp-calypso#489~~
 * [x] wpcom-xhr-request          0.3.1  →   0.3.3 @ockham ~~Automattic/wpcom-xhr-request#10~~ ~~Automattic/wp-calypso#488~~
 * [ ] xgettext-js                0.2.0  →   0.2.1 @gravityrail
 * [x] babel-eslint               4.1.1  →   4.1.5 @aduth
 * [x] blanket                    1.1.6  →   1.2.1 @blowery
 * [x] chai                       2.0.0  →   3.4.1 @blowery
 * [ ] esformatter                0.7.3  →   0.8.1 @dmsnell 
 * [ ] esformatter-semicolons     1.1.1  →   1.1.2 @dmsnell
 * [x] eslint                     1.3.1  →   1.9.0 @aduth
 * [x] eslint-plugin-react        3.3.1  →   3.9.0 @aduth
 * [x] jsdom                      3.1.2  →   7.0.2 @blowery
 * [x] livereload                 0.3.4  →   0.4.0 @mcsf _kept at 0.3.4_
 * [ ] localStorage               1.0.2  →   1.0.3 @retrofox
 * [ ] lodash-deep                1.5.3  →   1.6.0 @ockham
 * [x] nock                      2.17.0  →   3.1.1 @aduth
 * [x] rewire                     2.3.3  →   2.5.0 @mcsf _kept at 2.3.3_
 * [ ] sinon                     1.12.2  →  1.17.2 @rralian
 * [ ] sinon-chai                 2.7.0  →   2.8.0 @rralian
 * [ ] webpack-dev-server        1.11.0  →  1.12.1 @seear
 * [ ] chrono-node     ^1.0.6  →  ^1.0.10 @retrofox
 * [x] chai-immutable  ^1.4.0  →   ^1.5.3 @blowery

**Comment by mmigdol** [comment]
Just did a little research into the livereload upgrade, as I was curious about the (innocuous) warning message I was getting while installing livereload's dependency on ws.  e.g.
```
[ws v0.4.20] Native code compile failed (but the module will still work):
[ws v0.4.20] The native extensions are faster, but not required.
```
The current version of livereload (0.4) fixes this (it uses newer version of ws that does not exhibit this issue) and appears from my testing to be backwards compatable.   So recommend upgrading it if no other reason not to.  @mcsf what do you think?

**Comment by mcsf** [comment]
@mmigdol, thanks for looking at this! I'll try to have a look at `livereload@0.4.0` before the weekend. Meanwhile, looping @blowery in since I believe you were the last to touch live reloading.

**Comment by blowery** [comment]
Does anyone use the livereload how that we have hot updates? Can we just ditch it?

**Comment by aduth** [comment]
>Does anyone use the livereload now that we have hot updates? Can we just ditch it?

I'd second removing it. Doesn't make sense for us to maintain two separate mechanisms for live updating.

**Comment by mcsf** [comment]
> I'd second removing it. Doesn't make sense for us to maintain two separate mechanisms for live updating.

:+1:

**Comment by blowery** [comment]
@mcsf @aduth #1242

**Comment by ockham** [comment]
Closing. Vulnerable packages were upgraded, and this package and version list is outdated now.

We should however come up with some strategy to stay on top of package versions and make sure there aren't any vulnerabilities.

**Comment by montogeek** [comment]
Hi! Is there any plan to upgrade the other dependencies and remove these deprecated warnings:
```
npm WARN deprecated babel-core@5.8.12: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated jade-runtime@2.0.0: Replaced by pug-runtime
npm WARN deprecated jade-lexer@0.0.9: Replaced by pug-lexer
npm WARN deprecated jade-runtime@1.1.0: Replaced by pug-runtime
npm WARN deprecated jade-attrs@2.0.0: Replaced by pug-attrs
npm WARN deprecated jade-error@1.2.0: Replaced by pug-error
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated mocha-jsdom@1.0.0: Consider jsdom-global instead. https://www.npmjs.com/package/jsdom-global
npm WARN prefer global node-gyp@3.2.1 should be installed with -g
```

I would like to help upgrading them :)

**Comment by ockham** [comment]
@montogeek Thanks for your interest in helping out, it is much appreciated! For the Babel 6 upgrade, there's PR #1515. For the other dependencies, I don't think we currently have any PRs yet, so if you'd like to file one e.g. for upgrading from Jade to Pug, I'll glady review it! (Make sure to @mention me in the PR description.)

**Comment by montogeek** [comment]
@ockham Thank you! On it :)

**Comment by brunoscopelliti** [comment]
Hi there,

This morning I'm trying to add a few unit tests on the sites-dropdown component, but I am not particularly lucky :)

I came across this error:

```bash
Error: Cannot find module 'matches-selector'
      at require (internal/module.js:20:19)
      at Object.<anonymous> (node_modules/component-closest/index.js:1:77)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:166:7)
```

That seems reasonable because, matches-selector is not listed in the package.json.

I found that mocking the blocks/site component (as many other components are doing) fixes the issue; but I don't feel happy with this solution, because I've not any other reason to want to mock it.
Other modules to avoid this error use mockery:

```js
mockery.registerSubstitute( 'matches-selector', 'component-matches-selector' );
```

Since the stacktrace mentions component-closest module I started to investigate from there... and found that component-closest@0.1.4 (that we're using) requires matches-selector in the code, but does not define it as dependency.

This is the relevant part of the package.json:

```json
{
  "name": "component-closest",
  
  "dependencies": {
    "component-matches-selector": "~0.1.5"
  },
  "browser": {
    "matches-selector": "component-matches-selector"
  },
```

Upgrading component-closest fix this particular issue, but it would be a major upgrade... so I've found this old thread (sorry for resurrecting a closed issue).

@nylen from the above lists, I see you've assigned the task of updating component-closest. Do you have any update on this? Is it something we still want to do?

I would also like to ask if is there any particular reason why we don't simply install also matches-selector?

cc. @ockham as one of the maintainers of component-closest.

**Comment by ockham** [comment]
Short answer: You should probably stick to mocking :-)

For some background, see e.g. #4072

**Comment by brunoscopelliti** [comment]
@ockham Thank you for your fast reply... 

I'll follow your advice :)
but honestly, I can't say that reading the issue has helped me to better understand the situation.

I see that `component-*` stuff are mostly legacy/unmaintained modules... Am I right? 
I've also read that `component-closest` breaks somehow the DOM encapsulation, a React component usually provides... so we shouldn't rely on it too much.

However, I don't understand why we can't upgrade `component-closest`.

Is it because it has breaking changes?
I see that the signature has changed, and potentially also the return type.

```js
// version 1.0.1
const closest = (el, selector, scope) => {HTMLElement|null}

vs

// version 0.1.4
const closest =  (element, selector, checkYoSelf, root) => {HTMLElement|undefined}
```

Also the functionality is slight different, in that the new version does not permit to skip the element provided as parameter.

I'd appreciate if you could take the time in the next days to explain this to me.
