### ISSUE TITLE
Themes: Render the Masterbar for `/design` on the server

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#1327]
Once we’ve successfully refactored the masterbar (https://github.com/Automattic/wp-calypso/issues/1326), we should render it on the server. Rendering this small piece allows us to focus on the framework aspects of SSR, rather than getting bogged down in dependencies, routing and layout issues. 

The goal of this should be to have a solid base to build upon. 

TODO:
- [x] Smoke tests for dependency errors & ~~checksum checking for React tree reconciliation~~(https://github.com/Automattic/wp-calypso/pull/2240)
- [ ] ~~Restart server on shared/server file change (https://github.com/Automattic/wp-calypso/pull/848)~~
- [x]  renderToString() on `/design` (#2087)
- [x] Profile the `renderToString` — specifically we’re looking for how long the event loop is blocked for, and how ~70 concurrent requests are handled, compared to other logged-out routes. Note that profiling should happen in non-dev mode(!) (#2518)
- [x] Enable in staging (#2613)
- [x] Enable in production (https://github.com/Automattic/wp-calypso/pull/2735)

**Comment by ockham** [comment]
@ehg We'll need to temporarily move at least the logged-out masterbar and layout to `shared/`, right?

**Comment by ehg** [comment]
> We'll need to temporarily move at least the logged-out masterbar and layout to shared/, right?

Yep, we should move the stuff we need at the component directory level, e.g. `layout/`, then migrate back when we've got a universal `app` folder.
