### ISSUE TITLE
Framework: remove rest of sites-list uses

### ISSUE THREAD

**Issue by mtias** [Automattic/wp-calypso#13279]
Usually cases `sitesList.getSite()` or `sitesList.get()` which are replaced by `getSite` and `getSites` selectors.

Depends on #13094.

- [x] `client/components/site-selector-modal/index.jsx` ( @ockham, #13293  )
- [x] `client/blocks/daily-post-button` ( @jorgefilipecosta, #15374 )
- [x] `client/blocks/plan-storage/docs/example.jsx` ( @tyxla, #14114 )
- [x] `client/blocks/reader-share` ( @jorgefilipecosta, #15416)
- [x] `client/blocks/site-icon/index.jsx`  ( @jorgefilipecosta, is already not dependent on sites-list. Some code relies on passing fake site objects with just the icon there)
- [x] `client/components/plans/plan-price/index.jsx`
- [x] `client/devdocs/design/blocks.jsx` ( @tyxla, #14376 )
- [x] `client/layout/masterbar/drafts.jsx` ( @mtias, #13274 )
- [x] `client/lib/media/validation-store.js` (@jorgefilipecosta #15641)
- [x] `client/lib/signup/step-actions.js` ( @kwight, #14562 )
- [x] `client/me/account/main.jsx` ( @ockham, #13293 )
- [x] `client/me/billing-history/controller.js` ( @tyxla, #13330 )
- [x] `client/me/notification-settings/controller.js` ( @rodrigoi, #13849 )
- [x] `client/me/profile-links-add-wordpress/index.jsx` ( @tyxla, #14758 )
- [x] `client/me/purchases` ( @mtias @gziolo #13247)
- [x] `client/my-sites/plugins/` (@jorgefilipecosta #15767)
- [x] `client/my-sites/pages/controller.js` and `client/my-sites/pages/helpers.js` ( @jblz #13317 )
- [x] `client/my-sites/domain-tip/docs/example.jsx` ( @tyxla, #14251 )
- [x] `client/my-sites/post-selector/docs/example.jsx` ( @tyxla, #13861 )
- [x] `client/my-sites/resume-editing/index.jsx` ( @mtias, #13270 )
- [x] `client/my-sites/stats/controller.jsx` ( @tyxla, #13864 )
- [x] `client/my-sites/upgrades/controller.jsx` (@gziolo #13859)
- [x] `client/state/wordads/approve/` ( @tyxla, #13856 )

**Comment by lamosty** [comment]
Closing this as all the `sites-list` uses are removed! 🚀
