### ISSUE TITLE
Free Trials: Implement free trial expiration

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wp-calypso#1377]
The following day numbers are not final.

Day 0: User adds a 14-day free trial with a domain
Day 14: The trial is set to expire. If the user hasn't purchased the plan, they receive a 3 day extension.
Day 17: If the user hasn't purchased the plan, it is removed from their site. 

- [x] Change free trials to expire after 17 days.
- [x] Show the trial as expiring in 14 days (**_not_** 17 days). #1471 
- [x] Remove the plan subscription after 17 days.
- [x] Update the free trial code to not include a domain credit. #1522 
- [x] When the user purchases the plan we should add the domain credit. #1522

**Comment by scruffian** [comment]
Right now the domain isn't cancelled when the free trial is removed.

**Comment by fabianapsimoes** [comment]
@scruffian @matthusby as we'll no longer include domains in free trials, can you review what's been accomplished so far and close this issue if it makes sense?

**Comment by scruffian** [comment]
The remaining items in this issue will be fixed by #1522

**Comment by fabianapsimoes** [comment]
>  Show the trial as expiring in 14 days (not 17 days). 

This one will be fixed in #1471 though, not #1522.

**Comment by scruffian** [comment]
Closing since #1471 and #1522 are closed.
