### ISSUE TITLE
Add payments setup todo to store setup

### ISSUE THREAD

**Issue by belcherj** [Automattic/wp-calypso#13804]
As a user when I am setting up a store I would like to have an option that takes me to a page where I can setup payments.

Acceptance Criteria
- [x]  I should see payments icon
- [x] I should see text describing payment setup
- [x] I should see a button that says "Payment Setup"
- [x] Payment setup button should take me to Payments settings page
