### ISSUE TITLE
Free Trials: do not offer domains in free trials

### ISSUE THREAD

**Issue by fabianapsimoes** [Automattic/wp-calypso#1484]
We won't offer domains as part of the free trial offer (p6qnuF-129-p2). This means there are a few things we need to ensure:

- [x] free trials signups from `/start` can't offer domains (#1374).
- [x] a domain credit isn't available for users on free trials. (#1522)
- [x] users who paid to keep their plan after/during the trial should get their domain credit. (#1522)

**Comment by fabianapsimoes** [comment]
Related to #1522.

**Comment by drewblaisdell** [comment]
The final issue was closed by #1787.
