### ISSUE TITLE
Activity log: Connect banners to state

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#15260]
Success, progress and error banner should be connected to state.

- [x] Show progress info in banners
- [x] Try again from banners
- [x] Links to site #15786
- [x] Links to documentation #15647
- [x] Dismiss progress from banners #15555 

Follow up for #15259
