### ISSUE TITLE
Store Orders: Create an order

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#15679]
Create an order:

- Take customer information
- Add items
- Choose shipping method
- Add payment

Roadmap

- [x] Finish edit roadmap — See "Edit order" #15681
- [x] Swap existing Create Order page for an empty "edit order" page, make sure empty states prompt for input (products, customer info) #20665
- [x] Enable saving for a new order #20758
- [x] Payments: "Resend invoice" button
  - [x] Needs API to send an email https://github.com/Automattic/wc-calypso-bridge/pull/21
  - [x] Add button to header, discussion in #20794, PR #21306, #21403
- [x] Show coupons already on an order #20929
- [x] UI fixes #21374
- [x] Add tracks for "New"/"Save"/"Cancel" buttons like in edit

Next iteration

- [ ] Coupons
  - [ ] Create API endpoint for managing coupons woocommerce/wc-api-dev#78
  - [ ] Remove coupons from an order 
  - [ ] Add "Apply Coupon" field, design in #20741
- [ ] Search existing customers when entering email address, pre-fill details if exists
  - [x] Create redux state etc for `customers` endpoint. #20848
  - [ ] Update the customer details create component to offer a "customer search" #20876
- [ ] Take payments in the order screen
- [ ] Select a real shipping method, let that set shipping cost
- [ ] Improve UX of order creation flow #21795

**Comment by ryelle** [comment]
@jameskoster @kellychoffman How do you see the payment process working? It looks like this isn't even addressed in wp-admin. This is from the mockup, but I don't think we can take credit cards directly, especially not in a way that pays out to the user.

<img width="711" alt="screen shot 2017-09-05 at 11 48 18 am" src="https://user-images.githubusercontent.com/541093/30070000-2597630c-9230-11e7-9677-f41e46e35ad5.png">

**Comment by jameskoster** [comment]
For credit cards the idea was that it would basically work the same way as the checkout on the frontend. This was based around the user story;

> A customer has contacted us and wants to place an order and make payment over the phone

So they would collect the card details from the customer directly. For other situations the store owner would just choose the 'Pay later' option.

Honestly I'm not sure if this is behaviour we should encourage due to the security implications. Perhaps we can discuss this in our call today.

Alternatively when the 'new order' email is sent to the customer, we could include a link for them to complete payment. It's less convenient but more secure.

**Comment by ryelle** [comment]
@jameskoster @kellychoffman What should happen as soon as a user saves a new order? Do we give them a notice and leave them on this page, or try to shuffle them over to the single order view immediately?

If they need to make a change, the edit screen is very different from the create screen, that might be confusing. Would there maybe be benefit in looking at using the new edit order mockup for creating an order, too?

**Comment by kellychoffman** [comment]
When the user saves a new order, we should bring them to the single order view with a success message that says: "Order created successfully. [Edit order](#) [View all orders](#).

> Would there maybe be benefit in looking at using the new edit order mockup for creating an order, too?

Yes, I do. I'll discuss with @jameskoster.

**Comment by ryelle** [comment]
@jameskoster @kellychoffman I've got a new base page for "New Order":

<img width="1172" alt="empty" src="https://user-images.githubusercontent.com/541093/33784389-b548f84c-dc2e-11e7-96d2-8d1a7c008957.png">

I've updated the description here with the work I have planned, but I have a few things tagged "needs design":

1. an Apply Coupon field– we could also port this over to the edit order screen as well.
2. How should the customer get the payment to the store owner? We can display a direct link to the payment page, and/or offer the option to send the "Invoice/Order Details" to the customer via email  which looks pretty janky by default (the "[Store]" is my store title, it's not a broken placeholder):

<img width="613" alt="screen shot 2017-12-08 at 3 56 31 pm" src="https://user-images.githubusercontent.com/541093/33784933-c7e1ad58-dc30-11e7-963a-dce9fc429abe.png">


Lastly... some shipping cost thoughts, @Automattic/hydra might be helpful here:

- is it possible to offer the same localized shipping options that would be offered to the customer on checkout? Would need to filter shipping zone locations by customer shipping location, then fetch the method info from there?
- is it possible to pull from the WCS shipping label costs to automatically charge the exact shipping amount to the customer, before an order is fully created? We would have a list of real products, source and destination address... without loading the whole label dialog, can we just return a list of shipping options + costs?

**Comment by jameskoster** [comment]
For adding a coupon I think a new button alongside `Add Product` and `Add Fee` will be suffice. It should open a modal with a coupon lookup component - similar to the product lookup. I'll work on a design for that now.

> How should the customer get the payment to the store owner? We can display a direct link to the payment page, and/or offer the option to send the "Invoice/Order Details" to the customer via email which looks pretty janky by default (the "[Store]" is my store title, it's not a broken placeholder):

Yeah, that `please use the following link: pay` isn't the best phrasing. We should clean that up in core. The first sentence is fine I think, the CTA just needs to be clearer. 

> An order has been created for you on Store.
> [Pay for this order]

In general I think the email is useful though and should be kept. 

I'm not sure about the quick-link to the payment page. I wonder when that would be more useful than the email? I suppose if you're taking the order over the phone and want to text it to the customer or something? Either way, that link can only be created after the order has been "published" so perhaps we should just add an option to `copy` the payment link in the "order created" notification (and add it to the activity log). Keen to hear more thoughts on this.

**Comment by ryelle** [comment]
Thanks for the issues! Nice to see the email one already has a fix 😄 The design for `+ coupon` looks great.

> add an option to copy the payment link in the "order created" notification (and add it to the activity log)

+1 for adding it to the activity log. We're loading a lot into that success notice, though - [right now](https://github.com/Automattic/wp-calypso/issues/15679#issuecomment-332060109) it's set to have two other actions:

```
Order created successfully. [Edit order.] [View all orders.]
```

(though revisiting that, we can probably remove the edit link since we have the edit button right under where the notice appears)

Since you end up on the single-order view for the order, maybe we could use a banner notice across the top of the page, maybe with another button that would trigger the invoice email? like this

```
This order is unpaid, send [the customer payment page] to the user. [email invoice button]
```

**Comment by jameskoster** [comment]
Hmm, I'm gonna question the benefit of including the "edit" and "view all orders" links in the notification. I agree editing feels like overkill. Viewing all orders is just a click away in the main nav. 

I think it makes sense to link back to all orders when _editing an existing order_ because the task at hand is probably fulfilment, after-which you'd want to go and work on the next order. But with manual order creation the next step will be concluding payment...

The downside to including it in the notification however is that once it's been dismissed it could be frustrating to find that link again.

Here's another idea; how about, for any order that is `Payment pending` we include another action alongside the "Edit Order" button to "Copy payment link"? With a better label of course.

**Comment by ryelle** [comment]
I've moved the payment discussion to its own issue: #20794
