### ISSUE TITLE
Store Orders: Edit an existing order

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#15681]
A user can edit an existing order.

-----------------

Roadmap:

- [x] Infrastructure for editing
- [x] Enable edit & save order buttons #18510
- [x] Customer details form: email, name, phone number, address #18579
- [x] Product search bar #18343, #19531
- [x] Update OrderDetailsTable to allow quantity change #19047 
- [x] Add fee lines to the single order view #18729 
- [x] Delete products from an order #19056
- [x] Dialog to add fees #19141 
- [x] Add products to an order #19243
- [x] Update shipping #19641
- [x] Make sure editable sections are based on order status (products can change until paid, address can change until shipped) #19707 
- [ ] Open to production #20254

-----------------

Editing tasks in wp-admin:

- Change order date
- Change order status (already possible)
- Update customer shipping address
- Update customer billing address
- Add products
- Add fees
- Add shipping charge
- Discounts can be given by negative fees, but I can't seem to add a coupon to an existing order

Dev requirements:

- State to track edits
- Action to save edits
- UI for editing order

**Comment by ryelle** [comment]
@kellychoffman @jameskoster I'm almost finished with order editing, and the last part is making sure the things a user can edit make sense with the status of the orders. So I'm thinking that looks like:

| Status          | Add products & fees | Edit addresses | Refundable | Add notes |
| --------------- |:-------------------:|:---------------------:|:----------:|:---------:|
| Pending payment |           X         |           X           |     *      |     X     |
| On-Hold         |           X         |           X           |     *      |     X     |
| Processing      |                     |           X           |     X      |     X     |
| Completed       |                     |                       |     X      |     X     |
| Cancelled       |                     |                       |            |     X     |
| Refunded        |                     |                       |            |     X     |
| Failed          |                     |                       |            |     X     |

*&nbsp;Pending & On-Hold orders can be marked as paid, which changes the status.

Once an order is finished (the last 4 statuses), the only thing you can do in the edit mode is change the order status. Does this sound correct?

**Comment by kellychoffman** [comment]
This sounds correct on my end, @jameskoster does this sound right to you?

**Comment by jameskoster** [comment]
Yup, looks right to me.
