### ISSUE TITLE
Media: expand external media support

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#16536]
For the future:

- [x] **Guided tour** if user manually inserts a Google Photo

In progress:

Finished
- [x] ~~#17162 create transientId before uploading process~~
- [x] ~~#17007 tag transient images with data-istransient attribute~~
- [x]  ~~Improve access & improve search. Add a dropdown to the media library and keep the search field expanded. Also, adds it to the media page along with a copy button~~
- [x] ~~#16612 Add dropdown~~
- [x] ~~#17185 **Connect to Google inline**. Rather than bounce the user to the sharing page, do it all in the media library~~
- [x] ~~#17181 Move keyring request~~
- [x] ~~#17178 ES6 part 1~~
- [x] ~~#17175 ES6 part 2~~
- [x] ~~#17176 ES6 part 3~~
- [x] ~~ES6ify media library #17083~~
- [x] ~~External auth lib #16862~~
- [x] ~~search-url mixin replacement #17127~~
- [x] ~~**Refresh external data** - if someone uploads photos to the external source we don't have a way for the user to refresh their library in Calypso #16533~~
- [x] ~~**Refactor the sharing page**. Google Photos/Eventbrite don't really belong there. This may be a bigger task and can be raised as another issue. Note that the inline connect (below) may be a better solution for the moment~~ marked as complete as #16829 should cover us
- [x] ~~Fix filter menu on mobile #16221~~
- [x] ~~**Show an empty library message**. Helpful if the user hasn't got any external data yet #16322~~
- [x] ~~Enable on desktop #16220~~
- [x] ~~Show an **error message** if the API returns an error. The media library has no error handling while retrieving data, and will just endlessly flash the loading placeholder #16621~~
- [x] ~~~#16863 - get service by name~~~
- [x] ~~**Copy-and-insert** in one action. That is, when viewing external media the blue button should copy and insert directly into the post rather than copy to the WP library and then a second click inserts into the post.~~
  - [x] ~~Fix transient behavior https://github.com/Automattic/wp-calypso/issues/16919~~
  - [x] ~~Implement changes in the modal to insert the image directly in the editor. https://github.com/Automattic/wp-calypso/pull/17384 https://github.com/Automattic/wp-calypso/pull/17386~~
