### ISSUE TITLE
Accessibility: visual enhancements

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-calypso#16699]
This will be a larger ticket to cover a lot of issues we can improve. I will link them here. Props @drw158 for suggestion. Starting with the reader for this makes a lot of sense, so that is my focus.

- [ ] High contrast scheme: https://github.com/Automattic/wp-calypso/issues/457
- [ ] Allow users to set their own text size : https://github.com/Automattic/wp-calypso/issues/16696
- [ ] Allow users to select their own font: https://github.com/Automattic/wp-calypso/issues/16697
- [ ] Allow users to change the background color: https://github.com/Automattic/wp-calypso/issues/16698

A possible interface for this could be:

![reading-settings4](https://user-images.githubusercontent.com/253067/28726102-c8b34d18-73b7-11e7-8ad0-57d0a3ec0af1.png)

Work being done here could enable some of this: https://github.com/Automattic/wp-calypso/pull/15731
