### ISSUE TITLE
Migrate Sites Request To the data-layer action plan

### ISSUE THREAD

**Issue by jorgefilipecosta** [Automattic/wp-calypso#17376]
Watching by the number of uses of query sites component, requesting sites is one of the most common types of requests. 
Right now sites are being requested in 2 ways: action thunk and in sites-list with polling (and then sync back to redux).
With the deprecation of sites-list, it would be good to consolidate site requests in the data-layer.
This allows sites-request to take advantage of current and future feature of data-layer e.g. retries, ignore duplicate requests, freshness etc...
Some pull requests were tried that move that just move the requests to the data-layer, but we got the idea that moving the old paradigm to the data-layer is not enough. We should not be tracking manually if requests are in progress or not, and manually dispatching these kinds of actions. We should let data-layer handle for everything related to the request for us.
So this action plan removes the request flags and actions from the for the SITES_REQUEST action. All usages of this flag are updated to Instead of checking if sites are requested or not we just check the state if they are loaded or not.
We trust that if the components set the need for sites data, data-layer will be responsible for requesting them and keeping them fresh (freshness part is being worked right now).

**Action plan:**

- [ ] Change the initial state of site items to null (https://github.com/Automattic/wp-calypso/pull/17364).
- [ ] Create a hasLoadedSites selector (checks if site items are different from null) (https://github.com/Automattic/wp-calypso/pull/17365).
- [ ] Replace isRequestingSites usages (21) with hasLoadedSites. Involves testing really well the changes (https://github.com/Automattic/wp-calypso/pull/17373, https://github.com/Automattic/wp-calypso/pull/17374, https://github.com/Automattic/wp-calypso/pull/17375)
- [ ] Create hasLoadedMissingSites to replace isRequestingMissingSites. The new selector just replaces the condition !! state.sites.requestingAll with our new selector hasLoadedSites. isRequestingMissingSites has only one usage. Not a big change.
- [ ] Remove the requestingAll flag, the 2 actions changing the flag, and selectors isRequestingSites, isRequestingMissingSites.
- [ ] Finally, move sites request to the data-layer (https://github.com/Automattic/wp-calypso/pull/17213).

**Comment by jorgefilipecosta** [comment]
Closing there is no work being actively done on this task.
