### ISSUE TITLE
Port Countries List to Redux

### ISSUE THREAD

**Issue by delputnam** [Automattic/wp-calypso#18095]
The Countries List implemented in `client/lib/countries-list/index.js` needs to be added to Redux and then each component that uses this list should be reduxified. 

If you work on this issue, please add your PR number to the right of each list item below.

### 1. Add Country List to Redux

- [x] Add Country List to Redux (PR: #18098)

### 2. Replace the current CountryList in the following files:

- [ ] `client/blocks/credit-card-form/index.jsx` (PR: #25223)
- [ ] `client/me/security-2fa-sms-settings/index.jsx` (PR: #25223)
- [ ] `client/me/security-account-recovery/edit-phone.jsx` (PR: #25223)
- [ ] `client/my-sites/checkout/checkout/domain-details-form.jsx`
- [ ] `client/my-sites/checkout/checkout/secure-payment-form.jsx` (PR: #25223)
- [ ] `client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx`

### 3. Once all of the above uses of `client/lib/countries-list` have been replaced:

- [ ] Remove `client/lib/countries-list` (PR: #25223)

**Comment by samouri** [comment]
Drive by:

In order to make a GH Checklist you need to format it like:
```
- [ ] item 1
- [ ] item 2
```

**Comment by delputnam** [comment]
Thanks @samouri!

**Comment by danny-wieser** [comment]
@delputnam: I've created a project here: https://github.com/Automattic/wp-calypso/projects/45, in an attempt to wrangle all the existing Flux stores into Redux in one place.  I believe the country list is not Flux, but I'm wondering if it's worthwhile to add it, just to track overall movement to the global state tree?

**Comment by flootr** [comment]
closing as this seems to be done already. there's no `lib/countries-list` store and the referenced files don't mention any 
flux stores.
