### ISSUE TITLE
Reduxify: Migrate lib/ads stores

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-calypso#18222]
Just adding a task to track cleanup of the current Flux stores in client/lib/ads to Redux

- [x] migrate earnings-store
- [x] migrate settings-store - #39800, #39802
- [x] migrate tos-store (appears to not be used?) #26130
- [x] remove stores after migration is complete - #39803
- [x] investigate if utils are required for external usage

**Comment by blowery** [comment]
TOS Store removal in https://github.com/Automattic/wp-calypso/pull/26130

**Comment by tyxla** [comment]
I'm working on the ads settings store migration in #39800, #39802 and #39803.

**Comment by tyxla** [comment]
The above have been merged.

It appears that the `lib/ads/utils` are used externally. While they could be converted to selectors, I don't see the immediate need for that at this point. 

I'm closing this one as it's finished.
