### ISSUE TITLE
Jetpack services: Plans page

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#18266]
We need to extract the jetpack connect plans page from the general flow and make it work on its own. ATM, if you try to access directly to the jpc plans page while unconnected, you are being redirected to the JPC first step. This shouldn't be like this, you should be able to see and select a plan, independently of if you are connected or not.

![image](https://user-images.githubusercontent.com/1554855/30852538-606f3716-a2ac-11e7-9e71-3978ed850207.png)

Pretty much, what we need is a new route that renders the current plans page, but:

- If the user is logged and we are passing a site slug, and the site is in their sites list: render the plan list
- If the user is logged and we are not passing a site slug, render the plan list
- If the user is logged and we are passing a site slug, but the user doesn't have that site connected -> error state TBD
- If the user is not logged, and we are no passing a site slug. render the plans page (maybe with a prompt to login / sign in?)
- If the user is not logged and we are passing a site slug: login page

This new route will also be able to receive a 'flow' param that will signal which flow we are in, and that will affect the result of the 'action' (what happens when the user clicks one of the plans buttons).

This action will be, in all the cases, a redirection to another url. This url will depend on several conditions:
- Current flow
- User being logged or not
- Site slug being selected or not.

For this first version, we will handle only the standard flow, which:

1- If we have a site slug, we will redirect the user to the checkout page, either they are logged or not
2- If we don't have a site slug and the user is not logged, we will redirect the user to /jetpack/connect/, passing the selected plan as a querystring parameter
3- If we don't have a site slug and the user is logged, maybe if the user has any jetpack site already connected we could show a site selector ... and if they don't want to apply the plan to any of those sites, we will fall back to 2.

**Todo**
- [x] redirect to `/plans` instead of `/my-plan` #20522
- [x] For `/jetpack/connect/plans` (without site), render `plans-landing.jsx` #20562
- [x] For logged-out with site, redirect to login #20564
- [x] Handle `/jetpack/connect/plans/:site` where `site` is unknown/not-connected #20923
- [x] Login [currently broken](https://github.com/Automattic/wp-calypso/pull/20498#issuecomment-352492739) #20944
- [ ] We may want to tweak the "Your site is now connected..." title in some scenarios, or have a universal title
- [x] Add a loading placeholder #20953

**Comment by seear** [comment]
**Todo**
- [ ] redirect to `/plans` instead of `/my-plan` #20522
- [ ] For `/jetpack/connect/plans` (without site), render `plans-landing.jsx`
- [ ] For logged-out with site, redirect to login

**Comment by seear** [comment]
I took a good look at consolidating `plans-landing.jsx` (which we render for `/jetpack/connect/store`) and `plans.jsx`, but my view is that this would make the single component too complex. Given that over time more complexity will be added, I suggest we continue with two components: one for without a site and one for with a site.

**Comment by sirreal** [comment]
> I suggest we continue with two components: one for without a site and one for with a site.

Sounds good to me 👍 

Simply differentiating names and some descriptive comments in the files would go a long ways towards clarifying when they're used, for example `store` and `plans`.

**Comment by sirreal** [comment]
> For /jetpack/connect/plans (without site), render plans-landing.jsx

Do we need to stay at this route if we don't have a site, or can we redirect to `/jetpack/connect/store`? Could make my last comment irrelevant 🙂

**Comment by seear** [comment]
> Do we need to stay at this route if we don't have a site, or can we redirect to /jetpack/connect/store?

I suggest redirect as a first step. This issue suggests having everything unified under one route, so @johnHackworth can comment later as to how important that will be.

**Comment by seear** [comment]
Found an issue while testing this—going through two-factor login loses the redirect url so we don't come back to the plans. Will add to the todo list.

**Comment by seear** [comment]
> Found an issue while testing this—going through two-factor login loses the redirect url so we don't come back to the plans. Will add to the todo list.

Actually this seems to be a new issue affecting any login:
https://github.com/Automattic/wp-calypso/pull/20498#issuecomment-352492739

**Comment by sirreal** [comment]
I believe the only bullet left on this list is better handled in an upcoming project:

> We may want to tweak the "Your site is now connected..." title in some scenarios, or have a universal title

Shall we close this as complete @johnHackworth?

**Comment by sirreal** [comment]
✅ Complete.
