### ISSUE TITLE
Comments: post specific view

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18315]
Let's add a post specific view for moderating comments, this is very handy for individual authors who need to monitor comments on their posts only.

- [x] We'll need to update the route structure to be able to handle this #18330
- [x] Update the comments-tree endpoint with enough information to do this in the v1.1 update #17546 
- [ ] Implement the post specific view based on p3fqKv-5W1-p2 (This issue)
- [ ] Link to this view from various places #18332
- [x] Add a nudge screen to update Jetpack. (#18965)

![comments-m3-i3-post-view](https://user-images.githubusercontent.com/1270189/31955178-7c3155c8-b89c-11e7-949d-4ff860272cd0.png)

![comments-m3-i3-post-view-comment-expanded](https://user-images.githubusercontent.com/1270189/31955182-7f63e8a0-b89c-11e7-9480-26b33f9d0cd8.png)

![i3-mobile-post-view-commen-expanded](https://user-images.githubusercontent.com/1270189/31955200-8e859374-b89c-11e7-8dce-924a1bb2a09f.png)

![i3-mobile-post-view-commen-expanded-read-more](https://user-images.githubusercontent.com/1270189/31955212-99074612-b89c-11e7-8835-761a4e9bc737.png)

**Comment by vindl** [comment]
> Update the comments-tree endpoint with enough information to do this in the v1.1 update #17546

Do we still need a post specific endpoint for this (or additional comments-tree parameter), or did we decide to just fetch everything and filter the state for given `post_id` (could run into issues with cut-off)?

I'm pretty sure we discussed this update before but I can't seem to find a separate issue or PR for it.

**Comment by gwwar** [comment]
@vindl We should be able to create a selector for this view. We can revisit the endpoint work if we'd like to cut down the response size when folks visit this view with an empty cache.

**Comment by kwight** [comment]
Does anyone think this view could use some sort of excerpt of the post maybe? We give the title and no other context.

**Comment by gwwar** [comment]
> Does anyone think this view could use some sort of excerpt of the post maybe?

Potentially. The current post comments view in wp-admin also doesn't handle that, so we'd need to think of ways of providing more context without taking up too much space.
<img width="556" alt="screen shot 2017-10-27 at 4 45 26 pm" src="https://user-images.githubusercontent.com/1270189/32128847-58b4f6da-bb36-11e7-9e7a-cdc9b9b66759.png">
