### ISSUE TITLE
Comments: comment specific view

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#18321]
We need a Calypso comment specific view that is used for two cases:
1. As an author or admin, I click "Edit" on comment from my site. This currently opens wp-admin, but we should have a comment specific view in Calypso that opens in edit mode. ( related #17221 )
2. As an author or admin, I click on the call to action in the moderation email, with a specific action like approve or trash or mark as spam. Similarly we should have a comment specific view that performs that action and does not open in edit mode. ( related #19110 )

### Technical Tasks:
- [x] Visiting `/comment/{ siteFragment }/{ commentId }` will render the ui and comment permalink ( #19773 )
- [ ] Comment Audit history is added to the above view. ( #19772 )
- [x] Visiting `/comment/{ siteFragment }/{ commentId }?action={ approve | spam | trash | delete }` (#19774) will perform the related action and render the comment view in the first task
- [x] Update the edit link (#17221)
- [x] Update the moderation email links ( #19110 )

![comments-m3-i3-comment-view-edit-mode](https://user-images.githubusercontent.com/1270189/31955347-f6d64036-b89c-11e7-8d81-26a9a89ba40b.png)

![comments-m3-i3-comment-view](https://user-images.githubusercontent.com/1270189/31955353-faaae324-b89c-11e7-8b80-148a6d0e3cfa.png)

![i3-mobile-comment-edit](https://user-images.githubusercontent.com/1270189/31955356-fd207d12-b89c-11e7-8228-76feb3a10210.png)

So if we visit our site for example https://gwwartest.wordpress.com/2017/09/15/hello-world-11/comment-page-1/#comment-149, and click on edit. This currently takes us to wp-admin n/comment.php?action=editcomment&c=149

![i3-mobile-comment-view](https://user-images.githubusercontent.com/1270189/31955362-01695eac-b89d-11e7-904d-0d69df1c244f.png)

<img width="596" alt="screen shot 2017-10-24 at 1 36 23 pm" src="https://user-images.githubusercontent.com/1270189/31966828-cd324a6c-b8c0-11e7-94a3-0245c66f4cdd.png">

**Comment by gwwar** [comment]
Going to reopen this as a main tracking issue.

**Comment by gwwar** [comment]
going to close this out, since we can add history as an enhancement
