### ISSUE TITLE
Me: Two-Step: Allow users to 'Switch to a New Device'

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#19]
Currently:
When a user gets a new mobile device they must 'disable' and 'enable' 2fa in order to switch phones. That flow is not intuitive to a user. They may not understand that disabling is required. They may (just maybe) continue carrying around their old phone just for auth. They may disable and never re-enable.

Hopefully:
We can implement a 'switch to a different device' option that allows users to 'update' their 2fa settings without disabling 2fa.

Comment:
Hi all,

I've been playing with Google and Dropbox 2FA switching / editing mechanism &mdash; Facebook and Twitter have slightly different flow and depend on their mobile apps &mdash; and the simplest approach, IMO, is Dropbox. When 2FA is enabled in Dropbox, user can edit the 2FA setting. The 2FA edit screen and flow are basically the same as initial setup of 2FA &mdash; user chooses how to retrieve the verification code (sms or app).
## UI proposal

Using the same edit pattern as Dropbox allows us to reuse existing `security-2fa-setup` component. Followings show how 2FA edit applied in Calypso:
1. When 2FA is enabled, the edit button appears in Two-Step Authentication card inlined with disable button.
   ![image](https://cloud.githubusercontent.com/assets/7233112/11217404/200881c8-8d1e-11e5-9319-779c88f24e84.png)
2. Clicking edit will reveals edit progress which basically the same as initial setup.
   ![image](https://cloud.githubusercontent.com/assets/7233112/11217406/23b6b9b6-8d1e-11e5-9266-a8b23044adbf.png)

Any thought for the UI?
## Code consideration

The `TwoStep` component renders `Security2faDisable` when user has 2FA enabled. The `Security2faDisable` renders the status of 2FA setting and components related to 2FA disabling processes. Now edit 2FA setting flow is introduced. The name `Security2faDisable` doesn't fit to the context anymore as edit and disable buttons are rendered in the same component. I propose the name `Security2faEdit`. Basically the disable related functions stay the same, it only introduces new state &mdash; `editing`. This state is used to indicate whether to prompt disabling section or editing section.

When state `editing` is `true`, `Security2faEdit` uses 2FA setup component, `Security2faSetup`, that renders screenshot no. 2. From there, we need to adjust `Security2faSetup` component to bypass `initial-setup` state by introducing new prop `initialStep`.
## Todos
- [x] Implement `Security2faEdit`. This component replaces `Security2faDisable`.
- [x] Allows opt-in `step` state in `Security2faSetup` by introducing new prop `initialStep`. The initial state of `step` should be `this.props.initialStep || 'initial-setup'`. Another new prop is `onCancelSetup` &mdash; which allows `Security2faEdit` to get back to initial state rather than to `Security2faSetup`'s `initial-setup` step.
- [ ] Import styles, in `assets/stylesheets/_components.scss`, from `Security2faEdit` and remove styles from `Security2faDisable`.
- [x] Update READMEs mentioning `Security2faDisable` component &mdash; replaces it with `Security2faEdit`.
- [x] Update `TwoStep` component to change the child component to `Security2faEdit` instead of `Security2faDisable`.
- [ ] The REST API endpoints `/me/two-step/app-auth-setup/` always returns error if current user's 2FA is enabled with JSON response:
  
  ``` json
  {
     "_headers": {
         "Content-Type": "application/json",
         "Date": "Sun, 31 May 2015 15:39:21 GMT"
     },
     "error": "two_step_already_enabled",
     "message": "Two factor authentication is already enabled for the current user.",
     "name": "TwoStepAlreadyEnabledError",
     "statusCode": 400
  }
  ```
  
  I believe this is intended &mdash; from [wpcom-undocumented](https://github.com/Automattic/wp-calypso/blob/master/client/wpcom-undocumented/index.js) and [two-step-authorization](https://github.com/Automattic/wp-calypso/blob/master/client/lib/two-step-authorization/index.js) it seems no function exposed to deal with updating 2FA settings.

**Comment by lancewillett** [comment]
This came up in an internal discussion today:

> Someone noted that while some other services like Google give you to option to change devices, WP.com makes you completely disable 2FA which leaves your account temporarily less secure and invalidates your backup codes. Any plans to introduce the “Change “Device” functionality?

**Comment by simison** [comment]
Still an issue.

**Comment by simison** [comment]
Still an issue:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/87168/48959941-c594b400-ef71-11e8-870b-5c13fa959620.png">

A bit clearer today now with a link to https://en.support.wordpress.com/security/two-step-authentication/#moving-to-a-new-device
