### ISSUE TITLE
Me: Security: 2FA: Flux Refactor

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-calypso#20]
### Background

Per comment:

> I would also entertain moving some of this “store” logic out of the 2fa components and into a Flux store now that we are doing Flux implementation (we weren’t doing Flux when the 2fa components were originally written.)
#### Reason to refactor to Flux

There are good materials out there explaining benefits of using Flux, however one of my concern when diving into 2FA related components for the first time is components dependencies &mdash; for instance if component need to update user settings and application password data then instances of `lib/user-settings` and `lib/application-password-data` will be passed as props. Using this approach makes the responsibilities of view get doubled because it needs to know how to fetch data, how to update data, and what data to render.

With Flux, hopefully we could move those dependencies into action and store so view only knows what data to render. This also means flow of data becomes explicit and easy to understand thus increasing the locality of bugs (imagine you've three components depend on `client/lib/two-step-authorization` and there's change on REST API that affects `client/lib/two-step-authorization`. Now you've to hunt down those three components).
### Todos

Based on Flux approach in Plugins, this issue will serves as parent ticket of all PRs of 2FA Flux refactor. Ideally each todo item should have its own PR and should be marked as done when PR is accepted and merged.
- [ ] Create `TwoStepActions` in `client/lib/two-step/actions.js`. Actions are good starting point and will makes the rest easy to understand. Followings are defined action types based on 2FA functionalities:
  
  | Action Type | Description |
  | --- | --- |
  | `UPDATE_2FA_SETTINGS` | This action is created from view, i.e. when user clicks either "Verify via SMS" or "Verify via App". The payload for this action should includes: flow (which value is either "sms" or "scan") and phone settings (country code and phone number). |
  | `RECEIVE_UPDATED_2FA_SETTINGS` | This action is created by server &mdash; dispatched inside `userSettings.saveSettings` callback. The payload is error that's passed as callback argument. |
  | `REQUEST_APP_AUTH_CODES` | Request OTP Auth URI for app and time code. Under the hood the store calls `twoStepAuthorization.getAppAuthCodes`. |
  | `RECEIVE_REQUESTED_APP_AUTH_CODES` | This action is created from server &mdash; dispatched inside `twoStepAuthorization.getAppAuthCodes` callback. The payload includes error and data that's passed as callback arguments. |
  | `REQUEST_SMS_CODE` | Request to send SMS code. Store will handle this by calling `twoStepAuthorization.sendSMSCode`. |
  | `RECEIVE_REQUESTED_SMS_CODE` | This action is created from server &mdash; dispatched inside `twoStepAuthorization.sendSMSCode` callback. The payload is error that's passed as callback argument. |
  | `VERIFY_CODE` | This action is created from view, i.e. when user clicks the button to verify inputted code. The payload for this action should includes action (currently it's either "enable-2fa" or "disable-2fa". Under the hood the store calls `twoStepAuthorization.validateCode`. |
  | `RECEIVE_VERIFIED_CODE` | This action is created from server &mdash; dispatched inside `twoStepAuthorization.validateCode` callback. The payload includes error and data that's passed as callback arguments. |
  | `NEW_BACKUP_CODES` | Request to generate backup codes. Store will handle this by calling `twoStepAuthorization.backupCodes`. |
  | `RECEIVE_NEW_BACKUP_CODES` | This action is created from server &mdash; dispatched inside  `twoStepAuthorization.backupCodes` callback. The payload includes error and data that's passed as callback arguments. |
  | `VERIFY_BACKUP_CODE` | This action is created from view, i.e. when user clicks "Verify" button to verify inputted backup code. Store will handle this by calling `twoStepAuthorization.validateBackupCode` and passing inputted backup code. |
  | `RECEIVE_VERIFIED_BACKUP_CODE` | This action is created from server &mdash; dispatched inside `twoStepAuthorization.validateBackupCode` callback. The payload includes error and data that's passed as callback arguments. |
  | `CREATE_APPLICATION_PASSWORD` | This action is created from view, i.e. when user clicks "Generate Password" for inputted application name. Store will handle this by calling `appPasswordData.create` (from `client/lib/application-passwords-data`). |
  | `RECEIVE_CREATED_APPLICATION_PASSWORD` | This action is created from server &mdash; dispatched inside `appPasswordData.create` callback. The payload is error that's passed as callback argument. |
  | `REMOVE_APPLICATION_PASSWORD` | This action is created from view, i.e. when user clicks remove icon to remove application password. Store will handle this by calling `appPasswordData.revoke` (from `client/lib/application-passwords-data`). |
  | `RECEIVE_REMOVED_APPLICATION_PASSWORD` | This action is created from server &mdash; dispatched inside `appPasswordData.revoke` callback. The payload is error that's passed as callback argument. |
  
  PR: Closed
- [ ] Create `TwoStepStore` in `client/lib/two-step/store.js`. This store should provides public method that can be used to set initial state of View-Controller (`TwoStep` component).
  
  PR: Closed
- [ ] The `TwoStep` component, in `client/me/two-step/index.jsx` should acts as View-Controller in which it listens change event from `TwoStepStore` to update its state and passes that state to children views via props.
  
  PR: Closed 

While all PRs still WIP, I just want to put notes that:
-  Branch `add/two-step-actions` is based off of `master` branch &mdash; actions, constants, and utils do not have dependency to store and components.
- Branch `add/two-step-store` is based off of `add/two-step-actions` because store depends on utils and constants.
- Branch `update/two-step-view-controller-v2` is based off of `add/two-step-store` because the component that acts as View-Controller depends on store and actions.
- Code-review doesn't need to be in sequential order, however merging should be done in sequential order &mdash; `update/two-step-view-controller-v2` :arrow_right: `add/two-step-store` :arrow_right: `add/two-step-actions` :arrow_right: `master`.

---

> > Create TwoStepStore in client/lib/two-step/store.js. This store should provides public method that can be used to set initial state of View-Controller (TwoStep component).
> 
> It is just setting the initial state, or will the store drive the state of the TwoStep component throughout its lifecycle?

Store will drive the state of `TwoStep` component. Store provides public getter method for `TwoStep` component which is passed into `getInitialState`. Child views that's get rendered from `TwoStep` component will be passed down appropriate props from `TwoStep` state.

> (One of the oddities about how the existing code is written is we needed to ignore userSettings object changes during the setup flow since two-step actually becomes enabled part way through the setup flow (after they verify a code and before they print backup codes) - we didn't want the view component to completely reset.)
> 
> If the TwoStepStore is the sole source of state for TwoStep, how will we avoid that unwanted transition?

Can you elaborate more by giving example of unwanted transition? Is there any part that triggers userSettings `change` without user interaction?

I bind userSettings' change which in turns invoke `TwoStepActions.receiveUserSettings` which then dispatch that to Store.

> Based on some of the other flux examples I've seen, I'm also a little confused on whether or not the TwoStepStore should hold view state items like whether or not they've dismissed the Getting Started message or whether or not they just verified a code and need to see and print their backup codes. Maybe a deeper flux expert can weigh in.

Purely driving the state from a single store isn't necessary. I'd recommend we not, for example, store which step the user is on in TwoStepStore (or whether they are in the QR code or time code mode for example). In a quick slack chat, we concurred that we could retain that kind of state in the TwoStep component (or child components) itself or at least in a separate store. That way we get separation of concerns / maintainability and the TwoStep store will be potentially more useful to other components.

I think we need to define how many store will be and what responsibilities of each store before write it into code. Also, decide what should be kept in view-controller, TwoStep, and its child views.

**Comment by lancewillett** [comment]
Closing as this is obsolete now (not using Flux for state).
