### ISSUE TITLE
Me: Remove eventRecorder in favor of Redux analytics

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#20053]
`eventRecorder` uses `lib/analytics` instead of Redux actions for tracking events, which is no longer the preferred method. Also, it's used as a mixin in quite a few locations, which prevents some components to be refactored away from `createReactClass`. 

This issue serves as a master issue for removing `eventRecorder`.

- [x] client/auth/login.jsx - #21310, @tyxla
- [x] client/components/language-picker/README.md - #20199, @tyxla
- [x] client/me/account-password/index.jsx - #22879, @tyxla
- [x] client/me/account/main.jsx - #22881, @tyxla
- [x] client/me/application-password-item/index.jsx - #20680, @tyxla
- [x] client/me/application-passwords/index.jsx - #22882, @tyxla
- [x] client/me/billing-history/billing-history-table.jsx - #20054, @tyxla
- [x] client/me/billing-history/receipt.jsx - #20046, @tyxla
- [x] client/me/billing-history/transactions-header.jsx - #20048, @tyxla
- [x] client/me/connected-application-item/index.jsx - #20283, @tyxla
- [x] client/me/notification-settings/reader-subscriptions/index.jsx - #20457, @tyxla
- [x] client/me/profile-link/index.jsx - #20049, @tyxla
- [x] client/me/profile-links-add-other/index.jsx - #20050, @tyxla
- [x] client/me/profile-links-add-wordpress/index.jsx - #20051, @tyxla
- [x] client/me/profile-links-add-wordpress/site.jsx - #20052, @tyxla
- [x] client/me/profile-links/add-buttons.jsx - #20293, @tyxla
- [x] client/me/profile-links/index.jsx - #20082, @tyxla
- [x] client/me/profile/index.jsx - #20080, @tyxla
- [x] client/me/reauth-required/index.jsx - #22885, @tyxla
- [x] client/me/security-2fa-backup-codes/index.jsx - #20197, @tyxla
- [x] client/me/security-2fa-setup-backup-codes/index.jsx - #20198, @tyxla
- [x] client/me/sidebar/index.jsx - #20201, @tyxla
- [ ] remove `eventRecorder` completely from this world - #23262, @tyxla

**Comment by sirreal** [comment]
#20119 should help make GA changes easier to review 😉

**Comment by tyxla** [comment]
This janitorial effort also sparkled another one - reduxifying user profile links, see #20241

**Comment by tyxla** [comment]
Thank you for the numerous reviews, @Automattic/luna 🙇

**Comment by ockham** [comment]
And there was much rejoicing! 🎉
