### ISSUE TITLE
Me: Reduxify user profile links

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#20241]
User profile links are one of the oldest pieces of code within Calypso. They still use legacy practices like `EventEmitter`, and also lack tests, so we should update them to use Redux and the latest best practices.

This issue serves as a master issue for all related tasks, each of them might be split into smaller tasks eventually.

- [x] Introduce action creators for user profile links - @tyxla, #20242
- [x] Introduce data layer for user profile links - @tyxla, #20242, #20637
- [x] Introduce reducer for user profile links - @tyxla, #20242, #20609
- [x] Introduce selectors for user profile links - @tyxla, #20610, #20615, #20618
- [x] Introduce query component for user profile links - @tyxla, #20638
- [x] Convert profile links components to use Redux - @tyxla, #20994 
- [x] Remove the last usages of `lib/user-profile-links` - @tyxla, #21073
- [x] Convert all profile links components to React.Component/React.PureComponent - @tyxla, #21149, #21151
- [ ] Remove `lib/user-profile-links` - @tyxla, #21152
