### ISSUE TITLE
Store: Product Category Management

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wp-calypso#20295]
This issue will be used to track the overall progress of product category management.

See p90Yrv-9S-p2 for designs.

I will update this issue with issue/PR #s as I work.

Roadmap:
- [x] Category Listing Page (#20268, #20340, #20420, #20425, #21227)
- [x] Infrastructure for editing (#21283)
- [x] Implement form: description, image uploader, product category selection component (#21347, #21351, #21477)
- [x] Implement saving (#21379, #21467)
- [x] Implement deletion (#21418)
- [x] Add tracks / stats (#21473)
- [x] Testing (p90Yrv-vr-p2, #21740, #21503)
- [x] Launch (#21743)

**Comment by justinshreve** [comment]
@timmyc @kellychoffman @jameskoster 

I'm planning on adding tracks for opening the add new page, opening an edit page, completed product creates, and completed. updates Any suggestions on other things we might want to track around product categories?

**Comment by timmyc** [comment]
I _think_ we might have added tracks to when people use the search function in post categories - though not sure we ever did anything with such data... but if we see that the search isn't being used, it is something we could consider removing from the form.

The other event i think we should record a track for is when a category is trashed.
