### ISSUE TITLE
Comments: Delete the old comment component ✨

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#20727]
- [x] Enable Comments M3 Design to all environments. (#20715 - @vindl)
- [x] Move the bulk logic to `CommentNavigation`. (#20729 - @copons)
- [x] Remove comments tree. (#21155 - @copons)
- [x] Remove `CommentDetail` and all its related methods from `CommentList`. (#20745 -
 @copons)
- [x] Delete `CommentDetail` folder and its SCSS imports. (#20738 - @vindl)
- [x] Async load the comments sections (#20158 - @copons).
- [x] Remove obsolete feature flags (#20769 - @vindl)
