### ISSUE TITLE
Onboarding Checklist: don't use non-existent-route / noop to keep tours from triggering

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#20914]
Some tours in the onboarding checklist — see e.g. #20818 — use code like this to prevent being triggered automatically:

`<Tour ... path="/non-existent-route" when={ noop }>`

I think we should switch this to a more readable and succinct solution. E.g., we could introduce a new `noAutomaticTriggering={ true }` prop (name TBD) at the framework level and then leave out the `path` and `when` props. 

- [ ] introduce a solution for this
- [ ] document the new prop
- [ ] make sure all existing tours use it

/cc @mcsf @markryall

**Comment by markryall** [comment]
Yes - totally agree with this.

There aren't too many original tours so I was wondering if we could make this a positive attribute like `autoLaunch` and add that to the existing tours.  The default behaviour can then be to not auto launch - the checklist tours can just skip the `path` and `when` props.

**Comment by lsinger** [comment]
> There aren't too many original tours so I was wondering if we could make this a positive attribute like autoLaunch.

I completely agree that we should consider this. In the past, the idea behind Guided Tours was to launch tours automatically, in the context that people would need them. But now it seems that explicitly requesting a tour is as valid (or even more) a use case. 

Cons:

- goes against initial Guided Tours design rationale
- it's a change from what was before, so tours and documentation will need to be updated

Pros:

- this better reflects the reality of how Guided Tours are used today
- it's a relatively small change, and there aren't too many tours that would need changing
- it would (hopefully) make things clearer for future developers
- positive attributes are more comprehensive than negated ones
