### ISSUE TITLE
Store: Add next round of countries to calypso based management

### ISSUE THREAD

**Issue by allendav** [Automattic/wp-calypso#21574]
Proposed next set of countries (added 1/23):
- Australia
- <del>Austria</del>
- <del>Belgium</del>
- Canada (add fr_CA support)
- France
- <del>Germany</del>
- <del>Ireland (at least en_IE, but gd_IE optional for now)</del>
- <del>Luxemborg</del>
- Netherlands
- Spain
- United Kingdom

When adding a new country, we must be sure to handle

- [x] Updating the stripe cost ( i.e. the situation described in closed issue #21556 )
- [ ] Updating the Edit Address (e.g. within settings-payments) to allow nonUS nonCA ( i.e. the situation described in closed issue #21557 example 1)
- [ ] Make sure TaxJar doesn't automatically detect countries as states ( i.e. the situation described in closed issue #21557 example 1)
- [ ] Making sure the country currency is added to the list ( i.e. the situation described in closed issue #21557 example 2) (see also #21279 )
- [ ] Properly handling currency position (left or right), thousands separators (space, dot or comma), and decimal separators (dot or comma)

^^ Add/edit more as we come across them

Let's use this issue to gather things we want to make sure we don't forget as we do the first expansion beyond US and CA only support for Stores managed in Calypso

We can clone this issue for subsequent expansions.

cc @designsimply @iamgabrielma

**Comment by allendav** [comment]
Bumping Germany due to additional eCommerce laws that would need to be satisfied, e.g. regarding front-side display of prices https://www.haendlerbund.de/en/downloads/fact-sheet-on-indication-of-prices.pdf

Bumping Luxembourg due to its relatively small population - to make this first expansion beyond US and CA just a wee bit simpler for us.

**Comment by allendav** [comment]
Bumping Austria, Belgium and Ireland for now due to relatively low traffic compared to other opportunities.
