### ISSUE TITLE
Store Orders: Improvements to order creation

### ISSUE THREAD

**Issue by ryelle** [Automattic/wp-calypso#21974]
This follows off where #15679 finished. Order creation is live, but there are still features we could improve on. This is a "parent issue" for the next iteration of order creation.

- [ ] Applying coupons to orders
  - [ ] Create API endpoint for managing coupons woocommerce/wc-api-dev#78
  - [ ] Remove coupons from an order 
  - [ ] Add "Apply Coupon" field, design in #20741
- [ ] Search existing customers when entering email address, pre-fill details if exists
  - [x] Create redux state etc for `customers` endpoint. #20848
  - [ ] Update the customer details create component to offer a "customer search" #20876
- [ ] Take payments in the order screen
- [ ] Select a real shipping method, let that set shipping cost
- [ ] Improve UX of order creation flow #21795
