### ISSUE TITLE
State: Reduxify application passwords

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#22912]
This serves a master issue for reduxifying the legacy [application passwords store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/application-passwords-data).

- [x] Create action creators - @tyxla, #22913
- [x] Create data layer - @tyxla, #22913 
- [x] Update data layer to use `makeParser` for stricter validation - @tyxla, #23585
- [x] Create reducers - @tyxla, #23589 
- [x] Add actions, data layer and reducer for storing the new password - @tyxla, #23686
- [x] Create selectors - @tyxla, #23906, #23907
- [x] Implement persistence - @tyxla, #23909 
- [x] Create a query component - @tyxla, #23918
- [x] Migrate the existing application passwords components to use Redux - @tyxla, #23926
- [x] Update `ApplicationPasswords` to use `React.Component` - @tyxla, #23926 
- [x] Remove `applicationPasswordsData` from `lib/two-step-authorization` - @tyxla, #23928
- [ ] Remove the legacy `ApplicationPasswords` store - @tyxla, #24081

**Comment by sirreal** [comment]
Is persistence on the list? Should be simple after #23686

**Comment by tyxla** [comment]
Good point, added to the list 👍

**Comment by tyxla** [comment]
Also, @sirreal found a bug with the Add button - fixed in #24050.
