### ISSUE TITLE
Site Address Editor: Pre launch & Post launch Enhancements

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#23340]
### Summary

Following the addition of the Site Address Editor in #21861 and enabling in `wpcalypso.json`  in #23207 I've creating this tracking issue to capture, discuss and track any suggested follow up work that can be done to enhance this feature.

### Completed Tasks

- [x] Copy overhaul. ( https://github.com/Automattic/wp-calypso/issues/22906 )
  - [x] Work a link to the support documentation in to the copy/ui ( https://github.com/Automattic/wp-calypso/pull/23733 )
- [x] Upfront availability checking ( https://github.com/Automattic/wp-calypso/pull/23492 )
- [x] Styling issue with `FormTextInputWithAffixes` focused state. ( https://github.com/Automattic/wp-calypso/pull/23740 )
- [x] Investigate why this doesn't work with SU (solved by removing a8c only limitation)
- [x] Immediately after editing the address, the browser back button goes back to the old address and causes bugs (  #24169, Issue: #23929 ).
- [x] Remove DevDocs example ( #24394 )

### Imminent Tasks

- [ ] Fix component height in smaller viewports ( Issue: #24399, PR: #24427 )
- [ ] Rename files, directories, variable and function names to match 'Site Address Change' derived language ( issue: #24267, PR: #24417 )
- [ ] Link to the feature in other relevant places ( *Settings > Site Address* for instance ) (*)
- [ ] Add visual filler to the validation message area to avoid excessive jumps in height between messages

### Future Enhancements
- [ ] Support for other simple-site urls (`.blog` etc.)
- [ ] Lock up the features usage while an address change is in progress to avoid reported, related bugs.
- [ ] Explore collapsing spaces automatically ( #23903 )
- [ ] Include a site redirect option

*Regarding links to the feature - The only place that I've found that may need to link to the feature so far is in *Settings > General*. There are two sections within this menu that seem to address site addresses -- "Site Tools" and the "Site Address" section in "Site Profile"
It might make sense add to the sub text here, though I'm hesitant to grow this any larger:
<img width="733" alt="screen shot 2018-04-05 at 14 07 33" src="https://user-images.githubusercontent.com/4335450/38367531-d898d624-38da-11e8-87d2-fba60276b367.png">

**Comment by jblz** [comment]
@spen -- Can you please go through update the status of these?

**Comment by marekhrabe** [comment]
Just a small thing I've noticed: this is a screenshot at ~661px viewport and I think we should already break columns into linear content. Especially in languages with longer phrases, this could get really long, and subdomain ending ".wordpress.com" is almost guaranteed to be split in the middle.

<img width="396" alt="screen shot 2018-05-10 at 13 42 06" src="https://user-images.githubusercontent.com/156676/39868137-82fe126c-5458-11e8-9661-a78267225a92.png">

**Comment by spen** [comment]
Good spot @marekhrabe - I'll track this today :)

**Comment by jblz** [comment]
#27771
