### ISSUE TITLE
Reduxify: lib/user

### ISSUE THREAD

**Issue by blowery** [Automattic/wp-calypso#24004]
`lib/user` is as old as calypso and used in a lot of places, with 63 different places importing it.

## Summary
- EventEmitter / Flux hybrid with data currently mirrored to redux
- Large number of users
- Best strategy would be a series of small PRs to migrate clients to use redux and selectors
- Biggest challenge: how to handle non-reactive clients, mostly controllers

## Writeup

It's mostly an event emitter style store, though it does register with Flux, consuming the `INVITE_ACCEPTED` action from `lib/invites/constants`.

It doesn't dispatch flux actions, but has methods attached to the user instance that perform actions and then trigger a `change` event on the user instance. 

There's already some user state in redux (a combo of `current-user` and `users`). It doesn't appear to be as complete. it's kept in sync via `setCurrentUserOnReduxStore` in `lib/redux-helpers`, which is called when `lib/user` emits a change event. `lib/user` is effectively driving all the data into redux. 

Usage is typically get-the-user-singleton-and-ask-for-a-prop. _Not all clients are reactive_, so changes to the user object are not reflected. Take a peek at any of the controllers listed above for examples. Can we make them reactive? How should we expose the redux store in these cases? (redux-bridge?)

I'd recommend moving all the consumers over to use the redux-bound data, then moving the work that lib/user/* does to redux. That should allow us to keep this as a series of pretty small PRs.

## Imports

- [ ] client/blocks/login/index.jsx:1 (uses clear)
- [ ] client/boot/app.js:1 (uses change events)
- [ ] client/auth/controller.js:1 (kicks off fetch)
- [ ] client/signup/config/flows.js:1 (RO, but not reactive)
- [ ] client/signup/controller.js:1 (RO, but not reactive)
- [x] **client/signup/steps/about/index.jsx:1** (RO) #24476
- [ ] client/signup/utils.js:1 (RO, non reactive)
- [x] **client/signup/main.jsx:1** (RO) #24477
- [ ] client/state/lib/middleware.js:1 (calls decrementSiteCount)
- [ ] client/state/initial-state.js:1 (RO, used to determine where to save redux state)
- [ ] client/state/jetpack-connect/actions.js:1 (fetcher)
- [ ] client/controller/index.web.js:1 (RO? passes user through to layout / children)
- [ ] client/extensions/woocommerce/app/dashboard/setup/store-location.js:1 (fetches)
- [x] **client/my-sites/importer/author-mapping-item.jsx:1** (RO, passes through) #24597
- [x] client/my-sites/welcome/README.md:1 (readme) #24599
- [ ] client/my-sites/checkout/index.js:1 (routes set up based on state!)
- [x] **client/my-sites/checkout/checkout-thank-you/jetpack-plan-details.jsx:1** (RO) #24600
- [x] **client/my-sites/checkout/checkout-thank-you/google-apps-details.jsx:1** (RO) #24600
- [ ] client/my-sites/controller.js:1 (RO, non-reactive) #27516
- [x] **client/my-sites/people/edit-team-member-form/edit-user-form.jsx:1** (RO) #24603
- [x] **client/my-sites/people/edit-team-member-form/index.jsx:1** (RO) #24603
- [ ] client/my-sites/invites/controller.js:1 (RW)
- [x] **client/my-sites/invites/invite-accept/index.jsx:1** (RO) #24877
- [ ] client/my-sites/themes/index.web.js:1 (routes based on current state)
- [x] **client/my-sites/checklist/checklist-show/index.jsx:1** (RO) #24878
- [ ] client/components/email-verification/README.md:1 (readme)
- [ ] client/components/email-verification/index.js:1 (calls signalVerification)
- [ ] client/components/email-verification/email-unverified-notice.jsx:1 (calls sendVerificationEmail)
- [x] **client/components/tinymce/plugins/editor-button-analytics/plugin.js:1** (RO) #24880
- [ ] client/components/data/domain-management/email/index.jsx:1 (passes to storeConnection)
- [x] **client/components/post-schedule/index.jsx:1** (RO) #24882
- [ ] client/me/social-login/index.jsx:1 (calls fetch)
- [ ] client/me/sidebar/index.jsx:1
- [x] client/me/purchases/remove-purchase/index.jsx:1
- [x] client/me/purchases/cancel-privacy-protection/index.jsx:1
- [x] client/me/purchases/payment/add-card-details/index.jsx:1
- [x] client/me/purchases/payment/edit-card-details/index.jsx:1
- [x] client/me/purchases/purchases-list/index.jsx:1 (#24785 @sirreal)
- [x] client/me/purchases/manage-purchase/index.jsx:1
- [ ] client/me/purchases/controller.jsx:1
- [x] client/me/purchases/cancel-purchase/index.jsx:1
- [x] client/me/purchases/confirm-cancel-domain/index.jsx:1
- [ ] client/me/sidebar-navigation/sidebar-navigation.jsx:1
- [ ] client/me/security-2fa-backup-codes-list/index.jsx:1
- [ ] client/me/form-base/index.js:1
- [ ] client/me/account/main.jsx:1
- [ ] client/me/help/help-unverified-warning/index.jsx:1
- [ ] client/post-editor/controller.js:1
- [ ] client/post-editor/editor-word-count/index.jsx:1
- [ ] client/lib/user-settings/index.js:1
- [ ] client/lib/signup/step-actions.js:1
- [ ] client/lib/signup/flow-controller.js:1
- [ ] client/lib/abtest/test/index.js:1
- [ ] client/lib/abtest/index.js:1
- [ ] client/lib/desktop/index.js:1
- [ ] client/lib/user/README.md:1
- [ ] client/lib/user/utils.js:1
- [ ] client/lib/upgrades/actions/domain-search.js:1
- [ ] client/lib/siftscience/index.js:1
- [ ] client/lib/username/index.js:1
- [ ] client/lib/translator-jumpstart/index.js:1
- [ ] client/lib/analytics/ad-tracking.js:1
- [ ] client/jetpack-connect/index.js:1
- [ ] client/login/magic-login/handle-emailed-link-form.jsx:1

**Comment by blowery** [comment]
Unassigning myself

**Comment by blowery** [comment]
Starting back in on this. I'm going to start by looking through all the clients of lib/users and port anything with read-only usage. This should result in a slew of PRs.

**Comment by tyxla** [comment]
I'm going to be working on this one.

**Comment by tyxla** [comment]
More than a month and over 60 PRs later, we have the final PR to remove the `lib/user` `EventEmitter` store: #54168.

Thanks to everyone who worked on this one!
