### ISSUE TITLE
Simple Payments: Media Library user story

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#24593]
## Scenario

A user wants to edit the existing Simple Payments Button on one of his pages from his mobile device. Let's assume he'd like to improve the description and add a better image. He hasn't found a good fit for the image yet, and he's hoping to do it via the Free photo library that is accessible via the Media Library. However clicking on `Add Image` in Simple Payments dialog only offers an option to upload the image directly from the current device. 

![imagepicker](https://user-images.githubusercontent.com/1182160/39478949-1f583a94-4d64-11e8-88da-d54e34734477.png)

While it's possible to work around this by navigating to Media Library, selecting the image from there and downloading it to the mobile phone, and then uploading it again here. This is a tedious process and we should have a more polished flow in place that is at the same time consistent with the rest of Calypso.

## Steps

1. User opens `Sites Pages` and selects an option to edit the existing page from Ellipsis menu.
2. The page opens up in Editor and the users select the existing Payments Button and clicks on edit.
3. The upload dialog appears instead of the Media Library.

### Tasks

I've created separate issues for technical tasks that will need to be completed for this flow to work.

- [x] https://github.com/Automattic/wp-calypso/issues/24588 Simple Payments: use Media Library for image picking (PR: https://github.com/Automattic/wp-calypso/pull/24659)
- [x] https://github.com/Automattic/wp-calypso/issues/24595 Media Library: displaying audio and video options in wrong contexts (PR: #24620)
- [x] https://github.com/Automattic/wp-calypso/issues/24591 Simple Payments: Add ability to open up image editor directly from image (PR: https://github.com/Automattic/wp-calypso/pull/24659)
- [x] https://github.com/Automattic/wp-calypso/issues/24590 Media Library: modify the component for Simple Payments use case (PR: #24620)

**Comment by vindl** [comment]
Addressed in #24659 and #24620.
