### ISSUE TITLE
Deprecate dispatchRequest() - 100% complete

### ISSUE THREAD

**Issue by dmsnell** [Automattic/wp-calypso#25121]
We have a long-standing goal of unifying these on the newer API.

Let's get this done! We can do it in a month, wouldn't you say?

> 👉 Instructions below for those who want to skip the background

**Background**
When we first introduced `dispatchRequest()` in #10327 it looked much different
than it does today. It's gone through a series of API changes as a result of learning
how we were using it and wanted to us it. Go ahead and take a read over that PR.
At the time it introduced a dramatic change in how we approach API calls.

The data layer is an experiment in building a declarative, centralized, policy-governed,
and generic data provider subsystem for Calypso. We want to be able to inspect all
of the activity going through it at runtime. We want to be able to intercept requests
and modify them, cancel them, and track them. We want to be able to reason about
requests and inject fake requests states for tests.

Prior to `dispatchRequestEx()` the data layer handlers called `dispatch()` directly in
order to indicate actions and pass along requests. This led to one problem which was
that it made testing obnoxious as you had to create a spy for `dispatch()`. We also
noticed that the vast majority of handlers all shared a similar pattern: they dispatched
a single or sequence of actions without doing anything else like reading from state.

Thus in #18733 @jsnajdr introduced `dispatchRequestEx()` to make up for these and
other deficiencies. He introduced the new helper because by the point it was created
we had enough code relying on `dispatchRequest()` to make the API change difficult
to do in one go. Previously all changes had been atomic:  breaking API change came
with updates to all call sites. This was too big of a change to do that way though.

 - Stop differentiating between optional and required parameters
 - Handlers can return an action or a list of actions; these will be dispatched automatically
 - If a handler needs access to `state` it needs to return an action thunk (rare, avoid if possible)

Now it's time to eliminate `dispatchRequest()`. When we're done we'll rename the
temporary `dispatchRequestEx()` back to `dispatchRequest()` and all will be well
and normal in the world again.

**Instructions**

Start by picking one of the listed files below.

Before you do any work, please check the TODO box here so that someone else doesn't
think the item is still up for grabs. Once you post an actual PR you can add the PR link.
See the other examples below for the format.

Many of these data layer handlers were written early on and not only need changes
inspired by the changes from `dispatchRequestEx()` but also would benefit from
converting to use the `fromApi()` function. This is an _optional_ but _preferable_
change to include here. More below…

If none of the handlers use `getState()` then it's easy.
 - remove the `dispatch` parameter from the handlers
 - change the `dispatchRequest` import to `dispatchRequestEx`
 - change the exported `dispatchRequest` to `dispatchRequestEx`
 - replace the positional parameters with a "bag-of-options" object specifying
   specifying `{ fetch, onSuccess, onError }` and maybe `fromApi` or `onProgress`
 - replace calls to `dispatch( someAction )` by having the handlers return those
   actions. typically I delete the `dispatch` text and then auto-format - it will 
   automatically remove the parentheses that previously were from the call to
   `dispatch()`
 - you may want to change the names of the handlers - particularly if they are named
   things like `changeStuffSuccess` or `onCreateFailure`. in these cases and if the
   module only contains a single typical triplet of (fetch, success, failure) then rename
   them `fetch`, `onSuccess`, and `onError`. we can use the object shorthand syntax
   in the exported call to `dispatchRequestEx()` and the module name will be enough
   of a namespace for someone to know what the purpose of those functions are.
   (semantic names are still always best 🤷‍♂️ )
 - if there are multiple dispatches in a handler that's not a problem. stack them into
    a list and return that list. we can use conditions to build our list or even the convenient
   `lodash.compact()` function to return a list of either actions or falsely values.

if a handler _does_ access `getState()` then for now it's probably best to change very
little from inside the function. instead, take out `{ dispatch, getState }` from the
argument list and have it return a thunk with `( dispatch, getState )` instead. done.

at this point we should be done with the handler file itself. don't worry, it gets pretty
menial after you do a few of them. however, we're not done yet: we have to update the
test files.

 - update any imports in the test file
 - remove all `dispatch` or `getState` spies
 - probably at this point we can eliminate the external imports of `chai` and `sinon`.
   the built-in `expect` from Jest can be much nicer. read about it's [expect API](http://jestjs.io/docs/en/expect).
   `expect.objectContaining()` and `expect.arrayContaining()` are your friends!
 - if you incorporated `fromApi` then we probably have to update some tests or
   remove them entirely because the `fromApi` step is already unit-tested in the app

If you see something like this in the success handler: `const data = fromApi( apiData )`
then we probably should move `fromApi` into the call to `dispatchRequestEx`. In the
new system it will automatically try to transform the data from the API and will
automatically fail-over to `onError` if the transformation step throws an exception.
Sometimes you will find an `onSuccess` handler that manually transforms data then
jumps to `onError` manually; these need to be removed if we incorporate `fromApi`

Phew! That took longer to write and probably read than it takes to update a file. Good
luck hunting out there

 -  _**please assign me as a reviewer on the PRs**_.
 - Please assign the recommend reviewers to the PR
 - Please ask some people for help testing :smile:
 - please **use the form titles and descriptions in these PRs to make them easily identifiable**.

**Title**
> Framework: `dispatchRequest` update (NAME OF SUBSYSTEM)

**Body of PR**
> See #25121
>
> In this patch we're replacing the use of dispatchRequest()
> in the data layer handler to use the newer API exposed
> as dispatchRequestEx() This should have no change in
> actual effect or interaction.

**Todo**
- [x] extensions/woocommerce/state/data-layer/orders/index.js (#29138)
- [x] extensions/woocommerce/state/data-layer/product-categories/index.js
- [x] extensions/woocommerce/state/data-layer/products/index.js (#29140)
- [x] extensions/woocommerce/state/sites/coupons/handlers.js (#29199)
- [x] extensions/woocommerce/state/sites/review-replies/handlers.js (#29237)
- [x] extensions/woocommerce/state/sites/reviews/handlers.js (#29230)
- [x] extensions/woocommerce/state/sites/settings/general/handlers.js
- [x] extensions/woocommerce/state/wc-api/utils.js
- [x] extensions/wp-job-manager/state/data-layer/settings/index.js (#29143)
- [x] extensions/wp-job-manager/state/data-layer/setup/index.js (#29143)
- [x] extensions/zoninator/state/data-layer/feeds/index.js (#29127)
- [x] extensions/zoninator/state/data-layer/zones/index.js (#29126)
- [x] state/data-layer/wpcom-http/README.md
- [x] state/data-layer/wpcom-http/test/utils.js
- [x] state/data-layer/wpcom/gravatar-upload/index.js (#28027)
- [x] state/data-layer/wpcom/jetpack/settings/index.js (#28049)
- [x] state/data-layer/wpcom/login-2fa/index.js
- [x] state/data-layer/wpcom/me/send-verification-email/index.js (#27666)
- [x] state/data-layer/wpcom/me/settings/index.js (#28013)
- [x] state/data-layer/wpcom/me/transactions/supported-countries/index.js (#27605)
- [x] state/data-layer/wpcom/meta/sms-country-codes/index.js (#27668)
- [x] state/data-layer/wpcom/posts/revisions/index.js (#27669)
- [x] ~~state/data-layer/wpcom/privacy-policy/index.js~~ 
- [x] state/data-layer/wpcom/read/following/mine/index.js (#27912)
- [x] state/data-layer/wpcom/read/following/mine/new/index.js (#27919)
- [x] state/data-layer/wpcom/read/recommendations/sites/index.js (#27920)
- [x] state/data-layer/wpcom/read/site/comment-email-subscriptions/delete/index.js (#28093)
- [x] state/data-layer/wpcom/read/site/comment-email-subscriptions/new/index.js (#28092)
- [x] state/data-layer/wpcom/read/site/post-email-subscriptions/delete/index.js (#28077)
- [x] state/data-layer/wpcom/read/site/post-email-subscriptions/new/index.js (#28076) 
- [x] state/data-layer/wpcom/read/site/post-email-subscriptions/update/index.js (#28081)
- [x] state/data-layer/wpcom/read/sites/posts/follow/index.js
- [x] state/data-layer/wpcom/read/sites/posts/mute/index.js
- [x] state/data-layer/wpcom/sites/automated-transfer/eligibility/index.js (#28097)
- [x] state/data-layer/wpcom/sites/automated-transfer/initiate/index.js (#28119)
- [x] state/data-layer/wpcom/sites/automated-transfer/status/index.js (#28118)
- [x] state/data-layer/wpcom/sites/comments-tree/index.js (#27716)
- [x] state/data-layer/wpcom/sites/comments/index.js (#27613, #27711)
- [x] state/data-layer/wpcom/sites/comments/likes/mine/delete/index.js (#27713)
- [x] state/data-layer/wpcom/sites/comments/likes/new/index.js (#27714) 
- [x] state/data-layer/wpcom/sites/comments/replies/new/index.js (#27921)
- [x] state/data-layer/wpcom/sites/jitm/index.js (#29161)
- [x] state/data-layer/wpcom/sites/posts/replies/new/index.js (#27921)
- [x] state/data-layer/wpcom/sites/stats/google-my-business/index.js (#28094)
- [x] state/data-layer/wpcom/sites/users/index.js (#27615)
- [x] state/data-layer/README.md (#26213)
- [x] state/data-layer/third-party/refer/index.js (#26411)
- [x] state/data-layer/wpcom/account-recovery/lookup/index.js (#25728)
- [x] state/data-layer/wpcom/account-recovery/request-reset/index.js (#25729)
- [x] state/data-layer/wpcom/account-recovery/reset/index.js (#25730)
- [x] state/data-layer/wpcom/account-recovery/validate/index.js (#25731)
- [x] state/data-layer/wpcom/activity-log/activate/index.js (#25132)
- [x] state/data-layer/wpcom/activity-log/deactivate/index.js (#25133)
- [x] state/data-layer/wpcom/activity-log/delete-credentials/index.js (#25134)
- [x] state/data-layer/wpcom/activity-log/rewind/activate/index.js (#25135)
- [x] state/data-layer/wpcom/activity-log/rewind/downloads/index.js (#25137)
- [x] state/data-layer/wpcom/activity-log/rewind/restore-status/index.js (#25138)
- [x] state/data-layer/wpcom/activity-log/update-credentials/index.js (#25141)
- [x] state/data-layer/wpcom/comments/index.js (#25291)
- [x] state/data-layer/wpcom/concierge/schedules/available-times/index.js (#25292)
- [x] state/data-layer/wpcom/domains/countries-list/index.js (#25365)
- [x] state/data-layer/wpcom/me/devices/index.js (#26214)
- [x] state/data-layer/wpcom/me/notification/settings/index.js (#26219)
- [x] state/data-layer/wpcom/read/following/mine/delete/index.js (#26026)
- [x] state/data-layer/wpcom/read/teams/index.js (#26221)
- [x] state/data-layer/wpcom/sites/blog-stickers/add/index.js (#25129)
- [x] state/data-layer/wpcom/sites/blog-stickers/index.js (#25130)
- [x] state/data-layer/wpcom/sites/blog-stickers/remove/index.js (#25131)
- [x] state/data-layer/wpcom/sites/media/index.js (#25126)
- [x] state/data-layer/wpcom/sites/plugins/new/index.js (#25127)
- [x] state/data-layer/wpcom/sites/rewind/downloads/index.js (#25128)
- [x] state/data-layer/wpcom/theme-filters/index.js (#25125)
- [x] state/data-layer/wpcom/timezones/index.js (#25124)
- [x] state/data-layer/wpcom/users/auth-options/index.js (#25123)
- [x] state/data-layer/wpcom/videos/poster/index.js (#25122)
- [x] state/http/README.md (#26215)

**Comment by jonchurch** [comment]
Hello there @dmsnell would you like help from this OSS Citizen on cleaning these up?

**Comment by dmsnell** [comment]
> would you like help from this OSS Citizen on cleaning these up?

yes @jonchurch that would be great - is there anything I can do to help you with that? we're cleaning up existing uses of `dispatchRequest` and most are straightforward but some are more complicated - those that involve multiple dispatches and reading from state.

**Comment by jonchurch** [comment]
@dmsnell Thank you! I looked at some of the past commits and can see the pattern.

In my afternoon tmr (I'm GMT +7) I will catch up on #25728 and start with the files I immediately grasp the work within, will loop back with you once I have clarifying questions or blockers 👍

**Comment by jonchurch** [comment]
Leaving this here for my own/anyone's reference, the comment from when *`dispatchRequestEx`* was introduced in commit 541c109dc3cac01b4f53fcee7bd94cce0d4bb1cf (currently [here](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom-http/utils.js#L200) on master at time of writing) 

```
/**
 * Dispatches to appropriate function based on HTTP request meta
 *
 * @see state/data-layer/wpcom-http/actions#fetch creates HTTP requests
 *
 * When the WPCOM HTTP data layer handles requests it will add
 * response data and errors to a meta property on the given success
 * error, and progress handling actions.
 *
 * This function accepts several functions as the fetch, success, error and
 * progress handlers for actions and it will call the appropriate
 * one based on the stored meta.
 *
 * These handlers are action creators: based on the input data coming from the HTTP request,
 * it will return an action (or an action thunk) to be executed as a response to the given
 * HTTP event.
 *
 * If both error and response data is available this will call the
 * error handler in preference over the success handler, but the
 * response data will also still be available through the action meta.
 *
 * The functions should conform to the following type signatures:
 *   fetch  :: Action -> Action (action creator with one Action parameter)
 *   onSuccess  :: Action -> ResponseData -> Action (action creator with two params)
 *   onError    :: Action -> ErrorData -> Action
 *   onProgress :: Action -> ProgressData -> Action
 *   fromApi    :: ResponseData -> TransformedData throws TransformerError|SchemaError
 *
 * @param {Function} middleware intercepts requests moving through the system
 * @param {Object} options object with named parameters:
 * @param {Function} options.fetch called if action lacks response meta; should create HTTP request
 * @param {Function} options.onSuccess called if the action meta includes response data
 * @param {Function} options.onError called if the action meta includes error data
 * @param {Function} options.onProgress called on progress events when uploading
 * @param {Function} options.fromApi maps between API data and Calypso data
 * @returns {Action} action or action thunk to be executed in response to HTTP event
 */
```

**Comment by jsnajdr** [comment]
I think we are done here :tada: #29355 removes the legacy implementation and drops the `Ex` suffix.
