### ISSUE TITLE
DevDocs: show Gutenberg blocks

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#26064]
### Background
As part of the current plan for integrating Gutenberg into Calypso, it would be nice to include the Gutenberg blocks in Calypso and reflect the developer documentation with these new reusable pieces of UI. 

### Goals
- 🔨 Include the Gutenberg built-in blocks in Calypso. This depends on other work currently being developed in order to expose publicly the different Gutenberg modules as independent npm packages (WordPress/gutenberg#3955).
- 📘 Update the developer documentation in Calypso, so we let folks know how the Gutenberg blocks can be used for building the Calypso’s UI.
- 📣 Provide feedback to the Gutenberg project, so potential blockers can be identified when using the Gutenberg blocks in other projects.

### Tasks
- [ ] Include a new section in the [developer documentation](https://wpcalypso.wordpress.com/devdocs) that will be used in the future for adding the documentation explaining how to use the Gutenberg blocks in Calypso (#26065)
- [ ] Identify potential blockers we can have with the `@wordpress/core-blocks` npm package, using the `@wordpress/components` package (#26088)
- [ ] Prototype what a single Gutenberg block should look like in the new section on an experimental branch, copying over files if we really need to.
- [ ] Update the [Components page](https://wpcalypso.wordpress.com/devdocs/docs/components.md) explaining what Gutenberg blocks are
- [ ] Update the new Gutenberg blocks section with the collection of blocks exposed by the `@wordpress/core-blocks` npm package
- [ ] Include individual documentation for each Gutenberg block
- [ ] Add a search bar in the new Gutenberg blocks section so they can be filtered
- [ ] Integrate the Gutenberg blocks in the [Playground section](https://wpcalypso.wordpress.com/devdocs/playground)
- [ ] Remove feature flag

**Comment by mmtr** [comment]
I have created a (project)[https://github.com/Automattic/wp-calypso/projects/74] that makes this issue useless as it was intended for splitting the project in small tasks and check the progress
