### ISSUE TITLE
Podcasting: Help free customers not get "stuck" partway through the process

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#26074]
Our [documentation](https://en.support.wordpress.com/audio/podcasting) says:

> Uploading these files is only available as part of the WordPress.com Personal, Premium, or Business plan. If your site is on the Free plan, you will need to host your audio files elsewhere and embed them into your podcast episodes.

However, for a Free site, there is no indication in the UI that podcasting will not work with uploaded audio files.  You can set up all of the settings with no notices or warnings, but when you get to one of the last steps (create a podcast episode), you can't upload an audio file. Also, this error message is not very clear and does not contain any indication that the customer can upgrade their plan in order to upload audio files.

We will show a notice at the top of the Podcast Settings screen when on a Free plan that tells customers that they can create a podcast, but will need to link to external files unless they upgrade their plan.

Improvements to the media uploading experience will be tracked and addressed in separate cards.

### Tasks

- [x] Add notice to top of Podcast Settings screen if on a Free plan
- [x] Add a link to documentation (inline help if possible)
- [x] [invalid] Add notice action to upgrade
- [x] Add Tracks event for the click to upgrade, so we can track conversions

### Acceptance criteria

1.
- Given a Free site
- When Podcasting Settings is shown
- Then there is a notice indicating that only external audio files are supported (along with a link to documentation and action to upgrade plan)

2.
- Given a Free site with Podcast Setting shown
- When the notice action is clicked
- Then the customer is taken to the screen to upgrade their plan

3.
- Given a Free site with Podcast Setting shown
- When the link to documentation is clicked
- Then the customer is shown documentation (inline if possible)

----

**Tanooki complexity estimate: 2**

**Comment by creativecoder** [comment]
Add notice to top of Podcast Settings screen if on a Free plan: #26575

**Comment by creativecoder** [comment]
> Add Tracks event for the click to upgrade, so we can track conversions

Also in #26575 

Clicking on upgrade nudge triggers`calypso_upgrade_nudge_cta_click` with `cta_name` property as `podcasting_details_upload_audio`

**Comment by creativecoder** [comment]
> Add a link to documentation (inline help if possible)

Already exists in header to the right of "Podcast Settings" title

**Comment by creativecoder** [comment]
> Add notice action to upgrade

Cain tricked me into using the upgrade nudge rather than a notice. He says, "...since we are nudging an upgrade and a notice would stack on top of the podcasting enabled notice."

**Comment by michaeldcain** [comment]
>Cain tricked me into using the upgrade nudge rather than a notice. He says, "...since we are nudging an upgrade and a notice would stack on top of the podcasting enabled notice."

@mattsherman: how do we feel about this? Not the tricking per se, but the use of the nudge instead of the notice (see screenshot).

**Comment by mattsherman** [comment]
> using the upgrade nudge rather than a notice

@michaeldcain @creativecoder I think a nudge is the correct approach here. Thanks for not taking our acceptance criteria too literally, and instead thinking about the intent behind it! 👍

**Comment by mattsherman** [comment]
Fixed by #26575

Accepting this -- nice work!
