### ISSUE TITLE
Podcasting: Remind customer how to create new podcast episode after enabling podcasting

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#26111]
**As a podcaster, I want to know how to create a new podcast episode after I enable podcasting, so that I can quickly get started with my new podcast**

After a customer enables podcasting, we should remind them how to create a new podcast episode and provide them a link to the documentation where they can learn more (https://en.support.wordpress.com/audio/podcasting/).

Show a banner on the Podcasting Settings screen when podcasting is enabled, something similar to what we show on the Writing settings screen, but with a bit more detail.

<img width="736" alt="screencapture at tue jul 17 09 39 59 edt 2018" src="https://user-images.githubusercontent.com/2098816/42820980-76b5cfea-89a5-11e8-85bc-976c7d369fdf.png">

### Tasks

- [x] Create new component based on Writing setting screen, so that this can be shared on both Writing settings screen and Podcast Settings screen 
- [x] Add component to Podcast Settings screen whenever podcasting is enabled
- [x] Add a button to create a new episode
- [x] Add a link to inline help documentation (if possible; if not, create a new GH issue about this)
- [ ] Reply to pLZE4-cP8-p2

### Acceptance criteria

1.
- Given a site with podcasting support
- When podcasting is enabled
- Then the customer is reminded how to create a new podcast episode

2.
- Given a site with podcasting enabled
- When the "new episode" button is clicked
- Then the user is taken to the editor to create a new post

3.
- Given a site with podcasting enabled
- When the documentation link is clicked
- Then inline help for podcasting is shown

----

**Tanooki complexity estimate: 2**

**Comment by michaeldcain** [comment]
> Add a link to inline help documentation (if possible; if not, create a new GH issue about this)

We pulled this out b/c it breaks the layout in almost every case. I think that once https://github.com/Automattic/wp-calypso/pull/26254 is merged and we can link directly to a modal support doc, it'd be worth revisiting with the "information" icon as a trigger.

**Comment by michaeldcain** [comment]
Linked the Podcasting Header and `PodcastingSupportLink` to the inline docs in #26347.

<img width="642" alt="screen shot 2018-07-27 at 2 24 24 pm" src="https://user-images.githubusercontent.com/942359/43341155-9af76bb6-91ac-11e8-9a8f-3bdfe17c91b2.png">

**Comment by michaeldcain** [comment]
@mattsherman re:the inline documentation link. Just noting for grooming that it's probably worth discussing if this is the best place/implementation for something like this.

**Comment by mattsherman** [comment]
> We pulled this out b/c it breaks the layout in almost every case. I think that once #26254 is merged and we can link directly to a modal support doc, it'd be worth revisiting with the "information" icon as a trigger.

@michaeldcain I'm not really sure what is meant by this, as the link to documentation appears to still be in there.

**Comment by michaeldcain** [comment]
@mattsherman sorry, this was more a status update mid-week. In the original `PodcastPublishNotice` there was a "learn more" link (like the "after" screenshot on #26200). This caused the notice to wrap in every layout, so we removed it. Then, after #26254 merged, I went ahead and added the icon beside the header on the Podcast Settings screen.

**Comment by mattsherman** [comment]
@michaeldcain Thanks for the clarification!

**Comment by mattsherman** [comment]
Accepting this. Nice work!
