### ISSUE TITLE
Gutenberg: test published packages

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#26180]
The aim of this task is to spin up a Calypso test branch for each published Gutenberg package which should import some functionality from them and do simple function calls. We just want to check if everything is working as expected and provide feedback on the package if that's not the case. Optionally, we can consider adding integration tests for each package.

Here is the list of published packages to check:

* [x] `autop` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `a11y` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `api-fetch` (@vindl https://github.com/Automattic/wp-calypso/pull/26426)
* [x] `blob` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `blocks` (@vindl https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `block-serialization-spec-parser` (@vindl https://github.com/Automattic/wp-calypso/pull/26427)
* [x] `core-data` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `components` (@mmtr #26088 and #26314)
* [x] `compose ` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26203, @mmtr subdep in #26088)
* [x] `data` (@vindl https://github.com/Automattic/wp-calypso/pull/26203)
* [x] `date` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `deprecated` (@vindl https://github.com/Automattic/wp-calypso/pull/26203 and https://github.com/Automattic/wp-calypso/pull/26316, @mmtr subdep in #26088 and #26314)
* [x] `dom` (@mmtr subdep in #26088 and #26314, @vindl subdep in https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `editor` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `element` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26203 and https://github.com/Automattic/wp-calypso/pull/26316, @mmtr subdep in #26088 and #26314)
* [x] `hooks` (@vindl https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `html-entities` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `i18n` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `is-shallow-equal` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26203 and https://github.com/Automattic/wp-calypso/pull/26316)
* [x] `keycodes` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [ ] `library-export-default-webpack-plugin`
* [x] `nux` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `url` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `plugins` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [ ] `utils`
* [x] `viewport` (@vindl https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `wordcount` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26438)
* [x] `shortcode` (@vindl subdep in https://github.com/Automattic/wp-calypso/pull/26316)

And here are the packages that haven't been published yet:

* [ ] `core-blocks` 

Note: I've used the package list from https://github.com/WordPress/gutenberg/issues/3955 as a reference.

**Comment by mmtr** [comment]
It's nice to see this going forward.

FYI, I'm currently taking a look at the `components` package in #26088

**Comment by gziolo** [comment]
https://www.npmjs.com/package/@wordpress/blocks was published on Friday and all other packages had patch release with improved list of dependencies which contains Babel runtime from now on.

**Comment by gziolo** [comment]
It’s also worth mention that api-request was renamed to https://www.npmjs.com/package/@wordpress/api-fetch. It still depends on jQuery but we want to fix it at some point.

**Comment by vindl** [comment]
Resolved with https://github.com/Automattic/wp-calypso/pull/26438.
