### ISSUE TITLE
Store: Intl labels: What packages does USPS accept?

### ISSUE THREAD

**Issue by v18** [Automattic/wp-calypso#26265]
When shipping international labels, what types of packages does USPS allow merchants to use?

The USPS doc (https://www.usps.com/international/preparing-international-shipments.htm) mentions these packages and requirements for international shipments:

- USPS-produced Priority Mail International® Box
- If not the USPS intl priority mail box, then the total girth (distance around the thickest part) of your package is up to 108"

We don't currently let users add international labels here:

<img width="644" alt="screen shot 2018-07-23 at 2 15 28 pm" src="https://user-images.githubusercontent.com/11487924/43095148-de5f6174-8e82-11e8-8a5e-125674edfbc9.png">

Similarly, there are restrictions on envelopes. Are we following these restrictions? 

# Todos
- [ ] are we correctly following the restrictions for international shipments?
- [ ] add international service packages
- [ ] disallow any package not allowed in the drop-down menu while purchasing an international label

**Comment by jeffstieler** [comment]
Considering this a nice to have, and perhaps we should add some notice explaining why there aren't any rates showing up (useful for domestic shipments as well).
