### ISSUE TITLE
Importers: Flux & Component state > Redux

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#26512]
In anticipation of using our importers in places other than their current place, we want to split their components up for reuse. In order to reach that goal we'll need to make our state more accessible, both in terms of consumption and updating via actions.

Right now the state representing our importers and the importers UI is split between a Flux store and component state that drills down to components that need it. We can improve this greatly by moving this state and state handling to redux.

## TODO

- [ ] [Finalize top-level state tree slug](https://github.com/Automattic/wp-calypso/pull/26502#discussion_r216759637)
- [ ] Write tests for actions, reducers, selectors, & utils
- [ ] ...? (finish this list)

**Comment by jblz** [comment]
@spen Can you please add some details re: the plan for state here and or link a PR when you get sec?

I started a list in this issue, but we can split out separate issues if needed.

**Comment by spen** [comment]
Hey, sure!

It's taken some twists but I think I've settled on the idea of leaving the old (flux) state alone and just build out the new signup flow independently - idea being that we replace the existing code entirely with the new. That'll include the UI and the state, hopefully with the unified 'give us what you have' type input UI that's been mentioned a few times.

In the meantime, as we'll likely want parity between the old and new UI states we should be able to use the redux-bridge utils to do so.

That is assuming that the plan is still to trigger an import before landing in Calypso

**Comment by creativecoder** [comment]
@spen @jblz Given our new plan to use existing import screens within settings after signup, if/how is this task still relevant?

**Comment by jblz** [comment]
This is now one of those "fix it along the way if it's not too much effort" kind of chores.

**Comment by spen** [comment]
It's definitely something that needs to be done at some point IMO.
I think a full re-write will be considerably easier once we have good motive for doing so - when we come to build an improved UI in the future for instance.

**Comment by creativecoder** [comment]
I believe this is resolved by https://github.com/Automattic/wp-calypso/pull/48213
