### ISSUE TITLE
Gutenberg: fix console errors and warnings

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#26643]
If you navigate to `/gutenberg/post/{siteSlug}` now you'll notice a couple of console warnings that need to be investigated and fixed:

- [ ] Components package: `Warning: Unsafe lifecycle methods were found within a strict-mode tree:` (https://github.com/WordPress/gutenberg/issues/9017)
- [ ] Editor package: `Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.` (https://github.com/WordPress/gutenberg/issues/9033)
- [ ] Editor package: `Warning: Unsafe lifecycle methods were found within a strict-mode tree:`  (https://github.com/WordPress/gutenberg/issues/9037)
- [x] When adding a new block - `Uncaught (in promise) TypeError: Cannot read property 'rest_base' of undefined` - I believe this is related to mocked API response for `wp/v2/types` and should be resolved in https://github.com/Automattic/wp-calypso/issues/26639.
- [x] When adding a new block - `Uncaught SyntaxError: Unexpected token <`. (https://github.com/Automattic/wp-calypso/pull/27877)

**Comment by vindl** [comment]
I started an issue in Gutenberg repo to resolve the deprecated lifecycle warning, since it's coming from the Components package: https://github.com/WordPress/gutenberg/issues/9017

**Comment by vindl** [comment]
One more issue in Gutenberg repo for invalid DOM nesting in editor package: https://github.com/WordPress/gutenberg/issues/9033
