### ISSUE TITLE
Media Library: Add upgrade nudge when user attempts to upload an unsupported audio file

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#26803]
When a customer attempts to upload an any supported audio file not included in their plan (in other words, they are on a Free plan), they currently receive a message that the file type is not supported.

<img width="1112" alt="media-library-dead-end" src="https://user-images.githubusercontent.com/2098816/44410659-ee507c00-a532-11e8-9fb5-49f0657b1920.png">

Instead, they should be shown an upgrade nudge letting them know that if they upgrade their plan they will be able to upload audio files.

<img width="779" alt="screen shot 2018-08-21 at 11 13 07 am" src="https://user-images.githubusercontent.com/2098816/44410849-44bdba80-a533-11e8-96cd-71101f2bf4ae.png">

### Tasks

- [ ] Update check in https://github.com/Automattic/wp-calypso/blob/master/client/lib/media/utils.js#L259 to include audio files
- [ ] Update nudge wording to reflect that it covers video and audio files
- [ ] Update styling of nudge to add padding

**Comment by creativecoder** [comment]
Related to #9186. See comment (https://github.com/Automattic/wp-calypso/issues/9186#issuecomment-274531834).

**Comment by creativecoder** [comment]
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/1699996/109445798-03f96300-7a06-11eb-960e-51ddd7188bf1.png">

This has been resolved.
