### ISSUE TITLE
Purchases: Analytics

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#271]
We should add some analytics for the /purchases section.

Quick list of ones we should include for launch:

**Main:**
- [x] Viewed Purchases Page
- [x] Viewed Purchase Details Page (properties: product_type) (#475)

**Cancelations:**
- [x] Viewed Cancel Page (properties: product_type) (#475)
- [x] Viewed Cancel Confirmation Page (properties: product_type) (#475)
- [x] Clicked Cancel Page Support Link (properties: product_type) (#479)
- [x] Submitted Cancel Confirmation Form (properties: product_type) (#480)
- [x] Product Canceled (auto-renew disabled) (properties: product_type, days_since_purchase) (`D552-code`)
- [x] Product Canceled (refunded) (properties: product_type, was refunded, days_since_purchase) `D560-code`

**Edit Payment Method:**
- [x] Viewed Edit Payment Method Page (#475)
- [x] Submitted Edit Payment Method Form (#484)

**Renewals:**
- [x] Clicked Renewal CTA (properties: product_type) -- _How should we handle this with all the various notices and entry points?_ (#487)
- [x] Viewed Checkout Page (properties: is_renewal?, referrer?) -- This already exists as `calypso_checkout_page_view`, should we add a renewal flag property so we can track the funnel? (#495)
- [x] Product Renewed (properties: product_type, is_manual_renewal, days_before_expiration) (`D561-code`)

I've included some suggested properties we might want to send so we can properly segment this data. 

We can add more granularity later if needed, but I think this will cover the basic funnels related to this section.

**Comment by scruffian** [comment]
There are still some outstanding tasks on this. reopening.

**Comment by drewblaisdell** [comment]
I added a patch and separated the checkboxes for when a product is canceled and refunded or has auto-renew disabled. @scruffian Would you mind reviewing `D560-code`?

**Comment by scruffian** [comment]
Reopening

**Comment by scruffian** [comment]
All server side patches deployed. Closing this
