### ISSUE TITLE
Themes: View a theme's title and author

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#2875]
Let's show the theme's title and author in an obvious manner. This is a kick-off issue, and has an emphasis on initial architecture. As always in this milestone, this needs to be server-side-renderable from the start.

**TODO:**
- [x] Decide on data architecture — deferring until LRM, going to use 1.1 endpoint for now
- [x] Decide on whether we need layout-last routing — _YES WE DO_
- [x] `Sub[Master]Bar` component CSS + markup #3053
- [ ] ~~Theme Details 1.2 REST endpoint, which gets its data from ES.~~
- [x] Reducer/selectors/fetchers for title and author #3011
- [x] Bootstrap stores on the server, ignore caching for now #3279

**UI**:
![screen shot 2016-01-21 at 12 54 46](https://cloud.githubusercontent.com/assets/215074/12644996/befa7d26-c5be-11e5-904d-ad2a82f69bc4.png)
![screen shot 2016-01-21 at 12 55 02](https://cloud.githubusercontent.com/assets/215074/12644997/c3c6134c-c5be-11e5-802a-f911cd044776.png)

**Comment by ockham** [comment]
> * [ ] Theme Details 1.2 REST endpoint, which gets its data from ES.
> * [ ] Reducer/selectors/fetchers for title and author

I think we could get some working skeleton quickest if we wrote a `theme-details` reducer and selectors that we connect to the exisiting 1.2 endpoint (which gives us name and author) for now, and re-wire to the new Details endpoint afterwards.

**Comment by ehg** [comment]
> I think we could get some working skeleton quickest if we wrote a theme-details reducer and selectors that we connect to the exisiting 1.2 endpoint (which gives us name and author) for now, and re-wire to the new Details endpoint afterwards.

Yep, I can see us going that way initially. It'd be useful to have a think about the details API early on, so we don't keep adding fields to the list endpoint.

**Comment by ehg** [comment]
I think we need to optimistically load theme details on hover in the theme list, otherwise it'll be slooow.
