### ISSUE TITLE
Themes: See a screenshot in the sheet view

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#2876]
We should show a fairly big screenshot on the theme sheet page. Let's also start to consider how and what we'd like to cache.

**TODO**:
- [x] Screenshot markup/css/component #3053
- [x] Hook up screenshot to actual data #3279
- [x] Consider caching. Do we cache the REST responses & the markup? How do we cache, memcache? #3279
- [x] Initial cache implementation #3279

**UI**:
![screen shot 2016-01-21 at 18 36 08](https://cloud.githubusercontent.com/assets/215074/12645262/c769f002-c5c0-11e5-9c00-d463e672a098.png)
![screen shot 2016-01-28 at 13 14 35](https://cloud.githubusercontent.com/assets/215074/12645318/3262fe44-c5c1-11e5-8682-7ed7cd0d1509.png)
