### ISSUE TITLE
Settings: Clean up unnecessary Jetpack version checks

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#29888]
As suggested in https://github.com/Automattic/wp-calypso/pull/29597#discussion_r243597295 we can already clean the old Jetpack version checks in site settings. We support the current and the previous version of Jetpack, so the previous ones are no longer relevant.

cc @keoshi 

List of all the places where we need to clean up version checks:

* [x] client/my-sites/site-settings/composing/index.jsx - #30017
* [x] client/my-sites/site-settings/form-analytics.jsx - #30042
* [x] client/my-sites/site-settings/form-discussion.jsx - #30022
* [x] client/my-sites/site-settings/form-general.jsx - #30024
* [x] client/my-sites/site-settings/form-security.jsx - #30023
* [x] client/my-sites/site-settings/form-writing.jsx - #30037
* [x] client/my-sites/site-settings/jetpack-dev-mode-notice.jsx - #30020
* [x] client/my-sites/site-settings/manage-connection/api-cache.jsx - #30028
* [x] client/my-sites/site-settings/manage-connection/data-synchronization.jsx - #30029
* [x] client/my-sites/site-settings/manage-connection/public-post-types.jsx - #30030
* [x] client/my-sites/site-settings/manage-connection/site-ownership.jsx - #30031
* [x] client/my-sites/site-settings/seo-settings/form.jsx - #30039
* [x] client/my-sites/site-settings/seo-settings/site-verification.jsx - #30038
* [x] client/my-sites/site-settings/settings-performance/main.jsx - #30040
* [x] client/my-sites/site-settings/settings-traffic/main.jsx - #30041
* [x] client/my-sites/site-settings/speed-up-site-settings.jsx - #30040
* [x] client/my-sites/site-settings/wrap-settings-form.jsx - #30012
* [ ] Delete `siteSupportsJetpackSettingsUi` selector - #30757
* [x] Delete `siteSupportsGoogleAnalyticsIPAnonymization` selector - #30755
* [x] Delete `siteSupportsGoogleAnalyticsBasicEcommerceTracking` selector - #30755
* [x] Delete `siteSupportsGoogleAnalyticsEnhancedEcommerceTracking` selector - #30755

Note: while this might make things work in an unexpected way for sites with older Jetpack, we no longer support those versions and such users should be recommended to update to the latest Jetpack version.

**Comment by tyxla** [comment]
While this isn't of high priority, the related PRs remove a bunch of unnecessary code from Calypso. It would be a shame to not land them, especially given how straightforward most of them are. I've already requested reviews from my team (@Automattic/luna) but most of us are working on other things. I wonder if I could get some reviews from someone else interested. Perhaps @Automattic/team-calypso ?

**Comment by tyxla** [comment]
Thanks a bunch for all the reviews Jarda 🙇
