### ISSUE TITLE
Migrate from Picasa to Google Photos

### ISSUE THREAD

**Issue by johngodley** [Automattic/wp-calypso#29965]
The Picasa API is being disabled, and we need to move to the Google Photos API.

All the PRs relevant to that will be listed here. Changes are also required on the server, which are not listed here.

Before we switch:
- [x] ~~#29935 Add token error state~~
- [x] ~~#29937 Add migration notice~~
- [x] #29939 Inline migrate picasa to google photos
- [x] ~~#30366 Add migration notice to sharing page~~

After we switch:
- [x] #29966 Update Picasa restrictions

Enhancements:
- [x] #25762 Date range filter 
- [x] #30365 Update copy and icon - if we are allowed to use Google Photos branding

Fixes #24952
Fixes #22681
