### ISSUE TITLE
Themes: Sheet actions bar

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3160]
We want to see a theme’s cost, be able to download it, and activate/choose/customize it or go back to the previous view.

**TODO:**
- [x] Markup + CSS #3333
- [x] Back button goes back a page (browser history?) #3333
- [x] 'Start with this design' button can also 'Customize', 'Activate' or 'Purchase & Activate' #3333
- [x] Show the cost #3333

**UI:**
![screen shot 2016-01-21 at 12 55 38](https://cloud.githubusercontent.com/assets/215074/12884258/f3910c82-ce54-11e5-8080-acc77490593a.png)

![screen shot 2016-01-21 at 12 55 58](https://cloud.githubusercontent.com/assets/215074/12884248/e0a8bec6-ce54-11e5-8cd3-d63427368bc0.png)
