### ISSUE TITLE
Themes: Sheet details view

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3161]
We want to view a theme's general, support and documentation pages.

**TODO:**
- [x] `SectionNav` that allows switching between pages #3333
- [x] Render HTML into content div #3279 — heavily restrict tags, try to avoid setting HTML dangerously TBD
- [ ] ~~Clean markup, do we need a new endpoint for this?~~

**UI:**
![screen shot 2016-01-21 at 13 00 09](https://cloud.githubusercontent.com/assets/215074/12884657/b664fd70-ce57-11e5-97d0-4d5a31e4f6cb.png)
![screen shot 2016-01-21 at 12 59 24](https://cloud.githubusercontent.com/assets/215074/12884694/e0ee0c94-ce57-11e5-9ba4-07a48641e3af.png)

**Comment by ockham** [comment]
> Render HTML into content div #3279 — heavily restrict tags, try to avoid setting HTML dangerously TBD

Maybe we can re-use code from Reader for that?

**Comment by seear** [comment]
Markup comes output-buffered from theme.wordpress.com blog, so should be trusted.
