### ISSUE TITLE
Themes: Sheet live preview

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#3162]
We should open a preview on the theme sheet page.

**TODO:**
- [x] Add preview link
- [x] When preview link is clicked, open a `WebPreview` overlay with the theme's demo site
- [x] Buttons: "Pick this design" | "Try & Customize"
- [ ] Look into remaining problems on mobile safari [1]

**UI:**
![screen shot 2016-03-02 at 12 51 01](https://cloud.githubusercontent.com/assets/4389/13460823/741e6926-e075-11e5-9a54-f2b46b6776f7.png)

For mobile:
![screen shot 2016-05-23 at 11 45 38](https://cloud.githubusercontent.com/assets/7767559/15468393/f49cc6d2-20db-11e6-846b-bab5717d3386.png)

**Comment by folletto** [comment]
Design reference:
 
![tshowcase-m4-m7-livepreview-i3](https://cloud.githubusercontent.com/assets/4389/13503852/7dd5e15c-e169-11e5-88a2-4b8bb3935472.png)

The button changes depending if the user is logged in or logged out.

**Comment by seear** [comment]
Done #5482
