### ISSUE TITLE
Support User: Improvements for keyboard users

### ISSUE THREAD

**Issue by jordwest** [Automattic/wp-calypso#3201]
When using the keyboard to activate support user, two improvements would allow interaction without touching the mouse:

 - [x] The **Username** field should be focused when the dialog appears (#3244)
 - [x] Pressing enter should go to the next field when the username field is focused (#3243)
 - [x] Pressing enter should submit the form when the password field is focused (#3243)
 - [x] Pressing escape should close the dialog when any field is focused (#3243)

**Comment by marekhrabe** [comment]
Hi @jordwest, all mentioned PRs are merged. They should be marked accordingly in this issue. I found another small improvement and created a PR: 

- [ ] Focus password input after unsuccessful login request (#5603)

After that, we might want to close this.

**Comment by jordwest** [comment]
Thanks @marekhrabe!
