### ISSUE TITLE
(5P) FSE: verticals - add preview image to template response

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#33453]
(See `D28788-code` and https://github.com/Automattic/wp-calypso/issues/33452.)

- [ ] Create screenshot thumbnails and save them to a site.
- [ ] Use headstartdata or create a content site if necessary.
- [ ] Update headstart post meta to associate them with their templates.
- [ ] Research which scripts need to be modified to bring post meta into json files.

## Todo
- [ ] Ensure new post meta is **_not_** automatically copied to the sites by HS `p1559827350013200-slack` (as requested by @michaeldcain 
- [ ] Run the HS unit tests (see HS `README.md`)

See also https://github.com/Automattic/wp-calypso/issues/33697

**Comment by getdave** [comment]
@iamtakashi As discussed you will create the screenshots and (ideally) a mockup for us to follow.

**Comment by iamtakashi** [comment]
@getdave I sent both versions (3:4) & (4:3) to you via slack. I personally prefer (3:4) as it feels more they are pages as opposed to sections or blocks. But I'll understand if scrolling is a concern or simply it's too late to change the ratio from now :)
