### ISSUE TITLE
(5P) FSE: Add template selection tracking

### ISSUE THREAD

**Issue by obenland** [Automattic/wp-calypso#33489]
Todo:
- [x] Save template slug to meta so we can later use it #33645
- [x] Add Tracks calls #33784
- [x] Load Tracks library and initialize it with user and site #33877 
- [x] Figure out how to track page publishing from template - separated into #33880

Also see `PCYsg-4KT-p2`

**Comment by marekhrabe** [comment]
To ensure compatibility across platforms, let's leverage tracing code from Jetpack. Tracks are [used there](https://github.com/Automattic/jetpack/blob/43dd797dc951686a7aab3d62e7244f1ed23a0c64/_inc/lib/tracks/client.php).

**Comment by apeatling** [comment]
Based on these events I can work on the funnels that will use them. I'll add ideas to a P2 thread and follow up here.
