### ISSUE TITLE
Full Site Editing: Explore options for linking to the header editor

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#33511]
We will use the Block Editor to edit either the page content, or site header `template_part`, one at a time.

Requirements:
- Do not fork or create a new implementation of edit-post
- Do not save placeholder artifacts to post_content
- "Creative" solutions may be examined if they can be improved in the future.

Starting from site creation or any page edit link with the related child theme:

### Subtasks

- [x] https://github.com/Automattic/wp-calypso/issues/33627 display header preview alongside page content
- [x] https://github.com/Automattic/wp-calypso/issues/33628 add Edit button to Header template part on hover
- [x] https://github.com/Automattic/wp-calypso/issues/33629 header changes pre-publish confirmation 
- [x] https://github.com/Automattic/wp-calypso/issues/33632 back button navigation after editing header 
- [x] https://github.com/Automattic/wp-calypso/issues/33633 prevent direct access to `wp_template` and `wp_template_part` CPTs
- [x] https://github.com/Automattic/wp-calypso/issues/33636 prefill Header template part with default data
- [x] https://github.com/Automattic/wp-calypso/issues/33512 replace the Visual Header

**Comment by vindl** [comment]
This can probably be further decomposed in the following tasks - these could be handled in separate PRs:

- [ ] Show both preview blocks on the same page (can probably be resolved by just loading the parent `wp_template` CPT in the editor, although I'm open to other suggestions, similar to the ones from Editor in Editor exploration).
- [ ] Populate `Content Slot` block on load with the contents of the correct page (for example, we could do this by passing the `page_id` as a URL parameter).
- [ ] Display `Edit` button on hover of the `Template Part` block and make sure it opens up the correct `wp_template_part` CPT in the editor.
- [ ] Display `Edit` button on hover of the `Content Slot` block and make sure it opens up the correct page in the editor.
- [ ] Provide a way to return from the Header editing mode to the full page editing view. 
- [ ] Provide a way to return from the Page content editing mode to the full page editing view.

**Comment by apeatling** [comment]
<img width="509" alt="Screen Shot 2019-06-04 at 11 04 25 AM" src="https://user-images.githubusercontent.com/1464705/58902728-8978a380-86b8-11e9-80fc-92537c492f95.png">

I think we should avoid a dialogue here and use the Gutenberg paradigm of showing a message pre-publish in the sidebar. We also then don't have to invent something new.

**Comment by apeatling** [comment]
This should be implemented in a way that all edit page links that currently exist will enter the user at step 2.

**Comment by apeatling** [comment]
I'd like to see this broken out into separate issues that will allow better sharing across team members, the two teams, and easier estimating.

**Comment by gwwar** [comment]
@vindl @rodrigoi let's us this one to represent the user flow and add separate technical tasks for the work noted. Please share early work if there are any questions on potential flows / options as you run into decision points.

**Comment by vindl** [comment]
> I'd like to see this broken out into separate issues that will allow better sharing across team members, the two teams, and easier estimating.

@apeatling @gwwar I've broken this down into separate issues based on the latest designs available in Figma, and updated the issue summary. Let me know if you think that some subtask is missing in that list.

**Comment by vindl** [comment]
Closing this since the related subtask issues have been resolved too.
