### ISSUE TITLE
Full Site Editor: Dynamic Block Site Logo upload Image

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34009]
Please work on https://github.com/Automattic/wp-calypso/issues/34006 first. **ONLY** take this if we move forward with the dynamic block approach.

As a follow up to https://github.com/Automattic/wp-calypso/pull/33714:

- [ ] https://github.com/Automattic/wp-calypso/issues/34010 Add an endpoint that returns site logo attachment id, url, and related dimensions
- [ ] https://github.com/Automattic/wp-calypso/issues/34011 Add an endpoint that allows updating of site logo set on the theme. eg `get_theme_mod( 'custom_logo' );` (see the current customizer flow in site-identity for hints).
- [ ] https://github.com/Automattic/wp-calypso/issues/34012 Add in a related hook to the Calypso media modal and core media modal. Ping @rodrigoi for help on this if folks get stuck.

Site Logos are theme customizations and are set per theme. (If you switch a theme, a site logo is lost, and you need to re-set this).

If we need to create a related plugin endpoint, extra work is required to map that on wpcom appropriately. This will 404 otherwise.

https://developer.wordpress.org/themes/functionality/custom-logo/

**Comment by gwwar** [comment]
We've decided to use core blocks instead, closing these related tasks.
