### ISSUE TITLE
FSE: CoBlocks Audit v1.11.0 [5]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#34448]
Audit of CoBlocks https://github.com/godaddy/coblocks/releases/tag/1.11.0

- Does it work on Gutenberg Master?
- Does it work with Simple/Atomic?
- Security concerns?

Blocks 
=====

Please put your handle next to the block you're auditing.

- [ ] ~Accordion Block @glendaviesnz (waiting for IE11 VM to download to test polyfill)~
- [x] ~Alert Block @glendaviesnz~
- [x] ~Author Profile Block @glendaviesnz~
- [ ] Buttons Block
- [ ] Carousel Gallery Block
- [ ] Click to Tweet Block
- [ ] Dynamic Separator Block
- [ ] Features Block
- [ ] ~Form Block~
- [ ] ~Gif Block~
- [ ] GitHub Gist Block
- [ ] Hero Block  
- [ ] Highlight Block
- [ ] Icon Block
- [ ] Map Block
- [ ] Masonry Gallery Block
- [ ] Media Card Block
- [ ] Pricing Table Block
- [x] Resizable Row/Columns Blocks (@mmtr)
- [x] Shape Divider Block (@mmtr)
- [x] ~Social Sharing Block (@mmtr)~
- [x] Stacked Gallery Block (@mmtr)

cc @apeatling  @iamtakashi please strikethrough blocks that we _do not_ need on Simple Sites. 

paAmJe-wx-p2

A summery of the audit results can be found at paAmJe-wH-p2

**Comment by mmtr** [comment]
D30133-code should help with testing in Simple sites.

**Comment by kwight** [comment]
With our [updated implementation](https://github.com/Automattic/wp-calypso/issues/34466), security concerns need only be reviewed within the block code itself (`/src/blocks/:block` in the plugin).

**Comment by gwwar** [comment]
Going to go ahead and close this, since the audit was performed.
