### ISSUE TITLE
(?P) Add e2e tests to the SPT Plugin

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#34623]
Task to add automated e2e testing to the Plugin using Calypso's inbuilt e2e testing suite.

https://github.com/Automattic/wp-calypso/tree/master/test/e2e

## Tasks

- [ ] Get local testing up and running and improve Calypso documentation as required
- [ ] Write basic spec to create Page and validate presence of Template selector.
- [ ] Write suite of tests to cover selecting, inserting...etc

**Comment by frontdevde** [comment]
Closing as per https://github.com/Automattic/wp-calypso/pull/34629#issuecomment-511315325
