### ISSUE TITLE
FSE: Support other business themes

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#34733]
_Note: each subtask has been updated with all of the remaining tasks for supporting FSE, not just the footers._

The headers for business themes have been addressed in https://github.com/Automattic/wp-calypso/issues/34387

The footers also need an update. I suggest that outside of the template part block we continue to render the `[Site Name], Proudly powered by WordPress.` inside the actual theme's footer.php file. This will allow us to avoid having to deal with higher paid plans and the ability to remove this. We can scope that work out after this first launch.

I've asked @iamtakashi for reference visuals for all of the business theme footers, and I'll update here once I have that.

**Update** Modern Business is done in https://github.com/Automattic/themes/pull/1094

**Updated**: I converted this into an epic, folks should take the issues below that are more granular:

- [ ] Elegant Business: https://github.com/Automattic/wp-calypso/issues/34916
- [ ] Friendly Business: https://github.com/Automattic/wp-calypso/issues/34914
- [ ] Sophisticated Business: https://github.com/Automattic/wp-calypso/issues/34913
- [ ] Calm Business: https://github.com/Automattic/wp-calypso/issues/34912
- [ ] Professional Business: https://github.com/Automattic/wp-calypso/issues/34911

Important linked issues: https://github.com/Automattic/wp-calypso/issues/35399, https://github.com/Automattic/wp-calypso/issues/35059

**Comment by apeatling** [comment]
Footer visuals from Takashi:

![footers](https://user-images.githubusercontent.com/1464705/61416356-465d4300-a8a8-11e9-8c3c-212d307f4447.png)

**Comment by apeatling** [comment]
@vindl Re: 

> I suggest that outside of the template part block we continue to render the [Site Name], Proudly powered by WordPress. inside the actual theme's footer.php file. 

Are you able to handle this in a separate issue? With the footer.php changes this is hidden now with the dynamic footer. It needs to be present for both.

**Comment by vindl** [comment]
> Are you able to handle this in a separate issue? With the footer.php changes this is hidden now with the dynamic footer. It needs to be present for both.

@apeatling sure, I'll look into that.

**Comment by vindl** [comment]
Separated this out into multiple issues (one per theme) and linked them in the summary.

**Comment by apeatling** [comment]
Update: There will be more than just updating footers, so the issues will need to be updated accordingly.

**Comment by apeatling** [comment]
I'm moving this one to Not Doing, because we have decided that updating the other business themes is not a good next step.

Instead we are going to update the base theme, and then look at Stratford as a next theme based on paAmJe-Ik
