### ISSUE TITLE
Editor: Support Inserting Page Section Blocks

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35403]
Allow our customers to easily modify page templates (or construct their own) by inserting prebuilt “page sections” into the editor.

**Sections: Research technical options**
paAmJe-lL

**Examples in the wild**
Take a look at how Kioken handles page sections for constructing and editing page templates: https://www.youtube.com/watch?v=Mi4oixuQ__Q

**Tasks**

- [ ] Analyze existing page templates, and home page templates for all new template-first themes. Identify unique page sections that can be extracted.
- [ ] Extract each page section unit as a post in `wp_blocks`. This will allow easy combinations for the alternative templates to be made easily.
- [ ] Reconstruct all page templates using these page sections.
- [ ] Expose page sections in the block inserter under a “Sections” category so that users can insert, delete, and move whole sections.

**Comment by apeatling** [comment]
Moved this one to "Not Doing" as discussions with Matias have led us to moving this to a done-in-core project.

**Comment by apeatling** [comment]
This is something that will need to be worked on via core, as it's a foundational part of the FSE efforts there.

**Comment by shaunandrews** [comment]
The (current) Core issue for this, which they're calling "Block Patterns": https://github.com/WordPress/gutenberg/issues/17335

**Comment by noahtallen** [comment]
Accidentally closed this :)

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress Block Patterns, here: WordPress/gutenberg#17335
