### ISSUE TITLE
FSE: Navigation Block Improvements

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35544]
We need more advanced navigation block that will allow:

- [ ] Adding, removing, and reordering navigation items.
- [ ] Allow linking directly to navigation items to change what you are editing in the editor view. See: https://github.com/Automattic/wp-calypso/issues/35177
- [ ] Adding items to the navigation menu that are not pages.
- [ ] Showing sub menu items, not just on the front end.

This points to the navigation block work being done in core, and contributing to and using the work happening there.

**Comment by jordesign** [comment]
With the new Navigation block now landing in core - does it make sense to review whether we should default to this for FSE?

https://make.wordpress.org/core/2019/11/27/whats-new-in-gutenberg-27-november/

**Comment by apeatling** [comment]
We will make this the default for FSE going forward, but gradually as we update themes. /cc @vindl

**Comment by vindl** [comment]
> We will make this the default for FSE going forward, but gradually as we update themes. /cc @vindl

@apeatling is Ajax still planning to backfill the existing FSE sites and replace instances of A8C Navigation block?

**Comment by davipontesblog** [comment]
Closing in favor of the core WordPress FSE implementation in dotCom.
