### ISSUE TITLE
FSE: Add FSE support to Varia Base Theme

### ISSUE THREAD

**Issue by apeatling** [Automattic/wp-calypso#35632]
All of our template first themes are based on the Varia parent base theme. We need to update this theme with any FSE support that can be shared appropriately with all child themes.

Prerequisites are:

- [ ] #35519 Modern Business launch cleanup
- [ ] #35544 At minimum navigating and adding pages via the navigation block.
- [ ] #35622 FSE rolled out to 100% of Modern Business users.

**Comment by apeatling** [comment]
@Copons Since this was already added, we can probably close this one out?

**Comment by Copons** [comment]
Righto, totally missed this issue!

**Comment by apeatling** [comment]
No worries, it wasn't in the current sprint as slated for later.
