### ISSUE TITLE
PropTypes: Remove propType property access

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#35695]
Remove accessing component `propTypes` properties. This will allow for an optimization to strip `propTypes` from the production bundles.

- [x] [client/components/credit-card/index.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/components/credit-card/index.jsx) (#35918)
- [x] [client/components/gallery-shortcode/index.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/components/gallery-shortcode/index.jsx) (https://github.com/Automattic/wp-calypso/pull/35922)
- [x] [client/components/forms/multi-checkbox/index.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/components/forms/multi-checkbox/index.jsx) (#35871)
- [x] client/my-sites/media-library/list-item.jsx (#35783)
- [x] client/components/image-preloader/index.jsx (#35814)
- [x] client/components/infinite-list/index.jsx (#35771)
- [x] client/components/draggable/index.jsx (#35693)
- [x] client/components/forms/form-text-input-with-action/index.jsx (#35725)

It's also a good opportunity to transition away from `propTypes` and to type components with TypeScript.

cc: @Automattic/team-calypso @Automattic/type-review @sgomes

**Comment by sirreal** [comment]
@jsnajdr @sgomes If the list in this issue was complete, we've removed all runtime usage of `propType` and could attempt applying the transform that strips `propTypes` from production bundles 🚀

**Comment by sirreal** [comment]
> @jsnajdr @sgomes If the list in this issue was complete, we've removed all runtime usage of `propType` and could attempt applying the transform that strips `propTypes` from production bundles 🚀

Attempting here: https://github.com/Automattic/wp-calypso/pull/37344 (collaboration/help appreciated).
