### ISSUE TITLE
Full Site Editing: Estimate how long it would take to support FSE flows for template first themes [2]

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#35792]
This is a task for estimation only! Please timebox this task to 2 days

Known Technical Tasks:
- [x] No hard-coded checks for themes. We should be able to dynamically mark that a new theme is ready for FSE, without updating committed code whitelists. https://github.com/Automattic/wp-calypso/issues/35794
- [x] Populate header/footer templates from the respective theme demo site https://github.com/Automattic/wp-calypso/issues/35708
- [x] Better scripts/Improving workflows around template content snapshotting https://github.com/Automattic/wp-calypso/issues/35795

Tidying up Logic on eligible/active:
- [ ] https://github.com/Automattic/wp-calypso/issues/35852
- [x] https://github.com/Automattic/wp-calypso/issues/35853 

New themes to audit for needed header/footer content and fidelity between Edit/Publish views:
- [ ] Shawburn (Launching on Aug. 29th)
- [ ] Rivington (Launching on Aug. 29th)
- [ ] Balasana (Launching on Aug. 29th)
- [ ] Maywood (Launching on Aug. 29th)
- [ ] Alves
- [ ] Exford
- [ ] Rockfield
- [ ] Stratford
- [ ] Coutoire
- [ ] Morden
- [ ] Stow
- [ ] Hever
- [ ] Leven
- [ ] Brompton
- [ ] Redhill
- [ ] ( @iamtakashi feel free to edit if y'all have more planned)

**Comment by Copons** [comment]
I've run a quick-ish audit of the Varia-based themes listed here and these are my findings.

Most themes look straightforward enough to make FSE-ready, with just some relatively minor tweaks on the styles (e.g. make sure the colors are correct, and the navigation menus look good in both header and footer) or the overridden files (we need to add some FSE code to render the template blocks instead of the original theme parts).
Some of them, marked with a ⚠️, will be more challenging.

Many of these themes have an headstart folder. I don't know its purpose and have no idea of its implications with FSE, if any.

This said, without actually starting to add FSE support to these themes, it's quite hard to identify possible unforeseen complications (e.g. style overrides that could conflict with Gutenberg).

## [Maywood](https://maywooddemo.wordpress.com/)

- **Navigation Menu**: only in the header.
- **Footer**: only contains the site title.

## [Alves](https://alvesdemo.wordpress.com/)

- **Header**: 2 columns responsive.
- **Navigation Menu**: different in header and footer.
- **Footer**: 2 columns.
- **Overrides**: `footer.php`, but it looks identical to the Varia one, so we might be able to delete it.

## [Exford](https://exforddemo.wordpress.com/)

- **Footer**: 2 columns responsive.
- **Headstart**: yes.

## ⚠️ [Rockfield](https://rockfielddemo.wordpress.com/)

- **Header**: 2 columns; inverted colors; inline site title and description which disappears on small screens.
This might be hard to replicate in the editor.
- **Overrides**: `header.php` and `footer.php`.
- **Headstart**: yes.

## [Stratford](https://stratforddemo.wordpress.com/)

- **Header**: 2 columns; no site description.
- **Navigation Menu**: only in the header.
- **Overrides**: `header.php` and `footer.php`.
- **Headstart**: yes.

## ⚠️ [Coutoire](https://coutoiredemo.wordpress.com/)

- **Header**: 2 columns; no space between site title and tescription.
They will look different in the editor: we can't remove the blocks' vertical margin as it would misplace the Inserter button.
- **Navigation Menu**: different in header and footer.
- **Footer**: 2 columns responsive.
- **Overrides**: `header.php`.
- **Headstart**: yes.

## [Morden](https://mordendemo.wordpress.com/)

- **Header**: 2 columns responsive; inverted colors.
- **Footer**: 2 columns responsive.
- **Overrides**: `header.php`.
- **Headstart**: yes.

## [Stow](https://stowdemo.wordpress.com/)

- **Navigation Menu**: different in header and footer; in the header is full width with a pink background.
- **Footer**: 2 columns responsive.
- **Overrides**: `header.php`.
- **Headstart**: yes.

## [Hever](https://heverdemo.wordpress.com)

- **Header**: 2 columns responsive.
- **Footer**: 2 columns responsive.
- **Headstart**: yes.

## [Leven](https://levendemo.wordpress.com)

- **Header**: 2 columns.
- **Footer**: 2 columns responsive.
- **Headstart**: yes.

## ⚠️ [Brompton](https://bromptondemo.wordpress.com/)

- **Header**: 3 columns responsive; inverted colors; colored borders.
Has a circle larger than the container that overlaps both the content below and the padding above. I expect it won't be easy to recreate in the editor.
- **Navigation Menu**: only in the header.
- **Footer**: inverted colors; colored borders; only contains the site title.
- **Overrides**: `footer.php`.
- **Headstart**: yes.

## [Redhill](https://redhillthemedemo.wordpress.com/)

- **Navigation Menu**: only in the header.
- **Footer**: only contains the site title.
- **Headstart**: yes.

**Comment by iamtakashi** [comment]
Headstart is used to populate a new site that's created from the logged out Showcase and the activation bar at the top of the demo site. There might be more flows that use Headstart, and @michaeldcain or @davidakennedy can answer better than me.

<img width="323" alt="Screen Shot 2019-08-29 at 00 16 31" src="https://user-images.githubusercontent.com/908665/63898923-ca036700-c9f2-11e9-874d-ee51a2e66471.png">

<img width="1280" alt="Screen Shot 2019-08-29 at 00 17 12" src="https://user-images.githubusercontent.com/908665/63898926-ce2f8480-c9f2-11e9-9d6a-02a2f4f135f8.png">

**Comment by vindl** [comment]
2 weeks.
