### ISSUE TITLE
Full Site Editing: Varia/Maywood CSS Support

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#35870]
Since it's quickly becoming a bit too tangled for my brain, I'm going to track here all the tasks required for FSE, Varia, and Maywood to work well with each other.

- [x] Template Parts support for Varia and Maywood
https://github.com/Automattic/wp-calypso/pull/35698, https://github.com/Automattic/themes/pull/1309, D31833-code

- [x] Basic styling for Varia and Maywood
https://github.com/Automattic/wp-calypso/pull/35821, https://github.com/Automattic/themes/pull/1332, https://github.com/Automattic/themes/pull/1341

- [x] Update the Navigation block for Varia (see the differences in [header](https://github.com/Automattic/themes/blob/33eef2268bba09959ec411c185712b7b5133f94f/varia/header.php#L42-L60) and [footer](https://github.com/Automattic/themes/blob/33eef2268bba09959ec411c185712b7b5133f94f/varia/footer.php#L31-L41): we need to figure out how to have those same differences in FSE).
Make sure the Navigation block works appropriately on all screen sizes, in both editor and front end.
https://github.com/Automattic/wp-calypso/pull/35880, https://github.com/Automattic/themes/pull/1364

- [x] Style FSE blocks in the footer.
https://github.com/Automattic/themes/pull/1379

- [x] ~Do we need a block for the [site info](https://github.com/Automattic/themes/blob/33eef2268bba09959ec411c185712b7b5133f94f/varia/footer.php#L46-L57) in the footer? Some themes like Maywood have it inline with the navigation menu (or more precisely, the footer is a flex div with the site info at flex-start, and the navigation menu at flex-end), so we might want to display it in the editor too?~
See https://github.com/Automattic/wp-calypso/issues/34760

- [x] Adjust vertical spacing between header-title-content-footer.
https://github.com/Automattic/themes/pull/1371

- [x] Fix the FSE blocks text sizes in the editor on small screens.
https://github.com/Automattic/themes/pull/1381

- [x] Increase vertical spacing of the navigation menu in the footer (line height or items padding).
https://github.com/Automattic/wp-calypso/pull/35998, https://github.com/Automattic/themes/pull/1398

- [x] Center-align the site info (when in FSE context).
https://github.com/Automattic/themes/pull/1399

- [x] Make sure the template parts are `wide`-aligned.
https://github.com/Automattic/wp-calypso/pull/35999

- [x] Fix full-width blocks inside the Post Content block.
https://github.com/Automattic/wp-calypso/pull/36005, https://github.com/Automattic/wp-calypso/pull/36040

- [x] Manually resized images in template parts appear full-sized on the front-end.
https://github.com/Automattic/wp-calypso/issues/36020, https://github.com/Automattic/wp-calypso/pull/36026

- [x] On WPCOM there is an "Hide homepage title" option! Damn!
https://github.com/Automattic/themes/pull/1406

- [x] Fix FSE blocks style when inside a Cover block
https://github.com/Automattic/themes/pull/1418

- [ ] Follow up: Figure out if there's a better way (than [my approach](https://github.com/Automattic/themes/blob/33eef2268bba09959ec411c185712b7b5133f94f/varia/sass/full-site-editing/_editor.scss#L15-L22)) to decrease the blocks vertical spacing in the templates, in order to make them look more like the front end.

**Comment by apeatling** [comment]
> Do we need a block for the site info in the footer?

This can be punted for our testing release. We have an issue to turn this into a block. Like Modern Business it should be rendered on the front end in PHP by leaving it in footer.php.

https://github.com/Automattic/wp-calypso/issues/34760

**Comment by Copons** [comment]
> > Do we need a block for the site info in the footer?
> 
> This can be punted for our testing release. We have an issue to turn this into a block. Like Modern Business it should be rendered on the front end in PHP by leaving it in footer.php.
> 
> #34760

@apeatling Great thanks!
In the latest merged Maywood PR, I've arbitrarily made the footer `display: block` instead of `flex`.
This means that the site info doesn't inlines with whatever the footer's last block is (in the demo is the navigation menu, but in real life it won't necessarily be), but also that we leave full freedom of designing the layout in the editor (e.g. use the columns block for this kind of stuff).

**Comment by Copons** [comment]
Just for clarity: I'm keeping this issue open to have a centralized place to check what we have been doing for Varia/Maywood when we'll start tackling other themes.

So this is not a blocker issue anymore, and should not be closed before the 10% test.
The issues tracked here, on the other hand, they should be closed for the test!

**Comment by vindl** [comment]
Closing since all of the tasks have been completed. If new ones pop up we should document them in the above list.
