### ISSUE TITLE
Gutenboarding: i18n

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/wp-calypso#37665]
Gutenboarding should fully support a localized experience. MT: pbAok1-dn-p2

## Tasks

**Wip:**
- [ ] Creating a site with the name "테스트" works after D54000-code but we need to replicate #48031 for the launch flow in ETK as it also auto searches the blog name resulting in an instant error. #48399

**Todo:**

**Backlog:**
- [ ] Add new font pairings for non latin locales #43002

**Other teams:**
- [ ] [_low priority_] Gutenboarding: Load user provided translations #39493
- [ ] [_low priority_] Propagate locale slug through all log in flows: #23126
- [ ] Localize [support URL in launch flow summary step](https://github.com/Automattic/wp-calypso/blob/ec22864/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx#L165) (`localizeUrl( 'https://wordpress.com/help/contact' )`) (Logged in users will see a translated page, this is for logged out) #47947 - blocked, see: #48033
- [ ] Switch language picker on by setting `gutenboarding/language-picker` config entry to true or removing flag altogether. Relies on https://github.com/Automattic/wp-calypso/pull/46328 (not a blocker because we're releasing to existing users first)

**Done:**
- [x] Try using mshots for fetching vertically oriented screenshots in Gutenboarding (https://github.com/Automattic/wp-calypso/pull/43428)
- [x] Not all copy is updated when user switches languages #48196 #48232
- [x] Provide default blog name for /sites/new when providing non latin site titles. Skip domain step without providing ascii characters currently results in a ["something went wrong"](https://github.com/Automattic/wp-calypso/pull/48031#issuecomment-739734208) error on site creation. D54000-code
- [x] some copy isn't being queued for translation in ETK #47884 
- [x] Error handling for domain suggestions and non-Latin chars pbAok1-dn-p2#comment-3227 #48031
- [x] Non-latin character set handling for domain search: Don't auto search non-latin characters using the site name #48031 
- [x] Non-latin character set handling for domain search: Improve error handling by removing note about potential connection errors. (i.e. split the error conditions apart so the error message doesn't tell the user to refresh the page for a validation error) #47985
- [x] Gutenboarding: Localize support URL for HSTS required tooltip in domain suggestions https://github.com/Automattic/wp-calypso/issues/45610 #46670 #46998 #47564 #47492 #47567 #47570 #47612 #47613
- [x] illustration on domain step doesn't work on RTL languages #47490 #47891
- [x] should progress bars be filled from right-to-left? #47886
- [x] domain picker shows domain components in the wrong order in RTL locale #47885 #47889
- [x] Plan details are showing up untranslated (intermittent), there is a timing issue where we request `/plans/details` without a locale and with a locale around the same time, depending which one comes back first changes the outcomes, page: /new/features #47611 
- [x] Update Editing Toolkit to ensure the correct locale is passed to the `plans/details` API endpoint in the launch flow plans step as mentioned here: https://github.com/Automattic/wp-calypso/pull/46588#issuecomment-719196987 #47227
- [x] Move localizeUrl to a package (probably i18n-calypso) Depends on _Move language data to a package_ #46998
- [x] Localize domain suggestion shown in launch flow summary https://github.com/Automattic/wp-calypso/pull/44840#discussion_r468701391 #47178
- [x] Move language data to a package #46709
- [x] Ensure that the WPCOM Nux modal slides are translated https://github.com/Automattic/wp-calypso/pull/47136
- [x] Ensure code shipped from `./packages` (_without_ text-domain) works when shipped in Editor kit plugin (_with_ text-domain). context: pbAok1-1Ao-p2 Part of https://github.com/Automattic/wp-calypso/pull/46557 ?
- [x] Use translated plan feature lists either from `lib/plans` or API ([code](https://github.com/Automattic/wp-calypso/blob/366a96ac656d9e05e37ec4361eca2a11e8d15968/client/landing/gutenboarding/stores/plans/plans-data.ts)) in progress in #46588, endpoint deployed in D51380-code and D51895-code
- [x] Extract Gutenboarding language picker into @automattic/language-picker #46020 
- [x] Update style preview to generate template/demo endpoint url using current locale instead of path param #46793 
- [x] Get translated strings before rendering the page to avoid the current flicker of EN text at first load. (#46473)
- [x] Add `plans/details` endpoint (D51380-code)
- [x] RTL stylesheets #39592
- [x] Ensure Recoleta font works with all symbols of the language (https://github.com/Automattic/wp-calypso/issues/42522, https://github.com/Automattic/wp-calypso/pull/42814)
- [x] Gutenboarding: Set lang/dir in browser #39491 (Think this one is now redundant See [comment](https://github.com/Automattic/wp-calypso/issues/39491#issuecomment-711904463))
- [x] [?check if done] localize templates API
- [x] Finalize switching site locale in the flow from header by shipping it https://github.com/Automattic/wp-calypso/issues/40011
- [x] Implement switching site locale in the flow from header https://github.com/Automattic/wp-calypso/issues/40011
- [x] Localise domain prices #40733
- [x] Ensure domain categories come translated from the API (https://github.com/Automattic/wp-calypso/pull/41450)
- [x] Ensure we translate plan names consistently https://github.com/Automattic/wp-calypso/pull/41679#discussion_r421184975
- [x] Extract `@wordpress/i18n`-style strings for translation (#39541 / @yuliyan)
- [x] Add translation context to [animated verticals list](https://github.com/Automattic/wp-calypso/blob/9e68e6e3ca64f6a2dd16c42911b2aaada7a181fd/client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx#L65-L77)
- [x] get locale for logged-in users: #39410
- [x] localize text strings: #39410
- [x] get locale for new users: https://github.com/Automattic/wp-calypso/issues/38909
- [x] Gutenboarding: Serve/update RTL CSS as needed #39492
- [ ] ~localize vertical API: https://github.com/Automattic/wp-calypso/issues/37630~ **No verticals currently**
- [ ] ~[server-side-detect locale?](https://github.com/Automattic/wp-calypso/blob/a51b7190df0b9711b5c059e91e576ab9f2593f69/client/signup/index.node.js)~ **Suspect duplicate of #46473**

**Test i18n:**

- `en`: (redirect strip locale) https://wordpress.com/new/en
- `ar`: (RTL) https://wordpress.com/new/ar
- `de`: https://wordpress.com/new/de
- `es`: https://wordpress.com/new/es
- `fr`: https://wordpress.com/new/fr
- `he`: (RTL) https://wordpress.com/new/he
- `id`: https://wordpress.com/new/id
- `it`: https://wordpress.com/new/it
- `ja`: (non latin check) https://wordpress.com/new/ja
- `ko`: https://wordpress.com/new/ko
- `nl`: https://wordpress.com/new/nl
- `pt-br`: https://wordpress.com/new/pt-br
- `ru`: (long translations) https://wordpress.com/new/ru
- `sv`: https://wordpress.com/new/sv
- `tr`: https://wordpress.com/new/tr
- `zh-cn`: https://wordpress.com/new/zh-cn
- `zh-tw`: https://wordpress.com/new/zh-tw

**Some additional pointers:**

- Might be good to release work in stages, so e.g. left-to-right languages work first (Spanish etc) and then separately right-to-left languages.
- The site should be created in the locale that the UI is in.
- All the APIs, verticalized contents, UI strings, etc should be consistently translated.
- The flow works in Calypso, but parts of it are shipped to WP Admin, in which case UI translations should still work. Code for these parts shipped to two environments is typically in `/packages/*`
- Nothing gets shipped to "Calypso proper" but it should also work already (See 138-GH-i18n-issues)

**Comment by sirreal** [comment]
I've updated this master issue with some new issues to track additional i18n tasks.

**Comment by sirreal** [comment]
There's some good i18n work in https://github.com/Automattic/wp-calypso/pull/39627 that would be nice to clean up and get landed.
