### ISSUE TITLE
Enable recent horizon features in production (for FSE sites)

### ISSUE THREAD

**Issue by adamziel** [Automattic/wp-calypso#37867]
We've released a number of features behind a horizon feature-flag recently.

This was good enough for the user testing, but now it's time to roll it out to more users. As we want to get feedback about the overall FSE experience, FSE flow is a good aggregate for these.

Users going through https://horizon.wordpress.com/start/test-fse are getting assigned to FSE group. For sure we have a blog sticker for that. There's also an A/B test on the backend SSE_full_site_editing_20191007. The only question remaining is - how do we know it in Calypso?

### Tasks

- [x] Find out exactly how users are marked as FSE (see https://github.com/Automattic/wp-calypso/pull/37960)
- [x] Replace feature flag checks with FSE test checks:
- [x] ~"checklist-homepage-template-select": true, (https://github.com/Automattic/wp-calypso/pull/37964)~ — closed in favour of https://github.com/Automattic/wp-calypso/pull/38016
- [x] "checkout-upgrade-intent": true, (https://github.com/Automattic/wp-calypso/commit/46a98eda2fac8a7b4969ad31944936dbe79b859c)
- [x] "experience/domain-verification-in-checklist": true (https://github.com/Automattic/wp-calypso/pull/37960)

**Comment by apeatling** [comment]
One thing I want to flag here. Let's keep the domain and plan skip change locked to Horizon, and not in production. This is going to allow us to keep testing this, but feel more confident about ramping up the FSE test group to 50%+ after milestone 2.

Once we have a better handle on metrics and performance we can look at introducing that change to production separately.

**Comment by adamziel** [comment]
This test is (probably) assigned on backend after the site is created - in this case it should be assigned when the signup is started. This may require some coordination with Cylon. @apeatling would you be okay with this being a frontend test instead?

**Comment by adamziel** [comment]
Maybe relevant: https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/step-actions.js#L200

**Comment by adamziel** [comment]
See p1574769779015300-slack-CCS1W9QVA

**Comment by adamziel** [comment]
I started a few pull requests - getting them reviewed and merging them will effectively solve this issue

**Comment by apeatling** [comment]
@adamziel What else do we need to complete to close this one out?

**Comment by andrewserong** [comment]
I think the only one left is the check-list driven domain verification https://github.com/Automattic/wp-calypso/pull/37960 unless I've missed anything else?

**Comment by adamziel** [comment]
I think you're right @andrewserong! I just merged that PR and it seems we're good
