### ISSUE TITLE
[EPIC][Gutenboarding]: user account and site creation

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38701]
This is a parent task for:

-  **Implement account creation component** 
    - [x] Frontend account creation request/response handling #38794
    - [x] Build signup form UI component #38792
    - [x] Update new user endpoint #38795
    - [x] Integrate account creation/signup form #38797
- **Implement site creation**
   - [x] Frontend site creation request/response handling #38707 
   - [x] Update new site endpoint #38798
- [x] Chain account/site creation/redirect requests #39096
- [x] Add analytics (tracks) #38799
- [ ] Create welcome/marketing emails #38796

## Background

<img width="487" alt="Screen Shot 2020-01-09 at 9 08 07 am" src="https://user-images.githubusercontent.com/6458278/72124789-21124300-33ba-11ea-8fd0-a78821c21939.png">

We’re going to start looking at integration account creation (A.K.A “signup”) in Gutenboarding, in particular, circumstances under which we require/nudge the user to create a real account. 🙂

The intention is to, as far as practicable, exploit what we have right now, only requiring account creation when the user performs an action that demands a site be created.

Once the user has signed up, we’ll create a site and headstart it with their current work so that they may continue onto FSE and the NUX flow.

We will explore whether we can reuse some of our work on passwordless onboarding, which allows signup with an email address only.

## Future iterations

- If we generate the user's WordPress.com username via the passwordless signup flow, we should give the user a change to modify it, or at least tell them how to update it.
- ??

## Further reading

- MT https://wp.me/pbxlJb-5E-p2
- Recap after systems discussion on creating temporary accounts pbxlJb-6b-p2
- Passwordless onboarding paWIov-6C-p2
