### ISSUE TITLE
EPIC: ceate a TEMPORARY user account and site creation

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38702]
## Background

Our goal is to provide the background framework for temporary account creation so we can delay asking new users to create an account until the moment they have already started working on their sites.

This EPIC encompasses the following tasks:

- [ ] Investigate where and how we should provision temporary site #38703
- [ ] Create a temporary user account #38706
- [ ] Create a temporary site #38707
- [ ] Headstart the temporary site with user template and page selections #38708
- [ ] Log the user in and continue with FSE/Gutenboarding #38709

There may be some overlap between tasks.

## Further reading

- Spec paObgF-Sp-p2

**Comment by ramonjd** [comment]
We've been chatting about whether we could use an mu-plugin that targets temporary accounts/sites in order to:

- restrict access to certain parts of WordPress.com
- suppress all marketing/welcome/verification emails
- block recording any stats for these accounts (if that's decided)
- anything else?

**Comment by ramonjd** [comment]
Closing for now while we work on https://github.com/Automattic/wp-calypso/issues/38701
