### ISSUE TITLE
Unify Upsell Nudges

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#38778]
We have a lot of ways to display an upsell on WordPress.com. Let's try and streamline this using one component.

As an example here a rough sampling of the different types of notices and nudges we have in use today:

| Sidebar  | Larger Notices |
| ------------- | ------------- |
|  <img width="300" alt="Screen Shot 2020-01-10 at 1 16 59 PM" src="https://user-images.githubusercontent.com/1270189/72180110-12bd2a80-33ac-11ea-82b2-cef5f6255d08.png"> | <img width="619" alt="Screen Shot 2020-01-10 at 1 17 55 PM" src="https://user-images.githubusercontent.com/1270189/72180151-2f596280-33ac-11ea-94f6-c352348fa828.png"> |
| <img width="301" alt="Screen Shot 2020-01-10 at 1 17 08 PM" src="https://user-images.githubusercontent.com/1270189/72180128-210b4680-33ac-11ea-898c-89c86b314dd5.png"> | <img width="897" alt="Screen Shot 2020-01-10 at 1 19 03 PM" src="https://user-images.githubusercontent.com/1270189/72180180-3b452480-33ac-11ea-9da1-7a7f01a0f703.png">  |

### As part of this, we'll need to:
- [x] Create a new UpsellNudge Component that handles common upsell scenarios ( https://github.com/Automattic/wp-calypso/pull/38537 @sixhours )
- [x] Create a new feature flag (#38810 @sixhours)
- [x] Ship UpsellNudge to all 
- [x] Design upsell nudges for all screen sizes
- [x] Coordinate with Marketing and craft an A/B test, to see which variant wins.
- [x] Convert all existing instances of old upgrade nudges to use `UpsellNudge`
- [ ] Move `Banner` functionality and styles into `UpsellNudge`
- [x] Clean up unused instances of other upsell components

#### Banner

First set in #40721
- [x] /client/components/domains/transfer-domain-step/index.jsx
- [x] /client/my-sites/activity/activity-log-banner/upgrade-banner.jsx
- [x] /client/my-sites/hosting/main.js
- [x] /client/my-sites/plugins/plugin-meta/index.jsx
- [x] /client/my-sites/site-settings/form-general.jsx

Site Settings in #40988 
- [x] /client/my-sites/site-settings/jetpack-ads.jsx
- [x] /client/my-sites/site-settings/media-settings-performance.jsx
- [x] /client/my-sites/site-settings/search.jsx
- [x] /client/my-sites/site-settings/spam-filtering-settings.jsx
- [x] /client/my-sites/site-settings/seo-settings/form.jsx
- [x] /client/my-sites/site-settings/form-analytics.jsx

SEO settings in #41194

- [x] /client/components/seo/preview-upgrade-nudge/index.jsx

Theme Showcase in #41311
- [x] /client/my-sites/theme/main.jsx
- [x] /client/my-sites/themes/single-site-jetpack.jsx
- [x] /client/my-sites/themes/single-site-wpcom.jsx

#### Upgrade Nudge (handled in #40626)
- [x] /client/components/tinymce/plugins/simple-payments/dialog/index.jsx
- [x] /client/components/tinymce/plugins/simple-payments/dialog/memberships.jsx (Can't find this one "in the wild") in #41698
- [x] /client/my-sites/earn/memberships/index.jsx
- [x] /client/my-sites/marketing/main.jsx
- [x] /client/my-sites/media-library/list-plan-upgrade-nudge.jsx
- [x] /client/my-sites/post-type-list/index.jsx
- [x] /client/my-sites/site-settings/podcasting-details/index.jsx
- [x] /client/my-sites/stats/stats-module/index.jsx

#### Sidebar Banner/Notice
- [x] /client/my-sites/current-site/notice.jsx (@sixhours - A/B test in #38881 and final in #40026)
- [x] /client/reader/sidebar/reader-sidebar-nudges/index.jsx (@sixhours - A/B test in #38881 and final in #40026)

#### JITMs
- Default template updated in #41419

#### Domain to Plan Nudge in #41453
- [x] /client/my-sites/domains/domain-management/list/index.jsx

#### Upgrade Nudge Expanded in #41557
- [x] /client/my-sites/earn/ads/wrapper.jsx

#### Upgrade to Premium Nudge in #41545
- [x] /client/blocks/post-share/index.jsx

#### Domain Tip in #41552
- [x] /client/blocks/domain-tip/index.jsx

#### Uses `Banner` component, but is not an upsell
- /client/me/pending-payments/index.jsx
- /client/my-sites/activity/activity-log/index.jsx
- /client/my-sites/activity/activity-log/rewind-unavailability-notice.jsx
- /client/reader/following/main.jsx
- Privacy Policy Banner
- Jetpack Backup Creds Banner

#### Delete in #41809
- [x] UpgradeNudge
- [x] UpgradeNudgeExpanded

**Comment by davemart-in** [comment]
@sixhours what is the status on this? Can this one be closed out?

**Comment by sixhours** [comment]
Yes, this can be closed out!
