### ISSUE TITLE
[Gutenboarding]: Create onboarding email(s)

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38796]
Subtask of EPIC #38701

This task assumes we'll need to create custom onboarding site email(s) for Gutenboarding. 

This task can be split up into smaller units if necessary.

We already customize the WordPress.com onboarding email for passwordless. 

## Tasks
- [ ] Get in touch with marketing, let them know about the project and ask for advice
- [ ]  If necessary, create a new email template. See `activation-encourage-passwordless.php` for an example.
- [ ] Check that any email confirmation mail outs for `onboarding` flow - they should accept `gutenboarding` too? See [comment](https://github.com/Automattic/wp-calypso/issues/38796#issuecomment-577455229)
- [ ] Build the triggers into `users/new` and where appropriate
- [ ] Translations

If we reuse our work from passwordless signup (paWIov-6C-p2), and create a temporary username, here's a related issue that we could address as well:

#38082

**Comment by ramonjd** [comment]
As @andrewserong says in D37924-code#753999

> the full passwordless email template for confirming your email address is tied to the onboarding flow with `signup_flow_name: 'onboarding'`. When we add the signup form to Gutenboarding we might want to either pass in this parameter too, or update the logic to accept a flow name like `gutenboarding`, too, for triggering that email template.

**Comment by ramonjd** [comment]
Pushing this back to the backlog for now 

> Emails. No need attention for now; the actual emails that go currently out are aligned with the new mechanics.

p7rd6c-2dV-p2

**Comment by ramonjd** [comment]
Related discussion: 900&cid=CRWCHQGUB-slack-CRWCHQGUB

**Comment by ramonjd** [comment]
Going to close this one as https://github.com/Automattic/wp-calypso/issues/41307 covers the baseline.

Any further initiatives in this area might be driven from marketing/onboarding motivations
