### ISSUE TITLE
[Gutenboarding]: Update new site endpoint

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#38798]
Subtask of EPIC #38701

This task requires more clarity/investigation.

We might need to modify the `sites/new` endpoint or response object. 

## Tasks
- [x] Should we add some `gutenboarding` identifying flag to blog options here? Would we need it?
- [ ] Depending on what we need for headstart, we'll need to pass an array of pages the user has chosen as well. See: #38708 
- [ ] ~We might want to delay sending any emails triggered by site creation (if any). Because the user has not explicitly created a site themselves, it might be strange to receive an email until they've either launched, selected a plan, or have finished working with FSE.~ There are no site-related emails on signup.

**Comment by ramonjd** [comment]
Going to take an initial squiz at this to see how it fits in with Headstarting (https://github.com/Automattic/wp-calypso/issues/38708)

**Comment by ramonjd** [comment]
After digging around, as far as I can tell, not much needs to change in terms of calling `sites/new` if we follow the example in the `test-fse` flow. 

We provision a site, generate a url based on user input or a vertical via the `find_available_url` option.

Payload example:

```
{
  "blog_title": "",
  "options": {
    "theme": "pub/stow",
    "use_theme_annotation": true,
    "site_segment": 1, // must be 1 for fse, see: client/lib/signup/step-actions.js
    "site_information": {
      "title": ""
    },
    "site_creation_flow": "gutenboarding"
  },
  "public": -1,
  "validate": false,
  "blog_name": "someinputtocreatesitename", // use site title first then username we created
  "find_available_url": true,
  "client_id": "",
  "client_secret": "",
  "lang_id": 1,
  "locale": "en"
}
```

Creating a new blog triggers an action that kicks off Headstart.

The response for `sites/new` looks something like this:

```
  "body": {
    "success": true,
    "blog_details": {
      "url": "https:\/\/newsite291051204.wordpress.com\/",
      "blogid": "44444444444",
      "blogname": "Site Title",
      "xmlrpc": "https:\/\/newsite291051204.wordpress.com\/xmlrpc.php"
    }
```

We could add the WordPress blog domain/subdomain (newsite291051204.wordpress.com) to the response so that we can build the redirect url to FSE, e.g.,

`/block-editor/page/newsite291051204.wordpress.com/9`

Hmmm, we'd also need the post ID of the relevant post. To be continued...

**Comment by ramonjd** [comment]
> Hmmm, we'd also need the post ID of the relevant post. To be continued...

We might be able to pluck `page_on_front` from site options after calling `/v1.2/me/sites`

**Comment by ramonjd** [comment]
Might need to set the `USE_FULL_SITE_EDITING` PHP constant / `$should_use_fse` var,  in the new sites class.

**Comment by ramonjd** [comment]
> We could add the WordPress blog domain/subdomain (newsite291051204.wordpress.com) to the response so that we can build the redirect url to FSE

Done in D38739-code

**Comment by ramonjd** [comment]
Closing this for now as it seems that we won't have to tackle anything else in relation to sites until we look at verticals/templates.
