### ISSUE TITLE
Plugin updates: Gutenberg 7.3.0 / CoBlocks 1.20.1

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#38852]
Gutenberg 7.3.0 will be out on Jan 22, 2020.

**Gutenberg**
- [x] Install alpha version: D37714-code
- [x] Activate alpha version on edge sites: D37713-code
- [x] Install RC version:  D37928-code
- [x] Activate RC version on edge sites: D37929-code 
- [x] Install stable version: D38050-code
- [x] Activate stable version on edge sites: D38051-code
- [x] Activate stable version on prod: D38053-code / D38110-code (cleanup diff)
- [x] Request update for AT sites: p9o2xV-I8-p2

**CoBlocks**
Installing a more custom version of `1.20.1` (naming it `1.20.1-wpcom`) that addresses a WPCS lint error in one of the new files. 
- [x] Install 1.20.1: D38211-code
- [x] Activate 1.20.1 version on edge sites: D38212-code
- [x] Activate 1.20.1 version on prod: D38213-code

**Other**
- [x] Call for testing: p7DVsv-82g-p2 (Gutenberg), p7DVsv-84i-p2 (CoBlocks)
- [x] E2E tests PR: #38857 (Gutenberg), #39103 (CoBlocks), #38944

**Bugs encountered**
- [x] Post-Author: Move HTML tags outside of the translatable string https://github.com/WordPress/gutenberg/pull/19675 (WP.com unit tests were complaining about this)
  - Should get Phabricator CI (TeamCity?) to run the same lint, and ideally, the Gutenberg repo, too (https://github.com/WordPress/gutenberg/issues/19911).
- [ ] PR to force WPCS to flag HTML-wrapped translatable strings, https://github.com/WordPress/WordPress-Coding-Standards/pull/1856
- [x] File missing in Gutenberg 7.3.0 RC1, https://github.com/WordPress/gutenberg/issues/19770
- [ ] PR to fix legacy selectors in Jetpack (affected by both 7.2.0 & 7.3.0 upgrades), https://github.com/Automattic/jetpack/pull/14446
- [x] PR to fix legacy selectors in the FSE app (affected by both 7.2.0 & 7.3.0 upgrades), https://github.com/Automattic/wp-calypso/pull/39035
- [ ] Issue with uploading multiple images in Jetpack Slideshow, https://github.com/Automattic/jetpack/issues/14457
- [x] PR to fix our internal `coblocks-builder` failing to build our custom `coblocks` bundle, https://github.com/Automattic/coblocks-builder/pull/3
- [x] WPCS error found in CoBlocks 1.20.1 and fixed in D38211-code. 
- [x] PR to fix above WPCS error upstream, https://github.com/godaddy-wordpress/coblocks/pull/1311
- [ ] Issue with unhandled error shown in console (non-blocking) when uploading images to CoBlocks galleries, https://github.com/godaddy-wordpress/coblocks/issues/1318

**Comment by davipontesblog** [comment]
I checked a test atomic site on WordPress.com and I see:
CoBlocks 1.22.0
Gutenberg 7.3.0

closing this for now.
