### ISSUE TITLE
Gutenboarding: loading animation across site creation and editor loading

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#39287]
## Problem
In Gutenboarding: After selecting "Create My Site" it takes some time for the site to be created before the editor begins loading. Loading experience between "create site" and the editor is janky and dry.

<img width="350" alt="create-site-loading-editor" src="https://user-images.githubusercontent.com/28742426/73893447-ae28aa80-4847-11ea-956e-b5ba9144f0b9.gif">

## Ideal
One, continuous fun loading animation without extra things like cookie banner.

## Current loading animation

Here's a [screencast of the flow](https://cloudup.com/cmXRxLYL8yt) and here are the current steps from that screencast:

1. Start with the "create site" button. When authenticated, this will launch the loading sequence. When unauthenticated, we would first show them the signup form and then proceed with loading.

    <img width="500" alt="Screenshot 2020-02-07 at 12 23 14" src="https://user-images.githubusercontent.com/87168/74027105-2f9b4c80-49b0-11ea-84d9-5698460d55f7.png">

1. Loading while we're creating the site and waiting back from the API. 

    <img width="500" alt="Screenshot 2020-02-07 at 12 22 31" src="https://user-images.githubusercontent.com/87168/74027112-34f89700-49b0-11ea-834b-3f2774328bea.png">

1. We've created the site and now we're booting up rest of Calypso (instead of Gutenboarding entry point) to load the WP Admin iframe.

    <img width="500" alt="Screenshot 2020-02-07 at 12 22 38" src="https://user-images.githubusercontent.com/87168/74027125-3b870e80-49b0-11ea-9544-b6406a0d6e08.png">

1. WP Admin iframe and Gutenberg editor starts loading. Cookie banner pops up. The help bubble shows up.

    <img width="500" alt="Screenshot 2020-02-07 at 12 22 49" src="https://user-images.githubusercontent.com/87168/74027133-3e81ff00-49b0-11ea-99a7-3dca9eeab342.png">

1. There's a moment of a white screen before the editor loads.

    <img width="500" alt="Screenshot 2020-02-07 at 12 23 01" src="https://user-images.githubusercontent.com/87168/74027145-42ae1c80-49b0-11ea-8aa6-ede75286e580.png">

1. The block editor. With cookie banner.

    <img width="500" alt="Screenshot 2020-02-07 at 12 23 09" src="https://user-images.githubusercontent.com/87168/74027154-45107680-49b0-11ea-902f-f6b83cb4c7b6.png">

## Tasks & ideas

- [ ] Have one continuous loading animation from when a user hits "create site" (when authenticated) or succeeds to signup or login (when unauthenticated):
   - No "W" logo in the middle of the loading animation
   - No "jump" in the animation in the middle if possible. Can we show just one animation across the whole loading process, or continue the same animation across two different codebases? Should we import the editor iframe to Gutenboarding so that we don't have to load the rest of Calypso to load the editor?

- [ ] Just having different animation in general because the current is super dry:
  - Could the animation be different at the beginning, middle and towards the end, instead of looping one short animation?
  - Could it tell a story with quick funny texts changing over across the whole flow? Examples: _“creating pages”, “mixing up colors”, “optimizing for mobile”, “requesting a preview of your new site", ["reticulating splines"](https://www.urbandictionary.com/define.php?term=reticulating%20splines), "downloading unicorn models",_ etc…
  - Could it include a nice lively animation? Something like [this](https://giphy.com/gifs/wordpressdotcom-diversity-wordpress-radiate-jTqfCm1C0BV5fFAYvT) or [this](https://giphy.com/gifs/wordpressdotcom-wordpress-fxKWgoOG9hzPPkE1oc) or [this](https://giphy.com/gifs/wordpressdotcom-website-wordpress-plugin-ZgTR3UQ9XAWDvqy9jv).
  - Can the loading animation fade or jump out to reveal the block editor?

- [ ] Remove (or move elsewhere) the cookie banner that pops up when starting to load Gutenberg iframe.
  - We already ask for this at the beginning of the flow here — can we do away without one in onboarding flows?
      <img width="500" alt="Screenshot 2020-02-07 at 13 58 21" src="https://user-images.githubusercontent.com/87168/74028232-8570f400-49b2-11ea-95ce-7f6355ea14ac.png">

- [ ] Delay showing the help bubble
  - Can we animate it into view after FSE has been fully loaded, or even after the customer closes the welcome modal?

- _Anything else?_

@Automattic/gutenboarding-design @ramonjd

**Comment by simison** [comment]
I think we can split this to a few separate chunks of work that we can already start without design. Furthermore, we can do a lightweight prototype of a "continuous loading screen across all these steps". I'll update the issue description.

**Comment by joanrho** [comment]
@simison @Addison-Stavlo A prototype sounds like a great idea for this to improve the long and somewhat bland loading experience between clicking “Create my site” and the Editor.

I really like all of Addie's ideas mentioned above, in particular, using one of our existing loading animations. The second option feels great: https://giphy.com/gifs/wordpressdotcom-wordpress-fxKWgoOG9hzPPkE1oc. 

Let's also implement Addie's other suggestions to remove the cookie banner (redundant) and delay the help bubble (don't need them at this point until Editor appears) during this. If we need the cookie banner to reappear, Customer Home might be a better location once users are onboarded and the preliminary things are set up.

**Comment by Addison-Stavlo** [comment]
I think most of those are @simison 's suggestions (not mine), he updated my very short issue post I had initially with all this good stuff you see now.  🎉  But I agree, it seems like a good path forward!

**Comment by simison** [comment]
Thanks everyone! Hehe well Kudos Addison for recording a follow-up issue I could reuse. :-)

**Comment by ramonjd** [comment]
I've been looking forward to this one for ages, thank you!

> Could it tell a story with quick funny texts changing over across the whole flow?

Or it could rotate through some relevant tips. There are a bunch of already-translated tips to be found in places like https://github.com/Automattic/wp-calypso/tree/25d2ca0bf9148864d430e99304688a6019439b99/client/layout/guided-tours/tours

> Could it include a nice lively animation?

Canvas-based jumping T-rex game anyone? :)

**Comment by simison** [comment]
We'll need to update this with what's in Figma:

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/87168/78358607-25ff2100-75bc-11ea-86b0-2b3cf626173f.png">
