### ISSUE TITLE
[Gutenboarding]: enable passwordless login

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#40002]
We need to allow account holders, who haven't yet set a password, to login.

Normally, when the backend detects passwordless accounts it informs the user that we're emailing them a "Magic Login Link"

<img width="536" alt="Screen Shot 2020-03-10 at 3 28 14 pm" src="https://user-images.githubusercontent.com/6458278/76279747-e6f2ee00-62e3-11ea-9982-f8fee3355582.png">

<img width="666" alt="Screen Shot 2020-03-10 at 3 07 30 pm" src="https://user-images.githubusercontent.com/6458278/76279020-4ac7e780-62e1-11ea-97f9-0ee95ebcc3e8.png">

By default, when a user clicks on the link, we log them in and redirect to `wordpress.com`.

### Basic approach

We'll need to:

1. Inform the user that we've emailed them a login link
2. Pass the relevant Gutenboarding redirect URL to the login backend so that we can log the user in and send them back to Gutenboarding

### Tasks

- [ ] From looking at the code, Magic login does handle a `$redirect_to` argument. The `redirect_to` query parameter we POST to `https://public-api.wordpress.com/rest/v1.2/auth/send-login-email` might do the trick. In Calypso [we call this endpoint](https://github.com/Automattic/wp-calypso/blob/fde5736/client/state/data-layer/wpcom/auth/send-login-email/index.js) via [an action](https://github.com/Automattic/wp-calypso/blob/fde5736/client/state/auth/actions.js#L21) when login [detects a passwordless account](https://github.com/Automattic/wp-calypso/blob/fde5736/client/blocks/login/login-form.jsx#L133)
- [ ] We'll need to check in with the design folks to get input
- [ ] Create the component/screen in Gutenboarding informing the about the email/requirements 
- [ ] Handle any errors from the magic login endpoint response (?)

**Comment by ramonjd** [comment]
We might not need this straight away or at all, depending on what we learn from Login Frankenflow: https://github.com/Automattic/wp-calypso/issues/40004#issuecomment-596915097

**Comment by ramonjd** [comment]
This issue is stale. We've integrated the current login flow for now, and are working on the redirect in https://github.com/Automattic/wp-calypso/issues/41771
