### ISSUE TITLE
Plugin updates: Gutenberg 7.7.1

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#40078]
Gutenberg 7.7.1 [was released on March 13, 2020](https://github.com/WordPress/gutenberg/releases/tag/v7.7.1). 

This issue tracks progress upgrading wpcom.

With 7.7.1, we're skipping stable versions (7.4.0 (potentially), 7.5.0 and 7.6.0).

[7.4.0 is currently waiting in the halls](https://github.com/Automattic/wp-calypso/issues/39290) until the ongoing work on the data migration project (pbAok1-f8-p2) is complete, however the completion date is unknown with estimation 5-6 days, starting on Monday March 16th.

### Gutenberg 
- [x] Install stable version: D40297-code
- [x] Activate stable version on edge sites: D40215-code
- [x] Activate stable version on prod: D40794-code
- [ ] Cleanup old versions of GB (D39409-code)
- [x] Request update for AT sites (p9o2xV-N2-p2)

### Other
- [x] GB call for testing stable version: p7DVsv-8gl-p2
- [x] E2E tests stable version PR: #39292 (Fixes in #40239)
- [x] .com specific block patterns shipped (not a blocker, but good to have in before we release) https://github.com/Automattic/wp-calypso/pull/40105
- [x] Update the Gutenberg Plugin on WPCOM Fieldguide page under **Log Of Update Attempts**
### Bugs encountered 🐞

- [x] Fix issue with latest posts block fataling; https://github.com/Automattic/wp-calypso/issues/40127 Addressed in D40674-code ✅ Merged.
- [x] E2E test fails: Fixed in #40239 ⚠️ Needs to be merged after upgrade
- [x] ~Potential blocker if not addressed in 7.7.1 p3btAN-1dt-p2 and p3btAN-1dr-p2 Check that these have been addressed in core before we update.~ Fixed here D40222-code
- [X] The "W" icon back button does not work on wpcom. (need to target it with our URL overrides.) https://github.com/Automattic/wp-calypso/issues/40315 ✅ Merged in #40329
- [X] **FSE** Need to remove the "W" icon back button for dotcom-fse. #40334 Fixed in https://github.com/Automattic/wp-calypso/pull/40329 ⚠️ Needs to be merged before update.
- [x] **FSE** Need to update FSE back button alignment. #40334 #40329 ⚠️ Needs to be merged before update.
- [x] Small regression in starter page component button Fixed in https://github.com/Automattic/wp-calypso/pull/40278 ✅ Merged.
- [x] Positioning of header in editor on smaller screens. https://github.com/Automattic/wp-calypso/issues/40335 ✅ Merged in #40361
- [x] **FSE** Fix the editor frame in dotcom-fse. (Or remove the frame altogether.) fix in #40409
- [x] In-editor device preview not being properly applied to responsive content See p7DVsv-8gl-p2#comment-27501 — either fix or replace with old simple "preview" button for now. https://github.com/Automattic/wp-calypso/issues/40401 Fixing by switching to old preview in https://github.com/Automattic/wp-calypso/pull/40388 ✅ Merged.
- [x] adjustments to FSE header margins https://github.com/Automattic/wp-calypso/pull/40425  ✅ Merged.

### Punted after release
- [ ] ~Hide block patterns and their UI on .com (https://github.com/WordPress/gutenberg/issues/20867)~ We'll keep this (p7DVsv-8gl-p2#comment-27375)
- [ ] Fix issue with re-usable block fatalling: https://github.com/Automattic/wp-calypso/issues/40229 — could not be replicated
- [ ] Raise an issue for the mobile preview not working with stylesheets from different domains (p7DVsv-8gl-p2#comment-27501)    (p1585038214240800-slack-gutenberg-on-dotcom)

**Comment by ramonjd** [comment]
@p-jackson pointed out the changes to the header in 7.7

#### Current
<img width="1344" alt="Screen Shot 2020-03-12 at 3 44 43 pm" src="https://user-images.githubusercontent.com/6458278/76488132-a7113f80-6478-11ea-82d4-61d2d785acbe.png">

#### With 7.7 enabled
<img width="1338" alt="Screen Shot 2020-03-12 at 3 45 31 pm" src="https://user-images.githubusercontent.com/6458278/76488139-aaa4c680-6478-11ea-8a63-a18ca807c245.png">

This breaks our back button pretty hard.

My uneducated guess is that we'd need to update the [FSE BackButtonOverride hook method](https://github.com/Automattic/wp-calypso/blob/fc74c21/apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/index.js#L19) ?

**Comment by noahtallen** [comment]
> My uneducated guess is that we'd need to update the FSE BackButtonOverride hook method ?

That override will only work for dotcom-fse sites, so I think it will need fixed elsewhere too... Trying to remember where that is 🤔 

This also breaks the frame around the editor for dotcom-fse:

<img width="2558" alt="Screen Shot 2020-03-12 at 5 46 50 PM" src="https://user-images.githubusercontent.com/6265975/76579445-7e457600-6489-11ea-9213-6b110b6d8869.png">

And the new "document sidebar" button is hidden by our staging icon

<img width="1677" alt="Screen Shot 2020-03-12 at 5 48 11 PM" src="https://user-images.githubusercontent.com/6265975/76579508-ba78d680-6489-11ea-87b6-1ee2d7680ea0.png">

**Comment by noahtallen** [comment]
In dotcom-fse, we should probably just stick with the overridden back button and remove the W icon for now. I say this because the W icon in the template part editor won't make sense -- we still need to get back to the page editor, not back to wp-admin. And we should probably keep the back button in the page editor consistent with that for now.

**Comment by roo2** [comment]
hmmm so what's the best release process for getting  neccessary fixes changes to gutenberg into this release? ( I'm thinking of this one #40127)

This is the process as I understand it:

Gutenberg PR -> Gutenberg Master -> Tag a new Gutenberg release v7.7.x -> zip file -> install on wpcom edge sites -> test -> call for testing -> make it live for everyone

The problem then is that the new Gutenberg release v7.7.x will include a whole set of commits that haven't been tested with wpcom so we almost have to restart the testing effort rather than just checking this bug off the list of known issues.

But we can also manually change the zip file right, it sounds like that's the safer solution in this case, is that what you guys were thinking? 

Currently v7.7.0 is a tag on the master branch, I've seen teams create release branches for this kind of complex release and then apply or cherry-pick commits on to that branch.. but that would be a different future discussion I think.

**Comment by ramonjd** [comment]
> hmmm so what's the best release process for getting neccessary fixes changes to gutenberg into this release?

For major blockers we can update the files ourselves on .com. The only headache will be making sure we file a corresponding PR on the WordPress/Gutenberg repo.

> The problem then is that the new Gutenberg release v7.7.x will include a whole set of commits that haven't been tested with wpcom so we almost have to restart the testing effort rather than just checking this bug off the list of known issues.

I think we could carry on as we've been doing: deal with each release as it comes out from Gutenberg, and fixing things on our end + creating Gutenberg PRs to ensure that our changes make it into future versions.

**Comment by simison** [comment]
I'll close this — we can continue in 7.8.0 issue for the next version.
