### ISSUE TITLE
Site Setup List (checklist): Add checklist step for updating Site Title

### ISSUE THREAD

**Issue by gwwar** [Automattic/wp-calypso#40291]
With the new onboarding flow, we no longer capture a customer's Site Title during site creation. Let's add another step to the Site Setup List to update the Site Title.

<img width="1253" alt="Screen Shot 2020-03-20 at 2 46 07 PM" src="https://user-images.githubusercontent.com/1270189/77208717-a7818a00-6ab9-11ea-93ac-faafb0326620.png">

### Notes
* The checklist is backed by a server API. We need to know when a task is done. So this will require server patches. It may be worth it to make this step **skippable**. (There should be existing examples of this).
* We may need to think about for whom this task is eligible for. (Double check that we don't unset the "doneness" of site setup for folks that have already run through this list).
* We're currently not sure if we should link to https://wordpress.com/settings/general/yoursite or Site Identity in the Customizer
* Please add required analytics that we expect to this new task

cc @amamujee

**Comment by amamujee** [comment]
Totally fine in my mind for it to be skippable if that vastly simplifies the implementation. I'm also not sure how 'necessary' this is, but if users can't figure out how to add site name (we can look at % of new sites with name), this might be worth it. My instinct says it is :)

**Comment by mmtr** [comment]
Seems we already had this step in the past but for some reason if was removed.

https://github.com/Automattic/wp-calypso/blob/17fcc17c58db299622e5023c1c25ade6d538c74d/client/my-sites/checklist/wpcom-checklist/component.jsx#L68

It should be pretty straight forward to bring it back, let me see if I can quickly spin a server patch.

**Comment by mmtr** [comment]
The above patch will break the existing signup E2E tests since they are expecting the update homepage task to be first:

https://github.com/Automattic/wp-calypso/blob/11c9ed907d661d28b23fddc4ce36473da379969b/test/e2e/specs/wp-signup-spec.js#L466-L484

https://github.com/Automattic/wp-calypso/blob/11c9ed907d661d28b23fddc4ce36473da379969b/test/e2e/specs/wp-signup-spec.js#L1095-L1118

Should we update the E2E tests so they update the site title as well? Or should we keep the update homepage task first and move below the one for updating the site title?

**Comment by gwwar** [comment]
> Should we update the E2E tests so they try to change the site title before updating the homepage? Or should we keep the update homepage task first and move below the one for updating the site title?

I think either could make sense. @lcollette @danhauk @jancavan @sixhours thoughts on the ordering/priority of site title vs homepage editing?

If we need to we can update E2Es within the same branch so things are sync'd if we need to flip this on/need to revert later.

**Comment by sixhours** [comment]
I think site title is probably an easier "first win" for customers than the editor, which is a more complicated task, so I'd say site title should go first.

**Comment by danhauk** [comment]
I agree, site title is a better first task to build momentum, at least until we potentially [break down that massive "update homepage" task](https://github.com/Automattic/wp-calypso/issues/39183).

**Comment by mmtr** [comment]
Cool, thanks for the feedback. We need to follow then steps above in order to keep Calypso E2E tests green:
- [ ] Skip the update homepage steps on the signup E2E tests.
- [ ] Land D40692-code.
- [ ] Add additional steps to the signup E2E tests for setting a site title before updating the homepage.
- [ ] Bring back the skipped update homepage steps.

**Comment by jancavan** [comment]
Agreed. Make sense to have them update the Site Title first as a small task before proceeding to the home page.

I know it's old, but since we're at it, I'm not sure about that description copy - "Give your site a name to entice visitors":

![image](https://user-images.githubusercontent.com/4924246/77594675-5d7f1680-6eb4-11ea-9bbe-44bf911c73d5.png)

It doesn't seem like it's something you come up with to entice other people? It's more about establishing your brand or identity I think. cc @Automattic/editorial

**Comment by michelleweber** [comment]
Ideas:

Give your site a title that tells visitors what you're all about.

Establish your online identity with a descriptive name.

I might also changing the heading to just "Name your site" -- the meaning is the same, and that way the headings are nice and parallel, all three words long.

(Full disclosure, I also have no issue what what's currently there. A lot of bloggers are less interesting in branding than in getting people to look at this site period.)
