### ISSUE TITLE
Gutenboarding: Intent capture visual fixes

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40321]
Gutenboarding is looking awesome so far. I thought I'd write down a few fixes for the intent capture that we should get to at some point.

- [x]  Header title `.gutenboarding__site-title` should be `font-weight: 600`
- [x]  Padding left on WordPress logo to the edge of the screen should be `24px` not 18px
- [x]  Header height should be `64px`
- [x]  [Spacing on bottom border on input fields](https://d.pr/i/iYa8lQ) (when filled out) should be `12px` from the letter to the top of the border. It's currently around 27px.
- [x]  Button font-size should be `14px` not 16px. And font-weight 500
- [x]  Button border-radius should be `4px` not 3px
- [x]  `suggestions__label` should be `var(--studio-gray-30)` and not gray-20
- [x] If you use shift-tab to go back to site vertical after you filled the title, two arrows will appear next to both fields. See [here](https://user-images.githubusercontent.com/17054134/77912011-1917c000-7292-11ea-8df3-151f5e54fe49.png). We should display the arrow only when the 'next/skip' button is hidden (@alshakero  #40570)
- [x] [taken] The whole section [jumps](https://d.pr/i/7NHgz0) when you select and deselect the category field (@alshakero - PR #40616).
- [x] [taken] Let's hide the arrow on focus immediately and make the arrow appear if what user has entered is three or more characters (@alshakero - PR #40616).
- [x] [taken] Let's just remove the period altogether. It's making selecting and selecting things a bit awkward (@alshakero - PR #40616).
- [ ] Button jumps down when selecting site name and category field. https://github.com/Automattic/wp-calypso/issues/40474 (Fixed in #40612)
- [x] Improve the latency of the color changing animation https://github.com/Automattic/wp-calypso/pull/40601
- [ ] [TBD] Remove _I don't know_ button. Feels weird that the same button changes label.
- [ ] [TBD] Maybe we should limit site title length? Should check if there is any backend limit.

**Multi-line support** (@razvanpapadopol)
- [ ] The scaling as you enter a longer string is looking great :) Could we wrap it to two lines when it goes too off screen? (Fixed in #40612)
- [ ] If vertical title is long (even if from the list), the arrow/dot drop to the a new line. See [here](https://user-images.githubusercontent.com/17054134/77911818-bd4d3700-7291-11ea-85a4-29d9cc61fc22.png). (Fixed in #40612)

**Dynamic width support**
- [ ]  Site name capture shouldn't [have underline](https://d.pr/i/sspcOR) when nothing is filled in. It should also not show up until the category/topic is filled out. Look at prototype for correct behavior here. (Fixed in #40612)
- [ ] The underline shouldn't be [full width](https://d.pr/i/4V5U9N) for vertical select (related [comment](https://github.com/Automattic/wp-calypso/issues/40142#issuecomment-599999628)) (Fixed in #40612)

**Comment by simison** [comment]
@chriskmnds can you check if some of these get fixed already by https://github.com/Automattic/wp-calypso/pull/40176 and tick off once merged?

**Comment by sirreal** [comment]
Grabbing

> - [ ] The whole section [jumps](https://d.pr/i/7NHgz0) when you select and deselect the category field (@sirreal)

**Comment by alshakero** [comment]
>  If you use shift-tab to go back to site vertical after you filled the title, two arrows will appear next to both fields. See here. We should display the arrow only when the 'next/skip' button is hidden (@alshakero)

PR in https://github.com/Automattic/wp-calypso/pull/40570
