### ISSUE TITLE
Gutenboarding: Design step fixes

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#40394]
Some minor things to fix on the design step:

### To do

- [ ] The design thumbnail title should be `font-size: 18px` and `font-weight: 500`. I've noticed 500 doesn't do anything though. Are we loading in that font-weight? 

### Done

- [x] [taken] Start over button in the top right should be underlined (@alshakero - PR #40643)
- [x] The hover on thumbnails is looking good. Can we animate the `box-shadow` value too? They kinda just pop in which is a bit less elegant than a fade. (#40370 @sirreal)
- [x] The outer container shouldn't have a `max-width` and should be fluid. https://github.com/Automattic/wp-calypso/pull/40600
- [x] Clicking a design thumbnail should proceed to the next step, so no need for the outline and button in the top right bar (this only happens when you proceed and back at the moment) (#40320 / #40370 @sirreal )

**Comment by sirreal** [comment]
The thumbnail box-shadow and outline removal are handled in #40370, which should be ready to land. We can push more of these fixes there, they're pretty small likely to conflict.

cc: @alshakero in case you want to take some of these on.

**Comment by simison** [comment]
>The design thumbnail title should be font-size: 18px and font-weight: 500. I've noticed 500 doesn't do anything though. Are we loading in that font-weight? (Font size is taken care of in

We're loading 400. Marketing page already loads 500 (right now at least) so we'd have that in browser cache for free I think. Otherwise, I'd prefer to stick to one weight if possible just to optimize the speed. I appreciate if the difference is significant enough to justify loading both — that's fine and then we just do that. :-)

**Comment by dubielzyk** [comment]
The issue with the 400 weight on the site title comes when we add color to it. It becomes a less contrasty so we bump it to 500 to make it stand out a bit more. I understand the limitation and I'll leave it to you to decide. If we wanna change it later, I can create a PR.

**Comment by simison** [comment]
Everything from the list is pretty much done — the font in the design picker is no longer brand font but UI font instead, so I feel like this needs reviewing anyway.

@dubielzyk can you review if current one needs any adjusting and let us know — thanks!

<img width="627" alt="Screenshot 2020-04-03 at 14 36 47" src="https://user-images.githubusercontent.com/87168/78356679-ab80d200-75b8-11ea-8bd5-0437cdf8c6cc.png">

**Comment by dubielzyk** [comment]
> can you review if current one needs 

Looks good without the bold :)
