### ISSUE TITLE
Themes: Clean up Redux state

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#4057]
The themes Redux state does not follow many best practices of the Redux global state.

Specifically, the following should be fixed:
- [x] `client/state/themes/action-types.js` should be consolidated into `client/state/action-types.js` ([reference](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#actions)) @ockham #4440
- [ ] Remove reliance on computed `site` attributes sourced from `lib/site/index.js`, instead using only values which are made available on the raw REST API site object. It may be appropriate to create new selectors in `client/state/sites/selectors.js` (related issue: #2757)
  @seear
  - Examples: [[1]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L279)
- [x] Avoid side-effects in action creators whenever possible @ockham #6844 #8303
  - Examples: [[1]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L279), [[2]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L267), [[3]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L213)
- [ ] Try to be more granular with props passed to components, or at the very least not pass object to components expecting decorated site object: @ockham
  - Examples: [`<ThemesSingleSite />`](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/my-sites/themes/single-site.jsx#L135)
- [x] Remove unnecessary `Object.assign` calls in `react-redux` `mapStateToProps` argument: @ockham, #4095
  - Examples: [[1]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/my-sites/themes/sheet.jsx#L137)
- [x] Determine a more generic analytics approach which is not specific to the themes use-case #4699
  - [`client/state/themes/middlewares.js`](https://github.com/Automattic/wp-calypso/blob/master/client/state/themes/middlewares.js)

/cc @ockham , @ehg , @seear , @mtias

**Comment by gwwar** [comment]
Selectors in `state/plugins/wporg/selectors` should also be updated to pass through the full redux state object, instead of `state.plugins.wporg.items`.

**Comment by ockham** [comment]
@gwwar Maybe file a separate issue for that, so we'll use this one just to track themes related stuff?

**Comment by gwwar** [comment]
:) Didn't read the title properly. I'll move it.

**Comment by ockham** [comment]
- [ ] Try to be more granular with props passed to components, or at the very least not pass object to components expecting decorated site object: @ockham
 - Examples: [`<ThemesSingleSite />`](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/my-sites/themes/single-site.jsx#L135)

The example you give is quite the rabbit hole -- while we don't directly use `getRemoteManagementURL()` ourselves, `JetpackManageErrorPage` does -- and that component is used in a few components that don't seem to be `connect()`ed yet, so we can't easily replace `getRemoteManagementURL()` by a selector there.

**Comment by ockham** [comment]
^ Filed #4160

**Comment by ockham** [comment]
> - [ ] Avoid side-effects in action creators whenever possible
 - Examples: [[1]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L279), [[2]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L267), [[3]](https://github.com/Automattic/wp-calypso/blob/d05911147dfd812ff8cc318f687fbecd882405ca/client/state/themes/actions.js#L213)

Copying from https://github.com/Automattic/wp-calypso/pull/4440#discussion_r58208669

>  I think we made them actions mainy so we could tack tracking to them, but we probably don't do that anyway now. [...] Probably going to try and rip them out in another PR.

**Comment by ockham** [comment]
Closing. We've refactored our state tree completely (#8785), which fixed pretty much all the issues listed above. We still have side-effects (`page` calls) in some actions, but we can't get entirely rid of them right now.
