### ISSUE TITLE
(5P) Update to coblocks 1.23.0

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#40598]
1.21.1 was deployed to edge stickered sites but hasn't made it live because of a couple of outstanding bugs (and other priorities WRT data migration and getting gutenber 7.7.1 deployed). 
[Update to 1.21.1](https://github.com/Automattic/wp-calypso/issues/39290)

1.23.0 should fix at least one of the bugs so let's see if it is suitable for testing and deploying.

### TODO:
- [x] Create 1.23.0 build with the build repo https://github.com/Automattic/coblocks-builder
- [x] Deploy 1.23.0 to my sandbox
- [x] See if 1.23.0 fixes the issues identified in the 1.21.1 ticket #39290
- [x] Smoke test new features of 1.23.0 myself
- [x] Create a CfT for 1.23.0 p7DVsv-8u1-p2

Notes:
- [ ] Understand what replace-image is and if we need it for wpcom
- [ ] Find out what caregory=coblocks implies
- [ ] Find out what `coblocks_bundled_icons_enabled` does and if we can use bundled icons on wpcom
- [x] We're loading `coblocks-slick` for the "events block" D41933-code

**Comment by noahtallen** [comment]
@Automattic/ajax Do you want to take over this issue or do you already have a tracking issue? (if you don't need it we can close it)

**Comment by obenland** [comment]
Thanks for the heads up, I didn't know this existed. Yes, happy to adopt this as our tracking issue for the 1.23 update.

**Comment by marekhrabe** [comment]
E2E seem to be passing now https://github.com/Automattic/wp-calypso/pull/41400
there were some coblocks-unrelated errors which are now gone.

**Comment by marekhrabe** [comment]
The only issue reported in CfT was fixed. We might be safe to proceed with a public launch soon.

**Comment by WunderBart** [comment]
Looks like Gutenberg 7.9.1 is going to be skipped in favor of 8.0.0 (p7DVsv-8tt-p2#comment-28404). Should we hold off until the Call for Testing for 8.0.0 is done?

**Comment by marekhrabe** [comment]
To reconfirm - we have tested this 1.23.0 version on dotcom with its current Gutenberg 7.8.1 - no regressions detected. Prepping deploy in D42407-code
