### ISSUE TITLE
Gutenboarding: small visual issues

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#40757]
High Priority list:
- [x] “Start your website” in top bar should be regular weight, not bold. - fixed in #40740 
- [x] **Intent capture step** - fixed in #40743
 - Remove fixed underline (see image below) when placeholder keywords are animating, match prototype (no underline when keywords are animating).
- Increase the left padding of the intent capture statement by 50px, and top by 12px. Match prototype.
- Letter spacing should be 0 for “I don’t know yet”/Choose a design button text.
- [x] **Design selector** - fixed in #40745
 - Frames: the spacing between each frame should be 64px 
 - Header, subheader padding should be 64px 0 80px. (screenshot below). Same applies to style selection step
 - Design frame hover. To align with gutenberg, we should move away from drop shadow, and frame size increase animation to a fixed size, and border color change

**Style selector**: 
  -  [x] [taken] Reduce previewer box-shadow to .1 (currently .25) - @alshakero #40808
  - [x] [taken] Let's also reset scroll positions too in each route change by default: #40767  - @alshakero
  - [x] [taken] [no selected border](https://github.com/Automattic/wp-calypso/issues/40569#issuecomment-608404661) around desktop/tablet/mobile buttons in design picker (https://github.com/Automattic/wp-calypso/pull/40800 / @sirreal) 
 
Other known issues:
- [x] [taken] Intent capture input small glitches (jumping cursor and transitioning underline) mentioned in https://github.com/Automattic/wp-calypso/pull/40743#pullrequestreview-387115515 and detailed in https://github.com/Automattic/wp-calypso/pull/40743#issuecomment-608350809 - @alshakero  #40808
- [x] [taken] Vertical suggestions dropdown flicker mentioned in https://github.com/Automattic/wp-calypso/pull/40743#issuecomment-608350809 - @alshakero #40808
- [x] [taken] Design selector a11y concern regarding alt text https://github.com/Automattic/wp-calypso/pull/40745#discussion_r402901470 (@sirreal #40815)
- [x] [taken] Viewport selector should also have accessible text (@sirreal #40815)

**Comment by simison** [comment]
Let's also reset scroll positions to too in each route change by default: https://github.com/Automattic/wp-calypso/issues/40767

**Comment by razvanpapadopol** [comment]
all done ✨
