### ISSUE TITLE
Help: improve landing page layout hierarchy and clarity

### ISSUE THREAD

**Issue by rickybanister** [Automattic/wp-calypso#40870]
Currently:

![image](https://user-images.githubusercontent.com/437258/78716017-3b41bb80-78ec-11ea-8058-8b770548f60f.png)

![image](https://user-images.githubusercontent.com/437258/78716070-5280a900-78ec-11ea-93a9-1ec3016e2189.png)

The help page is a bit of a mess. 

It includes:
1. Search (which is lost kind of due to all the things below)
2. Courses (using a banner component instead of a more standard navigation pattern)
3. Most helpful articles (these were intended to be related to search, but the introduction of Courses dislocated them)
4. All support articles (external link to en.support.wordpress.com, somewhat redundant from search and most helpful articles)
5. Quick help video tutorials (also external link to support site)
6. Self-guided email course (external link to blogging U)
7. Self-guided online tutorial (external link to learn.wordpress.com)
8. Get in touch (link to contact form)

A lot of that serves the same purpose, but without much hierarchy it becomes very overwhelming to understand which option is the 'right one'. 

Another layer to this is the support search results. Results are pulled in from support articles, forums, and jetpack support articles. Their display is identical to the most helpful articles, making it unclear that results were even returned. 

The structure of this page has evolved over time as we've learned from data (what people are most often looking for) and as more resources have been created to help customers. This is at cross-purposes, however, to giving people a clear single pathway to find their answer or get help. 

There are low-hanging design details we can improve to help make this page more useful, and with a larger investment we can improve the page through structure and content.

**Comment by olesyabrk** [comment]
Current direction:

1. Improve usability and consistency via css and some simple layout fixes. No backend dev support needed.
2. Explore how to standardize and simplify search results across the Support widget and the Help page. 

cc: @rickybanister @lcollette @davemart-in

**Comment by rickybanister** [comment]
As a bonus, and since there's already so much stuff on the /help screen I think it'd be nice to include a promo for buying a quick start session.

**Comment by olesyabrk** [comment]
@rickybanister that upsell in the Help section makes a lot of sense. But I also want to see if we can either restructure the page or remove some of the sections, too much going on currently.

**Comment by lcollette** [comment]
@sfougnier shared the latest designs on p2: pbAPfg-Qu

**Comment by sfougnier** [comment]
**Design updates:**
- Made some adjustments to the order of the elements on the page, pushing "Most Helpful Articles" further up the page and moving guides and webinars down in order to show relevant help topics sooner.
- Added a CTA for contacting support into the page header so that it's not buried down at the bottom of the page.
- Looked at making article lists more visual by adding illustrations to "Most Helpful Links" that can be more curated and correspond with the handful of links surfaced here. Took a pass at how this could work in the search results too, but also don't mind going without visuals either.
- Took a look at implementing upsell banners for lower-tiered plans on landing instead of surfacing the Quick Start Session CTA. Not 100% sold on it - wondering if we should show/hide Quick Start Sessions based on your plan/whether you have any available or tailor the "Most Helpful Articles" surfaced to specific plans (if relevant). 

[Designs in Figma with alts
](https://www.figma.com/file/xoydtPtAB3VWb71Cznb5u1/Help-Landing?node-id=108%3A0)

**Landing**
<img width="1440" alt="00 Help Landing - Desktop" src="https://user-images.githubusercontent.com/67021691/96312058-d40e6d80-0fd8-11eb-974e-b7c5b9c13ef2.png">

**Search Results**
<img width="1440" alt="00 Help Landing - Desktop-3" src="https://user-images.githubusercontent.com/67021691/96312060-d83a8b00-0fd8-11eb-8ce2-6d15d0c21885.png">

**Comment by rickybanister** [comment]
I left a quick comment on the weekly updates thread saying something similar, but looking more closely I have perhaps an additional idea. If we could simply highlight your search term in the search results (in this case 'plugin) either with a background color or bold text that might provide enough of an affordance that you're still viewing search results vs default  suggestions.

**Comment by sixhours** [comment]
I'd roll this out over multiple smaller PRs, in rough order:

- [x] Add the support session card at the top - #47977
- [x] Update the More Resources section - #48222
- [x] Update the Most Helpful Articles section and search results - #48719
- [ ] We need more information from Happiness before we bring the "Contact support" button to the top of the page; I'm not sure if it's strategically low in the hierarchy. Leaving this for last until we get confirmation.

**Comment by sixhours** [comment]
@lcollette I'm almost ready to ship the support session card piece. Should we loop Happiness into the changes and let them have a look? Do you know who would be best to contact if so?

**Comment by sixhours** [comment]
The last thing on this list is to add the Contact Support button to the top of the page, opposite the page title as we do for My Home and Plugins. This seems like something we need to get approval from Happiness Ambassadors for, because it could increase support load by making the direct contact option more prominent. @jordesign what do you folks think?

**Comment by jordesign** [comment]
Thanks for the consideration @sixhours - It's probably something for me to flag with HappOps. I'll let them know.

**Comment by kristenzuck** [comment]
Hi @sixhours! @jordesign reached out to HappOps[ in Slack about this change](p1612753990070400-slack-CPJE78JQ5). We are all for making it easier for our customers to contact us :) That said, a couple questions for our planning:

1) Do you have an ETA of when you'd like to make this change? Wednesday launches are always best when possible for coverage reasons if there is an influx, but not required. 
2) Will you make the change for all customers at once? Any change we can try it at even 50% first to see what kind of response it causes?
3) Will there be a way in Tracks or otherwise we can monitor contacts from this route once it is live?

**Comment by sixhours** [comment]
> Do you have an ETA of when you'd like to make this change? Wednesday launches are always best when possible for coverage reasons if there is an influx, but not required.

No ETA at this point, just putting out feelers, so to speak. :) 

> Will you make the change for all customers at once? Any change we can try it at even 50% first to see what kind of response it causes?

I don't see why not. @lcollette @sfougnier any thoughts? Implementing this behind a feature flag for a subset of users for a few weeks to gauge impact seems like a good idea to me.

> Will there be a way in Tracks or otherwise we can monitor contacts from this route once it is live?

Yes indeed! I'll make sure there are Tracks events on the button.

**Comment by kristenzuck** [comment]
Sounds great! Just keep HappOps posted as things develop then!

**Comment by mattwondra** [comment]
@sixhours It looks like https://github.com/Automattic/wp-calypso/pull/48719 broke the styles for Sibyl on the Contact Form (the question/answer suggester to help customers answer their own questions before reaching out to us). See it by going to https://wordpress.com/help/contact and typing something like "css" into the message box. Here's a comparison of current production, vs the expected design:

<img width="2051" alt="Screen Shot 2021-02-26 at 11 35 03 AM" src="https://user-images.githubusercontent.com/518059/109335391-942d8180-7827-11eb-81a3-ac43ece2f35a.png">

Somewhat astonishingly, stats don't make it seem like this has changed how Sibyl or the contact form are used. But it's a pretty bad experience for customers (the Submit button gets pushed way down the page). Any chance you can take a look and fix this?

I'm not overly opinionated that Sibyl's design needs to match exactly what it was before, but something that's similar in page weight would be wonderful.

**Comment by sixhours** [comment]
> Any chance you can take a look and fix this?

Sure, will take a look!
