### ISSUE TITLE
[EPIC] Add tracking to events to Gutenboarding

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#41059]
This task needs to be further defined, but the gist of it is that we'll need to add as many events as we can in order to compare this flow with old start flow.

The advice in pbAok1-Ao-p2#comment-1260 should guide us as we go.

### Tasks

- [x] Audit/create a diagram for the Gutenberg flow to get a visual aid for tracks flow events. See: https://github.com/Automattic/wp-calypso/issues/41059#issuecomment-613765368
- [x] Audit the current sign up flow for analytics events
- [x] ~Decide, or ask whether we should use existing signup names, e.g., `calypos_{...}` or a new one, e.g., `gutenboarding_{...}`~ We'll use current IDs, with with different `flow` values See: pbAok1-Ao-p2#comment-1260

#### Adding events for Gutenboarding

- [x] Implement starting and completing signup events, try to reuse `calypso_signup_start` and `calypso_signup_complete` https://github.com/Automattic/wp-calypso/pull/41129
- [x] Implement start and end events for each step, e.g., intent gathering, design and so on. #41167
- [x] Add properties to step tracking https://github.com/Automattic/wp-calypso/pull/41431
- [x]  Implement open and close events for modals, e.g., domain picker. See: pbAok1-Ao-p2#comment-1267
- [x] ~Implement `button_click` events on Next/Back buttons https://github.com/Automattic/wp-calypso/pull/41462~ Looks like we don't need this for track right now pbAok1-Ao-p2#comment-1505
- [x] Implement a generic event for errors like calypso_signup_error #41273
- [x] ~Where we've mixed the flow with existing pages, e.g., plans or login, ensure that we're passing the correct flow name (assuming we have to). For the plans page,~[ the signup framework uses the name of the flow,](https://github.com/Automattic/wp-calypso/blob/9793440/client/signup/config/flows-pure.js#L358) which is `prelaunch` We're already tracking these steps in the original signup code
- [x] Add traintracks tracking for domains [Example](https://github.com/Automattic/wp-calypso/blob/master/client/components/domains/domain-registration-suggestion/index.jsx#L87) #41173

#### Future iteration tasks

- [ ] Add Google analytics to Gutenboarding, and use it for click-based events. Probably a separate task/mini-project given the scope of the tracks migration into `/packages`

#### Registering events
⚠️  For each new tracking even we create, we'll need to "register them" See: pbAok1-Ao-p2#comment-1260

Events registered so far:
- `calypso_signup_leave` https://github.com/Automattic/tracks-events-registration/pull/241 (introduced by https://github.com/Automattic/wp-calypso/pull/41167)
- `calypso_signup_error` https://github.com/Automattic/tracks-events-registration/pull/240 (introduced by https://github.com/Automattic/wp-calypso/pull/41273)

**Comment by ramonjd** [comment]
Hi @roo2 ! Do you mind tackling this one next up?

A good place to start would be to see what we're tracking on the current signup flow, and find the most appropriate parallel in Gutenboarding. 

As for the event IDs, we could use the same ID and track ID pattern for Gutenboarding events as we have in the current signup at least for development PRs. We can always find and replace them after we get advice from the data team.

Thanks!! 🙇

**Comment by roo2** [comment]
Yep l'll look at adding the events suggested by martin now!

**Comment by ramonjd** [comment]
I've created a very rough diagram of the flow/steps. 

Not sure it's helpful yet :) 

<img width="2015" alt="gb-flow-diagram-v1" src="https://user-images.githubusercontent.com/6458278/79289592-0d243300-7f0d-11ea-8797-227185b396bb.png">

**Comment by ramonjd** [comment]
Quoting from pbAok1-Ao-p2#comment-1260:

For your tracking, you should be able to have just a couple of events:

1. `calypso_signup_step_enter`
2. `calypso_signup_step_leave`

Where every event has these two properties:

1. `flow` with a value like `gutenboarding` or `gb202004`
2. `variant:domain_first` (I don’t know if that specific value makes sense, but if you’re testing different orderings, you could use a `variant` prop like this OR you could keep a list of variants on a P2 and use names like `gb202004_a` or something.
3. `step` for the current step name, e.g. ‘domain’.
4. Optional: One cool thing to include on every `_leave` event would be a property for `time_in_step`to record how many seconds they spent in that step.

So for example `intent_gathering` might be one step:
```
someTrackingCall( 'calypso_signup_step_enter', {
    flow: 'gutenboarding',
    step: 'intent_gathering',
    variant: 'some_variant_id`, // something referring to "soft launch" for example?
    time_in_step: 123123 // this might be good for a future iteration?
} );
```

**Comment by simison** [comment]
@ramonjd you can find quite extensive flow diagram also from Figma file.

**Comment by ramonjd** [comment]
> you can find quite extensive flow diagram also from Figma file.

Thanks. I basically copied it from there so I wouldn't have to open Figma again for at least another two days :trollface:

**Comment by simison** [comment]
I don't want the use of "gutenboarding" term to move focus to just the initial few steps of onboarding; let's also track what goes on in later steps. Namely, I'd like us to track the "launch" button and "welcome modal" in wp-admin.

**Comment by ramonjd** [comment]
For the plans page, [the signup framework uses the name of the flow, which is prelaunch](https://github.com/Automattic/wp-calypso/blob/9793440/client/signup/config/flows-pure.js#L358)

<img width="1007" alt="Screen Shot 2020-04-16 at 7 36 50 pm" src="https://user-images.githubusercontent.com/6458278/79440942-f61f3700-8019-11ea-9bc7-590c5b5b1218.png">

We could make it consistent with whatever flow id we're using for Gutenboarding (`gutenboarding`, `new`, `gb_signup` or whatever), but it's unique enough I think.

**Comment by ramonjd** [comment]
> let's also track what goes on in later steps. Namely, I'd like us to track the "launch" button and "welcome modal" in wp-admin.

What do you mean by "wp-admin" in this context? Is there some point at which the Gutenberg flow takes us into `wp-admin`?

I _think_ it should be straight forward to add an event listener to the launch button, seeing as we build it in [gutenboarding overrides](https://github.com/Automattic/wp-calypso/blob/master/apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js#L44), **and** we're using the tracks library in `/apps` it seems anyway.

The launch "flow" beyond that is still called `'frankenflow'` (which I guess we should change at some point too). Since it's part of the signup framework, it's tracked already so we don't have to touch it. The name of the flow isn't really important to build funnels, so long as we know what it is and it's unique. `'frankenflow'` is certainly unique enough 🤣 but we might like to change it to `'new-launch'` or something.

As for the welcome modal, we mean this one (?):

<img width="983" alt="Screen Shot 2020-04-17 at 8 54 24 am" src="https://user-images.githubusercontent.com/6458278/79514726-37e7c600-808a-11ea-81bb-d2ef605e9e1f.png">

If what I'm seeing is correct, and it's part of the FSE plugin, I'd tend to think that it's beyond the scope of this specific round of analytics. 

FSE has implemented a [small tracking library for the page template modal](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/utils/tracking.js), which we could probably copy or extend. We might have to get in touch with @marekhrabe to make sure.

What do we want to track exactly on the welcome modal? Clicks? Dismissals?

**Comment by ramonjd** [comment]
Some inspiration for whenever we implement a `time_in_step` property

p7H4VZ-2x2-p2

**Comment by ramonjd** [comment]
The groundwork for tracking is done for Gutenboarding. The next tasks will be refining, testing in funnels.
