### ISSUE TITLE
Editor: Remove deprecated code for WordPress.com editor

### ISSUE THREAD

**Issue by creativecoder** [Automattic/wp-calypso#41106]
## Requirements

After the [WordPress.com editor is deprecated](https://github.com/Automattic/wp-calypso/issues/41086), remove all unneeded code related to the Calypso editor and the editor preference.

### Items to remove

(please add to this list as you find more things)

- [x] Remove code for temporary notices in the editor #41087, #41084
- [x] Remove code related to Customer home notice (wpcom and Calpyso, search code for `TASK_EDITOR_DEPRECATION`) (https://github.com/Automattic/wp-calypso/pull/46633 and D50746-code)
- [x] Calypso state (e.g. selectors) that have to do with whether or not to load Gutenberg (@allilevine #45938) (also https://github.com/Automattic/wp-calypso/pull/45686)
- [ ] Editor preference code in wpcom that is used for the web platform (since mobile still depends on the editor preference, for now)
- [ ] Mark relevant wpcom API endpoints as deprecated (any v1 editor related endpoints that aren't used by the block editor or elsewhere in Calypso)
- [x] Editor code in client/post-editor (though [will need to move](https://github.com/Automattic/wp-calypso/issues/46367) any components, state, etc that are needed elsewhere in Calypso) (@allilevine #46331)
- [x] e2e tests for the Calypso editor that were skipped in #45041 (after we're sure we don't need to port these to the block editor in some way) (@creativecoder)
- [x] code related to the `in-editor-deprecation-group` query parameter, including [code in Jetpack](https://github.com/Automattic/jetpack/blob/5230b31e25e77e7233eed3379a6ad309ba2d77b3/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L309) (@pablinos https://github.com/Automattic/jetpack/pull/17475)

**Comment by creativecoder** [comment]
Note that @aaronrobertshaw got a start on one part of this in https://github.com/Automattic/wp-calypso/pull/44733

**Comment by creativecoder** [comment]
Note there are several e2e tests for the Calypso editor that were skipped in https://github.com/Automattic/wp-calypso/pull/45041 -- these can be removed after we're sure we don't need to port these to the block editor in some way.

**Comment by creativecoder** [comment]
Checklist to get started on code removal

- Calypso state (e.g. selectors) that have to do with whether or not to load Gutenberg
- Editor preference code in wpcom that is used for the `web` platform (since mobile still depends on the editor preference, for now)
- Mark relevant wpcom API endpoints as deprecated (any v1 editor related endpoints that aren't used by the block editor or elsewhere in Calypso)
- Editor code in `client/post-editor` (though will need to move any components, state, etc that are needed elsewhere in Calypso)

**Comment by creativecoder** [comment]
I've updated the issue description with a checklist for the items we're aware of, so far, that we can remove.

**Comment by allilevine** [comment]
>     Calypso state (e.g. selectors) that have to do with whether or not to load Gutenberg (@allilevine)

I'm going to start working on removing this item.

**Comment by creativecoder** [comment]
I'm adding another item to the list, which as to do with `in-editor-deprecation-group` query parameter, including [code in Jetpack](https://github.com/Automattic/jetpack/blob/5230b31e25e77e7233eed3379a6ad309ba2d77b3/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L309)

**Comment by pablinos** [comment]
[This is a PR for removing the redundant code](https://github.com/Automattic/jetpack/pull/17475) from Jetpack. We still need the `in-editor-deprecation-group` query parameter in the iframe because this triggers the classic editor block tour. We should probably set a point in the future to remove that too.

**Comment by creativecoder** [comment]
> We still need the in-editor-deprecation-group query parameter in the iframe because this triggers the classic editor block tour. We should probably set a point in the future to remove that too.

Thanks @pablinos, that makes sense ! I checked that item off the list in the description of this issue.

Does this issue cover the rest of the code that needs to be removed? https://github.com/Automattic/wp-calypso/issues/46472

**Comment by pablinos** [comment]
Yes, I think so. At that point we should be able to remove the web editor preference too.

**Comment by creativecoder** [comment]
> At that point we should be able to remove the web editor preference too.

@pablinos Do you mean the the code in Calypso related to editor type, such as [getSelectedEditor](https://github.com/Automattic/wp-calypso/blob/2eff0c49dfee1fb27461bd1e11ee4e93d2d83e6e/client/state/selectors/get-selected-editor.js#L9)?

I thought about that, but do we still need it for `gutenberg-redirect` and `gutenberg-redirect-and-style`? Or do you think that's all handled by the `isEligibleForGutenframe` now?

**Comment by creativecoder** [comment]
> e2e tests for the Calypso editor that were skipped in #45041 (after we're sure we don't need to port these to the block editor in some way)

I confirmed that the tests skipped in #45041 were either removed because they're no longer relevant (https://github.com/Automattic/wp-calypso/pull/46064) or updated to work with the block editor (https://github.com/Automattic/wp-calypso/pull/45583)

**Comment by pablinos** [comment]
> I thought about that, but do we still need it for gutenberg-redirect and gutenberg-redirect-and-style?

Kind of, because we are still using Calypsoify, but yes, whether to redirect should be determined by `isEligibleForGutenframe` in future. There are still sections of the code checking the editor value directly, so it's a case of looking for those and swapping them out.

**Comment by creativecoder** [comment]
> ... whether to redirect should be determined by isEligibleForGutenframe in future. There are still sections of the code checking the editor value directly, so it's a case of looking for those and swapping them out.

Thanks @pablinos, I created a separate issue for removing editor type: https://github.com/Automattic/wp-calypso/issues/46576. Please let me know if that captures accurately what we need to do.

**Comment by creativecoder** [comment]
> Mark relevant wpcom API endpoints as deprecated (any v1 editor related endpoints that aren't used by the block editor or elsewhere in Calypso)

It looks like we can do this by passing the `deprecated` (true|false) and `new_version` arguments when the endpoint is registered. (See class.json-api-endpoints.php#L173).

Potential endpoints to be deprecated include those listed at https://developer.wordpress.com/docs/api/#posts

- Some of those are probably still in use and haven't been replaced by v2 endpoints, such as the endpoints for likes and followers
- I think /me/posts is probably still used for the post list in Calypso
- I think v1 endpoints for revisions (not listed in the docs) can also be deprecated since I believe we have v2 endpoints -- will need to check if those are still used in Calypso or not, though

**Comment by creativecoder** [comment]
Tasks left

> Remove code related to Customer home notice (wpcom and Calpyso, search code for TASK_EDITOR_DEPRECATION)

- PR to remove related Cards from wp-calypso

> Editor preference code in wpcom that is used for the web platform (since mobile still depends on the editor preference, for now)

Mobile apps are still using some of the remaining library code related to the editor preference, wpcom/v3/sites/gutenberg endpoint, and Gutenberg opt-in library. We need a separate issue to remove this, and the User RC interface once mobile apps no longer rely on this.

Also related: https://github.com/Automattic/wp-calypso/issues/45513

> Mark relevant wpcom API endpoints as deprecated (any v1 editor related endpoints that aren't used by the block editor or elsewhere in Calypso)

There's still more to do here related to the data layer and state code only used by the deprecated editor. Spinning off a separate issue to handle that

https://github.com/Automattic/wp-calypso/issues/46578

**Comment by pablinos** [comment]
#46633 Is to remove the related card from Calypso

**Comment by creativecoder** [comment]
> Mark relevant wpcom API endpoints as deprecated (any v1 editor related endpoints that aren't used by the block editor or elsewhere in Calypso)

I did a bit of checking at the stats that track the number of daily endpoint requests related to posts. I didn't see anything that's drastically declined. I think we're still using some of these v1.1 endpoints for various tools in Gutenframe (but I didn't dig deeply to confirm). Therefore, I don't think it's time to mark them as deprecated yet--that needs to be part of a more comprehensive effort to replace the v1.1 API usage in Calypso.

---

All other tasks related to this issue have been spun off into separate issues. The [editor deprecation milestone](https://github.com/Automattic/wp-calypso/milestone/309) tracks those, so I'm closing this issue.
