### ISSUE TITLE
Gutenboarding: Mobile cleanup

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41138]
Things are generally looking nice. I've caught a few things:

- [x] Design step has [weird border around the whole content container](https://d.pr/i/AW6pdA). Style step [has it too](https://d.pr/i/72M7cI). [Fixed in #41186]
- [x] Going from Design step to Fonts step [doesn't scroll to the top](https://d.pr/i/x01w6b) so you miss the headline. [Fixed in #41323]
- [ ] Focusing on a input field [zooms the screen in slightly](https://d.pr/i/bECkgm). Is it possible to disable this? Let's not disable zoom all-together though, just the auto-zoom if that's possible.
- [ ] The padding around the WordPress icon is [different to the other pages](https://d.pr/i/vEAMjs). Let's match them all.
- [ ] Domain overlay has [too much padding from the edge](https://d.pr/i/50sJ8v). Let's match it to the other pages which I think is `20px`.
- [ ] Clicking done on the iOS keyboard in the domain overlay closes the domain overlay. Done should only close the keyboard. Also this is causing the domain selection to reset https://github.com/Automattic/wp-calypso/issues/42512
- [ ] Clicking back from the Payment screen goes back to a loading screen saying ["Hooray! Your site will be ready shortly."](https://d.pr/i/KvZOND)
- [ ] More domain picker iOS specific issues https://github.com/Automattic/wp-calypso/issues/41752

There's a few other things about the plans and payments screens, but since they also extent to desktop I'll create a separate issue.

**Comment by simison** [comment]
I'll close as many of these are handled or outdated.
