### ISSUE TITLE
Integrate A/B testing capabilities outside of Calypso

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#41165]
**Update Dec 2020:** exPlat experiments are replacing abtest lib but some of the concerns are still applicable since the JS code of the new platform lives also inside Calypso. Thread to follow: pbmo2S-Ca-p2
___

Eventually, once the Gutenberg flow is stable, and we have our tracking events working (https://github.com/Automattic/wp-calypso/issues/41059) we might want to think about conducting some A/B tests.

By "stable" we mean that we won't be introducing changes that might effect the outcome of any test.

The [abtest lib contains a few Calypso dependencies](https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/index.js#L12), which may affect the decision to migrate it to `/packages`

### Tasks

- [ ] Investigate the [current A/B test code](https://github.com/Automattic/wp-calypso/tree/master/client/lib/abtest) and work out if it's something we'll have to migrate to `/packages`, similar to what we did for Tracks (https://github.com/Automattic/wp-calypso/pull/39001)
- [ ] If we do have to migrate, plan and estimate the migration effort. We'll not only have to move the library into a new package, but update all references for existing tests in Calypso and conduct integration tests. 
- [ ] Whether we migrate the package or simply import from `/client/lib`, run a smoke run A/B test in Gutenberg to see if it works.

More context: pbAok1-Ao-p2#comment-1282

**Comment by klimeryk** [comment]
Just noting that https://github.com/Automattic/wp-calypso/pull/41882 probably will pull in abtest lib anyway into Gutenboarding as noted there.

**Comment by ramonjd** [comment]
Looks like it won't be as straight forward as this PR description postulates

> Regarding lib/abtest size, this will require a substantial rewrite. The whole library is based around a class model, with most of the functionality living in instance methods. This makes it impossible to split up.

> We'd need to rewrite it into a modularised approach, using exported methods instead of instance methods.

https://github.com/Automattic/wp-calypso/pull/41882#issuecomment-625363395

**Comment by roo2** [comment]
I've investigated this and it actually looks like including the existing `lib/abtest` library is a good approach. 
Including the `lib/abtest` library in gutenboarding only increased file size of the gutenboarding bundle by ~7KB ( **only 2KB Gzipped** ) https://github.com/Automattic/wp-calypso/pull/43678

The only issue is that `lib/abtest` relies on a "user" object being initialized https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/index.js#L14. In gutenboarding however, the "user" object is uninitialized. 

I was able to get the abtest library to work without a "user" object with one small tweak. https://github.com/Automattic/wp-calypso/pull/43678/files#diff-bfc7821cb918626d5e06f83e8854c679R204

However there is logic in the abtest library around **selecting users based on their locality or country code**. In order to make this logic work correctly we need to work out how to initialize the "user" in  way that can be consumed by the abtest library.

I had a stab at initializing the user but it wasn't completely straightforward. But considering we've done it in the main calypso app, it should be achievable with a little more effort.

**Comment by ramonjd** [comment]
cc @simison @johnHackworth 

Let us know if you'd like us to follow this up based on @roo2's investigations. 

I may be getting ahead of myself, so will need A/B testing in the next couple of months? If so, it might be worth getting it ready.

**Comment by razvanpapadopol** [comment]
With the deprecation of the abtest library we should update also this issue. Currently, pbmo2S-Ca-p2 seems to be the latest discussion on the subject.

**Comment by ramonjd** [comment]
Thanks @razvanpapadopol 

Rather than overwrite this issue, we'll keep it in the museum so future developers can visit and ask, "Is that how you used to A/B test, grandpa?" 😆 

Just kidding, I think it it'll be just as easy to create a new issue once we get feedback from pbmo2S-Ca-p2#comment-1375
