### ISSUE TITLE
Gutenboarding: Gutenberg latest issues

### ISSUE THREAD

**Issue by dubielzyk** [Automattic/wp-calypso#41214]
Here are a list of issues that were introduced with the latest launch of Gutenberg.

- [x] (@sirreal #41322) The hover and click state for the [font buttons](https://d.pr/i/rxaFGJ). Hover state should be black text and outline and click state should be the same as active state or hover state.
- [x] (@sirreal #41321) The device buttons. The hover state should be dark black and active state the same. Remove the border that exist on hovering the active state. 
- [ ] (@sirreal #41370) Domain picker. Hover state should be `1px solid --studio-gray-100` instead of the `2px solid blue`
- [ ] (@sirreal #41370) Domain picker. When clicking the domain picker and clicking it again to close it it gets [this blue border](https://d.pr/i/GJCye6). Lets remove that

**Comment by razvanpapadopol** [comment]
> Domain picker. When clicking the domain picker and clicking it again to close it it gets this blue border. Lets remove that

That's the focus/hover border. When closing the domain picker modal, the focus is returning to the button which was focused previously. I think we should just use correct styling for that border, not remove it entirely, right?
cc: @dubielzyk

**Comment by sirreal** [comment]
Working on this in https://github.com/Automattic/wp-calypso/pull/41321

**Comment by sirreal** [comment]
I've tentatively assigned the Domain Picker tasks to @razvanpapadopol.

**Comment by sirreal** [comment]
I've unassigned everyone. @razvanpapadopol let's make it clear when one of use gets started on the Domain Picker tasks so we don't duplicate work 👍

**Comment by sirreal** [comment]
#41370 contains the remaining fixes for this.
