### ISSUE TITLE
Plugin updates: Gutenberg v7.9.1

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#41265]
Gutenberg v7.9.1 [was released on April 16, 2020](https://github.com/WordPress/gutenberg/releases/tag/v7.9.1).

This issue tracks progress upgrading wpcom and issues to address along the way.

With v7.9.1 we're skipping stable version 7.9.0 due to issues with the Button block and the plugin sidebar not defaulting to displaying the installed plugins. v7.9.1 includes PRs https://github.com/WordPress/gutenberg/pull/21642 and https://github.com/WordPress/gutenberg/pull/21645 that should resolve these issues.

## Gutenberg

* [x] Install version 7.9.1 (D42121-code)
* [x] Activate version 7.9.1 on edge sites (D42124-code)
* [ ] Activate version 7.9.1 on prod:
* [ ] Clean up old versions of GB
* [ ] Request update for AT sites

## Other

* [x] Call for testing (add to CfT for 7.9.0): p7DVsv-8tt-p2
* [ ] E2E tests stable version PR: (TBC)

## Bugs encountered 🐛

* [ ] Further issues with buttons using existing markup: https://github.com/WordPress/gutenberg/issues/21685, https://github.com/WordPress/gutenberg/issues/21747, https://github.com/WordPress/gutenberg/issues/21707
* [x] Home button at top left in v7.9.0/v7.9.1 has additional spacing in legacy dotcom-FSE sites (logged in https://github.com/Automattic/wp-calypso/issues/41269)
* [x] Spacing issue addressed in https://github.com/Automattic/wp-calypso/pull/40361 has re-surfaced (check mobile layout of editor in legacy dotcom-FSE sites) p1587107834248800-slack-gutenberg-on-dotcom
* [ ] The broken `Continue reading` button issue in the Latest posts block should 🤞be fixed this upgrade (https://github.com/Automattic/wp-calypso/issues/40500)

**Comment by andrewserong** [comment]
I'm closing this issue now in favour of #41504 — as of April 28th, we haven't upgraded to v7.9.1 due to theme compatibility issues with the Button block markup. v8.0.0 resolves this by reverting the markup changes, so we can skip v7.9.1.
