### ISSUE TITLE
Plugin Updates: Gutenberg v8.0.0

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#41504]
Gutenberg v8.0.0 RC 1 [was released on April 27, 2020](https://github.com/WordPress/gutenberg/releases/tag/v8.0.0-rc.1).

This issue tracks progress upgrading wpcom and issues to address along the way.

With v8.0.0 we are skipping Gutenberg versions v7.9.0 and v7.9.1 due to [theme incompatibility issues](https://github.com/WordPress/gutenberg/issues/21909) with the simple Button markup that was introduced in https://github.com/WordPress/gutenberg/pull/21266. v8.0.0 includes https://github.com/WordPress/gutenberg/pull/21923 which reverts that changes to the Button block markup.

## Gutenberg

* [x] Install version 8.0.0 RC 1 (D42541-code)
* [x] Activate version 8.0.0 RC 1 on edge sites (D42542-code)
* [x] Install final version 8.0.0 (D42684-code)
* [x] Activate final version 8.0.0 on edge sites (D42687-code)
* [x] Activate final version 8.0.0 on production
* [x] Request update for AT sites (requested at p9o2xV-Rm-p2)
* [x] Clean up old versions of GB (D42967-code)

## Other

* [x] Call for testing: p7DVsv-8yH-p2
* [x] E2E tests against RC 1: https://github.com/Automattic/wp-calypso/pull/41505
* [x] E2E tests stable version PR: https://github.com/Automattic/wp-calypso/pull/41660

## Bugs encountered 🐛
* [x] Wpcom FSE compatibility with Gutenberg v8.0.0: full width blocks overflow the page container (https://github.com/Automattic/wp-calypso/issues/41513) (will be fixed by https://github.com/Automattic/wp-calypso/pull/41575)
  - [x] Note: https://github.com/Automattic/wp-calypso/pull/41575 has been merged, but the FSE plugin needs a version bump and to be deployed to the backend & .org before this change will be rolled out. See: PCYsg-mMA-p2
* [x] Mobile header layout regressions (https://github.com/Automattic/wp-calypso/issues/41521) (will be fixed by https://github.com/Automattic/wp-calypso/pull/41575 and https://github.com/Automattic/wp-calypso/pull/41572)
* [x] Duplicate Preview links appearing in the header (https://github.com/Automattic/wp-calypso/issues/41519) — fixed in https://github.com/Automattic/wp-calypso/pull/41528
* [x] The broken `Continue reading` button issue in the Latest posts block should 🤞be fixed this upgrade (#40500) - (@Addison-Stavlo confirming this now works on 8.0)
* [ ] The block inserter in legacy dotcom FSE sites does not include block patterns (https://github.com/Automattic/wp-calypso/issues/41654)
  - Note: this should be considered non-blocking and should be prioritized in the maintenance backlog.
* [x] Need to fix failing tests in D42693-code (themes API adds additional fields in response)

**Comment by andrewserong** [comment]
Looks like the FSE plugin changes in #41575 will be deployed in https://github.com/Automattic/wp-calypso/pull/41755

**Comment by Addison-Stavlo** [comment]
> Looks like the FSE plugin changes in #41575 will be deployed in #41755

I tested them on that build this morning.  They are working well! 😄

**Comment by andrewserong** [comment]
Excellent, thank you @Addison-Stavlo! 😃

**Comment by Addison-Stavlo** [comment]
We can now close this issue, thanks everyone for your work on this!
