### ISSUE TITLE
Gutenboarding: rename tracking events

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#41838]
In implementing tracking for Gutenboarding, we borrowed our old friends `calypso_signup_*` to use as event names.

See: https://github.com/Automattic/wp-calypso/issues/41059

We should rename them to something more representative of Gutenboarding because:

- this flow will also be used by users that don't need to signup at all
- the future of Gutenboarding as a signup flow is not confirmed (it might be destined to live its life out as a site builder)

### Tasks

- [x] Do a good 'ol find and replace on **[Gutenboarding events](https://github.com/Automattic/wp-calypso/tree/master/client/landing/gutenboarding)** from `calypso_signup_*` to `calypso_newsite_*` #41840 
- [x] Run through the flow and check that they are firing as expected
- [x] Register all new events https://github.com/Automattic/wp-calypso/issues/41838#issuecomment-624371456

**Comment by ramonjd** [comment]
Events that need to be registered:

| Current | New | Notes | Registered | 
|---|---|---|---|
|`calypso_signup_start`|`calypso_newsite_start`| New event  |   | 
|`calypso_signup_complete`|`calypso_newsite_complete`| New event  |   |
|`calypso_signup_error`|`calypso_newsite_error`|  Already registered as a new event, needs renaming |   |
|`calypso_signup_modal_close`|`calypso_newsite_modal_close`| New event  |   |
|`calypso_signup_modal_open`|`calypso_newsite_modal_open`| New event  |   |
|`calypso_signup_step_leave`|`calypso_newsite_step_leave`| Already registered as a new event, needs renaming  |   |
|`calypso_signup_step_enter`|`calypso_newsite_step_enter`| New event  |   |
