### ISSUE TITLE
Gutenboarding tracking integrity/verification

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#42311]
This task is to track our double/triple verification of our tracking events. 

We've identified possible areas to check over in https://github.com/Automattic/wp-calypso/pull/42309#pullrequestreview-413206272

- [x] ~Ensure that that the `_start` events are not fired again once a user returns to the Gutenboarding flow from the login flow or any other "frankenflow"~ See [comment](https://github.com/Automattic/wp-calypso/issues/42311#issuecomment-629942145)
    * Prevent calling `_start`  after login https://github.com/Automattic/wp-calypso/pull/42312
- [x] Check that all events (start, complete, steps, modal) are tracked correctly and in the right order in various browsers/devices (IE, FF, Safari, mobile safari )
- [x] If a user enters checkout and empties their cart, we should make sure we register `calypso_newsite_complete` https://github.com/Automattic/wp-calypso/pull/42316
[Some questions](https://github.com/Automattic/wp-calypso/issues/42311#issuecomment-629895430)
- [x] Domain modal and domain popover events should be distinguishable #42391

**Comment by ramonjd** [comment]
> If a user enters checkout and empties their cart, we should make sure we register calypso_newsite_complete 

This one is tricky. We're not firing `calypso_newsite_complete` after checkout at all. 

This is because Gutenboarding farms the flow off to checkout with the instructions to redirect to the editor after checkout. We're effectively leaving Gutenboarding, and therefore leaving our tracking implementation.

I see two approaches for now:

1. Fire the complete event in Gutenboarding [before we redirect to the checkout](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/hooks/use-on-site-creation.ts#L109) signalling that Gutenboarding site creation is complete
2. Re-implement our tracking method in the checkout code and fire if we detect a Gutenboarding site creation param. This is messy, but if it's better for our funnels, then we just do it :)

I've looked at some of the funnels and I don't think option 1 would upset any current stats, but it depends on our definition of Gutenboarding "complete". 

Should we consider checkout as part of the flow, or can we say that the flow is complete when we've created a site via Gutenboarding and leave the flow (to checkout or wherever)?

**Comment by ramonjd** [comment]
>  Ensure that that the _start events are not fired again once a user returns to the Gutenboarding flow from the login flow or any other "frankenflow"

Apparently this is okay:

> But once a user has been assigned to a variation in this test, they should always end up in the same flow, right?  fwiw if we get multiple _start events for the same flow when a user returns to a flow, that's fine in these edges cases, as long as the flow property is correct.  The funnels and Hypotheses will ignore the repeat events.

**Comment by ramonjd** [comment]
> Fire the complete event in Gutenboarding before we redirect to the checkout signalling that Gutenboarding site creation is complete

We've discussed this in and this option seems okay because:

> We're going to be looking at longer purchase conversion windows anyway (3 days, 7 days, 14 days, maybe longer), so IMO this works fine to mark site creation complete and track checkout separately.  In fact, since the dropoff at checkout is probably large, it's better not to have it part of the signup completion tracking.

> And we'll get a purchase event separately/later if they purchase something.  We can adjust the funnels if any of them depend on the order or purchase and _complete.

https://github.com/Automattic/wp-calypso/pull/42316

**Comment by p-jackson** [comment]
Found an issue where you can't tell which modal the `calypso_newsite_modal_*` events are for.
#42391

**Comment by ramonjd** [comment]
we done gud
