### ISSUE TITLE
Plugin Update Gutenberg v8.2.1

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#42609]
We have installed an alpha version of gutenberg 8.2.0 to edge sites for early feedback, I will track early feedback and bugs here.

### Process

* [x] Install version 8.2.0-alpha.1 (D43814-code)
* [x] Activate version 8.2.0-alpha.1 on edge sites (D43820-code)
* [x] Install version 8.2.0-rc.1 (D43925-code)
* [x] Activate version 8.2.0-rc.1 on edge sites (D43930-code)
* [x] Install version 8.2.0 (D44074-code)
* [x] Activate version 8.2.0 on edge sites (D44076-code)
* [x] Install version 8.2.1 (D44099-code)
* [x] Activate version 8.2.1 on edge sites (D44108-code)
* [x] Activate final version 8.2.1 in production (D43823-code)
* [x] Request update for AT sites (p9o2xV-Tk-p2)
* [x] Clean up old versions of GB:
     - [x] `8.0.0` (D44147-code)
     - [x] `8.2.0-*` pre-releases and `8.2.0` release (D44146-code)

### Testing

* [x] Calypso E2E tests #42650
* [x] Teamcity tests D43823-code

### Bugs 🐛

* [x] Duplicate add button in FSE sites https://github.com/Automattic/wp-calypso/issues/42611
* [x] Image centering is broken #42637
* [x] Gallery block, using "Media Library" gives no results https://github.com/WordPress/gutenberg/issues/22338

### Follow-up issues

* Prepare for new block categories (https://github.com/WordPress/gutenberg/pull/19279#issuecomment-621322775)
* Adjust for new slotfill in W logo (https://github.com/WordPress/gutenberg/pull/22323) - we can get rid of most of our hacks to extend this?

**Comment by p-jackson** [comment]
Finished with the tidy up tasks. Thanks for the great work @roo2 and @ockham! 🚀

**Comment by sirreal** [comment]
@roo2 or @p-jackson is there an issue for the W logo hacks to clean up? Do you have any details on that?

If those required 8.3.0, now deployed, we may be able to act on that.

**Comment by sirreal** [comment]
This is wrapped up now.

**Comment by p-jackson** [comment]
> is there an issue for the W logo hacks to clean up? Do you have any details on that?

@sirreal PR ready for review here #43471.
