### ISSUE TITLE
Gutenboarding: Domain picker changes

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#43133]
We'll be adding Domain Picker as a step in Gutenboarding, replace Domain Popover with Domain Modal, remove domain categories and use an expandable domain suggestion list. 

There will be 2 main changes:

- [x] **Flow updates** [WIP in #43136]
   - Hide DomainPicker button on Intent Capture step and on Plans step.
   - When pressing DomainPicker button, show directly the domain Modal.
   - If the user enters a site title on Intent Capture then show Domain step next, before Design Selection.
   - If the user skips entering a site title, then show Domain step after Style Preview (before Plans).
   - On Domain page/modal action buttons should be: _Go back_ and _Skip for now_ / _Continue_

- [x] **Domain Picker updates (@alshakero)** [done in #43147]
   - Show an empty state when the user didn't entered a site title (and search input is empty).
   <img width="971" alt="Screenshot 2020-06-10 at 10 36 13" src="https://user-images.githubusercontent.com/14192054/84240291-7c319880-ab06-11ea-82c4-c663e2940f00.png">
    - Add a button to expand the list of domain suggestions.
    - Display 6 domains by default (5+1) and 11 domains (10 + 1) in expanded mode.
    - Hide domain categories sidebar.
    <img width="819" alt="Screenshot 2020-06-10 at 10 23 07" src="https://user-images.githubusercontent.com/14192054/84239010-8b174b80-ab04-11ea-98cd-3f9d66451801.png">

- [x] Ensure "recommended" is always first on the list (issue https://github.com/Automattic/wp-calypso/issues/42010, old PR https://github.com/Automattic/wp-calypso/pull/42011)

**Comment by simison** [comment]
@dubielzyk @olaolusoga was it so that we can switch _"I don't know"_ button label to _"Skip for now"_?

**Comment by dubielzyk** [comment]
Yep. Let's do it :)
