### ISSUE TITLE
Plugin Update Gutenberg v8.4.0

### ISSUE THREAD

**Issue by WunderBart** [Automattic/wp-calypso#43525]
We've installed the Gutenberg [`v8.4.0`](https://github.com/WordPress/gutenberg/releases/tag/v8.4.0) to edge sites for early feedback. The feedback and related bugs will be tracked here.

Call for Testing: p7DVsv-8Te-p2

### Process

* ~Install `v8.4.0-rc.1` (D45339-code)~
* ~Activate `v8.4.0-rc.1` for edge-stickered sites (D45343-code)~
* [x] Install `v8.4.0` (D45400-code)
* [x] Activate `v8.4.0` edge (D45401-code)
* [x] Publish a Call for Testing post (p7DVsv-8Te-p2)
* [ ] Draft public announcement and submit to Editorial for review
* [ ] Close the Call for Testing post
* [ ] Activate `v8.4.0` for all sites
* [ ] Request update for Atomic sites
* [ ] Publish announcement posts
   - [ ] Internal
   - [ ] Public
* [ ] Clean up unused releases
   - [ ] `v8.2.1`
   - [ ] `v8.4.0-rc.1`

### Testing

* [ ] Calypso E2E tests
* [ ] Teamcity tests

### Blockers 🐛

* [ ] Disable block library (https://github.com/Automattic/wp-calypso/issues/43677)
* [ ] Image editing broken for .com (https://github.com/Automattic/wp-calypso/issues/43676)
* [x] Navigation block broken for .com (https://github.com/Automattic/wp-calypso/issues/43736)
* [ ] https://github.com/Automattic/wp-calypso/issues/43784

### Follow-up issues

- TBA :)

**Comment by andrewserong** [comment]
Just noting that v8.4.0 appears to fix https://github.com/Automattic/wp-calypso/issues/43408, so we can double-check and close out that issue once v8.4.0 has landed in production.

**Comment by sirreal** [comment]
We can close this and migrate remaining issues to a 8.5.0 planning issue.

**Comment by fullofcaffeine** [comment]
> We can close this and migrate remaining issues to a 8.5.0 planning issue.

Tracking issue for `8.5.1` has been created here: https://github.com/Automattic/wp-calypso/issues/44079
