### ISSUE TITLE
EPIC: A PHP library to get the translated block markup for a particular design

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#43712]
## Outcome

A set of libraries/classes to take raw block HTML as input and output that HTML with translated strings

## Tasks
- [x] Pull design content and other relevant data from source sites: this includes [themes](https://github.com/Automattic/wp-calypso/blob/master/static/page-templates/page-templates.json#L110), and sites with the sticker `block-patterns-source-site` added)
- [x] Parse blocks to identify translatable text
- [x] Create and store reusable pattern templates on wpcom (to be defined)
- [x] Create a centralized library / functions that can used elsewhere in the codebase 
    - E.g., We now have a block-patterns-source-site sticker as used in D45466-code and D45467-code  let’s create a `wpcom_is_block_pattern_source_site` function in our library to wrap the `has_blog_sticker` calls we’re using around the place
- [x] Unit tests

**Comment by ramonjd** [comment]
D45748-code is our WIP :)

**Comment by lsl** [comment]
These tasks are mostly covered by the now deployed D45748-code, there is more work ongoing under the [Patterns label](https://github.com/orgs/Automattic/projects/147?card_filter_query=label%3APatterns).
