### ISSUE TITLE
Migrate WP-Desktop to Calypso

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#43737]
### Progress

- [x] Initial spike (#43324) [**Done**] @jsnajdr 
    - [x] Migrate desktop files to monorepo 
    - [x] Get the application building locally
    - [x] Ensure calypso continues to build as wp-desktop submodule
- [x] CI and e2e (#43709) [**Done**] @nsakaimbo 
    - [x] Build Mac 
    - [x] Build Linux
    - [x] Build Windows ~~[BLOCKED -- see below]~~ Electron dependencies isolated prior to #43324 landing)
    - [x] e2e Mac
    - [x] e2e Linux
    - [x] Slack and Github notifications (#43837) [**Done**]
- [ ] Desktop development environment
    - [x] Makefile @nsakaimbo (#43324)
    - [ ] existing `dev` and `dev-server` functionality [**Not Started**]
- [x] CI: application deployment [**In Progress**] @nsakaimbo 
    - [x] Mac notarization
    - [x] Publish to Github

### Background: Build System

Out of necessity, the way the desktop app has been built to-date is the JS source is built upstream in Linux and fed into native Mac, Linux and Windows jobs, where the final application binaries are compiled. This CI strategy is required because:

- Calypso source cannot be built on Windows
- The Calypso + Desktop source takes ~10 minutes to build. Building the source once upfront makes CI significantly faster. 

In a little more detail, the process outlined above looks like the following:

1. Desktop and Calypso source are built in a Linux environment
2. Built source is sent to downstream Mac, Windows and Linux jobs. The downstream platform-specific jobs install node modules, but only for the desktop (not Calypso). [Here](https://app.circleci.com/pipelines/github/Automattic/wp-desktop/16875/workflows/cbb1cd3a-45e1-4203-b119-482ad6e61817/jobs/65361/steps) is an example of what the final build step on Windows looks like. At this point, the Windows environment has received the prebuilt JS and only the Desktop-specific dependencies necessary to build the final application bundle are installed.
3. On each platform, the pre-built source is compiled with Electron binaries to produce the final build.

Because of the constraints mentioned above, a similar scheme needs to be maintained when migrating the Desktop app to Calypso in order to continue building the application for all its target platforms.

### Blockers/Risks

1. By merging Calypso and Desktop dependencies, we can reduce the footprint of the Mac .DMG from 100.2MB to 77.3MB ([link](https://github.com/Automattic/wp-calypso/pull/43324#issuecomment-646652454)). However, we discovered that combining the two projects' dependencies in this manner is an issue because:
    1. ~~Calypso packages cannot be built on Windows, therefore the node module installation step will fail because this triggers a rebuild of Calypso's packages. (Side note: using `--ignore-scripts` flag is not an option here because we need the default behavior to rebuild the Electron binaries. Also, trying to hack around this seems like code smell that will inevitably bite us later).~~
    2. ~~Module installation now takes \~4.5 minutes when constructing the final application bundle for each platform: [link](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/65123/workflows/69f62ec9-7575-4f8c-a4f2-1d734f48d4f5/jobs/787918).~~ ~~Because of this overhead, the Mac job that would take 3-5 minutes to complete will now take roughly 7-9 minutes instead (factoring e2e tests). A concern here is it the time added to developer workflow when running (or re-running) CI. In contrast, this step was taking < 1m until now: [link](https://app.circleci.com/pipelines/github/Automattic/wp-desktop/16875/workflows/cbb1cd3a-45e1-4203-b119-482ad6e61817/jobs/65359/steps).~~
    **Update**: desktop/Electron dependencies have been sufficiently isolated prior to #43324 landing, so this issue should be addressed.
2. The exact way in which we'll tackle the problems encountered so far is still evolving, but we minimize disruption to existing desktop infrastructure and release cycle. This is a tricky given that Calypso is currently a submodule of the wp-desktop repo. We should be strategic in minimizing the window of time in which the existing wp-desktop processes (CI, release calender) are effectively taken offline.

**Comment by nsakaimbo** [comment]
All items addressed, save for local dev server - closing and will track remaining work in separate issue.
