### ISSUE TITLE
[EPIC] Step-by-step Launch: missing features

### ISSUE THREAD

**Issue by yansern** [Automattic/wp-calypso#43750]
This is a list of missing features in the Step-by-step launch flow from editor, many of them already available in the Focused Launch flow: pbAok1-1IU-p2

Not all al them are High priority so we'll need to do some triaging and split into High/Normal/Low.

## Design
Latest design iteration: pcbO8q-4l-p2

## Launcher Plugin
- [x] **Fix sidebar on mobile** #44692
- [ ] **Add a backdrop over editor and Getting started button** when sidebar is open the first time (no step is selected). https://cloudup.com/cu62Vcrofzl
- [x] **Update sidebar title with how many steps are left to complete** https://cloudup.com/cZSQj47DGL9
- [ ] **Add site preview** with real time update of the site title on the first step. https://cloudup.com/cRg0dZffLhu
- [x] **Fix modal styling** #44691 (@yansern) 
- [x] **Style loading screen** when waiting for launch site API response. https://cloudup.com/cH2LOXynLIo
First version should just say "**Hooray!** Your site will be ready shortly." on full screen. (@yansern)
- [x] **Add site name step** #44708 (@razvanpapadopol) 
- [x] **Create a launch sidebar** and include launch steps as cards. (@yansern) #44278
- [x] **Create a host modal frame.** (@yansern) https://github.com/Automattic/wp-calypso/pull/43825
  This modal frame will contain each steps as child component. For the domain step and plans step, it will contain the domain picker smart container & plans grid smart container.
- [x] **Only show the new launch flow in gutenboarding created sites.** (@yansern) #44069
- [x] **Only show launch button when site is unlaunched.** (@razvanpapadopol) #43983
  See `editor-gutenboarding-launch` for example. Also [here](https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L338) is the condition in Calypsoify iframe.
- [x] **Create a shared `LAUNCH_STORE` data store.** (@razvanpapadopol) #43983
  This is like the `ONBOARD_STORE` in gutenboarding. It will hold data to be used by DomainPicker & PlansGrid plugin.
- [x] **Discuss: Role of `LAUNCH_STORE` vs `DOMAIN_STORE` & `PLANS_STORE`.**
  In gutenboarding, the `currentDomain` is in the `ONBOARD_STORE` (so that means it will probably be in the `LAUNCH_STORE` in FSE-world equivalent). However, the `currentPlan` is stored in the `PLANS_STORE`. Should `currentDomain` be in the `DOMAIN_STORE` instead? Some discussion happening here: https://github.com/Automattic/wp-calypso/pull/43858/files#r449022369. Decision made here: https://github.com/Automattic/wp-calypso/pull/43935/files#r450782824
- [x] **Discuss: Should launcher plugin import the smart containers from another plugin folder on FSE?**
  We'll import smart containers from another plugin folder for now. Which means launch plugin's bundle includes code from domain and plan plugin's bundle for now.

## DomainPicker Plugin
- [ ] **Add "I already own domain" link** https://github.com/Automattic/wp-calypso/issues/44645
- [x] **If the user purchased a plan without registering a paid domain**, show _Included in your plan_ tag next to each domain item https://github.com/Automattic/wp-calypso/issues/42710
- [x] **DomainPicker under FSE shouldn't suggest another free domain anymore.** (@yansern) https://github.com/Automattic/wp-calypso/pull/44146
  When user is launching a site, the existing free sub-domain is already assigned to the site so we just display it as a static option.
- [x] **Fix small visual issue after style alignment** https://github.com/Automattic/wp-calypso/pull/44087#pullrequestreview-450057630
- [x] **Turn DomainPicker plugin into smart container** (@yansern) https://github.com/Automattic/wp-calypso/pull/43858 
  Currently the logic is in a domain picker button, the UI is in the domain picker modal component. Perhaps the logic & UI should be in a smart container. This is so it can be reused as a modal or popup or whatever the parent component is.
- [x] **`currentDomain` param to be a string instead of an object of `DomainSuggestion` type.** (@alshakero) https://github.com/Automattic/wp-calypso/pull/43799
  This is because there is no way to reconstruct an initial `currentDomain` object of `DomainSuggestion` type. Investigate if this is possible and what impact will it cause.
- [x] **Use the site title which can be taken from from the `SITE_STORE` as initial search term.**
 Turns out this was already done.
- [x] **Discuss: `currentDomain` is extracted from `SITE_STORE`.**
  Is this the right way to do it? Probably yes. We'll display it as the skip option, the [free domain](https://github.com/Automattic/wp-calypso/pull/43983/files#diff-7e9d3198ff83eaf435fe413ff67d6c82R25-R26) that will go with the Free plan. Remember to move away from `new URL()` as IE11 does not support this.

## PlansGrid Plugin
- [ ] **Handle paid plan already purchased** by showing a disabled _Purchase_ button for the selected plan and (TBD) disable other accordion items. https://cloudup.com/c5_e4GDPxM2
- [x] **Re-add single column** plans grid #44201 (first try in #44299)
- [x] **Fix missing Detailed comparison table** on _Choose a plan_ step. #44693
- [x] **Disable Free plan item when paid domain is selected** <s>https://github.com/Automattic/wp-calypso/issues/44448</s> pcbO8q-5j-p2#comment-82 #44748
- [x] **Turn PlansGrid plugin into smart container** (@yansern) https://github.com/Automattic/wp-calypso/pull/43859
  Currently the logic is in a plans grid button, the UI is in the plans grid modal component. Perhaps the logic & UI should be in a smart container. This is so it can be reused as a modal or popup or whatever the parent component is.
- [x] **Bug: Plans grid pricing is not showing.** (@alshakero) https://github.com/Automattic/wp-calypso/pull/43760
- [x] **If paid domain is chosen, switch plans to paid if they are previously on a free one.** (@razvanpapadopol) #43983

## Cart Integration
- [ ] **Load existing products (plan and domain) from cart and mark them as preselected during launch flow**
- [ ] **Composite checkout styled for Gutenboarding flow** #44447
- [x] **Discuss: How does cart integration looks like?** (@razvanpapadopol) #43983
  What happens after domanis & plans are selected?
  - [i16]: when a plan is selected, flow advances to next step (_Launch your site_) where a _Launch_ button would trigger launch and redirect to `/checkout`.
  - [i17][TBD]: when plan is selected, site is launched and then user is redirected to `/checkout`. https://github.com/Automattic/wp-calypso/issues/44450

## Styling Standardization
- [x] **Standardization of title, subtitle & action buttons.** (@yansern) #44077 #44087
  @razvanpapadopol suggested the addition of `title`, `subtitle` and `actions` params on `LaunchStep` component. See https://github.com/Automattic/wp-calypso/pull/43825#discussion_r448748743. Also, investigate if a reusable `Title`, `SubTitle` & `ActionButtons` (as seen in Gutenboarding) is needed.
- [x] **Margin & padding for mobile and tablet breakpoints.** (@yansern) #44087
  Gutenboarding has a `@mixin onboarding-block-margin` to deal with these things. Probably can be part of a bigger mobile view styling work once design is finalized.

## Accessibility
- [ ] Make sure keyboard navigation and focus styles are implemented. #44697

## KIV
- [X] **Design: User needs to be aware that when they choose a free plan, they lose chosen paid domain.** Fixed by setting the free plan as disabled.
- [ ] **Idea: Ability to change the sequence depending on user actions.**
  The `Launch` component can be a lot more reusable if the sequence is a param that be changed on the fly. See https://github.com/Automattic/wp-calypso/pull/43825#discussion_r448740346.

## Testing
Once the complete flow is functional and styled according to designs, we should make sure we go through these steps:
- [ ] **Cross browser testing** (including mobile iOS and Android).
- [ ] **Analytics events debugging**. Check if all the launch related events from current flow are being sent. Check if Gutenboarding events (for site title, domains and plans) are also being sent with some launch context.
- [ ] **[WIP] Make the new flow testable** in horizon and ask for design and general review of the flow. #44768 
- [ ] **Add e2e tests** to cover this new flow.

## Getting Started

* Set  `define( 'A8C_FSE_DOMAIN_PICKER_ENABLE', true );` and `define( 'A8C_FSE_PLANS_GRID_ENABLE', true );` in `.config/sandbox.php` on your sandbox.
* Run `yarn dev --sync` on `apps\full-site-editing` on local calypso folder.
* Go to `/wp-admin/post-new.php?post_type=page` on your sandbox site.

**Comment by joanrho** [comment]
Final design direction for v1: pcbO8q-4l
