### ISSUE TITLE
GuidesTours: Step-by-step tours

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#4377]
_I want the tour to guide me through the interface, step-by-step._

Here we'll do the flow framework and positioning, leaving proper styling until a later issue.

**TODO:**
- [x] A step can have a button to proceed to the next step. 
- [x] A tour step can prompt the user to click a certain UI element (most probably some button) to proceed with the tour and change the UI at the same time.
- [x] A bullseye can be shown on the target element, per the configuration of that step. It indicates that the target element must be clicked in order to proceed with tour. These steps do not have a Next button. Needs Gridicon or use PulsatingDot
- [x] ~~The user can exit the tour at any step (button/link/off-target)~~ (button + link work, unsure whether off-target really necessary, so not part of this iteration)
- [x] Steps and flow are specified in config file
- [x] A step can be positioned by the relevant action that is to be taken

**Comment by lsinger** [comment]
@MichaelArestad is working on some CSS for the dot.

**Comment by lsinger** [comment]
@ehg good to close?

**Comment by ehg** [comment]
> @ehg good to close?

It'll close automatically when we've reviewed and merged #4376 :)
