### ISSUE TITLE
GuidesTours: Tour opens on signup and also new site

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#4378]
_I want an optional guided tour, so I don’t get lost amidst the interface._ As its first step, the tour introduces itself. Hey, I’m a tour, I explain stuff so you can rock and roll. It also acknowledges that this is hard.

Here we want to make sure we have the correct logic for showing the tour at the right time. ~~The implementation will just provide hooks and `debug` messages for now, which the tours code can use later.~~

TODO:
- [x] Show on signup, never again ( qarg implemented in #4391 ) #4498
- [x] Show on ‘Add new WordPress’ #4498
- [x] After checkout, make sure we’re in GT #4498
