### ISSUE TITLE
GuidesTours: Step formatting

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#4379]
_I want the step to give me sufficient information, so that I may complete the action for myself._

Here we want to implement the various card style types, and also put some real step details in.

**TODO:**
- [x] Action step (text, `<hr>`, bullseye-W-click-to-continue)
- [x] Basic step (“do this later” anchor, “continue” button)
- [x] Variant basic step (“do this later” button, “no thanks” button)
- [x] Links step (like Action, but different Gridicon and accept an external link)
- [x] Finish Tour step (text, one primary button, external link)
- [x] Some of a step’s description text can be highlighted / bold. 
- [x] i18n
- [x] cleanup

**UI blueprints:**
![screen shot 2016-03-29 at 13 27 39](https://cloud.githubusercontent.com/assets/215074/14107828/2aaba11c-f5b2-11e5-8a2c-2f13181182b0.png)
![screen shot 2016-03-29 at 13 27 48](https://cloud.githubusercontent.com/assets/215074/14107836/315badcc-f5b2-11e5-8686-06262b7c339a.png)
![screen shot 2016-03-29 at 13 27 56](https://cloud.githubusercontent.com/assets/215074/14107854/3ac621c6-f5b2-11e5-8f70-4e671f52ab3d.png)
![screen shot 2016-03-29 at 13 28 04](https://cloud.githubusercontent.com/assets/215074/14107861/3dc48778-f5b2-11e5-941a-b994c6f2cb51.png)
![screen shot 2016-03-29 at 13 28 23](https://cloud.githubusercontent.com/assets/215074/14107866/414ce93a-f5b2-11e5-813c-cfe1f37a6f82.png)

**Comment by lsinger** [comment]
note: primary button on the left (not as in the screenshots above)

**Comment by lsinger** [comment]
finish tour step: 
![pasted_image_at_2016_04_04_04_11_pm](https://cloud.githubusercontent.com/assets/23619/14262000/94f4df1a-fab3-11e5-92b3-ce35efaa5659.png)
