### ISSUE TITLE
GuidesTours: Preview frontend

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#4380]
_I want to see my site, so that I get immediate feedback on what I’ve just chosen._

**TODO:**
- [ ] Use WebPreview, modified to ‘fake’ frontend
- [ ] Show on tour start
- [ ] Redirect/hide preview after first step? Maybe redirect to blogs/pages view

**UI:**
![screen shot 2016-03-29 at 13 38 09](https://cloud.githubusercontent.com/assets/215074/14108089/9117cd1c-f5b3-11e5-84eb-5a7a81b4957b.png)

**Comment by lsinger** [comment]
I think this was one of the wilder ideas we had when starting out building GuidedTours. 

It still sounds neat, but I think when looking at the effort / impact ratio we'll need to prioritize other tasks. 

Closing for now.
