### ISSUE TITLE
composite-checkout: Ebanx integration

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/wp-calypso#43812]
## Approach

- Leave current new checkout domain/g-suite/tax contact information step as-is.
- Consolidate Stripe/Ebanx into a single "credit card" payment method.
- Inside payment method, add (below Name field) a checkbox for "same as contact info above", pre-checked.
- If unchecked, unfurl additional billing information fields (starting with country).
- Credit card fields (which may be Stripe and may be custom, depending on country) will remain at the bottom of the payment method after the checkbox and optional additional billing information fields.

## Tasks

- [x] Figure out what happens if domain details and contact details are different in old Checkout (specifically in regards to the transactions endpoint).
- [x] Create new "all credit cards" payment method (this will eventually replace the existing `stripe-credit-card-fields.js` payment method). Started in https://github.com/Automattic/wp-calypso/pull/43841
- [x] Create state for the form fields in `CountrySpecificPaymentFields` as well as the credit card fields from `CreditCardFormFields` (which we'll need only for non-Stripe countries) inside payment method. Started in #43841
- [x] Create payment processor functions for Ebanx.
- [x] Figure out validation for new form fields.

**Comment by sirbrillig** [comment]
All that remains for this is to enable Brazil countries through `CheckoutSystemDecider`.

**Comment by michaeldcain** [comment]
> All that remains for this is to enable Brazil countries through CheckoutSystemDecider.

I think we should do the bank redirect method (also Ebanx) before opening it up to Brazil, to match legacy checkout. Since this card had more to do with the credit card processing, we can probably close it now.
