### ISSUE TITLE
Plugin Update to Gutenberg v8.5.1

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#44079]
We've installed the Gutenberg [`v8.5.1`](https://github.com/WordPress/gutenberg/releases/tag/v8.5.1) to edge sites for early feedback. The feedback and related bugs will be tracked here.

Call for Testing: p7DVsv-8X4-p2
Previous update: https://github.com/Automattic/wp-calypso/issues/43178

### Process

* [x] Install `v8.5.1` (r210245-wpcom)
* [x] Activate `v8.5.1` for edge-stickered sites (r210247-wpcom)
* [x] Publish a Call for Testing post (p7DVsv-8X4-p2)
* ~Draft public announcement and submit to Editorial for review~
* [x] Close the Call for Testing post (p7DVsv-8X4-p2#comment-30088)
* [x] Activate `v8.5.1` for all sites (D46856-code)
* [x] Request update for Atomic sites (p9o2xV-Yd-p2)
* ~Publish announcement posts~
   - [x] Internal (p7DVsv-91q-p2)
   - ~Public~
* ~Clean up unused releases (keep `v8.3.0` as last release)~

### Testing

* [x] Calypso E2E tests (https://github.com/Automattic/wp-calypso/pull/44416)
* [x] Teamcity tests
* [x] Fixes #43408? (via https://github.com/Automattic/wp-calypso/issues/43525#issuecomment-651544110)

### Blockers 🐛

* [x] Disable block library (https://github.com/Automattic/wp-calypso/issues/43677)
* [x] Image editing broken for .com (https://github.com/Automattic/wp-calypso/issues/43676)
* [x] Navigation block broken for .com (https://github.com/Automattic/wp-calypso/issues/43736)
* [x] Missing Block Inserter in .com FSE (https://github.com/Automattic/wp-calypso/issues/43784)

### Follow-up issues

- TBA :)

**Comment by davemart-in** [comment]
@fullofcaffeine mind sharing a status update on this? We're trying to map out timing for the deprecation of the Calypso editor and it would be handy to know if you have an estimate for when v8.5.1 might ship. If you don't that is fine as well. Mostly I've just looking for an update if you have one. Thanks!

**Comment by WunderBart** [comment]
@davemart-in we're going to deploy the 8.5.1 today 🤞

**Comment by davemart-in** [comment]
> we're going to deploy the 8.5.1 today 🤞

cc @creativecoder

**Comment by WunderBart** [comment]
This release was reverted back to v8.3.0 due to errors in production. For more information please see pc9Uba-2y-p2.
