### ISSUE TITLE
Gutenberg: Audit experimental feature usage.

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#44251]
There are many experimental features in use right now. Audit them. [See docs about these APIs](https://github.com/WordPress/gutenberg/blob/1d0eecb53fc3b91b1ad7bd51a368e088243fa8eb/docs/contributors/coding-guidelines.md#experimental-and-unstable-apis).

This is a master tracking issue for the following:
- [ ] Editing Toolkit: https://github.com/Automattic/wp-calypso/issues/46489
- [ ] WPCOM Block Editor: https://github.com/Automattic/wp-calypso/issues/46494
- [ ] WordPress Components Gallery: https://github.com/Automattic/wp-calypso/issues/46496

**Milestone**: https://github.com/Automattic/wp-calypso/milestone/324
**Gutenberg Experimental API Audit**: https://github.com/WordPress/gutenberg/issues/25786

**Comment by sirreal** [comment]
Do we need to watch `__unstable` as well?

**Comment by ockham** [comment]
Related upstream tracking issue: https://github.com/WordPress/gutenberg/issues/25786

**Comment by fullofcaffeine** [comment]
Make sure they don't break when the experimental feature goes away (undefined errors, etc), ping the right people about that, see if issues need to be created. Perhaps the best way would be to start with a P2 post.

**Comment by WunderBart** [comment]
> Do we need to watch __unstable as well?

Found just one occurrence [here](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/global-styles/src/dom-updater.js#L33). Added to the [Editing Toolkit tracking issue](https://github.com/Automattic/wp-calypso/issues/46489).

**Comment by sirreal** [comment]
@WunderBart Can you compare our feature usage with https://github.com/WordPress/gutenberg/issues/25786? That should help give us an idea of what things are priorities.

**Comment by WunderBart** [comment]
> @WunderBart Can you compare our feature usage with [WordPress/gutenberg#25786](https://github.com/WordPress/gutenberg/issues/25786)? That should help give us an idea of what things are priorities.

At this point we know that the following will not be considered as stable in 5.6:

### Block Editor
- `__experimentalLinkControl`

### Selectors
- `__experimentalGetAllowedBlocks`

### Components
- `__experimentalBoxControl`
- `__experimentalInputControl`
- `__experimentalNumberControl`
- `__experimentalUnitControl`

### Props

#### Block Preview
- `__experimentalPadding`

### Block Navigation
- `__experimentalBlockNavigationBlockFill`
- `__experimentalBlockNavigationEditor`
   ⚠️ This one's proposed to be removed in https://github.com/WordPress/gutenberg/pull/25069. Fortunately, we don't seem to be using it anywhere here.
- `__experimentalBlockNavigationTree`
- `__experimentalTreeGrid`
- `__experimentalTreeGridCell`
- `__experimentalTreeGridItem`
- `__experimentalTreeGridRow`

### Block API
- `__experimentalGetAccessibleBlockLabel`
- `__experimentalGetBlockLabel`

**Comment by sirreal** [comment]
Closing this as of https://github.com/Automattic/wp-calypso/pull/47712 / p4TIVU-9xW-p2
