### ISSUE TITLE
Gutenboarding: Feature picker - Main list

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#44428]
## Design
Latest design iteration: 
- Feature picker: pcbO8q-2S-p2
- Plans grid: pcbO8q-bb-p2

## To do
- [ ] <s>Re-introduce [single column plans grid](https://github.com/Automattic/wp-calypso/pull/44299) reverted in #44582</s> Update Plans Grid to display recommended plans and selected features [Design in progress pcbO8q-bb-p2] #45227 
- [ ] [WIP] Save selected features in site options when creating a site in Gutenboarding and use the data to recommend correct plan during Complete Setup flow [@razvanpapadopol]
- [ ] Enable feature flag in production, add `?latest` query param to `/new` [redirect in signup controller for  newSiteGutenbergOnboarding test](https://github.com/Automattic/wp-calypso/blob/master/client/signup/controller.js#L132) and update A/B test slug. #45232

## Development

- [x] Add UI feature picker component. #44382 
- [x] Add single column, accordion styled plans grid. #44299
- [x] Display Feature picker as a step in site creation flow (hidden behind feature flag). #44382
- [x] Store selected features in the Onboard store and persist the data between sessions. #44431
- [x] Update Plans step with recommended plan based on selected features. When multiple feature are selected, pick the highest plan as `recommendedPlan`. #44431

## Follow-ups & bug fixing
- [x] Update copy. https://github.com/Automattic/wp-calypso/pull/44382#issuecomment-663461840 #44431
- [x] Fix visual bug when tabbing. https://github.com/Automattic/wp-calypso/pull/44382#pullrequestreview-454232301

**Comment by razvanpapadopol** [comment]
All issues (open and completed) are now part of https://github.com/Automattic/wp-calypso/milestone/319
