### ISSUE TITLE
Gutenboarding: roll back some changes to v2

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#44454]
Together with the [new launch in editor](https://github.com/Automattic/wp-calypso/issues/43750), we're looking to bring back some of the most important features of Gutenboarding v2 abtest while keeping the current styling.

**Context**: pbAok1-1jD-p2

### Main tasks:
- [x] **Remove domain step** and allow accessing Domains just from top bar. #44655
- [x] **Display domain suggestion in top bar** (instead of a static _Choose domain_ label) if the site title or vertical is entered. https://github.com/Automattic/wp-calypso/pull/44655#issuecomment-669988891
- [x] **Display domain suggestion on plans page** pbAok1-1jD-p2#comment-2700
- [x] **Re-introduce the vertical input** #44701 
  * as an A/B test (50/50) within Gutenboarding following [this example](https://github.com/Automattic/wp-calypso/pull/44256). 
  * Use the vertical label (or free form input) to suggest a domain, even if the site title was skipped.
  * On mobile, vertical step should be a separate screen from site title, exactly like in v2.
- [x] **Prepare the changes on a feature branch.** https://github.com/Automattic/wp-calypso/pull/44820
- [ ] **Stop requiring a plan selection**. #44775 
_Free_ plan / _Premium_ plan should be preselected based on paid domain / premium design selection. Reference (ignore styling): https://cloudup.com/ctNg5MnimBM)

### Follow up tasks:
- [x] **Fix domain domain nudge behaviour** https://github.com/Automattic/wp-calypso/pull/44655#issuecomment-671375706 (@razvanpapadopol) Fixed in #44864
- [ ] **Vertical input remaining fixes**
  * https://github.com/Automattic/wp-calypso/pull/44701#issuecomment-670557434
  * https://github.com/Automattic/wp-calypso/pull/44701#issuecomment-671467951
  * https://github.com/Automattic/wp-calypso/pull/44701#issuecomment-671477203

**Comment by razvanpapadopol** [comment]
Closing this now as this test ended. We probably need to re-test the vertical input if we decide to re-introduce it later.
