### ISSUE TITLE
[Gutenberg WPCOM e2e tests i0] Automate steps 1 to 7 (Tracking Issue)

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#45209]
**Project:** pc9Uba-4N-p2
**Task:** Automate steps 1 to 7 from the Good Mountain Testing Checklist.

### Status

After the first exploration/PoC phase, I came up with a [PR](https://github.com/Automattic/wp-calypso/pull/45048) that gets close to automating steps 1 to 7 while testing across the most popular themes and non-edge/edge sites, but there are a few aspects missing, which leads us to our TODO list, below.

### TODO

- [X] Initial groundwork / exploration [task](https://github.com/Automattic/wp-calypso/pull/45048)
- [x] Fill all the popular blocks with the necessary minimum data for them to appear in the frontend and make sure each of them is displayed (here's an [example](https://href.li/?https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js#L69) of how the CoBlocks e2e tests do it) (@fullofcaffeine)
- [ ] ~DRY the frontend selector definition for each block class by deriving them at runtime, see: https://github.com/Automattic/wp-calypso/pull/45794/files#r495125663~ Moved to a task, [here](https://github.com/orgs/Automattic/projects/185#card-46874188), since it's not really required for this issue to be closed (it's an improvement).
- [ ] ~For more elaborate/interactive blocks, mimick a user using it the frontend. It might be as simple as clicking, say, the tile-gallery, and navigating through the images while making sure nothing broke. For each block, check if the codebase where it's developed already has a testing infrastructure/tests for it, and if so, make sure we can change the GB version to the one we want, and add the test there (the tests might already exist, just make sure it runs with a specific version of GB). Skip coblocks for now.~ This will be part of the next iteration and we will make sure that these tests are upstream, whenever possible.

**Comment by sirreal** [comment]
Current round of PRs:

- [ ] #45795
- [ ] #45796
- [ ] #45797
- [ ] #45798
- [ ] #45799

**Comment by fullofcaffeine** [comment]
Let's look into visual diffing instead of just taking screenshots.
