### ISSUE TITLE
Styles: Remove Calypso's global styles and resets

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/wp-calypso#45259]
This is an issue to track all the work we find we need to do to remove Calypso's global styles and resets. We want to do this to be able to use `@wordpress/components` inside of Calypso (including all of Gutenberg) without our resets conflicting with them.

- [x] Global `input[type="radio"]` styles - @saramarcondes https://github.com/Automattic/wp-calypso/pull/45198
- [x] Global `input[type="text"]` styles - @tyxla
  * [x] Removing unnecessary type="text" instances - @tyxla #45731
  * [x] Replace `<input type="text" />` instances to use the `FormInputText` component - @tyxla #45746
  * [x] Remove `type='text'` global styles and move them to components. - @tyxla #45781
- [x] Global `input[type="search"]` styles - @tyxla #45358
- [x] Global `input[type="email"]` styles - @tyxla #45940 
- [x] Global `input[type="number"]` styles @tyxla #45459
- [x] Global `input[type="password"]` styles - @tyxla #45431
- [x] Global `input[type="checkbox"]` styles - @tyxla #45324
- [x] Global `input[type="tel"]` styles - @tyxla #45400
- [x] Global `input[type="url"]` styles - @tyxla #45270
- [x] Global `select` styles - @tyxla #45491
- [x] Global `textarea` styles - @tyxla 
  * [x] Update `TextareaAutosize` to use `FormTextarea` - @tyxla #46087
  * [x] Update `TranslatableTextarea` to use `FormTextarea` - @tyxla #46092
  * [x] Update all comment content fields to use `FormTextarea` - @tyxla #46121
  * [x] Update all other `<textarea />` instances to use `FormTextarea` - @tyxla #46147
  * [x] Remove global `textarea` styles - @tyxla #46196
- [x] Global `label` styles - @tyxla 
  * [x] Update `FormToggle` to use `FormLabel` - @tyxla #46096
  * [x] Update `SelectDropdown` to use `FormLabel` - @tyxla #46122
  * [x] Update `<label />` to `FormLabel` in the post-editor section - @tyxla #46150
  * [x] Update `<label />` to `FormLabel` in WooCommerce - @tyxla #46154
  * [x] Update `CreditCardFormFields` to use `FormLabel` - @tyxla #46274
  * [x] Update `PostSelector` to use `FormLabel` - @tyxla #46310
  * [x] Update `LoginForm` to use `FormLabel` - @tyxla #46350
  * [x] Update component examples to no longer use raw `<label />` - @tyxla #46352
  * [x] Use `FormLabel` in Community Translator - @tyxla #46353
  * [x] Update SubscriptionLengthOption to use FormLabel - @tyxla #46354
  * [x] Use `FormLabel` in `TermTreeSelectorList` - @tyxla #46355
  * [x] Use `FormLabel` in `BillingReceipt` - @tyxla #46356
  * [x] Use `FormLabel` instead of `label` in the Simple Payments dialog - @tyxla #46395
  * [x] Use `FormLabel` instead of `label` in Magic Login - @tyxla #46396
  * [x] Use `FormLabel` in `Security2faProgressItem` - @tyxla #46397
  * [x] Use `FormLabel` in `SharingConnection` - @tyxla #46449
  * [x] Use `FormLabel` in `AccountDialogAccount` - @tyxla #46452
  * [x] Remove global `label` styles - @tyxla #46479
- [x] Global `fieldset` styles - @tyxla #45577
- [x] Global `form` styles - @tyxla #45696
- [ ] Remove remaining global input/textarea resets
- [x] Sidebar items (comment out `_reset.scss` then fix the sidebar) - @jsnajdr #45379
- [ ] Global button styles - @saramarcondes
    * https://github.com/Automattic/wp-calypso/pull/45341
- [ ] ESLint rule to warn against using raw `button` instead of `Button`
- [ ] ESLint rule to warn against using raw `label` instead of `FormLabel`
- [ ] ESLint rule to warn against using raw `type="radio"` instead of `FormRadio`
- [ ] ESLint rule to warn against using raw `type="checkbox"` instead of `FormInputCheckbox`

**Comment by simison** [comment]
@saramarcondes @tyxla  I remember reading there are no longer global styles in Calypso, is that true? Looks pretty complete here. :-)

Just thinking this in context of upgrading `@wordpress/components` package and having undetected CSS leakage if there would be any globals left. (pbAok1-1Oc-p2)

**Comment by sarayourfriend** [comment]
There are still global styles in Calypso, there are just not any (major) ones that conflict with `@wordpress/components` (as far as we can tell based on the [`/devdocs/wordpress-components-gallery`](https://wpcalypso.wordpress.com/devdocs/wordpress-components-gallery)).

What exactly did you have in mind as far as undetected CSS leakage?

**Comment by tyxla** [comment]
I second Sara - we removed most of the form global styles, but there are still some [global resets](https://github.com/Automattic/wp-calypso/blob/766d2a86796b83312d83c0f369ef54792890497f/client/assets/stylesheets/shared/_reset.scss#L135) and those seem to affect WP components - for example at [`/devdocs/wordpress-components-gallery`](https://wpcalypso.wordpress.com/devdocs/wordpress-components-gallery)) see the radio buttons - they look a bit broken. Those don't necessarily exist in the list above and still need to be recognized, diagnosed and fixed.

**Comment by simison** [comment]
>  there are just not any (major) ones that conflict with @wordpress/components

Yup, no worries. I was just thinking that as we update `@wordpress/components` package, that could change suddenly without noticing but maybe that's easy enough to catch with the devdocs gallery.

Thanks both!

**Comment by tyxla** [comment]
Still unresolved, but valid and useful.

**Comment by tyxla** [comment]
I think this is still valuable.
