### ISSUE TITLE
Create data layer integration for `/admin-menu` endpoint

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#45464]
Sub Issue of https://github.com/Automattic/wp-calypso/issues/45435.

This documents the need to (experiment with) creating a data-layer and state implementation for the `admin-menu` endpoint proposed in D49005-code.

## Tasks

- [x] Create new `admin-menu` directory in `client/state/data-layer/wpcom`.
- [x] Define Redux action namespace (eg: `ADMIN_MENU_`).
- [x] Register handler module for `all` menu items (`registerHandlers`).
- [ ] Wire up basic WPCom HTTP request using `dispatchRequest` and logging from the various response actions creators.
- [ ] Write data transformer to transform the API response into consumble data.

Following this, the next step will be to create a state tree for admin menus with actions, reducers and selectors to make the data available to the UI.
