### ISSUE TITLE
Create Redux state tree for admin menu

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#45465]
This is a Sub Issue of https://github.com/Automattic/wp-calypso/issues/45435.

This documents the need to create a new state tree (or repurpose [the existing](https://github.com/Automattic/wp-calypso/tree/a86e8114505121e29df7fd57bff78b99244d4a1a/client/my-sites/sidebar)) to manage state for the sidebar admin-menu.

The expectation is to write simple actions/action creators and reducers. Selectors can be handled in another Issue.

This will interact and depend on the data layer implementation created in https://github.com/Automattic/wp-calypso/issues/45464. However, it could easily be developed against unit tests to avoid the data layer work becoming blocking. Indeed, note the data layer has the ability to transform API data into any format required by Calypso, so its perfectly acceptable that this Issue leads the way in determining the required "shape" of the data.

## Tasks

- [x] Determine whether to use existing `sidebar` state tree or create new one (eg: `admin-menu`).
- [x] Mirror Redux action "namespace" with that utilised in the data layer (eg: `ADMIN_MENU_` or similar).
- [x] Define all actions (not creators!) by creating constants for each - if this is too difficult at this stage then come back to this later. But ideally, we should use this as a chance to define which actions we expect to receive.
- [x] Define Reducer skeleton.
- [x] Define action _creator_ to handle receiving new admin menus (eg: `receiveMenuItems`).
- [x] Write reducer to handle the action dispatched by `receiveMenuItems` action creator and persisting into Redux state.

**Comment by getdave** [comment]
Note that ultimately the items stored in state will need to be keyed by siteID to ensure each site gets it's own personalised admin menu.
