### ISSUE TITLE
GuidesTours: Rename to GuidedTours, move directory

### ISSUE THREAD

**Issue by ehg** [Automattic/wp-calypso#4575]
TODO:
- [x] Rename directory to `guided-tours` #4934
- [x] Rename all references to GuidesTours to GuidedTours in code #4984
- [x] Rename GitHub labels, milestones
- [x] Edit Zapier integration
- [x] Move to `client/layout` #4934
- [x] Move state into own directory #4966
