### ISSUE TITLE
Gutenberg: 9.2 Plugin Upgrade

### ISSUE THREAD

**Issue by sirreal** [Automattic/wp-calypso#46314]
Call for Testing: p7DVsv-9Er-p2
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/45772

### Process

- [x] Install and activate on edge sites (r215489-wpcom, r215493-wpcom)
- Testing:
  - [x] Calypso e2e: https://github.com/Automattic/wp-calypso/pull/46601
  - [x] TC ~D51384-code~ D51667-code
- [x] Publish a Call for Testing post (p7DVsv-9Er-p2)
- [x] Should there be a public announcement? Add release highlights here: 26e1b-pb/#plain
- [x] Update to stable release r215573-wpcom
- [x] Activate upgrade for all sites ~D51384-code~ D51667-code
- [x] Request update for Atomic sites p9o2xV-17h-p2
- [x] Publish internal announcements
- [ ] Clean up unused releases
   - [ ] 9.0.0
   - [ ] 9.2.0
   - [ ] 9.2.1
- [ ] Open a new issue for the next upgrade, transfer remaining tasks, close this issue.
- [x] Update the Log of Update Attempts section in the FG and list patches applied 

### Tasks

- [x] wpcomsh cleanup (500-gh-wpcomsh)

**Comment by fullofcaffeine** [comment]
This is complete, next one: https://github.com/Automattic/wp-calypso/issues/46985.
