### ISSUE TITLE
Google Analytics: change "Tracking ID" to "Measurement ID"

### ISSUE THREAD

**Issue by simison** [Automattic/wp-calypso#46764]
Let's update the label for Google Analytics ID?

Via p58i-9Dr-p2#comment-47915

**Todo:**
- [x] Update label https://github.com/Automattic/wp-calypso/pull/47617
- [x] ~Wait for translations~ Not needed. Existing translations will be reused in the meantime https://github.com/Automattic/wp-calypso/pull/47617#discussion_r527580642
- [x] Update docs:
  - [x] https://jetpack.com/support/google-analytics/
  - [x] https://wordpress.com/support/google-analytics/

**Our UI — "Tracking ID":**

![image](https://user-images.githubusercontent.com/87168/97147159-bb891a80-1771-11eb-9b4b-cd8453bb8003.png)

**Google Analytics UI — "Measurement ID":**

![image](https://user-images.githubusercontent.com/87168/97147182-c479ec00-1771-11eb-8231-d4d5c260abf8.png)

**Comment by tyxla** [comment]
Happy to tinker with this quickly, but just in case, I'd like to cc @Automattic/dotcom-manage-design - are there any other changes you'd like to see here to make sure everything remains to be intuitive and makes sense?

**Comment by sixhours** [comment]
It definitely makes sense to update the label to reflect the new wording on Google's end.

I also agree this section would benefit from an audit; there are so many links and a lot of explanatory text. There are probably opportunities to simplify without losing context.

<img width="1071" alt="Screen Shot 2020-10-27 at 11 32 39 AM" src="https://user-images.githubusercontent.com/2124984/97324441-34f33c80-1848-11eb-8ee2-797820e416fd.png">

I'm adding this to the Dotcom Manage Design board so @lcollette can prioritize against our backlog.

**Comment by simison** [comment]
Related https://github.com/Automattic/wp-calypso/issues/36332

**Comment by simison** [comment]
@sixhours does the copy change make sense independently from an audit?

**Comment by sixhours** [comment]
> @sixhours does the copy change make sense independently from an audit?

Yep!

**Comment by davemart-in** [comment]
@sixhours once you're happy with the design exploration, if you'd like help implementing this, please feel free to add this back to the Manage backlog. Thanks!

**Comment by getdave** [comment]
@sixhours Note also that [Google's own docs which we reference in the UI](https://support.google.com/analytics/answer/1032385?hl=en) still don't reflect the terminology change.

Searching the Google docs I came across this which [explains the difference between Tracking ID and Measurement ID](https://support.google.com/analytics/answer/9539598?hl=en). Perhaps a useful link to include?

Probably one for a follow up Issues/PR though when we actually tackle the UX/Design of this section.

**Comment by getdave** [comment]
@sixhours Could you possibly review https://github.com/Automattic/wp-calypso/pull/47617. Thanks.

**Comment by getdave** [comment]
> Wait for translations

@simison If we ship this change English speakers will see the change but it will fallback to the existing translation for all other languages. Given that the existing translation is the existing experience on WordPress.com does it make sense just to push this out and let the EN customers have the benefit of correct terminology and then the translations will catch up?

At what point is it appropriate to update the docs?

**Comment by simison** [comment]
There is a special i18n function for that kind of fallback behaviour. Good idea!

Search for repo with "docs" and you can open an issue there.

**Comment by simison** [comment]
This is sorted, just issue had been left open:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/87168/166894696-ef443167-8b24-4475-a625-c0feaad04e17.png">
