### ISSUE TITLE
Focused Launch: Plan step

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46865]
If the site doesn't have a pre-paid plan associated:
  - [x] Show the plan step in the "active" group — PR #47270
  - [x] Step title is "Confirm your plan"
  - [x] Side commentary:
    - [x] On desktop, reads  "Monetize your site with WordPress premium" and shows additional list items — PR #47281
    - [x] On mobile, starts with a bulb icon, reads "Grow your business with WordPress Business" and doesn't show any list items — PR #47281
  - [x] New "plan item" design — #47370 - PR #47370
  - [x] Show blue highlight for selected plan item — #47370 - PR #47370
  - [x] Show 2 plans (one is the free plan, the other is either the pre-selected, or the recommended/popular)
  - [x] Show a "View all plans" link which changes the view to the plans grid
  - [x] Pre-select the plan, by looking at the `@automattic/launch` data-store | https://github.com/Automattic/wp-calypso/issues/47233
  - [ ] If the `@automattic/launch` data-store doesn't contain a plan, fallback to items in the cart (if any) #47233
  - [ ] Ensure selected plan is always shown to the user (add it as the second item if not in the initial list) #47544

<img width="605" alt="Screenshot 2020-11-06 at 16 04 57" src="https://user-images.githubusercontent.com/1083581/98382049-f67d2f00-204a-11eb-83f6-6280eab4813c.png">

![Screenshot 2020-10-28 at 15 24 16](https://user-images.githubusercontent.com/1083581/97449129-a65aea00-1931-11eb-8b8f-1beb6a904ece.png)

<img width="397" alt="Screenshot 2020-11-10 at 15 48 23" src="https://user-images.githubusercontent.com/1083581/98692672-ab775a80-236f-11eb-89ba-40a287c12c75.png">

If the site already has a pre-purchased plan associated:
  - [x] show the plan in the "disabled" group — PR #47270
  - [x] Step title is 'Your plan' — PR #47281
  - [x] Show an info icon with a popover next to the title that reads "Changes to your purchased plan can be managed from your Plans page." — PR #47281
  - [x] Side commentary reads  "More than 38% of the internet uses WordPress" — PR #47281
  - [x] Show only the purchased  plan, which can't be selected by the user

<img width="806" alt="Screenshot 2020-11-06 at 16 04 19" src="https://user-images.githubusercontent.com/1083581/98382097-07c63b80-204b-11eb-909b-e90f40ecfc57.png">

<img width="303" alt="Screenshot 2020-11-10 at 15 48 35" src="https://user-images.githubusercontent.com/1083581/98692762-c518a200-236f-11eb-9ba0-c5d51e962f9d.png">

**Comment by ciampo** [comment]
Closing as the missing points are tracked in #47233 and  #47544
