### ISSUE TITLE
Focused Launch: Domain step

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46862]
If the site doesn't have a paid domain associated:
  - [x] Show the domain picker in the "active" group
  - [x] Step title is "Confirm your domain"
  - [x] Side commentary:
    - [x] On desktop, reads  "46.9% of globally registered domains are .com" and shows additional list items — PR #47281
    - [x] On mobile, starts with a bulb icon, reads "46.9% of registered domains are .com" and doesn't show any list items — PR #47281
  - [x] Show 3 domains (one is the default .wordpress.com)
  - [x] Show a "View all domains" link which changes the view to the domains picker details
  - [x] New "domain item" design - PR #47152  
  - [x] Show blue highlight for selected domain item - PR #47152 
  - [x] Pre-select the domain, by looking at the `@automattic/launch` data-store - PR #47191
  - [ ] If the `@automattic/launch` data-store doesn't contain a domain, fallback to items in the cart (if any) | #47233 
  - [ ] Ensure selected domain is always shown to the user (append it as the last paid domain if not in the initial list) #47540

<img width="595" alt="Screenshot 2020-11-06 at 16 04 29" src="https://user-images.githubusercontent.com/1083581/98381479-3c85c300-204a-11eb-857a-2060246ee01e.png">

![Screenshot 2020-10-28 at 15 13 42](https://user-images.githubusercontent.com/1083581/97447866-4d3e8680-1930-11eb-91f3-f8a5fb92b975.png)

<img width="305" alt="Screenshot 2020-11-10 at 15 48 39" src="https://user-images.githubusercontent.com/1083581/98689462-40785480-236c-11eb-8357-40228188b5e4.png">

If the site already has a pre-purchased domain associated:
  - [x] show the domain in the "disabled" group
  - [x] Step title is 'Your domain'
  - [x] Show an info icon with a popover next to the title that reads "Changes to your purchased domain can be managed from your Domains page."
  - [x] Show only the purchased domain, which can't be selected by the user
  - [x] Side commentary:
    - [x] On desktop, reads  "Unique domains help build brand recognition and trust" — PR #47281
    - [x] On mobile, starts with a bulb icon, and reads "Unique domains help build brand trust" — PR #47281

<img width="821" alt="Screenshot 2020-11-06 at 16 04 15" src="https://user-images.githubusercontent.com/1083581/98381546-51625680-204a-11eb-8269-a7d916121aa9.png">

<img width="404" alt="Screenshot 2020-11-10 at 15 48 09" src="https://user-images.githubusercontent.com/1083581/98689942-b5e42500-236c-11eb-8109-a90dd7c53adf.png">

**Comment by ciampo** [comment]
Closing as missing points are tracked in #47233 and #47540
