### ISSUE TITLE
CoBlocks: Create a fork and eliminate features and blocks we don't need

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#46935]
**Project:** pc9Uba-aT-p2

We have experimented with using the WP API to unregister all hooks and blocks that we don't need, but looks like it will be unpractical. See 548-gh-Automattic/wpcomsh#discussion_r514505973. The previous issue is here: https://github.com/Automattic/wp-calypso/issues/46782.

The goal of this task is to experiment with creating a custom fork of Coblocks and to eliminate any features and blocks we don't need from it.

#### Pull Requests
* https://github.com/Automattic/coblocks/pull/1
* https://github.com/Automattic/coblocks/pull/2
* https://github.com/Automattic/coblocks/pull/3
* https://github.com/Automattic/coblocks/pull/4
* https://github.com/Automattic/coblocks/pull/5

#### TODO

- [x] Test on WPCOM. Should work as it should be equivalent to the build created by `coblocks-builder` @fullofcaffeine 

- [x] Test on AT. Will probably fail as there are WPCOM-specific mods that (probably?) won't work on AT. In that case, we'll use the IS_ATOMIC (?) constant to detect that we're on Atomic (or not) and to enable/disable portions of code that are specific to WPCOM/AT. We can do that now because we're using a fork (no need for filters on wpcomsh, like we do with GB).
- [ ] ~Fix errors on AT. Isolate WPCOM-specific code for now if needed, using `IS_WPCOM`~ (see https://github.com/Automattic/coblocks/pull/1#issuecomment-722579054)
- [ ] Test the plugin as a `mu-plugin` in WPCOM and AT. Test it on AT while another version of Coblocks is active, the full-blown Coblocks should take over (aka handle plugin collision in AT: pc9Uba-7N-p2#comment-205) **(IN PROGRESS)** @fullofcaffeine 
- [ ] Talk to the AT folks about how to install/automatically activate the plugin zip on AT. I'm assuming the plugin will come from GH releases. **(IN PROGRESS)** @fullofcaffeine 
- [ ] The `mu-plugins` loader for CoBlocks in WPCOM (`wpcom-coblocks-load.php`) has some filters that disable / modify some of the Coblocks features. That should probably be part of the fork now.
- [ ] For now, I've only deleted the files that were also deleted / no needed by the build generated by `coblocks-builder`. There might be more code / files we can remove / delete. Have a further look.
- [ ] Review the blocks we want to allow. Currently, they are the same as the ones available in a build generated by `coblocks-builder`, which are: "Click To Tweet", "Collage", "Dynamic HR", "Hero", "Logo", "Masonry", "Offset", "Pricing Table", "Stacked".

- [ ] Setup GH action to create a release upon pushing a tag (@ockham already implemented something similar for GB, use as reference)
- [ ] Play with the idea of generating a Phab diff out of a GH release so that the WPCOM counterpart can also be installed.
- [ ] Fix automated tests

#### Open Questions
1. How to handle translations, specially if it's a wrapper plugin (hence, might not be recognized by the translations pipeline?) across AT and WPCOM?
1. ~Where should this fork live officially after this PR is finally merged?~
1. Should we aim at 1:1 feature parity between WPCOM/AT? Or will the builds differ at runtime? (I assume that, apart from code that is specific/required by WPCOM, the features provided to WPCOM/AT should be the same)
1. ~Should we come up with a tool that will install it on WPCOM + publish to the plugin SVN repo (so that AT can install off it)?~
1. ~For the non-allowed blocks, should we just no register them or should we hide them from the inserter? Will unregistering them prevent them from working in posts that have their markup? Test this.~

**Comment by fullofcaffeine** [comment]
@ockham Already answered some of the open questions here: https://github.com/fullofcaffeine/coblocks/pull/1#issuecomment-720411048.

**Comment by fullofcaffeine** [comment]
Closed in favor of pc9Uba-aT-p2#comment-236.

See:
* https://href.li/?https://github.com/Automattic/wp-calypso/issues/47820
* https://href.li/?https://github.com/Automattic/wp-calypso/issues/47821
* https://href.li/?https://github.com/Automattic/wp-calypso/issues/47822
* https://href.li/?https://github.com/Automattic/wp-calypso/issues/47823
