### ISSUE TITLE
Focused Launch: create a testing plan

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#46943]
We should think about what tests we should add to the `@automattic/launch` package, both unit and e2e.
This issue can be closed as soon as we create tasks to cover all the items below. We'll decide the priority for each issue separately and also if it is going to be done before or after the release.

Summary tests:
- [ ] Summary view is the default view when opening the modal
- [ ] No items are selected on first visit with an empty cart
- [ ] On successive visits, the previously selected items are pre-selected if they were not already purchased in other flow
- [ ] Check that summary steps appear in the correct order, and that the active steps have the correct step index
- [ ] Step index in active steps should be shown only when there are at least 2 active steps
- [ ] Number of domains shown in the domain step (3 / 4 depending if a non default premium domain is selected / from cart) and order (first recommended, last is free)
- [ ] Number of plans shown in the plan step (2 / 3 depending if a non default premium plan is selected / from cart) (first is popular, last is free)
- [ ] Selected plan / domain are highlighted correctly in the summary view
- [ ] The "marketing quotes" text is shown/hidden correctly in mobile/desktop views
- [ ] Cost of plans shown in plans step follows the billing period of the last selected paid plan (default to annually)
- [ ] Loading items from cart on an empty launch store (cart items should be saved to launch store)
- [ ] Loading items from cart on a non-empty launch store (cart items should be ignored)
- [ ] Disabled domain and/or plan steps, in case the site already has an associated paid domain / plan (domain/plan names are shown correctly in the disabled steps)
- [ ] Launch button is disabled until all fields are selected
- [ ] Launch callback is called when launch button is clicked on a free plan
- [ ] Checkout callback is called when launch button is clicked with a paid plan selected
- [ ] Free plan is disabled if a premium domain is selected)
- [ ] Free plan is unselected if a premium domain is selected
- [ ] Click on "View all plans" changes current view to Plan details
- [ ] Click on "View all domains" changes current view to Domain details
- [ ] Site title step shows only if site title is still the default one, or if the site title step was ever shown to the user
- [ ] Summary view is keyboard interactive (e.g. tab through items, pressing space/enter to interact)
- [ ] Step highlighting logic (which steps are "dimmed" and which aren't #48759)

DomainDetails tests:
- [ ] Can set a domain
- [ ] Can unset a domain
- [ ] Can fire analytics event
- [ ] Can click "Go back" to go back to summary view
- [ ] Can perform domain search
- [ ] Can click "View more results" to reveal more domains
- [ ] When a domain is selected, back to summary
- [ ] Currently selected domain is highlighted
- [ ] ... more domain picker specific tests

Plan details:
- [ ] table variant is shown
- [ ] Can click "Go back" to go back to summary view
- [ ] Picking a plan selects the plan in the launch store and goes back to summary view
- [ ] Currently selected plan is highlighted
- [ ] ... more plans grid specific tests

Integration tests:
- [ ] Launch with pre-purchased plan
- [ ] Launch with pre-purchased domain using `domain-only` flow ( related from Calypso launch flow: https://github.com/Automattic/wp-calypso/issues/42857 ) 
- [ ] Launch with pre-purchased plan and domain

E2E tests [tracked in separate issues]
- [x] Paid flow for a site with Free plan (details in https://github.com/Automattic/wp-calypso/issues/46943#issuecomment-779895421)
- [x] Free flow for a site with Free plan
- [x] Free flow to display translations (similar to what https://github.com/Automattic/wp-calypso/pull/51000 added to Gutenboarding)

**Comment by tjcafferkey** [comment]
@ciampo It's probably worth splitting this issue out into multiple issues such as:

* Summary tests
* Domain details tests
* etc.

That way we can individually assign each member an issue to progress with and focus on, then closing that issue will be accurately reflected in the milestone progress

The concern with having all tests in one issue is that this list could continuously grow and at times feel overwhelming or unachievable as this will be sat in "In Progress" for quite some time.

**Comment by razvanpapadopol** [comment]
> It's probably worth splitting this issue out into multiple issues

👍 We can check off things from this 'main issue' once we track them in separate issues. And let's keep this one in Backlog since is not directly actionable.

**Comment by razvanpapadopol** [comment]
All the supported users flows are combinations of the items groupped in 3 columns below. 

Flow start | User possible selection | Checkout options
-- | -- | --
**plan**: Free Plan \| purchased paid plan \| paid plan in cart | plan and domain | abandon checkout
**domain**: sub-domain \| purchased custom domain \| custom domain in cart | domain | pay with cc or credits without redirect to external page
**site title**: custom \| default ("Site title") | plan (except Free plan if custom domain is selected) | pay with Paypal or other processor that require processing on external page
**location**: Calypso \| wp-admin | no selection (already purchased paid plan and custom domain) | N/A (if no paid plan or custom domain are selected)

**[Note]:** There are probably more checkout cases to investigate. See https://github.com/Automattic/wp-calypso/pull/48452#discussion_r575358791

**Comment by ciampo** [comment]
Manual (and potentially e2e) testing, derived from this [spreadsheet](https://docs.google.com/spreadsheets/d/1IxR78eKN-L0P-pJDz4VhmXdbNfCiXdkl5_1wM6L_27g/edit#gid=0):

## Setup

- All tests need to be run on an _unlaunched_ site created via `/start`
- Make sure to assign your WordPress.com user to the _treatment_ variant of the A/B test
- Once the above is done, in order to open the Focused Launch modal, visit the block editor and click on the "Launch" button in the top header nav

## Brief overview and naming conventions

- The Focused Launch modal has 4 views: `Summary` view (the default one), `Success` view (shown when the site has launched), `Domain details` view (where the complete domains picker is shown), and `Plan details` view (the complete plans grid is shown)
- The Summary view is composed of (up to) 3 steps: Site title step, Domain step, and Plan step. The presence and the order of these steps changes depending on different factors.

## Critical Flows

### 1. Paid flow for a site with Free plan

1. The user's site is still on a free plan with a free subdomain before launching
2. User opens Focused Launch modal
3. User picks free sub-domain and free plan in the Summary view
4. User picks a custom domain 
    - [ ] The free plan is automatically unselected and becomes disabled
5. User picks the free sub-domain again
    - [ ] The free plan option is enabled again
6. User picks a paid plan (not eCommerce) and clicks the "Launch" button
    - [ ] The checkout modal should open with the selected paid plan in the cart
7. User completes checkout
    - paying with credit cart or credits
        - [ ] As the checkout modal automatically closes on successful payment, the site gets launched and the Focused Launch's Success view is displayed
        - [ ] In this case, because a plan was purchased, if the user chooses to _Continue Editing_, the page will reload to make Premium Blocks corresponding to that plan available.
    - paying with Paypal
        - [ ] User is redirected to an external processing page and, on payment complete, is redirected back to the block editor, where the site is launched and the Focused Launch's Success view is displayed

### 2. Free flow for a site with Free plan

1. The user's site is still on a free plan with a free subdomain before launching
2. User opens Focused Launch modal
3. User changes the site title to a custom title
    - [ ] The custom domain suggested in the Summary view reflects the custom title that the user has just written
4. User picks a custom domain and the Premium plan in the Summary view
5. User clicks on the "View all plans" link
    - [ ] The Plan details view is shown and the Premium (annually billed) plan is shown as selected in this view too
6. User clicks on "Monthly" in the toggle, and selects the "Personal" (monthly billed) plan
    - [ ] When selecting the plan, the user is taken back to the Focused Launch Summary view, and the summary view shows that plan as selected
    - [ ] The plan step in the Summary View shows the Premium, Personal and Free plan, and the prices refer to the monthly billed versions
7. User clicks the "Launch" button
    - [ ] The checkout modal should open with the selected plan and custom domain items in the cart
8. User abandons checkout
    - [ ] Site is not launched yet
9. User visits the block editor again, and opens Focused Launch again
    - [ ] The site title, selected domain and selected plans have been persisted from the previous Focused Launch modal interaction (points 3 and 4)
10. User picks the free subdomain and the free plan, and clicks the "Launch" button
    - [ ] The site is launched and the Focused Launch's Success View is displayed

## Non-critical flows

### 3. Pre-paid plan & free custom domain flow
   
1. The user's site has an associated paid plan (but the domain is still the free subdomain) before launching
2. User opens Focused Launch modal
    - [ ] The Focused Launch Summary view shows the associated paid plan as a greyed-out, disabled card
3. User picks a custom domain from the Summary view
4. User clicks the "View all domains" link
    - [ ] The Domain details view is shown and the domain selected in step 3 is shown as selected in this view too
5. User picks a different custom domain from the Domain details view
    - [ ] When selecting the custom domain, the user is taken back to the Focused Launch Summary view, and that domain is shown as selected
6. User clicks the "Launch" button
    - [ ] The checkout modal should open with the custom domain in the cart and a cost of 0
7. User completes checkout (use credits)
    - [ ] The checkout modal is automatically closed after purchase and the site is being launched. Finally, Focused Launch's Success view is displayed.
    - [ ] If the user clicks on the "Continue Editing" button, the modal is dismissed and the block editor is revealed
    - [ ] If the user clicks on the "Back to home" link, the user gets redirected to the WordPress.com dashboard (home) for their site

### 4. Site with both paid plan and custom domain associated before Launch

1. The user's site has an associated paid plan and custom domain before launching
2. User opens Focused Launch modal
    - [ ] Both the domain and plan options are disabled in the Summary view, since they have already been purchased
3. User clicks on the "Launch" button
    - [ ] The site is launched and the Focused Launch's Success View is displayed

### 5. Plan and domain Items in cart

1. The user adds a paid plan and a custom domain to the cart (without completing the purchase) before launching
2. User opens Focused Launch modal
    - [ ] Both the domain and the plan from the cart appear as pre-selected in the Focused Launch Summary view
3. User selects a different custom domain and paid plan
4. User clicks on the "Launch" button
    - [ ] The checkout modal should open with the plan and domain items selected in point 3 in the cart, instead of the items that were previously added in point 1
5. User completes the Checkout
    - [ ] As the checkout modal automatically closes on a successful payment, the site gets launched and the Focused Launch's Success view is displayed

### 6. Paid eCommerce flow for a site with Free plan

1. The user's site is still on a free plan with a free subdomain before launching
2. User opens Focused Launch modal
3. User picks free sub-domain and eCommerce plan in the Summary view, and clicks the "Launch" button
    - [ ] The site is launched immediately. One way of verifying this, is to open a new tab to `wordpress.com/home/[SITE_ID].wordpress.com` and check if the site is launched.
    - [ ] The user is redirected to the standalone `/checkout` page
4. User completes checkout (pay with credits)
    - [ ] As the checkout completes, the user is redirected to Checkout "Thank you" page, that triggers atomic transfer, so that the store setup can begin

### 7. Paid plan flow for a site with Free plan in Wp Admin

1. The user's site is still on a free plan with a free subdomain before launching
2. User opens Focused Launch modal _in Wp Admin_
3. User picks free sub-domain, a paid plan (not eCommerce) and clicks the "Launch" button
    - [ ] The site is launched immediately. One way of verifying this, is to open a new tab to `wordpress.com/home/[SITE_ID].wordpress.com` and check if the site is launched.
    - [ ] After seen the Success view for a brief moment, the user is redirected to the standalone `/checkout` page
4. User completes checkout (pay with credits)
    - [ ] User is redirected to the Calypso site home (`wordpress.com/home/[SITE_ID].wordpress.com`) 

### 8. Launch a non-en site

1. The user's account settings are set to a language different than english _before_ creating the site
2. The user's site is still on a free plan with a free subdomain before launching, and never edited the site title before launching
3. User opens Focused Launch modal 
    - [ ] The "Name your site" step should be visible as the first step in Focused Launch Summary view (_note: currently this is not working as expected, and is tracked in #50269_)
4. User navigates through Summary view, Plan details view and Domain details view
    - [ ] Every bit of copy in the UI is translated correctly

**Comment by yansern** [comment]
For **6. Paid eCommerce flow for a site with Free plan**, there seems to be a discrepancy between the Calypso & WP-Admin version.

3. User picks free sub-domain and eCommerce plan in the Summary view, and clicks the "Launch" button
    - [X] The site is launched immediately. One way of verifying this, is to open a new tab to `wordpress.com/home/[SITE_ID].wordpress.com` and check if the site is launched.
    - [ ] ~~The user is redirected to the standalone `/checkout` page~~
             - For Calypso, the checkout modal is displayed.
             - For WP-Admin, it is redirected to `/checkout` page.
    - **Issue 1:** Before the checkout is displayed, the hooray confetti view flashes in very quickly before the checkout takes over, too quick for user to understand what's going on.
4. User completes checkout (pay with credits)
    - **Issue 2:** After completing checkout, the hooray confetti view also flashes in very quickly, too quick for user to understand what's going on.
    - [ ] ~~As the checkout completes, the user is redirected to Checkout "Thank you" page, that triggers atomic transfer, so that the store setup can begin~~
         - **Issue 3:** For Calypso, user is redirected back to the block editor, user did not get redirected to the store setup. Atomic transfer did happen though, because the subdomain becomes *.wpcomstaging.com. For WP-Admin, atomic transfer & store setup works as usual.
         
Calypso video:
https://drive.google.com/file/d/1f5pKjq63hSM0UQytLjf5Btfc2Xa8eUHk/view?usp=sharing

WP-Admin video:
https://drive.google.com/file/d/1RzfZv-JQf4Wr25e7VMAnHIF29s7FXYqr/view?usp=sharing

**Comment by razvanpapadopol** [comment]
> - For Calypso, the checkout modal is displayed.

Yes, we display the modal in Calypso all the time regardless of selected plan but to fix **Issue 3** we'll need to do exactly what we're doing for wp-admin. See https://github.com/Automattic/wp-calypso/pull/50267

> Issue 1: Before the checkout is displayed, the hooray confetti view flashes in very quickly before the checkout takes over, too quick for user to understand what's going on.

We're planning to do this a bit nicer. See https://github.com/Automattic/wp-calypso/issues/50122

> Issue 3: For Calypso, user is redirected back to the block editor, user did not get redirected to the store setup. Atomic transfer did happen though, because the subdomain becomes *.wpcomstaging.com. For WP-Admin, atomic transfer & store setup works as usual.

Fix in https://github.com/Automattic/wp-calypso/pull/50267

**Comment by ciampo** [comment]
>    * [ ]  ~The user is redirected to the standalone `/checkout` page~
>      - For Calypso, the checkout modal is displayed.
>      - For WP-Admin, it is redirected to `/checkout` page.

This is expected. When not mentioned explicitly, we assumed that the test would happen in Calypso's iframed editor — but thank you for testing in both!

> Issue 1: Before the checkout is displayed, the hooray confetti view flashes in very quickly before the checkout takes over, too quick for user to understand what's going on.

This is expected at this point in time, and tracked in #50122

> Issue 2: After completing checkout, the hooray confetti view also flashes in very quickly, too quick for user to understand what's going on.

From the videos, this only happens when launching from Calypso — I believe this could belong also to #50122 

> Issue 3: For Calypso, user is redirected back to the block editor, user did not get redirected to the store setup. Atomic transfer did happen though, because the subdomain becomes *.wpcomstaging.com. For WP-Admin, atomic transfer & store setup works as usual.

This may need investigating

**Comment by ciampo** [comment]
Closing as not applicable anymore
