### ISSUE TITLE
Gutenberg: 9.3 Plugin Upgrade

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#46985]
Call for testing: TBD
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/46314

### Process

- [ ] Install and activate on edge sites
- Testing:
  - [ ] Calypso e2e
  - [ ] TC
- [ ] Publish a Call for Testing post
- [ ] Should there be a public announcement? Add release highlights here: 26e1b-pb/#plain
- [ ] Update to stable release
- [ ] Activate upgrade for all sites
- [ ] Request update for Atomic sites
- [ ] Publish internal announcements
- [ ] Clean up unused releases
   - [ ] 9.0.0
   - [ ] 9.2.0
   - [ ] 9.2.1
- [ ] Open a new issue for the next upgrade, transfer remaining tasks, close this issue.
- [ ] Update the Log of Update Attempts section in the FG and list patches applied 

### Tasks

- TBD

**Comment by fullofcaffeine** [comment]
See https://github.com/Automattic/wp-calypso/issues/47011, instead.
