### ISSUE TITLE
Gutenberg: 9.3 Plugin Upgrade

### ISSUE THREAD

**Issue by ockham** [Automattic/wp-calypso#47011]
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/46314

### Process

- [x] Install and activate on edge sites
  - [x] Copy 9.2.2 to 9.3.0 (r216208-wpcom)
  - [x] Activate 9.3.0 on edge (D52323-code) ~(D52300-code)~ ~(r216210-wpcom; reverted by r216349-wpcom)~
  - [x] Install 9.3.0 plugin version (D52273-code)
- [x] Testing (need to re-run these when we _actually_ activate 9.3.0 on edge):
  - [x] Calypso e2e https://github.com/Automattic/wp-calypso/pull/47455 ~(https://github.com/Automattic/wp-calypso/pull/47184)~ ~(https://github.com/Automattic/wp-calypso/pull/47096)~
  - [x] TC (D52264-code)
- ~Publish a Call for Testing post~
- [x] Update to stable release
- [x] Activate upgrade for all sites
  - [x] First attempt (D52264-code)
  - [x] Revert upgrade :cry: (D52818-code). Reason: The upgrade broke the Premium Content block (part of the Editing Toolkit Plugin).
  - [x] Fixed Premium Content block (https://github.com/Automattic/wp-calypso/pull/47467) and released as part of ETP 2.8.6.
  - [x] Second attempt (D52940-code)
  - [x] Debrief (p58i-9K9-p2)
- [x] Request update for Atomic sites
  - [x] First attempt (p9o2xV-19f-p2)
  - [x] Downgrade request (p9o2xV-19h-p2) b/c of Premium Content block issue, see above
  - [x] Second attempt (p9o2xV-19s-p2)
- [x] Publish internal announcements (p7DVsv-9RP-p2)
- [ ] Clean up unused releases
   - [x] 9.0.0 (D52179-code)
   - [ ] 9.1.1
   - [x] 9.2.0 (D52180-code)
   - [x] 9.2.1 (D52181-code)
- [x] Open a new issue for the next upgrade, transfer remaining tasks, close this issue.
- [x] Update the Log of Update Attempts at coGjb-p2 (pcoGjb-n-p2)

### Tasks
- [x] Figure out (and fix) WSOD in the editor (see D52323-code).

### Issues fixed by this release (close after activating!)

- [x] Editing captions in the Gallery Block creates conflict (#46813)

**Comment by sirreal** [comment]
Logs: pcoGjb-n-p2

**Comment by ockham** [comment]
I think we can close this now :relieved:
