### ISSUE TITLE
Premium Patterns in the editor pattern inserter

### ISSUE THREAD

**Issue by andrewserong** [Automattic/wp-calypso#47224]
This is a tracking issue for tasks related to supporting premium patterns in the editor pattern inserter (pbAok1-1D1-p2). The scope is still being defined, so the tasks are likely to change.

The overall goal is to support premium patterns in the pattern inserter, and once inserted into the post, so that it is clear to a user that the pattern will require an upgrade, but that they can also get an idea of what the pattern will be like once they do upgrade. If they decide to opt-out, deleting the pattern should be easy. If they decide to upgrade, this should be straightforward and via a similar upgrade path as to premium blocks.

## Tasks

* ~Wrap or categorize premium patterns as "premium" and add the corresponding upgrade text. Ideally once a pattern is inserted, the whole pattern is flagged as premium, not just the premium block within it. It should be easy for a user to then delete the pattern if they don't wish to upgrade (some more thoughts in p9Jlb4-1S1-p2#comment-2980) (Separate issue in #47226)~ (de-scoped)
* [x] Assess viability of adding a premium badge in the inserter, next to the pattern title, to flag that using the pattern will require an upgrade. Ideally, let's find a way to do this in the Editing Toolkit plugin. If that isn't possible, propose a generalised solution in Gutenberg to support the pattern inserter being extended by plugins. (Separate issue in #47225)
* [x] Work out how to flag that a pattern is premium in the API, and then register it as such:
  - [x] Is it as simple as adding a "premium" tag? And if so, how do we ensure that it's respected even when patterns are translated (e.g. untranslated tag slug?) — possibly yes! We're exploring using a tag `premium_block_pattern` for this.
  - [x] Update the API endpoint or PatternStore as needed (Add reserved tag to be excluded from translation `premium_block_pattern` D52643-code)
  - [x] Add a `pattern_meta` custom taxonomy and `is_premium` flag to the API endpoint (D53825-code)
* [x] Update how patterns are registered in the Editing Toolkit to set the `description` from the pattern description field from the API which pulls from the `post_excerpt`.
* ~Ensure the upgrade flow works correctly in all places where we display it.~ (de-scoped, we are now just showing an indicator)
* [ ] Test and add premium patterns to the patterns inserter.

**Comment by andrewserong** [comment]
This tracking issue is nearly complete, the remaining pieces just need to be deployed (covered in pbAok1-1D1-p2#comment-3533)

**Comment by andrewserong** [comment]
Closing since this is now live.
