### ISSUE TITLE
Focused Launch: "Launch your site" button

### ISSUE THREAD

**Issue by ciampo** [Automattic/wp-calypso#47392]
- [x] The button should say _"Launch your site"_

- [x] The button should be disabled if at least one of the active steps doesn't have a valid selected value:

![Screenshot 2020-11-12 at 21 03 57](https://user-images.githubusercontent.com/1083581/98990452-c4783b00-252a-11eb-99ef-c2ab7c508aa3.png)

- [x] The button should be enabled once all active steps have a valid selected value:

![Screenshot 2020-11-12 at 21 04 11](https://user-images.githubusercontent.com/1083581/98990455-c5a96800-252a-11eb-9456-209ff1be3284.png)

- [x] If the user doesn't need to make any purchase, the button should take the user to the Success view (#47393)

- [x] If the user needs to make a purchase:
  - [x] (https://github.com/Automattic/wp-calypso/pull/47808) the button should take the user to the checkout screen and set the "success" URL redirection back to the Success view (spec'd in #47393, done in #47404).
  - [ ] When redirecting the user back to the editor (from Checkout) we should show the Success View (implemented in #47808)
  - [x] Data should be stored according to what defined in #47241

- [x] The button should be sticky at the bottom of the screen on mobile screens, and fill the whole width of the screen (apart from some padding around it):

![Screenshot 2020-11-12 at 21 14 45](https://user-images.githubusercontent.com/1083581/98991417-19688100-252c-11eb-8f28-4446c9f0efcb.png)

**Comment by ciampo** [comment]
@razvanpapadopol please take a look at this issue's specs, in case I missed or misunderstood and requirements

**Comment by ollierozdarz** [comment]
@ciampo looks good to me.
