### ISSUE TITLE
Gutenberg: 9.4 Plugin Upgrade

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#47520]
Previous upgrade: https://github.com/Automattic/wp-calypso/issues/47011

### Process

- [x] Install and activate on edge sites
  - [x] Copy 9.3.0 to 9.4 RC1 (D52898-code and D52900-code)
  - [x] Activate 9.4 RC1 on edge (D52901-code)
  - [x] Install 9.4 plugin version
- [x] Testing
  - [x] Calypso e2e (https://github.com/Automattic/wp-calypso/pull/47533)
  - [x] TC (D52936-code)
- [x] Update to stable release
- [x] Update to 9.4.1 point release
- [x] Activate upgrade for all sites (D52936-code)
- [x] Request update for Atomic sites (p9o2xV-1az-p2)
- [x] Publish internal announcements (p7DVsv-9Ya-p2)
- [ ] Clean up unused releases
   - [ ] 9.1.1
   - [ ] 9.4.0
- [ ] Open a new issue for the next upgrade, transfer remaining tasks, close this issue.
- [ ] Update the Log of Update Attempts at coGjb-p2  and list patches applied

### Blocker

**Note that we can't update on Atomic sites until JP 9.2 is released (and installed there) -- otherwise, we'll break JP blocks on FF: https://github.com/Automattic/jetpack/issues/17850**
Update: JP 9.2 was released on 2020-12-01, so we proceeded and also landed the GB upgrade.

### Tasks / potential blockers 🐛 

- [x] Browser locks up upon adding a columns block (#47579)
- [x] Jetpack blocks not loaded / found in the inserter on Firefox (https://github.com/Automattic/jetpack/issues/17850) (p1605902623138500-slack-C015AL3QL7M)
- [x] With 9.4.0 RC1, template parts are no longer loading.
  - Reported in p1605706934011400-slack-CHN6J22MP (for a WP.com edge site, PczmP1-2-p2).
  - Upstream issue: https://github.com/WordPress/gutenberg/issues/27072.
  - Seems to be okay, as it only affects previously created FSE sites -- which currently aren't public. See https://github.com/WordPress/gutenberg/issues/27072#issuecomment-733108038 for more details.

### Open issues (post-release)

- [ ] With 9.4, the 'Publish' button now reads 'Schedule...'. (Reported at https://github.com/Automattic/wp-calypso/issues/47935, https://github.com/WordPress/gutenberg/issues/27514, https://github.com/WordPress/gutenberg/issues/27251, and https://github.com/WordPress/gutenberg/issues/27500.)
  - [ ] Potential fixes at https://github.com/WordPress/gutenberg/pull/27398 and https://github.com/WordPress/gutenberg/pull/27519.
  - [ ] Decided to fix through a revert (https://github.com/WordPress/gutenberg/pull/27550). See https://github.com/WordPress/gutenberg/pull/27550#issuecomment-739944522 for more context.
  - [ ] Needs a GB point release.
- [x] [Premium Content Block] Issues with multiple pricing plans (#47939)
  - [x] Fix: #47944
  - [x] Needs ETP release (#47969)
- [ ] Adding a new page and trying to select one of the page templates (from our WordPress.com Editing Toolkit plugin) causes the editor/template preview to crash every time.  (p1606867460319700-slack-C015AL3QL7M)
  - [x]  Fix: https://github.com/WordPress/gutenberg/pull/27445
  - [ ] Needs Gutenberg (patch) release, or further investigation what changed in Calypso that cause this to happen.
- [ ] Users can no longer see the WooCommerce Payments pages under WP-Admin > Payments. (p9F6qB-6dU-p2 and p1606927004322300-slack-CGGCLBN58)

**Comment by sirreal** [comment]
Release notes: https://make.wordpress.org/core/2020/11/19/whats-new-in-gutenberg-4-november-2/

**Comment by aleone89** [comment]
Crosslinking: https://github.com/Automattic/wp-calypso/issues/47579 

cc. @getdave

**Comment by sirreal** [comment]
> Adding a new page and trying to select one of the page templates (from our WordPress.com Editing Toolkit plugin) causes the editor/template preview to crash every time. (p1606867460319700-slack-C015AL3QL7M and WordPress/gutenberg#27445)

Diff here for testing: D53653-code

**Comment by fullofcaffeine** [comment]
This is done. Next one: https://github.com/Automattic/wp-calypso/issues/47881.
