### ISSUE TITLE
Editor Welcome Tour Project: Master Task List

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#47690]
# Editor Welcome Tour 
pbAok1-1Dh-p2

MVP Deliverable
- [x] Tech Spike https://github.com/Automattic/wp-calypso/issues/47688
- [x] Editor Welcome Tour MVP https://github.com/Automattic/wp-calypso/issues/47691 & https://github.com/Automattic/wp-calypso/pull/47779
- [x] Only show tour to users who haven't seen it before.
- [x] Ability to track necessary metrics, tech details TBD as needed (A/B test D53894-code) tracking PR: https://github.com/Automattic/wp-calypso/pull/48390

Nice to have for MVP or ToDo post-MVP
- [ ] Use icons that match buttons rather than text descriptions
- [ ] Tour animations: buttons/items in Editor UI are highlighted as user proceeds through tour [see WIP Spike](https://github.com/Automattic/wp-calypso/pull/47662)
- [x] Like/unlike buttons
- [ ] Remove legacy NUX content

**Comment by ramonjd** [comment]
We've launched the tour! See pbxNRc-Cb-p2#comment-1501

@autumnfjeld Should we move the nice to haves to a new issue and close this one? Up to you

**Comment by autumnfjeld** [comment]
> We've launched the tour! See [pbxNRc-Cb-p2#comment-1501](https://href.li/?pbxNRc-Cb-p2#comment-1501)
> 
> @autumnfjeld Should we move the nice to haves to a new issue and close this one? Up to you

@ramon Actually I don't think that list is valid anymore, and we don't need to track the items.  Because:

- Use icons that match buttons rather than text descriptions -
  -  I can't remember the root of this issue, and it doesn't make sense to me. 
- Tour animations: buttons/items in Editor UI are highlighted as user proceeds through tour see WIP Spike 
  -  This is noted in Jon's designs and also is tracked in our call for testing feedback.
- ~~Like/unlike buttons~~. 
  - DONE
 - Remove legacy NUX content -
   - Kind of obvious, after testing this will naturally fall into place as next step. IMHO

**Comment by ramonjd** [comment]
Going to go ahead and close this issue 🎉 

I think we've covered the spec. 🙇
