### ISSUE TITLE
Coming Soon v2 post-launch tasks

### ISSUE THREAD

**Issue by ramonjd** [Automattic/wp-calypso#47777]
Things have been up for a while. No major issues. What do we do next?

Here are some high-/low-/somewhere-in-between-level tasks.

### Immediate
- [x] Preserve Private + Viewer user privileges D53164-code and https://github.com/Automattic/wp-calypso/pull/47666 **(priority high)**
- [x] Update FG document PCYsg-py7-p2 **(priority high)**
- [x] Refactor the MU plugin https://github.com/Automattic/wp-calypso/issues/47486
- [x] ~Add login hooks to the Atomic Coming Soon page #47775~
- [ ] Ensure Coming Soon page doesn't import theme CSS for Atomic sites (we think it might be doing that)
- [x] Remove Calypso coming-soon-v2 flags and conditional code ~https://github.com/Automattic/wp-calypso/pull/47854~ ~https://github.com/Automattic/wp-calypso/pull/47849~ ~https://github.com/Automattic/wp-calypso/pull/47850~ ~https://github.com/Automattic/wp-calypso/pull/48346~ ~https://github.com/Automattic/wp-calypso/pull/47851~ ~https://github.com/Automattic/wp-calypso/pull/47852~
- [x] Use a hook to return the `localized_wpcom_url` from the WPCOM side instead of using a WPCOM-only method in the ETK https://github.com/Automattic/wp-calypso/pull/48076 D53828-code
- [ ] Ensure the badge updates when a user changes the settings #48153

#### Can be done now, but only if we get time

- [x] Update the fallback coming soon page design #46641 and maybe look at the UX of the buttons/layout for .com and Atomic
- [x] Hide privacy settings for unlaunched sites #46629

### Down the track

We might like to do another data request to check how many users are running coming soon v1 mode. See pa1C6h-Qp-p2

At this point we've already prepared to deliver the coming soon v2 functionality to users who haven't yet switched to coming soon v2 (via option checks or whatever). 

- [ ] Audit v1 code: where is it? What should we keep? What should we remove?
- [ ] Decouple privacy by default from Coming Soon
- [ ] Centralize Coming Soon functionality: where we can, to the ETK plugin, where we can't, to the WPCOM mu-plugin
- [ ] Remove references to Coming Soon v1
- [ ] Cleanup WPCOM and WPCOMSH launch banner logic
