### ISSUE TITLE
Editing Toolkit: Update newspack blocks (Tracking)

### ISSUE THREAD

**Issue by david-szabo97** [Automattic/wp-calypso#48253]
Newspack blocks is getting older and older in Editing Toolkit. We tried to update it in this [PR](https://github.com/Automattic/wp-calypso/pull/48179) but resulted in build errors. It got reverted in this [PR](https://github.com/Automattic/wp-calypso/pull/48186).

We can't update newspack blocks in ET till the tests are fixed. Here is my proposed plan to finally get it updated:

**Plan:**

- [x] - Fix an issue in newspack blocks that's causing some tests to fail: https://github.com/Automattic/newspack-blocks/pull/649
- [x] - Release a new newspack blocks version with the changes above (1.17.1)
- [x] - Create a PR which updates the newspack blocks to the latest version in Editing toolkit
- [x] - Merge newspack blocks update PR even though some tests are failing in TeamCity
- [x] - Create a PR which bumps the Editing Toolkit version
- [x] - Wait for a diff
- [x] - Add these changes to the ET release diff: D54168-code
- [x] - Make sure tests are passing
- [ ] - Commit diff
- [ ] - Merge PR

cc @Addison-Stavlo  @jeffersonrabb  @laurelfulford
