### ISSUE TITLE
Focused Launch: Domain details design parity

### ISSUE THREAD

**Issue by tjcafferkey** [Automattic/wp-calypso#48256]
Discrepancies between current domain details view and designed domains details view.

Design parity Figma link: 27834-pb

- [ ] Title - If we are able to, use Recoletta Medium font for the title.
- [ ] Title - `color: #101517;`
- [ ] Sub-title - Remove letter spacing
- [ ] Domain search input - Input box to be `height: 44px;`
- [ ] Domain search input - Unfocused `border-color: #C3C4C7;`
- [ ] Domain search input - Search icon to be the one in the design
- [ ] Domain search input - Search icon to be on the left hand side of the input
- [ ] Labels ("Keep sub-domain" and "Professional domains") - `letter-spacing: 0.8px;`
- [ ] Labels ("Keep sub-domain" and "Professional domains") - `font-weight: 600;`
- [ ] Sub-domain suggestion - Remove letter spacing on the text under the domain name within the sub-domain suggestion (You can change your free subdomain... etc)
- [x] [#50719] Sub-domain suggestion - "Free" text to be `color: #008A20;`
- [ ] Domain suggestion - Can the name and the TLD be the same style and colors as the Summary view
- [ ] Domain suggestion - Select button `border-color: #C3C4C7;`
- [ ] Domain suggestion - Select button `color: #1D2327;`
- [ ] Domain suggestion - "Recommended" tag should match Summary view style, which is green.
- [x] [#50719] Domain suggestion - "Included in plans" content should match design.
- [ ] View more results text link - `color: #117AC9;`

**Comment by youbrokesomething** [comment]
Focused Launch is no longer active and has been replaced by other projects. I'm closing this issue.
