### ISSUE TITLE
WP-Desktop: Apple Silicon Support

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#48504]
### Description

The wp-desktop application needs to be updated to be functional on Apple Silicon.

Per the [Electron docs](https://www.electronjs.org/blog/apple-silicon), upgrading to Electron v11 and compiling for `darwin-arm64` is required.

Because the app isn't distributed in the App Store, we'll need to test whether the auto-updater continues to work as expected with both Intel (w/ Big Sur) and Apple Silicon environments (now that we'll have to deploy two separate Mac targets for Intel and `arm64`).

We have established that the existing x64 build of the app will continue to function with Rosetta 2 emulation. However auto-updating the x64 build will fail (see note below).

### Tasks

- [x] Update `electron-builder` (waiting on patches that support arm64 compilation and auto-updates  [**Pending**] 
- [x] Add arm64 build (incl. notarization) to CI
- [ ] Add arm64 build to website

**Comment by nsakaimbo** [comment]
Update: we've done some testing and were able to verify that the current (x64) build of the application can run on Apple Silicon via Rosetta2 emulation. Howevery, auto-updating will likely fail as the translated application location is read-only ([ref](https://steipete.com/posts/apple-silicon-m1-a-developer-perspective/)).
