### ISSUE TITLE
Store|Woo: Launch deprecation of Store

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#48939]
Part of the "Sunset Store on WordPress.com" epic (https://github.com/woocommerce/woocommerce-admin/issues/5816) -- see that for more context.

### Enable in staging

- [x] Enable feature flag `woocommerce/store-deprecated` in all non-production environments where `woocommerce/extension-dashboard` is currently enabled: `desktop-development`, `development`, `stage`, `wpcalypso`
- [x] Update `STORE_DEPRECATION_START_DATE` in `client/lib/plans/constants.js` to a timestamp that will be right after you deploy to staging _(note: it is key to have some existing sites with Business plan subscriptions before doing this, so that you can properly test things)_

### Test in staging

- [x] Test in staging on all supported browsers/environments, with a variety of different site types, such as:
    - [x] Existing Business plan site
    - [x] New Business plan site
    - [x] eCommerce plan site
    - [x] Personal plan site

Verify... (from #48903):

- [x] "Store" available for (Atomic) sites with Business plan subscriptions started before Store was deprecated
- [x] "Store" not available for (Atomic) sites with Business plan subscriptions started after Store was deprecated
- [x] "Store" (linking to WooCommerce Core) available for sites with eCommerce plan subscriptions
- [x] "WooCommerce" available for (Atomic) sites with Business plan subscriptions

**TODO: add other key things to test from project thread and other issues**

- [x] Verify that MC stats and Tracks events are being logged

### Post about change

- [x] Publish a P2 post summarizing change and giving heads-up when it is expected to go live. Request that product and design run through it (or, maybe we provide a video of it in action), to make sure that we are all in agreement on what we are about to put in production.

### Enable in production

- [x] Enable feature flag `woocommerce/store-deprecated` in all production environments where `woocommerce/extension-dashboard` is currently enabled: `production`
- [x] Update `STORE_DEPRECATION_START_DATE` in `client/lib/plans/constants.js` to a timestamp that will be right after you deploy to production

### Test in production

- [x] Re-test everything that was tested in staging.

### Post publicly about change

~- [ ] Publish something on en.blog about the deprecation?~ (no need to keep this issue open for this potential action (asked on pbIJXs-sE-p2#comment-1656 for followup)

**Comment by mattsherman** [comment]
Close this issue, as all tasks were completed.
