### ISSUE TITLE
Tracking: Enable Gutenberg image editing on simple sites

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#49096]
Project: pc9Uba-fo-p2

- [x] Figure out a way to pass the value for `crossOrigin` for the img el  @fullofcaffeine 
- [x] Conditionally change the passed value of `crossorigin` depending on whether the site is public or private (D55474-code) @fullofcaffeine 
- [x] Send the proper CORS headers (D46175-code) @fullofcaffeine 
- [x] Set the `crossOrigin` attribute on the image element created by the image editor ([PR](https://github.com/WordPress/gutenberg/pull/28255)) @fullofcaffeine 
- [x] Get a Proof of concept diffs working with the wpcom and gb changesets (main POC diff has been split in the final diffs: D55474-code, D46175-code, D55641-code) @fullofcaffeine 
- [x] Get a [PR](https://github.com/WordPress/gutenberg/pull/28255) up with the Gutenberg changes @fullofcaffeine 
- [x] Ship the Gutenberg PR 
- [x] Test across multiple browsers and enable the image editor on wpcom simple sites (D55641-code).

**Comment by simison** [comment]
@fullofcaffeine good to close?

**Comment by fullofcaffeine** [comment]
> @fullofcaffeine good to close?

Oh, thanks for the nudge :)
