### ISSUE TITLE
Top Bar Alignment and Color Issues

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#49154]
### Steps to reproduce the behavior
There are some CSS alignment differences when viewing the topbar in Calypso vs on the front-end of a site (all logged-in views). Some are very significant, and some are pretty slight. I would say the mobile front-end view has the most jarring difference, and the desktop differences are more slight.

The difference in color is very obvious though.

1. In calypso, the shade of gray for the top-bar background color is darker than the shade of gray on a site frontend.
2. On front end views, on desktop viewports, there is significantly more left margin on the "reader" button than there is in the Calypso view.
3. On front-end views, on mobile viewports, there is significantly more left margin beside the "my sites" button than there is in the calypso view.
4. On front-end views, on mobile viewports, there is more margin between all buttons than there is in calypso.
5. On front-end views, on desktop viewports, there is more right margin on the profile icon than there is in calypso.
6. On front-end views, there is no "write" button. This is probably deliberate, unlike the other problems, but it is still a difference.

#### Desktop Calypso:
<img width="1343" alt="Screen Shot 2021-01-21 at 3 01 23 PM" src="https://user-images.githubusercontent.com/6265975/105423738-f678de00-5bfa-11eb-9d31-4736a63c5560.png">

#### Desktop Front-End:
<img width="1343" alt="Screen Shot 2021-01-21 at 3 01 28 PM" src="https://user-images.githubusercontent.com/6265975/105423743-f7aa0b00-5bfa-11eb-98b2-1db482abd31a.png">

#### Mobile Calypso:
<img width="612" alt="Screen Shot 2021-01-21 at 3 01 52 PM" src="https://user-images.githubusercontent.com/6265975/105423744-f842a180-5bfa-11eb-9b74-31c934b89154.png">

#### Mobile Front-End:
<img width="612" alt="Screen Shot 2021-01-21 at 3 01 58 PM" src="https://user-images.githubusercontent.com/6265975/105423746-f8db3800-5bfa-11eb-9069-93a8c59f2b18.png">

#### Browser / OS version
All

#### Is this specific to the applied theme? Which one?
No

#### Does this happen on simple or atomic sites or both?
All sites

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
All user logged-in views

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See above

**Comment by sixhours** [comment]
It looks like the front-end spacing weirdness issue on desktop is specific to P2; my normal simple sites and atomic sites are fine:

<img width="1665" alt="Screen Shot 2021-04-06 at 11 38 27 AM" src="https://user-images.githubusercontent.com/2124984/113738117-9f988600-96cc-11eb-9afd-fe0d9aec3d57.png">
<img width="1670" alt="Screen Shot 2021-04-06 at 11 37 45 AM" src="https://user-images.githubusercontent.com/2124984/113738129-a1fae000-96cc-11eb-9012-4b8e06eabcac.png">

On P2, there's an additional invisible menu item in that space, `#wp-admin-bar-menu-toggle`, that does not exist on normal sites. I'm not sure where it's coming from or what it does (I would have thought it was a mobile menu toggle, but it's invisible on mobile screens, too). In P2's CSS there's a reference to it that seems to suggest even P2 folks don't know what it is:

```
        // Prevent this invisible toggle from interfering with our
	// mobile menu toggle button when hovering near the edge of the window.
	// (What is this even?)
	#wp-admin-bar-menu-toggle {
		pointer-events: none;
	}
```

Confirmed this is happening on both internal P2 as well as non-internal P2: 
<img width="1666" alt="Screen Shot 2021-04-06 at 12 07 40 PM" src="https://user-images.githubusercontent.com/2124984/113742616-c658bb80-96d0-11eb-9233-bc71b07374b7.png">

**Comment by sixhours** [comment]
Aha, it's the core menu toggle for `/wp-admin`: 
<img width="231" alt="Screen Shot 2021-04-06 at 11 57 33 AM" src="https://user-images.githubusercontent.com/2124984/113741127-55fd6a80-96cf-11eb-8ba2-d7c1fb369b27.png">

I'm not sure why it's showing on P2 sites' front-end but it should be safe to `display: none` it at the bare minimum.

**Comment by sixhours** [comment]
> In calypso, the shade of gray for the top-bar background color is darker than the shade of gray on a site frontend.

I think this is the expected behavior. In Calypso, the top bar color will change depending on your color scheme, and those won't be reflected on the front end. We could update the default color scheme top bar color to match the front end for closer visual parity, but I don't think we should set the expectation that the front end will match Calypso.

**Comment by sixhours** [comment]
Related issue: #47386

**Comment by sixhours** [comment]
Started a PR for the extra left-hand padding in D59796-code

**Comment by noahtallen** [comment]
> I don't think we should set the expectation that the front end will match Calypso

I think my personal expectation would be for that bar to match my color scheme (especially if wp-admin/calypso are being kept in sync now) because it's part of the logged-in management UI

Thank you for looking into this! Glad it's not as wide-spread as it seemed at first.

**Comment by sixhours** [comment]
> I think my personal expectation would be for that bar to match my color scheme (especially if wp-admin/calypso are being kept in sync now) because it's part of the logged-in management UI

@noahtallen That's fair! I've opened a new issue in #51757 since I can see it going both ways and it's not technically a bug.

**Comment by sixhours** [comment]
Just breaking this out into checkboxes so I can keep track of what's shipped:

- [x] In calypso, the shade of gray for the top-bar background color is darker than the shade of gray on a site frontend. (TBD in #51757)
- [ ] On front end views, on desktop viewports, there is significantly more left margin on the "reader" button than there is in the Calypso view. (P2 only, reported in Automattic/p2#2443)
- [x] On front-end views, on mobile viewports, there is significantly more left margin beside the "my sites" button than there is in the calypso view - D59796-code
- [x] On front-end views, on mobile viewports, there is more margin between all buttons than there is in calypso (Addressed in #51720)
- [x] On front-end views, on desktop viewports, there is more right margin on the profile icon than there is in calypso. (Addressed in #51720)
- [x] On front-end views, there is no "write" button. This is probably deliberate, unlike the other problems, but it is still a difference. (Deliberately hidden on P2 only, asked about it here: https://github.com/Automattic/wp-calypso/issues/49154#issuecomment-815139127)

**Comment by sixhours** [comment]
The absence of a Write button on the front end is also specific to the new P2 (not older versions); normal site:

<img width="1665" alt="Screen Shot 2021-04-07 at 2 38 47 PM" src="https://user-images.githubusercontent.com/2124984/113917458-3b9abe00-97af-11eb-95fc-5e820e864c82.png">

P2:

<img width="1665" alt="Screen Shot 2021-04-07 at 2 40 11 PM" src="https://user-images.githubusercontent.com/2124984/113917500-448b8f80-97af-11eb-8dbf-af51a3757d42.png">

This was introduced by @mirka about a year ago in Automattic/p2#115, maybe they know why we're hiding it for P2?

**Comment by mirka** [comment]
> This was introduced by @mirka about a year ago in Automattic/p2#115, maybe they know why we're hiding it for P2?

Right, this was a deliberate design choice to encourage use of the front-end editor. And also to not confuse those who are unfamiliar to WP with two different editors.

**Comment by kwight** [comment]
All of the user-facing issues have been fixed – there's one remaining [P2-specific issue](2443-gh-Automattic/p2) being tracked and handled by that team. Closing.
