### ISSUE TITLE
Testing: Unit tests improvements

### ISSUE THREAD

**Issue by gziolo** [Automattic/wp-calypso#4915]
Follow up for #3822 where we migrated all tests to work with single test runner. We still should do some more cleanup. List of open tasks:
- [x] [Refactor server/api test to make it work in test env](https://github.com/Automattic/wp-calypso/pull/4697)
- [x] [Find solution for double callback warning](https://github.com/Automattic/wp-calypso/issues/4206)
- [x] [Remove lib/react-test-env-setup and use Automattic/react-test-env in useFakeDom test helper](https://github.com/Automattic/wp-calypso/issues/4916)
- [x] ~~[Move React mixin injection into useI18n helper method](https://github.com/Automattic/wp-calypso/issues/4917)~~
- [x] ~~[Get rid of temporary helper `useFilesystemMocks`](https://github.com/Automattic/wp-calypso/issues/4918)~~
- [x] [Run a subset of the tests from the command line and watch for changes](https://github.com/Automattic/wp-calypso/issues/4922)
- [x] [Remove obsolete useI18n test helper](https://github.com/Automattic/wp-calypso/issues/5818)
- [x] [Make sure we always use test env config when running client tests](https://github.com/Automattic/wp-calypso/issues/5856)
- [ ] [Bring back Mocha integration with IDEs](https://github.com/Automattic/wp-calypso/issues/6076)
- [x] [Successful test runs even without a config file](https://github.com/Automattic/wp-calypso/issues/6605)
- [ ] [Testing: Remove all React warnings from client tests](https://github.com/Automattic/wp-calypso/issues/8274)
- [ ] [Framework: Investigate new test warnings](https://github.com/Automattic/wp-calypso/issues/8376)

**Comment by gziolo** [comment]
@aduth @blowery @mtias @nb: I created list of follow up task that I would like us to take car of in the nearest future. Let me know if that makes sense for you. Feel free to add any item to that list :)

**Comment by gziolo** [comment]
We should also take a look at https://github.com/Automattic/wp-calypso/tree/master/test/test/helpers folder and see if want to remove something from there. I see `mocks` folder for the first time, should we keep it there or move closer to the code that uses it?

**Comment by gziolo** [comment]
It is no longer relevant since we migrated to Jest. See #16943.
