### ISSUE TITLE
[EPIC] Users, Settings, Media, People pages are inconsistent between Calypso vs WPAdmin - find a way to unify

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49262]
See https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-765555441.

Essentially there is no consistency between Settings screens registered to Calypso vs WPAdmin. Neither is the superset. Some settings are missing from each. We need to unify these.

## Research

- [x] As per https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-766865603, let's produce a spreadsheet comparing Calypso and WPAdmin for the following screens:
* Media
* People
* Users.
* Settings.
- [x] Determine how it is best to unify the experience. -> paYJgx-1lp-p2#comment-1661

## Tasklist
- [x] 577-gh-Automattic/wpcomsh Fix storefront menu item missing. If that’s a menu item registered by the Storefront theme, that should just be migrated into “Appearance” like any other 3rd-party menu item.
- [x] https://github.com/Automattic/wp-calypso/issues/49238 Appearance ->WordPress.org Themes [/wp-admin/theme-install.php] only for WoA
- [x] https://github.com/Automattic/wp-calypso/issues/49211 People -> Advanced Users List [/wp-admin/users.php] only for WoA.
- [x] https://github.com/Automattic/wp-calypso/issues/49191 Settings -> Advanced General Settings [/wp-admin/options-general.php] only for WoA when we detect that a plugin has registered settings for these screens.
- [x] https://github.com/Automattic/wp-calypso/issues/49191 Settings -> Advanced Writing Settings [/wp-admin/options-writing.php] only for WoA when we detect that a plugin has registered settings for these screens.
- [x] [High] https://github.com/Automattic/wp-calypso/issues/49830 Widgets & Menus

**Comment by getdave** [comment]
I agree with what @obenland mentioned in https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-766963036 that we need to find a way to unify the settings screens rather than expect users to switch between Calypso and WPAdmin.

This is on Ajax's radar and will be tackled in due course.

No requirement for design work at the moment @sfougnier.

**Comment by ghost** [comment]
I'll be taking a look into the toggle issue from a UX perspective, so I'd love to work with whoever picks this one up. If whoever picks this up could ping me, I'd be happy to collaborate on this one.

**Comment by mmtr** [comment]
> I agree with what @obenland mentioned in https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-766963036 that we need to find a way to unify the settings screens rather than expect users to switch between Calypso and WPAdmin.

I agree with https://github.com/Automattic/wp-calypso/issues/47043#issuecomment-766963036 as well, it's a better solution than showing the quick toggle that I suggested.

For conflicting pages, rather than choosing one, we could present both in the menu and make sure they are named differently.

Example:
- Users
  - All people: `wordpress.com/people/team/:site`
  - Edit users: `/wp-admin/users.php` (Only JP/AT sites)
  - Invite: `wordpress.com/people/new/:site`
  - Add new: `/wp-admin/wp-admin/user-new.php` (Only JP/AT sites)
- Settings
  - Site: `wordpress.com/settings/:site`
  - General: `wp-admin/options-general.php` (Only when there are custom fields or sections)

**Comment by cpapazoglou** [comment]
Another issue

> Markdown in comments can only be accessed from `/wp-admin/options-discussion.php` but there’s not a link to get there now.

props: @kriskarkoski

**Comment by ghost** [comment]
>Users
All people: wordpress.com/people/team/:site
Edit users: /wp-admin/users.php (Only JP/AT sites)
Invite: wordpress.com/people/new/:site
Add new: /wp-admin/wp-admin/user-new.php (Only JP/AT sites)
Settings
Site: wordpress.com/settings/:site
General: wp-admin/options-general.php (Only when there are custom fields or sections)

I'm a little unsure from a user's perspective why we'd want to surface all these pages at once, as they seem to create duplicates of the same functionality in some pages.

- Are you suggesting the duplicate wp-admin pages would only appear conditionally if I had enabled some kind of feature that would be managed on those pages?
- Why would "Edit Users" and "Add New" only be visible on JP/AT sites? Would those replace the "All People" and "Invite" pages that would only be seen on Simple sites?
- How would this work with the advanced settings (default to wp-admin) toggle, if at all?

I've been doing my own audit of the experience and I'm aiming to have some potential solutions to this issue in the next few days. I'd like to create something we can iterate toward. I think the above approach could certainly be considered, but I also want to be sure we're not missing out on a better approach for our users.

**Comment by obenland** [comment]
> Why would "Edit Users" and "Add New" only be visible on JP/AT sites?

Only in JP/AT are we in a situation where 3rd-party plugins could add settings to these screens.

> Are you suggesting the duplicate wp-admin pages would only appear conditionally if I had enabled some kind of feature that would be managed on those pages?

I'm in favor of that. It shouldn't be too hard to only show them based on whether the page has any registered settings.

> I've been doing my own audit of the experience and I'm aiming to have some potential solutions to this issue in the next few days.

I'm looking forward to your suggestions! The ones we've come up with so far don't feel super ideal, it's not an easy problem to solve.

**Comment by cpapazoglou** [comment]
After some fiddling with ALL the menu items I could find in a site with e-commerce plan with **nav-unification disabled** I have published my findings and a proposal here paYJgx-1lp-p2.

**Comment by cpapazoglou** [comment]
I have tracked down the Issues to be resolved in the description.

**Comment by getdave** [comment]
## Status Update

To confirm @obenland has asked that we pursue the solution outlined at paYJgx-1lp-p2#comment-1661.

To that end @cpapazoglou has updated this Issue description with a task list.

Let's work towards this.

**Comment by pendantry** [comment]
Pardon my jumping in here... much of this is gobbledegook to me (I'm a n👀b on GitHub, though not to WordPress).

I thought I could add a user's perspective.

Having used wp-admin quite happily for years, I'm very familiar with it. I'm not entirely clear on what 'Calypso' is, but I'm guessing from the context here that it's that 'other' configuration interface that rears its ugly head every now and again. And to be brutally frank, it drives me more than a little nuts! The way WordPress works these days is totally inconsistent: sometimes I follow a link and end up in wp-admin, exactly where I expect to be; other times (for no apparent reason I can fathom) I'm taken to the pretty-blue-pastel-with-far-too-much-white-space 'other' interface.

I really don't understand the need to reinvent the wheel: the wp-admin interface is compact, clean, well-proven. Why change it? Maybe it's something to do with the need to try to accommodate dumbphone interfaces? (I always use a desktop myself for my creative writing, struggling with that tiny dumbphone keypad thingy doesn't work at all for me, I've spent too many years touch-typing on a proper keyboard.)

Glad to hear that you're working on the problem!

Thank you for listening. Keep up the good work! I'll leave you in peace :)

**Comment by getdave** [comment]
@mmtr Can we remove this EPIC from our backlog and just retain the single remaining issue in our Global Backlog? Cleans things up a bit. What do you think?

**Comment by mmtr** [comment]
Agreed. I updated the summary to remove the remaining issue and moved it to our Global Backlog.
