### ISSUE TITLE
Store|Woo: Remove Store in production environments

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49429]
_Part of the Sunset Store project. See pbIJXs-sE-p2 for more details._

To launch the removal of Store, we should remove Store in the following environments by enabling the `woocommerce/store-removed` feature flag.

- `config/production.json`
- `config/stage.json`

## Acceptance criteria

On production (wordpress.com when unproxied)...

- If user accesses any `/store` URL, they are redirected to the Store dashboard where they will see a message stating the Store experience has been replaced by the WooCommerce experience (implemented in #48249 and #48026)
- If user clicks any sidebar item in the Store dashboard, they will be redirected to the corresponding WooCommerce Core experience (implemented in #48194)

## Tasks

- [x] Enable `woocommerce/store-removed` feature flag in environments listed above
- [x] Update P2 project thread and call-for-testing posts
    - [x] Include a link to `calypso_store_post_sunset` MC stat

**Comment by mattsherman** [comment]
Re-opening, because I haven't updated P2s yet.

**Comment by mattsherman** [comment]
This is now Done.
