### ISSUE TITLE
Store|Woo: Remove Store in development and wpcalypso environments

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49428]
_Part of the Sunset Store project. See pbIJXs-sE-p2 for more details._

To prepare for the launch of the removal of Store, we should remove Store in the following environments **_a week prior to launch_**, by enabling the `woocommerce/store-removed` feature flag.

- `config/desktop-development.json`
- `config/development.json`
- `config/wpcalypso.json`

## Acceptance criteria

On wpcalypso.wordpress.com and local Calypso dev environments...

- If user accesses any `/store` URL, they are redirected to the Store dashboard where they will see a message stating the Store experience has been replaced by the WooCommerce experience (implemented in #48249 and #48026)
- If user clicks any sidebar item in the Store dashboard, they will be redirected to the corresponding WooCommerce Core experience (implemented in #48194)

## Tasks

- [x] Enable `woocommerce/store-removed` feature flag in the above environments
- [ ] Publish a P2 post, similar to pbIJXs-y6-p2, informing Automatticians that the Store has been removed on wpcalypso.wordpress.com and local Calypso dev environments
    - [x] Note that this is ready in the non-Nav Unification experience (which is all that customers have access to now) and that we are still wrapping up final fixes to have it fully compatible with Nav Unification 
    - [x] Ask for help testing, including verifying that redirects work
    - [x] Mention when the Store will be removed in production

**Comment by moon0326** [comment]
The change is in `update/49428-remove-store-in-development-and-wpcalypso-env` branch. I'm holding off creating a PR until we are ready to merge to avoid any confusion.

**Comment by becdetat** [comment]
@moon0326 I've done your PR again (ok I didn't see it until I was mostly done) - I also made sure the notice on the store pages is definitely the store removed copy as I think the logic was a little off

**Comment by mattsherman** [comment]
This was closed via #50070
