### ISSUE TITLE
Store|Woo: Remove `woocommerce/store-removed` flag (always remove Store)

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#49430]
_Part of the Sunset Store project. See pbIJXs-sE-p2 for more details._

Now that Store has been removed for a few weeks in production for all customers, we should clean up the codebase by removing the `woocommerce/store-removed` flag. Store should always be removed, no matter the environment.

## Acceptance criteria

- Store should always be removed, with behavior identical to when the `woocommerce/store-removed` feature flag was enabled

## Tasks

- [ ] Remove `woocommerce/store-removed` feature flag from
    - [ ] `config/desktop-development.json`
    - [ ] `config/development.json`
    - [ ] `config/production.json`
    - [ ] `config/stage.json`
    - [ ] `config/wpcalypso.json`
- [ ] Remove all references to `woocommerce/store-removed` feature flag and adjust logic such that is behaves the same as when the feature flag was enabled
- [ ] Make sure all automated tests are updated
