### ISSUE TITLE
[EPIC] DomainPicker: what domain features are still missing?

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#49651]
### What
The missing domain related features were discussed in pbAok1-Hb-p2. We should try to match the existing features from `/start` flow.

### Why
The `/new` onboarding flow is already live for existing customers with EN locale and some new experiments are going to start soon.

#### How
We should check what is still missing from the current DomainPicker and if there are issues to track everything. Then we should prioritize these issues.

#### List of missing features
- [ ] handle Premium domains to show they are not included in plans. See convo: p1612357132271000-slack-C0KDTA48Y
- [ ] handle unavailable domain different statuses #51651 
- [ ] handle redirect to use-a-domain-i-own flow for new users https://github.com/Automattic/wp-calypso/issues/51137
- [ ] handle purchasing a TLD with a Free plan https://github.com/Automattic/wp-calypso/issues/42081
