### ISSUE TITLE
Make it easier to see what plan a user is on, and make it easy for them to change it

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#49660]
Based on comment by Aadil in p7DVsv-ago-p2#comment-34188.

> It’s much harder for me to know what plan I’m on with the new Nav. Can we explore some ideas to make it easier to see what plan a user is on, and make it easy for them to change it? Right now I need to click on `Upgrades -> Plan -> My Plan` which feels too far away.

## Tasks

- [x] Explore solutions (being mindful of expediency) to make it clearer which Plan the user is on.
- [x] Discuss ideas with Design and Engineering.
- [x] @Automattic/ajax to implement necessary changes.

@sfougnier would you be able to help us out with this one?

**Comment by ghost** [comment]
- Add the user's plan name to the sidebar, similar to how it appeared in the Calypso nav.
<img width="1440" alt="desktop - calypso" src="https://user-images.githubusercontent.com/67021691/108241157-88500a00-7119-11eb-9ae3-bc2fb5267332.png">

- Switch the order of 'Plans' and 'My Plan' in the tabs so that when I click 'Upgrades' in the sidebar, it lands me in 'Plans', with the 'My Plan' tab selected by default.
<img width="1440" alt="desktop - calypso-1" src="https://user-images.githubusercontent.com/67021691/108241196-91d97200-7119-11eb-9fb7-8a4441735712.png">

**Comment by tjcafferkey** [comment]
**Planning meeting notes**
* Potentially look into creating a standard to pass additional data into markup which doesn't compromise security by allowing plugin developers to inject their own markup in to menu items.
* Potentially look at modifying the "badges" functionality to accommodate text.
