### ISSUE TITLE
[EPIC] Nav Unification launch/pre-launch tasks

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#50080]
In order that we launch nav-unification to the first segment of users (5%) [pbAPfg-103-p2] we will need to edit the following so that they include **all new users and 5% of existing users** : 

- [x] ~Check for final decision on whether Jetpack connected sites are in/out of v1 launch - _disable_ across envs if being ommitted~. **Update** - the decision was made to omit.
- [x] Disable Nav Unification for Jetpack connected sites and confirm via test with JPOP.
- [x] #50379 calypso
- [x] #50380 wpcom
- [x] 613-gh-Automattic/wpcomsh atomic
- [x] #50037 Update the condition for the modal to only show to existing users
- [x] Pre launch check with Happiness Product Ambassadors
- [x] Launch p2 post across all p2s - especially updateomattic.

in order to get a consistent segment which doesn't alter on each ramp up, we will use `$user_id % 100 < $segment` where `$segment = 5` for the launch.

If all the above are accomplished, each ramp up will only need change in Calypso & wpcom. No need to deploy wpcomsh.

**Comment by getdave** [comment]
Let's make individual, well-formed Issues for all of these tasks and add them to our Backlog for this coming Iteration 4.

**Comment by getdave** [comment]
> Launch p2 post across all p2s - especially updateomattic.

I will start preparing this.

**Comment by getdave** [comment]
@cpapazoglou This looks to be done. Can we close it out?

**Comment by cpapazoglou** [comment]
Sure
