### ISSUE TITLE
[EPIC] LiveChat "quick fixes" for WPAdmin

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#50226]
Please see paYJgx-1nM-p2#comment-1705.

As LiveChat cannot currently work in WPAdmin, these "quick fixes" are proposed as a short term work around to unblock the launch of Nav Unification.

A more robust solution will follow if/when resources become available. 

## Tasks

The following should be split into two separate Issues/PRs:

- [x] https://github.com/Automattic/wp-calypso/issues/50235: Show a warning when Happy Chat **is active** and a customer **clicks on a wp-admin link**, then **open it in new tab**.
- [x] https://github.com/Automattic/wp-calypso/issues/50271 Add the FAB icon in wp-admin, linking to wordpress.com/help **in a new tab**
- [x] Notify folks at paYJgx-1nM-p2 (specifically @jordesign) and request some testing is undertaken.

**Comment by mrfoxtalbot** [comment]
I am reopening this since the FAUX FAB needs to be repositioned to prevent it from overlapping with the community translation icon, as seen below:

![Community-translate-faux-fab](https://user-images.githubusercontent.com/4452464/111011057-8e43ae80-8398-11eb-8f61-89131a285d8d.gif)

In case it is not clear, I am referring to this:

![Screen Shot on 2021-03-13 at 01:08:59](https://user-images.githubusercontent.com/4452464/111011112-baf7c600-8398-11eb-8f78-c0226f711ae1.png)

**Comment by cpapazoglou** [comment]
I am going to move the Translator Button to the top of the FAB like it happens in Calypso
![](https://cln.sh/BxE6KV+)

**Comment by cpapazoglou** [comment]
WIP here D58793-code

**Comment by mrfoxtalbot** [comment]
Ok, I have a new one. We need to make sure that the FAUX WP-Admin FAB is placed to the LEFT on RTL sites. Currently it sits on top of the menu itself:

![Screen Shot on 2021-03-26 at 16:15:21](https://user-images.githubusercontent.com/4452464/112653306-926ad400-8e4e-11eb-9352-261ac485256f.png)

CCing @cpapazoglou and @mmtr to avoid this slipping through the cracks, since the issue was already open and taken care of (and a merge was in place). Thank you!

**Comment by cpapazoglou** [comment]
> Ok, I have a new one. We need to make sure that the FAUX WP-Admin FAB is placed to the LEFT on RTL sites. Currently it sits on top of the menu itself:
> 
> ![Screen Shot on 2021-03-26 at 16:15:21](https://user-images.githubusercontent.com/4452464/112653306-926ad400-8e4e-11eb-9352-261ac485256f.png)
> 
> CCing @cpapazoglou and @mmtr to avoid this slipping through the cracks, since the issue was already open and taken care of (and a merge was in place). Thank you!

This should be now handled correctly

![](https://cln.sh/lH3vCg+)
