### ISSUE TITLE
[EPIC] Jetpack and Nav Unification v1 prelaunch flow fixes

### ISSUE THREAD

**Issue by getdave** [Automattic/wp-calypso#50225]
The following are a set of "quick fixes" that will fix the flows for Jetpack connected sites for Nav Unification.

Given the other work that is happening simultaneously, there is no guarantee these will be fixable in time for launch. Therefore if they are unable to be completed, then a fallback will be to completely disable Nav Unification for Jetpack connected sites at the point of launch.

More context at p1HpG7-bcl-p2.

## Preferred route: Fix the flows

To quote @folletto the aim of the changes is...

> [i]n short: any flow that starts in WP Admin should end in WP Admin, any flow that starts in Calypso should end in Calypso. If no other way it’s possible, the switch should be explicit.

(see: p1HpG7-bcl-p2#comment-44627).

### Guiding principles

- From Calypso Blue (.com), a link to WP Admin that:
  - has a .com equivalent, should be changed to that.
  - has only a WP Admin equivalent, should have an explicit label (maybe even with the external link icon), so the user knows it’s going outside.
- From WP Admin, a link to .com that:
  - has a WP Admin or Calypso Green equivalent, should be changed to that.
  - has only a .com page, should still link to that, but find a label that says so explicitly (maybe even with the external link icon), so the user knows it’s going outside.

### Changes required

Our changes should be as follows. I would recommend these are broken up into their own Issues (update checkboxes with link) and close each one-by-one so we can have a record of where each point has been addressed:

#### From Calypso
- [x] **[Ajax]** Update `Jetpack_Admin_Menu` so we don’t return more items that the ones currently present in the existing navigation. https://github.com/Automattic/jetpack/pull/18921
- [x] **[Ajax]** Make sure all links point to Calypso (regardless of the link destination toggle). https://github.com/Automattic/jetpack/pull/18921
- [x] **[Ajax]** Ensure `Import`, `Export`, `Feedback`, and `WP Admin` links open in new tab and present an "external" icon. These are exceptions to the rule because they will be linking to WP Admin pages because there is no Calypso equivalent. https://github.com/Automattic/wp-calypso/pull/50444
- [x] **[Ajax]** Fix static fallback to remove items that have been removed from the API response. Tidy up job! https://github.com/Automattic/wp-calypso/pull/50522

#### From WPAdmin

See p1HpG7-bcl-p2#comment-44716. Please note that Nav Unification has not caused any regressions here. This is simply an update that has become necessary as a result of the paradigm shift in the way we view the relationship between Calypso and WPAdmin introduced by Nav Unification.

- [x] **[Jetpack team]** Calypso Add New Post - takes to WP Admin. Should stay in Calypso (also there seems to be a problem requiring logins there?).
- [x] **[Jetpack team]** WP Admin Setup Checklist - navigates to Calypso. We should probably remove that and provide just a link to the Assistant.
- [ ] **[Jetpack team]** WP Admin Backup Credentials — takes to Calypso Blue. This could go to Calypso Green instead.
- [x] **[Jetpack team]** WP Admin Configure Notification - notification settings, also in new tab (should not).
- [ ] **[Jetpack team]** WP Admin Backup & Scan Nav -  should open Calypso Green (cloud.jetpack.com/backup).

## Fallback: disable Nav Unification for launch

In the case that we cannot implement the above fixes in time for launch then we should fallback to...

- [ ] Disable Nav Unification and use old (existing) "Calypso style menu" on Jetpack connected sites (needs to happen in Calypso repo).

## Screenshots

This screenshot should be useful context

<img width="400" alt="Screen Shot 2021-02-18 at 11 49 44" src="https://user-images.githubusercontent.com/444434/108352927-6e78fa80-71df-11eb-9d1b-262047520169.png">

**Comment by obenland** [comment]
@folletto @rcoll When you get a chance, could you review the list of tasks tagged `[Jetpack team]` and check off the ones that are done? 

/cc @getdave

**Comment by ebinnion** [comment]
Changing the checklist button link is handled in Automattic/jetpack#18843

**Comment by ebinnion** [comment]
This PR directly above should address the monitor notifications settings.

For the items that mention Calypso Green vs Calypso Blue, those are handled via our redirects system, so can handle via a WPCOM commit.

For the Calypso Add New Post task, I'm not sure that we can get to that. I'm not sure that we can get that handled before the launch, nor that we're the best placed to handle it. What's happening there, I believe, is that Calypso is trying to log the user in to their remote site via SSO so that we can then iFrame the editor in Calypso. This was built quite a while back when Atomic was launching. In the reported issue, I believe that SSO was likely not enabled. 

To fix this correctly, we would probably want to build something like magic login for Jetpack sites and then use that instead. But, realistically, I don't think that we could prioritize in the near term. Definitely not before the launch of nav unification in a few weeks.

**Comment by folletto** [comment]
Yes I confirm the list above is the initial one I wrote with the fixes. 
I can't tho check items myself as I'm not directly fixing them, but Eric and Rich can follow up as soon as these get done. Thanks you both! 👍

**Comment by getdave** [comment]
Ajax will go through the Ajax items shortly and make sure we close any that have been completed. 

However, due to the Jetpack 9.5 code freeze having now past (on Monday) we'll have to make a call on what we can/can't fix via other means (ie: WPCOMSH) and then decide whether we can/can't include Jetpack connected sites in Nav Unification v1 launch.

My gut instinct is that it's unlikely. I don't have confidence that JP support are happy it provides a good enough UX for all the edge cases yet.

**Comment by monsieur-z** [comment]
This patch D57273-code from @rcoll fixes the _WP Admin Backup Credentials_ (along with Scan creds) and _WP Admin Backup & Scan Nav_ items.

**Comment by getdave** [comment]
@monsieur-z That looks positive. Would you be able to check off the items under https://github.com/Automattic/wp-calypso/issues/50225 that this addresses? Thank you.

**Comment by monsieur-z** [comment]
> Would you be able to check off the items under #50225 that this addresses?

Should we wait for the patch to be deployed, @getdave?

**Comment by getdave** [comment]
> > Would you be able to check off the items under #50225 that this addresses?
> 
> Should we wait for the patch to be deployed, @getdave?

Yes please. Is it landing soon?

**Comment by monsieur-z** [comment]
> Yes please. Is it landing soon?

It will shortly: p1HpG7-blf-p2

**Comment by mmtr** [comment]
I see D57273-code has been reverted in r221904-wpcom. I created separated issues for the remaining tasks (https://github.com/Automattic/jetpack/issues/18975, https://github.com/Automattic/jetpack/issues/18976), so we can close this epic out.
