### ISSUE TITLE
Site Editor: Global Styles are not persisted on WP.com

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#50358]
The saving flow for Global Styles is not working properly now on Dotcom. The preview in editor works fine but there are two potentially related issues when you attempt to update/save the changes:

- [x] The editor styles are completely reset including theme styles. It reverts to white background etc. (WordPress/gutenberg#30888)
- [x] The style changes are not reflected on front end, and default theme styles are rendered instead. (WordPress/gutenberg#30888)
- [x] Global styles don't work properly in the Site Editor on Atomic sites (https://github.com/Automattic/wp-calypso/issues/50953)
- [x] Verify WordPress/gutenberg#30888 fix is working on WPCOM after plugin is updated.

Similar already reported issues that probably have the same root cause:
- [x] https://github.com/Automattic/wp-calypso/issues/50556, 
- [x] https://github.com/Automattic/wp-calypso/issues/50575, 
- [x] https://github.com/Automattic/wp-calypso/issues/50289

P2 comment with context of what might be causing the problem: paYE8P-Km-p2#comment-627

**Comment by vindl** [comment]
There is some more context about what might be going on here: paYE8P-Km-p2#comment-627

**Comment by autumnfjeld** [comment]
Some points of investigation from Ganon estimation discussion:
- Could jetpack be the culprit
- Could public-api manipulation be the culprit
- Changes to 3rd party cookie requests
- Custom post types 
- Start with tracing data

Start with at least Size M due to unknowns/need to investigate.

**Comment by simison** [comment]
Related convo in paYE8P-PE-p2

**Comment by p-jackson** [comment]
> p-jackson added the [Status] Blocked / Hold label

Waiting for more discussion on paYE8P-PE-p2

**Comment by simison** [comment]
PR: https://github.com/WordPress/gutenberg/pull/30888

**Comment by p-jackson** [comment]
WordPress/gutenberg#30888 has merged, we just need to verify the bug has been fixed once the GB plugin is updated on wpcom

**Comment by p-jackson** [comment]
> - [x] Verify WordPress/gutenberg#30888 fix is working on WPCOM after plugin is updated.

Verified, thanks @vindl! pbAok1-26m-p2#comment-4407
