### ISSUE TITLE
Store|Woo: Deploy wc-calypso-bridge/wpcomsh updates necessary for Store removal

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#50353]
Before we remove Store (see pbIJXs-sE-p2 for more info), we need to deploy wc-calypso-bridge/wpcomsh updates so that those fixes are available:

- https://github.com/Automattic/wc-calypso-bridge/pull/651

## Tasks

- [x] Tag release on `wc-calypso-bridge` (see P90Yrv-219-p2) https://github.com/Automattic/wc-calypso-bridge/pull/653
- [x] Update `wc-calypso-bridge` version in `wpcomsh` 612-gh-Automattic/wpcomsh
- [x] Deploy new release of `wpcomsh` (see documentation in that repo)

**Comment by mattsherman** [comment]
Everything has been Done.
