### ISSUE TITLE
Store|Woo: Move `client/extensions/woocommerce/components/text-control` out of `client/extensions/woocommerce`

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wp-calypso#50809]
Part of the Sunset Store project. See pbIJXs-sE-p2 for more details.

Now that Store has been removed from the user experience on WordPress.com (pbIJXs-Hj-p2), we should start removing unused code. Ideally, we will eventually get rid of `client/extensions/woocommerce` entirely. However, there are some files that are used elsewhere. We should move those out of `client/extensions/woocommerce`.

## Tasks

- [ ] Move `client/extensions/woocommerce/components/text-control` to `client/components`
- [ ] Update [places where this component is used](https://github.com/Automattic/wp-calypso/search?q=%22woocommerce%2Fcomponents%2Ftext-control%22) to point to the new path (these are all part of Jetpack Connect)
    - [ ] `client/blocks/signup-form/style.scss`
    - [ ] `client/login/wp-login/style.scss`
    - [ ] `client/blocks/login/login-form.jsx`
    - [ ] `client/blocks/signup-form/index.jsx`

## Dev tips

- When you connect WooCommerce to WordPress.com, to trigger the Jetpack Connect UI, replace `https://wordpress.com/` with `http://calypso.localhost:3000/` in the Jetpack Connect URL.

**Comment by simison** [comment]
> When you connect WooCommerce to WordPress.com, to trigger the Jetpack Connect UI, replace https://wordpress.com/ with http://calypso.localhost:3000/ in the Jetpack Connect URL.

You can also load Jetpack wp-admin screen with `&calypso_env=local` (or was it `=development`, worth checking with Jetpack Crew team) URL param and it'll open all connection links correctly.
