### ISSUE TITLE
GuidedTours: add a site preview step

### ISSUE THREAD

**Issue by lsinger** [Automattic/wp-calypso#5120]
In the [GuidedTours milestone M2](https://github.com/Automattic/wp-calypso/milestones/GuidedTours%20M2:%20Preview%20&%20Polish), we'd like to add a step that shows the user how to preview their site. 

Open tasks:

- [x] add the `preview` layoutFocus for `DesignPreview` (see #4690)
- [x] change CurrentSite in sidebar so that it opens the DesignPreview (see #5117)
- [ ] add a GuidedTours step that introduces site preview (see #5553)
