### ISSUE TITLE
Focused Launch: re-add e2e tests for free flow

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#51270]
**Update**: Focused launch e2e tests were removed in https://github.com/Automattic/wp-calypso/pull/55995
___
**What**
Add e2e tests for Focused Launch flow

**Why**
Focused Launch is now rolled out for `/new` users and AnchorFM flow.

**A/C**
- [ ] Re-add e2e tests code (removed as part of https://github.com/Automattic/wp-calypso/issues/53118)
- [x] Cover with E2E tests the Free Launch flow for a site with Free plan. See 1st Critical flow in https://github.com/Automattic/wp-calypso/issues/46943#issuecomment-779895421
- [ ] Add `@parallel` tag in the suite name so the E2E test is picked up by TeamCity
- [ ] Replace `driverHelper.waitTillPresentAndDisplayed` function that no longer exists (see #51506)

**Context** for the last two A/C: https://github.com/Automattic/wp-calypso/pull/51842#issuecomment-828951044

**Comment by razvanpapadopol** [comment]
Re-opened since the test needs some more tweaking: https://github.com/Automattic/wp-calypso/pull/51842#issuecomment-828951044
Also updated A/C

**Comment by razvanpapadopol** [comment]
@yansern, do you want to work on the follow-up to enable the test or we take it to the Signup Pod?

**Comment by yansern** [comment]
> @yansern, do you want to work on the follow-up to enable the test or we take it to the Signup Pod?

Take it to the signup pod! TQVM! :)
