### ISSUE TITLE
🚧. Welcome Tour mobile version 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#52280]
## 🚧. Task Details WIP
The Welcome Tour was shipped as desktop only, now we want to develop the mobile version.   
Currently design is stretched very thin, so to move forward without formal design we propose to create a tech prototype and iterate over a working version with @ollierozdarz  to get to a shippable mobile version.

**Initial tasks**
- [ ] Spike using the nux modal with the welcome tour gifs, and then trying to make any look/feel improvements. This is probably a better approach that using the actual Welcome Tour, which isn't well suited for a mobile device (particularly a phone)
- [ ] Create project thread
- [ ] Identify breakpoints for the Welcome Tour vs modified NUX modal 
- [ ] Get new graphics or determine if existing graphics are sufficient
- [ ] Confirm it will not be minimizeble

### Related to
[Prior Welcome Tour work](https://github.com/orgs/Automattic/projects/147?card_filter_query=welcome+tour#card-42963912)
[Project thread for desktop version](pbAok1-1Dh-p2)

**Comment by razvanpapadopol** [comment]
### Aug, 26 Update

This is the current state of the NUX modal on mobile:

<img width="200" alt="Screenshot 2021-08-26 at 10 53 45" src="https://user-images.githubusercontent.com/14192054/130925373-0e5a2ddc-db28-4222-9989-7d4c94aeb316.png">

- modal header that includes the _Close_ button has no background
- image is not displayed
- footer is not accessible 

Tested on:
- MacOS, Chrome, with mobile resolution and cleared local storage
- Android, Chrome
- iOS, Safari

**Comment by razvanpapadopol** [comment]
### Aug, 30 Update

All the previous issues are now fixed by using the new welcome tour also on mobile (#55791) and by displaying the overlay control buttons all the time on mobile resolutions (#55754). 

<img width="319" alt="Screenshot 2021-08-30 at 11 38 39" src="https://user-images.githubusercontent.com/14192054/131312635-1efc62ab-1f12-4631-aa12-bfba4e4887a6.png">

After further discussion and testing ( p1629899413074600-slack-C029WSAQMT9 ), additional issues were created:
* Instructional graphics adapted for mobile UI: https://github.com/Automattic/wp-calypso/issues/55826
* Overlay controls hidden on large touch devices: https://github.com/Automattic/wp-calypso/issues/55821

**Comment by simison** [comment]
Thanks Razvan 👍  I think we can close this issue while we have https://github.com/Automattic/wp-calypso/issues/55826

**Comment by razvanpapadopol** [comment]
Thanks, @simison! Yes, that's correct. The only thing left will be to clean up the old tour previously used on mobile.
