### ISSUE TITLE
Blank Canvas in /new Design Picker: Create Tracking Events

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [Automattic/wp-calypso#52289]
### What
We need to add tracking events to identify a site that has been creating using Blank Canvas.

### Why
In order to keep track of everything track of everything around the blank canvas.

### A/C
* [x] `calypso_newsite_complete` should include `is_blank_canvas` prop 
* [x] `calypso_signup_complete` should include `is_blank_canvas` prop 
* [x] Update the event as described above when fired in both `/new` and `/start` onboarding flows
* [x] `is_blank_canvas` is added to the `calypso_signup_complete` config  [in the Tracks Events Registration repo](https://github.com/Automattic/tracks-events-registration/blob/master/events/calypso_signup_complete.event.json).
* [ ] All dashboards/tracking pages are configured. Share new funnels on Project Thread

### Open Work

There has been some good progress in #52388, but needs to be picked up

**Comment by StefanNieuwenhuis** [comment]
Don't forget that we have to register the prop [in the Tracks Events Registration repo](https://github.com/Automattic/tracks-events-registration/).

**Comment by autumnfjeld** [comment]
@razvanpapadopol  Does this still need work? It seems like a great task for our new Ganon devs.  😄

**Comment by razvanpapadopol** [comment]
@autumnfjeld, thanks for checking this out. There has been some good progress in https://github.com/Automattic/wp-calypso/pull/52388 but it definitely needs a rebase and a re-check of the acceptance criteria. I agree it can be a good opportunity to play around with Tracks debugging.

**Comment by autumnfjeld** [comment]
@Automattic/ganon Let's prioritize this work, see above comment on picking up work in PR 52338.  Even though we are going to deprecate /new soon, collecting this data will be valuable for referencing how Blank Canvas was selected by users.

**Comment by fushar** [comment]
@autumnfjeld Sure, I'll pick this up 😄

**Comment by fushar** [comment]
@autumnfjeld: we have shipped https://github.com/Automattic/wp-calypso/pull/52388.

Re: this AC

> All dashboards/tracking pages are configured. Share new funnels on Project Thread

Is this still relevant? I don't have context on this, could you share the Project Thread? cc: @StefanNieuwenhuis @razvanpapadopol

**Comment by razvanpapadopol** [comment]
Hi @fushar and thanks for pushing this over the finish line 🏁 👏🏼 
There was a PT (pbAok1-27t-p2) and also spec (pbAok1-28z-p2) for this project but they weren't updated in a long time. 
Probably the FG documentation is more important at this point: PCYsg-DdX-p2

**Comment by fushar** [comment]
Cool, thanks @razvanpapadopol!

Hmm @autumnfjeld, it seems that according to the linked PT, this whole thing is not necessary now as we have already rolled out blank canvas to 100% users? What do you think?

**Comment by autumnfjeld** [comment]
@fushar Adding tracking events is not to measure a before/after with regards to that PT.  Instead we're just wanting to observe how many users pick Blank Canvas vs other themes when they go through the /new site creation flow.  

In general we hope that we present interesting themes for the user, so if a significant number of users are picking blank canvas instead of one of the offered themes, we know we need to do some additional digging to understand why.  We then are also interested in knowing if users who pick blank canvas are more or less successful in using WordPress. For example, what happens after user creates a site?  Do they return and edit their site frequently? Do they launch their site? Do users who pick Blank Canvas take longer to launch their site? Do they have visitors to their site 1 or 2 or 3 months later?  

Some interesting discussion:
p58i-asN-p2
p9Jlb4-2qt-p2
p9Jlb4-2qt-p2
many various opinions on blank canvas
