### ISSUE TITLE
Template Editor Tracking

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#52571]
Let's make sure we have Tracking for the Template Editor that will be available from in the Gutenberg Plugin from 10.5.2 onward.

- [ ] Clicks on any of the UI.
- [ ] Templates created via UI.
- [ ] Ability to filter block usage by templates created via UI.
- [ ] Publish/edit stats for templates created via UI.
- [ ] Ability to filter sites in stats that have created templates using the UI.

**Note:** this refers to the Template Editor UI available in the Page Editor. **Not the Site Editor**.

See screeshot of the early in-progress UI:

![image](https://user-images.githubusercontent.com/545779/117036149-c1d0f400-acca-11eb-99d2-5f14fa170628.png)

**Comment by vindl** [comment]
Just a follow-up note that this will be hidden on Simple sites and WoA for now, most likely until it lands in core.
