### ISSUE TITLE
 Onboarding checklist on atomic sites: Edit the Site Menu

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#52706]
### Task Details

On Atomic sites, the _Edit the Site Menu_ task is not being marked as completed even after the site menu has been edited.

Anchor.fm sites should start with the menu already marked as set up, I haven't tested if this is working or not on atomic.

- [x] _Edit the Site Menu_ is marked as complete after editing the items in a menu on atomic sites
- [x] _Edit the Site Menu_ is always marked as complete on Atomic Anchor.fm sites
- [x] _Edit the Site Menu_ is marked as complete after removing items from a menu on atomic sites
- [x] _Edit the site Menu_ is marked as complete after changing where a menu is displayed on atomic sites

### More Info

I noticed that when a simple site's menu is updated, the `customizer_value_updated` function in `wp-content/lib/onboarding-checklist/blog.php` is called, this calls `mark_task_complete( 'site_menu_updated' )`. For Atomic sites, the `customizer_value_updated` is not called when a sites menu is updated.

### How to test

in the wpcom codebase, in `wp-content/lib/onboarding-checklist/functions.php`, modify the `is_blog_eligible_for_dotcom_checklist` to return `true`;

Open the customizer link from the _Edit the Site Menu_ task
Add an item to the primary menu
Save your changes
This should have caused the _Edit the Site Menu_  task to be marked as completed

Part of #50523

**Comment by roo2** [comment]
we think the implementation will be:

* intercept the `customize_save_after` action in the atomic site
* save the value in the site option for the `site_menu_updated` task.
* sync the site option back to the cloud site

**Comment by roo2** [comment]
sizing as small for assuming that we've done something similar for https://github.com/Automattic/wp-calypso/issues/52705

**Comment by autumnfjeld** [comment]
@deBhal working on this in D62307-code

**Comment by autumnfjeld** [comment]
@deBhal  Can this be moved to done?
D62307-code solves the atomic issue. Does it also satisfy the check on achor.fm sites (as described in the issue description above)?

**Comment by roo2** [comment]
I feel like the anchor.fm thing will be working, I'm trying to work out what I was talking about when I created this card and test it now.

**Comment by roo2** [comment]
The link for starting a wordpress.com blog from anchor.fm did not appear for me, but I was able to create a test site by copying testing instructions from here https://github.com/Automattic/wp-calypso/pull/48389

wordpress.com/new?anchor_podcast=5fa58048&anchor_episode=4e225062-9ead-fefb-a7b1-6a17dbf9e8d7

I updated the test site to be atomic and the "Edit the site menu" was still marked as completed as expected

**Comment by autumnfjeld** [comment]
@roo2 I'll. move this to done then!  😄

**Comment by roo2** [comment]
@p-jackson made the point that D62307-code only handles operations on menu-items and not on the entire menu

Cases where "edit the site menu" should be marked as completed but currently isn't( and I believe, is on simple sites ):

#### changing a menu's name
`jetpack_sync_updated_nav_menu`  captures this case well ✅ 


#### adding a new empty menu
 `wp_create_nav_menu` event captures this case well ✅ 

#### removing menu items
Could handle this by looking for `deleted_post_meta` event with the second argument being `_menu_item_object_id` or `_menu_item_object`. 🟡 

#### changing menu locations
We only get a `updated_option` event with `theme_mods_twentytwentyone` which seems to be a theme specific option name, I don't see an easy way to listen for this action ❌ 

I think that we should add code to handle those two cases that have clearly defined actions already being raised.

**Comment by roo2** [comment]
@deBhal has a diff to handle the other cases, I'll move this back to in progress for now D62739-code

**Comment by deBhal** [comment]
D62739-code is merged now, so I'm marking this compete.
