### ISSUE TITLE
Cleanup editor-site-launch

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/wp-calypso#53118]
**Task Details**

Latest mention in p58i-dox-p2#comment-56299

Cleanup editor Launch related code:
- [ ] ETK [editor-site-launch folder](https://github.com/Automattic/wp-calypso/tree/trunk/apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch) (#75037)
- [ ] ETK [typings](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/typings/index.d.ts) (#75037)
- [ ] ETK [common data-stores](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/index.ts) (#74551)
- [ ] `editor_site_launch` backend function - 29596-pb (including the exPlat code)
- [x] [Focused Launch e2e tests](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-focused-launch-spec.js)
- [ ] Remove also AnchorFM launch flow from editor (see p1621965288224700/1621458244.077600-slack-C0202PMUXLJ) and its support code in ETK and backend (29596-pb)

**Related to**
#53109;
follow up of https://github.com/Automattic/wp-calypso/pull/53115

**Comment by simison** [comment]
We will likely return to launch flow btw, just the button needs new placement.

**Comment by richtabor** [comment]
Closing this as its quite dated.
