### ISSUE TITLE
My Home (pre-launch): visual cleanup, reducing unneeded elements 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#53141]
### Overview
This is part of [My Home Pod short-term design improvements](pd2qGl-4i-p2)
pd2qGl-4i-p2#reducing-unneeded-elements
My Home: **pre-launch** visual cleanup, reducing unneeded elements 

![image](https://user-images.githubusercontent.com/5665959/120263101-651f2400-c2de-11eb-8650-ac42693008bc.png)

### Task List
- [x] Removing non-essential icons #53569 #53570
- [x] Rename the "Create a logo" quick link #53571
- [x] ~~Update name of "Contact support" link #53618~~ the mockups were created while that label was in an intermediary state, we're not actually changing it
- [x] Replacing extra line dividers with breathable white space #53619 #53565 _(<--- an a11y fix, but happens to tidy up one of the lines)_
- [x] Balancing the content column (left) with the sidebar (right). #53572 D62612-code
- [x] Giving the support section proper space so article titles aren’t cut off #53572 D62612-code
- [x] Removing the “site created” checklist task. We can jump right into the items to set the context properly https://github.com/Automattic/wp-calypso/issues/53138
- [x] Remove stats pre-launch, since this area does not contribute to getting the customer focused on editing and launching their site yet https://github.com/Automattic/wp-calypso/issues/52764
- [x] Improve padding in the "Go Mobile" feature card (as seen in Figma and mentioned here D62243-code#1282476) #53619
- [x] Clean up typography sizing #53619 

### Figma Designs
https://href.li/?https://www.figma.com/file/fLQcNzdadWzo87n89Imecj/?node-id=1763%3A0
Look for "Short term improvements - part 1"

### Related links
[My Home Project thread]( pd2qGl-17-p2)
[My Home: Short-term design improvements](pd2qGl-4i-p2)

### Dev Notes

**Comment by jeffgolenski** [comment]
**RE: mobile app card**

Per a convo with some of the mobile team, we'll most likely keep, but change the sub title on the small app card. Waiting to see what they feel is best to help market the app. pd2qGl-4i-p2#comment-191
