### ISSUE TITLE
My Home (post-launch): visual cleanup, reducing unneeded elements 

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#53178]
### Overview
This is part of [My Home Pod short-term design improvements](pd2qGl-4i-p2)
pd2qGl-4i-p2#reducing-unneeded-elements
My Home: **post-launch** visual cleanup, reducing unneeded elements 

![image](https://user-images.githubusercontent.com/5665959/120263287-bf1fe980-c2de-11eb-9385-9f6fbe278916.png)

Most of this ticket may come for free from work in the[ pre-launch ticket](https://github.com/Automattic/wp-calypso/issues/53141).  In which case this ticket is a quality check to make sure  post-launch matches the designs.

### Task List
- [x] Removing non-essential icons
- [x] Replacing extra line dividers with breathable white space
- [x] Balancing the content column (left) with the sidebar (right).
- [x] Giving the support section proper space so article titles aren’t cut off
- [x] Verify layout on tablet & mobile
- [x] Make padding on feature promo cards uniform with other cards
  - Reported in https://github.com/Automattic/wp-calypso/pull/53619#discussion_r654142166
  - #53927

### Figma Designs
https://href.li/?https://www.figma.com/file/fLQcNzdadWzo87n89Imecj/?node-id=1763%3A0
Look for "Short term improvements - part 1"

### Related links
[My Home Project thread]( pd2qGl-17-p2)
[My Home: Short-term design improvements](pd2qGl-4i-p2)

### Dev Notes

**Comment by p-jackson** [comment]
Far as I can tell all the work for this is also done in #53141 (there's nothing special in post-signup that needs doing)

**Comment by autumnfjeld** [comment]
@p-jackson  When the final PR for this is ready, or perhaps after the last PR is shipped, then let's flag with Jeff so he can have a look over to make sure we didn't miss anything.
