### ISSUE TITLE
Drop support for IE11 and multi-target builds

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#53222]
**Task Details**
We want to drop support for IE11. It will allow us to drop support for multi-target builds, simplifying our code and (in theory) making the build process faster.

### Drop support for IE 11:

* [x] Implement redirect to `/browsehappy` for fallback browsers (#53221)
* [x] Ensure that the production browsehappy page routes to Calypso instead of Atlas (done in pMz3w-dyS-p2)
* [x] Enable fallback redirect in production (#55142)
* [x] Revert fallback redirect (https://github.com/Automattic/wp-calypso/pull/55317)
* [x] Support calypso.live in desktop app CI (important for ensuring it doesn't break again) (https://github.com/Automattic/wp-calypso/pull/55323)
* [x] Implement a more secure redirect mechanism (https://github.com/Automattic/wp-calypso/pull/55402)
* [x] Make sure the desktop app is a supported browser (https://github.com/Automattic/wp-calypso/pull/55404)
* [x] Enable logging for the fallback page so that we know what % of requests we consider unsupported (https://github.com/Automattic/wp-calypso/pull/55732)
* [x] re-enable fallback redirect in production. (https://github.com/Automattic/wp-calypso/pull/55775)

### Drop support for multi-target builds:

* [x] Do not serve fallback build to redirected (unsupported) agents (#56029)
* [x] Remove `nomodule` redirect backup (done in #56029)
* [x] Do not build target `fallback` anymore (#53366)
* [x] https://github.com/Automattic/wp-calypso/pull/56198
* [x] https://github.com/Automattic/wp-calypso/pull/56195
* [x] https://github.com/Automattic/wp-calypso/pull/56127
* [ ] Rename target `evergreen` to something more sensible (eg: `app`)
* [ ] Drop references to "target build" or "fallback build"
* [ ] Remove fallback redirect environment feature flag

### Other Tasks
* [x] Delete the legacy browsehappy page from atlas (D65139-code)
* [ ] Make sure that when we redirect the desktop app to "unsupported browser" page, we show a more helpful message (like to update the app).
