### ISSUE TITLE
Full Site Editing: Stats (Tracking Issue)

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#53410]
**Task Details**
This issue will be to help track issues and PRs related to FSE stats tracking on dotcom.  pbAok1-2c4-p2

* [x] Add editor type to events tracking. #53411 (https://github.com/Automattic/wp-calypso/pull/53384)
* [x] Enable Undo/Redo tracking in Site Editor. #53412 (https://github.com/Automattic/wp-calypso/pull/53405) (https://github.com/Automattic/wp-calypso/pull/53733)
* [x] Fix `inserter_method` for inserting blocks through block inserter sidebar in Site Editor. https://github.com/Automattic/wp-calypso/issues/53414 (https://github.com/Automattic/wp-calypso/pull/53457)
* [x] Fix bug with undo/redo triggering block inserted track events when effected content is in Template Parts or Reusable Blocks. #53413 (https://github.com/Automattic/wp-calypso/pull/53501)
* [x] Extend the `editor_type` property to work with blocks widgets editors. (https://github.com/Automattic/wp-calypso/pull/53789)
* [x] Add events for Global styles in the site editor. paYE8P-V2-p2 (https://github.com/Automattic/wp-calypso/pull/53456) (https://github.com/Automattic/wp-calypso/pull/53801)
* [x] Stop inserter tab events from firing in global styles tabs. (https://github.com/Automattic/wp-calypso/pull/53788)
* [x] Add events for the navigation panel/sidebar in the site editor. (https://github.com/Automattic/wp-calypso/pull/53500 https://github.com/Automattic/wp-calypso/pull/53864)
* [x] Add events for selecting content items in the navigation sidebar. (https://github.com/Automattic/wp-calypso/pull/54385)
* [x] Track usage of the list view. (https://github.com/Automattic/wp-calypso/pull/53464)
* [x] Track selecting a block via list-view. (https://github.com/Automattic/wp-calypso/pull/54128)
* [x] Track template part convert/detach blocks actions. https://github.com/Automattic/wp-calypso/issues/53519 (https://github.com/Automattic/wp-calypso/pull/53592)
* [x] Explore tracking template part placeholder flows - creation & pattern selection vs. existing template part selection. (https://github.com/Automattic/wp-calypso/pull/54093)
* [x] Tracking template part replacement flow. (https://github.com/Automattic/wp-calypso/pull/54093)
* [x] Explore tracking context of block events within the site editor (template vs. template part vs. query vs. post content, etc.) (https://github.com/Automattic/wp-calypso/pull/54352)
* [x] Try generalizing tracking for block variations. (https://github.com/Automattic/wp-calypso/pull/53606) (https://github.com/Automattic/wp-calypso/pull/53667)
* [x] Try adding subscriber and capture systems for tracking. (https://github.com/Automattic/wp-calypso/pull/53598) (https://github.com/Automattic/wp-calypso/pull/53787)
* [x] (non-FSE) `from_template_selector` for block inserting events is `false` even when from template selector. https://github.com/Automattic/wp-calypso/issues/53637 (https://github.com/Automattic/wp-calypso/pull/53640)
* [x] add e2e test to verify `from_template_selector` prop works as expected. (https://github.com/Automattic/wp-calypso/pull/54074)
* [x] (non-FSE) Explore adding `pattern_category` property for the pattern inserted event. (https://github.com/Automattic/wp-calypso/pull/53492)
* [x] (non-FSE) Add tracking for 'details' button in header of post editor. (https://github.com/Automattic/wp-calypso/pull/53468)
* TBD...

Other found issues:
* Poor fidelity with `blocks_replaced` property - https://github.com/Automattic/wp-calypso/issues/53634
* Drag and drop event not tracking properly - https://github.com/Automattic/wp-calypso/issues/54353

Follow up TODOs:
* [x] Update E2E instructions here: PCYsg-nrf-p2 (https://github.com/Automattic/wp-calypso/pull/53384)
* [x] Create Site Editor Gutenberg Edge user (https://github.com/Automattic/wp-calypso/pull/53384)
* [x] Ensure all new events properties are registered & verified in tracks.
