### ISSUE TITLE
Playwright: turn on CI runs by default

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#53514]
**Task Details**
Currently, Playwright E2E tests do not run by default.

The best way to gauge the effectiveness of the migration is to run it as part of the issue life cycle. Maybe it can catch an issue or two while more tests are migrated, as well.

- [ ] create two tasks - mobile and desktop
- [ ] run both on TeamCity with a known baseline
- [ ] turn on by default

**Comment by worldomonation** [comment]
This is partially done for the following combination:

- desktop AND trunk

**Comment by worldomonation** [comment]
Recently there was an issue where change to the Themes page was proposed, implemented and merged to `trunk`.
This change broke Playwright E2E tests, but this was not detected due to the simple fact that Playwright tests do not currently run for feature branches by default.

As briefly discussed in p1626193579185500-slack-C01QG4Y91RR it appears we are reaching a point where enabling Playwright tests by default on features branches makes sense.

Tasks for this iteration:

- [ ] enable Playwright E2E for all branches
- [ ] remove Selenium counterparts that have been migrated to Playwright

**Comment by worldomonation** [comment]
Also look into turning on `mobile` variant, limited to `trunk` for now. 

- [ ] ensure #54569 is in good shape.
- [ ] add new configuration item for mobile Playwright tests.

**Comment by worldomonation** [comment]
Playwright is now turned on for all branches, for both mobile and desktop!

**Comment by worldomonation** [comment]
Closed via #55407.
