### ISSUE TITLE
Playwright: minor clean up and housekeeping.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#53556]
**Task Details**
A few things had been missed from previous code reviews that need to be addressed.

- [x] replace method name `login` with `logIn` to indicate action.
- [x] replace use of `assert.equals` with `assert.strictEqual`.
- [x] change selector used in `SidebarComponent` to restrict the how far it would match ([link](https://github.com/Automattic/wp-calypso/pull/53323#discussion_r648149864))

**Comment by worldomonation** [comment]
Last point is being addressed in #53566. First two points are addressed by #53568.
