### ISSUE TITLE
Search: enable Jetpack Search section in Jetpack Cloud

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#53689]
**Task Details**
Add the 'Search' menu item to Jetpack Cloud at `/jetpack-search`. This section will show the same information as Jetpack > Search in Calypso blue.

![image](https://user-images.githubusercontent.com/17325/121989901-ff0fc200-cdf0-11eb-9542-819071e43696.png)

Todo:
- [x] Handle the different way that search is toggled for Jetpack sites (module enabled/disabled)
- [x]  Fix 'flash of search is turned off' when actually enabled - show placeholder until we know
- [x] Handle missing site where we cannot access the API (currently just keep showing placeholder) - #54634

**Related to**
Some existing work towards this goal:

https://github.com/Automattic/wp-calypso/pull/53208
https://github.com/Automattic/wp-calypso/pull/53239
https://github.com/Automattic/wp-calypso/pull/53272
https://github.com/Automattic/wp-calypso/pull/53296
