### ISSUE TITLE
Playwright: explore playwright-test runner

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#53962]
**Task Details**
As of 1.12.0 Playwright ships with its [in-house test runner](https://playwright.dev/docs/test-intro). 

It offers many functionalities that I had to implement myself (as hooks or browser managers), so explore if this suits our needs.

Key objectives:
- [ ] Ensure TeamCity reporting works
- [ ] Investigate how much of the existing hooks and frameworks can be removed
- [ ] Is it any more reliable than Jest?

There are key features of Playwright test runner that are of interest to us:
- automatic instance and page management
- screenshot capture on test fail (configured via file)
- better video capture
- retry

The last point could be contentious as theoretically a test should be able to stand on its own, but our experience with Jest so far is showing that things may be flakier than expected even with Playwright.

**Related to**
Blocked by #53928 
Related to #53200

**Comment by worldomonation** [comment]
Discontinuing this task due to the migration to Jest.

**Comment by worldomonation** [comment]
Reopening issue.

@dpasque may be interested in exploring this avenue.

Updated original description as well.
