### ISSUE TITLE
My Home: Onboarding checklist task "Name your site" 

### ISSUE THREAD

**Issue by deBhal** [Automattic/wp-calypso#54273]
### Steps to reproduce the behavior

- Create a new non-english site, skipping the site name stage
- triggered Automatic Transfer
- go to `wordpress.com/home` for the new site
- Observe that the "Name your site" task is already marked complete

The task should not be completed with the default "Site Title" site name.

The logic for updating the task does check for the translation of "Site Title", but it looks like something in the Automated Transfer or Atomic logic path is bypassing or fouling up that check and marking the task as done anyway.

The automated transfer will trigger a whole slew of jetpack sync events that the new atomic logic in `\Onboarding_Checklist` watches, so that seems a likely place to start looking.

### Various situations where the "name your site" task needs to work

- [x] The user and blog lang match, but they're non-`en`. Fixed by #54440.
- [x] The user and blog lang don't match. Fixed by D63937-code.
- [ ] The user changes the site language after site creation. The site will have a title that no longer matches the blog lang and so the task will be incorrectly marked complete.
- [ ] The blog is on the atomic platform, which means `public-api` has no way of knowing what the blog lang is so can't make a correct comparison of site titles.
- [ ] The default title we're using for new sites is changed, which will incorrectly mark the task as complete for users who haven't changed the title from the default they were given at site creation time.

**Comment by p-jackson** [comment]
I'm reproducing this issue even without the AT 🤔

**Comment by p-jackson** [comment]
To decide whether the site's title has changed we compare the the current title with `__( 'Site Title' )`. There's potentially two issues happening here:

**Situation 1: the site language and user language match**
There's no translation available for "Site Title" https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=Site+Title
That's an easy fix. Once that term is translated in the `wpcom` project this should be fixed.

**Situation 2: the site language and user language don't match**
Comparing the site title against `__( 'Site Title' )` isn't the correct check because `__()` is going to use the user's language. We want to compare the current site title with "Site Title" translated into the site's language.

**Situation 3: the user changes the site's language**
Comparing the current site title with "Site Title" doesn't even seem like the correct check, because if the user changes the site's language after site creation then that'll cause the checklist task to be marked as done.

**Comment by p-jackson** [comment]
Situation 1 is fixed by #54440

I'm going to work on a fix for Situation 2, because I still think the logic is wrong if it's using user-language instead of site-language.

Situation 3 might be diminishing returns, so maybe I won't fix this. What do you think @autumnfjeld @deBhal

**Comment by p-jackson** [comment]
D63937-code addresses Situation 2 🤞

**Comment by p-jackson** [comment]
We've made improvements to this task, however we've also discovered other situations where the task logic doesn't work correctly. The My Home Pod doesn't have time to fix the other situations, but I've added them to the issue description and will pop this back in the backlog.

**Comment by jordesign** [comment]
Hey @p-jackson  - I'm just going through old issues. Feeling like this one can be closed given the stale-ness and the likelihood that My Home things are being handled differently?

If not - please feel free to pop back open.

**Comment by autumnfjeld** [comment]
Definitely can be closed. We are about to start this.
