### ISSUE TITLE
Tech Spike: My Home checklist "Edit the site menu" new user flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#54436]
### Background
Currently, when a user goes through the My Home site setup checklist, they are guided to edit a menu.  Clicking the CTA, shown in the pic below, takes the user to `wordpress.com/customize/menus/{site}`. Here, new users are shown a pop guide, as shown in the screenshots below.  The copy in this pop-up doesn't match the context the user is in, it doesn't match the edit a menu flow.  

See Showing the Customiser Guide During the Edit Menu Task: (pd2qGl-ar-p2) and comment on UX ideas (pd2qGl-ar-p2#comment-311).

![image](https://user-images.githubusercontent.com/5665959/125222098-b8888700-e30c-11eb-964a-8f4aaad64591.png)
![image](https://user-images.githubusercontent.com/5665959/125222112-c0e0c200-e30c-11eb-9888-d59468bab1c9.png)

### Proposed improvement
My brilliant visual design (😆 ):
![image](https://user-images.githubusercontent.com/5665959/125225806-38195480-e313-11eb-9606-51171d46f7ea.png)

This is for a new user experience, as the pop up is only shown when user visits the customizer for the first time

- [ ] In this My Home Edit a menu flow, Instead of landing the user on https://wordpress.com/customize/menus/{site}, we send them to https://wordpress.com/customize/{site}.  
- [ ] We conditionally check if they are coming from My Home>Edit a menu flow, if they are, then we show a pop-up with copy relevant to that experience (for now just use some placeholder copy), if they are coming from from any other flow (e.g. sidenav Appearance>Customize) show the existing copy, let's call this the default copy.
- [ ] Guide the user to click "Menus" (I think this can just be done with in the pop-up copy, but maybe also the pop-up left arrow should point to "Menus"

For now, don't worry about details around the flag that controls checking if this is a new user. Meaning we may need two flags if we put this in production, one for the default copy and one for the My Home menu flow.

**Track tech issues/questions that come up during spike:**
* issue 1

Once we have a working prototype, we can share to get further input.
@jeffgolenski if you have additional UX specs for this tech investigation, let us know. 

**While working on this, think about how we can answer these related questions**
* Can we create a similar educational flow for My Home>Name your site flow?  As discussed here https://github.com/Automattic/wp-calypso/issues/53434
* Can we have additional targeted pop-ups in the customizer such that the user gets a specific pop up depending on the flow they came from? So that we are targeting the context and providing better new user education.  Ideas presented here pd2qGl-ar-p2#comment-302

**Comment by roo2** [comment]
it looks like it is straightforward to implement a tour specific to editing the menus by passing something like `guide=edit-menu` in via the customizer url.

The link from the checklist takes us to the edit menus panel already now that https://github.com/Automattic/wp-calypso/pull/54345 is fixed, so we will need to come up with content that makes sense from the _menus_ panel.

<img width="1000" alt="Screen Shot 2021-07-13 at 10 49 42 am" src="https://user-images.githubusercontent.com/22446385/125373266-2b0a6d00-e3c8-11eb-8366-0c57e05e97c6.png">

**Comment by roo2** [comment]
> Can we create a similar educational flow for My Home>Name your site flow? As discussed in #53434

Yes ✅ it looks like we can hook into the same logic for this

> Can we have additional targeted pop-ups in the customizer such that the user gets a specific pop up depending on the flow they came from? So that we are targeting the context and providing better new user education. Ideas presented here

Yes ✅ The customizer has the `guide` parameter which can be set in the link that they followed and implemented on by adding logic to the switch statement here p1626061025312200/1626054191.306400-slack-C01VA0R5NKY

**Comment by roo2** [comment]
I was able to get a simple one step help guide working 
![edit-menus](https://user-images.githubusercontent.com/22446385/125445140-21366f4a-8c07-46df-a37e-de628005767f.gif)

A two step guide or anything more complicated didn't work so well though  pd2qGl-ar-p2#comment-316

**Comment by roo2** [comment]
Draft implementation saved in https://github.com/Automattic/wp-calypso/pull/54583 and D64107-code , I'll close this spike card
