### ISSUE TITLE
Migrate to `import/order`

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#54448]
**Task Details**

After some debate in p4TIVU-9Hd-p2, we have decided to change how to document our imports:

* Do not use `wpcalypso/import-docblock`
* Delete any existing `/** External dependencies **/` block comments and similar.
* Enable `import/order`

See the proof of concept in https://github.com/Automattic/wp-calypso/pull/52499

**Instructions**

1. Select a directory you want to refactor. For example, `packages/foo`
2. Add `packages/foo/**/*` to `.eslintrc`, to the override for `wpcalypso/import-docblock` section
3. Run `./bin/import-order.sh packages/foo`
4. Review the result and commit it.

As this is a massive task that will change almost every file in the repo, I think we should split it into smaller PRs based on folders. This is the list of packages (+ number of occurrences) we have converted so far. Feel free to split them if you think more granular PRs are needed:

* [x] `2579` ./client/state #55659
* [x] `1216 ./client/my-sites` (#55607)
* [x] ` 863 ./client/components` (#55224)
* [x] ` 490 ./client/lib` (#55200)
* [x] ` 315 ./client/blocks` (#55199)
* [x] ` 268 ./client/my-sites/customer-home` (#54746)
* [x] ` 251 ./test/e2e` (#54452)
* [x] ` 251 ./client/me` (#55190)
* [x] ` 164 ./client/extensions` (#55134)
* [x] ` 130 ./client/reader` (#55127)
* [x] ` 124 ./apps/editing-toolkit` (#54680)
* [x] `  97 ./packages/calypso-products` (#54485)
* [x] `  90 ./packages/data-stores` (#54486)
* [x] `  85 ./client/signup` (#55114)
* [x] `  84 ./client/landing` (#55033)
* [x] `  82 ./apps/notifications` (#54839)
* [x] `  79 ./client/layout` (#55100)
* [x] `  72 ./client/devdocs` (#55099)
* [x] `  64 ./client/jetpack-cloud` (#55098)
* [x] `  57 ./packages/wpcom.js` (#55000)
* [x] `  52 ./packages/composite-checkout` (#54539)
* [x] `  51 ./desktop/app` (#55094)
* [x] `  42 ./client/post-editor` (#55093)
* [x] `  38 ./packages/calypso-e2e` (#54542)
* [x] `  35 ./client/jetpack-connect` (#55092)
* [x] `  34 ./client/server` (#55091)
* [x] `  33 ./apps/wpcom-block-editor`(#55025)
* [x] `  33 ./packages.calypso-e2e` (#54550)
* [x] `  24 ./packages/wpcom-checkout` (#54579)
* [x] `  24 ./packages/launch` (#54580)
* [x] `  20 ./apps/o2-blocks` (#55024)
* [x] `  19 ./packages/plans-grid`(#54638)
* [x] `  19 ./packages/domain-picker` (#54640)
* [x] `  17 ./client/data` (#55022)
* [x] `  16 ./packages/shopping-cart` (#54742)
* [x] `  16 ./client/login` (#55018)
* [x] `  14 ./packages/explat-client` (#54879)
* [x] `  13 ./packages/design-picker` (#54915)
* [x] `  12 ./packages/browser-data-collector` (#54916)
* [x] `  10 ./packages/calypso-codemods` (#55012)
* [x] `   9 ./packages/i18n-calypso` (#55011)
* [x] `   9 ./packages/calypso-build` (#55009)
* [x] `   8 ./packages/page-pattern-modal` (#55008)
* [x] `   8 ./client/document` (#55007)
* [x] `   7 ./packages/wp-babel-makepot` (#54971)
* [x] `   7 ./packages/state-utils` (#54970)
* [x] `   6 ./packages/social-previews` (#54969)
* [x] `   6 ./packages/calypso-url` (#55015)
* [x] `   6 ./packages/calypso-analytics` (#54968)
* [x] `   6 ./client/gutenberg` (#54966)
* [x] `   5 ./packages/onboarding` (#54964)
* [x] `   5 ./packages/load-script` (#54963)
* [x] `   5 ./packages/i18n-calypso-cli` (#54962)
* [x] `   5 ./client/test-helpers` (#54961)
* [x] `   5 ./client/controller` (#54892)
* [x] `   4 ./packages/search` (#54887)
* [x] `   4 ./packages/i18n-utils` (#54888)
* [x] `   4 ./desktop/e2e` (#54955)
* [x] `   4 ./client/mailing-lists` (#54890)
* [x] `   4 ./client/boot` (#54893)
* [x] `   3 ./packages/webpack-inline-constant-exports-plugin` (#54891)
* [x] `   3 ./packages/popup-monitor` (#54882)
* [x] `   3 ./packages/languages` (#54836)
* [x] `   3 ./packages/language-picker` (#54802)
* [x] `   3 ./packages/eslint-plugin-wpcalypso` (#54837)
* [x] `   3 ./packages/calypso-polyfills` (#54884)
* [x] `   2 ./packages/wpcom-proxy-request` (#54835)
* [x] `   2 ./packages/whats-new` (#54798)
* [x] `   2 ./packages/viewport-react` (#54956)
* [x] `   2 ./packages/request-external-access` (#54957)
* [x] `   2 ./packages/photon` (#54834)
* [x] `   2 ./packages/format-currency` (#54799)
* [x] `   2 ./packages/explat-client-react-helpers` (#54883)
* [x] `   2 ./packages/babel-plugin-transform-wpcalypso-async` (#54958)
* [x] `   2 ./client/incoming-redirect` (#54838)
* [x] `   2 ./client/auth` (#54797)
* [x] `   1 ./test/server` (#54796)
* [x] `   1 ./test/client` (#54796)
* [x] `   1 ./packages/webpack-config-flag-plugin` (#54791)
* [x] `   1 ./packages/viewport` (#54605)
* [x] `   1 ./packages/tree-select` (#54604)
* [x] `   1 ./packages/spec-xunit-reporter` (#54602)
* [x] `   1 ./packages/spec-junit-reporter` (#54601)
* [x] `   1 ./packages/retarget-open-prs` (#54600)
* [x] `   1 ./packages/mocha-debug-reporter` (#54596)
* [x] `   1 ./packages/js-utils` (#54594)
* [x] `   1 ./packages/create-calypso-config` (#54593)
* [x] `   1 ./packages/calypso-stripe` (#54592)
* [x] `   1 ./packages/calypso-config` (#54590)
* [x] `   1 ./packages/babel-plugin-i18n-calypso` (#54589)
* [x] `   1 ./docs/modularized-state.md` (#55055)
* [x] `   1 ./docs/guide` (#55055)
* [x] `   1 ./desktop/webpack.config.js` (#54584)
* [x] `   1 ./client/webpack.config.node.js` (#54584)
* [x] `   1 ./client/webpack.config.js` (#54584)
* [x] `   1 ./client/webpack.config.desktop.js` (#54584)
* [x] `   1 ./client/types.ts` (#54546)
* [x] `   1 ./client/support` (#54545)
* [x] `   1 ./client/sections.js` (#54543)
* [x] `   1 ./client/sections-preloaders.js` (#54495)
* [x] `   1 ./client/sections-middleware.js` (#54494)
* [x] `   1 ./client/sections-helper.js` (#54492)
* [x] `   1 ./client/sections-filter.js`  (#54493)
* [x] `   1 ./client/root.js` (#54960)
* [x] `   1 ./client/notifications` (#54959)
