### ISSUE TITLE
Patterns: Add Link in Bio Patterns to Patterns/Page Selection

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wp-calypso#54458]
**Task Details**

- Add Blank Canvas Link in Bio Patterns to Dotcom Library.
- Surface in Pattern Inserter.
- Surface in New Page Modal.

**Notes**

Let's get this category of patterns surfaced for users of all themes, not just Blank Canvas, by moving them to the Dotcom Pattern library.

![image](https://user-images.githubusercontent.com/545779/125318098-28901080-e2ff-11eb-8e97-8f24fa5dff11.png)

And get them surfaced in the new page modal as well. (Could do with featuring the nicest of the bunch as well.)

![image](https://user-images.githubusercontent.com/545779/125318216-45c4df00-e2ff-11eb-8fd4-1a5b039a306f.png)

**Comment by apeatling** [comment]
@alaczek I don't believe any code is needed to move them to the selector for patterns. They needed to be added to the dotcom patterns source site and a new category added for "Link in Bio". They should then show up after the cache is cleared.

Not sure about the page modal, but let's get them in the sidebar first.

**Comment by alaczek** [comment]
Yep, I can do both of those things, no engineering power needed :)

> Add Blank Canvas Link in Bio Patterns to Dotcom Library.

Most of them are added, they are sitting under the "About" category in Pattern inserter. We discussed it together a while back and we evaluated all the patterns and decided to leave out a couple (the colorful hamburger one was one of them). Shall I go back and add everything? Also, shall I move them to the "Link in Bio" category so that they are easier to discover?

**Comment by ianstewart** [comment]
Let's add the lot. Moving them up to a link in bio should help with categorization. And then we can evaluate the usage later.

**Comment by alaczek** [comment]
Alrighty!

- [x] Add Blank Canvas Link in Bio Patterns to Dotcom Library.
- [x] Surface in Pattern Inserter. (I assume this will happens automatically when I add them.)
- [x] Surface in New Page Modal. (Tagged them all as Layouts, that should do it.)

It is all done. Just noting that if the active theme is Blank Canvas, all the patterns in Link in Bio category are now doubled. This issue is being tackled 273-gh-view-design
