### ISSUE TITLE
Full Site Editing: Theme switching flows

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54462]
Update the theme switching flows according to paYE8P-ZP-p2.

Remaining tasks

- [x] Remove the keep/replace content modal when switching themes for FSE Beta sites (moved to https://github.com/Automattic/wp-calypso/issues/56872)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/132927910-e9ca4e19-eb87-43d9-98ac-42666cfd3853.png">

For universal themes, should they always skip this modal, or only for FSE Beta sites? Needs further testing

- [x] Update the after theme switch modal primary button for FSE Beta sites to always say "Edit site" or "Design your site" and link to the Site Editor, rather than the Customizer or page editor (moved to https://github.com/Automattic/wp-calypso/issues/56873)

<img width="303" alt="image" src="https://user-images.githubusercontent.com/1699996/132928110-e675de1f-740d-46a8-b923-fa896f8daaf0.png">

- [x] Update the "Full Site Editing" tab in the Themes showcase to show based on the blog sticker `core-site-editor-enabled`, so this tab always shows for sites enrolled in the beta (moved to https://github.com/Automattic/wp-calypso/issues/56854)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/132928453-c260ea48-09d1-4ea3-831b-defe739a1411.png">

- [x] Resolve the discussion about if we need to offer a beta opt-out upon theme switch, and if so, how that will work (see paYE8P-10U-p2)

- [x] The above will require surfacing the Beta opt-in status of a site in the REST API, which should include creating a library function for checking this status (e.g. `A8C\FSE\is_core_fse_eligible`) (moved to https://github.com/Automattic/wp-calypso/issues/56373)

**Comment by creativecoder** [comment]
Looking at the FSE Beta flow chart and cross referencing the tasks in other issues like #54508, I'm seeing the following tasks remaining for this issue

- [ ] Remove the keep/replace content modal when switching themes for FSE Beta sites

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/132927910-e9ca4e19-eb87-43d9-98ac-42666cfd3853.png">

For universal themes, should they always skip this modal, or only for FSE Beta sites? Needs further testing

- [ ] Update the after theme switch modal primary button for FSE Beta sites to always say "Edit site" or "Design your site" and link to the Site Editor, rather than the Customizer or page editor

<img width="303" alt="image" src="https://user-images.githubusercontent.com/1699996/132928110-e675de1f-740d-46a8-b923-fa896f8daaf0.png">

- [ ] Update the "Full Site Editing" tab in the Themes showcase to show based on the blog sticker `core-site-editor-enabled`, so this tab always shows for sites enrolled in the beta

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1699996/132928453-c260ea48-09d1-4ea3-831b-defe739a1411.png">

- [ ] Resolve the discussion about if we need to offer a beta opt-out upon theme switch, and if so, how that will work (see paYE8P-10U-p2)

- [ ] The above will require surfacing the Beta opt-in status of a site in the REST API, which should include creating a library function for checking this status (e.g. `A8C\FSE\is_core_fse_eligible`)

I'll add more details about each of these as I have them, and start in on PRs next week.'

**Comment by creativecoder** [comment]
> The above will require surfacing the Beta opt-in status of a site in the REST API, which should include creating a library function for checking this status (e.g. A8C\FSE\is_core_fse_eligible)

Note that I've broken out a separate issue for this item, as there are a number of related tasks: https://github.com/Automattic/wp-calypso/issues/56373

**Comment by vindl** [comment]
> Update the "Full Site Editing" tab in the Themes showcase to show based on the blog sticker core-site-editor-enabled, so this tab always shows for sites enrolled in the beta

This is now being tracked separately in https://github.com/Automattic/wp-calypso/issues/56854.

**Comment by vindl** [comment]
> Resolve the discussion about if we need to offer a beta opt-out upon theme switch, and if so, how that will work (see paYE8P-10U-p2)

Marked this as done since we've reached an agreement in the P2 post.

**Comment by vindl** [comment]
I've moved the remaining tasks into separate issues. Not all of them are necessarily blockers so it's better to track them individually.
