### ISSUE TITLE
Full Site Editing: Support universal themes (Tracking Issue)

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54469]
Universal themes can disable the Site Editor via site option.

Let's use this option in the site creation flow:
- If the site is **not** FSE, turn the option on (and disable the Site Editor).
- Otherwise, leave the option off.

Tasks:
- [x] Site option to disable the Site Editor: https://github.com/Automattic/themes/pull/4154
- [x] Disable the Site Editor by default on simple sites: https://github.com/Automattic/themes/pull/4206
- [x] Atomic sites
- [x] Jetpack sites
- [ ] Enable the Site Editor on sites opted-in to the Dotcom FSE Beta.

**Comment by mattwiebe** [comment]
Note that #54620 will introduce a toggle, via ETK, to supersede the in-Blockbase toggle. This will also allow us to take account of Atomic immediately since ETK is distributed there. Here are the remaining tasks that would be needed to complete that:

- [x] Revert Automattic/themes#4154 → Automattic/themes#4340
- [x] Deactivate `pub/tt1-blocks` ([See discussion](https://github.com/Automattic/wp-calypso/pull/54576#issuecomment-881019059)) #55176
- [x] Allowlist `wpcom_is_fse_activated` option for Atomic transfers D64657-code
- [x] Allowlist `wpcom_is_fse_activated` option for Jetpack Sync D64660-code
- [x] Update `is_core_site_editor_enabled` on `/site(s)` endpoints to account for new option (can use `\A8C\FSE\is_core_fse_active()` for the right value. D65143-code

**Comment by mattwiebe** [comment]
This is pretty much finished. There's ongoing work related to it in D67076-code but Universal Themes are launched and in the wild 🎉 🙌
