### ISSUE TITLE
Full Site Editing on Dotcom: Improve themes flows (Tracking Issue)

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54508]
## Description
FSE has been available on Atomic for months, by simply activating a block-based theme.
With the accelerating release of [block-based themes on WordPress.org](https://en-gb.wordpress.org/themes/tags/full-site-editing/), more users will enable FSE on their sites, in some case accidentally.

There are a few flows that we can improve and simplify to make clear that the feature is still experimental.
These issues will make the experience better for Atomic FSE sites now, but will also eventually benefit _all_ FSE sites in the beta.

## Main Tasks
- [x] Restore the [Beta] label to the Site Editor menu item in the navigation sidebar: https://github.com/Automattic/wp-calypso/issues/54464 @david-szabo97 
- [x] Add a [Beta] label to block-based themes (tagged with `full-site-editing`) in the theme showcase (see first screenshot below). @david-szabo97 #54706
  - [x] Follow-up: Show beta badge in the "current theme" banner ([context](https://github.com/Automattic/wp-calypso/pull/54706#pullrequestreview-718272702)) https://github.com/Automattic/wp-calypso/pull/56123
  - [x] Follow-up: Show beta badge in theme info screen ([context](https://github.com/Automattic/wp-calypso/pull/54706#pullrequestreview-718272702)) https://github.com/Automattic/wp-calypso/pull/56225
  - [x] Follow-up: Only show beta badges when sites are FSE eligible  ([context](https://github.com/Automattic/wp-calypso/pull/56123#discussion_r709392712)) https://github.com/Automattic/wp-calypso/issues/56854
- [x] When activating/deactivating an FSE theme, the sidebar requires a full refresh to toggle the Site Editor and Customizer items. (see [example](https://github.com/Automattic/wp-calypso/pull/54751)) https://github.com/Automattic/wp-calypso/pull/56172
- [x] (Optional) Add a "Full Site Editing [Beta]" tab to the new theme showcase filter bar (see second screenshot below). #54698 https://github.com/Automattic/wp-calypso/issues/54820
- [x] Write a doc about FSE, and how it's still experimental: 1163-gh-Automattic/en.support-docs-content
- [x] Fix Mayland (Blocks) not activating on Dotcom: https://github.com/Automattic/themes/issues/4229
- [x] Only show non-universal block themes to FSE sites: https://github.com/Automattic/wp-calypso/pull/54576

<img width="480" alt="Screenshot 2021-07-13 at 15 28 32" src="https://user-images.githubusercontent.com/2070010/125471215-3420e447-8302-44d0-b848-6046107e5487.png">

<img width="694" alt="Screenshot 2021-07-14 at 18 45 14" src="https://user-images.githubusercontent.com/2070010/125668504-7ce69ec1-25ff-4d51-b704-11a1d9ebf55c.png">

## Follow-up Tasks (Not blockers)
- [ ] When a block-based theme is active, the recommended themes in the showcase should display both block-based and "classic" themes together. https://github.com/Automattic/wp-calypso/pull/56341
- [x] https://github.com/Automattic/wp-calypso/issues/56853

**Comment by david-szabo97** [comment]
>  Add a [Beta] label to block-based themes (tagged with full-site-editing) in the theme showcase (see first screenshot below).

Taking this 👀  (https://github.com/Automattic/wp-calypso/pull/54706)

**Comment by david-szabo97** [comment]
>  (Optional) Add a "Full Site Editing [Beta]" tab to the new theme showcase filter bar (see second screenshot below).

Taking this one too (https://github.com/Automattic/wp-calypso/pull/54713)

**Comment by Copons** [comment]
**Note**

- When activating/deactivating an FSE theme, the sidebar requires a full refresh to toggle the Site Editor and Customizer items.

There is a recent PR that addresses the sidebar refresh for another toggle: https://github.com/Automattic/wp-calypso/pull/54751


Example code:
```js
import { requestAdminMenu } from 'calypso/state/admin-menu/actions';

// ...

requestAdminMenu( siteId )
```

**Comment by synora** [comment]
FSE doc page is complete and is currentlly awaiting review from the Docs Guild. 👍

**Comment by synora** [comment]
FSE doc is complete: https://wordpress.com/support/full-site-editing/

**Comment by jeyip** [comment]
## Status Update

I'm going to champion the remaining the tasks. One thing to note is that **all of these can be worked on in parallel**. Here are estimates for the final 4 issues:

#### 1. Show beta badge in the "current theme" banner
- Best, nominal, and worst case: 2 days / 3 days / 5 days
- Might need some design discussion
- Draft PR https://github.com/Automattic/wp-calypso/pull/56123

#### 2. Show beta badge in theme info screen
- Best, nominal, and worst case: 2 days / 3 days / 5 days
- Might need some design discussion
- Draft PR https://github.com/Automattic/wp-calypso/pull/56225

#### 3. When a block-based theme is active, display both block-based and classic themes together
- Best, nominal, and worst case: 3 days / 4 days / 6 days
- May need some refactoring (to avoid duplicate network requests)
- Is this actually a blocking requirement for the FSE beta release?

#### 4. When activating / deactivating an FSE theme, the sidebar requires a full refresh to toggle the Site Editor and Customizer items.
- Best, nominal, and worst case: 1 days / 2 days / 4 days
- Draft PR https://github.com/Automattic/wp-calypso/pull/56172
