### ISSUE TITLE
Playwright: set up Atomic test user account.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#54531]
**Task Details**
Currently, atomic tests in `specs/specs-playwright` are using the `wooCommerceUser` in the secrets file.
This user was meant to be used for WooCommerce tests  (as the name would imply) and so is not suited for expanded Playwright E2E testing against atomic sites.

- [ ] set up an Atomic test user.
- [ ] check with relevant teams (systems?) to ensure account is exempt from A/B testing and other user-facing attributes.
- [ ] include user in secrets file.
- [ ] move existing tests that use WooCommerce user to this new user.
- [ ] document the process above in the Field Guide for future reference.
