### ISSUE TITLE
Site Editor: Usability improvements (Tracking Issue)

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#54553]
This issue is intended to track some more-or-less low hanging usability improvements that we might want to take care for the FSE Beta, if we have time.

- [x] The toolbar of the topmost blocks cover the block content: https://github.com/WordPress/gutenberg/issues/29464
- [ ] Improve the empty default text of the Query Loop block, maybe adding a "create your first post" CTA: https://github.com/WordPress/gutenberg/issues/32606
- [ ] Improve the Template Part block placeholder: https://github.com/WordPress/gutenberg/issues/29950
  For example, it could have 3 buttons instead:
  - Create new (empty)
  - Create based upon the block patterns defined by theme and plugins
  - Choose from existing custom template parts
- [ ] ~~Add an actual "preview site" functionality (not really low hanging 😅 ): https://github.com/WordPress/gutenberg/issues/29398~~

**Comment by creativecoder** [comment]
Note, I crossed off the Site editor preview functionality from this list, as that's likely a whole project in itself, so we can track it separately. The other two issues look good to start, in terms of improving Site editor design tools.

**Comment by Addison-Stavlo** [comment]
The remaining items have issues in core, closing this as we won't be tackling these any time soon.
