### ISSUE TITLE
Task: Migrate issue templates to use the new GitHub forms template

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#54565]
### Details

As noted in [this](pciE2j-oa-p2) P2 post, GitHub now has in public beta a new issue form that is much more powerful than the existing Markdown-based one.

Look to convert the issue templates we have currently to this new format.

### Checklist

- [ ] Bug Report
- [x] Feature Request #54702
- [ ] Flakey E2E spec report #54728
- [ ] Happiness Bug Report #54741
- [ ] Simple/Atomic Disparity #54728
- [x] Task #54534
- [ ] Tooling Request #54728

**Comment by worldomonation** [comment]
Task is completed as part of #54534.
