### ISSUE TITLE
My Home: Update the copy in the site setup checklist

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#54708]
### Details

We have proposed some new and improved [copy](https://en.wikipedia.org/wiki/Copy_(written)) for the site setup checklist.

The new copy can be found in the spreadsheet linked here: pd2qGl-7s-p2

<img width="983" alt="ssc" src="https://user-images.githubusercontent.com/1500769/126284703-80c51c0b-01a0-420a-8a5d-624ffa2c3aca.png">

The current copy will be using the `translate()` function so that it appears in the user's selected language. However `translate()` falls back to English if the translation doesn't exist, which will make the experience worse for non-English speakers during the period of time after this change merges but before translations are complete. So we could do something like this:
https://github.com/automattic/wp-calypso/blob/0fee1ca86a95b29d58ea3c207ffd13d983eadb44/client/my-sites/customer-home/cards/actions/quick-links/index.jsx#L160
Then when the translation bot says translations are complete, we can come back and remove the unecessary code.

We could also use the `[Status] String Freeze` label to block merging until translations are complete PCYsg-pTM-p2. The downside of this is that it takes longer for improvements to get into the hands of customers.

### Checklist

- [ ] Task titles match spreadsheet
- [ ] Task descriptions match spreadsheet
- [ ] Task action button text matches spreadsheet
- [ ] English copy isn't shown to non-English users

### Related

#52936 pd2qGl-7s-p2
