### ISSUE TITLE
EPIC: Marketplace V1

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#55157]
### Details

This issue will serve as an epic issue to track progress toward launching Marketplace V1

Related P2: pdh6GB-4-p2
Analysis: https://docs.google.com/document/d/14owltmMZwX-JR91IP_71YFjlFwoR16JrvnwadjDATNI

### Checklist

- [x] #55156 Enable Staging feature flag that will allow access to all a12s to test the feature
- [x] #55574
- [x] #55309
- [x] #55575
- [x] #55576
- [x] #55577
- [x] Add a plugin / extension as managed by atomic p9o2xV-1hB-p2
- [x] Make sure that any product / subscription can be added / removed / canceled from Store Admin
- [x] I can manage my subscription either directly in /me or from a link through plugins management 

Questions
- [x] Canceling my subscription should deactivate / delete the plugin? - No, as long as the subscription hasn't expired
- [x] Refunding my subscription should deactivate / delete the plugin? - Yes

**Comment by tjcafferkey** [comment]
I think once all of the details and questions have been ironed out we can turn them into individual GH Issues with proper user stories as a team and use Githubs native Milestone feature to track them rather than an Epic issue.

**Comment by cpapazoglou** [comment]
I have created a [milestone](https://github.com/Automattic/wp-calypso/milestone/361) containing the open issues.

I am closing this.
