### ISSUE TITLE
Empathy Testing aka Dave's order of operations:

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55281]
p58i-aqv-p2#comment-50287

- [x] Go through your focus yourselves as if you were a customers. Spend a solid hour just clicking through flows and trying to do things as if you were a customer. Look for things that stand out. Look for bugs. Fix those.
- [ ] Use FullStory to watch actual customers go through your section. Look for things that stand out. Look for bugs. Fix those.
- [x] Reach out to HE’s. Ask them for feedback on what customers typically struggle with within your section. Fix those.
- [x] Ask a friend of family member to perform a couple of specific things within your section while you watch. Jot down notes about what you observe. Look for points of friction. Fix those.
- [ ] Ask a hand full of Automatticians who have no idea what you’re working on if you can snag 15 minutes of their time. Ask them to perform a couple of specific things within your area while recording their session. Watch these videos together as a pod. Identify things that feel off. Fix those.
- [x] Dive into GitHub looking for issues in your section. Come up with a prioritized list and fix those.
- [ ] Write up a P2 if you have any interesting comments experiences.

**Comment by jordesign** [comment]
Noting this user testing here: pdgK6S-1u-p2
