### ISSUE TITLE
Migrate `client/state` to `import/order`

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#55438]
related to #54448 split `client/state` into separate directories to make it easier to review

- [ ] client/state
- [x] client/state/account-recovery #55439
- [x] client/state/account #55440
- [x] client/state/action-log  #55441
- [x] client/state/action-watchers #55442
- [x] client/state/active-promotions #55443
- [x] client/state/activity-log #55460
- [ ] client/state/admin-menu
- [ ] client/state/all-domains
- [ ] client/state/analytics
- [ ] client/state/application-passwords
- [ ] client/state/application
- [ ] client/state/atomic-transfer
- [ ] client/state/audio
- [ ] client/state/auth
- [ ] client/state/automated-transfer
- [ ] client/state/billing-transactions
- [x] client/state/checklist #55445
- [x] client/state/comments #55457
- [ ] client/state/concierge
- [ ] client/state/connected-applications
- [ ] client/state/console-dispatch
- [ ] client/state/countries
- [ ] client/state/country-states
- [ ] client/state/currency-code
- [ ] client/state/current-user
- [x] client/state/data-getters #55446
- [ ] client/state/data-layer
- [ ] client/state/desktop
- [ ] client/state/document-head
- [ ] client/state/domains
- [x] client/state/editor #55451
- [ ] client/state/email-accounts
- [ ] client/state/email-forwarding
- [ ] client/state/exporter
- [x] client/state/google-my-business #55453
- [x] client/state/gsuite-users #55459
- [ ] client/state/guided-tours
- [ ] client/state/gutenberg-iframe-eligible
- [x] client/state/happychat #55454
- [x] client/state/help #55458
- [ ] client/state/hosting
- [ ] client/state/http
- [ ] client/state/i18n
- [ ] client/state/immediate-login
- [ ] client/state/importer-nux
- [ ] client/state/imports
- [ ] client/state/inline-help
- [ ] client/state/inline-support-article
- [ ] client/state/invites
- [x] client/state/jetpack-checkout #55606
- [x] client/state/jetpack-connect #55606
- [x] client/state/jetpack-product-install #55606
- [x] client/state/jetpack-remote-install #55606
- [x] client/state/jetpack-review-prompt #55606
- [x] client/state/jetpack-scan #55606
- [x] client/state/jetpack-sync #55606
- [x] client/state/jetpack #55606
- [ ] client/state/jitm
- [ ] client/state/lasagna
- [ ] client/state/legal
- [ ] client/state/lib
- [ ] client/state/login
- [ ] client/state/logout
- [ ] client/state/logstash
- [ ] client/state/mailchimp
- [ ] client/state/marketing
- [ ] client/state/marketplace
- [ ] client/state/media
- [ ] client/state/memberships
- [ ] client/state/my-sites
- [ ] client/state/notices
- [ ] client/state/notification-settings
- [ ] client/state/notifications-panel
- [ ] client/state/notifications
- [ ] client/state/nps-survey
- [ ] client/state/oauth2-clients
- [ ] client/state/order-transactions
- [ ] client/state/pages
- [ ] client/state/partner-portal
- [ ] client/state/plans
- [ ] client/state/plugins
- [ ] client/state/post-types
- [ ] client/state/posts
- [ ] client/state/preferences
- [ ] client/state/products-list
- [ ] client/state/profile-links
- [ ] client/state/purchases
- [ ] client/state/push-notifications
- [ ] client/state/reader-ui
- [ ] client/state/reader
- [ ] client/state/receipts
- [ ] client/state/rewind
- [ ] client/state/route
- [ ] client/state/selected-editor
- [ ] client/state/selectors
- [ ] client/state/sharing
- [ ] client/state/signup
- [ ] client/state/site-address-change
- [ ] client/state/site-keyrings
- [ ] client/state/site-settings
- [ ] client/state/sites
- [ ] client/state/stats
- [ ] client/state/stored-cards
- [ ] client/state/support-articles-alternates
- [ ] client/state/support
- [ ] client/state/teams
- [ ] client/state/terms
- [ ] client/state/test
- [ ] client/state/theme-setup
- [ ] client/state/themes
- [ ] client/state/timezones
- [ ] client/state/ui
- [ ] client/state/user-devices
- [ ] client/state/user-settings
- [ ] client/state/user-suggestions
- [ ] client/state/utils
- [ ] client/state/wordads
