### ISSUE TITLE
Atomic Downgrade: Create `wpcom/v2` endpoints to cancel/delete a purchase

### ISSUE THREAD

**Issue by mmtr** [Automattic/wp-calypso#55555]
### Details

We've decided to integrate the Atomic revert functionality into the API endpoints called by Calypso to cancel/delete a purchase. That way, Calypso will be abstracted from the revert process, and will always call the same API endpoints when a user wants to cancel/remove a purchase, regardless of the site type.

However, requests to remove/cancel plans from an Atomic site won't be performed immediately, since the revert process will run asynchronously in background, so the endpoint should inform that the cancellation/removal has been queued.

This differs from the current behavior of the existing API endpoints, where purchases are immediately removed/cancelled and API consumers expect so.

In order to don't change the behavior of the existing API endpoints, we're going to create a new version of the endpoints (in the now preferred `wpcom/v2` namespace) so we can implement the behavior freely without the risk of breaking existing usages.

Further context: pdgTfM-X-p2, p1628761881093800-slack-C029N3D2ZHR, p1629099146141000-slack-C029N3D2ZHR.

### Tasks

- [x] Copy callback logic from the `rest/v1.1/me/purchases/:purchase-id/delete` endpoint to a separate lib, so it can be used from non-endpoint contexts. (D65870-code)
- [x] Copy callback logic from the `rest/v1.1/purchases/:purchase-id/cancel` endpoint to a separate lib, so it can be used from non-endpoint contexts (D65705-code)
- [x] Create a `wpcom/v2/purchases/:purchase-id/delete` endpoint, which simply runs the logic copied to a library above. (D65870-code)
- [x] Create a `wpcom/v2/purchases/:purchase-id/cancel` endpoint, which simply runs the logic copied to a library above (D65705-code).
- [x] Switch Calypso to the new `wpcom/v2` endpoints and make sure that the success notifications displayed after the calls to these endpoints are only triggered when the `status` of the response is `completed` (#55531).

**Comment by BogdanUngureanu** [comment]
@mmtr @dsas I've created D65705-code that contains the existing endpoint refactor and the new endpoint for /cancel subscription.
