### ISSUE TITLE
Marketplace: Purchase & Install paid plugin Flow

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#55575]
First Exploration
- [x] Add a static UPS Shipping method button in `/marketplace/test` and complete the purchase flow in an ecommerce site. The plugin should get installed / activated (as it is already a managed plugin).

Acceptance Criteria
- [x] In a site that already has WooCommerce installed, I can buy extensions. Buying an extension also installs / activates it in my site.
- [x] In a site without WooCommerce installed / activated, I can buy any extension and WooCommerce should get installed / activated along with the selected extension.
- [x] I can manage my subscription in `me/purchases`
- [x] Create the upgrade and install for paid plugins - the cart should cover the plan upgrade and the plugin price

Sub-tasks
* https://github.com/Automattic/wp-calypso/issues/55584
* https://github.com/Automattic/wp-calypso/issues/55585
* https://github.com/Automattic/wp-calypso/issues/55586
* https://github.com/Automattic/wp-calypso/issues/55574

**Comment by cpapazoglou** [comment]
FWIW, there is already a POC for buying a plan and a plugin in single checkout operation buy buying YOAST in

`https://wpcalypso.wordpress.com/marketplace/test/[DOMAIN]`

![image](https://user-images.githubusercontent.com/12430020/143443404-d864bc53-1c7f-4321-a5d8-b208fcfc9e01.png)

but the flow seems currently broken
