### ISSUE TITLE
Hero Flow: Write & Build intent screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#55603]
# Hero Flow v1:  Write & Build intent screen
## This is [iteration #2](pdgK6S-78-p2#write-build-intent-screen) in  production of Hero Flow v1.  👏 

![image](https://user-images.githubusercontent.com/5665959/133527358-1ac8f422-35ed-4d2a-ba89-26414f205bde.png)
**Write Flow:** 
Finish Signup -> Intent Screen -> Click Write -> Land in editor with default blogger theme

**Build Flow:** 
Finish Signup -> Intent Screen -> Click Build -> Design Picker -> ❓My Home

## Details
Project Thread: pdgK6S-78-p2
[Figma designs](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/?node-id=2119%3A1108)
This is [iteration #2](pdgK6S-78-p2#write-build-intent-screen) in the Blogger Experience Pod's production of Blogger Flow v1.  👏 

For this iteration we want to ship the multi-intent screen with **only** the Write and Build options . 

**User Facing Specs** (also verify against specs in the Project Thread):
- [x] Write button links to the editor
- [x] Build option links to My Home
- [x] Will ship with new default blogger theme with [Zoologist a derivative of Geologist](dmli5-p2) 🤞🏼
- [x] Optional: include Blog Name screen  (can easily ship in a followup PR)
- [x] "Skip this step" link in the top right of the design picker (copy TBD)
- [x] Implement a persistent  "blogger" flag: on selecting the blog/write option we'll want to persist a flag and then (in future work) call that flag to tailor content in places like the editor, or My Home, or in the[ launch banner ](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/?node-id=2119%3A1113) that shows in preview mode 
- [x] Responsive / mobile designs
- [ ] Set up tracks events and communicate these to Mike Bal: tracked here https://github.com/Automattic/wp-calypso/issues/57488

## Dev Checklist
List out tech tasks and/or PRs that will fulfill the criteria above

- [x] Intent screen
  - [x] https://github.com/Automattic/wp-calypso/pull/56165
  - [x] Tracks events on all user clicks (write button, build button, etc) and comms with @that-mike-bal to make sure we get all the tracking needed.
      - This PR https://github.com/Automattic/wp-calypso/pull/56165 has tracked the user intent with event name `calypso_signup_select_intent`.
  - [x] https://github.com/Automattic/wp-calypso/pull/56725
  - [x] Persistent intent flag: a site option called `site_intent` which will be either 'build' or 'write' D68408-code and #57018
- [x] Write Flow
  - [x] https://github.com/Automattic/wp-calypso/pull/56611
  - [x] https://github.com/Automattic/wp-calypso/pull/56750
- [x] Build Flow
  - [x] Clicking build links to My Home
- [x] Before shipping
  - [x] https://github.com/Automattic/wp-calypso/pull/56862

### Related
Blogger Experience Goals: p9Jlb4-2Sr-p2
Blogger Flow v1: p9Jlb4-31T-p2
[Figma designs](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/?node-id=2119%3A1108)

**Comment by autumnfjeld** [comment]
@arthur791004 & @roo2 
For the item  “Draft your first post modal” when user lands the in editor : there may be some design changes or evolution on this modal.   Let's wait to implement this until we are certain what will happen with the Welcome Tour conflict.

**Comment by autumnfjeld** [comment]
Update on  “Draft your first post modal” 
- hide Welcome Tour if modal is showing
- show Welcome Tour as normal for Build flow

**Comment by autumnfjeld** [comment]
> Update on “Draft your first post modal”
> 
> * hide Welcome Tour if modal is showing
> * show Welcome Tour as normal for Build flow

* Any first time visit to the Page Editor (not the post editor) always show the Welcome Tour 

Confirmation from Ollie: pdgK6S-bD-p2#comment-381

And for translations, ship to EN-locales first, then when translations are done, ship to all users.
pdgK6S-bD-p2#comment-380

**Comment by autumnfjeld** [comment]
@arthur791004  @p-jackson @roo2  Just following up from our Ganon conversation about the flag for tracking bloggers/builders/segments of users:  Here is the comment from @leomattic  about "dimensions" pa1C6h-16h-p2#comment-7372.  
> segmenting using a new dimension it’s indeed doable. I imagine it would be useful in the future to have our most popular metrics segmented by the type of user (out of bloggers, builders, importers, etc).
>
> For that to be possible, the dimension should be implemented and easily accessible. The way to picture this is having a table with user_id and attribute so that we can augment our existing tables with the new information.

I would guess,  once we set up a persistent flag / user preference (or however the user segment is persisted) the data can be retrieved for any data analysis.

**Comment by autumnfjeld** [comment]
@roo2 & @arthur791004 

Have we done the work for this item:
![image](https://user-images.githubusercontent.com/5665959/139288372-f9665a0e-6b56-4771-9143-06b7f627d3da.png)

Discussion in slack: p1635434258301000-slack-C029SB8JT8S

If this work has already been done: in the description above,  ~could  you add a link to the diff or PR that completed that work?~  Thank You!! 😄

EDIT: I've updated the description. 😄

**Comment by autumnfjeld** [comment]
@roo & @arthur791004 I believe this work is done!  Do you agree we can close this umbrella ticket?  Any new issues we can consider followup issues.

**Comment by arthur791004** [comment]
Close this one as all of the tasks are done!
