### ISSUE TITLE
Task: Add new tracks events to be used to create new blogger success metrics

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#55671]
### Details

We want to develop blogger success metrics. There are existing tracks events that can help us develop these higher level success metrics, however there are some gaps.

This task is to add tracks events to plug those gaps.

Something that complicates this work is tracks events are associated with the user that carries out the action. But in the case of likes for instance, we want that action to count towards the success of the blogger whos site was liked, not who performed the action.
Perhaps this will all be ironed out in the process that produces the higher-level success metric from the low level tracks events.

Previous work identifying useful tracks events: pdgK6S-3b-p2
Existing metrics that will be useful: 2a0c5-pb

### Checklist

- [ ] A blogger receives a comment on one of their posts
	- [ ] Prop for where comment was made e.g. blog frontend calypso, iOS, android, etc.
- [ ] A blogger replies to a comment on one of their posts
- [ ] A blogger receives a reblog
- [ ] A blogger receives social share
- [ ] A blogger's post is linked to by another site

**Comment by p-jackson** [comment]
We don't need to work on this, we think we have all the info in the stats feature. pdgK6S-3b-p2#comment-134
