### ISSUE TITLE
Full Site Editing on Dotcom: Gathering Feedback (Tracking Issue)

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#55709]
- [x] Add a new editor plugin in the Site Editor with a "leave feedback" form in the sidebar, where users can tell us their opinions about the Site Editor (see [example implementation](https://github.com/Automattic/wp-calypso/pull/55609)).
- [x] Add HotJar or Fullstory to the Site Editor.
- [x] Tweak the Snapshots tool to return launched FSE sites.
- [x] Create relevant Tracks funnels.

More context in paYE8P-108-p2

**Comment by Addison-Stavlo** [comment]
D66681-code updates the snapshots tool.

Fullstory may already be set up to include the site editor, investigating further on this.

**Comment by Addison-Stavlo** [comment]
I received confirmation that FullStory is already set up to capture the site editor both through calypso and wp-admin for simple sites. (p1631717075059500/1631278794.054000-slack-CFFF01Q4V)
