### ISSUE TITLE
Task: Convert monorepo packages to ESM

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#55855]
### Details

Since we moved to Node 16 we can use ESM packages without any experimental flag as they are considered stable. We can convert all packages in our repo.

Useful reads:
* https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
* https://2ality.com/2021/06/typescript-esm-nodejs.html

#### For all packages
1. Do a major version bump in `package.json`, as this is a breaking change. Document it as breaking in the package's `CHANGELOG.md`
2. Add `"type": "module",` and `"engines": { "node": "^12.20.0 || ^14.13.1 || >=16.0.0" }` to `package.json`.
3. If it has a `.eslintrc.js`, rename it to `.eslintrc.cjs`.
4. If it has a `jest.config.js`, change its `module.exports` to `export default`

#### For JS packages only
1. Replace `main` with `exports`
2. Convert the package code to ESM (replace all `require()`/`module.export` with `import`/`export` as required)
3. If it uses `__dirname`, add this polyfill:
    ```
    import path from 'path';
    import url from 'url';
    const __dirname = path.dirname( url.fileURLToPath( import.meta.url ) );
    ```

#### For TS packages only
Our TS packages export CJS and ESM transpilations, as well as the original source in `calypso:src`. As part of this migration we are dropping CJS support, and use `exports` to expose ESM and original source.

1. Replace `main` with (adjust paths if required)
    ```
	"exports": {
		"calypso:src": "./src/index.ts",
		"import": "./dist/esm/index.js",
		"types": "./dist/types/index.d.ts"
	},
    ``` 
2. Delete `./tsconfig-cjs.json` and its usages

### List of packages

- [ ] Convert ./desktop/package.json to ESM
- [ ] Convert ./package.json to ESM
- [x] Convert ./packages/accessible-focus to ESM (#55226 and #56130)
- [ ] #55857
- [ ] Convert ./packages/babel-plugin-transform-wpcalypso-async/package.json to ESM
- [x] Convert ./packages/browser-data-collector/package.json to ESM (#56130)
- [x] Convert ./packages/calypso-analytics/package.json to ESM (#56130)
- [ ] Convert ./packages/calypso-build/package.json to ESM
- [ ] Convert ./packages/calypso-codemods/package.json to ESM
- [x] Convert ./packages/calypso-color-schemes/package.json to ESM (#56232)
- [x] Convert ./packages/calypso-config/package.json to ESM (#56459)
- [ ] Convert ./packages/calypso-doctor/package.json to ESM
- [x] Convert ./packages/calypso-e2e/package.json to ESM (#56492)
- [ ] Convert ./packages/calypso-polyfills/package.json to ESM
- [ ] Convert ./packages/calypso-products/package.json to ESM
- [ ] Convert ./packages/calypso-stripe/package.json to ESM
- [ ] Convert ./packages/calypso-url/package.json to ESM
- [ ] Convert ./packages/components/package.json to ESM
- [ ] Convert ./packages/composite-checkout/package.json to ESM
- [ ] Convert ./packages/create-calypso-config/package.json to ESM
- [ ] Convert ./packages/data-stores/package.json to ESM
- [ ] Convert ./packages/design-picker/package.json to ESM
- [ ] Convert ./packages/domain-picker/package.json to ESM
- [ ] Convert ./packages/effective-module-tree/package.json to ESM
- [ ] Convert ./packages/eslint-plugin-wpcalypso/package.json to ESM
- [ ] Convert ./packages/explat-client-react-helpers/package.json to ESM
- [ ] Convert ./packages/explat-client/package.json to ESM
- [ ] Convert ./packages/format-currency/package.json to ESM
- [ ] Convert ./packages/i18n-calypso-cli/package.json to ESM
- [ ] Convert ./packages/i18n-calypso/package.json to ESM
- [ ] Convert ./packages/i18n-utils/package.json to ESM
- [ ] Convert ./packages/js-utils/package.json to ESM
- [ ] Convert ./packages/language-picker/package.json to ESM
- [ ] Convert ./packages/languages/package.json to ESM
- [ ] Convert ./packages/launch/package.json to ESM
- [ ] Convert ./packages/load-script/package.json to ESM
- [ ] Convert ./packages/magellan-mocha-plugin/package.json to ESM
- [ ] Convert ./packages/material-design-icons/package.json to ESM
- [ ] Convert ./packages/mocha-debug-reporter/package.json to ESM
- [ ] Convert ./packages/onboarding/package.json to ESM
- [ ] Convert ./packages/page-pattern-modal/package.json to ESM
- [ ] Convert ./packages/photon/package.json to ESM
- [ ] Convert ./packages/plans-grid/package.json to ESM
- [ ] Convert ./packages/popup-monitor/package.json to ESM
- [ ] Convert ./packages/request-external-access/package.json to ESM
- [ ] Convert ./packages/search/package.json to ESM
- [ ] Convert ./packages/shopping-cart/package.json to ESM
- [ ] Convert ./packages/social-previews/package.json to ESM
- [ ] Convert ./packages/spec-junit-reporter/package.json to ESM
- [ ] Convert ./packages/spec-xunit-reporter/package.json to ESM
- [ ] Convert ./packages/state-utils/package.json to ESM
- [ ] Convert ./packages/tree-select/package.json to ESM
- [ ] Convert ./packages/typography/package.json to ESM
- [ ] Convert ./packages/viewport-react/package.json to ESM
- [ ] Convert ./packages/viewport/package.json to ESM
- [ ] Convert ./packages/webpack-config-flag-plugin/package.json to ESM
- [ ] Convert ./packages/webpack-extensive-lodash-replacement-plugin/package.json to ESM
- [ ] Convert ./packages/webpack-inline-constant-exports-plugin/package.json to ESM
- [ ] Convert ./packages/webpack-rtl-plugin/package.json to ESM
- [ ] Convert ./packages/whats-new/package.json to ESM
- [ ] Convert ./packages/wp-babel-makepot/package.json to ESM
- [ ] Convert ./packages/wpcom-checkout/package.json to ESM
- [ ] Convert ./packages/wpcom-proxy-request/package.json to ESM
- [ ] Convert ./packages/wpcom.js/examples/browser-cors/package.json to ESM
- [ ] Convert ./packages/wpcom.js/examples/server/package.json to ESM
- [ ] Convert ./packages/wpcom.js/package.json to ESM
- [ ] Convert ./test/e2e/package.json to ESM

### Related
For follow up, these items can only be done after migrating to ESM:
- [ ] Update `chalk` to v5 ([example pr](https://github.com/Automattic/wp-calypso/pull/58890))

_No response_
