### ISSUE TITLE
Widget Visibility: Update Recommended themes to use selective refresh

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#55970]
### What

Add selective refresh support to all Recommended themes

### Why

Upon investigating discrepancies in theme behavior in https://github.com/Automattic/wp-calypso/issues/55875#issuecomment-910790543, we discovered that themes that support selective refresh widgets in the Customizer (like Twenty Twenty One) cause less back and forth between settings panels when options change than themes that do not support selective refresh (like Independent Publisher 2).

Several themes don't support any widget areas by default, and remove theme support for selective refresh:

- [x] /pub/overton/ D66360-code
- [x] /pub/balan/ D66360-code
- [x] /pub/vesta/ D66360-code
- [x] /pub/taylor/ D66360-code
- [x] /pub/fredrickson/ D66360-code
- [x] /pub/baker/ D66360-code
- [x] /pub/bradford/ D66360-code
- [x] /pub/paxton/ D66360-code
- [x] /pub/jones/ D66360-code
- [x] /pub/miller/ D66360-code
- [x] /pub/blank-canvas/ Automattic/themes#4525
- [x] /pub/independent-publisher-2 Automattic/themes#4525
- [x] /pub/lodestar Automattic/themes#4525

I'm going to propose we update these themes to support selective refresh regardless, because when a widget area *is* activated (via Content Options, for example), it makes the Customizer experience faster, and because [the current behavior in themes without selective refresh support is a blocker](https://github.com/Automattic/wp-calypso/issues/55875#issuecomment-912036657) for launching Widget Visibility in #20731. 

We also need to fix `independent-publisher-2` and `lodestar`, which I think are intended to support selective refresh, but have typos in the code (underscores vs. dashes) that prevent it from loading:

`add_theme_support( 'customize_selective_refresh_widgets' );`

/cc @Automattic/theam do you have any objections/concerns before I update some themes? :) 

### How

It's as simple as ensuring all themes/parent themes have `add_theme_support( 'customize-selective-refresh-widgets' );` in their theme setup functions.

In some cases, this means removing `remove_theme_support( 'customize-selective-refresh-widgets' );` from certain themes to re-enable it.

**Comment by scruffian** [comment]
Seems like a good idea
