### ISSUE TITLE
Marketplace: Woo Integration Research

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#56149]
**Initial Research on creating a new WordPress.com woocommerce powered site as our base api.**
> While there was a suggestion to create a new multisite network (pdh6GB-1A-p2#comment-114) (eg site_id != 1), we don't actually need to create multiple sites. We need just one that will hold all of our marketplace products.
> 
> Following the steps here, pdhcfv-26-p2 I have created a Simple site with WOO and imported all woocommerce.com products with success. The only problem I had, was importing the `download url` column cause of
> ```
> The downloadable file <code>extension-name.zip</code> cannot be used as it does not have an allowed file type. Allowed types include: <code>jpg|jpeg|jpe, png, gif, pdf, doc, docx, docm, pot|pps|ppt, pptx, pptm, odt, ppsx, ppsm, xla|xls|xlt|xlw, xlsx, xlsm, xlsb, key, webp, asc</code>
> ```
> 
> The rest api seems working as expected eg
> `https://cpapwoop.wordpress.com/wp-json/wc/v3/products?tag=723839232` returns all products with tag `wpcom_marketplace_products`.
> 
> **After this approach proves to be working** and we get 🟢 from barry pMz3w-bEX-p2#comment-91580, we should proceed with:
> - following the same steps in pdhcfv-26-p2 for marketplace dot wordpress dot com
> - importing the woo products pdh6GB-1A-p2#comment-144
> - tagging the products that belong to Marketplace V1 (pdh6GB-2M-p2) with `wpcom-marketplace`
> - creating an exception for this site to run without being proxied (pdhcfv-26-p2)
> 
> Note: you will need to proxied for the WOO to work.
> 
> Discussion pdh6GB-1A-p2#comment-144

**New approach: Use WooCommerce.com as our base API. pdh6GB-ex-p2**

Subtasks:

- [ ] Automattic/woocommerce.com#12388
- [ ] Automattic/woocommerce.com#12392
- [ ] Automattic/woocommerce.com#12389
- [ ] Automattic/woocommerce.com#12390
- [ ] https://github.com/Automattic/wp-calypso/issues/57816
- [ ] Automattic/woocommerce.com#12391

**Comment by cpapazoglou** [comment]
After some chats with Barry, we decided that if we are creating a WOO infrastructure it would be better collaborating with the Woonification team so that we don't introduce any bugs and site maintenance is well thought. I will be reaching to @jcsanyi  as it seems that Woonification efforts are paused (pLZE4-isR-p2)

**Comment by jcsanyi** [comment]
Thanks for reaching out, @cpapazoglou.

Just to be clear for anybody else that might run across this, Woonification itself is not paused - it's still a current and primary focus of the A8C Payments team.

However - we did pause our project for adding additional support for running woocommerce on simple sites when the WOOP pod decided to go with a solution that used atomic sites in their first iteration.

We're discussing this further on slack, but one of the primary things that's missing for running woo on simple sites is a set of guidelines for if/when/how this should be done, along with a plan for how to address the ops concerns about tracking, security, and reliability.

**Comment by cpapazoglou** [comment]
Let's try integrating with woocommerce.com if we can. Otherwise we will again fall back to this solution.
