### ISSUE TITLE
Remove unused signup flow code

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#56264]
### Details

We should remove signup flows that are no longer in use pbAok1-2hj-p2#comment-4638
This will save on bundle size

### Checklist

- [x] #56304
- [x] removes the `with-design-picker` flow
  - [x] #56852
- [x] Remove `onboarding-with-preview` flow
  - [x] https://github.com/Automattic/wp-calypso/pull/59795
- [x] Remove `site-style` step that is no longer needed
  - [x] https://github.com/Automattic/wp-calypso/pull/59796
- [x] Remove `*-with-preview` and `site-title-without-domains` steps that support showing a site preview, but are no longer. Make sure to remove dead code that supports showing site previews
  - [x] https://github.com/Automattic/wp-calypso/pull/59798
  - [x] https://github.com/Automattic/wp-calypso/pull/59935

**Comment by arthur791004** [comment]
Close it as all of the related PRs are shipped 🎉

**Comment by p-jackson** [comment]
Kudos and thanks for all the help with this @arthur791004 @roo2 @tyxla! We're now thousands of lines lighter in the signup framework!

FYI @simison
