### ISSUE TITLE
Hero Flow: Extended Write Flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#56568]
# Blogger Flow v1:  Extended Write Flow 
This is iteration #3 pdgK6S-78-p2#extended-write-flow in the production of Blogger Flow.  👏   
Prior and related work listed below
Brought to you by the Blogger Experience Pod

![image](https://user-images.githubusercontent.com/5665959/134825595-4697ad1e-1be6-4a21-b0d4-987f3d5522b1.png)

## Details

**Write -> Draft post flow**
Finish Signup -> Intent Screen -> Click Write -> Write Start Screen -> Draft your first post -> Editor (no modal)
See user-facing specs in Project Thread (pdgK6S-78-p2#write-draft-post-flow)

**Write -> Choose a design flow**
Finish Signup -> Intent Screen -> Click Write -> Write Start Screen -> Choose a design -> Design Picker (with Preview ability) -> Editor (TBD: with modal)
See user-facing specs in Project Thread (pdgK6S-78-p2#write-choose-design-flow)

Note:
- Still under discussion: ”First post is published modal“ when the user publishes the first post. Don't build this modal until we have further input from design.

## Dev Checklist
List out tech tasks and/or PRs that will fulfill the user-facing criteria

- [x] Pick a starting point without “Take the Masterclass”
- [x] Don't show “Draft your first post modal”  in the draft post flow
- [x] DO show "Draft your first post modal" in the choose a design flow

### Related
Blogger Experience Goals: p9Jlb4-2Sr-p2
Blogger Flow v1: p9Jlb4-31T-p2
[Figma designs](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/?node-id=2119%3A1110)
https://github.com/Automattic/wp-calypso/issues/56302
Blogger Flow v1: Write & Build intent screen #55603
Design Picker v2 #56567
