### ISSUE TITLE
Onboarding: Implement the video course.

### ISSUE THREAD

**Issue by kwight** [Automattic/wp-calypso#56888]
# Blogger Flow v1:  Masterclass Flow
## This is iteration 4 in production of Blogger Flow v1.  👏 

Let's implement our video course UI and data sources.

![videos](https://user-images.githubusercontent.com/349751/136468030-ff15e36a-cee3-4c5f-85ee-c42280c74779.png)

This UI, while initially intended for Blogger Experience onboarding, should be useable in any section of Calypso with any given videos. The first target use-case for launch, however, will be five videos available in the onboarding stage of signup. We'll use VideoPress for the interface. The dark design is not a Dark Mode implementation, but rather is intended as a "screening room" feel.

See: pdgK6S-ck-p2, "Video and Toolbar UIs for Onboarding"

## Details
Project Thread: pdgK6S-78-p2
[Figma designs](EuqfSnWpfYx8fgiBlVmbuA-fi-2119%3A1111)
This is iteration 4: pdgK6S-78-p2 /#masterclass-flow

**User Facing Specs** (also verify against specs in the Project Thread):
- [x] Users can "escape" from onboarding at any time to watch the videos.
- [x] A user's progress is tracked (they can see in the UI which videos they have and haven't watched).
- [x] Completing the last video unlocks a call-to-action, such as "write your first post".
- [x] The UI is available in our mag16 languages.

## Discovery and Preparation
- [x] Find a more appropriate name than "Masterclass".
- [x] How can watches (and last timestamp) be tracked?
- [x] How should the video content be managed? Can the Theme Showcase with CPTs offer inspiration there? We can also begin with hard-coded arrays pointing to a certain blog's Media Library.
- [x] What existing content could we surface today (YouTube, WordPress.tv, past marketing campaigns)?

## Dev Checklist
List out tech tasks and/or PRs that will fulfill the specs above.

- [x] Add an endpoint that Calypso can use to request a course and its videos' data.
- [x] Add a library server-side for managing the courses and their videos.
- [x] Set up a central data location for the videos. If the above discovery doesn't give any concrete actionable plans for storage, we can skip this item.
- [x] Build the Calypso UI behind a feature flag for easy testing.
- [x] Verify behaviour for Jetpack and Atomic sites in Calypso.
- [x] Remove EN-only gating.
- [x] Ensure all needed stats tracking is in place.
- [x] Launch to production in the signup intent flow.

### Related
Blogger Experience Goals: p9Jlb4-2Sr-p2
Blogger Flow v1: p9Jlb4-31T-p2
[Figma designs](https://www.figma.com/file/EuqfSnWpfYx8fgiBlVmbuA/?node-id=2119%3A1111)

**Comment by kwight** [comment]
@jordesign @provenself Let's coordinate on how to proceed with the discovery items.

**Comment by provenself** [comment]
I can definitely get started with 1 & 4 on the discovery list:

> Find a more appropriate name than "Masterclass".
> What existing content could we surface today (YouTube, WordPress.tv, past marketing campaigns)?

Having just come back from the eye doctor with dilated pupils, not sure it's the best afternoon to spend staring at videos 😎, but happy to coordinate with a call or async!

**Comment by jordesign** [comment]
I can also jump into number 4 next week. @provenself you mentioned in the meeting there may have been an audit of sorts done - is there a record of that somewhere?

I'll hit up some Happiness Guilds who will have an idea of other suggestions and compile a list from there as well.

**Comment by provenself** [comment]
@jordesign Only an informal (and totally incomplete) effort—someone on the WPCOM comms team was looking for visual assets, so Jeff Rozic helped track some down. Slack conversation [is here](https://a8c.slack.com/archives/C02BCAKBGDB/p1632499580033900).

**Comment by provenself** [comment]
@jordesign I started a spreadsheet for tracking, in case it's easier (and stops us from duplicating work!): https://docs.google.com/spreadsheets/d/1rQqavRg1Zh4BcihjR85a3HV4z6o0Px0uaAiXGIfJUgE/edit#gid=0

**Comment by andres-blanco** [comment]
Figma link is broken, is this what you wanted to link to: EuqfSnWpfYx8fgiBlVmbuA-fi-2119%3A1111 ?

**Comment by jordesign** [comment]
@provenself I've added a couple more resources for videos - but mostly came across the YouTube ones you already references. We've got a pretty good pool to draw from...

Some interesting use-cases I can think of using as this initial example of the showcase/player (if our blogger-specific ones won't be ready:

* 'Getting Started with Wordpress' (15 minutes) split into separate videos in a playlist
* 'Earn Money with your site' pulling together the payment options videos
* Playlist of selected Webinar topics

**Comment by provenself** [comment]
@jordesign You read my mind—I already split out that 15-minute video into its constituent parts, with timestamps, in the doc! Since it's from 2021 and explicitly deals with the Block editor, it's by far the most current onboarding project (I also inventoried a couple of other larger videos from 2017/2018). The webinars and payments videos feel long and/or maybe a touch advanced for a 5-video landing page, but seem like great fodder for something down the road. 

Based on the various playlists/onboarding videos, it seems like this is emerging as the most elementary five-step approach:

Sign Up/Choose Plan & Domain*
Theme
Customize Site/HP
Add Content (probably Post)
Launch

*The first step (signup/plan) might be preliminary enough that we can replace it with something more content-driven (inserting images, connecting your blog to social platforms, etc.)

**Comment by provenself** [comment]
Quick update on this—I broke the spreadsheet into a column for possible names, and broke down a number of 5-step approaches (per Ian) as they appear in various videos and/or support documentation. Once we've satisfied ourselves that we're not missing anything, I'm thinking the next steps are likely: 

• settling on the best core 5-step approach for onboarding new bloggers (i.e., do we need signup? do we need social? how deep do we go into static pages vs. blog?)
• determining the best existing video asset for each step
• presenting a shortlist of names for wider input (P2, probably, yeah?)

**Comment by jordesign** [comment]
This is awesome - thanks @provenself 

I think having 'Sign Up/Choose Plan & Domain*' as the first video depends a little on where/how we think this showcase will be presented in _this_ first example. Originally we were talking about having it as part of the onboarding flow for Bloggers (which would be _after_ they've already started a site and been through checkout). 

I feel like including 'Sign Up/Choose Plan & Domain*' is relevant if this showcase is shown somewhere to users _before_ they are in the process of building their site. But if we're surfacing it once things are in progress (through My Home, or through Help or something) then that first step is a littl redundant.

>  connecting your blog to social platforms, etc

This could be cool to include. I would probably need to be *after* the 'launch' video - as until the the site is launched there is nothing to share.

**Comment by provenself** [comment]
Yup, totally agree that we can nix signup/plan/domain elements since this is a post-signup onboarding. Here's a 5-step flow that might work:

[How to Change Theme](https://www.youtube.com/watch?v=at76kFMGf1g) (2:23, 2021) OR [Getting Started, 3:19-4:15](https://www.youtube.com/watch?v=twGLN4lug-I&t=199s)
[Customizing](https://www.youtube.com/watch?v=twGLN4lug-I&t=255s) (from Getting Started, 4:15-7:21)
[Add/Editing Posts](https://www.youtube.com/watch?v=twGLN4lug-I&t=756s) (from Getting Started, 12:36-14:02)
[Launch](https://www.youtube.com/watch?v=twGLN4lug-I&t=843s) (from Getting Started, 14:03-14:16)
[How to Set Up Social Media Icons Widget](https://www.youtube.com/watch?v=nAzdUOlFoBI) (2:00, 2021)

**Total Runtime: 9:08** (or < 8 mins, depending on which theme video we use)

**Comment by kwight** [comment]
Sweet, great start; is anyone here able to do the video editing if we go with that 5-step flow?

**Comment by provenself** [comment]
Momentum is currently hiring a couple of video producer roles, but beyond that I'm not sure who we've got with that skill. Maybe we can discuss at today's meeting?

**Comment by provenself** [comment]
Update: Turns out we have a video editor on retainer (who's also playing pro basketball in Sweden!). The ever-helpful Jeff Rozic thinks this can fit into her work easily, since it’s been a slowish month. He’s tracking down the raw files from the video flow, and I’m creating a breakdown specifying what we’re looking for (i.e., intro screen copy, etc.). Anticipate a fairly quick turnaround, though I'll update with any estimates I get from her.

**Comment by kwight** [comment]
We will be aiming for an MVP launch on Nov 3, after a very short internal call-for-testing. The MVP will be for English users only, to avoid needing to wait for translations.

**Comment by kwight** [comment]
Our goals have changed to being an internal call for testing on November 4, with a proper full launch (again, EN only to start) on November 15.

**Comment by kwight** [comment]
https://github.com/Automattic/wp-calypso/pull/57515 is currently being used as a simple gate for testing; using its `calypso.live` link will allow anyone to experience the My Home card and the subsequent modal that displays the videos UI.

The two biggest pieces of polish needed at this point are having the "modal" be fullscreen, and improving styling and layout at all screens (from mobile to 27" desktops). The only remaining functionality to implement is the user progress tracking; the library can handle the user attributes, but needs to have test coverage, and the UI needs to fetch those results and tie them into the individual video accordions.

**Comment by kwight** [comment]
This was just launched for EN users only. Next steps will be:

* user progress tracking,
* and course management.

**Comment by kwight** [comment]
Video production progress can be followed here: pdj6Nk-2h-p2

**Comment by kwight** [comment]
User progress tracking main issue: https://github.com/Automattic/wp-calypso/issues/58248

**Comment by autumnfjeld** [comment]
Sister issue to this, specifically for the implementation in Blogger Flow: Video UI branch from starting-point screen #58262

**Comment by kwight** [comment]
Integration with the hero flow is being handled in #58234 .

**Comment by kwight** [comment]
PR to activate the videos UI on prod: https://github.com/Automattic/wp-calypso/pull/59747

**Comment by kwight** [comment]
> Ensure all needed stats tracking is in place.

Events are listed in the Field Guide (PCYsg-DgC-p2), along with some basic funnels; also see pdgK6S-m4-p2.

**Comment by kwight** [comment]
#59747 has been merged, completing this issue.
