### ISSUE TITLE
[Meta] Playwright: Update documentation

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57149]
### Details

This is a big grouper issue for ideas to ensure are present in documentation and other updates to add to documentation re: Playwright.

### Checklist

- [ ] Update the Conifg FG page to give `cd test/e2e` command, and setting values in `.zshrc`
- [ ] Draw more intention to using `page.pause` and the Playwright inspector
- [ ] Using Playwright traces
- [ ] Which attribute to add to HTML elements if you need to make selection easier
- [ ] Async navigation
- [ ] Waiting on a specific URL when navigating to handle the multi-redirects we do
- [ ] `waitForSelector` as a means of validation
- [ ] Handlers not being attached yet to elements, and waiting on other keying elements that indicate buttons/links should have handlers
