### ISSUE TITLE
Gutenberg: v11.8.x plugin upgrade

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#57251]
Previous upgrade:  https://github.com/Automattic/wp-calypso/issues/56695.
Release notes: [v11.8.3](https://github.com/WordPress/gutenberg/releases/tag/v11.8.3)

**Install and activate**
- [x] Copy & install v11.8.0-rc.2 (D68852-code, D68857-code)
- [x] Activate v11.8.0-rc.2 on edge (D68865-code)
- [x] Copy & install v11.8.0 (D69124-code, D69133-code)
- [x] Activate v11.8.0 on edge (D69134-code)
- [x] Activate v11.8.0 on production (D69138-code)
- [x] Request v11.8.0 AT upgrade (p9o2xV-1Gw-p2-p2)
- [x] Revert to v11.7.1 due to fatal PHP errors (see the issue under "Blockers" below) (D69236-code)
- [x] Reactivate v11.8.0 (D69566-code)
- [x] Copy v11.8.0 to v11.8.1 (D69711-code)
- [x] Install v11.8.1 (D69712-code)
- [x] Activate v11.8.1 on edge (D69713-code)
- [x] Activate v11.8.1 on production (D69715-code)
- [x] Copy & install v11.8.2 (D69762-code, D69763-code)
- [x] Activate v11.8.2 on edge (D69765-code)
- [x] Activate v11.8.2 on production (D69771-code)
- [x] Request v11.8.2 AT upgrade (p9o2xV-1HC-p2)
- [x] Copy & install v11.8.3 (D69817-code, D69820-code)
- [x] Activate v11.8.3 on edge (D69829-code)
- [x] Activate v11.8.3 on production (D69839-code)
- [x] Request v11.8.3 AT upgrade (p9o2xV-1HG-p2-p2)

**Testing**
- [x] v11.8.0 Desktop viewport E2E
- [x] v11.8.0 Mobile viewport E2E
- [x] v11.8.0 WPCOM core (D69138-code)
- [x] v11.8.2 Desktop viewport E2E
- [x] v11.8.2 Mobile viewport E2E
- [x] v11.8.2 WPCOM core (D69771-code)
- [x] v11.8.3 Desktop viewport E2E
- [x] v11.8.3 Mobile viewport E2E
- [x] v11.8.3 WPCOM core (D69831-code)
- [x] v11.8.3 Desktop viewport E2E
- [x] v11.8.3 Mobile viewport E2E
- [x] v11.8.3 WPCOM core (D69839-code)

**Publish internal announcements**
- [x] Slack: #team-calypso
- [x] Slack: #wpcom-happy-announce
- [x] P2: wpcomhappy

**Wrap-up**
- [ ] Clean up unused releases
- [x] Add log entry to the Gutenberg Upgrade Log (pcoGjb-g-p2)
- [x] [Open a new issue](https://github.com/Automattic/wp-calypso/issues/new?assignees=&labels=gutenberg-upgrade%2C+%5BType%5D+Task&template=gutenberg-plugin-upgrade.md&title=Gutenberg%3A+%5Bv%23.%23.%23%5D+plugin+upgrade) for the next upgrade, transfer remaining tasks, close this issue.

 ### Blockers 🤷‍♀️

- [x] v11.8.0 cause fatal in some block based themes (404 pages) when FSE is enabled. Context: p1635444907019500-slack-C4N88L95W. Fixed in 777-gh-Automattic/wpcomsh and D69279-code. Upstream fix is pending: https://github.com/WordPress/gutenberg/pull/36089. Notice that this has been fixed in core WP, too (see https://github.com/WordPress/gutenberg/issues/35912), but we couldn't wait for a new WP release in this case. This caused us to revert to 11.7.1 for a few days, unfortunately. More context: https://github.com/Automattic/wp-calypso/issues/57251#issuecomment-954197969.

 ### Other Issues 🐛

- [x] https://github.com/Automattic/wp-calypso/issues/57687 / https://github.com/WordPress/gutenberg/issues/36254. This was fixed in GB 11.8.1. Thanks @alshakero!
- [x] https://github.com/Automattic/wp-calypso/issues/57711, present in 11.8.1 too, fixed in https://github.com/WordPress/gutenberg/pull/36312 and released in 11/9.0 RC3 and 11.8.2.

 **Issues transferred from previous release(s)**

 ---
 cc @simison @Automattic/gutenberg-upgrades

**Comment by chad1008** [comment]
Updating the issue with the new formatting in preparation of the tracking script launching soon!

**Comment by inaikem** [comment]
Thanks for the ping! Would it be possible to swap me out in favour of this team call: @Automattic/gutenberg-upgrades ? 
 Thanks in advance!

**Comment by chad1008** [comment]
Definitely. This should be the last issue with the old template that pinged you individually... I actually (unrelated to this conversation) already updated the above message with the new template :)

**Comment by fullofcaffeine** [comment]
Next one: https://github.com/Automattic/wp-calypso/issues/57451.

**Comment by fullofcaffeine** [comment]
We had to revert to 11.7.1, unfortunately, due to some fatal errors reported here: p1635444907019500-slack-C4N88L95W. We’ll investigate that and upgrade back to 11.8.0 as soon as possible. 

Note: We didn't need to revert WoA because 11.8.0 wasn't installed in AT sites yet when we made the revert. I removed the request to upgrade, for now, we'll post a new one when it's safe to upgrade again.

**Comment by fullofcaffeine** [comment]
v11.8.0 is back in simple sites! AT upgrade has been requested, too! Special kudos to @david-binda  for all his help investigating and fixing the issue in WPCOM simple and WoA!

**Comment by fullofcaffeine** [comment]
Re-opening as we are going to release 11.8.1 with a fix for https://github.com/Automattic/wp-calypso/issues/57687.

**Comment by fullofcaffeine** [comment]
11.8.1 with https://github.com/WordPress/gutenberg/pull/36263 has been released.

**Comment by chad1008** [comment]
v11.8.2 with https://github.com/WordPress/gutenberg/pull/36312 has been released
