### ISSUE TITLE
Cover Block: Fixed background causes image to be zoomed in on Safari browser in iPad and iPhone

### ISSUE THREAD

**Issue by devNigel** [Automattic/wp-calypso#57390]
### Quick summary

The cover block image is zoomed and blurry in Safari on iPad and iPhone if the Fixed background setting is enabled. 

On a related note, the. fixed background setting does not work on mobile, it is reported here: #35800

### Steps to reproduce

1. Add a Cover block with Fixed background image setting.
2. Visit the site on Safari browser on iPad. You can use BrowserStack to test.
3. You will notice that the image is zoomed in and blurry in Safari.
4. If you check in Google Chrome, you will notice that the image is not fixed, but it is not blurry like in Safari.

### What you expected to happen

Fixed background settings shouldn't cause the image to be zoomed in and blurry settings

### What actually happened

The image should not be blurry and it should be fixed. 

### Context

Slack thread: p1635302725391100-slack-C03TY6J1A

Chat: 32416087-hc
Follow up ticket: 4407792-zen

### Operating System

iOS

### Browser

Apple Safari

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

No, was able to reproduce with multiple themes.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Disable Fixed background.

**Comment by Robertght** [comment]
Thank you for reporting this @devNigel !

It appears to be related to this core issue: https://github.com/WordPress/gutenberg/issues/17718

For everyone who encounters this on WordPress.com, feel free to add your reports here.

**Comment by dpasque** [comment]
This issue is tracking an issue in another repository. All +1's of end-user reports should be done on this issue, while any discussion related to the issue itself and its fix should be done on the issue in the outside repository.

**Comment by pauloeaquino** [comment]
Same type of issue encountered in 32189249-hc (Followup in 4449254-zen)

**Comment by paaljoachim** [comment]
How is this issue coming along?

**Comment by aleone89** [comment]
There was another report of this here: hc-33587816 - this user also reported that this happens with Chrome installed on an iPhone.

**Comment by Agepeuve** [comment]
Another case in 33401257-HC

**Comment by csabarakasz** [comment]
5205392-zd-woothemes the same issue here. iOS Safari. I tried CSS code suggestion in the public repository, but it didn't work.

**Comment by tomasztunik** [comment]
We've had some fixes deployed for that along with Gutenberg 13.2. Can 5205392-zd-woothemes (don't have access) be replicated if the current version of Gutenberg is installed? What version of WP/G was it reported with? 

Re. fixed background - as for today (ios 15.5) it is currently not supported by iOS at all on the platform level.

**Comment by gwensmithx** [comment]
Hi all - let me know if you want a new report opened for this but it appears this is affecting other browsers now too - I've tested on Chrome and Firefox and also using Windows w/ Chrome on Browserstack.

We had multiple reports today of images in the Cover Block suddenly being very zoomed in. Customers noticed this after making an unrelated change to their page and clicking update.

I'm able to replicate by just adding a cover block to my test site and you can see it zooms right in when toggled. It appears to only affect simple sites. I could not replicate on AT / self-hosted.

#5296698-zd, #5295781-zd, #5295697-zd

**Comment by rw-ye** [comment]
- [ ] Follow-up in a new ticket for 5295697-zd-woothemes when the issue has been fixed.

**Comment by danielk-am** [comment]
- [ ] The user may be encountering the same over here 5297555-zen.

**Comment by pauljacobson** [comment]
- [ ] In 5296698-zen the user told us that they are using macOS Catalina, and are using Safari 15.5

**Comment by marutim** [comment]
- [ ] Follow up required for 5296698-zen

**Comment by st8matrix** [comment]
- [ ] Another report here is 5329312-zen

**Comment by cintacks** [comment]
- [ ] User looking for followup on this issue: 5331917-zd-woothemes

Provided a CSS workaround that seems to work in this particular instance:

```
.wp-block-cover-image.has-parallax, .wp-block-cover.has-parallax, .wp-block-cover__image-background.has-parallax, video.wp-block-cover__video-background.has-parallax {
	background-size: cover;
	background-position: 53% 50% !important;
}
```

**Comment by Greatdane** [comment]
I wonder if https://github.com/Automattic/themes/issues/1759 is related to this?

**Comment by cometgrrl** [comment]
@Automattic/dotcom-pqa-group Can some check if this is reproducible on a Jurassic.ninja site with the latest Gutenberg plugin active? If it is, we should move it to WordPress core. Otherwise, we'll look at finding someone in Forge to take a look.

**Comment by jordesign** [comment]
I'm unable to recreate this on a Jurassic.ninja site - either with Gutenberg plugin active *or* inactive.
https://eventual-swift.jurassic.ninja/

**Comment by TeniCola** [comment]
- [ ] Another user asking for a follow for this issue -- 5354565-zen

They're on a Personal plan, so CSS isn't feasible as a workaround unless we applied the feature as coutesy.

Meanwhile, in addition to the user's site, I was also able to recreate this behavior with the Cover block on a test site, and it happened in the editor view as well as the live site.

**Comment by ccwalburn** [comment]
Working with the user here 5296698-zen

Resized one of their images to 1200 x 803 and tested on my own test site and the image looks correct at that size. 
Currently, the image is 5236 ✕ 3503 and over 7 MB.
Suggested to the user that they resize and optimize their images as a workaround.

(I also found that I could fix this with the larger images by adding the `background-size: cover` declaration to the cover block in the editor code view, so I'm noting that here as additional information in case it's useful)

**Comment by yansern** [comment]
While the actual fix is in Gutenberg https://github.com/WordPress/gutenberg/pull/42470, if escalation is needed, here's a phab patch for a temp fix in WPCOM. D84701-code

Also related to https://github.com/Automattic/wp-calypso/issues/64682.

**Comment by youbrokesomething** [comment]
Looks like this was fixed in Gutenburg 13.8 so I'm going to close this ticket for now.

**Comment by ariel-maidana** [comment]
It seems this bug has returned: 5712779-zd-woothemes
The [core issue](https://github.com/WordPress/gutenberg/issues/17718) is closed. Should I re-open it or do we have to do some tests on our end first?
I can reproduce the issue on a test site: 

https://user-images.githubusercontent.com/4965723/202467250-12f62384-627e-46da-b749-d6f5df0ea199.mp4

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on Simple - Uncertain
- Tested on AT - Uncertain
- Tested on Self-hosted - Uncertain
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested using the steps from the initial report:
1. Add a Cover block with Fixed background image setting.
2. Visit the site on Safari browser on iPad. You can use BrowserStack to test.
3. You will notice that the image is zoomed in and blurry in Safari.
4. If you check in Google Chrome, you will notice that the image is not fixed, but it is not blurry like in Safari.
- Using Browserstack, I checked iPad Pro 12.9 2020 and 2018, Safari browser.
- I was not able to recreate the issue with the image zoomed in or blurry, but the fixed background effect didn't seem to be working. 
- I think it would be helpful if someone is able to test this on an actual iPad since I think my testing on Browserstack may be limited, so I'm marking as triaged for further review.

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by zdenys** [comment]
Another instance 37845107-hc They asked to let them know once it's fixed.

**Comment by khristiansnyder** [comment]
Also reported in 37222039-hc
AT site
Theme: Appleton
I could replicate on iOS/iPhone.

**Comment by zdenys** [comment]
5897938-zd-woothemes

**Comment by taipeicoder** [comment]
I can reproduce this issue by opening https://rockfielddemo.wordpress.com/ on an iPad. Screenshot for reference:
<img width="1180" alt="rockfielddemo" src="https://user-images.githubusercontent.com/797888/216552206-c0b6f1ed-509d-41ef-964f-aeaa8a542b0d.png">

This seems like a regression from Gutenberg. As a follow-up, I've created the following issue https://github.com/WordPress/gutenberg/issues/47726.

**Comment by rw-ye** [comment]
Another report 6033927-zd-woothemes

Simple site
Theme: Russell

**Comment by DustyReagan** [comment]
Now that Guttenberg 15.6 is deployed to WPCOM & Atomic, [our fix](https://github.com/WordPress/gutenberg/pull/48981) for this issue is in production. If you're still seeing this problem, please feel free to re-open this GitHub issue.
