### ISSUE TITLE
Hero Flows Tracks Events

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#57488]
# Hero Flow Metrics
These metrics are part of 
Hero Flow: Write & Build intent screen #55603
Hero Flow: Extended Write Flow #56568
Design Picker v2 #56567

Many Automatticians will be looking at metrics of the Hero Flow and we need to make sure we have clear tracks events that can be used in funnels and other metrics analysis.   
This ticket will track all the ToDos and PRs related to Hero Flow metrics

WIP Figma
![image](https://user-images.githubusercontent.com/5665959/139539211-ae24b993-b7ee-427a-a60d-0257fb6fdf79.png)

List of ToDos and concerns
- [x] `calypso_signup_complete[flow=setup-site]` can fire in one of the four branches of the Hero Flow. We need to make sure we know in which flow it fires.
- [x] We should discuss if we should use the calypso_signup_ pattern.  Maybe we should have a different pattern.
- [x] All steps in each branch of the Hero Flow must be trackable, we will want to watch how users move through the flows, where they drop off.
- [x] @autumnfjeld validates all events before shipping https://github.com/Automattic/wp-calypso/issues/55603

Dev Tasks
- 
- [x] Disable track events for next button #57497
- [x] Onboarding: Adjust tracks events #57417
- [x] Onboarding: Rename track data key of site title to match the property naming #56860
Opened in Automattic/wp-calypso
- [x] https://github.com/Automattic/wp-calypso/pull/57809
- [x] https://github.com/Automattic/wp-calypso/pull/57810
- [x] https://github.com/Automattic/wp-calypso/pull/57887

Related PRs

**Comment by roo2** [comment]
https://github.com/Automattic/wp-calypso/issues/57494 is related

**Comment by arthur791004** [comment]
Verify the events

![image](https://user-images.githubusercontent.com/13596067/142162053-68ca27ae-4158-4abb-b133-fdbe30f997ff.png)

### Where will you start > Give your blog a name > Pick a starting point > Skip to My Home > My Home

<details>

 calypso_signup_start [flow=setup-site]
![image](https://user-images.githubusercontent.com/13596067/142149738-43b59aef-9dc1-4823-9564-25e385794954.png)

 calypso_signup_step_start [flow=setup-site, step=intent]
![image](https://user-images.githubusercontent.com/13596067/142149774-119c69cd-8fea-45e9-b1fd-e0d2a3ae4342.png)

 calypso_signup_intent_select [intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149842-3d5ec3ca-f61d-4fa8-a944-d4bc9c9a4105.png)

 calypso_signup_actions_submit_step [step=intent, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149877-d2639380-2c02-4537-af5c-423b18ca9028.png)

 calypso_signup_step_start [flow=setup-site, step=site-options, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149928-5a877073-7b8f-4780-b9cf-e3fd12eaa212.png)

 calypso_signup_site_options_submit [has_site_title=*, has_tagline=*]
![image](https://user-images.githubusercontent.com/13596067/142149979-3679ba36-b186-4c20-9611-00c5fb1ab499.png)

 calypso_signup_actions_submit_step [step=site-options, intent=wrtie, site_title=*, tagline=*]
![image](https://user-images.githubusercontent.com/13596067/142150006-e045dd29-9f82-41d2-8ac5-62f08316de3c.png)

 calypso_signup_step_start [flow=setup-site, step=starting-point, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142154798-f114f350-40bc-4e94-9034-4ff543efe2e8.png)

 calypso_signup_starting_point_select [flow=setup-site, intent=write, starting_point=skip-to-my-home]
![image](https://user-images.githubusercontent.com/13596067/142155563-7807428d-8c8a-4bf5-8e71-371ea2244ffc.png)

 calypso_signup_complete [flow=setup-site, intent=write, starting_point=skip-to-my-home]
![image](https://user-images.githubusercontent.com/13596067/142155651-2eda0d7a-4835-4c9f-a0bc-f96f96baa5ed.png)

</details>

### Where will you start > Give your blog a name > Pick a starting point > Draft your first post > Editor

<details>

 calypso_signup_start [flow=setup-site]
![image](https://user-images.githubusercontent.com/13596067/142149738-43b59aef-9dc1-4823-9564-25e385794954.png)

 calypso_signup_step_start [flow=setup-site, step=intent]
![image](https://user-images.githubusercontent.com/13596067/142149774-119c69cd-8fea-45e9-b1fd-e0d2a3ae4342.png)

 calypso_signup_intent_select [intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149842-3d5ec3ca-f61d-4fa8-a944-d4bc9c9a4105.png)

 calypso_signup_actions_submit_step [step=intent, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149877-d2639380-2c02-4537-af5c-423b18ca9028.png)

 calypso_signup_step_start [flow=setup-site, step=site-options, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149928-5a877073-7b8f-4780-b9cf-e3fd12eaa212.png)

 calypso_signup_site_options_submit [has_site_title=*, has_tagline=*]
![image](https://user-images.githubusercontent.com/13596067/142149979-3679ba36-b186-4c20-9611-00c5fb1ab499.png)

 calypso_signup_actions_submit_step [step=site-options, intent=wrtie, site_title=*, tagline=*]
![image](https://user-images.githubusercontent.com/13596067/142150006-e045dd29-9f82-41d2-8ac5-62f08316de3c.png)

 calypso_signup_step_start [flow=setup-site, step=starting-point, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142154798-f114f350-40bc-4e94-9034-4ff543efe2e8.png)

 calypso_signup_starting_point_select [starting_point=write]
![image](https://user-images.githubusercontent.com/13596067/142150100-be04b5c5-e4ab-4613-84d5-1213833e16fc.png)

 calypso_signup_actions_submit_step [step=starting-point, intent-write, starting_point=write]
![image](https://user-images.githubusercontent.com/13596067/142150128-2745eee6-d2f3-4d51-996c-259aa770dfd1.png)

 calypso_signup_complete [flow=setup-site, intent=write, starting_point=write]
![image](https://user-images.githubusercontent.com/13596067/142150198-58c7490c-9ff8-4d2f-ad1e-e7df09ab5ff6.png)

</details>

### Where will you start > Give your blog a name > Pick a starting point > Choose the design > Preview the design > Editor

<details>

 calypso_signup_start [flow=setup-site]
![image](https://user-images.githubusercontent.com/13596067/142149738-43b59aef-9dc1-4823-9564-25e385794954.png)

 calypso_signup_step_start [flow=setup-site, step=intent]
![image](https://user-images.githubusercontent.com/13596067/142149774-119c69cd-8fea-45e9-b1fd-e0d2a3ae4342.png)

 calypso_signup_intent_select [intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149842-3d5ec3ca-f61d-4fa8-a944-d4bc9c9a4105.png)

 calypso_signup_actions_submit_step [step=intent, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149877-d2639380-2c02-4537-af5c-423b18ca9028.png)

 calypso_signup_step_start [flow=setup-site, step=site-options, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142149928-5a877073-7b8f-4780-b9cf-e3fd12eaa212.png)

 calypso_signup_site_options_submit [has_site_title=*, has_tagline=*]
![image](https://user-images.githubusercontent.com/13596067/142149979-3679ba36-b186-4c20-9611-00c5fb1ab499.png)

 calypso_signup_actions_submit_step [step=site-options, intent=wrtie, site_title=*, tagline=*]
![image](https://user-images.githubusercontent.com/13596067/142150006-e045dd29-9f82-41d2-8ac5-62f08316de3c.png)

 calypso_signup_step_start [flow=setup-site, step=starting-point, intent=write]
![image](https://user-images.githubusercontent.com/13596067/142154798-f114f350-40bc-4e94-9034-4ff543efe2e8.png)

 calypso_signup_starting_point_select [flow=setup-site, intent=write, starting_point=design]
![image](https://user-images.githubusercontent.com/13596067/142150266-549c1d32-17e7-46a9-b6db-9f629ce7a774.png)

 calypso_signup_actions_submit_step [step=starting-point, intent=write, starting_point=design]
![image](https://user-images.githubusercontent.com/13596067/142150308-40c08b7f-ebc8-4ccd-a7c0-7d3a9c80772a.png)

 calypso_signup_step_start [flow=setup-site, step=design-setup-site, intent=write, starting_point=design]
![image](https://user-images.githubusercontent.com/13596067/142150347-ad32c8f7-7ec8-4141-a64c-11f6b0ca158e.png)

 calypso_signup_design_preview_select [flow=setup-site, intent=write, theme=*, template=*]
![image](https://user-images.githubusercontent.com/13596067/142150369-2008eea8-34ef-4e93-a719-27993a47b302.png)

 calypso_signup_actions_submit_step [step=design-setup-site, intent=write, selected_design=*]
![image](https://user-images.githubusercontent.com/13596067/142150420-0b8ae560-7d39-490a-adad-12d3277381ca.png)

 calypso_signup_select_design [flow=setup-site, intent=write, theme=*, template=*]
![image](https://user-images.githubusercontent.com/13596067/142150474-5e42164a-d487-4b68-9195-d26c6819ae1a.png)

 calypso_signup_complete [flow=setup-site, intent=write, starting_point=design]
![image](https://user-images.githubusercontent.com/13596067/142150532-572f740f-49c0-461e-8757-2752305fbb1c.png)

</details>

### Where will you start > Choose the design > Preview the design > My Home

<details>

 calypso_signup_start [flow=setup-site]
![image](https://user-images.githubusercontent.com/13596067/142149738-43b59aef-9dc1-4823-9564-25e385794954.png)

 calypso_signup_step_start [flow=setup-site, step=intent]
![image](https://user-images.githubusercontent.com/13596067/142149774-119c69cd-8fea-45e9-b1fd-e0d2a3ae4342.png)

 calypso_signup_intent_select [intent=build]
![image](https://user-images.githubusercontent.com/13596067/142150585-83ef91c0-de34-4f4a-9e86-09daabb674a4.png)

 calypso_signup_actions_submit_step [step=intent, intent=build]
![image](https://user-images.githubusercontent.com/13596067/142150603-0b06d15c-0e60-4a15-a87a-c4c28d29073d.png)

 calypso_signup_step_start [flow=setup-site, step=design-setup-site, intent=build]
![image](https://user-images.githubusercontent.com/13596067/142150619-fe8b6c31-8b91-435a-a9dc-550dbca43f03.png)

 calypso_signup_design_preview_select [flow=setup-site, intent=build, theme=*, template=*]
![image](https://user-images.githubusercontent.com/13596067/142150654-ede76196-bfea-4424-80df-928b2a3e67b1.png)

 calypso_signup_actions_submit_step [step=design-setup-stite, intent=build, selected_design=*]
![image](https://user-images.githubusercontent.com/13596067/142150696-8978118d-0819-447b-88d7-9858d1e1afbe.png)

 calypso_signup_select_design [flow=setup-site, intent=build, theme=*, template=*]
![image](https://user-images.githubusercontent.com/13596067/142150717-b61ec399-14ca-4a37-8c81-838aeb8accdb.png)

 calypso_signup_complete [flow=setup-site, intent=build]
![image](https://user-images.githubusercontent.com/13596067/142150758-73973ab1-53c9-4466-9c44-50c507a1697a.png)

</details>

**Comment by autumnfjeld** [comment]
I've verified all the events and they look good!   

![Uploading image.png…]()

**Comment by arthur791004** [comment]
Close as all the events look good!
