### ISSUE TITLE
Improve the unified sidebar responsiveness on wp-admin

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#58107]
The unified sidebar is slightly larger than the Core sidebar, and so we had to recalculate the various sidebar-related breakpoints and positionings in wp-admin.
In some cases, they don't work appropriately.
This issue is likely related to #51388 and #50765.

## Large Screens (`>782px`)

| Expanded | Collapsed |
| - | - |
| <img width="1062" alt="Screenshot 2021-11-16 at 10 32 57" src="https://user-images.githubusercontent.com/2070010/141969513-34f9d7fd-316d-4ced-835a-0c785e3ee1d4.png"> | <img width="1063" alt="Screenshot 2021-11-16 at 10 33 07" src="https://user-images.githubusercontent.com/2070010/141969535-17723832-6e1d-4d5d-99fe-10e756c9f20a.png"> |

The unified sidebar works well on large screens.
There is a real chance that too many columns will mess up the title columns, but it's a [Core issue](https://core.trac.wordpress.org/ticket/52151) already.

I would probably leave this alone for now, or maybe experiment with an extremely low-maintenance change, like adding a minimum width to the title column (also [proposed in Core](https://core.trac.wordpress.org/attachment/ticket/52151/52151.diff)) and see how it plays out.

### The `960px` Breakpoint

Between `782px` and `960px`, the sidebar is automatically collapsed.
This seems to only happen when **resizing** the window; if I load the page at e.g. `800px` the sidebar will show up **expanded**.
My hunch is that this is not intended, so we might want to investigate what happens here.

## Medium Screens (`661px - 782px`)

| Screen | Expanded | Collapsed |
| - | - | - |
| 661-782 (WPCOM) | <img width="777" alt="Screenshot 2021-11-16 at 10 38 18" src="https://user-images.githubusercontent.com/2070010/141971030-062b8657-f255-45c1-a167-f4b3235016ad.png"> | <img width="776" alt="Screenshot 2021-11-16 at 10 38 09" src="https://user-images.githubusercontent.com/2070010/141971049-f99fd65d-2a93-4e20-8fee-d51c422cfb1c.png"> |
| <783 (Core) | <img width="777" alt="Screenshot 2021-11-16 at 10 40 59" src="https://user-images.githubusercontent.com/2070010/141971362-d8d8f00c-d2ab-432b-b747-e137135583be.png"> | <img width="777" alt="Screenshot 2021-11-16 at 10 40 50" src="https://user-images.githubusercontent.com/2070010/141971406-de1d9b57-5cf8-4465-9edb-d5263757b6f6.png"> |

There are three visible issues here:

- The screen title is moved to the right with a `padding-left: 50px`.
It seems it was introduced in D6125-code, but I can't seem to figure out _why_. Given how old that change is (2017), it might not be relevant anymore.

- The admin bar becomes taller (`46px` instead of the `32px` on large screens), but all its buttons (excluding the new post "quill" button) keep the original height.
This is most obvious because of the cut-off profile image, when hovering on the various buttons, or when the sidebar is open (look at the shape of the My Sites button).
Note: this only happens in wp-admin, and it works fine in Calypso.

- The page body moves to the right to make room for the sidebar. But on WPCOM it doesn't move far enough, so part of the table's left side is covered by the sidebar.
Compare with the Core version where the table's left side is fully visible.
Note: in both Core and WPCOM the content overflows to the right, so that's not an issue.

## Small Screens (`<661px`)

| Screen | Expanded | Collapsed |
| - | - | - |
| <661 | <img width="652" alt="Screenshot 2021-11-16 at 10 42 59" src="https://user-images.githubusercontent.com/2070010/141971109-9c6e16db-0c78-4e45-af8d-65b79d43649f.png"> | <img width="654" alt="Screenshot 2021-11-16 at 10 43 06" src="https://user-images.githubusercontent.com/2070010/141971135-0619b4d0-e061-4111-b639-443d567247ec.png"> |

On small screens we show the sidebar at full width, whereas Core keeps the same behaviour of medium screens.

I don't see issues here, except for the Posts title moved to the right (noted above).

## Tasks

This is the summary of what surfaced in my exploration. Please read above to get all the context.

- [x] (Optional) Experiment with adding a min width to the title column on medium and large screens.
- [x] (Optional) Investigate why the sidebar collapses between `782px` and `960px`, but only when resizing. Is it intended? Should we fix it?
- [x] (Optional) Investigate why screen titles in wp-admin are moved `50px` to the right, and if we can avoid that.
- [x] Fix the admin bar buttons height on wp-admin.
- [x] Fix the content reposition with the sidebar expanded on medium screens.

**Comment by rcrdortiz** [comment]
#### Experiment with adding a min width to the title column on medium and large screens.
There is currently an open issue about this #51388. We can tackle it there since there already is an open conversation about the solution.

#### Investigate why the sidebar collapses between 782px and 960px, but only when resizing. Is it intended? Should we fix it?
Once we reach a screen resolution of 782 or less a ['wp-responsive-activate' event will be triggered by WordPress.org](https://github.com/WordPress/WordPress/blob/5d73860e5c0dc159005d4f3956b04dcf0bfe3dc0/wp-admin/js/common.js#L1811). When this event is fired, the body gets the 'auto-fold' class added and the admin menu is set to responsive [by WordPress.org](https://github.com/WordPress/WordPress/blob/5d73860e5c0dc159005d4f3956b04dcf0bfe3dc0/wp-admin/js/common.js#L1768).

The 'auto-fold' class collapses the menubar so that a user can see the contents of the page instead of the navigation. 

The menuState isn't persisted between screen resolution changes, therefore once the user resizes the screen again to 782, < screen size <= 960px, the menubar will remain folded as seen on core [WordPress.org](https://github.com/WordPress/WordPress/blob/5d73860e5c0dc159005d4f3956b04dcf0bfe3dc0/wp-admin/js/common.js#L1949).

In my opinion, we shouldn't pursue changing this behavior proactively since most of our users will either not trigger the necessary conditions to reproduce the issue, and for the cases when it does get triggered, I would say they won't find it troublesome since it doesn't have a direct impact on the functionality of the menu (the user can still expand the menu if needed).

#### Investigate why screen titles in wp-admin are moved 50px to the right, and if we can avoid that.
I've tried to reproduce this issue with @BogdanUngureanu, but neither of us was able to replicate this. We both could see the title as expected.

#### Fix the admin bar buttons height on wp-admin.
Tested on an Atomic and Simple site and it's working as expected. I can see that the profile image isn't being cut off at any screen resolution.

#### Fix the content reposition with the sidebar expanded on medium screens.
This has already been fixed here: [#21869](https://github.com/Automattic/jetpack/pull/21869).

@Copons & @Automattic/ajax, since there is only one task that isn't solved, but has a separate ticket for it, should we close this ticket?

**Comment by Copons** [comment]
@rcrdortiz Thanks for the thorough investigation and comment, this is extremely helpful! ✨ 

> #### Experiment with adding a min width to the title column on medium and large screens.
> There is currently an open issue about this #51388. We can tackle it there since there already is an open conversation about the solution.

Sounds good to me! 👍 

> 
> #### Investigate why the sidebar collapses between 782px and 960px, but only when resizing. Is it intended? Should we fix it?
> Once we reach a screen resolution of 782 or less a ['wp-responsive-activate' event will be triggered by WordPress.org](https://github.com/WordPress/WordPress/blob/5d73860e5c0dc159005d4f3956b04dcf0bfe3dc0/wp-admin/js/common.js#L1811). When this event is fired, the body gets the 'auto-fold' class added and the admin menu is set to responsive [by WordPress.org](https://github.com/WordPress/WordPress/blob/5d73860e5c0dc159005d4f3956b04dcf0bfe3dc0/wp-admin/js/common.js#L1768).
> 
> The 'auto-fold' class collapses the menubar so that a user can see the contents of the page instead of the navigation.
> 
> The menuState isn't persisted between screen resolution changes, therefore once the user resizes the screen again to 782, < screen size <= 960px, the menubar will remain folded as seen on core [WordPress.org](https://github.com/WordPress/WordPress/blob/5d73860e5c0dc159005d4f3956b04dcf0bfe3dc0/wp-admin/js/common.js#L1949).
> 
> In my opinion, we shouldn't pursue changing this behavior proactively since most of our users will either not trigger the necessary conditions to reproduce the issue, and for the cases when it does get triggered, I would say they won't find it troublesome since it doesn't have a direct impact on the functionality of the menu (the user can still expand the menu if needed).

Given it's the same behaviour happening in Core, and that it's just not a big deal, I agree with you that it's better to leave it alone.

> #### Investigate why screen titles in wp-admin are moved 50px to the right, and if we can avoid that.
> I've tried to reproduce this issue with @BogdanUngureanu, but neither of us was able to replicate this. We both could see the title as expected.

I can't repro this anymore as well.
I distinctly remember a `padding-left: 50px` applied to the post type heading, so I guess it must have been fixed over the last few days.
There are just too many possible files that might have been updated for this fix, so I'd say that searching for the diff is just not worth it in the slightest.

> #### Fix the admin bar buttons height on wp-admin.
> Tested on an Atomic and Simple site and it's working as expected. I can see that the profile image isn't being cut off at any screen resolution.

This was fixed by D69246-code, which, surprisingly enough, was merged the same day I opened this issue. 😅 
 
> #### Fix the content reposition with the sidebar expanded on medium screens.
> This has already been fixed here: #19695.

It looks like you typed the wrong PR number. 🙂 

Regardless, I couldn't reproduce the issue as well. 👍 

> @Copons & @Automattic/ajax, since there is only one task that isn't solved, but has a separate ticket for it, should we close this ticket?

Makes total sense, let's close it down, and keep working on #51388 for the last remaining task!

**Comment by rcrdortiz** [comment]
> It looks like you typed the wrong PR number. 🙂

@Copons, I've updated my original message with a link to the right PR.
