### ISSUE TITLE
Hero/Blogger flow launch checklist

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58196]
## PREPARE FOR LAUNCH 🚀 
We are ready to launch the Blogger Flow, all critical issues from the [CfT](p58i-bpK-p2) have been addressed.

**Let's make sure we are fully prepared with this checklist:**

- [x] Only shipping to en local users (we are waiting for translations)
- [x] Add in new [illustrations](p1637188230478600/1637183547.475700-slack-C029SB8JT8S)
- [x] Feature freeze: be cautious about merging any PRs related to the Hero flows until we establish stability in production
- [x] Create PR to remove feature flag
- [x] Be aware of potential conflicts with Design Picker shipping (there might not be any, just voicing the idea)
- [x] Announce to #blogger-experience channel, and perhaps #dot-com
- [x] Announce to HE  @jordesign 
- [x] Announce dotcom data @kurt213 
- [x] Make it LIVE!  Merge PR to remove feature flag
- [x] Add PR & timestamp to [Ship table](pdgK6S-iY-p2)

**Post launch**
- Note to remember that when we begin merging code again it isn't behind a feature flag, so thorough testing is needed.
- Check an eye translations, and make announcements to the above peeps/channels when translations become available (PR that removes the english "if" statement)

### Related
Blogger Flow v1: p9Jlb4-31T-p2
https://github.com/Automattic/wp-calypso/issues/56302
Blogger Flow v1: Write & Build intent screen #55603

**Comment by autumnfjeld** [comment]
@arthur791004 @roo2 @p-jackson   Can you think of anything to add?

I'm just doing some last tracks checking, but I think we're ready to launch to users.  Just want to respect the feature freeze for code that might introduce potential bugs over the next few days.

**Comment by autumnfjeld** [comment]
Hero Flow: Release on production #58223

![image](https://user-images.githubusercontent.com/5665959/142499562-12895471-dff4-44cc-a9ca-cb31e21c6277.png)

**Comment by jordesign** [comment]
Closing this issue as it is no longer relevant.
