### ISSUE TITLE
Blogger Flow: Video UI branch from starting-point screen

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58262]
## Blogger Flow: Video UI
The stretch squad, aka Serenity, has just shipped [a version of the Video UI](pdgK6S-mD-p2), accessible through a button on My Home.   Umbrella Issue: Implement the video course. #56888
We will be reusing their [VideoUi component](https://github.com/Automattic/wp-calypso/blob/1cd97852e8bf12d5d123d6660c2b9df7843a01b7/client/components/videos-ui/index.jsx) in the Blogger flow.
See their umbrella issue: Onboarding: Implement the video course. #56888

![image](https://user-images.githubusercontent.com/5665959/142515064-3351b44b-4df8-4c3a-8b07-e2d0c55d7fe7.png)

![image](https://user-images.githubusercontent.com/5665959/142515114-e522a8a1-f219-4941-b529-492d01267d81.png)

![image](https://user-images.githubusercontent.com/5665959/142515140-1dd5a3ed-70ff-4e16-b04a-eb30adfc6ffb.png)

![image](https://user-images.githubusercontent.com/5665959/142515167-5818588d-630f-41b8-ba21-1bb0224bd065.png)

![image](https://user-images.githubusercontent.com/5665959/142515191-8681b570-1b63-4ecf-adcb-42a29d455aa4.png)

### Acceptance Criteria & User Facing Requirements
- [x] The title is ["Blogging Quick Start"](pdgK6S-mD-p2) NOT Masterclass
- [x] Desktop and mobile built to match: EuqfSnWpfYx8fgiBlVmbuA-fi-2119%3A1111
- [x] Video UI loads from pick a starting-point screen
- [x] "Back" link goes back to the starting-point screen
- [x] "Draft your first post" link goes to editor, where the [modal](![image](https://user-images.githubusercontent.com/5665959/142511802-5d04f618-2cdd-4fc5-8d1f-f630605482f5.png)) will show
- [x] Completion of playing last video reveals "Start writing" button, which goes to the editor, where the modal will show
- [x] User behavior is tracked with tracks events
- [x] Call for Testing on dtkmj-p2

### Dev Checklist
- [x] https://github.com/Automattic/wp-calypso/pull/58234
- [ ] https://github.com/Automattic/wp-calypso/pull/59747

### Related
[Blogger/Hero Flow Project Thread](pdgK6S-78-p2)
Hero Flow: Write & Build intent screen #55603
Onboarding: Implement the video course. #56888
Demo of Video UI: pdgK6S-mD-p2
Implement the video course. #56888

**Comment by autumnfjeld** [comment]
@arthur791004 & @roo2  You should coordinate with Serenity Team, e.g. @kwight  when you start  work on this.   Check what changes are in the works in the VideoUi or any other concerns. :)

**Comment by arthur791004** [comment]
I propose a draft [here](https://github.com/Automattic/wp-calypso/pull/58234). I think we should wait for something such as marking the video completed and showing the CTA on the footer once all of the videos are watched. One concern might be we should ensure the tracks events of the signup framework are fired correctly.

Maybe they should expose some props let us to control some behavior of CTA. Or we only need the content of the video UI without the header and footer. And the `onComplete` function props so that we can control the behavior after the user has watched all of the videos.

cc @kwight

**Comment by kwight** [comment]
> Maybe they should expose some props let us to control some behavior of CTA.

We do have some props for this at the moment, but we're switching them to a simpler "context" prop that can be used to output any header/footer changes needed. I could see something like `<VideosUi course="onboarding" context="<sign up flow slug>">`.

> Or we only need the content of the video UI without the header and footer.

I'd personally avoid this, to keep styling and layout as consistent as possible across the different eventual contexts for the component.

> And the onComplete function props so that we can control the behavior after the user has watched all of the videos.

Is this something different from triggering the call to action?

**Comment by arthur791004** [comment]
Close it as https://github.com/Automattic/wp-calypso/pull/59747 is shipped 🎉
