### ISSUE TITLE
Blogger Experience: My Home site setup checklist

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58372]
## Blogger Experience: tailoring the site setup checklist for bloggers

WIP: This is ticket needs additional detail and design input.

![image](https://user-images.githubusercontent.com/5665959/142943938-71671a33-e86c-4b84-8488-b8398e08808d.png)

[Figma](https://www.figma.com/proto/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?page-id=3511%3A1633&node-id=3511%3A1923&viewport=273%2C48%2C0.26&scaling=min-zoom&starting-point-node-id=3511%3A1880)

## User facing criteria

- [x] ToDo: Mobile app step needs to be added in to design
- [x] ToDo: final pass on copy, asking @kristastevens to help us out
- [x] devs: when starting this ticket please check in with Ollie on final designs
- [x] ToDo: TBD language: Blog vs Site should we keep using "Site" (One reason to use blog: https://wordpress.com/support/do-i-need-a-website-a-blog-or-a-website-with-a-blog/). --> We will use "blog"
- [x] Built to design specs in [Figma](https://www.figma.com/proto/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?page-id=3511%3A1633&node-id=3511%3A1923&viewport=273%2C48%2C0.26&scaling=min-zoom&starting-point-node-id=3511%3A1880)
- [x] Many items will be checked off for users who complete the steps of BLogger onboarding, all the checked items should be sorted above unchecked items
- [x] Theme step is checked off for anyone who chose a theme in the DP (it is unchecked for anyone who skipped the DP)
- [x]  Show the new publicize step to everyone, not just bloggers

## Dev task list
- [x] D71330-code
- [x] https://github.com/Automattic/wp-calypso/pull/59060

## Related
[Blogger Flow Project Thread](pdgK6S-78-p2)

**Comment by autumnfjeld** [comment]
@kristastevens  Would you have time to help us polish the copy in these [My Home Checklist Figma designs](Figma)?  To make sure the language in each card in the My Home checklist sounds good?   

You could put your copy suggestions in a spreadsheet or here in the git comments and then we'll get @ollierozdarz to update the designs.  Also note: the designs are missing the Mobile App step.

Here's the existing mobile app card on the current My Home checklist:
![image](https://user-images.githubusercontent.com/5665959/143959339-aad27fb2-69ab-4629-9282-05237a7061f1.png)

**Comment by kristastevens** [comment]
Hi @autumnfjeld, I've got some draft copy below. I'm basing my suggestions off the current design in this [Figma file](https://www.figma.com/proto/EuqfSnWpfYx8fgiBlVmbuA/Blogger-Experience?page-id=3511%3A1633&node-id=3511%3A1880&viewport=273%2C48%2C0.26&scaling=min-zoom&starting-point-node-id=3511%3A1880). I made some changes to the text throughout. I also re-ordered the list so that browsing themes comes before previewing your blog. 

@jordesign I'd love to get your thoughts on this suggested text:

Name your blog
Choose a name for your blog that reflects your site's personality. Don't worry, you can change it any time you like. 
Button text: Name your blog

Browse themes
Choose the perfect look for your site — one that reflects your site's personality. 
Button text: Browse themes

Preview your blog
See how your site looks to site visitors. Remember, your blog is a work in progress — you can always choose a new theme or tweak your site's design. 
Button text: Preview blog

Publish your first post
Share your ideas with the world! Don't worry, your site remains private — visible only to you — until you're ready to launch it. 
Button text: Draft a post

Enable post sharing
Allow blog visitors to share your posts to social media such as Twitter, Facebook, and LinkedIn. It's a great way to help you build your audience. 
Button text: Enable sharing

Launch your blog
Ready for the big reveal? Right now, your blog is private and visible only to you. Launch your blog so that it's public for everyone. 
Button text: Launch blog

Try the WordPress App
Write posts, check stats, and reply to comments on the go! 
Button text: Download the app

**Comment by jordesign** [comment]
Tes for all of these looks great - thanks @kristastevens.

**Comment by ollierozdarz** [comment]
Great work, @kristastevens! @autumnfjeld, Figma designs are now updated with the new copy.

**Comment by arthur791004** [comment]
@autumnfjeld @kristastevens I just want to confirm the final list for the blogger is as follows, right?
* Name your blog
* Preview your blog
* Browse themes
* Publish your first post
* Enable post sharing
* Launch your blog
* Try the WordPress App

@ollierozdarz Should we need the `Try the WordPress App` task as I see @kristastevens mentioned it [here](https://github.com/Automattic/wp-calypso/issues/58372#issuecomment-983951263) but it doesn't show on the Figma?

Besides, @kristastevens `Enable post sharing` might also need the copy for non-blogger as @autumnfjeld mentioned that it should show to everyone, not just bloggers. Also, @autumnfjeld Do you have any preference for the order of this task in the non-blogger checklist?

Last, @autumnfjeld @p-jackson @roo2 Do you have any idea how to mark the following steps completed? I'm not familiar with this part and need to take more time to investigate.
* Preview your blog
* Browse themes
* Publish your first post
* Enable post sharing

In my option, the logic might be as follows
* “Preview your blog” and “Browse themes” are marked as completed when the user clicks the button
* “Publish your first post” is marked as completed when the user publishes any post and the logic is the same as showing the first post published modal in the editor.
* “Enable post sharing” might be weird because the post sharing is enabled by default?

**Comment by ollierozdarz** [comment]
@arthur791004 the WordPress App mention is [here in Figma](https://d.pr/i/9YNJ1G), you may be looking in the wrong spot 🙂

We'll definitely need it as it drives some important usage for our Mobile App.

**Comment by arthur791004** [comment]
Oh yes, I found I saw the old section last week 😅

**Comment by kristastevens** [comment]
Hi @arthur791004, I defer to @autumnfjeld about the order, but my preference was for how they appear in the comment above: 

* Name your blog
* Browse themes
* Preview your blog
* Publish your first post
* Enable post sharing
* Launch your blog 
* Try the WordPress app

My rationale is that you'd typically browse themes before previewing your blog. 

> Enable post sharing might also need the copy for non-blogger 

Great catch, @arthur791004! Here's some proposed copy for the non-blogger: 

Enable post sharing
Allow visitors to share your posts to social media such as Twitter, Facebook, and LinkedIn. It's a great way to help you build your audience.
Button text: Enable sharing

**Comment by autumnfjeld** [comment]
How we determine if these items are "done"

Preview Blog
-  we think this means previwing https://wordpress.com/view/{site}

Browse Themes
- clicked the "Browse Themes" button on the card

Publicizie
- the user has visited ~https://wordpress.com/marketing/sharing-buttons/{site}~. UPDATE:  /marketing/connections/<your_site>

**Comment by ollierozdarz** [comment]
I think you're spot on @autumnfjeld. Let's keep it dead simple to begin with and just count them going off to 'view' the pages as done. 'Preview', 'Browse' are both good words we use because it's keeping the expectations light.

For Publicize, if we can't easily tell if they've connected it, then viewing will be fine IMO.

**Comment by arthur791004** [comment]
## Update

For “Enable post sharing”, we want the user to link their social accounts to share their new posts automatically. So, revert the copy to the original one and link to Publicize `/marketing/connections/<your_site>`. cc @kristastevens and maybe you have the better copy for **Publicize**

![image](https://user-images.githubusercontent.com/13596067/145948373-6af4344f-ca1a-40cb-818a-4b36cc0eaab1.png)


See: p1639450680103300-slack-C029SB8JT8S

**Comment by kristastevens** [comment]
Hi @arthur791004, current copy is good! Thanks for asking!

**Comment by arthur791004** [comment]
Close it as D71330-code and https://github.com/Automattic/wp-calypso/pull/59060 are shipped 🎉
