### ISSUE TITLE
Refactor away from React `UNSAFE_*` lifecycle methods

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#58453]
### Details

We want to refactor away from React `UNSAFE_*` lifecycle methods. While this project has been going on for a while we want to track any remaining occurrences here to make sure we don't loose oversight. At the time of this writing there are ~180 of those unsafe lifecycle methods left.

If you need a review or have any questions, please don't hesitate to ping @Automattic/team-calypso-frameworks. It may also be helpful to look into [React component documentation](https://reactjs.org/docs/react-component.html) to look up with what you might want to replace an unsafe method and/or look at previous refactoring PRs (e.g. https://github.com/Automattic/wp-calypso/pull/58232, https://github.com/Automattic/wp-calypso/pull/58232).

### Checklist

- [ ] `client/login/magic-login/handle-emailed-link-form.jsx` #61163
- [x] `client/login/magic-login/request-login-email-form.jsx` #60285
- [x] `client/login/wp-login/index.jsx` #61165
- [ ] `apps/notifications/src/panel/templates/index.jsx`
- [x] `apps/notifications/src/panel/templates/empty-message.jsx` - @tyxla #63276
- [x] `apps/notifications/src/panel/templates/image-loader.jsx` - @tyxla #63277
- [ ] `apps/notifications/src/panel/templates/status-bar.jsx`
- [ ] `apps/notifications/src/panel/templates/note-list.jsx`
- [ ] `apps/notifications/src/panel/Notifications.jsx`
- [x] `client/jetpack-connect/search.jsx` - @tyxla #59440
- [x] `client/jetpack-connect/main.jsx` - @tyxla #59169
- [x] `client/jetpack-connect/signup.js` - @tyxla #61117
- [x] `client/jetpack-connect/remote-credentials.js` @flootr #61541
- [x] `client/jetpack-connect/sso.jsx` #62758
- [ ] `client/jetpack-connect/authorize.js`
- [x] `client/post-editor/editor-revisions/dialog.jsx` - @tyxla #60484
- [x] `client/post-editor/editor-diff-viewer/index.jsx` - @tyxla #63172
- [x] `client/lib/analytics/track-component-view/index.jsx` - @tyxla #58860
- [ ] `client/lib/url-search/index.js`
- [x] `client/lib/with-dimensions/index.jsx` - @tyxla #63441
- [x] `client/post-editor/media-modal/detail/detail-preview-image.jsx` @flootr #61234
- [ ] `client/post-editor/media-modal/index.jsx`
- [x] `client/post-editor/media-modal/gallery/index.jsx` @flootr #62658
- [x] `client/post-editor/media-modal/detail/detail-preview-videopress.jsx` @flootr #62586
- [x] `client/post-editor/media-modal/detail/detail-fields.jsx` @flootr #62568
- [ ] `client/me/help/help-contact-form/index.jsx`
- [x] `client/me/help/help-courses/index.jsx` @tyxla #58857
- [x] `client/me/application-passwords/index.jsx` @flootr #61562
- [x] `client/me/concierge/reschedule/calendar-step.js` @flootr #61814
- [x] `client/me/concierge/book/calendar-step.js` @flootr #61814
- [x] `client/me/purchases/confirm-cancel-domain/index.jsx` @flootr #62732
- [x] `client/me/purchases/cancel-purchase/index.jsx` @brookewp #61828
- [x] `client/me/purchases/manage-purchase/index.jsx` - @tyxla #60456
- [ ] `client/components/token-field/index.jsx`
- [ ] `client/components/language-picker/index.jsx`
- [x] `client/components/checklist/checklist.js` - @tyxla #60289
- [ ] `client/components/async-load/index.jsx`
- [x] `client/components/post-schedule/index.jsx` - @tyxla #62220
- [x] `client/components/post-schedule/docs/example.jsx` - @tyxla #62220
- [x] `client/components/data/query-users-suggestions/index.jsx` @flootr #60337
- [x] `client/components/data/query-theme/index.jsx` @flootr #59979
- [x] `client/components/data/query-plugin-keys/index.jsx` @flootr #59982
- [x] `client/components/data/query-keyring-connections/index.jsx` @flootr #59990
- [x] `client/components/data/query-site-guided-transfer/index.jsx` @tyxla #60011
- [x] `client/components/data/query-post-stats/index.jsx` #60026
- [x] `client/components/data/query-jetpack-plugins/index.jsx` #60025
- [x] `client/components/data/query-contact-details-cache/index.jsx` #60034 
- [x] `client/components/data/document-head/index.jsx` - @tyxla #60949
- [x] `client/components/data/query-keyring-services/index.jsx` - @tyxla #58753
- [x] `client/components/data/query-reader-lists/index.jsx` - @tyxla #60434
- [x] `client/components/data/query-reader-feed/index.jsx` @flootr #60660
- [x] `client/components/data/query-posts/index.jsx` @flootr #60532
- [x] `client/components/data/query-post-likes/index.jsx` @flootr #61152
- [x] `client/components/data/query-concierge-appointment-details/index.js` @flootr #60669
- [x] `client/components/data/query-support-article-alternates/index.jsx` @flootr #60396
- [x] `client/components/data/query-reader-site/index.jsx` @flootr  #60488
- [x] `client/components/data/query-post-types/index.jsx` @flootr #60492
- [x] `client/components/data/query-plans/index.jsx` - @tyxla #58757
- [x] `client/components/data/query-site-monitor-settings/index.jsx` - @tyxla #60439
- [x] `client/components/data/query-jetpack-user-connection/index.jsx` - @tyxla #60960
- [x] `client/components/data/query-reader-tag-images/index.jsx` @flootr #60670
- [x] `client/components/data/query-user-connection/index.jsx` - @jsnajdr #58943
- [x] `client/components/data/query-reader-thumbnails/index.jsx` - @tyxla #60667
- [x] `client/components/data/query-rewind-backup-status/index.js` - @tyxla #61115
- [x] `client/components/data/moderate-comment/index.jsx` - @tyxla #60961
- [x] `client/components/data/media-list-data/index.jsx` - @tyxla #60991
- [ ] `client/components/keyed-suggestions/index.jsx` @flootr 
- [ ] `client/components/jetpack/with-server-credentials-form/index.jsx`
- [ ] `client/components/input-chrono/index.jsx`
- [x] `client/components/web-preview/content.jsx` - @tyxla #60663
- [x] `client/components/web-preview/component.jsx` - @tyxla #60663
- [x] `client/components/image/index.js` - @tyxla #62103
- [ ] `client/components/search/index.jsx`
- [ ] `client/components/infinite-list/index.jsx`
- [ ] `client/components/rewind-credentials-form/index.jsx`
- [x] `client/components/track-input-changes/index.jsx` - @tyxla #60995
- [x] `client/components/locale-suggestions/index.jsx` - @tyxla #59004
- [ ] `client/components/foldable-card/index.jsx`
- [ ] `client/components/title-format-editor/index.jsx`
- [x] `client/components/forms/form-phone-input/index.jsx` - @tyxla #58997
- [x] `client/components/forms/sortable-list/index.jsx` - @tyxla #61574
- [x] `client/components/domains/registrant-extra-info/fr-form.jsx` - @tyxla #62256
- [x] `client/components/domains/registrant-extra-info/with-contact-details-validation.jsx` @tyxla #58396
- [x] `client/components/domains/registrant-extra-info/uk-form.jsx` - @tyxla #62255
- [x] `client/components/domains/contact-details-form-fields/index.jsx` - @tyxla #62257
- [x] `client/components/domains/trademark-claims-notice/index.jsx` - @tyxla #62850
- [ ] `client/components/domains/transfer-domain-step/index.jsx`
- [ ] `client/components/domains/transfer-domain-step/transfer-domain-precheck.jsx`
- [ ] `client/components/domains/register-domain-step/index.jsx`
- [ ] `client/components/section-nav/index.jsx`
- [x] `client/components/social-buttons/facebook.js` - @tyxla #58760
- [x] `client/my-sites/post-type-list/max-pages-notice.jsx` - @flootr #59121
- [ ] `client/my-sites/post-type-list/index.jsx`
- [x] `client/my-sites/customize/main.jsx` - @tyxla #63963
- [x] `client/my-sites/earn/ads/form-settings.jsx` - @edanzer #81048
- [x] `client/my-sites/themes/themes-selection.jsx` - @tyxla #62135
- [x] `client/my-sites/stats/stats-module/index.jsx` - @tyxla #62155
- [ ] `client/my-sites/themes/theme-upload/index.jsx`
- [ ] `client/my-sites/themes/theme-preview.jsx`
- [x] `client/my-sites/email/email-forwarding/email-forwarding-add-new.jsx` - @stephanethomas #61572
- [x] `client/my-sites/store/app/store-stats/referrers/index.js` - @tyxla #60083
- [x] `client/my-sites/store/app/store-stats/store-stats-module/index.js` - @tyxla #60946
- [x] `client/my-sites/store/app/store-stats/store-stats-referrer-widget-base/index.js` - @tyxla #60083
- [x] `client/my-sites/pages/page-list.jsx` - @flootr #61314
- [x] `client/my-sites/post-selector/selector.jsx` - @tyxla #63664
- [x] `client/my-sites/store/components/d3/base/index.js` - @tyxla #63666
- [x] `client/my-sites/resume-editing/index.jsx` - @tyxla #60295
- [x] `client/my-sites/site-settings/date-time-format/index.jsx` - @tyxla #63443
- [x] `client/my-sites/site-settings/jetpack-sync-panel/index.jsx` - @tyxla #58764
- [x] `client/my-sites/site-settings/form-jetpack-monitor.jsx` - @tyxla #60439
- [x] `client/my-sites/site-settings/seo-settings/main.jsx` @flootr #59107
- [x] `client/my-sites/site-settings/seo-settings/form.jsx` @flootr #59940
- [ ] `client/my-sites/site-settings/seo-settings/site-verification.jsx` @flootr 
- [x] `client/my-sites/site-settings/wrap-settings-form.jsx` - @tyxla #60045
- [x] `client/my-sites/plan-features/index.jsx` - @tyxla #60389
- [ ] `client/my-sites/marketing/buttons/tray.jsx`
- [ ] `client/my-sites/marketing/connections/services/slack.js`
- [ ] `client/my-sites/marketing/connections/services/instagram.jsx`
- [ ] `client/my-sites/marketing/connections/services/google-photos.js`
- [ ] `client/my-sites/marketing/connections/services/google-my-business.js`
- [ ] `client/my-sites/marketing/connections/services/mailchimp.js`
- [ ] `client/my-sites/marketing/connections/inline-connection-action.jsx`
- [ ] `client/my-sites/marketing/connections/service.jsx`
- [x] `client/my-sites/preview/main.jsx` - @tyxla #60044
- [x] `client/my-sites/exporter/export-card/index.jsx` - @tyxla #60298
- [x] `client/my-sites/people/people-invites/invites-list-end.jsx` - @flootr #58907
- [x] `client/my-sites/people/people-invite-details/index.jsx` - @flootr #59106
- [x] `client/my-sites/people/invite-people/index.jsx` - @flootr #59118
- [x] `client/my-sites/theme/main.jsx` - @tyxla #60084
- [x] `client/my-sites/checkout/checkout-thank-you/index.jsx` - @tyxla #62851
- [x] `client/my-sites/plan-features-comparison/index.jsx` - @tyxla #60387
- [x] `client/my-sites/purchase-product/search.jsx` - @tyxla #59440
- [x] `client/my-sites/plugins/plugin.jsx` - @tyxla #58850
- [x] `client/my-sites/plugins/plugins-browser/index.jsx` - @wberredo #59019
- [x] `client/my-sites/plugins/main.jsx` - @tyxla #61571
- [ ] `client/my-sites/plugins/plugin-upload/index.jsx`
- [x] `client/my-sites/plugins/plugin-automated-transfer/index.jsx` - @tyxla #60244
- [ ] `client/my-sites/picker/picker.jsx`
- [x] `client/my-sites/woocommerce/dashboard/required-plugins-install-view.jsx` - @allilevine #60784
- [x] `client/my-sites/domains/map-domain/index.jsx` #61236
- [x] `client/my-sites/domains/domain-search/site-redirect.jsx` #61239
- [x] `client/my-sites/domains/transfer-domain/index.jsx` #61241
- [x] `client/my-sites/domains/components/form/state-select.jsx` - @tyxla #60449
- [x] `client/my-sites/domains/domain-search/index.jsx` - @tyxla #60453
- [x] `client/my-sites/domains/components/domain-warnings/index.jsx` #61242
- [x] `client/my-sites/domains/domain-management/dns/dns-add-new.jsx`  @flootr #62689
- [x] `client/my-sites/domains/domain-management/site-redirect/index.jsx` #62551
- [x] `client/my-sites/domains/domain-management/name-servers/index.jsx` - @leonardost #62626
- [x] `client/my-sites/comments/comment-list/index.jsx` - @flootr #61311
- [ ] `client/my-sites/comments/comment/index.jsx`
- [x] `client/my-sites/comments/comment/comment-html-editor/add-link-dialog.jsx` - @tyxla #61570
- [ ] `client/signup/steps/site-picker/site-picker-submit.jsx` @flootr 
- [x] `client/signup/steps/site/index.jsx` - @tyxla #64408
- [ ] `client/signup/steps/rewind-migrate/index.jsx`
- [x] `client/signup/steps/user/index.jsx` - @jsnajdr, #59114
- [x] `client/signup/steps/user/test/index.js` - @jsnajdr, #59114
- [x] `client/signup/steps/clone-credentials/index.jsx` @flootr #61256
- [x] `client/signup/steps/rewind-form-creds/index.jsx` @tyxla #63133
- [ ] `client/signup/main.jsx`
- [x] `client/layout/guided-tours/config-elements/continue.js` - @tyxla #61366
- [x] `client/layout/guided-tours/docs/patch/clean-history.patch` - @tyxla #61367
- [ ] `client/layout/guided-tours/config-elements/step.tsx` - @tyxla
- [x] `client/layout/guided-tours/config-elements/quit.js` - @tyxla #61360
- [x] `client/layout/guided-tours/component.jsx` - @tyxla #61362
- [x] `client/layout/masterbar/notifications.jsx` - @tyxla #64079
- [x] `client/landing/domains/registrant-verification/index.jsx` - @tyxla #58990
- [x] `client/landing/domains/transfer-away-confirmation/index.jsx` - @tyxla #59168
- [x] `client/blocks/term-tree-selector/index.jsx` - @tyxla #60486
- [x] `client/blocks/term-tree-selector/terms.jsx` - @tyxla #60486
- [ ] `client/blocks/login/login-form.jsx`
- [x] `client/blocks/login/two-factor-authentication/verification-code-form.jsx` #61353
- [x] `client/blocks/video-editor/index.jsx` @flootr #62586
- [x] `client/blocks/conversations/list.jsx` - @tyxla #60487
- [x] `client/blocks/reader-full-post/featured-image.jsx` - @tyxla #60915
- [x] `client/blocks/reader-featured-video/index.jsx` - @tyxla #60914
- [x] `client/blocks/signup-form/index.jsx` - @tyxla #63089
- [x] `client/blocks/shortcode/frame.js` - @tyxla #63085
- [ ] `client/blocks/keyring-connect-button/index.js`
- [ ] `client/blocks/user-mentions/add.jsx` @flootr
- [x] `client/blocks/site-preview/index.jsx` @flootr #63008
- [x] `client/blocks/global-notice/index.js` - @tyxla #60920
- [ ] `client/blocks/image-editor/image-editor-crop.jsx`
- [x] `client/blocks/image-editor/index.jsx` @flootr #62944
- [x] `client/blocks/image-editor/image-editor-canvas.jsx` #62946
- [x] `client/blocks/comments/form.jsx` @flootr #63087
- [x] `client/blocks/comments/post-comment-list.jsx` - @tyxla #61568
- [ ] `apps/o2-blocks/src/todo/item.js`
- [x] `client/lib/keyboard-shortcuts/README.md` - @tyxla #60127
- [x] `client/state/sharing/keyring/README.md` - @tyxla #60127
- [x] `client/state/sharing/services/README.md` - @tyxla #60127
