### ISSUE TITLE
Framework: Refactor away from `wpcom.undocumented()`

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#58458]
### Details

We’re in the process of removing `wpcom-undocumented` in favor of the `wpcom` library. Many have already been removed in recent PRs, but there are still some that need to be refactored and removed.

See p4TIVU-9KX-p2 for more details.

If you need a review or have any questions, please don't hesitate to ping @Automattic/team-calypso-frameworks.

### Checklist

- [x] `undocumented().jetpackLogin()` - @tyxla, #58575
- [x] `undocumented().jetpackAuthorize()` - @tyxla, #58575
- [x] `undocumented().jetpackIsUserConnected()` - @jsnajdr, #58943
- [x] `undocumented().settings()` - @tyxla, #58901
- [x] `undocumented().isDomainAvailable()` - @chad1008, #58243
- [x] `undocumented().checkAuthCode()` - @chad1008, #58956
- [x] `undocumented().getInboundTransferStatus()` - @chad1008, #58315
- [x] `undocumented().startInboundTransfer()` - @jsnajdr, #58945
- [x] `undocumented().getAvailableTlds()` - @tyxla, #58569
- [x] `undocumented().getDomainPrice()` - @tyxla, #58902
- [x] `undocumented().readFeedPost()` - @tyxla, #58650
- [x] `undocumented().readSitePost()` - @tyxla, #58650
- [x] `undocumented().readSitePostRelated()` - @tyxla, #58568
- [x] `undocumented().launchSite()` - @jsnajdr, #58952
- [x] `undocumented().themes()` - @tyxla, #58239
- [x] `undocumented().themeDetails()` - @tyxla, #58239
- [x] `undocumented().jetpackThemeDetails()` - @tyxla, #58239
- [x] `undocumented().installThemeOnJetpack()` - @tyxla, #58239
- [x] `undocumented().deleteThemeFromJetpack()` - @tyxla, #58239
- [x] `undocumented().activateTheme()` - @tyxla, #58239
- [x] `undocumented().uploadTheme()` - @tyxla, #58239
- [x] `undocumented().resendIcannVerification()` - @tyxla, #58990, #59234
- [x] `undocumented().fetchDns()` - @tyxla - #59056
- [x] `undocumented().updateDns()`  - @tyxla - #59056
- [x] `undocumented().applyDnsTemplate()` - @tyxla - #59056
- [x] `undocumented().applyDnsTemplateSyncFlow()` - @chad1008, #59146
- [x] `undocumented().getDnsTemplateRecords()` - @chad1008, #59146
- [x] `undocumented().transferToUser()` - @jsnajdr, #59059
- [x] `undocumented().transferToSite()` - @jsnajdr, #59059
- [x] `undocumented().changeTheme()` - @jsnajdr, #58999
- [x] `undocumented().isSiteImportable()` - @tyxla, #59007
- [x] `undocumented().fetchImporterState()` - @tyxla, #58545
- [x] `undocumented().updateImporter()` - @tyxla, #58545
- [x] `undocumented().uploadExportFile()` - @tyxla, #58545
- [x] `undocumented().getSiteConnectInfo()` - @jsnajdr, #59110
- [x] `undocumented().importReaderFeed()` - @tyxla, #58578
- [x] `undocumented().wordAdsApprove()` - @jsnajdr, #58862
- [x] `undocumented().initiateTransfer()` - @tyxla, #58239
- [x] `undocumented().transferStatus()` - @tyxla, #58897
- [x] `undocumented().oauth2ClientId()` - @jsnajdr, #58896
- [x] `undocumented().getDomainConnectSyncUxUrl()` - @tyxla, #59168
- [x] `undocumented().domainsVerifyRegistrantEmail()` - @tyxla, #58990
- [x] `undocumented().domainsVerifyOutboundTransferConfirmation()` - @tyxla, #59168
- [x] `undocumented().getMigrationStatus()` - @tyxla, #58944
- [x] `undocumented().resetMigration()` - @tyxla, #58944
- [x] `undocumented().startMigration()` - @tyxla, #58944
- [x] `undocumented().getAtomicSiteMediaViaProxy()` - @jsnajdr, #58903
- [x] `undocumented().getAtomicSiteMediaViaProxyRetry()` - @jsnajdr, #58903
- [x] `undocumented().getMatchingAnchorSite()` - @jsnajdr, #58991
- [x] `undocumented().me().getReceipt()` - @tyxla, #58510
- [x] `undocumented().me().getPeerReferralLink()` - @tyxla, #58449
- [x] `undocumented().me().setPeerReferralLinkEnable()` - @tyxla, #58449
- [x] `undocumented().me().sendVerificationEmail()` - @tyxla, #58452
- [x] Remove `wpcom.undocumented()` from `wpcom` - @tyxla, #59237
