### ISSUE TITLE
Marketing: Update copy to reflect premium themes updates

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#58780]
We can leave this until the last part of the sprint since premium themes need to be functional before we advertise them again.

Spreadsheet with prioritization and locations is in the project thread.

Everything under Phase I update is slated for the first launch.

**Comment by sixhours** [comment]
Related PRs/diffs:

- [x] D70966-code - H4: Update /pricing to re-add theme references
- [x] D70969-code - Signup: Re-add premium themes reference
- [x] D72931-code - Update Logged-out Homepage based on updated components
- [x] #59006 - Plans: Update feature list and FAQs with premium theme info
- [x] #58747 - Add premium theme ref to /start/plans
- [x] #58743 - Add premium theme ref to cart

**Comment by sixhours** [comment]
All phase I updates have shipped! 🥳
