### ISSUE TITLE
Blogger & Build Hero Flows: ship to all languages

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#58859]
## Background
In  #56862 we released the Blogger & Build Hero flows to en users only.   Translations are now ready, and we can begin the process to release to all customers.
https://translate.wordpress.com/deliverables/overview
https://translate.wordpress.com/developer/arthur791004

## Prioritised Task List
- [x] #58872
- [x] Post a CfT pdtkmj-1y-p2
- [x] Fix draft post modal translations p1638860644143300-slack-C02AED43D
- [x] Make sure the site is headstarted using the localised annotation file D71183-code pdtkmj-1y-p2#comment-6
- [x] #58979
- [x] Custom wrapping doesn't look good in some languages pdtkmj-1y-p2#comment-11
- [x] Deal with annotations that aren't translated (headstart uses "default" content) pdtkmj-1y-p2#comment-32 D72796-code
- [x] #59973

## Make Life Easier for Translators
- [ ] Add context for site intent copy pdtkmj-1y-p2#comment-27

## Other Non-Blockers
- [x] #58983
- [x] #59154
- [ ] Translate thumbnails. Need to add recommended theme demo sites to Block Pattern glotpress project pdtkmj-1y-p2#comment-34
- [x] French translation of domain placeholder seems wrong (not quite in scope) pdtkmj-1y-p2#comment-9

## Shipping Tasks
- [x] Announce to @jordesign and HE p1642122828116300-slack-CB0B2G43X
- [x] Annouce via an @channel on #blogger-experience p1642122847067600-slack-C029SB8JT8S
- [x] Release to all customers #59965
- [x] Add item to Ship Table pdgK6S-dL-p2

## Related & Prior work
Hero Flow: Write & Build intent screen #55603
Onboarding: Enable hero flow for English users only now #56862

**Comment by p-jackson** [comment]
Shipped by #59965
