### ISSUE TITLE
Improve the WooCommerce in-app landing page

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#59190]
### What

The landing page at /woocommerce-installation currently looks like this:

<img width="1184" alt="Screen Shot 2021-12-14 at 11 22 10 AM" src="https://user-images.githubusercontent.com/1689238/146037830-4e27038b-f9d6-4979-8b58-74c79a18f578.png">

But to match the new designs it should look like this:

![image](https://user-images.githubusercontent.com/1072756/151723220-00d8f395-708e-43ad-85a1-3709f45f1eaf.png)

### Why

Keep it on-brand and up-to-date.

### How

See https://github.com/Automattic/wp-calypso/pull/57918

**Comment by obenland** [comment]
@SaxonF We're considering this for our next sprint, starting January 31st. Is there a design version that is more current than the one in the "Woo on Atomic Review" figma that we should be looking at?

@ianstewart @allilevine

**Comment by obenland** [comment]
@SaxonF Have you had a chance to take a look at this yet?

**Comment by SaxonF** [comment]
Hey @obenland , I think we can have something for you by the end of the week.

**Comment by lsl** [comment]
@SaxonF could you update this issue with the new design / figma links? re changes in p1643266622311500-slack-C029UPVMGTW

**Comment by SaxonF** [comment]
We're changing direction with this a little bit. We want to start creating some consistency when it comes to empty states and upsell opportunities in the platform. We're going to use the same pattern found in the domains page when no domains have been added. In this case we'll add an extra content section below.

![image](https://user-images.githubusercontent.com/1072756/151723220-00d8f395-708e-43ad-85a1-3709f45f1eaf.png)
 
I'll chase up an illustration this week to replace the present.

r6eTqDpL2GGk96hcPLhsBb-fi-877%3A2069

**Comment by allilevine** [comment]
> We're going to use the same pattern found in the domains page when no domains have been added. 

- [ ] To do: see what we can repurpose from /domains/manage/< site id >
- [ ] See if we have a 3-col content section component and/or child components we can use.

**Comment by allilevine** [comment]
- Remove woop references from image folder we use (move up a folder, there may be another issue for this).
- "WooCommerce" should link to the WordPress.com plugin details page, not WooCommerce.com.

**Comment by lsl** [comment]
>  (move up a folder, there may be another issue for this).

We were thinking about this one https://github.com/Automattic/wp-calypso/issues/60349

> "WooCommerce" should link to the WordPress.com plugin details page, not WooCommerce.com.

I wonder if we should be pushing people through the installer when they click install from that plugin page / marketplace? Might be a bit early for now but I think I'd prefer that approach longer term.

**Comment by lsl** [comment]
From @SaxonF, icons we can use for the headers in the footer:

Run Your Store From Anywhere
```
<Gridicon icon="globe is-small" />
```

Learn with a global community
```
<Gridicon icon="user-circle is-small" />
```

Customize and extend
```
<Gridicon icon="story is-small" />
```

**Comment by lsl** [comment]
Top section mostly figured out in https://github.com/Automattic/wp-calypso/pull/60697 though there are a couple more [todo's](https://github.com/Automattic/wp-calypso/pull/60697#issuecomment-1026528667) to go.

![Screenshot 2022-02-01 at 17-41-21 WooCommerce — WordPress com](https://user-images.githubusercontent.com/811776/151925112-1569fd5e-02ef-4e55-bfb3-09c879fc57d0.png)

**Comment by allilevine** [comment]
> > "WooCommerce" should link to the WordPress.com plugin details page, not WooCommerce.com.
> 
> I wonder if we should be pushing people through the installer when they click install from that plugin page / marketplace? Might be a bit early for now but I think I'd prefer that approach longer term.

@lsl Can you expand on this? Do you mean that we should redirect people to this Woo installer flow when they click to install the plugin? Are you still in agreement about linking the colophon to the plugin page?

**Comment by lsl** [comment]
> @lsl Can you expand on this? Do you mean that we should redirect people to this Woo installer flow when they click to install the plugin? 

Yes, I think so, not something for this sprint, just thinking out loud.

> Are you still in agreement about linking the colophon to the plugin page?

Yes I think that's fine.

**Comment by lsl** [comment]
Remainder todo after https://github.com/Automattic/wp-calypso/pull/60697
- [ ] Replace illustration with new one (The shopping bags one is fine for now) https://github.com/Automattic/wp-calypso/issues/60791
- [x] Spacing / whitespace / margins need fixing up (I think Allison already cleaned this up in #60697, #60753 gets us the rest of the way)
- [x] Delete removed images (I don't think anything else uses them) https://github.com/Automattic/wp-calypso/pull/60742
- [x] Update colophon link to plugins/woocommerce/ https://github.com/Automattic/wp-calypso/pull/60739
- [x] Colophon sizing inline with figma https://github.com/Automattic/wp-calypso/pull/60754
- [x] Max width on the empty content div of 540px https://github.com/Automattic/wp-calypso/pull/60753
- [ ] The bottom section https://github.com/Automattic/wp-calypso/pull/60755
- [ ] Remove `_blank` target on Learn More perhaps use inline help link instead. (like other pages) https://github.com/Automattic/wp-calypso/issues/60792
- [ ] Header "WooCommerce" alignment should match heading in the footer section (left justify) https://github.com/Automattic/wp-calypso/issues/60790
- [ ] Icon alignment https://github.com/Automattic/wp-calypso/issues/60788
- [ ] 720 breakpoint https://github.com/Automattic/wp-calypso/issues/60789

**Comment by lsl** [comment]
I think we've shipped a good baseline for this. Lets close this.

There are a few more follow up [todos](https://github.com/Automattic/wp-calypso/issues/59190#issuecomment-1027488359) so I created new issues to track those independently and added them to the backlog.
