### ISSUE TITLE
Design Picker: include Premium Themes in all Personal & Free Plans with checkout flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#59229]
## Design Picker: Premium Themes with a checkout flow

Project Thread: pdgK6S-sR-p2

We are waiting for this dependency, pdgAPm-2Q-p2#comment-116, to be completed, likely in Jan 2022.

This work is a follow up to Design Picker: include Premium Themes in Premium and above plans #59025.    This work will allow users on free & Personal plans to see Premium themes in the DP, and allow the user to select these themes and go through a checkout process to upgrade their plan.

![image](https://user-images.githubusercontent.com/5665959/146107273-2a00148a-d111-411d-aeb6-31f0aa8eb69d.png)

![image](https://user-images.githubusercontent.com/5665959/146107301-694743d3-422c-4e33-9e5a-bd225346d6e7.png)

## User Facing Acceptance Criteria
- [x] Show premium themes to all users
- [x] Select Button becomes “Upgrade plan” instead of “Select {design}”
- [x] When user clicks Upgrade Plan on the theme, they will be taken through a checkout flow , directly to the checkout screen
- [x] The Premium Plan will be preselected in the checkout screen
- [x] After the checkout flow the User will be returned to the Design Picker screen 
- [x] User can then reselect their design of choice
- [x] User has ability to cancel in the checkout flow and be returned to the DP

## Dev Tasks
- [x] https://github.com/Automattic/wp-calypso/pull/60181
- [x] #60609
- [x] https://github.com/Automattic/wp-calypso/pull/60279
- [x] #60476
- [x] https://github.com/Automattic/wp-calypso/pull/60545
- [x] #60531

## Related 
Plan for Premium Themes pdgAPm-2Q-p2

**Comment by arthur791004** [comment]
>  Select Button becomes “Upgrade plan” instead of “Select {design}”

This should also apply to the top-right button when the user previews the theme.

> If a user wants to select a single theme, are they going to pay for a whole plan upgrade? Premimum Plan is $14/month if they pick monthly or $96/year. Is that a fair ask for a theme? Shouldn't it be a one off price?

Can the user pay for the theme rather than upgrade the plan? I'm not familiar with this part but I think the flow might be different. If we allow the user to pay for a theme, we should let the user go to next step (complete the Hero Flow) after checkout. However, if we request the user to upgrade the plan, I think it might be better to show the checkout as the modal and come back to the Design Picker after checkout. Then, they have a chance to browse other premium themes.

>  When user clicks Upgrade Plan on the theme, they will be taken through a checkout flow , directly to the checkout screen

I think showing the checkout flow as modal might be better and the user can easily close the modal and continue browsing the themes. After upgrading to the premium plan, they would see "Select {design}". On the other hand, we can also show the fullscreen checkout with the back button on mobile. This makes the user have the chance to go back to the Design Picker when they change their mind.

**Comment by arthur791004** [comment]
Note that we have two ways to use the premium themes

* Access premium themes for FREE with a premium or above plan
* Pay for the specified theme

![image](https://user-images.githubusercontent.com/13596067/148914635-5db1614e-0225-4f1a-bb30-624c5a3d4a73.png)

**Comment by autumnfjeld** [comment]
@arthur791004 Nice find!!!   @ianstewart was helpful in explaining why we should go with only offering upgrade to a paid plan, rather than offering to pay-per-theme: see slack convo p1639588915168600/1639587071.165900-slack-C029SB8JT8S

But maybe we could experiment with pay-per-theme pricing in a future iteration: p1639589182170200/1639587071.165900-slack-C029SB8JT8S.  We could measure if a user is more likely to pick a paid theme if they are offered a one-off price.   Ohhhh, that makes me wonder, maybe there are already stats that show this in theme showcase, how often a user is selecting to pay-per-design.

**Comment by p-jackson** [comment]
Launching 🎉 
pdgK6S-wB-p2
