### ISSUE TITLE
Analytics for the install flow / steps / user actions

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59478]
Add or improve tracks events for each step / action in the new installer flow.

- [x] Confirm click is provided by `submitSignupStep` usage [via this event](https://github.com/Automattic/wp-calypso/blob/90de6e7a658d438677bf81571f0ff30b21fc3e4c/client/state/signup/progress/actions.js#L71).
- [x] [Transfer](https://github.com/Automattic/wp-calypso/blob/57a61c13796924c35e41da868df1edd395e4ec4f/client/state/data-layer/wpcom/sites/atomic/transfers/index.js#L29) initiation
- [x] [Install](https://github.com/Automattic/wp-calypso/blob/57a61c13796924c35e41da868df1edd395e4ec4f/client/state/data-layer/wpcom/sites/atomic/software/index.js#L31) initiation
- [x] Landing page impression in wp-admin https://github.com/Automattic/wp-calypso/issues/59926
- [x] Checkout step required #60513
- [x] Checkout step not required #60513
- [x] Transfer completes - redirect https://github.com/Automattic/wp-calypso/issues/59926
- [x] Install completes - redirect https://github.com/Automattic/wp-calypso/issues/59926
- [x] Onboarding address step - `calypso_page_view` with path = `/start/woocommerce-install/store-address`
- [x] Onboarding info step - `calypso_page_view` with path = `/start/woocommerce-install/business-info`
- [x] Transfer attempts but times out  #60467
- [x] Install attempts but times out  #60467
- [x] Add site information to `calypso_woocommerce_dashboard_snag_error` https://github.com/Automattic/wp-calypso/pull/60560
- [x] Add more detailed error information (transfer or install status, exact error) to `calypso_woocommerce_dashboard_snag_error` https://github.com/Automattic/wp-calypso/pull/60560

**Comment by allilevine** [comment]
@lsl Have these been added/identified in https://github.com/Automattic/wp-calypso/issues/59926?

> Landing page impression in wp-admin
Transfer completes - redirect
Install completes - redirect

**Comment by allilevine** [comment]
> Transfer attempts but times out
> Install attempts but times out

Started PR here: https://github.com/Automattic/wp-calypso/pull/60467

**Comment by lsl** [comment]
> @lsl Have these been added/identified in #59926?

First two I think so, thanks for tidying that overlap up.

I'm not sure about the "Landing page impression in wp-admin" using @Rolilink's [suggestion](https://github.com/Automattic/wp-calypso/issues/59926#issuecomment-1020616330) to:
> track the wc-admin loading we can use the wcadmin_page_view event with the path attribute being home_screen." 

I couldn't see any tracks numbers that looked correct. 

That said, `calypso_woocommerce_dashboard_redirect` should cover this use case good enough for my needs.

**Comment by lsl** [comment]
@allilevine tagged the last two as done per https://github.com/Automattic/wp-calypso/pull/60467 this should be enough I think (at least to gauge where problems are / where to look closer / repro issues)

**Comment by allilevine** [comment]
> @allilevine tagged the last two as done per #60467 this should be enough I think (at least to gauge where problems are / where to look closer / repro issues)

@lsl We noticed that we don't get the site info in the recorded tracks event. See p1643228088275100/1643227044.271100-slack-C029UPVMGTW

**Comment by Rolilink** [comment]
Closed since we deployed all the PRs
