### ISSUE TITLE
Woo Installer: Add e2e test flows for the installer

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#59483]
We need to add e2e tests covering the new installation flows.

- [x] Using playwright
- [ ] ~Free > Confirm > Checkout > Transfer > Redirect to Woo~ See note [below](https://github.com/Automattic/wp-calypso/issues/59483#issuecomment-1026342356).
- [ ] ~Business (simple) > Confirm > Transfer > Redirect to Woo~ See note [below](https://github.com/Automattic/wp-calypso/issues/59483#issuecomment-1026342356).
- [ ] ~Business (atomic) > Confirm > Install > Redirect to Woo~ See note [below](https://github.com/Automattic/wp-calypso/issues/59483#issuecomment-1026342356).
- [x] "Setup my Store" click loads the /start/woocommerce-install url. https://github.com/Automattic/wp-calypso/pull/59548
- [x] Learn More opens the support dialog https://github.com/Automattic/wp-calypso/pull/59548
- [ ] Address step confirms + validates
- [ ] Business step confirms + validates
- [ ] Confirm step confirms
- [ ] Install only step redirects to wc-admin

**Comment by lsl** [comment]
TBD Will need to cover the new address / business info steps soon too.

**Comment by lsl** [comment]
Video of flow available here: p7DVsv-dp5-p2

**Comment by lsl** [comment]
Scope for Sprint 3: 

Our "done" for this sprint / issue = Have under test that the landing page "Setup my Store" click loads the `/start/woocommerce-install` url.

Stretch / if we have time:
- Address step confirms + validates
- Business step confirms + validates
- Confirm step confirms
- Install only step redirects to wc-admin

Definitely out of scope for Sprint 3:

Testing Atomic transfers is not currently an option and out of scope.

Testing the install flow is doable because the flow can run on a site with woo already installed but I would suggest it is out of scope to uninstall / deactivate before hand: It's easy to set up one atomic site for testing but you'll run into issues with multiple tests running on the same site at the same time if you need to assert woo installation takes place.
