### ISSUE TITLE
Marketplace: V1 Launch Checklist 🚀 

### ISSUE THREAD

**Issue by gavande1** [Automattic/wp-calypso#59893]
- [x] Remove automattician check from backend
- [x] Merge https://github.com/Automattic/wp-calypso/pull/59900
- [x] Merge https://github.com/Automattic/wp-calypso/issues/59657 only after release of V1 to production

**Comment by gavande1** [comment]
Backend diff: D72726-code

**Comment by gavande1** [comment]
Deployed r237876-wpcom

**Comment by gcsecsey** [comment]
### Testing checklist

#### [Plugins browser page](https://wordpress.com/plugins/?flags=marketplace-v1)
- [x] The new modal appears: 
  ![image](https://user-images.githubusercontent.com/11555574/148757746-1f3b4eb3-3950-4c98-a6b4-153248c585e3.png)
- [x] paid plugins appear as expected
- [x] free plugins appear as expected
- [x] pricing toggle works as expected
 
#### Plugin pages:
- [Paid plugin page (Woocommerce-subscriptions)](https://wordpress.com/plugins/woocommerce-subscriptions/?flags=marketplace-v1):
  - [x] Banner video is rendered
  - [x] Description renders correctly
  - [x] Plugin details (developer, rating, last updated, version) render correctly
  - [x] Billing period selector is rendered
  - [x] Billing period selector changes __the prices of both the plugin and the plan__
  - [x] CTA and USPs rendered correctly:
  ![image](https://user-images.githubusercontent.com/11555574/148759720-ebde0503-50b6-471e-8264-e8da906c92d5.png)
  - [x] Purchase and activate button throws the modal as expected:
  ![image](https://user-images.githubusercontent.com/11555574/148758503-1b236b25-0a60-4b9c-8a4d-ae292868705c.png)

- [Free plugin page (Woocommerce)](https://wordpress.com/plugins/woocommerce/?flags=marketplace-v1)
  - [x] Banner image is rendered
  - [x] Description renders correctly
  - [x] Plugin details (developer, rating, last updated, version) render correctly
  - [x] Billing period selector is rendered
  - [x] Billing period selector changes __the price of the plan__
  - [x] CTA and USPs rendered correctly:
  ![image](https://user-images.githubusercontent.com/11555574/148759657-5491da00-6f44-463c-96ef-b7a60e0ffbda.png) 
  - [x] Purchase and activate button throws the modal as expected:
  ![image](https://user-images.githubusercontent.com/11555574/148759441-71f22def-c908-40f4-8a90-566241967db7.png)


#### Checkout page:
- [x] (Free site) Removing the plan removes the plugin from the cart
- [x] (Free site) Plugin can be removed from the cart, the plan remains
- [x] Plan period can be edited from the checkout page
- [x] Taxes are added correctly for US ZIP codes

**Comment by cpapazoglou** [comment]
Closing this issues as all dependencies have been deployed.
