### ISSUE TITLE
"Add a new site" A/B testing /new vs /start

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60166]
## Description
This is part of the the FSE rollout, in that once the FSE beta prompt is removed from the /new flow, we can start the A/B test.  See recent FSE rollout timeline  p58i-bWs-p2

Redirect a portion of  logged in existing customers to /start instead of /new for an A/B test
See Mikael's overview post for more details: pbxNRc-1eh-p2
Slack convo with Mikael: p1642139591064500-slack-CRWCHQGUB

## Tasks
- [ ] Identify edge cases or potential bugs: testing to see what happens when users go through /start flow multiple times
- [x] a8cexperiments post (Mikael)
- [ ] Create  experiment plan (see tips below) on bxNRc-p2
- [ ] Set up Abacus test 
- [ ] Set up AB test code, should be quickie (Ganon)
- [ ] After experiment, if the /start test does no harm; deploy the "Add a new site" button redirection (Ganon).

## Tips on running an  experiment. 
* FG: The Experimentation Platform   PCYsg-tdK-p2
* Experiment checklist: https://github.com/Automattic/experimentation-platform/wiki/Experiment-Checklist
* Check out links in the sidebar of a8cexperiments p2: bxNRc-p2

Very rough guideline of steps:
1. Post the experiment plan on bxNRc-p2. Here's an example from the Welcome Tour experiement pbxNRc-Cb-p2 You may not need to include so much detail, perfectly fine to keep it simple.
2. Create the abacus experiment (I had to do about 4 versions of this til I got it right)
3. Set up experiment code : https://github.com/Automattic/experimentation-platform/wiki/Experiment-Code-Setup-Guides
4. Run the experiment
5. Analyze the results.  This may require pulling in help from the data team, because the analysis uses terminology and concepts that aren't really targeted a "lay people" :) 

This wiki is a great guideline to follow: https://github.com/Automattic/experimentation-platform/wiki/Experiment-Checklist#implement-and-launch

 @razvanpapadopol is now in the experiment group, so he would be a great resource to ask for help!

**Comment by autumnfjeld** [comment]
-
