### ISSUE TITLE
Remove unused signup flows

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60281]
## Description

As per Tracks trends in 2b63f-pb, ecommerce-onboarding, simple, main, and developer flows don't seem to get any traffic.  We will remove these flows from the code.  See prior discussion & work: https://github.com/Automattic/wp-calypso/pull/60142#pullrequestreview-856523377

## Related
https://github.com/Automattic/wp-calypso/pull/60142
https://github.com/Automattic/wp-calypso/issues/56264

Signup: reskin minor flows #60142
Remove unused signup flow code #56264

## TODO

- [x] https://github.com/Automattic/wp-calypso/pull/60944
- [x] https://github.com/Automattic/wp-calypso/pull/60945
- [x] https://github.com/Automattic/wp-calypso/pull/60947
- [x] https://github.com/Automattic/wp-calypso/pull/60948

**Comment by michaeldcain** [comment]
I know there's not traffic to support it, but I kind of wonder if we should leave the `reader` flow. For a person that only wants to use our product as a feed reader, it's a good flow, low-maintenance (only a landing page and the account page), and drops the user directly into the reader. 

I think the lack of traffic has to do with our having removed the logged-out reader landing page. To test this hypothesis, I'm going to add a link to the flow to the top of [Reader support documentation](https://wordpress.com/support/reader/) and see if the numbers change :). If we decide to still remove the flow, we can just remove the link from the doc.

**Comment by arthur791004** [comment]
Close it as all of the ecommerce-onboarding, simple, main, and developer flows are removed

**Comment by michaeldcain** [comment]
> To test this hypothesis, I'm going to add a link to the flow to the top of [Reader support documentation](https://wordpress.com/support/reader/) and see if the numbers change :)

Just to follow-up a month later, it looks like ~15-20% of people that visit the Reader support doc end up clicking that button. It's still low numbers, but possibly worth keeping the flow around since it's a decent, low-maintenance experience for both new and existing users.
