### ISSUE TITLE
Intent Screen Iterations: analysis and suggestions on A/B tests to run

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#60424]
## Description
TODO
Iterating on the Intent Screen P2: pdgK6S-un-p2

## Tasks
- [ ] tracks & funnel analysis
- [ ] P2
- [ ] decide on what we should change & get buy in
- [ ] run A/B test
- [ ] make sure not to conflict with Importers or othe intetn screen work

**Comment by autumnfjeld** [comment]
Closing since Goals Screen is launching next week, and will replace Intent Screen.
