### ISSUE TITLE
☂️  [Spike]:  Verticalization of patterns to create themes in the FTM Design Picker

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#61198]
## Description
Project Thread: pbxlJb-XO-p2
Design Concept: pbAok1-2rq-p2
Important reading for PTK tech: PCYsg-t0i-p2

## Acceptance Criteria
Create a Proof of Concept to demonstrate Verticalization of patterns in the Design Picker in FTM onboarding flows.

**An example scenario:**
8 A user has selected "Restaurants" as their vertical
* A Restaurant vertical is defined to be four block patterns from 2bba8-pb
* The patterns are fetched from from the dotcompatterns repository 
* Patterns are assembled into a preview-able dynamic theme 
* The dynamic theme is shown in the Design Picker

We will need to mock/hard code some of the steps above, for example we don't need to build out the Verticals screen 2bba9-pb  initially. But after the core spike work is done, we may want to add that just for show-and-tell purposes. And of course many steps have been glossed over, we can add detail during Verticals Kickoff.

**Things to note or report on**
- [x] Shortcomings of the PTK for this use case
- [x] What happens when creating a site without headstart? pbxlJb-10W-p2
- [x] Can we use the Editor as the tool for creating a static preview?
- [x] Issues assembling the patterns into a theme "on the fly"
- [x] Headstart complexity
- [x] How will this fit in with the big picture of  Generated Themes pulling in verticalized patterns, images, and text?
- [x] What else is of concern?
- [x] Should we be getting the page skeleton using the theme demo site like the `template/demo` does
- [x] What are the recommendations for building a shippable MVP?

### Dev Tasks / list of PRs
- [x] New API similar `template/demo`, except it accepts a theme id and vertical id
- [x] API returns previewable HTML, similar to the `template/demo` API
- [ ] Assemble preview response with a hardcoded set of restaurant patterns accessed from the dot com patterns library
- [ ] Assemble the preview using a page skeleton that doesn't use the theme demo site? Can we render theme templates directly instead?
- [ ] Feature flag in Calypso to request previews using new API

**Comment by roo2** [comment]
> A user has selected "Restaurants" as their vertical
> - A Restaurant vertical is defined to be four block patterns from 2bba8-pb [patterns API]

I'm trying to confirm how exactly we define a vertical, for block based themes, would they also potentially define content for different template parts or block patterns defined by the theme?

I'm looking at [twentytwentytwo theme](https://github.com/WordPress/twentytwentytwo) for example, it looks like the blog headline [comes form the header pattern](https://github.com/WordPress/twentytwentytwo/blob/trunk/inc/patterns/header-large-dark.php#L24). So in order to verticalize a preview (and starter content) for the theme, we would also need a way to update at least some patterns(?)

**Comment by autumnfjeld** [comment]
@roo2  This is how I am thinking about verticals at this _ early stage_:

* The existing block based themes in the DP (at wordpress.com/start/setup-site?siteSlug=somesite.wordpress.com ) are not really tailored to any vertical, they are super generic.   If someone picked "car racing association" or "restaurenat" most of the existing block based themes don't make sense
* Thus we know work will need to be done by the design team to create  Verticalized themes from our block patterns, and likely they might have to make new block patterns that are useful to the various verticals. 

TT2 is very much a blog theme. It's probably not ideal for most verticals.   But let's use it for discussion purposes: say a user has come to blog about fashion, and chooses TT2. Then we would want to populate TT2 with fashion images and appropriate text, probably including header text.  The site should look like a fashion blog.

> I'm looking at [twentytwentytwo theme](https://github.com/WordPress/twentytwentytwo) for example, it looks like the blog headline [comes form the header pattern](https://github.com/WordPress/twentytwentytwo/blob/trunk/inc/patterns/header-large-dark.php#L24). So in order to verticalize a preview (and starter content) for the theme, we would also need a way to update at least some patterns(?)

You've got the exact right idea with these questions.   We would want to be able to verticalize any text, including text in the patterns.  @p-jackson talked a little bit about this yesterday when he was giving us a tour of the PTK pattern library.

**Comment by p-jackson** [comment]
Created D75775-code: a proof of concept to use the PTK to render specific block patterns as they would appear in a FSE theme (instead of stand-alone like in the block pattern previewer)

`https://public-api.wordpress.com/rest/v1.1/template/demo/pub/bennett/dotcompatterns.wordpress.com/?use_patterns=true&post_id=157&language=en&keep_page_wrapper=true` generates this demo
<img width="1560" alt="Screenshot 2022-02-28 at 6 35 04 PM" src="https://user-images.githubusercontent.com/1500769/155929725-b655aa75-ebb9-4700-a54d-bd85bde67ba6.png">

Which is a menu block pattern rendered within the Bennet page.

**Comment by autumnfjeld** [comment]
@arthur791004 & @fushar I think we can close this spike ticket now, and then I/we can create more specific issues for the project.  Do you agree?

**Comment by fushar** [comment]
Yes, that makes sense!

**Comment by arthur791004** [comment]
Sure, that sounds good 👍
