### ISSUE TITLE
☂️  [Spike]: Verticalization of images in themes, templates, & patterns

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#61228]
## Description
Project Thread: pbxlJb-Y8-p2
Part of Verticals in Onboarding project

## Acceptance Criteria

Create a POC that demonstrates the following:

* Identify a vertical, a theme, and relevant images for this prototype. Note that a theme may need horizontal, square or vertical image.
* For an identified vertical, say weddings or shoe stores, search the Vertical Images Source PduBjF-5-p2 and pull a relevant set of images  
* Insert the images into the theme preview in the Design Picker
* Show the same images in the starter content (this step might be a secondary spike)

**Things to note or report on**
- [ ] Shortcomings of the Vertical Images Tool / Source site p9Jlb4-3ph-p2
- [ ] Issues setting the theme to use dynamic images instead of own theme images
- [ ] Headstart complexity
- [ ] Will we need to worry about a "color" theme with images, e.g. black & white vs color image or "country wedding" vs "formal wedding"
- [ ] Do colors of images clash with the theme?
- [ ] How will this fit in with the big picture of  Generated Themes pulling in verticalized patterns, images, and text?
- [ ] What else is of concern?
- [ ] What are the recommendations for building a shippable MVP?

## Dev Tasks
- [x] #61399
- [x] #61400
- [x] #61401

## Related

Project Thread: pNEWy-eFy-p2
Vertical Image Curator: p9Jlb4-3ph-p2
The lifecycle of a vertical Headstart annotation: PaWIov-3k-p2

**Comment by arthur791004** [comment]
Close it as we have already done all of the spikes to verticalize the images in themes, page templates, and block patterns.

You could check the result as followed:
* pbxlJb-190-p2
* pbxlJb-1l7-p2
* pbxlJb-1ow-p2

And here is the PR - D76068-code

Our next step is to find the best substitutions to improve the results after the verticalization of images. See https://github.com/Automattic/wp-calypso/issues/62198 and pbxlJb-1lY-p2.
