### ISSUE TITLE
☂️ [Spike]: Verticalized text in themes, templates, patterns

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#61305]
## Description
Project Thread: pbxlJb-XO-p2
Part of Verticals in Onboarding project
This is lower priority than #61198 #61228 -- and likely those two pieces of work are needed before the verticalized text feature can be designed.   This may be as much of designing a data flow as a code task. 

## Acceptance Criteria

Create a POC that demonstrates the following:

* Identify a vertical, a theme, and sample text for this prototype. 
* For a chosen vertical, say weddings or shoe stores, the text in the pattern or theme should be related to the vertical 
* The themes shown in the Design Picker contain the verticalized text
* The start content contains the verticalized text
* Text must be translated in i18n supported languages 

**Things to note or report on**
- [ ] Where will this text be sourced from?
- [ ] How will it work with i18n translation processes?
- [ ] How will this fit in with the big picture of  Generated Themes pulling in verticalized patterns, images, and text?
- [ ] What else is of concern?
- [ ] What are the recommendations for building a shippable MVP?

## Dev Tasks
- [ ]  task/PR 1
- [ ]  task 2

## Related
☂️ [Spike]: Verticalization of images in themes, templates, & patterns #61228
☂️ [Spike]: Verticalization of patterns to create themes in the FTM Design Picker #61198

Project Thread: pNEWy-eFy-p2
Vertical Image Curator: p9Jlb4-3ph-p2

**Comment by autumnfjeld** [comment]
Closing this since we will be moving to the idea of "Tailored Copy" for specific patterns and usage of generic copy.
