### ISSUE TITLE
☂️ [Spike]: Verticalize starter content (headstart)

### ISSUE THREAD

**Issue by roo2** [Automattic/wp-calypso#61350]
## Description
As part of the verticalization in onboarding (build flow) we want to start understanding the technical aspects of copy injection into Block Patterns. PT: Verticalized text in themes & patterns: pbxlJb-YI-p2

## ToDo
- [x] Find out the background and approach that Mikeal and others invisioned for creating starter content for FSE themes pNEWy-eFy-p2
- [ ] Decide if we want to use headstart or something else for FSE themes going forward
- [ ] Come up with a possible technical solution for inserting:
  - [ ] Translated, verticalized, posts
  - [ ] Translated, verticalized, page templates (and determine where this data comes from)
  - [ ] Translated, verticalized template parts
  - [ ] Translated, verticalized block patterns (is this neccessary?)
  - [x] Verticalized images and other media
  - [ ] Identify other things that need to be inserted

Implementation notes:
Will likely use results of PTK API being worked out in #61198

## Related 
☂️ [Spike]: Verticalization of images in themes, templates, & patterns #61228
☂️ [Spike]: Verticalization of patterns to create themes in the FTM Design Picker #61198
pbxlJb-10E-p2

**Comment by roo2** [comment]
Will also do a research and a spike on modifying FSE theme content e.g. the twentytwentytwo header

**Comment by autumnfjeld** [comment]
@roo2  Is this work still ongoing?  Or could we consider your post pbxlJb-10E-p2
 the outcome of this spike investigation?

I do think we need to define some new github issues specifically about  the user's starer site. Hoping we are at a point where we can define more specific explorations.

**Comment by roo2** [comment]
I'd say that pbxlJb-10E-p wrapped up the idea of replacing template parts on block based themes. 
Arthur has since done some spikes around headstart supporting a recipe with block patterns and replacing images which I believe were successful but we will now need to take into production.

**Comment by roo2** [comment]
We've investigated various aspects of this 
pbxlJb-1l7-p2
pbxlJb-1nH-p2

I think we can close this spike ticket in favor of future work
