### ISSUE TITLE
Flux to Redux: Plans, Domains & Purchases

### ISSUE THREAD

**Issue by scruffian** [Automattic/wp-calypso#6144]
As outlined in #5046 we need to move the `/plans`, `/purhcases` and `/domains` to Redux. The work can be broken down like this:
#### ~~Plans~~
- [x] Move "plansList" data to redux and remove localStorage dependency. #5444 
- [x] Add `QuerySitePlans` component. #4933
- [x] Remove plans flux stores. #10155
- [x] Create `QueryPlans` component. #5444 
#### Domains
- [ ] Create `QueryDomains` component.
- [ ] Stop using `StoreConnection` in domain management.
- [x] Remove domains flux stores.
#### Purchases
- [x] Move existing reducer in `client/lib/purchases/reducer` to `client/state/` #6317
- [x] Create `QueryPurchases` component. #6317
- [x] Stop using `StoreConnection` in purchases. #6317
- [x] Remove purchases flux stores. #6647
- [ ] Remove unused purchases reducer

This issue is to investigate how much work this will be and how we will approach it.

**Comment by drewblaisdell** [comment]
I added a checkbox to this and #5046 to add a `purchases` reducer.

**Comment by fabianapsimoes** [comment]
@scruffian is "Remove plans flux stores" done or still pending?

Removing `Purchases` since we're done with the things under that label.

**Comment by scruffian** [comment]
The last checkbox for plans is still pending...

**Comment by klimeryk** [comment]
Just FYI, there's already a `QueryDomains`-like component: https://github.com/Automattic/wp-calypso/blob/ba85297f6f21d08cd2c693040b8c2c3b2ac03185/client/components/data/query-site-domains/README.md So hopefully you can re-use it here. The old store is slowly being removed from domains code - glad to see this push! Please add @Automattic/cobalt to reviewers when you get this part - would love to help test and review 🙇
