### ISSUE TITLE
☂️  Vertical question step in onboarding

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#61526]
## Description
 Project Info: pbxlJb-Zj-p2 
We will be adding a verticals question into the onboarding process. As a first iteration we can put this just after the intent screen. Keep in mind that this work may involve syncing up with other teams, making sure we understand if we are using the current list of verticals in the API, https://public-api.wordpress.com/wpcom/v2/verticals,  or if there are different business requirements.   We also might have an MVP subset of verticals for the MVP.  Lots of parameters still being discussed. 

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/5665959/155929923-acaa726f-373a-48d2-b87a-4e83e1e83d5b.png">

This old component could possibly be reused: Gutenboarding: Remove disabled vertical input #59307

## Acceptance Criteria
- [x] Designed to Figma specs: 42PgVsdlQ1v2wpk6lmmrnq-fi-461%3A11368
- [x] fetch a list of verticals from verticals API  (TBD if we will use a subset of verticals for an MVP)
- [x] chosen vertical is tracked (tracks event)
- [x] chosen vertical is stored in site preferences
- [x] Share / get input from Serenity as needed
- [x] Show a list of featured verticals when the input field is empty and focused
- [ ] Once merged, share with Mike to get feedback on how API is working

## Dev Tasks
- [x] consult with @Team/Vertex pdDR7T-1l-p2 about the modernization work going on in onboarding flows
- [x] Review prior work: #59307
- [x] https://github.com/Automattic/wp-calypso/pull/62365
- [x] https://github.com/Automattic/wp-calypso/pull/62611
- [x] 776-gh-Automattic/tracks-events-registration 
- [x] https://github.com/Automattic/wp-calypso/pull/62871
- [x] https://github.com/Automattic/wp-calypso/issues/62582

## Related
Slack convo with tips from Mikael: p1646638400175699/1646631074.164809-slack-CDPL9US68
Prior work: Gutenboarding: Remove disabled vertical input #59307

**Comment by autumnfjeld** [comment]
@Automattic/ganon  

![bitmoji](https://sdk.bitmoji.com/render/panel/6ce76d26-9c7a-4fd2-8675-f5d4225363d6-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=39)

I just created this issue for the Design Picker: https://github.com/Automattic/wp-calypso/issues/62237
Making a note of that because the Verticals Screen step described above will save the vertical in site preferences, and the Design Picker will fetch the vertical in order to display the right designs.  

In addition, we should think not only about the "exact vertical" but also the parent grouping that is saved in the verticals data object pbxlJb-1oG-p2 .  
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5665959/160056369-05275c02-2d38-457b-b34a-0925b6512afa.png">
 
For example: perhaps we would present the same marketing/business design to all those verticals shown in the screenshot.  (That is just an example to illustrate use of hierarchy, actual verticals are not yet nailed down for MVP.)

**Comment by roo2** [comment]
**Future performance improvement:**

In the verticals selector, we currently send a request to the server whenever the user types and then wait to show them results. We added a spinner to make this experience nicer.

https://user-images.githubusercontent.com/22446385/164354876-cb3e5785-a83e-40c6-8aa0-eabfe96d7bce.mov

I realized that it would be possible to avoid this loading experience entirely if we preloaded the list of verticals and filtered them on the client side. Then suggestions could be returned practically instantly. Since the total data returned by https://public-api.wordpress.com/wpcom/v2/verticals is only 66kb when gzipped, I think it's reasonable.

I don't think we need to do this for MVP, but in future it would improve the experience :)

I got the idea after reading an article that @bangank36 linked about apparent performance
https://github.com/Automattic/wp-calypso/blob/trunk/docs/reactivity.md
https://rauchg.com/2014/7-principles-of-rich-web-applications

**Comment by taipeicoder** [comment]
I like the idea of offloading more data processing to the client side! There are some considerations that we will need to weight against to see if it's worth the trade-off:

The API is reusable across technologies, meaning that other teams (e.g.: mobile) can also access the same functionalities without having to re-implement them. This is especially important as the suggestion "algorithm" grows in complexity (if ever) and beyond simple text matching. The current API, while still in its infancy, already assigns weights to each suggested term.

💯  agree that apparent performance is very important, especially during onboarding! I wonder what kind of pre-optimizations we can do down the road to make the experience snappier. I think, for instance, removing the 150ms debounce will make it already snappier, at a cost...

**Comment by taipeicoder** [comment]
Thanks everyone for the reviews of this initial work! As we move towards a more iterative cycle, we will be closing this issue and create new ones as needed. We have plans of staging a CfT in a week or two, and we'll pick it up from there.

**Comment by taipeicoder** [comment]
@roo2 I have created a [spike](https://github.com/Automattic/wp-calypso/issues/62940) for what you mentioned. I feel that it's something very worth exploring 😄
