### ISSUE TITLE
Marketplace: Add Sensei Pro

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#61547]
### Details

- [ ] Adding in `store_products`. Prices can be found in the spreadsheet of next woo extensions (Pdh6GB-2Y-p2)
- [ ] Adding in `https://public-api.wordpress.com/wpcom/v2/marketplace/products` endpoint (`featured: false`)

Plugin icon: p1646132379334519/1646085228.310919-slack-C07418EJ0
![SenseiPro](https://user-images.githubusercontent.com/1689238/156180697-16abfeaf-fb7e-475d-bad0-8c76961574a4.svg)

Documentation: PCYsg-AhH-p2
PT: pdh6GB-lx-p2

**Comment by lsl** [comment]
- [x] Create a catalog product and yearly plan
- [x] Create monthly plan against the same product
- [x] Sync the new catalog product and plans from store sandbox to production
- [x] Add catalog product id constants - D76056-code
- [x] Add store product to catalog product mapping - D76057-code
- [x] Generate the legacy store_product records
- [x] Add a store product name for translation - D76326-code
- [x] ~Notify accounting on a8cscorecard p2~ No longer required see: p1646859940177699-slack-C08JMM3LN
- [x] Add new marketplace product entry - ~D76063-code~ D76441-code
- [x] Add vendor info
- [x] Make an atomic p2 request to have the plugin be flagged as managed p9o2xV-1Wj-p2 
- [ ] ~Confirm plugin is purchase-able and installs on purchase~ https://github.com/Automattic/wp-calypso/issues/61882
- [ ] ~Remove a11n only flags~ https://github.com/Automattic/wp-calypso/issues/61883
- [ ] ~Clear product cache?~ https://github.com/Automattic/wp-calypso/issues/61881

**Comment by lsl** [comment]
Bit blocked at the minute, update in D76063-code and p1646715767620249-slack-C029JEQRVRT

**Comment by lsl** [comment]
Updated everything to use `woothemes-sensei` as the slug and created new product / plans in prod for legacy mapping.

**Comment by lsl** [comment]
This is mostly "done", ~leaving open until it's fully launched~ might actually close this and break out any remaining tasks: added three new tasks to the list. @gcsecsey is there some kind of product cache blocking this from showing in prod for a11n users? I recall being able to see yoast as a11n in but I think that's changed or something.

**Comment by lsl** [comment]
https://github.com/Automattic/wp-calypso/issues/61881
https://github.com/Automattic/wp-calypso/issues/61882
https://github.com/Automattic/wp-calypso/issues/61883
