### ISSUE TITLE
Woo Pre-Orders: Create store_product's

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#61887]
### Must complete first: 
- [x] https://github.com/Automattic/wp-calypso/issues/61885
- [x] https://github.com/Automattic/wp-calypso/issues/61886 
- [x] https://github.com/Automattic/wp-calypso/issues/61895

Generating legacy store products without supporting code deployed results in warning pings in #payments-dev and potentially other issues.

### Tasks 
- [x] Generate the legacy `store_product` table entries for the yearly plan using the `create-store-product-entry-from-plan` sub-command
- [x] Repeat for the monthly plan, ensuring you correctly match the ID's to plan slugs

Running the script requires passing in both:
- The billing catalog plan slug for the USD variant we created in https://github.com/Automattic/wp-calypso/issues/61885, this plan_slug can be queried from db tables, the docs has an example of this PCYsg-CJy-p2 under the "generate the legacy" heading.
- And the matching product id we reserved in the previous steps

Running the command prompts a series of questions, use the table below to answer:

| Question  | Answer | Notes |
| ------------- | ------------- | ------------- |
| product_name  | Hit enter | To select the default option, should be same as given in https://github.com/Automattic/wp-calypso/issues/61885 |
| product_type | `marketplace_plugin` | All marketplace plugins get this type |
| product_slug  | Hit enter | To select default option, should be a snake_cased version of the billing catalog product slug given in https://github.com/Automattic/wp-calypso/issues/61885 |
| available | y | Yes, this only makes it available for sale, it doesn't make it available to users yet. |
| multi | n | Users should only be able to purchase a single copy of a plugin on each site |
| Final confirmation | y | Assuming everything was entered correctly and looks good, y |

**Comment by paulopmt1** [comment]
## How to validate

1. Make sure the product is on the production `store_products` table: `gpr select * from store_products where product_slug like 'woocommerce_pre_orders_%`. You should see monthly and yearly plans:

### Validate:
- Product IDs: should be the same registered in [this step](https://github.com/Automattic/wp-calypso/issues/61886), available here on Phabricator: D76804-code
- All the other values are available in this issue description table.

**Comment by lsl** [comment]
We don't really need to review these ones but LGTM!
