### ISSUE TITLE
Marketplace: add Jetpack Search

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62025]
Relevant PT comment: pdh6GB-s7-p2#comment-958
Documentation: PCYsg-AhH-p2

We need to add Jetpack Search as a plugin that can be purchased via the Marketplace. However, Jetpack Search is really a service that's already available on WordPress.com. See https://wordpress.com/jetpack-search/

- [x] Plan for how to create a Marketplace product that when purchased activates the Jetpack Search billing plan. #62177
- [x] Change [the inactive/active logic](https://github.com/Automattic/wp-calypso/pull/61389) in Calypso to show when Jetpack Search is active.
- [x] Handle Jetpack Search (as a preinstalled premium plugin) in the Marketplace. #65125
- [ ] Handle Jetpack Search in the Marketplace's `PluginsBrowserList`.

Design:
- [x] Needs Jetpack Search logo, see pdh6GB-s7-p2#comment-966

**Comment by allilevine** [comment]
Start with timeboxed investigation: is this possible? Develop a plan.

**Comment by lsl** [comment]
Timeboxed some thinking, suggested an alternative approach here: pdh6GB-s7-p2#comment-1079

**Comment by allilevine** [comment]
See: pdh6GB-s7-p2#comment-1081
This is blocked until Jetpack Search is available as a standalone plugin. 
We're also planning to add a JITM for Jetpack Search, but it needs design: https://github.com/Automattic/wp-calypso/issues/62355

**Comment by gibrown** [comment]
The standalone plugin is now available: https://wordpress.org/plugins/jetpack-search/

**Comment by allilevine** [comment]
> The standalone plugin is now available: https://wordpress.org/plugins/jetpack-search/

@Copons

**Comment by Copons** [comment]
This can be closed by the release of https://github.com/Automattic/wp-calypso/pull/65125 a couple of weeks ago, which makes Jetpack Search purchasable through the Marketplace.

There is room for polish and to tackle minor issues, but we'll consider them regular maintenance.
