### ISSUE TITLE
Marketplace: Change popular search terms

### ISSUE THREAD

**Issue by allilevine** [Automattic/wp-calypso#62266]
Update the popular search terms in the search header to reflect search data. Hard-coded, update biweekly.  `calypso_plugins_search_results_show` is a track event that has the search_term as a prop. 

Acceptance criteria:
- [x] See p1648138858900379-slack-C029JEQRVRT (priority) - #62351
- [x] There are no specific products in the search terms.  -> #62361
- [x] The search terms more accurately reflect the data we have. -> #62361
