### ISSUE TITLE
☂️ Improvements to Verticals API behavior and data quality

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#62449]
## Description
Iterate on Verticals API's behavior and data quality. 

## Improvements
- [x] Use exact matching for synonyms instead of partial matching (D78006-code)
- [x] Matching synonyms to return the vertical name instead of synonym text (D78909-code)
- [x] Show featured verticals when user has not yet typed in any text (D78352-code)
- [x] Generate site verticals v2 synonyms without text splitting (D79076-code)
- [x] Add parameter expand_root to determine whether to expand the vertical root property (D79293-code)

## Dev tasks
* ✅ D78006-code
* ✅ D78352-code
* ✅ D78909-code
* ✅ D79076-code
* ✅ D79293-code

## Related
#61526
