### ISSUE TITLE
Flaky E2E: Support search

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#62778]
### Spec file

support__popover-invalid.ts / support_home.ts

### TeamCity ID

7741506 (but there are many)

### Logs

It appears that the response we are waiting for is often not received:

```
page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
at SupportComponent.search (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/support-component.ts:217:14)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/support/support__popover-invalid.ts:51:27)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

### Tasks

- [ ] Try to reproduce the issue today (September 2022).
- [ ] Identify which line is the culprit.
- [ ] Determine a path to fix the call.

**Comment by worldomonation** [comment]
@john-legg I've assigned you this flaky e2e spec task. This one will require you to take a look at the entire e2e spec and possibly require restructuring of the test steps. If you do not yet feel comfortable, feel free to wait until I return.

The gist of this flaky e2e report is that we have a spec, `support__popover-invalid` and `support_home` which both test the Inline Help feature in Calypso. 

In both situations, there exists some step where the `page.waitForResponse` event times out.
What makes this issue a bit challenging is that the line numbers for both the spec (`support__popover-invalid`) and the root POM file (`support-component.ts`) does not line up with the actual file today.

It may be required to run this locally and many times in order to debug this issue.
I strongly suggest taking advantage of the additional env vars we support to make life easier, noted on [this page](https://wpcalypso.wordpress.com/devdocs/test/e2e/docs/environment_variables.md?term=authenticate_accounts) and also reference the [how to run tests on your machine](https://wpcalypso.wordpress.com/devdocs/test/e2e/docs/tests_local.md) page to help make debugging life a bit easier.

**Comment by john-legg** [comment]
After running `support__popover-invalid` and `support_home` multiple times locally, I haven't been able to replicate the issue. I ran the tests on different build environments as well as through the debugger and they still pass every time. 
@worldomonation mentioned that the next steps should be:
- [ ] Decide whether or not to re-enable the test.
- [ ] If re-enabled, determine for which test suites (Calypso E2E, pre-release tests only, etc).

**Comment by worldomonation** [comment]
I am in favor of re-enabling at least one of the specs with the group `calypso-pr`, which would enable it to run on _every commit on every branch except for trunk_. 

After enabling, it would be good to monitor the pass/fail rate of this spec. Once we establish that this flakiness is gone then re-enable the other one.

How does that sound @john-legg?

**Comment by john-legg** [comment]
Sounds good to me, @worldomonation! I noticed that `support__popover-invalid.ts` actually [has the calypso-pr group already](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/support/support__popover-invalid.ts#L2) and I haven't seen any failures in TeamCity, so I'll update `support__home.ts` instead. Thanks for your guidance!

**Comment by worldomonation** [comment]
FYI I caught news of the new Help Centre, which might pose an issue for the `support__popover` series of specs:
p7DVsv-fpN-p2

I'll be contacting the team responsible to see if we can coordinate a release that won't end in failed Pre-Release Tests.
