### ISSUE TITLE
Marketplace: Prepare the Plugin Browser UI for scaling and advanced search

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#62935]
In SOTB, we identified the marketplace / plugins code we think we need to refactor or replace, in order to scale the Marketplace UI and search. p1650403911852059-slack-CKZHG0QCR

- [x] Rework or replace UrlSearch (at least in the marketplace codebase) with something other than the HOC it is today https://github.com/Automattic/wp-calypso/issues/63013
- [ ] Rework how search is executed, at the moment it happens in lifecycle methods this should probably happen in a hook instead https://github.com/Automattic/wp-calypso/issues/63014
- [x] Rework [the controller](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js), it currently has a lot of duplicated handlers - old routes and redirects, use /plugins/browse/category for categories, remove dual plugin-category route https://github.com/Automattic/wp-calypso/issues/63030
- [ ] Similarly, rework [the index](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js), it has a lot of duplicate endpoints - same as above to clean things up https://github.com/Automattic/wp-calypso/issues/63030
- [ ] Rework [the pluginsbrowser](https://github.com/Automattic/wp-calypso/blob/115363bdb05ae5e986486b41fbd2b64c21ceb26e/client/my-sites/plugins/plugins-browser/index.jsx), currently has 4-5 components to render a list of plugins - remove all fetching, paid plugins fetched on every render, potential usePlugins hook - #63191 and #63192

**Comment by lsl** [comment]
Sprint call: I'll create an issue for controller/index, @Rolilink will create an issue for the plugins browser refactoring.

**Comment by lsl** [comment]
Added https://github.com/Automattic/wp-calypso/issues/63030

**Comment by Rolilink** [comment]
Added #63191

**Comment by Rolilink** [comment]
Added #63192 for the Hook, this one should probably be worked before #63191

**Comment by lsl** [comment]
Not sure if you caught this change to search https://github.com/Automattic/wp-calypso/pull/62777, maybe rope in @gcsecsey as a heads up, I don't think we'll be touching search logic itself but sounds like that hook might change how/where/when its called.

**Comment by gcsecsey** [comment]
Thanks for the heads up @lsl! I'm working on fetching data from a new endpoint, but the intention is to keep the same plugins schema, so the hook can be swapped in place of the `useWPCOMPlugins`, `useWPORGPlugins` or `useWPORGInfinitePlugins` hooks: https://github.com/Automattic/wp-calypso/issues/62729#issuecomment-1112169085

**Comment by lsl** [comment]
Not much use keeping this around, everything is broken up / split up into backlog issues.
