### ISSUE TITLE
Marketplace: Controller / routing refactor

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#63030]
Subtask of https://github.com/Automattic/wp-calypso/issues/62935 to focus on routing / controller code. Both are tightly coupled so hard to split this work up in a non conflicting way, there is quite a bit I'd like to change in these but will focus on easy wins / rescope as needed.

#### Done
- [x] Replace `/plugins (no-site)` routes with a site-selector screen per https://github.com/Automattic/wp-calypso/pull/63161
- [x] Figure out if we can remove these [redirect handlers](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js#L36-L49). What are these for? https://github.com/Automattic/wp-calypso/pull/63264 / D80029-code
- [x] [Inline these](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L173-L181) https://github.com/Automattic/wp-calypso/pull/63265
- [x] [Dead code?](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L183-L186) https://github.com/Automattic/wp-calypso/pull/63268
- [x] [Try get rid of this](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L22-L27) https://github.com/Automattic/wp-calypso/pull/63268

#### Resolved / moved to new issues
- [x] ~Try to remove the [pluginFilter route](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js#L93). What does this do?~ This is part of /plugins/manage/:site - we're likely going to re-use this in the future, I don't think its linked to from anywhere but would prefer to leave in place for now.
- [x] ~Try to simplify the [middleware handlers](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js#L94-L100) to reduce complexity.~ - new issue: https://github.com/Automattic/wp-calypso/issues/63792
- [x] ~Use `/plugins/?c=:category` for categories, remove dual `/plugins/:pluginOrCategory` route - probably need to wait for https://github.com/Automattic/wp-calypso/pull/63352 before doing this~ - new issue here: https://github.com/Automattic/wp-calypso/issues/63940
- [x] ~[Probably a hook](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L152-L171)~ - new issue here: https://github.com/Automattic/wp-calypso/issues/63941
- [x] ~[Try fix this properly](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L133)~ - https://github.com/Automattic/wp-calypso/issues/63940
- [x] ~[These types of functions](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L109-L122) (there are more than 2) should just render the browser which can use a hook to get the selected site ID. (coordinate change with @Rolilink + earlier [change](https://github.com/Automattic/wp-calypso/issues/62912#issuecomment-1109137046) mentioned above to remove the `/plugins (no site)` routes)~ new issue here https://github.com/Automattic/wp-calypso/issues/63942
- [x] ~Discuss with @Rolilink, suspect we can drop [this extra function](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L46) and just render almost (maybe all?) everything through the plugin browser.~ new issue here https://github.com/Automattic/wp-calypso/issues/63942

**Comment by Rolilink** [comment]
> [These types of functions](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L109-L122) (there are more than 2) should just render the browser which can use a hook to get the selected site ID. (coordinate change with @Rolilink + earlier https://github.com/Automattic/wp-calypso/issues/62912#issuecomment-1109137046 mentioned above to remove the /plugins (no site) routes)

Yes please!

>Discuss with @Rolilink, suspect we can drop [this extra function](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L46) and just render almost (maybe all?) everything through the plugin browser.

Sounds good to me!, it makes the browser component more understandable!

**Comment by lsl** [comment]
- [ ] Figure out if we can remove these [redirect handlers](https://github.com/Automattic/wp-calypso/blob/0b1198ce5237a2540aaeeff024da4d5532a84acb/client/my-sites/plugins/index.js#L36-L49). What are these for? 

https://github.com/Automattic/wp-calypso/pull/63264 / D80029-code

**Comment by lsl** [comment]
- [ ] [Inline these](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L173-L181) 

https://github.com/Automattic/wp-calypso/pull/63265

**Comment by lsl** [comment]
- [ ] [Dead code?](https://github.com/Automattic/wp-calypso/blob/9e41858a07e5e404f28e7da7e82afb4197b5416d/client/my-sites/plugins/controller.js#L183-L186) 

https://github.com/Automattic/wp-calypso/pull/63268

**Comment by lsl** [comment]
Moved everything to new issues with clear outcomes.
