### ISSUE TITLE
Add color information to wpcom url-analyzer

### ISSUE THREAD

**Issue by jeroenpf** [Automattic/wp-calypso#63039]
Color detection for the [url analyzer has been implemented in mShots.](https://github.com/Automattic/mShots/issues/51) The color information for a given URL has to be added to the URL analyzer endpoint in wpcom. This can be done when the url-analyzer in mShot has been deployed to production.

**Todo:**

- [x] Deploy mShots url-analyzer to production
- [x] Consume the mShots url-analyzer endpoint on wpcom
- [ ] Implement caching for the wpcom url-analyzer endpoint

**Comment by vishnugopal** [comment]
- This work here is to make this a signed request from the public API to the Lambda endpoint.

**Comment by vishnugopal** [comment]
WPCOM Diff here: D80900-code

**Comment by vishnugopal** [comment]
No caching has been implemented at the WPCOM end, but otherwise this is deployed.
