### ISSUE TITLE
Migrate tests from `enzyme` to `@testing-library`

### ISSUE THREAD

**Issue by flootr** [Automattic/wp-calypso#63409]
### Details

Migrate tests which make use of `enzyme` to using `@testing-library`. Have a look at recent examples e.g. [here](https://github.com/Automattic/wp-calypso/pull/63272) or [here](https://github.com/Automattic/wp-calypso/pull/63128). Please tick the box and reference your PR when you're refactoring one of the listed components.

If you need a review or have any questions, please don't hesitate to ping @Automattic/team-calypso-frameworks. You might want to have a look at the [docs for `@testing-library`](https://testing-library.com/docs/react-testing-library/intro).

### Checklist

- [x] client/jetpack-connect/test/authorize.js @fullofcaffeine #67351
- [x] client/jetpack-connect/test/jetpack-connect-notices.js @tyxla #68658
- [x] client/jetpack-connect/test/auth-form-header.js @tyxla #68657
- [x] client/jetpack-connect/test/main-wrapper.jsx @tyxla #68640
- [x] client/jetpack-connect/test/signup.js @tyxla #68660
- [x] client/lib/analytics/page-view-tracker/test/index.jsx @flootr #67000
- [x] client/me/concierge/test/main.js @flootr #67087
- [x] client/me/purchases/billing-history/test/tax.js @flootr #63672
- [x] client/me/purchases/purchase-item/test/index.jsx @flootr #63672
- [x] client/me/purchases/track-purchase-page-view/test/index.js @flootr #63672
- [x] client/me/purchases/manage-purchase/plan-details/test/billing-period.jsx @flootr #63672
- [x] client/me/purchases/manage-purchase/plan-details/test/index.jsx @flootr #66226
- [x] client/post-editor/media-modal/detail/test/index.jsx @brookewp  #65011 
- [x] client/my-sites/site-settings/settings-security/test/main.jsx @flootr #65190
- [x] client/my-sites/site-settings/test/form-cloudflare-analytics.jsx @flootr #65224
- [x] client/my-sites/site-settings/test/form-google-analytics.jsx @flootr #65226
- [x] client/my-sites/site-settings/test/form-general.jsx - @tyxla #63505
- [x] client/my-sites/site-settings/seo-settings/test/form.jsx @flootr #65676
- [x] client/my-sites/site-settings/seo-settings/test/help.jsx @flootr #65591
- [x] client/components/language-picker/test/index.jsx - @tyxla #64433
- [x] client/components/themes-list/test/index.jsx @flootr #64150
- [x] client/components/auto-direction/test/auto-direction.jsx - @tyxla #63128
- [x] client/components/button-group/test/index.js - @spraveenitpro #63371
- [x] client/components/happychat/test/composer.jsx @flootr #66599
- [x] client/components/banner/test/index.jsx @brookewp #64048 
- [x] client/components/suggestion-search/test/index.js @flootr #66679
- [x] client/components/token-field/test/index.jsx @tyxla #70823
- [x] client/components/community-translator/test/translatable.js - @tyxla #63706
- [x] client/components/translator-invite/test/index.js - @tyxla #64736
- [x] client/components/seo/preview-upgrade-nudge/test/index.jsx @flootr #67091
- [x] client/components/data/media-list-data/test/index.jsx @flootr #68600
- [x] client/components/data/query-verticals/test/index.js @flootr #63661
- [x] client/components/global-notices/test/index.js @tyxla #64407
- [x] client/components/external-link/test/index.js - @tyxla #63135
- [x] client/components/sites-dropdown/test/index.js - @tyxla #69619
- [x] client/components/support-info/test/index.js @flootr #63662
- [x] client/components/close-on-escape/test/index.jsx @fullofcaffeine #63785
- [x] client/components/date-range/test/index.js @fullofcaffeine Automattic/wp-calypso#63879
- [x] client/components/notes-formatted-block/test/blocks.js @fullofcaffeine https://github.com/Automattic/wp-calypso/pull/66324
- [x] client/components/notes-formatted-block/test/index.js @fullofcaffeine https://github.com/Automattic/wp-calypso/pull/66324
- [x] client/components/jetpack/render-switch/test/index.js @flootr #66695
- [x] client/components/jetpack/daily-backup-status/test/index.jsx @flootr #66694
- [x] client/components/jetpack/daily-backup-status/test/action-buttons.jsx @flootr #66692
- [x] client/components/jetpack/has-vaultpress-switch/test/index.js @flootr #66687
- [x] client/components/theme/test/index.jsx @flootr #64186
- [x] client/components/jetpack-header/test/index.js @flootr #66700
- [x] client/components/popover-menu/test/menu-item.jsx - @tyxla #63164
- [x] client/components/videos-ui/test/index.jsx - @tyxla #70828
- [x] client/my-sites/store/components/d3/base/test/index.js - @tyxla #63666
- [x] client/my-sites/store/components/d3/sparkline/test/index.jsx - @tyxla #69512
- [x] client/components/sorted-grid/test/index.jsx - @tyxla #63162
- [x] client/my-sites/backup/backup-date-picker/test/index.jsx - @vikneshwar #68933 
- [x] client/my-sites/backup/backup-date-picker/test/date-button.jsx - @vikneshwar #65517
- [x] client/my-sites/plan-features/test/index.jsx - @tyxla #68809
- [x] client/my-sites/plan-features/test/header.jsx - @tyxla #68816
- [x] client/components/head/test/index.jsx @spraveenitpro #65019 
- [x] client/components/head/test/favicons.jsx  @flootr #69903
- [x] client/components/marketing-survey/cancel-purchase-form/step-components/test/upgrade-at-step.jsx @brookewp #65049
- [x] client/components/marketing-survey/cancel-purchase-form/step-components/test/business-at-step.jsx @brookewp #65140
- [x] client/post-editor/media-modal/test/index.jsx @flootr #69893
- [x] client/components/bulk-select/test/index.js - @tyxla #63336
- [x] client/my-sites/hosting/sftp-card/test/index.js @flootr #68636
- [x] client/my-sites/media-library/test/index.jsx - @tyxla #64480
- [x] client/my-sites/media-library/test/list.jsx @flootr #69375
- [x] client/my-sites/media-library/test/list-item-image.jsx - @vikneshwar #66759
- [x] client/my-sites/media-library/test/content.jsx @flootr #68668
- [x] client/my-sites/media-library/test/list-item.jsx #68634
- [x] client/my-sites/media-library/test/data-source.jsx - @vikneshwar #66759
- [x] client/my-sites/people/people-invite-details/test/index.jsx - @tyxla #65234
- [x] client/components/notice/test/index.js - @tyxla #63335
- [x] client/my-sites/checkout/composite-checkout/test/wechat-payment-qrcode.js
- [x] client/my-sites/checkout/checkout-thank-you/test/header.js @flootr #66108
- [x] client/my-sites/checkout/checkout-thank-you/test/index.js @flootr #66114
- [x] client/my-sites/checkout/checkout/test/country-specific-payment-fields.js @flootr #66166
- [x] client/components/purchase-detail/test/index.jsx @flootr  #66118
- [x] client/my-sites/plans-features-main/test/plan-type-selector.jsx @flootr #66116
- [x] client/my-sites/plans-features-main/test/index.jsx - @tyxla #70425
- [x] client/components/select-dropdown/test/item.js @flootr #63966
- [x] client/components/select-dropdown/test/index.js @flootr #63966
- [x] client/my-sites/plugins/plugins-browser/test/index.jsx @flootr  #67374
- [x] client/my-sites/plugins/plugin-action/test/index.jsx @flootr #64368
- [x] client/my-sites/plugins/plugins-list/test/index.jsx @flootr #67380
- [x] client/my-sites/plugins/plugins-browser-item/test/index.jsx @flootr #64356
- [x] client/my-sites/plugins/plugin-activate-toggle/test/index.jsx @flootr #64355
- [x] client/my-sites/plugins/plugins-browser-list/test/index.jsx @flootr #67376
- [x] client/my-sites/plugins/plugin-autoupdate-toggle/test/index.jsx #64354
- [x] client/my-sites/plans/test/legacy-plan-notice.js - @tyxla #64075
- [x] client/components/readme-viewer/test/index.js - @tyxla #64077
- [x] client/my-sites/domains/map-domain/test/map-domain.js @flootr  #65031
- [x] client/my-sites/domains/domain-management/list/test/index.js @flootr #65023
- [x] client/my-sites/domains/components/form/test/hidden-input.js - @tyxla #63431
- [x] client/my-sites/domains/components/form/test/select.js - @tyxla #63431
- [x] client/components/product-expiration/test/index.js - @tyxla #63163
- [x] client/components/count/test/index.jsx @flootr #64028
- [x] client/components/locale-suggestions/test/index.jsx @brookewp #68592
- [x] client/components/logged-out-form/test/link-item.js @brookewp #64912 
- [x] client/components/domains/contact-details-form-fields/test/index.js @flootr  #65084
- [x] client/components/forms/form-country-select/test/index.jsx - @tyxla #63165
- [x] client/components/forms/form-phone-input/test/index.jsx - @flootr #63238
- [x] client/components/domains/registrant-extra-info/test/ca-form.js - @tyxla #64734
- [x] client/components/domains/registrant-extra-info/test/index.js - @tyxla #64734
- [x] client/components/domains/registrant-extra-info/test/uk-form.js - @tyxla #64734
- [x] client/components/forms/form-text-input/test/index.jsx - @flootr #63272
- [x] client/components/domains/domain-suggestion/test/index.js @flootr  #65967
- [x] client/components/happiness-support/test/index.jsx @flootr #67540
- [x] client/components/feature-example/test/index.js - @tyxla #64735
- [x] client/components/d3-base/test/index.js - @spraveenitpro  #64648
- [x] client/components/localized-moment/test/index.js @flootr #68571
- [x] client/signup/wpcom-login-form/test/index.jsx @flootr https://github.com/Automattic/wp-calypso/pull/68099
- [x] client/signup/validation-fieldset/test/index.jsx - @tyxla #63958
- [x] client/devdocs/docs-example/test/index.jsx - @tyxla #63957
- [x] client/signup/submit-step-button/test/index.jsx - @tyxla #63955
- [x] client/signup/steps/site-picker/test/site-picker-submit.jsx - @tyxla #63956
- [x] client/signup/steps/plans-atomic-store/test/index.jsx @flootr #66918
- [x] client/signup/steps/plans/test/index.jsx @flootr #66913
- [x] client/signup/navigation-link/test/index.jsx @flootr #66910
- [x] client/devdocs/test/doc.jsx @flootr #64982
- [x] client/devdocs/design/test/component-playground.js @flootr #67419
- [x] client/reader/sidebar/test/promo.jsx - @spraveenitpro #64049
- [x] client/blocks/login/test/login-form.jsx @flootr #64645
- [x] client/blocks/jetpack-benefits/test/site-backups.jsx @flootr #63912
- [x] client/blocks/jetpack-benefits/test/scan-history.jsx @flootr #63912
- [x] client/blocks/time-mismatch-warning/test/index.jsx - @tyxla #63709
- [x] client/blocks/edit-gravatar/test/index.jsx @flootr #66808
- [x] client/blocks/get-apps/test/apps-badge.js - @tyxla #63670
- [x] client/blocks/daily-post-button/test/index.jsx @flootr #64607
- [x] client/blocks/product-purchase-features-list/test/video-audio-posts.jsx @flootr #66703
- [x] client/blocks/product-purchase-features-list/test/product-purchase-features-list.jsx @flootr #66966
- [x] client/blocks/upsell-nudge/test/index.jsx - @tyxla #63669
- [x] client/blocks/follow-button/test/button.js - @spraveenitpro #63195
- [x] client/blocks/reader-author-link/test/index.js - @tyxla #64486
- [x] client/blocks/post-share/test/nudges.jsx - @tyxla #64483
- [x] client/blocks/image-editor/test/image-editor-toolbar.jsx - @tyxla #63207
- [x] client/blocks/image-editor/test/image-editor-canvas.jsx - @tyxla #63207
- [x] client/my-sites/marketplace/pages/submission-success/test/index.js - @tyxla #70829

**Comment by tyxla** [comment]
All client tests have now been migrated from `enzyme` to `@testing-library/react`! ✅ 

Thanks for the great work, everyone who contributed to this large-scale migration ❤️ 

Work is being done to remove the unused `enzyme` from the Calypso client in #70830. 🚧 

I'm going to close this one as it served its purpose. 👍 

As a next step, we might want to migrate the apps and package tests away from `enzyme` as well.
