### ISSUE TITLE
Plugin Details: display related plugins

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#63717]
- [ ] Get related plugins request: https://github.com/Automattic/wp-calypso/issues/80287
- [ ] create a new component that returns 4 related plugins to the current plugin (through jetpack search) - #80288
- [ ] create a new page that returns all related plugins (through jetpack search) to a plugin - #80289
- [ ] add the component to the plugin details page - #80290

<img width="592" alt="Screen Shot 2022-08-04 at 09 30 03" src="https://user-images.githubusercontent.com/5039531/182859430-8927ba60-2ac2-424d-b284-4d6b3e0fc697.png">

Epic Issue: https://github.com/Automattic/wp-calypso/issues/43332
P2: pdh6GB-sk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi-2496_27593

**Comment by cpapazoglou** [comment]
@gcsecsey have you found any interesting functionality in Jetpack search that will help us here?

**Comment by gcsecsey** [comment]
@cpapazoglou AFAIK no, the Jetpack search API layer has no similar feature implemented.

We could use ES to get [simple recommendations via aggregations](https://opensourceconnections.com/blog/2016/09/09/better-recsys-elasticsearch/) on an index which contains all the installed plugins for a site. I see that Jetpack site profiles have an `enabled_plugins` array, but I couldn't find which index do the results come from (at least with my test blog ids). I'm also not sure whether using aggregations on this index would cause any performance issues.

cc @gibrown

**Comment by gibrown** [comment]
Answered on that p2 thread.

**Comment by gcsecsey** [comment]
Added #66301 and #66303 for fetching the related and recommended plugins, respectively.

**Comment by gavande1** [comment]
We also need to create an additional page where we display all related plugins when someone clicks on `See All`

**Comment by gcsecsey** [comment]
CC @SaxonF @vinimotaa we've discussed this issue further on our sprint planning call, and we need some design guidance before proceeding with it:

Based on our earlier discussions on P2 (pdh6GB-sk-p2#comment-1639), we have a proposed way to get a list of either _related_ and _recommended_ plugins for any given plugin. The difference between the two:
- Related: plugins that have similar descriptions to the current one, or have similar categories/tags assigned
- Recommended: plugins that are installed by other sites that have installed the current one

Would it be better to display the lists of these plugins in two separate sections on the plugins page, or merge them into one and display them together?
