### ISSUE TITLE
AMP: Disable and hide AMP on new simple sites

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64002]
The first step in slowly rolling out the removal of AMP from simple sites is to stop making it available on new sites.

Rather than picking a magic timestamp and comparing it with a site's creation time to decide whether it counts as "new", we'll instead use a magic blog ID as the cutoff point. Blog IDs are auto-incrementing which is why they work well for this sort of thing, and they were the Atomic Team's preferred method when this sort of thing has been done in the past.

We can update the magic blog ID right before deploying.

**Tasks**
- [x] Update the functions in `amp-loader.php` so that the AMP plugin is unavailable and disabled for "new" sites
- [x] Make sure the code for determining whether a given blog ID is eligible for AMP is factored into its own function. We'll want to update this function as we continue the rollout.
- [x] AMP UI should not be available in Calypso
   - [x] Special AMP customiser at `https://wordpress.com/customize/amp/{{ site slug }}`
   - [x] And also in the settings page ![Image](https://user-images.githubusercontent.com/1500769/170210125-e8922cc9-0527-48fe-9ceb-fd133182e967.png)
   - [x] AMP is not available on the site's front end. You can verify with the AMP Validator browser extension.
   - [x] "WP Admin -> Appearance -> AMP" that is shown for non-Gutenberg themes

See project thread: pdKhl6-48-p2

**Comment by vykes-mac** [comment]
I like the way  tasks are added as a kinda acceptance criteria. I think it helps the developer to have a clearer picture of what's expected and what constitute this issue being mark as 'Done'

**Comment by p-jackson** [comment]
Yeah this task is probably the most well defined one in terms of acceptance criteria. The other tasks are probably going to require a bit more interpretation 🙈

**Comment by wojtekn** [comment]
I created an initial diff for that D81653-code

**Comment by wojtekn** [comment]
@p-jackson I've added one thing to the scope - removal of the "WP Admin -> Appearance -> AMP" item based on the AMP status. It looks like the code that adds that link was missing the check and the link was displayed even if AMP was disabled.

**Comment by danielbachhuber** [comment]
> I like the way tasks are added as a kinda acceptance criteria. I think it helps the developer to have a clearer picture of what's expected and what constitute this issue being mark as 'Done'

Me too 💯

**Comment by wojtekn** [comment]
This is launched now, closing.
