### ISSUE TITLE
Tracking Issue - Guided Tour / Help Center v1

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#64080]
Overview tracking issue for our Next Steps Guided Tour - paYE8P-1xk-p2. 

## Glossary

We have three layers to our framework for Next Steps guidance:

```
Tutorial
|-- Task
     |-- Step
```

<img width=316 src="https://user-images.githubusercontent.com/195089/171740786-c5e20605-9fec-45fa-94db-dab93d1c0b45.png" />

## Tutorial

The top-level grouping of a collection of related Tasks. The three top-level Tutorials that will be going into the Help Center are 1) Site essentials, Homepage content, and 3) Launch site.

The most semantically useful umbrella term here would be **Tour** but that overlaps too much with the `TourKit` framework we will use for Steps. There was also of course [Guided Tour](https://github.com/Automattic/wp-calypso/blob/6cb33027cd048e31c0fbd065317cd4b9e17001e1/client/layout/guided-tours/README.md) in Calypso. There's even a backend email framework called Guides! There is no safe space, semantically speaking, in our codebases. So we settled on Tutorials as the least-occupied name.

## Task

A specific task to accomplish within the Tutorial. Examples in the above image include "Welcome to the site editor", "Personalize your site", "Give your site a name", and "Confirm your email address".

## Step

Each Task in a Tutorial will have one or more steps, rendered on the client by `TourKit`/`WpcomTourKit`. In the above example, there's a single step that will show a video for "Welcome to the site editor" Task. "Personalize your site" has 4 steps (not shown above), etc.

---

## Release Workflow
- [x] #65130

## Tutorial (formerly Checklist) API

- [x] #64251
- [x] #64252
- [ ] #64254

## TourKit

- [ ] #64256
- [ ] #64259

## Help Center / Next Steps Tour

- [x] Add help center to the Site Editor. (https://github.com/Automattic/wp-calypso/pull/63429)
- [ ] #64260
- [ ] #64261
- [ ] #64262
- [ ] #64263
- [ ] #64264
- [ ] #64265
- [ ] #64267
- [ ] #64334

## Guided Tour

- [ ] #64268
- [ ] https://github.com/Automattic/wp-calypso/issues/64374
- [ ] #64269
- [ ] #64335

## Testing and maintenance

- [ ] #64336
- [ ] #64337
- [ ] #64338

**Comment by mattwiebe** [comment]
This is a backup of the above as I start consolidating and linking into sub-issues:

## Checklist API

- [ ] Create a new Checklist API that can support multiple checklists of tasks subdivided into steps.
- [ ] <s>Tasks can support custom criteria for task completion and completion status.</s> **scope down** - users mark complete on their own.
- [ ] Supports a 'skipped' status for tasks.

## TourKit

- [ ] Implement logic so elements can be found regardless of whether or not there is an editor canvas iframe.
- [ ] Enhance positioning logic (for pinpoint/spotlight) to work consistently when items are inside an editor canvas iframe.
- [ ] Implement scroll-into-view logic to ensure the referenced target element is visible.
- [ ] Tour can 'fail gracefully' when a selector for pinning is not found, defaulting to standard position. (may already be the case)
- [ ] Supports a way to add callbacks to be used on the failure. End goal: Can send a tracking event with checklist, task, and step properties when a dependent selector is not found (failing gracefully scenario as listed above).
- [ ] ...

## Help Center / Next Steps Tour

- [x] Add help center to the Site Editor. (https://github.com/Automattic/wp-calypso/pull/63429)
- [ ] Implement a section to contain next steps (tab or accordion? tbd check recent designs).
- [ ] Next steps section retrieves available checklists/tours to surface them as options.
- [ ] Next steps to step through / guide a selected tour - connecting checklist to tourkit.
- [ ] Tours pick up where users left off.
- [ ] Create UI components for task management interface, utilizing Gutenberg components where possible.
- [ ] Make checklist tasks show up as results in the search feature.
- [ ] Implement UI and functionality such that when we aren't in an editor that supports a checklist tour or task, this item provides a link to the appropriate place.
- [ ] Create tooltip 'were always here' reminder when tour is closed/dismissed.

### Moar Tours
(was above in checklists but belongs here)

- [ ] Steps can define required blocks. 
- [ ] Steps can define custom criteria to advance to next step, such as selectors to watch for click events and wp-data actions to monitor.
- [ ] Checklists can provide context for where their tours can be used (Post editor, Page editor, Site Editor, Calypso, multiple places, etc.).
- [ ] (?) Pre-step action callback -(ex- like open sidebar before starting a task)
- [ ] (?) Checklists can be added via filter extension.
- [ ] (?) Checklists support an availability criteria/callback. (so certain checklists can only be available IF - specific plugin active, site created with specific onboarding flow, etc.)

## Guided Tour

- [ ] UI and Functionality for when a required block is not present.  A conditional step should be triggered to prompt the user to allow us to automatically add the block, or temporarily skip the task.
- [ ] Sends checklist, task, step, and editor info in a tracking event when TourKit fails to find a dependent selector.
- [ ] Implement Site Editor tasks.
- [ ] <s> Implement Post Editor tasks. </s> scoped down
- [ ] Surface tour status and entry points in 'My Home'

## Testing and maintenance

- [ ] Unit tests where appropriate. Such as for the next steps components checklist handling and starting from where left off.
- [ ] Basic E2E coverage (eg. starting, closing, reopening tour.)
- [ ] Tracks event monitoring.

## Concerns

Maintenance concerns with the challenge of brittle DOM selectors.

- Previous attempts at similar projects have resulted in difficult maintenance due to breakages from brittle DOM selectors changing.
- We must be mindful of which selectors may or may not be reasonably stable. Most blocks and main interface buttons at this time should be have stable selectors. However, newer features can be subject to change and we need to be cautious. If certain steps are only able to rely on unstable selectors, we should avoid using pinpoint/spotlight features.

Testing concerns and catching regressions.

- E2Es may be the only level of testing able to verify the integration of this feature with the editor. However, due to the open source nature of the editor being beyond our control, past attempts at E2Es have created large maintenance burdens just in the tests themselves. More often E2Es fail as a problem in the test itself after a Gutenberg upgrade than because of an actual issue with the item they are testing. Given this, it may be best to avoid comprehensive E2Es and focus only on a few key checks.
- An addition we should supply is well documented and communicated testing flows to happen during Gutenberg upgrades, as well as monitoring influx of tracking events related to TourKit failures listed above (final safety net).

**Comment by jeyip** [comment]
Some helpful notes for developers:

- Entry point for help center is located in `wp-calypso/apps/editing-toolkit/editing-toolkit-plugin/help-center`
- Frontend UI for the help center is located in `wp-calypso/packages/help-center/src/components`
- To develop against the UI:
  - Sandbox a wpcom simple site
  - Run `yarn dev --sync` in `wp-calypso/apps/editing-toolkit`
  - Navigate to the site editor and show the help center by clicking on the icon in the top right hand corner of the screen
