### ISSUE TITLE
AMP: Add removal notice to settings screen

### ISSUE THREAD

**Issue by p-jackson** [Automattic/wp-calypso#64731]
We want users who have an interest in AMP to be aware that the feature is no longer available on Simple sites. At the same time, we don't want to unnecessarily notify a lot of users who probably weren't aware of AMP in the first place.

We are going to add a message to the `Settings -> Performance` screen that will replace the AMP toggle.

![Image](https://user-images.githubusercontent.com/1500769/174267983-d0eede2b-8090-4f4b-a960-4eb18fa36a17.png)

This is a fairly standard notice component that we can use. 

![Image](https://user-images.githubusercontent.com/1500769/174270316-fbcb5013-de7c-4bbe-8f67-895c9fe9a63f.png)

See project thread: pdKhl6-48-p2

**Tasks**
- [x] Don't show message on private sites (we previously hid the AMP setting from these sites)
- [x] Show message when AMP is deprecated for this site
   - We might need a new API flag because `amp_is_supported` is currently used to hide the control on private sites
   - sites which have been created since we disabled AMP should see the message
- [x] Draft some preliminary copy for the message. We should be able to refine it during the PR process and ask for feedback from the Editorial team.
   - Maybe something like "performance on mobile devices might be improved by installing the AMP plugin"
   - I'm not sure whether the wording should focus on the feature being removed or on the need to install a plugin. If we encourage the user to install the plugin
   - We might need to vary the wording depending on whether the user is on a Pro/Business plan or not

**Not in scope**

- We might want to include a link to the support site in our message. We can do that after the support site content has been updated, but I think we can ship this before that happens. See 1603-gh-Automattic/en.support-docs-content
- We'll probably eventually want to remove this message after everyone who uses AMP has had a chance to see it. But we don't need to implement any sort of expiry mechanism.

**Comment by vindl** [comment]
@p-jackson @wojtekn Could we add a tracks event for this upsell to the task list? (it can be a separate GH issue too, doesn't hurt to have more granular tasks) We could track _clicks_ and possibly _views_.

What it can help us answer is:
- how many users click on it?
- what's the percentage of users that click after seeing the nudge?
- what's the percentage of users that end up upgrading after clicking on the nudge?

**Comment by wojtekn** [comment]
I started working on this one. I did some refactoring to let us implement the UI based on supported/deprecated conditions.

- [x] Move "deprecated" condition out from "supported" check scope D83017-code
- [x] [Synchronize changes to Jetpack repository](https://github.com/Automattic/jetpack/pull/24814)
- [x] [Adjust Calypso to account for the new setting received from the API](https://github.com/Automattic/wp-calypso/pull/64857)
- [x] Remove no longer needed "deprecated" condition from "supported" function D83077-code
- [x] [Add removal notice](https://github.com/Automattic/wp-calypso/pull/64889)

**Comment by wojtekn** [comment]
@vindl good idea, I think we can do this under this ticket. It looks like the `UpsellNudge` component supports those requirements OOTB.

**Comment by vindl** [comment]
@wojtekn just a heads up that @p-jackson already created a separate issue for it https://github.com/Automattic/wp-calypso/issues/64842.

**Comment by vindl** [comment]
I'm assuming that clicking the nudge will take the user to `https://wordpress.com/plugins/amp/{site_url}`, but just wanted to verify if we are all on the same page regarding that?

**Comment by wojtekn** [comment]
@vindl I still need to finish investigating it. We may have two cases now: for a free plan, take the user to the plan comparison page. For another user, take them to the mentioned plugin URL.

**Comment by wojtekn** [comment]
@vindl @p-jackson I've opened a PR that adds the message: https://github.com/Automattic/wp-calypso/pull/64889

I skipped the whole tracks part here as we have https://github.com/Automattic/wp-calypso/issues/64842 for that. Adding tracking for impressions and clicks is supported OOTB - we will use `tracksImpressionName`, `tracksClickName`, and `event` attributes of `UpsellNudge` for that.

**Comment by vindl** [comment]
> @vindl I still need to finish investigating it. We may have two cases now: for a free plan, take the user to the plan comparison page. For another user, take them to the mentioned plugin URL.

Plugin installation should already handle the free plan upsell flow. Taking them to the plan comparison page might be disorienting. ("I upgraded to a paid plan, what now?")

**Comment by wojtekn** [comment]
@vindl good idea. I tested that flow and plugin installation is enough to handle plan upsell - it provides proper messaging:

<img width="991" alt="Screen Shot 2022-06-27 at 11 34 32" src="https://user-images.githubusercontent.com/727413/175915419-5a1cb964-8f20-45be-9045-e0f47c9c6750.png">

I unified the links and the messaging. However, I left the track events code only displayed for plan upsell events as I think we want to track plan upgrades there, and not plugin installations.
