### ISSUE TITLE
☂️ Light importer: Colors flow

### ISSUE THREAD

**Issue by bogiii** [Automattic/wp-calypso#64774]
### ⚠️  The project is on pause, and the current work is on [the backup repo](https://github.com/Automattic/wp-calypso/tree/backup/design-picker-updates) ⚠️

- [x] Create Analyzer `@wordpress/data store` | #64776
- [x] Capture screen, match with a new design
- [x] Capture screen, setup "Don’t have a site address?” (framework nav back button as well)
- [x] #64887
- [x] #64775
- [x] #64813
- [ ] [Integrate "setColors" (global styles) endpoint](https://github.com/Automattic/wp-calypso/issues/63804)
- [x] #65121
- [x] #65053
- [ ] Integrate a whole flow processes
- [ ] Add e2e tests
- [x] Correctly apply global style colors CSS to theme preview endpoint D83240-code

Designs: 42PgVsdlQ1v2wpk6lmmrnq-fi-1821%3A54036

(see: pbAok1-2RP-p2)

**Comment by vishnugopal** [comment]
Closing this for now!
