### ISSUE TITLE
☂️ Light Importer: Photos & split issues

### ISSUE THREAD

**Issue by zaerl** [Automattic/wp-calypso#65064]
- [x] Add custom verticalizer D82922-code
- [x] Add recipe import preview D82637-code

The project is on hold, so we're not planning to work on these:

- [ ] Unify JSON schema 16-gh-Automattic/importer-functions
- [ ] [imports/url-analyzer/multiple](https://public-api.wordpress.com/wpcom/v2/imports/url-analyzer/multiple?url=example.com) endpoint must output the errors of the lambda functions
- [x] Add better image analysis 12-gh-Automattic/importer-functions
- [x] Add staging environment 18-gh-Automattic/importer-functions
- [ ] https://github.com/Automattic/wp-calypso/issues/63319
- [ ] Fix: unsupported image type 6-gh-Automattic/importer-functions
- [ ] Fix: better Cloudflare CDN support 4-gh-Automattic/importer-functions
- [ ] Fix: enhance importer functions performances 17-gh-Automattic/importer-functions
- [x] Generate new JSON schema 15-gh-Automattic/importer-functions

**Comment by zaerl** [comment]
D82922-code and D82637-code have been deployed. This issue can be closed.
