### ISSUE TITLE
LaunchPad v1 - tracking issue

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#65684]
Related to project thread - paYE8P-1Kg-p2
EDIT - Follow-up tracking moved to https://github.com/Automattic/wp-calypso/issues/67335

#### LaunchPad Container
- [x] https://github.com/Automattic/wp-calypso/issues/66119 (https://github.com/Automattic/wp-calypso/pull/66194)
- [x] https://github.com/Automattic/wp-calypso/issues/66130
- [x] https://github.com/Automattic/wp-calypso/issues/66120  (https://github.com/Automattic/wp-calypso/pull/66555)
- [x] https://github.com/Automattic/wp-calypso/issues/66708
- [x] https://github.com/Automattic/wp-calypso/issues/66573
- [x] https://github.com/Automattic/wp-calypso/issues/66705
- [x] https://github.com/Automattic/wp-calypso/issues/66757
- [x] https://github.com/Automattic/wp-calypso/issues/66764
- [x] https://github.com/Automattic/wp-calypso/issues/67107
- [x] https://github.com/Automattic/wp-calypso/issues/67214

#### LaunchPad Data

- [x] https://github.com/Automattic/wp-calypso/issues/66706
- [x] https://github.com/Automattic/wp-calypso/issues/66707

#### LaunchPad Checklists
- [x] https://github.com/Automattic/wp-calypso/issues/66124 (https://github.com/Automattic/wp-calypso/pull/66375)
- [x] https://github.com/Automattic/wp-calypso/issues/66704
- [x] https://github.com/Automattic/wp-calypso/issues/66125
- [x] https://github.com/Automattic/wp-calypso/issues/66126

#### LaunchPad Site Preview
- [x]  https://github.com/Automattic/wp-calypso/issues/66131 (https://github.com/Automattic/wp-calypso/pull/66424)
- [x] https://github.com/Automattic/wp-calypso/issues/66571
- [x] https://github.com/Automattic/wp-calypso/issues/66572 

--------------------
#### Punted to [follow-ups](https://github.com/Automattic/wp-calypso/issues/67335)
- [ ] https://github.com/Automattic/wp-calypso/issues/66574 (🟠 normal) 
- [ ] https://github.com/Automattic/wp-calypso/issues/66575 (🟡 low)
- [ ] https://github.com/Automattic/wp-calypso/issues/67279 (🟡 low)

#### LaunchPad Overrides
- [ ] https://github.com/Automattic/wp-calypso/issues/66121 (❓ see if necessary after v1 release)
- [ ] https://github.com/Automattic/wp-calypso/issues/66123 (❓ see if necessary after v1 release)

#### Compact MyHome LaunchPad
- [ ] https://github.com/Automattic/wp-calypso/issues/66128 (❓ see if necessary after v1 release)

#### Other
- [ ] Update publish modal for newletters flow.
- [ ] https://github.com/Automattic/wp-calypso/issues/66147
