### ISSUE TITLE
Unified design picker: Event tracking

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#65925]
## Description

Add event tracking to the unified design picker:
- [x] When the user changes the standard theme filter.
- [x] When the user exits preview.
- [x] Remove `useTrackScrollPageFromTop` in UDP

## Acceptance Criteria
- [x] The events described above should be tracked.

## Related 
#64998
Implemented events ([comment](https://github.com/Automattic/wp-calypso/issues/64998#issuecomment-1182724200))

**Comment by bangank36** [comment]
Closed as shipped
