### ISSUE TITLE
LaunchPad Checklists - Create Initial Checklist flows

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#66125]
Create the initial checklist flows corresponding to newlsetter and links-in-bio sites.  More context and designs - paYE8P-1Ot-p2

----- 
EDIT - for initial CFT release we can treat prior/completed tasks as inert and dont need to set up navigation and flows for them. We will follow up in the CFT to enable more of these flows from the launchpad as necessary, but for now we can focus on the incomplete tasks.

For Newsletters - this means we need to 

- [x] enable the "write your first post" link to lead into the editor. 
- [x] And manage some launchpad completion status on publish.

For Links-in-bio - we will need to 

- [x] have the 'edit links' lead into the site editor, 
- [x] determine some form of completion status for the 'edit links' step (they clicked the button? or maybe later check post content for a social icon block with a url attribute set).
- [x] manage some launchpad completion status on site launch.

For all flows we will need to connect the above such that:

- [x] Launchpad is dismissed upon completion
- [x] Launchpad checklist UI reflects the above completion status of tasks.

----

prior art:

<s>The checklist flows should:

- [ ] Allow task buttons to direct the user to the appropriate screen to complete their task.
- [ ] Return to LaunchPad after that step.
- [ ] Show completed tasks as complete.

For domains and plans steps, we should allow the user to navigate to these tasks if they have not already made selections and gone through checkout. However, if the user has already purchased selections, these tasks can be complete and inert.</s>

**Comment by Addison-Stavlo** [comment]
note D86254-code will resolve (or all?) of the remaining items on this

**Comment by Addison-Stavlo** [comment]
This task will be complete with the deployment of the following PRs:
https://github.com/Automattic/wp-calypso/pull/67190
https://github.com/Automattic/wp-calypso/pull/67224
