### ISSUE TITLE
Metrics: analyze user selection of v13n themes and recipe layouts compared to non-v13n themes

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#66667]
# Description

We have shipped recipe layouts in June.
We are soon shipping v13n of a few "standard themes". 
Shipped https://github.com/Automattic/wp-calypso/pull/67077
- Geologist
- Stewart
- Arbutus
- Zoologist
We want to measure if there is a difference in user selection of these v13n themes.

For example:  Let's examine Arbutus:
* look at how often Arbutus is/was chosen in onboarding when it is shown as it's original demo site
* look at how often Arbutus is chosen in onboarding as a v13n design
* if the numbers are dramatically different, we can learn something
* if the numbers are very similar, we may conclude v13n doesn't make the theme more interesting to the users

What questions do we want to answer? Mostly we want to see if seeing vertical images make the theme seem more attractive to the user.

We should do some "bulk" analysis, meaning look at trends/data for all v13n themes.  To do this we need tracks events that have more precision.

It may be easier to use Hue to do some of these analysis.  The smartest approach is to define the questions we want to answer and use the right data tools to get the answers.

# Tasks
- [x] add event `calypso_singup_select_verticalized_design` with props:
  - [x]  `theme`  
   - [x]  a prop that identifies the recipe slug
   - [x] maybe also a prop `design_type` 
- [ ] do a premilinary analysis once prop is in production to ensure the event can be used as expected and ensure there aren't any bugs (I often find events aren't tracking what I expect when go to do any analysis, thus good to do an anylsis early)
- [ ]  Once event is in production for a 2/3 weeks, a analysis can be done and results P2ed.

**Comment by fushar** [comment]
@autumnfjeld: As I said a couple weeks ago, this `calypso_singup_select_verticalized_design` is a bit buggy as it will be fired even if the themes are not verticalized (e.g. the user did not select the "supported" vertical). Should we fix this first?

**Comment by autumnfjeld** [comment]
@fushar Yes, let's definitely fix that.  I don't think I understood the urgency of what you were getting at in our prior discussion.
 `calypso_singup_select_verticalized_design` should only fire when a user selects:
* a generated v13n design (e.g. recipe tool layouts)
* one of the v13n standard designs - and of course it must be in its' verticalized state

Thank you!!! 😃

Because of this, we can't consider this metric reliable today. But I might be able to formulate some HUE queries that would help us to an accurate analysis.

**Comment by fushar** [comment]
@autumnfjeld Looks like we actually have the needed props already.

When the design is a generated design:

- `design_type` will be `vertical`
- `slug` will be the recipe slug.
- `theme` will be the recipe theme.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/1525580/195549550-86106f23-aef1-4df6-b838-2f8bdf274317.png">

When the design is a standard theme:

- `design_type` will be `standard`
- `slug` & `theme` will indicate the theme.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1525580/195551436-25485c4e-7dbf-414b-9cd2-caa119d69997.png">

So, the next step is to wait for ~ 2 weeks and then the analysis can be done.

**Comment by fushar** [comment]
Done: pbxlJb-2PI-p2
