### ISSUE TITLE
Newsletter Accent Color: Add `accent_color` property to create site API request

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#66765]
## Task Description
User selects the accent color in the following screen: https://wordpress.com/setup/newsletterSetup?flow=newsletter.
![Screenshot 2022-08-16 at 16 01 40](https://user-images.githubusercontent.com/2019970/185657258-942d1fd6-c239-475a-9a92-dcce86e0fdb4.png)
The above screen is a step in what is known as the `Stepper` framework. See here.

Once `Continue` is pressed the user is redirected, away from `Stepper`, to: https://wordpress.com/start/newsletter/domains. 
<img width="1179" alt="Screen Shot 2022-08-19 at 17 47 56" src="https://user-images.githubusercontent.com/2019970/185657556-e4fc39a3-e04e-4860-ad21-8a522ca12995.png">
See the flow's definition here.

Once domain is picked the user is asked to pick a plan and the following endpoint is called upon any plan selection (no matter free or paid):
https://public-api.wordpress.com/rest/v1.1/sites/new. Calling this endpoint results in site creation. Sample payload:
<img width="532" alt="Screen Shot 2022-08-19 at 17 59 39" src="https://user-images.githubusercontent.com/2019970/185660068-1d8efaa7-d5dc-4cbd-a30e-e5fe8fa47676.png">
The plan for us is to extend the endpoint to support one more argument in its payload: `options.site_accent_color`.

The goal of this task is to include the selected accent color with the site creation call.

## Acceptance Criteria
- [ ] Include the selected accent color with the site creation call in the newsletter flow
- [ ] The property is to be `options.site_accent_color`
- [ ] hexadecimal color notation to be used for color value
- [ ] Do not include the accent color in the payload if none were selected
- [ ] Pass the selected `siteAccentColor` as url arg to `signup`'s `newsletter` flow but do not include the arg if the accent color was not selected

**Comment by mashikag** [comment]
I have just went through writing an implementation of saving the `siteAccentColor` on `newsletter-signup` step submission to `Onboard` store of `@automattic/data-stores` , and then retrieving it back from the store in the `newsletter` flow of the `signup` framework, a.k.a. `start`. I have create [the PR](https://github.com/Automattic/wp-calypso/pull/66845) but only for demonstration purposes so you can see how over-complicated this looks.

Instead I am planning now to write a new implementation where I will use the url params to pass the `siteAccentColor` . It looks like quite a common practice to get input args into the `signup` flows.

cc @yansern

**Comment by yansern** [comment]
Good attempt though! And I can see there is a [18.5% increase in bundle size](https://github.com/Automattic/wp-calypso/pull/66845#issuecomment-1223657198).

```
async-load-signup-steps-plans                                   +56456 B  (+17.3%)   +17150 B  (+18.5%)
```

URL params it is! Wondering if you would need 2 params, one to indicate this is a newsletter flow, one to indicate the accent color. :)

**Comment by mashikag** [comment]
> Wondering if you would need 2 params, one to indicate this is a newsletter flow, one to indicate the accent color. :)

No need to do anything extra for indicating newsletter flow. The flow is already explicitly defined as `newsletter`. It is already in the url too, just as a path and not an url param: `/start/newsletter/domains` :)
