### ISSUE TITLE
(Optional) Pattern Assembler: Make a new preview component to preview the selected patterns

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#66786]
# Description

We want to show the preview of the selected patterns and the user could easily know what their home page look like. We could re-use the `<WebPreview />` component and make a new toolbar for it.

![Screen Shot 2022-08-19 at 3 48 21 PM](https://user-images.githubusercontent.com/13596067/185570775-aec93197-42a0-4bf7-9d50-e6d1842f24db.png)

7l53h5fxAUNjVRBQ82YFwn-fi-238%3A41198

# Acceptance Criteria

- [ ] This component could be shared in both https://github.com/Automattic/wp-calypso/issues/66456 and https://github.com/Automattic/wp-calypso/issues/66589

## Desktop

- [ ] The preview toolbar contains dots, the URL bar, and the device switcher. But according to [this](https://github.com/Automattic/wp-calypso/issues/66589#issuecomment-1220357836), we could use `<WebPreview />` component first and do it in the next iteration
- [ ] (optional) A scale selector on the left side of the device switcher but it will be next iteration. See https://www.figma.com/file/7l53h5fxAUNjVRBQ82YFwn?node-id=249:41386#249913056

## Mobile
UPDATE: we will not being creating a mobile version in this release. Please see pbxlJb-2ki-p2#user-facing-acceptance-criteria

- [ ] The preview toolbar should be hidden
  <img width="300" src="https://user-images.githubusercontent.com/13596067/185573249-d1cb4100-0b40-4b96-82ed-47041c0aeca2.png" />

See pbxlJb-2gk-p2#mobile

# Dev Tasks

- [ ]  TBD

# Related

* https://github.com/Automattic/wp-calypso/issues/66589

**Comment by miksansegundo** [comment]
The team Cylon were recently working on the component `<WebPreview>` as part of [LaunchPad v1](https://github.com/Automattic/wp-calypso/labels/LaunchPad%20v1). Here is a [conversation](https://github.com/Automattic/wp-calypso/issues/66131#issuecomment-1204250235) about the changes.

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/67424 and we decided to re-use the existing layout of the device switcher. See 7l53h5fxAUNjVRBQ82YFwn-fi-256%3A42065

![image](https://user-images.githubusercontent.com/13596067/189575039-67113f8e-7287-4284-9cda-bfd668427361.png)
