### ISSUE TITLE
CPT: Incorporate analytics for interaction tracking

### ISSUE THREAD

**Issue by aduth** [Automattic/wp-calypso#6681]
We should add analytics tracking for user interactions on the custom post types list screen and new editor components.

__Interactions to be tracked:__

- [x] Custom post type list screen post actions (#7046)
- [x] Toggling custom content types on site settings (#4502)
- [x] Track CPT usage by source/action (#6847)
- ... others?
