### ISSUE TITLE
Marketplace: Add WP Job Manager Add-ons

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#67100]
This is an epic to track adding 1st-party WP Job Manager add-ons to the Dotcom Marketplace.

- [x] #67101
  - [x] PoC license integration
- [x] #67102
- [x] #67550
- [x] https://github.com/Automattic/wp-calypso/issues/67610
- [x] 891-gh-Automattic/dotcom-forge
- [x] #67715
- [x] #67714
- [x] #67551
- [x] #67103
  - [x] Gather the listing information for the Marketplace
  - [x] ~Check if we need to create new vendor.~ Create new Dotcom Store vendor `wp-job-manager-svc`.
  - [x] #67553
