### ISSUE TITLE
Marketplace: Add WP Job Manager add-ons to WCCOM and WPCOM Store

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#67103]
- [x] [Applications](https://wpjobmanager.com/add-ons/applications/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated see https://github.com/Automattic/dotcom-forge/issues/1050
    - [x] PR opened to ease future updates see https://github.com/Automattic/wp-job-manager-applications/pull/298
- [x] [Resume Manager](https://wpjobmanager.com/add-ons/resume-manager/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated 
    - [x] PR opened to ease future updates see https://github.com/Automattic/wp-job-manager-resumes/pull/385
- [x] [WC Paid Listings](https://wpjobmanager.com/add-ons/wc-paid-listings/)
    - [x] wpcom billing plan - needs fixing see https://github.com/Automattic/dotcom-forge/issues/1047
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-wc-paid-listings/pull/198)
- [x] [Job Tags](https://wpjobmanager.com/add-ons/job-tags/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-tags/pull/34)
- [x] [Bookmarks](https://wpjobmanager.com/add-ons/bookmarks/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-bookmarks/pull/49)
- [x] [Job Alerts](https://wpjobmanager.com/add-ons/job-alerts/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-alerts/pull/133)
- [x] [Simple Paid Listings](https://wpjobmanager.com/add-ons/simple-paid-listings/)
    - [x] wpcom billing plan - needs fixing see https://github.com/Automattic/dotcom-forge/issues/1047
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-simple-paid-listings/pull/54)
- [x] [Application Deadline](https://wpjobmanager.com/add-ons/application-deadline/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-application-deadline/pull/53)
- [x] [Embeddable Job Widget](https://wpjobmanager.com/add-ons/embeddable-job-widget/)
    - [x] wpcom billing plan
    - [x] wccom marketplace
    - [x] Marketplace catalogue updated D90222-code
    - [x] [PR opened to ease future updates](https://github.com/Automattic/wp-job-manager-embeddable-job-widget/pull/41)

**Comment by Copons** [comment]
On WCCOM, these add-ons must be assigned to author Automattic.
In the Dotcom Store, they must be assigned to the `wp-job-manager-svc` vendor (which has be created).

**Comment by BogdanUngureanu** [comment]
I've opened a new issue about some minor issues in WPCOM Store: https://github.com/Automattic/dotcom-forge/issues/1047

**Comment by dsas** [comment]
> On WCCOM, these add-ons must be assigned to author Automattic.

Just for future reference, it's the new wpcom specific Automattic vendor, not the standard wccom automattic vendor that e.g. sensei uses.
