### ISSUE TITLE
READER - Redesign left nav & add right sidebars to select views

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wp-calypso#67164]
## Progress Tracker

Each of the following will be worked on in separate PR's but I'll keep track of everything here. I've broken everything out into a couple of separate deploys to prevent any wires from being crossed.

### First deploy

- [x] **Introduce the new SVG icons** - (#70659)
- [x] **Masterbar changes and optional label** - (#70660)
- [x] **Favicon component - use the size prop instead of hardcoding 18** - (#70661)
- [x] **Move ReaderSidebarFollowedSites** - (#70667)

### Second deploy

- [x] **Following - move the "Manage" button** - (#70669)
- [x] **Add search filter to right sidebar** - (#70681)

### Third deploy

- [x] **Move ReaderSidebarOrganizationsList** - (#70783)

### Fourth deploy

- [x] **Reader sidebar rearrangement plus copy & icon changes** - (#71010)

### Fifth deploy

- [ ] **Fallback avatar if one doesn't exist** - (#71022)
- [ ] **Move unseen count inline** - ()
- [ ] **Refactor body (line 477) in /stream/index.jsx to have sub components** - ()
- [ ] **move "Mark all as seen" to right sidebar header under organizations** - ()
- [ ] **Better flow for reading through P2s** - ()

## Project Details

In our on-going effort to clean up the Reader, we'd like to make the following updates to the left nav:

- Update copy
- Update icons
- Remove Following, A8c, and P2 drop downs from left nav
- Add right sidebar to Following, A8c, and P2 screens
- Add ability to filter followed sites with a search field (when you have 15 or more followed sites)
- Update order of links in left nav
- Improve mobile reader navigation

@ollierozdarz redesigned the Reader left sidebar (reorganizing a few links, updating copy and icons). Here's a before/after comparison of the left sidebar:

![CleanShot 2022-11-28 at 15 05 27](https://user-images.githubusercontent.com/5634774/204370660-df23603e-1a21-41d2-983f-29cfd3ed22c3.png)

Here's what the sidebar will look like with all of the changes in place:

<img width="1456" alt="following" src="https://user-images.githubusercontent.com/5634774/197338859-c659424f-58a0-44bb-90fc-705e45d92c48.png">

We will move some of the drop downs in the existing sidebar to right side of the feed (For following, A8c, and P2 feeds).

For mobile resolutions, we will show tabs at the top to expose both the feed and the followed sites in the right sidebar:

![CleanShot 2022-11-28 at 15 08 13](https://user-images.githubusercontent.com/5634774/204371153-dbc013db-31a7-41c9-9c3e-3e138c89d7f2.gif)

Note: While the original plan was to shift all drop downs out from the left sidebar, tags and lists drop downs need to remain (since there is no centralized page to link to for those sections).

### Punting

- I'm nervous about making stylistic changes (padding, margins, separator line styles) to the left nav without also updating the other screen left nav styles (My Sites, Me, etc..). I've started a [separate PR](https://github.com/Automattic/wp-calypso/pull/69668) for this, and plan to create related PRs in Jetpack, Dotcom and in core.
- I didn't mess with moving the + icon under lists for this v1. Happy to address that in a v2 though.

### Note

I originally had attempted to put all of this into [a single PR](https://github.com/Automattic/wp-calypso/pull/69253), which just ballooned to the point that it made it hard to review.

**Comment by davemart-in** [comment]
We made a lot of progress, going to close out this top level macro issue in favor of opening up smaller issues.
