### ISSUE TITLE
LaunchPad Followups Tracking Issue

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#67335]
A follow up tracking issue to https://github.com/Automattic/wp-calypso/issues/65684

### Up Next?

Do we want to tackle items in the 'Other' category below, or consider this tracking issue complete?

### In Progress

- [x] https://github.com/Automattic/wp-calypso/issues/69756 (🔴 high)
- [x] https://github.com/Automattic/wp-calypso/issues/69690  (🟠 normal)
- [ ] [LaunchPad - resolve edge case for already launched sites](https://github.com/Automattic/wp-calypso/issues/72005)
- [x] [LaunchPad - Customize domain should hide nav bar and be easy to return from.](https://github.com/Automattic/wp-calypso/issues/72087) (🔴 high)

### Complete 
- [x] https://github.com/Automattic/wp-calypso/issues/70071 
- [x] https://github.com/Automattic/wp-calypso/issues/70069
- [x] https://github.com/Automattic/wp-calypso/issues/69624
- [x] https://github.com/Automattic/wp-calypso/issues/68961
- [x] https://github.com/Automattic/wp-calypso/issues/69483
- [x] https://github.com/Automattic/wp-calypso/issues/67820
- [x] https://github.com/Automattic/wp-calypso/issues/68967
- [x] https://github.com/Automattic/wp-calypso/issues/68466 
- [x] https://github.com/Automattic/wp-calypso/issues/69666 
- [x] https://github.com/Automattic/wp-calypso/issues/68488 
- [x] https://github.com/Automattic/wp-calypso/issues/68519 
- [x] https://github.com/Automattic/wp-calypso/issues/68969 
- [x] https://github.com/Automattic/wp-calypso/issues/68970 
- [x] https://github.com/Automattic/wp-calypso/issues/68407
- [x] https://github.com/Automattic/wp-calypso/issues/68665
- [x] https://github.com/Automattic/wp-calypso/issues/68711
- [x] https://github.com/Automattic/wp-calypso/issues/68112
- [x] https://github.com/Automattic/wp-calypso/issues/68035
- [x] https://github.com/Automattic/wp-calypso/issues/67660
- [x] https://github.com/Automattic/wp-calypso/issues/68214
- [x] https://github.com/Automattic/wp-calypso/issues/68034
- [x] https://github.com/Automattic/wp-calypso/issues/68036
- [x] https://github.com/Automattic/wp-calypso/issues/67429
- [x] https://github.com/Automattic/wp-calypso/issues/68033
- [x] https://github.com/Automattic/wp-calypso/issues/68038 
- [x] https://github.com/Automattic/wp-calypso/issues/68037 
- [x] https://github.com/Automattic/wp-calypso/issues/66574 
- [x] https://github.com/Automattic/wp-calypso/issues/67824 
- [x] https://github.com/Automattic/wp-calypso/issues/67426
- [x] https://github.com/Automattic/wp-calypso/issues/67825
- [x] https://github.com/Automattic/wp-calypso/issues/67667
- [x] https://github.com/Automattic/wp-calypso/issues/67430
- [x] https://github.com/Automattic/wp-calypso/issues/67658
- [x] https://github.com/Automattic/wp-calypso/issues/67456
- [x]  https://github.com/Automattic/wp-calypso/issues/67279
- [x]  https://github.com/Automattic/wp-calypso/issues/66575 
- [x] https://github.com/Automattic/wp-calypso/issues/67659
- [x] https://github.com/Automattic/wp-calypso/issues/67336 
- [x] https://github.com/Automattic/wp-calypso/issues/68206 
- [x] https://github.com/Automattic/wp-calypso/issues/67823
- [x] https://github.com/Automattic/wp-calypso/pull/68918 
- [x] https://github.com/Automattic/wp-calypso/issues/67974
- [x] https://github.com/Automattic/wp-calypso/issues/71326
- [x] https://github.com/Automattic/wp-calypso/issues/71888
- [x] https://github.com/Automattic/wp-calypso/issues/70883 (🟠 normal)
- [x] https://github.com/Automattic/wp-calypso/issues/71717 (🟠 normal)
- [x] https://github.com/Automattic/wp-calypso/issues/72093) (🔴 high)
- [x] https://github.com/Automattic/wp-calypso/issues/72097) (🟠 normal)
- [x] https://github.com/Automattic/wp-calypso/issues/71888) (🟠 normal)
- [x] https://github.com/Automattic/wp-calypso/issues/72021) (🟠 normal)
- [x] https://github.com/Automattic/wp-calypso/issues/69757 (🔴 high)
- [x] https://github.com/Automattic/wp-calypso/issues/70965 (🔴 high)
- [x] https://github.com/Automattic/wp-calypso/issues/70825 (🟠 normal)
- [x] https://github.com/Automattic/wp-calypso/issues/72006

Other

- [ ] https://github.com/Automattic/wp-calypso/issues/66147
- [ ] https://github.com/Automattic/wp-calypso/issues/69894
- [ ] https://github.com/Automattic/wp-calypso/issues/68763 (low)

**Comment by Addison-Stavlo** [comment]
closing this as we no longer use it and have the remaining issues in our board.
