### ISSUE TITLE
Task: resolve stylelint errors across wp-calypso

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#67467]
In #66909, @manzoorwanijk helped us utilize `@wordpress/stylelint-config/scss` for many of our style lint rules. While we caught and resolved a few problems noticed while reviewing, other warnings have been introduced (or already existed) in Calypso. 

Our goal should be 0 stylelint warnings across calypso. You can view all issues in the repo with `yarn lint:css`. _Note: I'm working on speeding this up somewhat -- it's not currently ignoring any files._

To resolve issues, we need to:
1. Run auto-fix on the entire repo. 
2. Determine if we really need the rule or if the rule should be tweaked or removed. I think there are two criteria: first, we should match [WordPress CSS style guidelines](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/). Second, we should encourage "best practices." Otherwise, we can remove or tweak the rule to make it less restrictive. I think "best practices" are mostly covered by the WordPress guidelines, so we can mostly just stick with that. (see #67468)
3. Correct valid style issues, or if the usage is fine for the code, [ignore the specific rule for that line](https://stylelint.io/user-guide/ignore-code/).

### Tasks:

- [x] Update rules (#67468)
- [x] For every unscoped `stylelint-disable`, scope it to a specific rule. Unfortunately, there is [no way to enforce this](https://github.com/stylelint/stylelint/issues/2292) going forward, but `--fix` [does not work correctly](https://github.com/stylelint/stylelint/issues/2643) if rules are unscoped. (E.g. if you write `/* stylelint-disable-line */`, the **entire file** cannot be autofixed. Autofix only works for the rest of the file if the line is scoped to a rule.) (#67477)
- [x] Add rules to enforce valid scoping in disable rules: #68584
- [x] Autofix the repo, adding the commit to `.git-blame-ignore-revs` (https://github.com/Automattic/wp-calypso/pull/67568, https://github.com/Automattic/wp-calypso/pull/67585)
- [x] Add `stylelint` to our lint check in TeamCity (https://github.com/Automattic/wp-calypso/pull/68920)
- [x]  Once all style issues are fixed, forbid merging PRs which break stylelint rules
- [x] Update the CSS coding guidelines:  https://wpcalypso.wordpress.com/devdocs/docs/coding-guidelines/css.md (https://github.com/Automattic/wp-calypso/pull/67650)
- Fix existing rules one by one:
- - [x] `color-named` @brookewp 
- - [x] `CssSyntaxError`
- - [x] `declaration-block-no-duplicate-properties` @manzoorwanijk
- - [x] `declaration-block-no-shorthand-property-overrides` @manzoorwanijk
- - [x] `declaration-property-unit-allowed-list` @manzoorwanijk
- - [x] `font-family-no-missing-generic-family-keyword` @manzoorwanijk
- - [x] `function-parentheses-space-inside` @manzoorwanijk
- - [x] `function-url-quotes` @manzoorwanijk
- - [x] `indentation` @manzoorwanijk
- - [x] `no-duplicate-at-import-rules` @manzoorwanijk
- - [x] `no-duplicate-selectors` @manzoorwanijk
- - [x] `no-empty-source` @manzoorwanijk
- - [x] `no-eol-whitespace` @brookewp 
- - [x] `no-irregular-whitespace` @manzoorwanijk
- - [x] `property-no-unknown` @manzoorwanijk
- - [x] `scales/radii` @manzoorwanijk 
- - [x] `scss/at-import-no-partial-leading-underscore` @manzoorwanijk
- - [x] `selector-pseudo-class-parentheses-space-inside` @manzoorwanijk
- - [x] `selector-type-no-unknown` @brookewp 
- - [x] `string-quotes` @manzoorwanijk
- - [x] `unit-allowed-list` @manzoorwanijk
-  - [x] Remove needless disables @manzoorwanijk

**Comment by manzoorwanijk** [comment]
💡 Tips regarding "Fix existing rules one by one"

Run `yarn lint:css` in VS Code terminal and you can directly open the affected files using `Option + Click`

<img width="1708" alt="Screenshot 2022-09-15 at 6 05 47 PM" src="https://user-images.githubusercontent.com/18226415/190405455-450bf024-7119-4b90-8d5d-39b4bc72cad9.png">

And then if you need to disable warnings for some lints, Problems section of VS Code is really helpful.

<img width="1453" alt="Screenshot 2022-09-15 at 6 23 32 PM" src="https://user-images.githubusercontent.com/18226415/190409164-a9c12986-0840-4ecb-b885-59da54375209.png">

**Comment by manzoorwanijk** [comment]
I think `mini-css-extract-plugin` webpack plugin does not work well without quotes for URLs. See this [build failure](https://github.com/Automattic/wp-calypso/actions/runs/3110661070/jobs/5042119531) for #68181

May be we need to change `function-url-quotes` rule to `always`. Although Gutenberg sets it to `never` but I hardly found a few calls to `url()` function in Gutenberg, unlike Calypso where we have quite a bit.

**Comment by noahtallen** [comment]
This project is complete! `yarn lint:css` returns no errors on trunk, and it should run per-PR to prevent more rule violations from being merged.
