### ISSUE TITLE
LaunchPad - add tracking events to launchpad UI.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#68112]
We should add tracking events for when:

- [x] the launchpad screen is loaded (after we are sure its not redirecting to my home)
- [x] clicking "go to admin"
- [x] clicking an actionable task (note event names should be hardcoded and not generated programmatically) - this can contain extra properties such as the tasks completion status when clicked.

This can be separated via multiple PRs if necessary, and tracked via check boxes above and comments to this issue.

Information about track events naming conventions and usage can be found PCYsg-4S2-p2

**Comment by agrullon95** [comment]
Potential fix PR: https://github.com/Automattic/wp-calypso/pull/68450
