### ISSUE TITLE
🔍  [Spike] Pattern Assembler: Make a POC for blog patterns (aka query block patterns)

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#68133]
# Description

An immediate iteration on the PA will be to 
* Allow user to select blog patterns (aka query block patterns)
* Show the PA in the Write flow

| Blog | Query |
| -- | -- |
|  <img width="300" alt="image" src="https://user-images.githubusercontent.com/5665959/191632952-72ae1ff1-65ac-4e39-a656-942611ad0dc6.png">   | <img width="300" alt="image" src="https://user-images.githubusercontent.com/5665959/191632749-e7c50a8c-53b1-42aa-ab8a-995fad036fe9.png"> |
| pulled from dotcoompatterns | pulled from core |

This work can start once Pattern Assembler is feature complete for CfT/MVP or if Ganon has bandwith--which could be now. :) Discuss with team if anyone wants to pick this up before we ship MVP.

This issue is about creating a POC to surface any technical complications with blog patterns in the preview, headstart, or starter site.

# Tasks
- [x] Identify most popular blog patterns inserted in the editor  (I think we can simply use patterns from dotcompatterns, rather than core for this POC)
- [x] Research & P2: While POC does not need to pull patterns from core, as part of this ticket please research the tech implementation needed to source patterns from core and write a P2 on this
- [x] Share POC with stakeholders & designers

More details to be added

# References
* p1661849184727399/1661827036.318049-slack-CRWCHQGUB
* Key tracks trends, specifically see pattern wpcom_pattern_inserted for popular patterns

@Automattic/ganon  cc: @alaczek @onuro

**Comment by miksansegundo** [comment]
## **Patterns from core**

Our slow preview API `/blocks-preview` supports patterns from `dotcompatterns` or other source sites in `wpcom`. A simple solution to use core patterns in the onboarding is to copy them into `dotcompatterns` because the pattern assembler loads patterns from a [static file](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts) using their ids.

There are currently 6 query patterns listed in the pattern inserter in the editor:
- query-grid-posts
- query-large-title-posts 
- query-medium-posts
- query-offset-posts
- query-small-posts
- query-standard-posts

They live in WordPress core, in the folder [/block-patterns](https://github.com/WordPress/WordPress/tree/master/wp-includes/block-patterns).

There aren't, at the moment, query patterns in the [Pattern Directory](https://wordpress.org/patterns/). There is no such category. See the patterns created by the [user WordPress.org](https://wordpress.org/patterns/author/wordpressdotorg/).

There are attempts to add more from Gutenberg:

- https://github.com/WordPress/gutenberg/pull/44163
- https://github.com/WordPress/gutenberg/pull/30763


## **The query pattern category** 

The pattern category `Query` is now called `Posts` in the pattern inserter.

![Image](https://user-images.githubusercontent.com/1881481/208093389-31bb6057-7f1c-471f-8cbf-a924efbaf2e5.png)


## **The Query Loop block**

![Image](https://user-images.githubusercontent.com/1881481/208093719-f1f93f99-080a-45b0-9d99-d8a9c3dd6a82.png)

The `Query Loop` block is similar to `Posts List`. 

![Image](https://user-images.githubusercontent.com/1881481/208093625-a99a6542-32f8-485d-b9d9-fcce96173679.png)

They allow users to choose a pattern from the category `Post`, the editor uses the pattern property `blockTypes: core/query` to identify them.

![Image](https://user-images.githubusercontent.com/1881481/208093867-f895d97c-1cb5-4d3c-8173-b4ff3b81b516.png)

**Comment by miksansegundo** [comment]
Next actions for this POC are:

1. Research what will happen if we copy the core query patterns from this folder [/block-patterns](https://github.com/WordPress/WordPress/tree/master/wp-includes/block-patterns) to `dotcompatterns` and publish them but leave them uncategorized for testing. We should not put them in the category `posts` or `query` because they will appear in the editor in production.
   - When posts are added to the category `posts` in `dotcompatterns`, they will appear duplicated in the pattern inserter in the editor. We discussed a solution to avoid duplication by checking the pattern slugs in the server API that returns the patterns.  
2. Research how we can support core patterns without copy them in `dotcompatterns`
   - Option 1: We'll have to render them directly in Calypso using the fast previews that Arthur is working on. There is a way to get patterns from the Pattern registry using their slug. Core patterns are already in the Pattern registry. See the patterns toolkit API.
   - Option 2: We'll have to work on the preview API to use the Patterns registry class and add support for pattern slugs. Currently the preview API `/blocks-preview` works with the ids of patterns in source sites. This option is not ideal because the performance is not good.
3. Check if we already have patterns that use `core/query` blocks in `dotcompatterns`. We can easily test them in the PA:
   - Add their post ids in the sections list in the [static file](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/patterns-data.ts) that loads patterns in the PA.
   - Access the PA and you should see only one post `Hello World!` in the preview because the site `blankcanvas3demo` only have that one. 
     - We'll have to create more posts in the demo site for the previews. How many? You'll need to add yourself to the site or use the user `themedemos`.
   - When you land in the editor, the query pattern preview will show the posts in your site or the message `No results found`.
     - We'll have to create posts in the user's site or the editor preview will be empty. 
       - These posts are only required if the user chooses a query pattern.
       - We can create them using `Headstart` annotations but I think we should not add posts in Blank canvas theme because this theme should be blank.
       - We can use a new server endpoint and call it from the browser before the user is redirected to the editor.
