### ISSUE TITLE
Onboarding Design Selection: add Marketplace themes

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#68288]
As described in the flow chart created by Saxon at pdgAPm-qE-p2#comment-401, we need to implement the appropriate UI flows for users selecting a *third-party bundled theme ("type 2")* at checkout. These users would be prompted to purchase the theme as an annual subscription, and to upgrade to a business plan if necessary.

- [x] List marketplace themes ( and theme detail page ) - https://github.com/Automattic/dotcom-forge/issues/2955
- [x]  Make sure customers understand they need to upgrade ( through the upgrade modal ) - https://github.com/Automattic/dotcom-forge/issues/2956
- [x]  Add the business plan AND the theme subscription to the cart (with the same billing period) - https://github.com/Automattic/dotcom-forge/issues/2957
- [x] Display the curated Marketplace Themes on the Onboard screen -  https://github.com/Automattic/dotcom-forge/issues/3446
- [x] Remove the filtering out of Marketplace Themes from the search -  D118299-code and https://github.com/Automattic/wp-calypso/pull/80446
- [x]  Display Marketplace themes thumbnails on the Onboard screen - https://github.com/Automattic/dotcom-forge/issues/3447

**Comment by nelsonec87** [comment]
I've added a "Fake Theme" to the test tables:

- `test_billing_products`
![image](https://user-images.githubusercontent.com/3801502/196821577-41aac939-0ccf-4308-a061-1500003cc253.png)

- `test_billing_plans` (for each currency)
![image](https://user-images.githubusercontent.com/3801502/196821669-badc144e-dfcf-40ed-8bfc-4912bd047f10.png)

- `test_store_products`
![image](https://user-images.githubusercontent.com/3801502/196821793-a4727b14-ef92-4f90-adf0-ff80d4c8976d.png)

**Comment by blackjackkent** [comment]
Nice! If I'm reading correctly (and based on the conversation at p1666118314026709-slack-C0Q664T29) we'll still need to figure out how we're differentiating third party from first party in this theme data, but that's going to be a separate thing to figure out.

**Comment by blackjackkent** [comment]
Work on this project should make use of the `themes/subscription-purchases` feature flag introduced in https://github.com/Automattic/wp-calypso/pull/69292 .

**Comment by nelsonec87** [comment]
> Nice! If I'm reading correctly (and based on the conversation at p1666118314026709-slack-C0Q664T29) we'll still need to figure out how we're differentiating third party from first party in this theme data, but that's going to be a separate thing to figure out.

Maybe use the same approach from the theme/plugin bundle (taxonomy)?

**Comment by markbiek** [comment]
@nelsonec87 Looks like we're going to use Tsubaki as a test theme: paYKcK-2kT-p2

**Comment by sixhours** [comment]
I think this work would better be taken on by another team working more closely with third-party themes. Maybe @Automattic/bespin ?

**Comment by cpapazoglou** [comment]
Thanks for the ping @sixhours, I have pulled in this issue.

**Comment by epeicher** [comment]
Discussion during backlog grooming here p1688648612554749-slack-C02JPCHEKDY

**Comment by WBerredo** [comment]
While grooming we decided to do the following steps:

- [ ] List marketplace themes ( and theme detail page ) - https://github.com/Automattic/dotcom-forge/issues/2955
- [ ] Make sure customers understand they need to upgrade ( through the upgrade modal ) - https://github.com/Automattic/dotcom-forge/issues/2956
- [ ] Add the business plan AND the theme subscription to the cart (with the same billing period) - https://github.com/Automattic/dotcom-forge/issues/2957

**Comment by cpapazoglou** [comment]
This is now done.
