### ISSUE TITLE
Add tracks event for "Unlock theme" button in the design picker preview

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#68376]
# Description

![Image](https://user-images.githubusercontent.com/5665959/192731891-b1d183c2-40e2-43db-98f1-f3048df35615.png)

![Image](https://user-images.githubusercontent.com/5665959/192731950-30b0b59f-58e5-4bfb-8e58-43f92236b851.png)

# Tasks
 Add event 'calypso_signup_design_preview_unlock_theme_click`
prop:
  theme: {theme}
  template: {template}
  intent: {intent}
  theme_style: like pub/livro-white

- [x] Add `calypso_signup_design_preview_unlock_theme_click` to track the user action of a click.
- [x] Register the newly created events
  - [x] calypso_signup_design_preview_unlock_theme_click
  - [x] calypso_signup_design_upgrade_modal_show
  - [x] calypso_signup_design_upgrade_modal_checkout_button_click

**Comment by fushar** [comment]
I checked the codebase. Looks like we already tracks this, with the following event:

`calypso_signup_design_upgrade_modal_show`

- `theme`: the theme slug

Can you check? Do we want to extend this event, or...?

**Comment by autumnfjeld** [comment]
Thanks for calling that out @fushar .   In the spirit of precise tracking we should actually have two events here: one for user click and one for modal showing.

Also I see that `calypso_signup_design_upgrade_modal_show` isn't registered. :(. Could you be so kind to do that as part of this work?  THen you can ensure the descriptions in tracks are clear and precise. :)

**#1**
Tracking the user action of a click
 'calypso_signup_design_preview_unlock_theme_click`
theme: {theme}
template: {template}
intent: {intent}
theme_style: like pub/livro-white

**#2**
Tracking that the modal successfully shows
`calypso_signup_design_upgrade_modal_show`
![image](https://user-images.githubusercontent.com/5665959/193161838-c500c51f-3c3e-4e82-8149-d0793ffd5b1d.png)

**#3**
Tracking button click in modal
I double checked and this is implemented for the button in the modal ✅
[calypso_signup_design_upgrade_modal_checkout_button_click](https://mc.a8c.com/tracks/live/?eventname=calypso_signup_design_upgrade_modal_checkout_button_click)


cc: @sixhours

**Comment by arthur791004** [comment]
Close it via https://github.com/Automattic/wp-calypso/pull/68565. Here is the screenshot of the event

<img src="https://user-images.githubusercontent.com/13596067/193766131-beffd0ff-5e8b-4096-bbdd-c65d440c44bc.png" />

**Comment by fushar** [comment]
> Also I see that calypso_signup_design_upgrade_modal_show isn't registered. :(. Could you be so kind to do that as part of this work? THen you can ensure the descriptions in tracks are clear and precise. :)

Sorry, missed this. @arthur791004 as you worked on this, did you have a chance to look into the above?

**Comment by arthur791004** [comment]
> did you have a chance to look into the above?

I've registered that event 🙂
