### ISSUE TITLE
Task list for setting up blank-canvas-3 for the PA flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#68550]
# Description
See slack conversation p1664498573444889/1663881788.778639-slack-C029FM1EH

When the [blank-canvas-3](https://github.com/Automattic/themes/tree/trunk/blank-canvas-3)  theme is ready, use it for the PA assembler. 

# Tasks
- [x] follow Onur's progress and check in with him as needed to start using the new theme https://github.com/Automattic/themes/pull/6665
- [x] understand if we can use a template that is part of theme - UPDATE: the new theme will NOT have a home.html template, we will create it on the fly
- [x] merge https://github.com/Automattic/themes/pull/6665
- [x] soft launch blank-canvas-3 D90827-code
- [x] network activate blank-canvas-3
- [x] Blank Canvas 3: Add Headstart annotation file D91174-code
- [x] use blank-canvas-3 in the PA flow for Ganon internal testing (wire it up to the card in the DP grid)
- [x] use blank-canvas-3 in the PA flow for CfT (this may be exactly the same as prior point, but I'm just making sure)
- [x] "clean up" https://blankcanvas3demo.wordpress.com - this is an awkward state because it won't be user facing, but we need it for headstart and the preview step. @arthur791004 will follow up with this: hiding the "Start using this theme on your site" banner or another solution
- [x] retire [blank-canvas-blocks](https://github.com/Automattic/themes/tree/trunk/blank-canvas-blocks) from showcase, see Retiring a Theme info: PNEWy-tR-p2
- [x] hide blank-canvas-3 in showcase D90503-code
- [ ] prevent access to customizer for the bc3 theme
- [ ] "launch" blank-canvas-3 theme with PA flow (I'm not sure anything really needs to be done here, since we are not really launching it as a standalone theme)

We will hide blank-canvas-3 in the showcase, then when we wire up PA flow in the showcase, we will expose BC to users in the showcase.

This is the state of https://blankcanvas3demo.wordpress.com
<img width="863" alt="image" src="https://user-images.githubusercontent.com/5665959/199849984-915bde0c-057f-492f-aea3-4b5c8a934723.png">

cc: @Automattic/ganon

**Comment by autumnfjeld** [comment]
@arthur791004  Even though the theme is not ready, I put this in Ready for Dev because I'd like someone to take charge of following Onur's progress and also making sure we know what templates will be available, that they have "good name" and there is a template we can use for the home page.

Related comment:
I was playing around with the TT2 theme yesterday and it feels like a good approach.  
![image](https://user-images.githubusercontent.com/5665959/193948406-5539267d-8305-4feb-bd2e-afd6185be731.png).  It makes sense that user sess "Home" and that it is the home template.  https://themes.svn.wordpress.org/twentytwentytwo/1.2/templates/

I assume the theme that Onur is building will have a `home.html` template.     

At this point Arthur, your knowledge is much greater than mine, so take my comments with a[ grain of salt](https://en.wikipedia.org/wiki/Grain_of_salt).

**Comment by autumnfjeld** [comment]
🥳 The PR has been merged.  https://github.com/Automattic/themes/pull/6665 

See the slack convo for details
p1666696424251269/1666560395.863769-slack-CRWCHQGUB

@arthur791004 will soft launch the blank-canvas-3.
p1666704226337649-slack-CRWCHQGUB
D90503-code

**Comment by arthur791004** [comment]
We have soft launched the blank-canvas-3 via D90827-code

**Comment by autumnfjeld** [comment]
I have network activated blank-canvas-3. See https://wordpress.com/wp-admin/network/themes.php?s=blank


<img width="1062" alt="image" src="https://user-images.githubusercontent.com/5665959/198908004-bef445e1-82ca-4340-bb9b-e66574754926.png">

In this process Ola figured out that https://github.com/Automattic/themes/blob/trunk/blank-canvas-3/style.css has incorrect Theme URI.    https://github.com/Automattic/themes/pull/6707

**Comment by arthur791004** [comment]
✅ Pattern Assembler: Remove old blank canvas on the client side before it's retired #69608
✅ Pattern Assembler: Adjust footer position and scroll selector #69609
✅ Pattern Assembler: Update Home template if it's existed #69613
✅ Soft launch blank-canvas-3 D90827-code
✅ Block Preview: Fix missing root element if the homepage is template D91163-code
✅ Blank Canvas 3: Add Headstart annotation file D91174-code
✅ Themes Showcase: Hide blank-canvas-3 D91170-code

**Comment by arthur791004** [comment]
> prevent access to the customizer for the bc3 theme

Do we have this feature on a simple site 🤔

> WordPress will only add the Customize menu item if a non-block theme is activated or a plugin interacts with the Customizer (please see the customize_register action).

Referring to [State of the Customizer with block themes in WordPress 5.9](https://make.wordpress.org/core/2022/01/07/state-of-the-customizer-with-block-themes-in-wordpress-5-9/), it looks like we still have plugins registering `customize_register` action on the simple site, and that's why we still see the Customizer there even if the current activated theme is the block-based theme. Am I correct?

**Comment by arthur791004** [comment]
✅ Hide theme activation bar for blank-canvas-3 D91664-code

**Comment by arthur791004** [comment]
I think this issue has been done, let's close it 🙂

> prevent access to customizer for the bc3 theme

If we want to hide the customizer for the block-based theme on a simple site, we might need to investigate how to do it.
