### ISSUE TITLE
Metrics: Analyze how style selection affects user selection

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#68743]
## Description

| 🗓 | 🚢
--- | ---
October 3, 2022 | Style selection in onboarding
ETA October 12, 2022 | #68183

We want to measure how styles selection impacts theme selection.
Questions we are interested in answering:
- [x] Do themes with variations see a usage uptick after October 3rd?  
- [x] How much of a usage uptick after #68183? 
- [x] Are themes with more variations more previewed?
- [x] Do users actually pick themes with variations or just previewing them?

Metrics that we are interested in:
- [x] Are users clicking the style indicators in the theme grid?
- [x] Are users clicking the style buttons in the theme preview?
- [x] Percentage of users selecting default style vs. variation.

## Tasks
- [x] Set up trends of theme usage
  - [x] Pre style selection
  - [x] Post style selection, pre #68183
  - [x] Post #68183

**Comment by autumnfjeld** [comment]
@taipeicoder  Nice job of being thorough yet keeping it simple.

>  Do themes with variations see a usage uptick after October 3rd?

I'd define "usage" more precisely:   
Do themes with variation get previewed more?
Do themes with variation get selected as chosen design more?
The latter question is the most important, so if you wanted to limit your analysis that would be the one to focus on.

You touched on differences in "usage: here (calling out diff between preview and final selection):

>  Do users actually pick themes with variations or just previewing them?

>  Percentage of users selecting default style vs. variation.

Great question, simple but will be really useful - could be fed back to theme designers to say "this is what the most users are choosing over the default".  

>  Do an in-depth analysis of Quadrat (most variations) vs. Zoologist (three variations).

Like this idea.  Likewise you might decide to do this on the most popular selected theme (instead of Quadrat or Zoologist - what do you think would have the most impact? Your call 😃).

![image](https://user-images.githubusercontent.com/5665959/194784887-b4ad8048-ab6c-42df-931b-9bbc049c17e2.png)

In those stats, I suspect Meraki is so high because it is one of the recipe layout themes.  would have to drill down to isolate only "standard theme choices" (I should make a hue query on that, since we can't use tracks trends to do that check)

from tracks/events/event.php?eventname=calypso_signup_select_design

**Comment by autumnfjeld** [comment]
In the analysis P2, be sure to cross post to themedev p2 and maybe also ping in the #themes channel.   I think it's good if we increase our communication with those channels more, ensure awareness of how much Ganon is involved in theme analysis, and again how important themes are in onboarding.

![bitmoji](https://sdk.bitmoji.com/render/panel/e6518353-71e9-41b7-9208-fde8f676bf08-b931236c-c79a-49b5-b0f5-ab26d7e4cd09-v1.png?transparent=1&palette=1&width=46)
