### ISSUE TITLE
[Tracking] Wayfinding and labeling improvements for the Site Editor

### ISSUE THREAD

**Issue by jordesign** [Automattic/wp-calypso#68953]
### What

It would be great to build some better labelling and signposting/wayfinding around pathways and entry points to the Site Editor in order to improve user orientation and context. 
Some potential ideas (ref: pc4f5j-2wc-p2#comment-2997 from @pablohoneyhoney ):

* Clearer labeling of the template name within the Site Editor
* A snackbar when the Site Editor loads - indicating you're editing a template
* Clearer CTA wording when a block theme is activated (instead of 'Edit Site')
![pasted image 0](https://user-images.githubusercontent.com/1842363/195260216-4b0f7b15-47e8-4a90-99b5-abdd174e2784.png)
* Consider different labelling instead of Appearance > Edit within the admin menu
* Clearer CTA wording for the 'Edit Homepage' checklist item in My Home
![pasted image 0-1](https://user-images.githubusercontent.com/1842363/195260525-6df9dbfb-bf53-4bda-9a4c-aa4a53c69324.png)

I imagine there are other options where we can add further clarity in the pathways to the Site Editor for the user.

### Why

Currently we see a lot of confusion from users when entering the Site Editor - not understanding the context that they are editing elements under (within templates). This often results in content which is *intended for a single page* being added as content to the template (amongst other things).

**Comment by autumnfjeld** [comment]
> Clearer CTA wording when a block theme is activated (instead of 'Edit Site')

@jordesign What did you have in mind?   I'm adding similar issues for Ganon to tackle as part of the Pattern Assembler flow.

**Comment by miksansegundo** [comment]
Sharing some context about the wording we use in support pages to see how we can improve it. 

**The labels being used are**

- Editor
- Site Editor
- Block Editor
- WordPress Editor

**Relevant info from support pages**
> Also referred to as the **Block Editor**, the **WordPress Editor** launched in late 2018. It is the most powerful and flexible WordPress editing experience and used by millions of website owners around the world.

> With the **Site Editor**, you can design everything on your site — from the header right down to the footer — using blocks.

> Before the **Site Editor**, many fundamental elements of your site’s design (like the header, sidebars, page content, and more) were all determined by your theme. With the Site Editor, you have access to a whole new level of control over how your site looks!

> **When to Use the Site Editor**
The Site Editor brings a whole new level of control when editing a WordPress site. While it’s possible to edit your **site’s overall structure** (i.e. the **templates**) as well as the content of individual **pages** and **posts**, we recommend following this advice:
> - When you want to **edit your site’s overall structure** (i.e. areas like headers, footers, and the structural appearance of your pages and posts), use the **Site Editor**.
> - When you want to **edit the content of your pages** (i.e. text, images, embeds, and more), edit those pages individually by going to your dashboard and selecting **Pages**.
> - When you want to **edit the content of your blog posts** (i.e. text, images, embeds, and more), edit those posts individually by going to your dashboard and selecting **Posts**.

> **Full Site Editing** (or “FSE”) is a collection of interrelated features that unlocks the ability to edit your entire site using blocks. This allows you to take advantage of the familiar and flexible experience of the **Block Editor** in more places.

**Support pages**
 - [Editors](https://wordpress.com/support/editors/)
 - [Site Editor](https://wordpress.com/support/site-editor/)
 - [Full Site Editing](https://wordpress.com/support/full-site-editing/)
 - [WordPress Editor](https://wordpress.com/support/wordpress-editor/)
 - [Video Tutorials Block Editor](https://wordpress.com/support/video-tutorials/using-the-block-editor/)

**Help search**
<img width="625" alt="Screen Shot 2565-10-18 at 15 42 31" src="https://user-images.githubusercontent.com/1881481/196382418-95436125-cc0e-4809-b6e5-9e7293aeacf8.png">
<img width="590" alt="Screen Shot 2565-10-18 at 15 54 56" src="https://user-images.githubusercontent.com/1881481/196384702-2905ad3d-c40d-41fc-bba7-ad5c9af41751.png">
<img width="624" alt="Screen Shot 2565-10-18 at 15 47 10" src="https://user-images.githubusercontent.com/1881481/196382692-e5fd2fbb-b96a-4995-ae76-df6f6c50be70.png">

**Comment by jordesign** [comment]
I'm definitely up for discussion on this - but from a user-facing perspective I can imagine options like these to be clearer:

> Appearance > Editor

* Theme Editor?
* Template Editor?
* Edit Site Appearance

> Clearer CTA wording when a block theme is activated (instead of 'Edit Site')

* Edit Site Appearance?
* Edit theme?

**Comment by autumnfjeld** [comment]
The way I've understood, we are moving customers forward to truly do all Site editing in the Site Editor : both content & styles(appearance).  So in terms of messaging for the BCPA flow , "Edit Site" makes sense.

**Comment by autumnfjeld** [comment]
![image](https://user-images.githubusercontent.com/5665959/196605136-c4b51b0a-3444-4fd0-8c8e-67660563c3af.png)
For this point, ideally we'd change the copy according to the theme.   Because BC and [Pendant](https://href.li/?https://pendantdemo.wordpress.com/), [Cultivate](https://href.li/?https://cultivatedemo.wordpress.com/), [Archeo](https://href.li/?https://archeodemo.wordpress.com/), [Yuga](https://href.li/?https://yugademo.wordpress.com/) all put content in the template.  Thus user edits both design and content in the Site Editor.

But for other themes, that work in the "traditional" way the messaging should be edit content in the Page Editor. 

Proceed with caution to this slack thread:9 p1666034981840009-slack-C02M88KJ684 it is loooong.

**Comment by autumnfjeld** [comment]
This has been prioritized and sent to @Automattic/t-rex . See pekYwv-fE-p2
<img width="745" alt="image" src="https://user-images.githubusercontent.com/5665959/207142651-5dab707c-f982-4ee2-8eaa-845ed6ecba20.png">

**Comment by Copons** [comment]
With T-Rex taking over part of this issue, let me summarize a little bit looking back at the original request.

### Providing Better Location Awareness

Better labelling when landing in the Site Editor to ensure the user is aware of what they are editing.

For example:
- [x] https://github.com/Automattic/wp-calypso/issues/71274
- [ ] https://github.com/Automattic/wp-calypso/issues/71275

In some cases, we might need a Core Gutenberg upstream fix. That's ok and encouraged as always!

cc @SaxonF for design pointers.

### Clearer Naming

The original request suggested changing "Edit Site", but I concur with others that we should **not change it**, as Core is all-in with the "Site Editor" name.

I'd also argue that we should **not touch** the `Appearance -> Editor` position and labelling.
The Site Editor has been in beta for a while, but I suspect it won't be forever, and at some point it will be "promoted" somehow. Changing the menu item now, and potentially having to change it again soon-ish would only introduce confusion.

If we want to act upon any of these, I'd recommend waiting to see what Core does once the Site Editor is out of beta.

(This said, I don't have a strong opinion on this, so let's talk!)

### My Home "Edit Homepage" Task

- [x] https://github.com/Automattic/wp-calypso/issues/71277

This is a nasty one with countless combinations, and will need to be properly investigated.

Let's start from Autumn's [comment above](https://github.com/Automattic/wp-calypso/issues/68953#issuecomment-1283454135) that provides pointers to external resources and conversations about this.

**Comment by dsas** [comment]
I think Gutenberg 14.8 has gone _some_ way towards addressing this, it's _sometimes_ much clearer than it was but once you enter "full screen" editor mode there's no improvement. Here's a quick 1 minute tour:


https://user-images.githubusercontent.com/93301/208448867-dea85314-75ab-4d16-9aac-0d305a7f1661.mp4

**Comment by mmtr** [comment]
> The original request suggested changing "Edit Site", but I concur with others that we should not change it, as Core is all-in with the "Site Editor" name.

As discussed in p1675791999480439-slack-C04DZ8M0GHW, that's a good call as default, but what pc4f5j-2wc-p2#theme-activation says is that the "Edit site" wording is particularly confusing after switching to a new theme (it gives users the wrong expectation that they should only edit the content, not the appearance or design of the site).

So I opened https://github.com/Automattic/wp-calypso/pull/73274 to change the CTA's text to "Customize site" which hopefully provides a clearer expectation.

**Comment by dsas** [comment]
Finally closing, https://github.com/Automattic/wp-calypso/issues/71275 was the last remaining task and upstream are going another way.
