### ISSUE TITLE
Secondary pages header (Breadcrumbs)

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#69179]
Part of the modernization project (p1HpG7-igQ-p2).

# Development
- [x] Introduce new page header behind a feature flag. (#69372)
- [x] Reconstruct backlinks using the site slug instead performing string manipulation on the current path. ([reference](https://github.com/Automattic/wp-calypso/pull/69372#pullrequestreview-1171254692)) (#69844)
- [x] Release the new page header to the public. (#69877)
- [x] Remove deprecated code related to the old header. (#69877)

# Design

Detailed pages should have a different type of header, more focused on relative (vs absolute) navigation.

- First item should always be the main Stats page where the jump originated from (Traffic, Insights, etc.)
- Chevron between the items.
- Last item should be the item name: a blog post title (“Land of fire and ice”), a metric name (“Countries", "Pages & Posts"), etc.

This header is already present in some sections in WordPress.com:

- Domain: https://wordpress.com/domains/manage/all/SITE_URL/edit/SITE_URL
- Plugins: https://wordpress.com/plugins/wordpress-seo-premium
- And probably other sections too.

Below you'll find the Before/After comparison as well as specs:

![Image](https://user-images.githubusercontent.com/390760/195898723-db3d2a33-1c13-4b6f-b285-24a9b628d6e6.png)

![Image](https://user-images.githubusercontent.com/390760/196402217-b3cfc0ff-f247-412a-ae0e-693dc301ad04.png)

**Comment by jsnmoon** [comment]
@a8ck3n: I've added a new subtasks breakdown in the development section.

**Comment by jsnmoon** [comment]
@a8ck3n, @keoshi, @jeffgolenski: Can we consider this task complete?

**Comment by keoshi** [comment]
Yeah, I believe so. Just checked all detailed views (aka secondary pages) and the new header was present on all of them.
