### ISSUE TITLE
Video screen in Blank Canvas Pattern Assembler flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#69175]
# Description 
To offer users extra help before landing in the Site Editor we will add two screens at the end of the PA flow, like we do in the Write(Blog) flow. See this Figma for context in the Pattern Assembler Flow ifmp3NXprvQqRLgzI1dDaU-fi-92%3A101

### Data justification
In the Write flow, on average, about 100/day click through to the video screen.  See this slack discussion on data p1665974172025759/1665974081.129129-slack-CRWCHQGUB.  This is significant enough to justify usefulness of video education in onboarding for a subset of users.  HE has also done investigations on how screencasts help users, pc4ICr-J7-p2 , and are advocating for this video UI, see pbxlJb-2yb-p2#comment-1946

![image](https://user-images.githubusercontent.com/5665959/196388926-988a88b1-a727-4040-9fc8-ad3ffcfdf4d3.png)

### Screen1 
![image](https://user-images.githubusercontent.com/5665959/196601999-ba6a98cd-9cff-436b-887c-e47093b74c83.png)

**Copy**
On the left:
* Heading text: Nice job! Now it's time to get creative. 
  * Subheading:  Continue to the WordPress Site Editor or take a few moments to learn the basics.
On the right (there will be two items)

Item1
* Customize your homepage [btn: Start creating]
  *  Edit your content and style your site

Item2 
* Learn the basics [btn: Start learning]
  * Watch videos and be site building in minutes 

### Screen2: Video Screen
![image](https://user-images.githubusercontent.com/5665959/196602074-d50acce1-e997-4216-9e50-e0335facbe05.png)
**Copy**
* Learn the basics of site editing
* Familiarize yourself with WordPress
* Upskill quickly to harness key design tools
* Set yourself up for creative success

# Tasks
- [ ] contact editorial for copy work/ approval [@autumnfjeld ]
- [ ] videos are here pbxlJb-2TD-p2#comment-2069
- [ ] Implement the screens in the PA flow (using existing components/[code](https://github.com/Automattic/wp-calypso/blob/47f215c10f565daf0e5a831b08ca71c977166a05/client/signup/videopress-step-wrapper/index.jsx) [dev]

# Testing
* todo

**Comment by autumnfjeld** [comment]
I'm not yet sure if we should make this mandatory for MVP.  I would really like to if we can get it done quickly.  Looks like we have videos: https://ganonp2.wordpress.com/2022/10/13/ganon-q4/#comment-1929

**Comment by miksansegundo** [comment]
Here is a relevant video [Understanding the Page Editor vs. Site Editor](https://learn.wordpress.org/tutorial/understanding-the-page-editor-vs-site-editor/)

**Comment by autumnfjeld** [comment]
One thing in that video though is it stresses editing content in Page editor and we don't want to give that message in the PA flow. 🤔

**Comment by autumnfjeld** [comment]
@SaxonF We will need a new graphic and copy help on this one.   I’m working on copy help.  Can you help with the new graphic?

**Comment by autumnfjeld** [comment]
For reference on style/tone/length, here are a few of the videos in the Blog Flow:

https://wpcommedia.files.wordpress.com/2022/08/create_page_long_-1.mov
https://wpcommedia.files.wordpress.com/2022/08/social_icons_long_-1-2.mp4
https://wpcommedia.files.wordpress.com/2022/08/right_blocks_long_-1.mov

**Comment by autumnfjeld** [comment]
See Saxon's copy suggestions: https://ganonp2.wordpress.com/2022/10/27/mini-pt-video-screen-for-pattern-assembler/#comment-2011

**Comment by autumnfjeld** [comment]
Note that the videos will be in English, however we can show these screens to all languages, and then on the video screen include a link for "Request translation of these videos" 

e.g. like this existing event: calypso_courses_translation_support_link_click

**Comment by autumnfjeld** [comment]
I have updated copy in this issue.  It is good to go.

**Comment by arthur791004** [comment]
I'll take this ticket if nobody wants 🙂

**Comment by arthur791004** [comment]
Close it in favor of https://github.com/Automattic/wp-calypso/issues/70189
