### ISSUE TITLE
Add mobile app promo card

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/wp-calypso#69230]
# Development

- [x] Create PromoCard component in `@automattic/components`. (#69819)
- [x] Address feedback on PromoCard component. (#69917 & #70023)
- [x] Update URLs/QR code to go to Jetpack mobile app. (#70028)
- [x] Design review (if needed).
- [x] Add iOS/Android device detection and show correct app store badge. (#70165)
- [x] Add support for Jetpack Redirect links. (#70926)
- [x] Add support for tracking click events. (#71190)
- [x] Add component to bottom of Stats pages (including Tracks support). (#71201)

# Design

Part of the modernization project (p1HpG7-igQ-p2).

Let's tell users about our mobile app and communicate the fact that they can see Stats on the go with Jetpack.

This design matches the new visuals present in WordPress.com: pcdRpT-16c-p2

![Image](https://user-images.githubusercontent.com/390760/196480593-d074cf17-abde-416f-838f-eee8e5697d46.png)

![Image](https://user-images.githubusercontent.com/390760/196480634-20307b7b-e20a-43ee-a129-b16523a87120.png)

**Comment by a8ck3n** [comment]
Two questions regarding the behaviour here.

1. Should we be using the Apple app store badge here or should we show a more generic app store badge that just links to our wp.com/app page? With this approach, we'd push any device detection logic to the external page.
2. Or should we try detecting the device and present the correct badge based on that? In which case, we'd need SVG data for a Google app store.

Any thoughts on this one @jeffgolenski? Thanks!

**Comment by a8ck3n** [comment]
Note that this is currently on hold pending [some investigation](https://github.com/Automattic/wp-calypso/pull/70059#issuecomment-1319365005) from the design team.

**Comment by a8ck3n** [comment]
I believe we're all done with this. The card is now integrated on the Stats page. Will open follow up issues for integration on other pages as needed.

@jsnmoon Please re-open if you think I've missed anything here. Thanks!
