### ISSUE TITLE
[Bug]: E2E tests failing for various editor-tracking events

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#69254]
### Quick summary

End to end tests are currently failing for a range of editor tracking events. Here's a summary of current status per file:

- [x] `test/e2e/specs/editor-tracking/editor-tracking__block-inserted-events`
   - Current status on trunk: Test Suites: 1 failed, 1 total. Tests: 1 failed, 4 skipped, 21 passed, 26 total.
- [x] `test/e2e/specs/editor-tracking/editor-tracking__fse-template-events`
   - These were fixed in this PR, but one test appears to have re-broken since then.
   - Current status on trunk: Test Suites: 1 failed, 1 total. Tests: 1 failed, 18 passed, 19 total.
- [ ] `test/e2e/specs/editor-tracking/editor-tracking__global-styles-events`
   - Current status on trunk: Test Suites: 1 failed, 1 total. Tests: 2 failed, 14 skipped, 10 passed, 26 total.
- [x] `test/e2e/specs/editor-tracking/editor-tracking__other-block-events`
   - Current status on trunk: All tests passing.
- [x] `test/e2e/specs/editor-tracking/editor-tracking__pattern-events`
   - Current status on trunk: Test Suites: 1 failed, 1 total. Tests: 2 failed, 3 skipped, 2 passed, 7 total.
- [x] `test/e2e/specs/editor-tracking/editor-tracking__toolbar-events`
   - Current status on trunk: All tests passing.

### Steps to reproduce

Setup and run test specs following the instructions here: 
https://github.com/Automattic/wp-calypso/tree/trunk/test/e2e

### What you expected to happen

All tests should pass. 

### What actually happened

A range of tests fail or are skipped. See output per file above. 

### Reproducibility

Consistent

**Comment by jordesign** [comment]
Hey @edanzer  - based on the timeframe, and there only being one test that still needed looking at - does this issue still need to be open and addressed?

**Comment by edanzer** [comment]
Hi @jordesign! I don't know the status of that last E2E item, but this is an old issue and lot has changed in terms of personal / team / company focus since this was opened. I think we can close the issue at this point.
