### ISSUE TITLE
Site Editor Tracking - Add event for tracking document actions dropdown

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/wp-calypso#69630]
We need to add tracking events for the document actions dropdown in the site editor:

![image](https://user-images.githubusercontent.com/28742426/199086875-7a138bde-25a0-46c7-b9f2-3d035747761d.png)

We should have events for:

- [ ] Opening the panel
- [ ] Selecting an item in the panel ('header', 'footer', 'browse all templates') as seen above.

FG info related to events - PCYsg-nrf-p2

**Comment by Addison-Stavlo** [comment]
events have been added in -  https://github.com/Automattic/wp-calypso/pull/69642

We still plan to:

- [x] create e2e cases to cover the basic interactions here
- [x] register/verify the events on tracks.

And can close this issue once those follow ups are complete.

**Comment by jeyip** [comment]
https://github.com/Automattic/wp-calypso/pull/69803 create e2e cases to cover the basic interactions here

**Comment by jeyip** [comment]
Registering tracks events now

**Comment by jeyip** [comment]
The UI has changed, so some event tracking is no longer valid, but I've registered `wpcom_site_editor_document_actions_dropdown_open` https://github.com/Automattic/tracks-events-registration/pull/1497
