### ISSUE TITLE
Free Onboarding Flow Tracking Issue

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#69899]
### Details

This is a tracking issues for task related to the new Free Flow, which will be based on stepper and use architecture similar to our existing tailored flow cases like newsletters and link in bio websites. 

### On Deck ###

- [ ] https://github.com/Automattic/wp-calypso/issues/70845
- [x] https://github.com/Automattic/wp-calypso/issues/72268
- [x] https://github.com/Automattic/wp-calypso/issues/72269

### Done
- [x] https://github.com/Automattic/wp-calypso/pull/70350
- [x] https://github.com/Automattic/wp-calypso/issues/70843
- [x] Ensure My Home redirects to launchpad.
- [x] https://github.com/Automattic/wp-calypso/issues/70556
- [x] https://github.com/Automattic/wp-calypso/issues/70558
- [x] https://github.com/Automattic/wp-calypso/issues/69921 
- [x] https://github.com/Automattic/wp-calypso/issues/71280
- [x] https://github.com/Automattic/wp-calypso/issues/70559
- [x] https://github.com/Automattic/wp-calypso/issues/70844
- [x] https://github.com/Automattic/wp-calypso/issues/69920 
- [x] https://github.com/Automattic/wp-calypso/issues/71353
- [x] https://github.com/Automattic/wp-calypso/issues/71354

Abandoned
- [ ] https://github.com/Automattic/wp-calypso/issues/70842

### Relevant Links
- Project Thread: paYE8P-2bD-p2
- Marketing Plan: p5uIfZ-cw9-p2
- P2: p9Jlb4-5ST-p2

**Comment by agrullon95** [comment]
@Addison-Stavlo / @ebinnion - Is the [optional domain name generator button](https://github.com/Automattic/wp-calypso/issues/69922) supposed to be displayed on the existing sign up flow?

**Comment by jeyip** [comment]
> Is the https://github.com/Automattic/wp-calypso/issues/69922 supposed to be displayed on the existing sign up flow?

Designers are in the process of creating mocks. Eric says "I would focus efforts right now on the backend, such as getting the library in place, endpoint, etc." ( [link](p1668451042654359/1668450288.931879-slack-CHN6J22MP) )

**Comment by edanzer** [comment]
Following a lot of discussion, we have decided to try creating a new Free Flow based on Stepper. This is inline with all our other recent work on tailored flows as well as efforts to move generic onboarding screens like Domains and Plans to stepper.

With this in mind, I prepared an [initial PR](https://github.com/Automattic/wp-calypso/pull/70350) to set up the scaffolding for a stepper-base Free flow. I also updated the task list above with follow up tasks based on this approach.

**Comment by obenland** [comment]
@Addison-Stavlo @jeyip Is https://github.com/Automattic/wp-calypso/issues/70845 the only remaining item before this can be closed?

**Comment by Addison-Stavlo** [comment]
Actually I think we have those in place already too, unless @edanzer had any other events in mind we might be missing here?

> the only remaining item before this can be closed?

We could either keep it open to track future follow ups we may tend to, or just close this and move forward.

**Comment by edanzer** [comment]
> unless @edanzer had any other events in mind we might be missing here?

I do have one last PR open to update how/when calypso_signup_start fires for our new stepper flows. Should be done today or Monday. I wouldn't keep this open for that though. So we can close or, if we do keep it open, do so for future follows. Sounds like we may just want to close it though.

**Comment by obenland** [comment]
Let's close! 🎉
