### ISSUE TITLE
Launchpad i1

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#70067]
The Launchpad will be a modular checklist that will help guide users through specific use case onboarding flows. These sites will enter the LaunchPad flow instead of standard Calypso interfaces after initial onboarding steps, and the LaunchPad will help guide them to reach their specific goals. The LaunchPad will be in place of standard management interfaces until the launch flow is complete, or the LaunchPad itself is disabled.

Project Thread: paYE8P-1Kg-p2

**Iterations included:**

- [ ] [Launchpad: Copy to Clipboard](https://github.com/Automattic/wp-calypso/issues/68967)
- [ ] [Launchpad: Upgrade domain badge](https://github.com/Automattic/wp-calypso/issues/68969)
- [ ] [Launchpad: Email Validation message](https://github.com/Automattic/wp-calypso/issues/68961)
- [ ] [Launchpad: Small Iterations](https://github.com/Automattic/wp-calypso/issues/68900)
- [ ] [Launchpad: Improve the experience from Launchpad → Editor](https://github.com/Automattic/wp-calypso/issues/68971)
