### ISSUE TITLE
☂️ Theme Showcase: Improve search/filter UX

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#70162]
## Description
Currently, the search and filter experience in the Theme Showcase is done via three components: search, category filter, and pricing component. For a seamless search and filter experience, when the state of one of the components changes, the others should also reflect said change. The issue aims to track all the inconsistencies found so far:

- [x] When filtering for `subject:podcast` in the search box, the Podcast filter is automatically selected. But it is not the other way around: If I click on Podcast, the search box is not automatically filled with `subject:podcast`. #70322
- [x] When filtering for "Podcast" in the category filter, changing to "Portfolio" doesn't update the search box with `subject:portfolio`. #70322
- [x] Multiple subjects can be filtered in the search box, but only one category filter can be selected. When filtering for a subject in the search box, it should replace any existing filtered subject. #70283
- [x] Dead area between the dropdown suggestion list items, where clicking it will close the dropdown unexpectedly. #70401
- [x] Selecting the Feature term "Blog Excerpts" will unexpectedly switch subject filter to "Blog". #70800

**Comment by bangank36** [comment]
I'm looking at these issue atm

**Comment by bangank36** [comment]
These are recordings to describe the current UX issues

1.  The search box does not reflect subject change upon clicking on category filter

![Screen Capture on 2022-11-23 at 11-23-40.gif](https://cdn-std.droplr.net/files/acc_1243635/pKdjlL)

2. Search input should replace existing filtered subject

![Screen Capture on 2022-11-23 at 11-29-30.gif](https://cdn-std.droplr.net/files/acc_1243635/wdIlfk)

3. Seach input should remove duplicate filter criteria

![Screen Capture on 2022-11-23 at 11-32-28](https://user-images.githubusercontent.com/10071857/203464729-289622ed-66c6-4c95-a783-59a01520e7bb.gif)

**Comment by taipeicoder** [comment]
There is a dead area where clicking it will unexpectedly close the search dropdown: 
https://user-images.githubusercontent.com/797888/203757314-223c0ce3-9831-411d-bcaf-f2fcd13844eb.mp4

**Comment by bangank36** [comment]
Good catch, I think it is caused by this, will propose a PR

![Screenshot on 2022-11-24 at 18-26-50.png](https://cdn-std.droplr.net/files/acc_1243635/2jB5iP)

**Comment by bangank36** [comment]
@taipeicoder Should we leave this ticket open to collect feedbacks about UX from the Cft post? Thanks

**Comment by taipeicoder** [comment]
Jupiter team jotted down their feedback in pdtkmj-OF-p2#comment-134. Could you check which ones we can do short-term?

**Comment by bangank36** [comment]
> Jupiter team jotted down their feedback in [pdtkmj-OF-p2#comment-134](https://href.li/?https://wp.me/pdtkmj-OF#comment-134). Could you check which ones we can do short-term?

Thanks for heads up, I did not check the post this morning! Having a look now

**Comment by taipeicoder** [comment]
Added: Selecting the Feature term "Blog Excerpts" will unexpectedly switch subject filter to "Blog".

**Comment by bangank36** [comment]
> Added: Selecting the Feature term "Blog Excerpts" will unexpectedly switch subject filter to "Blog".

I can reproduce that, will have a look

**Comment by bangank36** [comment]
Seems like "Blog Excerpts" creates url `themes/filter/blog-excerpts/${siteSlug}` and messes up with the method `getTabFilterFromUrl` since it did not find the exact string in URL. Will propose a fix tomorrow

**Comment by bangank36** [comment]
@taipeicoder Should we hide these tags or update their label? 
![image](https://user-images.githubusercontent.com/10071857/205816942-94b9c252-05a0-453f-99f8-7dfd3af323da.png)

**Comment by taipeicoder** [comment]
@bangank36 updating label would be nice 🙂
Also, we can close this issue and keep track future improvements individually.

**Comment by bangank36** [comment]
Closed as landed, follow-up issues will be tracked on individual issue
