### ISSUE TITLE
Metrics for Pages and virtual home page links

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70487]
# Description

We are about to ship  "Virtual pages" for `home.html` and `front-page.html` templates pages.  https://github.com/Automattic/wp-calypso/issues/69158  We need to add tracks events.

![Image](https://user-images.githubusercontent.com/5665959/204340265-6a51e797-ab22-42c6-9337-a46aab95df38.png)

<img width="170" alt="image" src="https://user-images.githubusercontent.com/5665959/204354695-550cf961-837b-4be4-9fc1-5f3eb6ee123b.png">

# Tasks
- [x] Review FG naming convention if you are unfamiliar: PCYsg-4S2-p2
- [x] Implement the tracks events in the table below
- [x] Register the events in Tracks `/tracks/events/`
- [x] Flag with @autumnfjeld if we've missed any other items that should be tracked
- [x] Ask @autumnfjeld for review when ready for testing

| UI element        | Event name           | Prop | PR | Done? ✅ |
| ------------- |:-------------| ------| :-----:|-----:|
| Add new page     |  `calypso_pages_addnewpage_click` |  N/A | [PR](https://github.com/Automattic/wp-calypso/pull/70565) | ✅ |
| Click on a real page link  |  `calypso_pages_page_title_click`  | page_type=`real` |  #70618 | ✅  |
| Click on a virtual page link  |  `calypso_pages_page_title_click`  | page_type=`virtual` |  #70637  | ✅  |
| Ellipsis menu  | `calypso_pages_ellipsismenu_open_click`      | N/A | #70626  |  ✅  |
|  Ellipsis menu Edit | `calypso_pages_ellipsismenu_item_click`   | item=`editpage` |   | ✅ |
|  Ellipsis menu View page | `calypso_pages_ellipsismenu_item_click`   | item=`viewpage` |   | ✅ |
|  Ellipsis menu Stats | `calypso_pages_ellipsismenu_item_click`   | item=`viewstats` |   | ✅ |
|  Ellipsis menu Copy page | `calypso_pages_ellipsismenu_item_click`   | item=`copypage` |   | ✅ |
|  Ellipsis menu Copy link | `calypso_pages_ellipsismenu_item_click`   | item=`copylink` |   | ✅ |
|  Ellipsis menu Export page | `calypso_pages_ellipsismenu_item_click`   | item=`exportpage` |   | ✅ |
|  Ellipsis menu QR Code | `calypso_pages_ellipsismenu_item_click`   | item=`qrcode` |   | ✅ |

Please update table with a ✅ for each event. If event names get updated, please make sure that is reflected in the table.

# References
* pdtkmj-MO-p2#comment-1253
* https://github.com/orgs/Automattic/projects/338/views/1?filterQuery=virtual+page

**Comment by bangank36** [comment]
@autumnfjeld do we need to implement the Stats and QR menu item for the virtual page three dots menu? If we do, then we may need to update the Ellipsis menu props pdtkmj-MO-p2#comment-1292

**Comment by autumnfjeld** [comment]
@bangank36  & @fushar 

> do we need to implement the Stats and QR menu item for the virtual page three dots menu? 

You mean this issue: https://github.com/Automattic/wp-calypso/issues/70569
Yes, that issue needs to be done. :). And when that issue is done, it should have metrics for stats and QR.  I have added info about metrics to #70569.


This issue here #70487  is just for the metrics that can currently be added.  #70569 is not a blocker for this issue. Does that make sense?




When this issue is worked on pdtkmj-MO-p2#comment-1342

**Comment by bangank36** [comment]
@autumnfjeld for event `calypso_pages_page_edit_click`, I suggest changing the name to `calypso_pages_page_title_click`, since the page title will not always navigate to page editor ( [depends on user privilege](https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/my-sites/pages/page/index.js#L547) ), we can add new prop for event ( can\_edit ) if needed. What do you think?

cc: @fushar

**Comment by miksansegundo** [comment]
@bangank36 I've added a task to register the events in Tracks.

**Comment by fushar** [comment]
> @autumnfjeld for event calypso_pages_page_edit_click, I suggest changing the name to calypso_pages_page_title_click, since the page title will not always navigate to page editor ( depends on user privilege )

Sorry for late reply. Agree. To be consistent with the existing GA event.

> we can add new prop for event ( can_edit ) if needed

I don't think it's necessary for now though 😄 I don't see any useful use case for that (now)

**Comment by fushar** [comment]
> pagetype=virtual

I'd suggest `pagetype=virtualhomepage` as it's possible to have more virtual pages in the future (e.g. posts page), sounds good?

**Comment by fushar** [comment]
> pagetype=real

@autumnfjeld Sorry for being very nitpicky but what about `regular`? So regular vs. virtual. `real` implies that the other types are "nonexistent" (dunno, maybe it's just me?)

**Comment by bangank36** [comment]
> > pagetype=virtual
> 
> I'd suggest `pagetype=virtualhomepage` as it's possible to have more virtual pages in the future (e.g. posts page), sounds good?

I'd like to keep `pagetype=virtual` and add additional props to identify the template name if needed

**Comment by fushar** [comment]
> add additional props to identify the template name if needed

We could but the problem is that the virtual homepage's template can be Front Page / Home / Index. So it will be hard to track that "the user clicked on the virtual homepage link"

Let's wait for @autumnfjeld 😄

**Comment by fushar** [comment]
Another question: for the `calypso_pages_ellipsismenu_*` events, do we need to add the `page_type` props as well?

**Comment by autumnfjeld** [comment]
Thanks everyone for being thorough with suggestions!

> for event calypso_pages_page_edit_click, I suggest changing the name to calypso_pages_page_title_click, ince the page title will not always navigate to page editor ( [depends on user privilege](https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/my-sites/pages/page/index.js#L547) ),

Yes, agree.
Adding a prop now is important, because we may want to filter on users that are going to the editor.  Let's do your suggestion @bangank36 : `can_edit`

> I'd suggest pagetype=virtualhomepage as it's possible to have more virtual pages in the future (e.g. posts page), sounds good?

I see your point, but I'm not sure.  We don't track the type of "standard" page, e.g. we aren't tracking if user clicks on a contact page or an about page or home page.   I think for that we could implement another prop in the future `template=home | front-page | page | whatever |` or `virtual_type = home | single | 404 | page `.  When/if we have more virtual pages we can decide how to identify this if needed.
 
Oh, I just saw @bangank36 said the same
> I'd like to keep pagetype=virtual and add additional props to identify the template name if needed

Yes.

> Sorry for being very nitpicky but what about regular? So regular vs. virtual. real implies that the other types are "nonexistent" (dunno, maybe it's just me?)

Doesn't virtual mean not-real? 😄    I'm fine with `real` or `regular` or `standard`.    @bangank36 you can be the DM here (Decision Maker)


> do we need to add the page_type props as well?

Yes, this is a good idea. :) 

<img width="74" alt="image" src="https://user-images.githubusercontent.com/5665959/205134444-5de6d0ac-9ae3-4bd2-8101-f51b751f0262.png">

**Comment by autumnfjeld** [comment]
For changes to props event names, please update the issue description. 😃 

Let me know when this ready to test. Thank you!

**Comment by fushar** [comment]
Thanks @autumnfjeld. We'll stick with the original plan then (`can_edit`, `virtual`, `real`) 😄

**Comment by autumnfjeld** [comment]
| Trigger | Event | Props | Aut Verified |
|-|-|-|-|
| User clicks virtual homepage card<br><img width="265" alt="image" src="https://user-images.githubusercontent.com/1525580/205231681-d55f47b5-5fe8-450b-b7a2-c6929a1c250b.png"> | `calypso_pages_page_title_click` | `page_type: virtual` |  ✅ |
| User clicks to open the ellipsis menu<br><img width="209" alt="image" src="https://user-images.githubusercontent.com/1525580/205232035-87f5d92e-d26a-4792-98a7-ff031d3b129c.png"> | `calypso_pages_ellipsismenu_open_click`<br><br>Existing GA event:<br><img width="475" alt="image" src="https://user-images.githubusercontent.com/1525580/205234156-538b30fb-3c2e-4a81-b3ea-174598b4a584.png"> | `page_type: virtual` |  ✅  |
| User clicks the Edit menu item<br><img width="206" alt="image" src="https://user-images.githubusercontent.com/1525580/205232282-e6230fff-d886-4885-aa7b-3f92d34c9f05.png"> | `calypso_pages_ellipsismenu_item_click`<br><br>Existing GA event:<br><img width="397" alt="image" src="https://user-images.githubusercontent.com/1525580/205233767-1ec8fae2-ca90-47fd-8748-829121511022.png"> | `page_type: virtual`<br>`item: editpage` | ✅ |
| User clicks the View page menu item<br><img width="184" alt="image" src="https://user-images.githubusercontent.com/1525580/205232677-76d9f4ea-b02b-454f-8f1f-10261d520bd8.png"> | `calypso_pages_ellipsismenu_item_click`<br><br>Existing GA event:<br><img width="425" alt="image" src="https://user-images.githubusercontent.com/1525580/205234306-abb34474-dfd9-46ed-9159-6d2cdc6e4ef5.png"> | `page_type: virtual`<br>`item: viewpage` |  ✅ |
| User clicks the Copy link menu item<br><img width="190" alt="image" src="https://user-images.githubusercontent.com/1525580/205232983-13f793cd-4ec1-44e2-97f6-15a33c5357c1.png"> | `calypso_pages_ellipsismenu_item_click`<br><br>Existing GA event:<br><img width="457" alt="image" src="https://user-images.githubusercontent.com/1525580/205234422-d1fb4101-2ee0-49c0-b6f8-778ea680662b.png"> | `page_type: virtual`<br>`item: copylink` | ✅ |


## Verification screenshots
<img width="513" alt="image" src="https://user-images.githubusercontent.com/5665959/206294467-5d6ab38e-d04c-4fb1-bd86-9a27507cafd7.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/5665959/206294776-c9f16916-165d-4d8b-bddf-5d8c472878a6.png">

<img width="815" alt="image" src="https://user-images.githubusercontent.com/5665959/206294926-4a5b78d7-e491-4e26-9b43-a7fecacc3558.png">

<img width="826" alt="image" src="https://user-images.githubusercontent.com/5665959/206295102-9b64c38f-510e-4d84-b429-f743e701a223.png">

<img width="818" alt="image" src="https://user-images.githubusercontent.com/5665959/206295639-daaed6a6-8ae4-4264-9487-efd45a218441.png">

And a sampling of verification for real pages:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/5665959/206296379-8723398a-e721-4c52-b81a-f9ec5e296aca.png">


<img width="827" alt="image" src="https://user-images.githubusercontent.com/5665959/206296141-646603e0-abed-49e2-894e-6dc578e683a1.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/5665959/206296197-d1adf193-7686-4df9-8abc-3dc77e1531b0.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/5665959/206296235-63b892f0-e8a0-435e-b44f-1bc5478ada20.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/5665959/206296489-e9736d8e-e5df-47a8-a1ce-bcdf436840aa.png">

**Comment by autumnfjeld** [comment]
@bangank36  The events are  not registered and validated in tracks. This is in the checklist of the issue description.
![image](https://user-images.githubusercontent.com/5665959/206297891-7dacd009-5b06-4326-953e-e077bfec0d39.png)



I just registered and validated this one:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/5665959/206297668-33e8ef8a-91b7-4385-8d47-9c463f9ed4cf.png">

Can you go through all the events and make sure they are both validated and registered with sufficient documentation?

<img width="644" alt="image" src="https://user-images.githubusercontent.com/5665959/206298887-af027479-6adf-463d-8a9c-9a8af14d1c40.png">


p.s. I just noted this "mistake" in the prompt here

<img width="541" alt="image" src="https://user-images.githubusercontent.com/5665959/206298940-443fbc92-7ef6-432f-ab9c-5b7490da51bd.png">

An event definitely DOES NOT measure "how many times" it measures one click.   So a proper  entry would be "when a user clicks button/link X"

**Comment by bangank36** [comment]
The note on 'mistake' makes sense to me

**Comment by bangank36** [comment]
> Can you go through all the events and make sure they are both validated and registered with sufficient documentation?

Absolutely, doing it today

**Comment by bangank36** [comment]
Events has been registered as follow:

<table><tbody><tr><td>Event</td><td>Screenshot</td><td>URL</td></tr><tr><td>`calypso_pages_page_title_click`</td><td><figure class="image"><img src="https://cdn-std.droplr.net/files/acc_1243635/RWY6qt" alt="Screenshot on 2022-12-08 at 09-59-19.png"></figure></td><td><a href="/tracks/events/event.php?eventname=calypso_pages_page_title_click">tracks</a></td></tr><tr><td>`calypso_pages_addnewpage_click`</td><td><figure class="image"><img src="https://cdn-std.droplr.net/files/acc_1243635/ZwxLJN" alt="Screenshot on 2022-12-08 at 10-00-34.png"></figure></td><td><a href="/tracks/events/event.php?eventname=calypso_pages_addnewpage_click#">tracks</a></td></tr><tr><td>`calypso_pages_ellipsismenu_open_click`</td><td><figure class="image"><img src="https://cdn-std.droplr.net/files/acc_1243635/FXL8Iy" alt="Screenshot on 2022-12-08 at 10-01-04.png"></figure></td><td><a href="/tracks/events/event.php?eventname=calypso_pages_ellipsismenu_open_click#">tracks</a></td></tr><tr><td>`calypso_pages_ellipsismenu_item_click`</td><td><figure class="image"><img src="https://cdn-std.droplr.net/files/acc_1243635/5hh7wj" alt="Screenshot on 2022-12-08 at 10-01-25.png"></figure></td><td><a href="/tracks/events/event.php?eventname=calypso_pages_ellipsismenu_item_click#">tracks</a></td></tr></tbody></table>
