### ISSUE TITLE
Tracking Issue: Free Flow 

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#70491]
### Details

This is a tracking issues for task related to the new Free Flow, which will be based on stepper and use architecture similar to our existing tailored flow cases like newsletters and link in bio websites. 

**Screen: Setup**
- [x] Add domain generation field to Free Setup screen

**Screen: Chose Design**
- [x] Update design to match mockups in Free Flow P2 post (or Figma when ready). We will need to determine which themes we're showing. We may need to discuss fact that different themes need different setup steps - this is different than what we've encountered with Newsletter and Link in Bio, which have very specific and limited theme options. 

**Screens: Domains & Plans**
- [x] Remove Domains screen. Without a domains screen, we will need to provide the domain from the domain generator on the Free Flow - Setup screen to site setup process. 
- [x] Remove Plans screen. Without a plans screen, we may need to directly provide provide 'free' plan to site setup process. 

**Screen: Post Setup**
- [x] Add Free Post-Setup flow and screen.

**Screen: Launchpad**
- [x] Enable link to Edit Site Design screen.
- [x] Enable link to Personalize Website screen (requires Free Post Setup screen first).
- [x] Add task completion logic for Edit Design Screen. Should update when site editor is visited or saved?
- [x] Fix task completion logic for Write First Post task. Should use existing logic to update task when post is saved.
- [ ] Disabled Launch task until other tasks are completed?
- [x] Update web copy to match mockups in Free Flow P2 post (or Figma when ready)

**Screen: My Home**
- [x] Ensure My Home redirects to launchpad. It currently redirects to the Goals screen of the older startup flow for some reason.

**Comment by edanzer** [comment]
Just updated [this existing tracking issue](https://github.com/Automattic/wp-calypso/issues/69899) for free flows rather than create a new one here.
