### ISSUE TITLE
Build default theme: change default theme for build flow to Twenty Twenty Three

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#70604]
# Description

Change default theme for **build flow** from Zoologist to Twenty Twenty Three, because zoologist is not great for the build flow and TT3 is a nice multipurpose theme. And as Ian said, it makes sense to have the default be a WP org theme.  Autumn will do this task.

Check out the very cool style variations in this theme:

| Cool Purple Variation  | Cool Salmon Variation  |
| --- | --- |
| ![Image](https://user-images.githubusercontent.com/5665959/204905295-30021b04-0b66-49d0-a527-18e6978597b1.png) | ![Image](https://user-images.githubusercontent.com/5665959/204905344-7ad61ae0-515b-4bb3-bcd2-6e64a9ac70cd.png)  |

### History of default theme changes
* 2020-03-05  Changed from Maywood to Hever  https://github.com/Automattic/wp-calypso/pull/39795
* 2021-11-03 Changed to Zoologist https://github.com/Automattic/wp-calypso/pull/57134 & https://github.com/Automattic/wp-calypso/issues/55277
* 2021-11-21 "Hero Flows" were shipped, introducing Build and Write(Blogger) onboarding flows https://github.com/Automattic/wp-calypso/pull/58223
* 2022-07-15 Changed Write from Zoologist to Livro Dark, thus Build & Blogger flows now have different default themes. https://github.com/Automattic/wp-calypso/pull/65535 &   https://github.com/Automattic/wp-calypso/issues/65035
* 2022-09-15  Changed Write flow from Livro Dark to Livro White  https://github.com/Automattic/wp-calypso/pull/67141 & D86760-code
* Now Changed Build from Zoologist to TT3

Related
* [Hero & Blogger Flow Ship Table] pdgK6S-iY-p2 
* [FTME Change Log / Ship Table] pbAok1-2MG-p2
* Livro info pdDOJh-JA-p2
* https://github.com/Automattic/wp-calypso/issues/76564

# Tasks
- [x] Change the default theme
  - [x] https://github.com/Automattic/wp-calypso/pull/71025
  - [x] D109689-code
- [x] Ensure that the starter content has only one Hello World post and an About page.   
- [x] Update the [default annotation](fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Surnqfgneg%2Snaabgngvbaf%2Sra.wfba%3Se%3Qnn84sq2p-og) to have only one Hello World post and an About page.
  - [x] D110180-code

**Comment by autumnfjeld** [comment]
There is current discussion on changing the default headstart annotation to have only ONE post and NO pages.  Or instead of the "Home" page, it should be an About or Sample page.

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Surnqfgneg%2Snaabgngvbaf%2Sra.wfba%3Se%3Qnn84sq2p%234-og

p1674754837126459/1674748273.748169-slack-C029FM1EH

p1674567054199089/1674460018.673149-slack-C048CUFRGFQ

**Comment by arthur791004** [comment]
Close it as it's completed via
* D110177-code
* D110180-code
* D109689-code
* https://github.com/Automattic/wp-calypso/pull/71025
