### ISSUE TITLE
Launchpad in My Home

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#70731]
This project aims to integrate the Launchpad within our current My Home page. Some areas involved in this project are Tailored Use Cases, Launchpad and My Home Page. The engineering team working on this project is @Automattic/cylon

**Milestone: https://github.com/Automattic/wp-calypso/milestone/417**

- [x] https://github.com/Automattic/wp-calypso/issues/70102
- [ ] https://github.com/Automattic/wp-calypso/issues/70728
- [ ] https://github.com/Automattic/wp-calypso/issues/70729
- [ ] https://github.com/Automattic/wp-calypso/issues/70730
