### ISSUE TITLE
Migrate package tests from `enzyme` to `@testing-library`

### ISSUE THREAD

**Issue by tyxla** [Automattic/wp-calypso#70873]
### Details

Migrate package tests that make use of `enzyme` to using `@testing-library`. For recent examples, see #63409 which encompasses our work on refactoring all tests in `client`.

See p4TIVU-ac2-p2 for background on why we're migrating.

Please tick the box and reference your PR when you're refactoring one of the listed components.

If you need a review or have any questions, please don't hesitate to ping @Automattic/team-calypso-frameworks. You might want to have a look at the [docs for `@testing-library`](https://testing-library.com/docs/react-testing-library/intro).

### Checklist

- [x] packages/components/src/button/test/index.js - @tyxla #70874
- [x] packages/components/src/card/test/index.js - @tyxla #70877
- [x] packages/components/src/progress-bar/test/index.jsx - @tyxla #70878
- [x] packages/components/src/root-child/test/index.jsx - @tyxla #70881
- [x] packages/components/src/suggestions/test/index.js - @tyxla #70882
- [x] packages/help-center/src/components/test/back-button.tsx - @noahtallen #70917
- [x] packages/onboarding/src/intent-screen/test/index.tsx - @tyxla #70930
- [x] packages/social-previews/test/index.js - @tyxla #70938

### Related

#63409

**Comment by tyxla** [comment]
All remaining tests have been migrated and this is ready for closing! ✅
