### ISSUE TITLE
eCommerce Flow - design tweaks

### ISSUE THREAD

**Issue by blackjackkent** [Automattic/wp-calypso#71244]
Notes from Saxon in Slack regarding tweaks for the eCommerce flow: 
* [x] Like Newsletter we can use loader bar at top to signify progress (#71341)
* [x] I noticed labels on forms inputs differ from newsletter, should look like screens (#71435)
* [x] The old address form was also shown for me post checkout now, intentional? (To be removed as part of #71472)
* [x] Domains aren't pre-populated with domain suggestions based on store name like Newsletter flow _(Can't reproduce)_.
* [x] [Adding](https://github.com/Automattic/wp-calypso/issues/71244#issuecomment-1354405313) "WooCommerce Powered" to welcome screen , loading and profiler (see Newsletter for an example and existing styles) (#71391)
* [x] To be consistent with other tailored flows it looks like we should re-use the initial background image for our loader (#71476, **needs review**)

**Comment by SaxonF** [comment]
One more little thing is domains aren't pre-populated with domain suggestions based on store name like Newsletter flow.

https://wordpress.com/start/newsletter/domains?new=My%20newsletter%20test&search=yes&hide_initial_query=yes&siteAccentColor=%23113AF5

**Comment by SaxonF** [comment]
One more. Adding "WooCommerce Powered" to welcome screen , loading and profiler (see Newsletter for an example and existing styles)

![image](https://user-images.githubusercontent.com/1072756/208060162-a620a629-9588-4ad7-b091-3e8e26fd927b.png)

![image](https://user-images.githubusercontent.com/1072756/208060180-3d60a207-3014-4168-add8-48725e39c4ff.png)

![image](https://user-images.githubusercontent.com/1072756/208060222-b677a54c-7c26-46d9-97b2-ae18323bfe27.png)

**Comment by blackjackkent** [comment]
> One more little thing is domains aren't pre-populated with domain suggestions based on store name like Newsletter flow.
> 
> https://wordpress.com/start/newsletter/domains?new=My%20newsletter%20test&search=yes&hide_initial_query=yes&siteAccentColor=%23113AF5

@SaxonF I can't reproduce your issue with this. When I use (for instance) the site title "Test Test ABC", I get these initial results prepopulated on the domain step:

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/13437011/208437062-1565abcc-fed3-4fdb-aabf-c08ccd08a9ef.png">

Can you let me know what you're seeing on your end?

**Comment by blackjackkent** [comment]
Opened a PR for the progress bar at #71341 ; I'll try to also get one in for the "WooCommerce Powered" labeling tomorrow before I'm off for the holiday.

**Comment by markbiek** [comment]
Example showing the difference between the form labels between the ecommerce and newsletter flows.

![image](https://user-images.githubusercontent.com/917632/209008124-635c173e-7c4a-4e60-ae5e-ee8ce3979c80.png)

**Comment by markbiek** [comment]
> The old address form was also shown for me post checkout now, intentional?

This step will most likely be removed as part of #71472.
