### ISSUE TITLE
Social/Marketing Assets Standardisation

### ISSUE THREAD

**Issue by Noemish** [Automattic/wp-calypso#71421]
Review and standardise Social assets

- [Ref 1](paqDfi-26A-p2)
- [Ref 2](pcUrMV-1V3-p2)

Main designer: @garretsteider-a8c 
Support designer: @jrdnhllr @Noemish

**Comment by garretsteider** [comment]
**Milestones:**
- [x] Social Review - Jan 17th 
- [x] Gather Feedback - Jan 17th - Jan 27
- [ ] Social assets guideline - Feb 28
