### ISSUE TITLE
Stats: Extract "key-container" to a reusable component

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#71762]
#### Post Detail page  - All-time Insights
<img width="1330" alt="截圖 2023-01-06 下午10 17 04" src="https://user-images.githubusercontent.com/6869813/211030362-65785bfd-3ed0-40b8-bd19-4adf74c9af48.png">

#### Insights page - All-time insights
<img width="1284" alt="截圖 2023-01-06 下午10 17 27" src="https://user-images.githubusercontent.com/6869813/211030368-7e5c638e-8154-4952-bd01-6ac7a2acfeda.png">

#### Insights page - Posting activity
<img width="1273" alt="截圖 2023-01-06 下午10 19 33" src="https://user-images.githubusercontent.com/6869813/211030376-467331eb-757e-4098-aad8-b70932e54a49.png">

#### Sub-Tasks
- [x] Create component as `HeatMapTableLegends`
( https://github.com/Automattic/wp-calypso/pull/71878 )
- [x] Post Detail page - All-time Insights
( https://github.com/Automattic/wp-calypso/pull/71878 )
- [x] Insights page - All-time insights
( https://github.com/Automattic/wp-calypso/pull/71878 )
- [x] Insights page - Posting activity
( https://github.com/Automattic/wp-calypso/pull/71948 )
- [x] Delete component [StatsViews](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/stats-views/index.jsx) and consolidate its styles
( https://github.com/Automattic/wp-calypso/pull/72082 )

**Comment by jsnmoon** [comment]
We could also conceptualize the component as a "legend" for a "heatmap table" 🙂

**Comment by dognose24** [comment]
> as a "legend" for a "heatmap table"

Could you tell me how you're reading my mind? I just need help with the naming! 😄

**Comment by jsnmoon** [comment]
> Could you tell me how you're reading my mind? I just need help with the naming! 😄

It's a secret power that comes with leading a team! 😉
