### ISSUE TITLE
Show Blank Canvas 3 theme card in the Theme Showcase

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#71911]
# Description

Currently the BC3 theme, [blank-canvas-3](https://github.com/Automattic/themes/tree/trunk/blank-canvas-3) that is used in the Assembler flow is hidden in the showcase because of waiting to tie up loose ends and make decisions as discussed in these slack convos: 
p1672961362021169/1672759241.582349-slack-C029FM1EH
p1673410564512999/1673409133.031799-slack-CRWCHQGUB

In theory, we'd like to display the BC3 as a typical theme card in the showcase, so the user can choose it without the Assembler flow.  However, as @arthur791004 has pointed out, this theme does not have a `home.html` template. It has only index, page and single.   Thus the homepage for the BC3 (without PA flow) will be index.html and by default it will display a list of posts. See https://developer.wordpress.org/themes/basics/template-hierarchy/#home-page-display
![Image](https://user-images.githubusercontent.com/5665959/211719745-509e97ff-7d61-4a94-952e-8d18f92ec17e.png)

See [discussion](p1666130037340589/1666090149.152199-slack-CRWCHQGUB) with Matias on why BC3 does not have a `home.html` template.

This poses a problem in the "marketing" of this theme as a "blank canvas" because if a user selects this theme from the showcase (without Assembler flow) then when they go to edit their homepage in the editor they will see the `index.html` with post content - it will not look "blank". 

Here is a view of what my test site looks like when I pick BC3 from the showcase:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/5665959/211720029-8839811e-14aa-477a-8998-81f93eea40ac.png">

# Tasks & Acceptance criteria

- [x] Resolve concerns about BC3 not having a `home.html` 
- [x] Remove code that hides BC3
- [x] Show BC3 in LiTS
- [x] Hide BC3 in LoTS
- [x] Notify Carolyn Sonnek @csonnek  when this is shipped to users: p1673530827345509/1672759241.582349-slack-C029FM1EH
- [x] Heads up post in wpcom happy - good to over-communicate about this and make sure HE is clear on the difference between BC-3 as a theme and the BC-Site Assembler

## Possible followup
- [ ] Update theme detail page (maybe)
- [ ] At some point we will expose BC in LoTS, but it will be wired up with the Assembler flow and we are not yet ready to act on that. 

@Automattic/lego

**Comment by autumnfjeld** [comment]
From Ian p1673445049401509/1673409133.031799-slack-CRWCHQGUB:

> My initial thoughts are that we should probably have one of these options:
- We should have a Blank Canvas 4 that has an empty home template in it, just like the previous one. And switch to using that in PA Flow so that you could have a theme you could switch back and forth from after signing up.
- We should rename Blank Canvas 3 to something else and just give up on it being “Blank” in the showcase. It’s Blank in our flow. Which is what matters most. Let’s say it was called, “Natural” or something like that. We could then also have the previous Blank Canvas unretired if we wanted.


Currently discussing the best way to move forward: p1673582075935699/1673409133.031799-slack-CRWCHQGUB

**Comment by autumnfjeld** [comment]
Arthur's idea: we could programatically set up a home.html for the user when the select the BC card.

**Comment by miksansegundo** [comment]
I like this solution to keep BC3 hidden and create a new BC4.

> We should have a Blank Canvas 4 that has an empty home template in it, just like the previous one. And switch to using that in PA Flow so that you could have a theme you could switch back and forth from after signing up.

I think we can close this issue and create a new one to `Create a new BC4 theme with an empty home and show it on the showcase`.

**Comment by autumnfjeld** [comment]
https://github.com/Automattic/dotcom-forge/issues/1578

**Comment by autumnfjeld** [comment]
We will move forward with this issue pbxlJb-3pL-p2#comment-2312

**Comment by autumnfjeld** [comment]
See D97579-code

**Comment by autumnfjeld** [comment]
Slack conversation with launch confirmation: p1676013695213049/1675743668.239919-slack-C048CUFRGFQ

**Comment by arthur791004** [comment]
Close it via D97579-code
