### ISSUE TITLE
WooExpress: Update the flow styles to be consistent and aligned with the design.

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#72095]
This is a general task to track updating the WooExpress flow styles. More details to come.

Design details: p1673364315302559-slack-C03Q87XT1QF

Tasks
- [x] Use WooCommerce fonts and colors (see Figma for specifics) (#72166).
- [x] Use WooCommerce logo in the stepper header (instead of WordPress) (#72167).
- [x] Update processing screen messages (see Installation -> Loaders in Figma) (#72168).
- [x] Make loaders consistent. We currently have a mix of the loading ellipses and the blue progress bar. Switch everything to using a purple progress bar. (#72169)
- [x] Step background images (these may be the same as tailored ecommerce) (#72170).
