### ISSUE TITLE
LaunchPad in General Onboarding Tracking Issue

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#72459]
### Details

Tracking issue for implementing Launchpad in general onboarding

### Up Next:
- [ ] https://github.com/Automattic/wp-calypso/issues/72887 (🔴 high)
- [x] https://github.com/Automattic/wp-calypso/issues/72572 (🟡 low)

### In Progress
- [x] https://github.com/Automattic/wp-calypso/issues/72870 (🟠 medium)

### Backlog:
- [x] https://github.com/Automattic/wp-calypso/issues/72480

### Complete
- [x] (spike) https://github.com/Automattic/wp-calypso/issues/70825
- [x] https://github.com/Automattic/wp-calypso/issues/72479
- [x] https://github.com/Automattic/wp-calypso/issues/72477
- [x] https://github.com/Automattic/wp-calypso/issues/72569
- [x] https://github.com/Automattic/wp-calypso/issues/72570
- [x] https://github.com/Automattic/wp-calypso/issues/72571
- [x] https://github.com/Automattic/wp-calypso/issues/72872 (🔴 high)
- [x] https://github.com/Automattic/wp-calypso/issues/72885 (🟠  medium)
- [ ] 

### Future ideas
- [ ] https://github.com/Automattic/wp-calypso/issues/72478

### Resources
Resources
- Initial Discussions about Launchpad in Onboarding p1667518943518509-slack-CHN6J22MP
- Discussions about possible task lists paYE8P-2dY-p2
- Notes on General Onboarding – Problems and Thoughts paYE8P-2op-p2

**Comment by Addison-Stavlo** [comment]
closing this as we no longer use it and the last issue is tracked on our board and being resolved.
