### ISSUE TITLE
Site Editor Quick Start Videos: update videos and copy

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#72542]
# Description

 
See
* mini PT: Video Screen for Pattern Assembler] pbxlJb-2TD-p2
*  PT:Update Site Editor Videos pdOQHC-lv-p2

BEFORE (CURRENT):

![Image](https://user-images.githubusercontent.com/5665959/214477367-84cda830-8db8-4f86-85b0-c1eee911674d.png)

AFTER:
These videos: pdOQHC-lv-p2#comment-371
This [copy](https://videomotionp2.wordpress.com/2022/12/14/project-thread-update-site-editor-videos/#comment-393):

> Building with WordPress blocks
> Learn the fundamentals of the literal building blocks of a WordPress site.
> 
> Building with WordPress patterns
> Quickly design and build a webpage using block patterns.
> 
> Navigation with the List View
> Learn to navigate and edit your design like a pro with the list view.
> 
> Add Style to your WordPress site
> Learn about design tools to control fonts, colors, and spacing.
> 

# Tasks
- [x] Update copy
- [x] Update videos, add them to wp media
- [x] Update tracks events
- [x] Share in a comment here when finished & tag Scott Wiley & Mike Bal

# Testing
* Go to My Home
* Click on the Design like an expert card (see below)
* Check that 
  * videos in correct order
  * copy is correct
  * videos play as expected
  * all tracks event fire

# Related
* https://github.com/orgs/Automattic/projects/338/views/1?filterQuery=video

**Comment by autumnfjeld** [comment]
For Tadahiro

**Comment by MohitBansal321** [comment]
this link shows 404
https://github.com/orgs/Automattic/projects/338/views/1?filterQuery=video

**Comment by autumnfjeld** [comment]
@miksansegundo  & @okmttdhr  this might be a good issue  for Tadahiro to take.

**Comment by MohitBansal321** [comment]
@autumnfjeld this testing is on website or after download the application

**Comment by MohitBansal321** [comment]
![Screenshot 2023-02-12 160353](https://user-images.githubusercontent.com/78220157/218305912-bda048d5-57eb-42b7-b158-4822c43cbb6d.png)
let me know are you asking for this?
@miksansegundo @okmttdhr  @autumnfjeld

**Comment by okmttdhr** [comment]
Hello @that-mike-bal @swilleya8c @autumnfjeld!
I finished updating the copy and videos!

You can directly see the change in `/home/<your-site>?courseSlug=site-editor-quick-start`, or `Go to My Home` ->
`Click "Start learning" on the "Design like an expert" card`! Let me know if you have some findings.

**Comment by autumnfjeld** [comment]
We can close this issue now @okmttdhr. :). Thank you!

See the following P2s for testing and closure:
pbxlJb-3Am-p2
pdOQHC-lv-p2#comment-547

**Comment by autumnfjeld** [comment]
> let me know are you asking for this?

@MohitBansal321 sorry for the late reply.  Yes you have that right.  Our team was saving this issue for our new dev, but appreciate your interest here.  ;)
