### ISSUE TITLE
Update the theme activation flows

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#72703]
- Create a diagram with the related flows - https://miro.com/app/board/uXjVPsA5uiI=/
- Implement what is missing

Related P2 paYJgx-2Rv-p2#comment-3102

**Comment by cpapazoglou** [comment]
This seems one issue it should get resolved after consolidating the flows

https://github.com/Automattic/wp-calypso/issues/70759

**Comment by WBerredo** [comment]
Diagram with flows created - https://miro.com/app/board/uXjVPsA5uiI=/

**Comment by cpapazoglou** [comment]
Here is a P2 with a universal thank you page p9Jlb4-6ic-p2

**Comment by epeicher** [comment]
Draft PR created with a PoC for the WP.org installation flow https://github.com/Automattic/wp-calypso/pull/73028

**Comment by cpapazoglou** [comment]
Let's note down the flows that we are going to refactor and resolve them one by one.

**Comment by epeicher** [comment]
### Identifying the Theme Flows


#### Free

It requires to be refactored, so the Thank You page is displayed.

#### Premium 

It requires to be refactored, so the Thank You page is displayed.

#### WooCommerce

It requires to be refactored, so the Thank You page is displayed.

#### dotOrg

They require some changes in the backend as well as the front end. The following draft PR implements the flow when navigating to 

`/marketplace/:productSlug/install/:siteId`

- https://github.com/Automattic/wp-calypso/pull/73028

But the backend expects to install a plugin, and [the following error](fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qfvgrf%2Qnhgbzngrq%2Qgenafsref%2Qvavgvngr%2Qraqcbvagf.cuc%3Se%3Q58pn6qs9%26zb%3Q4338%26sv%3Q140%23140-og) is returned.

The current implementation is that [the themes call](https://github.com/Automattic/wp-calypso/blob/8684950efbabd1985ffafb9fe1dc471096b94fe0/client/state/themes/actions/install-and-activate-theme.js#L26)

`/sites/${ siteId }/themes/${ themeId }/install`

#### Marketplace

It requires to be refactored, so the Thank You page is displayed.

**Comment by epeicher** [comment]
For reference and examples for testing, these are examples of the different Themes:

|Theme type|Example|
|---|---|
|Free|Twenty Twenty-Three|
| Premium | Varese |
| WooCommerce | Zaino |
| .org | Darcie,  Astra|
| Marketplace | Makoney|

**Comment by epeicher** [comment]
The following tasks have been created: 
- [x] https://github.com/Automattic/wp-calypso/issues/73834
- [x] https://github.com/Automattic/wp-calypso/issues/73835
- [x] https://github.com/Automattic/wp-calypso/issues/73836
- [x] https://github.com/Automattic/wp-calypso/issues/73837
- [x] https://github.com/Automattic/wp-calypso/issues/73838

**Comment by ebinnion** [comment]
WooCommerce flow should be the only thing left to ship. Might've just shipped. Will followup async.

**Comment by epeicher** [comment]
With the deployment of https://github.com/Automattic/wp-calypso/pull/76544, all the flows are shipped 🚀
