### ISSUE TITLE
Notification Illustrations

### ISSUE THREAD

**Issue by garretsteider** [Automattic/wp-calypso#72739]
Redesign Illustrations in the Wordpress notification side bar

Primary Designer: Garret Steider
Support Designer:

**Comment by garretsteider** [comment]
**Milestones**

- [x] V1 internal check in with Brand team - Jan 27
- [ ] V1 P2 post to gather feedback - Feb 10 - Feb 18
- [ ] V2 Internal Check in with brand team of finalized direction and feedback - March 3
- [ ] V2 P2 post - March 17
