### ISSUE TITLE
Phone Input: Build a better phone number input

### ISSUE THREAD

**Issue by umurkontaci** [Automattic/wp-calypso#7453]
See #2535. 

This issue tracks the progress of building the new phone-input. As the number of validation has been increased and become more strict, we are seeing a super increased amount of errors the users see during registration. 
- [x] Create a library for parsing / formatting numbers (PR: #7454)
- [x] Create a module that utilizes GeoIP to guess the user's location (Issue: #7455, PR: #7457)
- [x] Create a React component that utilizes the libraries above (PR: #7456, #10312)
- [x] Deploy with A/B test in Domain Contact Form to measure impact and capture errors (Issue: #10369, PR: #10313, #10447)
- [x] Deploy to all users in Domain Contact Form (PR: #11249)
- [ ] Retire old `form-phone-input` and replace all usages of `form-phone-input` with the new component. (Issue: #2535)

/cc: @klimeryk @aidvu @wensco @Automattic/sdev-feed

**Comment by klimeryk** [comment]
The last part, `Retire old form-phone-input and replace all usages of form-phone-input with the new component` , is being tracked in https://github.com/Automattic/wp-calypso/issues/15538, so there's no need to keep this issue open anymore.
