### ISSUE TITLE
Assembler: discuss approaches from improving for the text list of section patterns, not using category names

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#74869]
# Description
🚧 THIS IS CURRENTLY UNDER DISCUSSION.  [pbxlJb-3EX-p2#comment-2453](https://href.li/?https://wp.me/pbxlJb-3EX#comment-2453)NEEDS DESIGN RESOLUTION. Perhaps different ideas.

This is not required for the Categories CfT, but it should be a priority for soon after. 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/5665959/227428274-356e3fe9-8740-4b62-bfb9-de4852c278d5.png">

One solution to the "pattern name problem": don't show the name or category at all! Instead show a list thumbnail images.

| ### **BEFORE** | **AFTER**  |
| --- | --- |
|  <img width="351" alt="image" src="https://user-images.githubusercontent.com/5665959/227427409-7c6f2066-15b2-48bd-8d94-a0790f421621.png"> |  <img width="332" alt="image" src="https://user-images.githubusercontent.com/5665959/227427664-21a75971-c905-4571-9175-c9d69d0d05df.png">
 |

See how Editor has tooltip with pattern name
<img width="163" alt="image" src="https://user-images.githubusercontent.com/5665959/227431127-71e54cbc-0b5c-46f1-90d9-659586d7d348.png">

COPY NOTE:
* We are changing from "Add patterns" to "Insert patterns"

# Tasks / Acceptance Criteria
- [ ] User will see a thumbnail list instead of 
- [ ] User can access "Insert patterns" button at all times, it should remain at the top, so it is always viewable
- [ ] Save button should remain visible, on top of list (like in other Assembler sidenavs)
- [x] Update the snackbar to show pattern names https://github.com/Automattic/wp-calypso/pull/74813#top
- [ ] Edit controls should be on top of the thumbnails: probably they should only show on hover.  Open to discuss what is best.
- [ ] Nice to have: on hover the [pattern name appears in a tooltip](https://user-images.githubusercontent.com/5665959/227431127-71e54cbc-0b5c-46f1-90d9-659586d7d348.png)
- [ ]  Anything else @davewhitley 

@Automattic/lego

**Comment by arthur791004** [comment]
> ![image](https://user-images.githubusercontent.com/13596067/227432714-d92d8afe-0124-4c1c-b796-dc35ea31b39d.png)

After thinking about this again, I feel the thumbnail list is a bit duplicated with the large preview 😂

IMHO I'd still prefer to get rid of the list view or have a toggle to display the list view.

**Comment by autumnfjeld** [comment]
@arthur791004 

> After thinking about this again, I feel the thumbnail list is a bit duplicated with the large preview 😂
@davewhitley  has the same concerns pbxlJb-3EX-p2#comment-2453


> IMHO I'd still prefer to get rid of the list view or have a toggle to display the list view.
We can keep exploring ideas.   Or revisit the ideas of a toggle view that is in the main sidebar, as @taipeicoder proposed pbxlJb-3BK-p2#comment-2424



![Image](https://user-images.githubusercontent.com/5665959/228117419-fc6a29c4-dc07-4700-968c-d6bf5574788a.png)

**Comment by taipeicoder** [comment]
Closing since the section patterns listing has already been removed.
