### ISSUE TITLE
`Story` User can unfollow a site

### ISSUE THREAD

**Issue by phcp** [Automattic/wp-calypso#74981]
## Context

This story is focused on allowing users to easily unfollow a site from their list of subscribed sites. This will require the creation of a dropdown (reusing existing components), a new "Unfollow" button, API updates, and create React Query queries and mutations.
![Image](https://user-images.githubusercontent.com/3113712/228038484-fbb1fd4e-62fb-461f-88f1-ebd92b30fd84.png)

## Tasks

- [x] https://github.com/Automattic/wp-calypso/issues/74973
- [x] https://github.com/Automattic/wp-calypso/issues/74987
- [x] https://github.com/Automattic/wp-calypso/issues/74988
- [x] https://github.com/Automattic/wp-calypso/issues/74964
- [x] https://github.com/Automattic/wp-calypso/issues/74965
- [x] Mobile view
- [ ] Accessibility support
- [ ] Automated tests

**Comment by phcp** [comment]
Closing the story as we agreed it doesn't fit with the GH board format.
