### ISSUE TITLE
[Tracking] Subtracting cats: vfification of link-in-bio

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#75289]
See pekYwv-FK-p2#comment-802 for non-code tasks, background etc

- [x] Move to the starter-designs endpoint rather than the custom one it currently uses. #75831
- [x] Make previews work with the [same mechanism as vThemes](https://github.com/Automattic/dotcom-forge/issues/1773) rather than the lynxdemo site. Should be careful to retain the same site title's etc as now. https://github.com/Automattic/wp-calypso/pull/75782
- [x] Ensure selecting a design will result in a site with BC3 and a homepage template containing a pattern, not a page containingg a pattern displayed by the blank template. https://github.com/Automattic/wp-calypso/pull/75831
