### ISSUE TITLE
☂️  Update theme cards in Theme Showcase/Onboarding Design Picker to use the same component

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#75457]
This issue covers the effort of creating a new component for theme cards, that's reusable for both the Theme Showcase and the Onboarding Design Picker. The goal of this task is to achieve more consistency in the theme listing experience in both pages.

| Theme Showcase | Onboarding Design Picker |
| --- | --- |
| ![Screenshot 2023-04-10 at 12 14 06 PM](https://user-images.githubusercontent.com/797888/230824581-6dbda163-afa6-4e01-a7b1-43a73793d58d.png) | ![Screenshot 2023-04-10 at 12 14 15 PM](https://user-images.githubusercontent.com/797888/230824598-1e18407f-0494-4fc6-b31b-27ed1208bacb.png) |

## Dev tasks

- [x] Create new component for theme cards.
  - https://github.com/Automattic/wp-calypso/pull/75422
- [x] Update the Theme Showcase to use the new component
  - https://github.com/Automattic/wp-calypso/pull/75422
- [x] Clean up related unused code in the Theme Showcase.
  - https://github.com/Automattic/wp-calypso/pull/75519
- [x] Update the Onboarding Design Picker to use the new component
  - https://github.com/Automattic/wp-calypso/pull/75616
- [x] Clean up related unused code in the Onboarding Design Picker.
  - https://github.com/Automattic/wp-calypso/pull/75754

**Comment by taipeicoder** [comment]
Closing as the dev tasks are completed.
