### ISSUE TITLE
Tracking Task: Moving Launchpad Logic to Backend

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#75504]
## Goal

Refactor the launchpad checklist API and migrate checklist definitions into backend. Launchpad should now fetch checklists via backend endpoint, rather than have those hard coded in calypso. This will make retrieving checklist info platform agnostic.

## All Remaining Work
- [x] https://github.com/Automattic/wp-calypso/pull/76644

**Deleting unused code**
- [x] Dependency: Once https://github.com/Automattic/wp-calypso/issues/76058 is done and **deployed to atomic**
- [x] Dependency: Also before deleting these, we should double check old launchpad methods aren't being used anywhere.
  - [x] https://github.com/Automattic/wp-calypso/issues/76473
  - [x] https://github.com/Automattic/wp-calypso/issues/76059
- [ ] Dependency: Once the **Frontend Batch** above is updated to use data-stores/useLaunchpad 
  - [ ] https://github.com/Automattic/wp-calypso/issues/76364
  - [ ] https://github.com/Automattic/wp-calypso/issues/76368
  - [x] https://github.com/Automattic/wp-calypso/issues/76597

**Misc follow ups**
- [ ] https://github.com/Automattic/wp-calypso/issues/76060
- [x] Remove unnecessary `require` of the launchpad feature in the jetpack-mu-wpcom checklist API endpoint ( it's already being `required` in the index https://github.com/Automattic/jetpack/pull/30856
- [x] Ensure that in the main launchpad endpoint, the defintion and validation of possible args is generated from the checklist registry rather than manually. See https://github.com/Automattic/jetpack/pull/30227#discussion_r1179291097
- [x] https://github.com/Automattic/wp-calypso/issues/76056
- [ ] Figure out how to get the _doing_it_wrong checklist registry error to display in the error log (see https://github.com/Automattic/jetpack/pull/30211#discussion_r1173998786) 
- [ ] https://github.com/Automattic/jetpack/pull/30369
 
## Completed Since First Milestone
- [x] https://github.com/Automattic/wp-calypso/issues/76057
- [x] https://github.com/Automattic/wp-calypso/issues/75846
- [x] https://github.com/Automattic/jetpack/pull/30211
- [x] https://github.com/Automattic/wp-calypso/pull/76164
- [x] https://github.com/Automattic/wp-calypso/pull/76154
- [x] https://github.com/Automattic/wp-calypso/pull/76510
- [x] https://github.com/Automattic/wp-calypso/issues/76058
  - https://github.com/Automattic/jetpack/pull/30397
- [x] Need to ensure we are getting correct value for domain_upsell, whether from frontend or backend, after the logic for this was emergency bypassed on the backend. See https://github.com/Automattic/jetpack/pull/30361/ and p1682690156146969/1682634536.650749-slack-C0299DMPG for context.
  - https://github.com/Automattic/jetpack/pull/30397
- [x] Once we have updated Launchpad to fully use the backend checklist definitions, we should review launchpad/tasks.tsx and task-helpers.tsx to ensure any unneeded code is removed from those files. 
   - https://github.com/Automattic/wp-calypso/pull/76467
- [x] https://github.com/Automattic/wp-calypso/issues/76476
  - https://github.com/Automattic/wp-calypso/pull/76510
- [x] https://github.com/Automattic/wp-calypso/issues/76472
    - https://github.com/Automattic/wp-calypso/pull/76514
- [x] https://github.com/Automattic/wp-calypso/issues/76470
  - https://github.com/Automattic/wp-calypso/pull/76541
- [x] Once we have updated Launchpad to fully use the backend checklist definitions, we should review launchpad/tasks.tsx and task-helpers.tsx to ensure any unneeded code is removed from those files.
    - https://github.com/Automattic/wp-calypso/pull/76599
    - https://github.com/Automattic/wp-calypso/pull/76560
- [x] https://github.com/Automattic/wp-calypso/issues/76471
  - https://github.com/Automattic/wp-calypso/pull/76543
- [x] https://github.com/Automattic/wp-calypso/issues/76469
  - https://github.com/Automattic/wp-calypso/pull/76549 ( Approved )
- [x] https://github.com/Automattic/wp-calypso/issues/76363 
  - https://github.com/Automattic/wp-calypso/pull/76506 ( Approved )
- [x] https://github.com/Automattic/wp-calypso/issues/76362
  - https://github.com/Automattic/wp-calypso/pull/76596 ( Approved )
- [x] https://github.com/Automattic/wp-calypso/issues/76478
      - https://github.com/Automattic/wp-calypso/pull/76467 ( Approved )
     
## First Milestone (DONE)
Define task definitions on backend, use them in help center icon.
- [x] https://github.com/Automattic/jetpack/pull/30023
   - Setup scaffolding for new backend file and endpoint
   - D107596-code
   - https://github.com/Automattic/jetpack/pull/30044
   - https://github.com/Automattic/jetpack/pull/30069
   - https://github.com/Automattic/jetpack/pull/30112
   - https://github.com/Automattic/wp-calypso/pull/76052
- [x] https://github.com/Automattic/jetpack/issues/30041
   - Add detailed completion / enabled logic for general tasks
   - 'plan_selected', 'first_post_published', 'design_selected', 'design_edited', 'site_launched'
   - https://github.com/Automattic/jetpack/pull/30116
   - https://github.com/Automattic/jetpack/pull/30117
- [x] https://github.com/Automattic/jetpack/issues/30038
   - Add detailed completion / enabled logic for newsletter tasks
   - 'setup_newsletter',  'subscribers_added', 'first_post_published_newsletter', 'newsletter_plan_created' 
   - https://github.com/Automattic/jetpack/pull/30078
- [x] https://github.com/Automattic/jetpack/issues/30039
   - Add detailed completion / enabled logic for link-in-bio tasks
   - 'setup_link_in_bio', 'links_added', 'link_in_bio_launched'
   - https://github.com/Automattic/jetpack/pull/30076
- [x] https://github.com/Automattic/jetpack/issues/30040
   - Add detailed completion / enabled logic for videopress tasks
   - 'videopress_setup', 'videopress_upload', 'videopress_launched'
   - https://github.com/Automattic/jetpack/pull/30141
- [x] https://github.com/Automattic/jetpack/issues/30042
   - Add detailed completion / enabled logic for other misc tasks 
   - Don't think these need anything, but check: 'setup_free', 'setup_general', 'setup_write'
   - Others; 'domain_upsell', 'verify_email'
   - https://github.com/Automattic/jetpack/pull/30146
- [x] https://github.com/Automattic/wp-calypso/issues/75587
   - [x] https://github.com/Automattic/wp-calypso/pull/75575#pullrequestreview-1380274462
   - [x] https://github.com/Automattic/wp-calypso/pull/75933
   - [x] https://github.com/Automattic/wp-calypso/pull/75987

**Comment by jeyip** [comment]
**Note:**

After more discussion with @edanzer and @mattwiebe, the verify email task completion status will be left to be defined in the client for the time being. Apparently, the necessary information isn't available on Atomic sites, and it would take about two weeks of drafting a PR, exposing an endpoint, discussion with Jetpack folks, waiting on the next JP release cycle, incorporating the changes into our refactor, and then waiting on the subsequent `jetpack-mu-wpcom` release to get things done.

We have the rest of the task definitions and their completion statuses migrated to the backend, and are still able to leverage most of the benefits of the refactor without committing to the extra complication of migrating the `verify_email` task 

cc @Addison-Stavlo

**Comment by jeyip** [comment]
**Note:**

@edanzer Below is Matt's suggestion about how we can tackle the third milestone in a safe way

> Once we want to centralize things in our plugin and unload the existing logic on wpcom, we'll first move this line in jetpack-mu-wpcom to an earlier priority.
> 
> ```
> add_action( 'plugins_loaded', array( __CLASS__, 'load_launchpad' ), 9 );
> ```
> 
> This will get us in just before the default priority `10`, and tidily allow us unhook what's currently running on wpcom and Launchpad inside the `load_launchpad` method below.
> 
> ```
> if ( class_exists( 'WPCOM_Launchpad' ) {
>   remove_action( 'plugins_loaded', array( WPCOM_Launchpad::get_instance(), 'init' ) );
> }
> ```
> 
> Once that's running, we can remove `WPCOM_Launchpad` from the Simple and `wpcomsh` codebases safely. (Although first we'll have to audit to ensure nothing else is calling `WPCOM_Launchpad`)



https://github.com/Automattic/jetpack/pull/30211#discussion_r1173990182
