### ISSUE TITLE
Assembler:  create a "wait list" system with meta tag for patterns that need fixes

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#75944]
# Description

@alaczek has vetted the 293 dotcom patterns in [Async Walkthrough – Site Assembler with All Dotcom Patterns] pekYwv-15Q-p2 thus we are in final steps of shipping All Patterns in the Assembler.  Also see slack convo p1681886698322349-slack-C048CUFRGFQ

We don't need a CfT, the vetting & testing done in pekYwv-15Q-p2 is sufficient.

# Miguel & Ola tasks
- [x] Create the “Wait list” of patterns that we should not release in the Assembler until their issues are fixed (the list is pretty much done based on discussion in the [comments](pekYwv-15Q-p2#comment-827))
- [x] set up a meta tag in the patterns that need fixing
- [x] Create the conditional filtering in the code so that the wait list patterns do not show in the assembler.  From @miksansegundo :  Filter the patterns in the front end. We can do this because we receive the patterns with their meta tags.
- [x] show waitlisted patterns in Development and Horizon environments for testing 
- [ ] Ship the All Patterns in Assembler  feature. I guess we'll have to call "Almost All Patterns"🤣

# Related 
* [Site Assembler - Featured patterns review and update](https://github.com/Automattic/wp-calypso/issues/75864)
