### ISSUE TITLE
Subscription Management: Pre-launch tasks (Individual subscription settings page)

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/wp-calypso#77173]
### Details

The goal of this PR issue is to list smaller tasks/bugs that need to be addressed. All items below are related to the _Individual Site Subscription_ page and need further exploration and clarification. Each item can be converted into its own GH task.

### Checklist

**High priority:**
- [x] API isn't returning correct value for `send_comments` setting (context: https://github.com/Automattic/wp-calypso/pull/77148#pullrequestreview-1433989293)
  - https://github.com/Automattic/wp-calypso/issues/77246 → Fixed in D111587-code
- [x] resubscribing doesn't work for logged-in users - we will need to use different endpoint. 
  - https://github.com/Automattic/wp-calypso/issues/77241
- [x] create email template link redirects (initial investigation: p1684163332495579-slack-C02TCEHP3HA)
  - https://github.com/Automattic/wp-calypso/issues/77248

**Medium priority**
- [x] add optimistic update for unsubscribe and subscribe actions; please keep in mind that the site title, site icon and count need to be stored somewhere (e.g. in state) when the user unsubscribes.
  - https://github.com/Automattic/wp-calypso/issues/77093 → Addressed in: https://github.com/Automattic/wp-calypso/pull/77264
- [x] fix error handling when the user requests details about non-existent site / site they are not subscribed to; this is the current output (https://github.com/Automattic/wp-calypso/pull/77148#pullrequestreview-1433989293) → Addressed in https://github.com/Automattic/wp-calypso/issues/77305
- [x] when you unsubscribe, the API should not return any data (context: p1684490224815849/1684480794.314739-slack-C02TCEHP3HA) → Fixed in D111587-code

**Low priority**
- [x] consider caching DB query (D111349#2222241-code)
- [ ] fix "Cancel subscription" button styling → Will be addressed later (as a part of maintenance): https://github.com/Automattic/wp-calypso/issues/77394

### Related

Related discussion: p1684507008002259/1684480794.314739-slack-C02TCEHP3HA

**Comment by ivan-ottinger** [comment]
I have carried over the "fix "Cancel subscription" button styling" task into its own GH issue: https://github.com/Automattic/wp-calypso/issues/77394 and added it to one of our maintenance milestones.

**Comment by yansern** [comment]
Closing this issue and https://github.com/Automattic/wp-calypso/issues/77394 can live on its own.
