### ISSUE TITLE
Launchpad: Move the completion check logic out of the task list availability status

### ISSUE THREAD

**Issue by valterlorran** [Automattic/wp-calypso#77494]
Currently, the logic that checks if the task list is enabled is tied with the completion logic, which means that a task list with the completed status will make the is_enabled flag false. We need to decouple this logic to give more flexibility to Launchpad in other contexts.

- [x] Add a new callback called `is_completed_callaback` to the task list definition.
- [x] Add a new `required_task_ids` attribute to the task list definition.
- [x] Add a general-purpose function that we can use as the default completion callback.
  - [x] Identify any required tasks for the task list
  - [x] If any required tasks exist, the task list is complete if all required tasks are complete
  - [x] If no required tasks exist, we may want to look at tasks flagged with `isLaunchTask` as a secondary check for backwards-compatibility, and have completion be defined by whether all of those tasks are complete
  - [x] If no required tasks and no launch tasks exist, we can check whether all tasks are complete – if they are, then we mark the task list as complete
  - [x] If no required tasks and no launch tasks exist, and we have one or more incomplete tasks, then we can check if the last task was completed, and use that as the deciding factor
    - [x] We may want to have this be controlled by a flag rather than being a default for new task lists, as this would be confusing for task lists where the steps may not be sequential.
    - [x] In general, I think we likely want to keep the task list marked as incomplete by default, as most task list use cases are going to be non-blocking and more focused on user guidance and next steps rather than pushing people to a super-specific goal like site launch.

More context: paYKcK-30Q-p2#comment-2193
