### ISSUE TITLE
Colors and Fonts in the Onboarding Theme Previews

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#78419]
### PT

Referring to pbxlJb-3Ze-p2, we want to surface Colors & Fonts in the Onboarding Design Preview for the designs without the style variations to allow users to change Colors & Fonts when previewing the design. In this first iteration, we will deliver this experience only to themes without global style variations.

With our experience with the Site Assembler, we anticipate that colors might not play well with some theme patterns. In that scenario, we will ship the first iteration with fonts only.

### Designs

pbxlJb-40F-p2

| Desktop | Mobile |
| - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/748b68e4-0dc3-4c8e-9d99-f7a8bf267dcc) | ![image](https://github.com/Automattic/wp-calypso/assets/13596067/767d8b6f-e4c3-4d9e-9e42-7dc91de1df22) |

### Tasks

- [x] Surface Colors in the Onboarding Design Preview
- [x] Surface Fonts in the Onboarding Design Preview
- [x] Display both Colors & Fonts with Navigation
- [x] The copy on the Upsell Modal
- [x] Mobile layout
- [x] Mobile layout with the fullscreen animation
- [x] Disable Colors & Fonts for themes that don't play well with them
- [x] a11y
- [x] Metrics
- [x] Ship
  - [x] https://github.com/Automattic/wp-calypso/pull/79727
- [x] Issues
  - [x] [Disco has a flash of yellow background](https://github.com/Automattic/wp-calypso/pull/78313#pullrequestreview-1500380658)
  - [x] [Spearhead Blocks has some fonts that don't seem to change](https://github.com/Automattic/wp-calypso/pull/78313#pullrequestreview-1500380658)
    - Missing the font CSS
    - D115913-code
  - [x] The name of the free font of the Otis theme doesn't display correctly
    - p1689301362083989-slack-CRWCHQGUB
    - D116160-code

### PRs

- [x] https://github.com/Automattic/wp-calypso/pull/78313
- [x] https://github.com/Automattic/wp-calypso/pull/78380
- [x] https://github.com/Automattic/wp-calypso/pull/78774
- [x] https://github.com/Automattic/wp-calypso/pull/78934
- [x] https://github.com/Automattic/wp-calypso/pull/78978
- [x] https://github.com/Automattic/wp-calypso/pull/78979
- [x] https://github.com/Automattic/wp-calypso/pull/79062
- [x] https://github.com/Automattic/wp-calypso/pull/79124
- [x] https://github.com/Automattic/wp-calypso/pull/79166
- [x] https://github.com/Automattic/wp-calypso/pull/79166
- [x] https://github.com/Automattic/wp-calypso/pull/79340
- [x] D115913-code
- [ ] https://github.com/Automattic/wp-calypso/pull/79284
- [x] D115904-code
- [x] D116064-code
- [x] D116065-code
- [x] D116160-code
- [x] https://github.com/Automattic/wp-calypso/pull/79540
- [x] https://github.com/Automattic/wp-calypso/pull/79727
- [ ] TBD

**Comment by miksansegundo** [comment]
I missed that the layout changes for fonts done in https://github.com/Automattic/wp-calypso/pull/78734 affect this issue, the UI on mobile will need CSS adjustments.

How do you think we should address this? I can use your PR #78774 as the base for another PR to fix it. cc: @taipeicoder 

**Mobile**

<img width="935" alt="Screenshot 2566-06-30 at 11 21 25" src="https://github.com/Automattic/wp-calypso/assets/1881481/6bfefe31-6d70-4aca-b0cf-93afedea64cd">

**Desktop**

<img width="1090" alt="Screenshot 2566-06-30 at 11 21 07" src="https://github.com/Automattic/wp-calypso/assets/1881481/bee23d53-71d8-4d8c-b849-903338a55c6c">

**Comment by arthur791004** [comment]
I don't think it's an issue for now as this feature is still under the feature flag, and users won't see them.

**Comment by taipeicoder** [comment]
As @arthur791004 said, we haven't started working on the mobile view yet. Thanks for checking the UI there as well @miksansegundo

**Comment by arthur791004** [comment]
Closing it since everything is done 🎉
