### ISSUE TITLE
Fastrack Next Assembler Tasks Jun 2023

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#78513]
# Descrption

I'd like to fast track these tasks, perhaps have two devs working on these for the next week.  These are easily addressed improvements highlighted recently by Pablo or Kelly.

The tasks below are based on items in 
* [Async Walkthrough – Pattern Assembler on Production & Next Steps] pekYwv-1YD-p2
* Kelly comment pekYwv-1YD-p2#comment-1495
* Pablo & Lucas work in  Non-linear flow 1 & Non-linear flow 2Tv3pYqA3EcRfiXC31IxrXE-fi-723%3A25499.   Non-linear flow 2 is the latest and I have taken some tasks from Non-linear flow 2.   There are also bigger pieces of work that aren't included in this issue. These items we can discuss with Pablo in the walkthrough call.
   * Revamp of GS gating Tv3pYqA3EcRfiXC31IxrXE-fi-723%3A25499
   * Adding celebration after payment

I tried to make exact links to the right area of the Figma, but that doesn't seem to work properly all the time.   Let me know if there are questions or confusion on which part of the Figma to look at.

# Tasks
These  are in order of importance:
- [x] Updates to the blank preview page
  - [x] Remove the icon from the blank preview. [See Figma: Tv3pYqA3EcRfiXC31IxrXE-fi-751%3A31932
  - [x] Change "Welcome to your blank canvas." to "Welcome to your homepage".   ( Lucas suggested other copy, but IMO [ it doesn't sound good.](Tv3pYqA3EcRfiXC31IxrXE-fi-751:31932)  I'll think about it. 

- [x] In the CTA, adjust the copy so that "homepage" is not on its own line. Perhaps "Use our library...." should be on its own line. The image below shows what is wrong & should be fixed.

![Image](https://user-images.githubusercontent.com/5665959/247803314-f885d9e9-4e54-460f-9ad2-6dc09703eab3.png)

- [x] Update this copy, to be the copy shown below.  Figma: Tv3pYqA3EcRfiXC31IxrXE-fi-751%3A31932

![Image](https://user-images.githubusercontent.com/5665959/247803192-004073e4-f883-4adc-b27e-db982048c496.png)

- [x] Update "main button" to be "Save and Continue" [See Figma: Tv3pYqA3EcRfiXC31IxrXE-fi-751%3A31932

- [x] Change copy: Add Patterns -> Add Sections. Figma Tv3pYqA3EcRfiXC31IxrXE-fi-819%3A46329

- [x] New copy: "Find the right patterns for your homepage by exploring the pattern categories below."

![Image](https://user-images.githubusercontent.com/5665959/247806150-93a19941-b94a-48fc-a935-e2b3739b139f.png)

- [x] A few alignment issues that need to be cleaned up in prod to match the design. The vertical spacing is off in this section:
![image](https://github.com/Automattic/wp-calypso/assets/1881481/09d1aa2e-ccdf-4340-b747-e97ed567035a)

- [x] [Remove all widows anywhere in the UI](puPv3-6m9-p2). There’s one in the helper text above the main CTA button. @autumnfjeld  can help with copy tweaks if you need help.

@miksansegundo:  going forward with any Assembler or UI copy, use your good judgement with trailing words like you brought up before.  :)

**Comment by miksansegundo** [comment]
Closed by #78581
