### ISSUE TITLE
Themes: Update the Upsell Modal

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#78694]
Part of https://github.com/Automattic/dotcom-forge/issues/2227

We'll update the upsell flows in the Theme Details screen to improve consistency across different theme types, clarify our plans' features, and reduce users' confusion.

<img width="1139" alt="Screenshot 2023-06-27 at 17 11 53" src="https://github.com/Automattic/wp-calypso/assets/2070010/dc1fe393-f89d-40c7-b3dd-547bb3d914ec">

## Update After paYJgx-3TE-p2

* Separate the plan upgrade and theme activation in different, manual steps.
  * This will also automatically resolve some auto-activation rough edges that we discovered yesterday (paYJgx-3Rd-p2), and have already been agreed upon (p1692804322343539-slack-C02JPCHEKDY) with Bespin.
* If the theme does not require purchases, upon clicking the (primary) Activate action in the Theme Details, we’ll show any relevant warning (more on this later).
* If the theme requires a plan upgrade, we’ll add the plan upgrade modal on the Theme Details page, upon clicking the (primary) Upgrade action.
  * This modal will be based on the mockups I shared a couple of days ago (https://github.com/Automattic/wp-calypso/issues/78694#issuecomment-1688440177).
  * The modal will point to the checkout page.
  * It will NOT include the domain change warning, because the domain change should not happen until theme activation.
  * It will NOT include pricing info; they are available on the checkout page.
  * It will include the target plan’s feature lists. We should reuse existing feature lists from Onboarding ([1](https://github.com/Automattic/wp-calypso/blob/583ad811bb85bd1103ad2f2eaca1f9b53bfc976b/client/components/premium-global-styles-upgrade-modal/index.tsx#L35-L48), [2](https://github.com/Automattic/wp-calypso/blob/583ad811bb85bd1103ad2f2eaca1f9b53bfc976b/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx#L136-L164)).
  * We should reuse most copy from existing similar modals, to avoid having to re-translate everything.
* If the theme requires a subscription, we’ll send the user straight to checkout.
* After checkout, we’ll send the user to the Congrats page, where they can activate the theme.
* If the theme requires a homepage replacement and/or a domain change (for the Atomic transfer), we’ll show either or both warning modals on the Congrats page, upon clicking the (primary) Activate button.
  * The Activate button will perform the Atomic transfer if needed.
  * The Back button sends the user back to the Theme Showcase: Recommended for Simple sites, My Themes for Atomic sites.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/81088
- [ ] https://github.com/Automattic/wp-calypso/issues/81089
- [ ] https://github.com/Automattic/wp-calypso/issues/81090
- [ ] https://github.com/Automattic/wp-calypso/issues/81092
- [ ] https://github.com/Automattic/wp-calypso/issues/81093
- [ ] https://github.com/Automattic/wp-calypso/issues/81095
- [ ] https://github.com/Automattic/wp-calypso/issues/81096
- [ ] Ensure that the plan upgrade and theme activation are separate steps for all cases, and they are always manually triggered by the user.
```

**Comment by BogdanUngureanu** [comment]
**Community**
I think for the community (dotorg) themes, we can reuse the WooCommerce banner with small changes to the copy:
header: Unlock this Community themes
Copy: Upgrade to a Business plan to select this theme and unlock all its features. It's X-amount per year with a 14-day money-back guarantee.

**Partner (Marketplace)**
This one is a bit more complicated because we'll need to inform the user that they need to purchase a plan AND a separate subscription for the theme itself. 

@lucasmendes-design did some research (with some sketches) a few months ago here: pekYwv-1IU-p2#comment-1399

**Comment by lucasmendes-design** [comment]
Hi there, we have different modals here, let's create a standard for us :) 

- When an upgrade is required, we use the modals on the left side. When it's not, we can use the right side ones. 
- I improved the modal for the free sites. 
- The icon/badge/image above the title is optional. 
- Figma link: RcxiuWYjZGkFRdlWL7L02m-fi-673:86934#531144688
<img width="874" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/60e189ff-9dbe-4286-949c-878125777a76">

> Community
I think for the community (dotorg) themes, we can reuse the WooCommerce banner with small changes to the copy:
header: Unlock this Community themes
Copy: Upgrade to a Business plan to select this theme and unlock all its features. It's X-amount per year with a 14-day money-back guarantee.

+1. I think it will work fine.

> Partner 
 
We can get inspiration from this copy here. The CTA could be "Upgrade and subscribe".WDYT? 
<img width="354" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/418ca625-47ae-450c-865f-ccad000f1b24">

<img width="878" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/3e7618ca-4c3f-416f-8863-c14b8d685e33">

**Comment by autumnfjeld** [comment]
Per this conversation, peapX7-2YO-p2#comment-4354,  I was wondering if we should be adding copy somewhere to explain what  "Community themes"  and "Partner themes" are.    We explain what they cost and the plan needed but should we let users know (with more polished copy):  
* A community theme comes from wordpress.org/themes  
* A partner theme is created by a third party theme developer

For me "partner" feels self explanatory, maybe community is too (?).
What do you all think?  This doesn't have to be actioned now, but I did want to bring it up. :)

**Comment by lucasmendes-design** [comment]
Partner may sound self-explanatory but Community is not. One idea is to add the WordPress.org logo above the title and a learn more :) 


<img width="779" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/ae53a0ce-b83d-4e07-b9bb-25aedf27204a">

**Comment by Copons** [comment]
Let me try to make sense of it all!

@lucasmendes-design I've shamelessly stolen all your Figmas and clumsily reassembled them. 🙂 

Some notes, comments, or highlights of some details that might be lost in the confusion.

* We only show the 2-column layout when there is a plan upgrade involved.
* I've reused the features list from existing modals. For the most part, they describe an upgrade from Free. But if the user is on a higher plan, they might already own now of the features listed. In the grand scheme of things, this is fine, IMHO. Otherwise, we need "conditional feature lists", which increases the complexity to infinity.
* AFAICS, upgrading a plan does not also activate a theme. Meaning, the user returns to the Showcase after purchase, selects the theme again, and activates it. For this reason, I've avoided the phrasing "Upgrade and activate" in favour of a simple "Upgrade plan".
  * I have not checked if subscribing to a Partner theme automatically activates the theme. I've left the "Subscribe and activate" CTA, but if this is not the case, I'd say "Subscribe to [theme name]" would be the appropriate CTA.
  * Generally speaking, we should only say "activate" when the theme activation happens in the upcoming flow of actions.
* I've noticed that in some cases, we don't show the "cancel" or "back" secondary button on plan upgrade modals. I've maintained it for consistency, but I don't have a strong opinion about it. FWIW, users can always leave the modal with the "X" button or (IIRC) clicking outside.
* The Premium theme upgrade modal doesn't use the "Upgrade plan" phrasing but "Get Premium for $xx/month". I don't like it, and I can't find where I got the reference modal from in the first place. I'm totally ok with switching the CTA to "Upgrade plan" as all the others.
* If an action triggers the Atomic transfer on a site without custom domain, it is **imperative** that we show the domain warning.
  * If a flow does not involve the Atomic transfer, we should not show the warning (obviously).
* In some cases, we show a homepage replacement warning (see #77881). I'm not exactly sure what the criteria are, but we should only show it if needed. If not needed, we should just activate the theme without further confirmation.
  * We can also integrate the "notice + checkbox controlling the primary button" into other modal types, if needed.


| Theme Type | Current Plan | Modal |
|--------|--------|--------|
| Free _(included with current plan)_<br>without `auto-loading-homepage` | Any | No modal (see #77881). |
| Free _(included with current plan)_<br>with `auto-loading-homepage` | Any | ![Free - Any](https://github.com/Automattic/wp-calypso/assets/2070010/0ebb4779-4ade-4a9d-a387-774f3ed06834) |
| Free with Custom Styles Selected | Free, Personal | ![Free with Custom Styles - Free, Personal](https://github.com/Automattic/wp-calypso/assets/2070010/2c2a84cd-6d7f-422c-976f-e9247d0027a2) |
| Premium | Free, Personal | ![Premium - Free, Personal](https://github.com/Automattic/wp-calypso/assets/2070010/e0939984-f744-4872-9e70-610b650cdb10) |
| Partner | Free, Personal, Premium | ![Partner - Free, Personal, Premium](https://github.com/Automattic/wp-calypso/assets/2070010/b39d2558-06de-4606-9b3f-459efd60ed2e) |
| Partner | Business (Simple) | ![Partner - Business (Simple)](https://github.com/Automattic/wp-calypso/assets/2070010/f0f82bc1-5cdf-4dc2-9507-5d795593188f) |
| Partner | Business (Atomic), Commerce | ![Partner - Business (Atomic)](https://github.com/Automattic/wp-calypso/assets/2070010/d8faa772-a435-44f4-b47c-782067228d68) |
| Community | Free, Personal, Premium | ![Community - Free, Personal, Premium](https://github.com/Automattic/wp-calypso/assets/2070010/6e3e1971-9047-4ca5-af37-9b266c7bce7c) |
| Community | Business (Simple) | ![Community - Business (Simple)](https://github.com/Automattic/wp-calypso/assets/2070010/8023ee5c-14b5-41f9-80e8-6872b5630b82) |
| Community | Business (Atomic), Commerce | ![Community - Business (Atomic)](https://github.com/Automattic/wp-calypso/assets/2070010/a0336932-2911-4497-a223-11d3e36fc817) |
| WooCommerce | Free, Personal, Premium, Business | ![WooCommerce - Free, Personal, Premium](https://github.com/Automattic/wp-calypso/assets/2070010/40d0a0f1-3096-419d-b471-58551bd4dc9d) |
| WooCommerce | Business (Simple) | ![WooCommerce - Business (Simple)](https://github.com/Automattic/wp-calypso/assets/2070010/96dbb23b-ed8f-4321-a9bd-75bdc8f5724f) |
| WooCommerce | Business (Atomic), Commerce | ![WooCommerce - Business (Atomic), Commerce](https://github.com/Automattic/wp-calypso/assets/2070010/89eb4fca-c896-4ee5-a548-de1fc31d04e0) |

**Comment by lucasmendes-design** [comment]
Thanks, Jacopo. I didn't go through all possible combinations. This was very helpful. Let me review "all" flows and put everything together in a P2 post.

> I've avoided the phrasing "Upgrade and activate" in favour of a simple "Upgrade plan".

Agree. 

> I have not checked if subscribing to a Partner theme automatically activates the theme.

I just checked here, and users need to activate it after the purchase. So, in general, we can split this into two steps, as we talked about earlier. 

<img width="970" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/b5bf7aef-1310-4ba7-83e7-08d04953473e">

I found some inconsistencies. For example, if you're enrolled in a free plan and buy a partner theme. We don't warn users about the domain change.

**Comment by lucasmendes-design** [comment]
I think there is a bug in the flow Free -> Buy a Partner theme. It automatically activates. I'm recording everything and put in a P2. So, it's more organized.

**Comment by Copons** [comment]
> I found some inconsistencies. For example, if you're enrolled in a free plan and buy a partner theme. We don't warn users about the domain change.

@lucasmendes-design if you mean in the *current* flow, then yes, I noticed the same problem yesterday when researching all the combos.

---

To report back from our meeting, working on these modals is not really a technical challenge, but it's hard to understand exactly how they work and interact with each other.

I'm trying to look at them as modular/composable components, where the developer has enough leeway to decide what's best.

We might get some minor detail wrong, but IMHO it's a worthwhile tradeoff versus painstakingly detailing all combinations (they are many!), which will become obsolete as soon as a flow changes.

**Comment by lucasmendes-design** [comment]
Thanks Jacopo. Once I started doing this, I noticed a lot of details that we can tweak so I went through the main combinations. Here is the P2 ( paYJgx-3Rd-p2 )

We can simplify all flows and use the rationale (2 steps) we discussed yesterday.

**Comment by lucasmendes-design** [comment]
**Update** 
Upsell flows from themes i2 ( paYJgx-3TE-p2 )

**Comment by Copons** [comment]
## Update

Based on all the conversations, I've edited the issue description, including the new specs and a new tasklist.
