### ISSUE TITLE
Launchpad: Create "Share" task

### ISSUE THREAD

**Issue by nelsonec87** [Automattic/wp-calypso#78856]
Create a new task for the `keep-building` checklist. 

![image](https://github.com/Automattic/wp-calypso/assets/3801502/b9711f06-e5a9-481f-bbc4-36c5a603f8b8)

*The styles are similar to the Modal from `/client/my-sites/customer-home/components/celebrate-launch-modal.jsx`

![image](https://github.com/Automattic/wp-calypso/assets/3801502/b3e1f0f7-8af8-46bd-8819-9d34c10ebfd0)

### Tasks:
- [x] Create task on the backend
- [x] Add task to the `keep-building` checklist
- [x] Create the Modal
- [x] Link the Modal to the task

**Comment by nelsonec87** [comment]
@nuriapenya , what do you think about adding the `claim your domain` footer for the sites that don't have a custom domain?
