### ISSUE TITLE
Plans Next: Migrate the Features list/metadata to `@automattic/calypso-products`

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#79004]
This is part of uncoupling the plans-grid components for enabling and exploring use outside of Calypso. 

We have so far worked around the `FEATURES_LIST` definition living locally in Calypso by passing it into the components as a prop. However, that only allowed us to migrate the grid components to a package. We need to address the features list definition of living locally now. We cannot possibly use the plans-grid package in an external environment without the list of features.

It's not a straight-up migration as `FEATURES_LIST` has a few local dependencies - icons, `ExternalLinkWithTracking` component, etc. We will piece-meal the migration. Similarly to the AddOns metadata migration (https://github.com/Automattic/wp-calypso/issues/81374), we have created an exploratory PR (https://github.com/Automattic/wp-calypso/pull/88186) with TODOs and a list of tasks below.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/88181
- [ ] https://github.com/Automattic/wp-calypso/issues/88182
- [ ] https://github.com/Automattic/wp-calypso/issues/88183
- [ ] https://github.com/Automattic/wp-calypso/pull/88186
```

**Comment by chriskmnds** [comment]
Handling a partial solution to uncouple `plans-features-2023-grid` in https://github.com/Automattic/wp-calypso/pull/79733. Specifically the following:

> as a more realistic/faster alternative we can consider passing features-list as a prop and localise the getPlanFeaturesObject method in plans-features-2023-grid

cc @southp (we'll still need these ported into calypso-products, but with https://github.com/Automattic/wp-calypso/pull/79733 it will no longer be a blocker to package extraction

**Comment by southp** [comment]
Thansk for the heads up. Good to know that you've identified a way around it :) 
Also cc @jdc91 here since I've recommended him to look into this issue the other day.

**Comment by chriskmnds** [comment]
**Update:** Updated the description and added a list of tasks to handle this migration. There's a bit to do, although it will also contribute to the overall hygiene e.g. https://github.com/Automattic/wp-calypso/issues/88183 will be cleaning up more than just serving the Plans NPM migration
