### ISSUE TITLE
Pattern Placeholder blocking editing of template parts in site editor

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/wp-calypso#79145]
### Quick summary

**Status**: Work around in place, issue is being left open while root cause is addressed 

There seems to be a bug in the site editor when editing a Header or Footer template part where you see  Pattern Placeholder block, and you can’t edit.

This has been reported so far on simple sites, and on a range of themes.

Workaround: editing the template from the Page Editor works as expected.

![Pattern Placeholder](https://github.com/Automattic/wp-calypso/assets/31009008/08738d2a-2c91-4ca0-837a-27e239e6152b)

### Tasks

- [x] Stop triggering the GB bug: https://github.com/Automattic/wp-calypso/pull/79238 
- [x] Open a PR in GB to fix the issue @arthur791004 https://github.com/WordPress/gutenberg/pull/52503
- [ ] Revert #79238 once the GB fix has been deployed to dotcom

### Steps to reproduce

1. Pick one of these themes: Appleton, jinjang, Barnett
2. Click to go to Site Editor
3. Go to template parts
4. Click to edit Header or Footer template parts

### What you expected to happen

To edit the blocks that are part of the template part

### What actually happened

Can't see blocks, so can't edit.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
FYI this was escalated internally by OP here: p1688757944597679-slack-C02FMH4G8

📌 Message to Author
- Hey @davipontesblog , you mentioned this is noted `on a range of themes`, but could you let us know any of the themes that should be used when testing to replicate this?  Your steps to replicate doesn't currently include that info. Thanks!

**Comment by liviopv** [comment]
**More info:**
- Only affecting Simple Sites. I couldn't repro in Atomic of self-hosted.
- It seems to happen on theme switches, affecting only WordPress.com themes.
- It seems to be affecting themes set to display the latest post on the front page (those using Front Page, Home or Index template to load front page content). When I switched to Meraki, which uses a page assigned as front page on Reading Settings, I cannot reproduce it. 
- TT2 and TT3 are not affected either.

Tested the following theme switches:
TT3 (no issue) > Tenaz (issue) > Archivo (issue) > Kigen (issue) > TT3 (no issue) > TT2 (no issue) > Geologist (issue) > Meraki (no issue)


- Yesterday, I ran into this on 6511093-zd-woothemes and I thought the issue was being caused by attempts to headstart a FSE theme, so I tried to recreate the header by copying the blocks from the theme demo, which worked.

**Comment by davipontesblog** [comment]
Themes where we saw this:

Appleton, jinjang, Barnett

> Hey @davipontesblog , you mentioned this is noted on a range of themes, but could you let us know any of the themes that should be used when testing to replicate this? Your steps to replicate doesn't currently include that info. Thanks!

cc @cuemarie 👍

**Comment by khristiansnyder** [comment]
Noting this is happening on an AT site with Barnett active: #6517506-zen

Site Editor: 
<img width="1060" alt="Markup 2023-07-09 at 16 16 44" src="https://github.com/Automattic/wp-calypso/assets/41035049/757e8bbd-19fe-4afc-b868-f54fd3983bbc">

Template editor accessed from the regular page editor:
<img width="1213" alt="Screenshot on 2023-07-09 at 16:17:22" src="https://github.com/Automattic/wp-calypso/assets/41035049/2a9d2bd3-6752-4eff-9be9-4d1edcb9326a">

**Comment by sophiegyo** [comment]
I also could not reproduce this on a jurassic ninja selfhosted instance with WP 6.2.2 and NO plugins (or just Gutenberg 16.1.2).

Ran into a thread of reports:
https://wordpress.com/forums/topic/editing-header-footer-not-displaying/

**Comment by aleone89** [comment]
I've ran into this here: https://wordpress.com/forums/topic/editor-not-showing-section-on-index-page/

Theme: Bitácora 

On this theme, the workaround of editing the footer and header in the page editor doesn't seem to work.

**Comment by wiesenhauss** [comment]
6520328-zen - Issue appeared for after switching from Boutique to Yuga on an Atomic site.

**Comment by metabreakr** [comment]
pdEkSe-3PS-p2 using the Russell theme.

**Comment by dsas** [comment]
This only seems to happen when a template-part contains a pattern which includes `postTypes` in its metadata. [On dotcom we add this header](https://github.com/Automattic/wp-calypso/blob/1043c246e944255bfdd85100a0f0d8c9c8dfc739/apps/editing-toolkit/editing-toolkit-plugin/block-patterns/class-block-patterns-from-api.php#L295) to patterns which include a `core/template-part` blockType if it doesn't already have a postType set.

The intention of us adding that header is to hide patterns that aren't relevant to the post editor from the post editor. I think we could just temporarily remove that while we investigate.

The issue can also be reproduced on a dotorg site using the latest GB release if you change a dotorg theme like TT3 to make one of the patterns include a Post Types header [like this one](https://gist.github.com/dsas/ae1091679a1fbd94fa35f2c911653655).

**Comment by Greatdane** [comment]
6522285-zd-woothemes

Theme is **Tenaz** Simple site, switched from a classic them to FSE.

**Comment by liviopv** [comment]
@dsas It definitely seems related to ETK.

When I activate it on an Atomic Site (GB 16.1.2), this is what I get:

<img width="1504" alt="CleanShot 2023-07-11 at 09 29 06@2x" src="https://github.com/Automattic/wp-calypso/assets/14153300/c128ad55-7609-4438-a68d-c89cf2efae5d">

_The block that isn't rendering is not on the Header, ignore it._

And this is without ETK:

<img width="1503" alt="CleanShot 2023-07-11 at 09 31 54@2x" src="https://github.com/Automattic/wp-calypso/assets/14153300/067237cb-194d-48a1-a5c3-d184c8044323">

**Comment by liviopv** [comment]
Bumping the priority to high, since it's affecting both types of WordPress.com sites and the workaround at difficult to implement. cc @cuemarie

**Comment by arthur791004** [comment]
The root cause is the site editor only [allows the pattern with the specific post types](https://github.com/WordPress/gutenberg/blob/e6c4f7e46b9b8c14a447e92ea074a4572d282953/packages/edit-site/src/components/block-editor/use-site-editor-settings.js#L54) but it [doesn’t pass the current template type to the hook](https://github.com/WordPress/gutenberg/blob/e6c4f7e46b9b8c14a447e92ea074a4572d282953/packages/edit-site/src/components/block-editor/site-editor-canvas.js#L61). Hence, the pattern with the post types will be filtered out and becomes placeholder pattern.

**Comment by dsas** [comment]
I deployed a change to stop triggering this issue a while ago and have deployed a new ETK version to dotorg. It'll be picked up on atomic sites within the hour.

**Comment by cuemarie** [comment]
@dsas Thank you for that update! Checking in - looks like https://github.com/Automattic/wp-calypso/pull/79238 is merged, but https://github.com/WordPress/gutenberg/pull/52503 is not yet, so I don't want to jump to conclusions.

**Comment by dsas** [comment]
Yeah it's not a problem on dotcom right now because I disabled something obscure. I would like to keep this issue open so I remember to re-enable it when the GB PR makes its way back to dotcom.

**Comment by metabreakr** [comment]
For pdEkSe-40P-p2 I'm encountering an issue where the "pattern placeholder" exists for the comments template part — comments are not rendering on Atomic, however just using the Comments block works fine. 

Caveat: I am using a child theme of TT3, however this was not an issue earlier.

**Comment by dsas** [comment]
@metabreakr I doubt it's the same bug. I think it sounds like create-block-theme isn't exporting the pattern/template-part correctly.

 Are you comfortable checking that on a wporg site and raising a bug on https://github.com/WordPress/create-block-theme if so? if not I can do it.

**Comment by metabreakr** [comment]
@dsas I was discussing this with a colleague and will see if I can reproduce this further with the parent TT3 active. For what its worth, with the child theme active, the Comments template part when removed/re-added renders blank. Editing it shows only the pattern placeholder. On the other hand, just using the Comments block renders correctly.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Due to the status of this issue, I've downgraded the priority from `High` to `Normal` to better reflect its status in the larger context of open bugs in this repo.

>  I would like to keep this issue open so I remember to re-enable it when the GB PR makes its way back to dotcom.

@dsas https://github.com/WordPress/gutenberg/pull/52503 should now be in Dotcom, so just pinging you in case you'd like to revert https://github.com/Automattic/wp-calypso/pull/79238 next. 👍 When that's all squared away, I think we should be able to close this out again

**Comment by iamtakashi** [comment]
I'm unsure if this is the same, but I'm experiencing something similar—_some_ patterns in a theme don't appear in the editor. (they appear as pattern placeholders in the list view) It's only happening on simple sites, not atomic sites, not self-hosted sites.

**Comment by annezazu** [comment]
Hey folks. I just tried to replicate this on a simple site using the jinjang theme and wasn't able to replicate:

https://github.com/user-attachments/assets/80305c1e-c384-4673-bb5e-8e8c4f1173fe

Instead, I was able to edit the header in isolation without a problem. Further, from what I can see above, the Gutenberg PR to fix this was merged a long time ago: https://github.com/WordPress/gutenberg/pull/52503

I think it's safe to say that without the ability to replicate nor any recent reports that we can close this out. Let me know if that was incorrect.
