### ISSUE TITLE
Paid Stats: Redirect from purchase screen to checkout

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#79329]
Extend the purchase page developed as part of [Paid Stats: Add purchase screen to Calypso#31344](https://github.com/Automattic/jetpack/issues/31344) and link purchase buttons to redirect to a checkout page.
```[tasklist]
### Tasks
- [x] Use a [Jetpack Redirect link for checkout](https://github.com/Automattic/wp-calypso/pull/79328#discussion_r1264096919)
- [x] Add [redirect handling for Odyssey](https://github.com/Automattic/wp-calypso/pull/79328#discussion_r1262122262)
- [x] Add [success banner query string to redirect URL](https://github.com/Automattic/wp-calypso/pull/79328#discussion_r1262121239)
- [ ] https://github.com/Automattic/wp-calypso/issues/79858
```

**Comment by jsnmoon** [comment]
Capturing potential todo's from https://github.com/Automattic/wp-calypso/pull/79328 for your convenience, @grzegorz-cp:

- Use a [Jetpack Redirect link for checkout](https://github.com/Automattic/wp-calypso/pull/79328#discussion_r1264096919)
- Add [redirect handling for Odyssey](https://github.com/Automattic/wp-calypso/pull/79328#discussion_r1262121239)

I've added these to the parent issue's tasklist.

**Comment by kangzj** [comment]
I'm closing this as the Checkout page and Purchase page are all within Calypso, meaning the tracking events would have plenty of time to fire. Also it'd be easier to build funnels if all of these are captured in the same way.
