### ISSUE TITLE
Plans: Add support for paid Stats products (Self hosted Jetpack sites)

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#79402]
Related to https://github.com/Automattic/wp-calypso/issues/79092. This is the Calypso equivalent to https://github.com/Automattic/jetpack/issues/31713.

<img width="1232" alt="截圖 2023-07-14 下午2 50 27" src="https://github.com/Automattic/wp-calypso/assets/6869813/55c6e9eb-7300-40b9-a10a-7be187e35983">

Before(Now)|After
-|-
![Image](https://user-images.githubusercontent.com/4044428/253691530-2df8b1be-7e03-4301-a893-49c2e765f564.png)|![Image](https://user-images.githubusercontent.com/4044428/253691511-bcdbb109-1908-465a-b4d4-669f2bc5bb31.png)

The plans page at https://wordpress.com/plans/:siteSlug needs to be updated to handle paid Jetpack Stats products.

```[tasklist]
### Tasks
- [ ] <strike>Add support for simple and atomic WPCOM sites on Calypso's `/plans/my-plan/`</strike>
- [x] Add support for self-hosted (Jetpack) sites on Calypso's `/plans/my-plan/`
- [x] Add support for self-hosted (Jetpack) sites on Calypso's `/plans/`
```

**Comment by jsnmoon** [comment]
I removed this item from the tasklist: "Add support for self-hosted (Jetpack) sites on [Jetpack Cloud](https://cloud.jetpack.com/)".

Context: p1689793009681529/1689778516.503539-slack-C0438NHCLSY

**Comment by kangzj** [comment]
Since we are not rolling out to WPCOM site for this release. I'm marking the priority of the issue to Low.

**Comment by jsnmoon** [comment]
Sounds good!

**Comment by kangzj** [comment]
I've created a task https://github.com/Automattic/wp-calypso/issues/80258 to track 'Add support for simple and atomic WPCOM sites on Calypso's `/plans/my-plan/`'. Let's close the issue as all the efforts have been finished for self hosted Jetpack sites.
