### ISSUE TITLE
Launchpad: Audit of the current state in all flows

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#79468]
This is a maintenance task to ensure Launchpad works fine in all flows and find areas of improvement.

- [ ] General Onboarding - Write
- [ ] General Onboarding - Build
- [ ] Newsletter
- [ ] Link in Bio
- [ ] Free Flow
- [ ] Sensei
- [ ] VideoPress

Under each task list I will be adding the different issues I find
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/79473
```
