### ISSUE TITLE
WPCOM Paid Stats: Ensure that the upgrade notice isn't shown for WPCOM sites with a WP.COM paid plan

### ISSUE THREAD

**Issue by dognose24** [Automattic/wp-calypso#79880]
pejTkB-Ih-p2#comment-641

The response of API `/rest/v1.2/me/sites` has empty [site products](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/selectors/get-site-products.ts#L49) for ~Atomic and~ Simple sites.

Selector: `calypso/state/selectors/is-site-on-paid-plan`

```[tasklist]
### Tasks
- [x] Use the consistent purchase data resources for `notices` of all types of sites
- [x] Use purchases to check the owned products  of all types of sites on the purchase page: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/stats/stats-purchase/index.tsx#L49
- [x] Check plans with `isSiteOnPaidPlan` to show upsell notice for sites with only free plan
```

**Comment by annacmc** [comment]
Adding a comment here as I'm going to move on from this for the moment: after investigation, I think a good solution here could be to check the recent sales, and so if there's a number greater than 0 on product sales, choose to not display the Upgrade banner.

**Comment by kangzj** [comment]
closed with #81514
