### ISSUE TITLE
Live Preview: Review the options "Live preview" and "Open live demo" to avoid user confusion

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80134]
## Description

Currently, the options "Live preview" and "Open live demo" are next to each other:

| Theme card options | Theme detail page |
| --- | --- |
| ![Image](https://github.com/Automattic/wp-calypso/assets/797888/cf6746dd-9ff5-4f8b-811c-ff4cb1b09bd0) | ![Image](https://github.com/Automattic/wp-calypso/assets/797888/481b0c11-26c5-421a-ace8-ca8a4c0ea751)|

This is likely to confuse users, and especially problematic since the Live Preview takes users to the Site Editor. Thus, we need to explore better labels to describe these two options.

## Design

Design spec: pbxlJb-3Uv-p2#comment-2868

### Theme Card three dots menu

- For themes that have Live Preview functionality, show `Live Preview`
- For other themes, show `Demo site`

### Theme Detail view

- For themes that have Live Preview functionality, show `Preview demo site` button [on-hover](https://video.wordpress.com/v/5KTZnDJW)
- For other themes, show `Demo site` as a button

## Acceptance Criteria

```[tasklist]
### Tasks
- [x] Align with stakeholders regarding the new labels for "Live preview" and "Open live demo".
- [x] Align with stakeholders regarding the UI for "Live preview and "Open live demo".
- [x] Implement the new label copy. https://github.com/Automattic/wp-calypso/pull/80540
```
