### ISSUE TITLE
WPCOM Paid Stats: Add support for Simple and Atomic WPCOM sites on Calypso

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80258]
Related: https://github.com/Automattic/wp-calypso/issues/79402
```[tasklist]
### Tasks
- [x] Showing purchased Stats products on `/plans/my-plan/`
- [x] Provide multiple direct Stats products according to `is_commercial` of the site on the `Add-Ons` page: p1HpG7-oj4-p2#comment-65546
- [x] Remove the feature flag: `stats/paid-wpcom-stats`
```

**Comment by dognose24** [comment]
Note that the WPCOM `Plans` page only provides bundles along with products for `Jetpack` sites. The place to purchase Jetpack Stats for `Simple` and `Atomic` sites is on the WPCOM `Add-Ons` page.
