### ISSUE TITLE
Paid Stats: stop Commercial sites from purchasing Personal / Free products

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80259]
When the site is commercial (we'll have the identifier available soon), we only allow the site to choose the Commercial plan.

Other than stopping user from select lower plans, we'll probably want a message to clearly state why the Personal / Free plan is not available for the site.

![Image](https://github.com/Automattic/wp-calypso/assets/112354940/c51141e1-4ad4-4ed0-86d4-216f8c2410b9)

We need to remove the first accordion (with (1) Commercial header), so it looks like it's easier to pull out the commercial page into a separate component and skip showing the Purchase Wizard component.

Update the main section first and extend the page with the bottom section (for creating a support ticket) in the following pull requests. Support ticket functionality should be linked as part of #80882

```[tasklist]
### Tasks
- [x] Remove the possibility to click on the 1st step on the purchase wizard (1st accordion bar)
- [x] Add a section for creating a support ticket
- [x] Add a link to create a support ticket in case the site was incorrectly categorised as commercial
- [x] Check with design if we need to remove the bar showing `Commercial plan` (in place of `What site type is <domain>?`)
```

**Comment by kangzj** [comment]
Hi @ederrengifo @madebynoam 👋 

Do you folks have any design / UX guidance over the task please? Thanks in advance.

**Comment by grzegorz-cp** [comment]
This is now achieved by implementing the new design:

![Image](https://github.com/Automattic/wp-calypso/assets/112354940/4c7ac404-da0e-4fd5-a933-360b02400bb8)
