### ISSUE TITLE
Activity log: 

### ISSUE THREAD

**Issue by mj-collab** [Automattic/wp-calypso#80291]
#### Steps to reproduce

1. Starting at URL:
2.
3.
4.

#### Context / Source

https://wordpress.com/checkout/argentwebconnexion.wordpress.com#step2

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/80267
- [ ] https://github.com/Automattic/wp-calypso/pull/80250
- [ ] https://github.com/Automattic/wp-calypso/pull/80277
- [ ] https://github.com/Automattic/wp-calypso/pull/80242
- [ ] https://github.com/Automattic/wp-calypso/pull/79733
- [ ] https://github.com/Automattic/wp-calypso/pull/80282
- [ ] https://github.com/Automattic/wp-calypso/pull/80236
- [ ] https://github.com/Automattic/wp-calypso/pull/80095
- [ ] https://github.com/Automattic/wp-calypso/pull/80187
- [ ] https://github.com/Automattic/wp-calypso/pull/80180
- [ ] https://github.com/Automattic/wp-calypso/pull/80221
- [ ] https://github.com/Automattic/wp-calypso/pull/80169
- [ ] https://github.com/Automattic/wp-calypso/pull/80088
```

**Comment by mj-collab** [comment]
Je suis trop nulle pour comprendre ça!😵‍💫
