### ISSUE TITLE
[Spike] Live Preview: Support wporg themes on Simple sites

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#80411]
# Description
In Simple sites, the Live Preview will not work for wporg themes currently since we don't have wporg themes installed on it. 
We have two scenarios to make it work on Simple sites;

- For users who have an upgraded plan already;
	- Users can install a theme if they have a plan, so we can take a similar way as Atomic sites' "install&preview" (see https://github.com/Automattic/wp-calypso/pull/80353). 
	- We might need to notify users that the site will become the Atomic site once they install a wporg theme before doing the "install&previw". And it might take a longer time since it includes the transferring from Simple to Atomic.
- For users who do not have an upgraded plan yet;
	- This is trickier than the former since users need to upgrade a plan AND do the "install&preview". Or we might be able to change the logic so that users can install a theme without a plan only when live-previewing.

In this issue, we'll investigate how to address it as a spike.

Project Thread: pbxlJb-3Uv-p2

# Acceptance Criteria
- [ ] We know the clear path to make the Live Preview work on Simple sites.

# Dev Tasks

```[tasklist]
### Tasks
- [ ] Investigate it for users who have an upgraded plan already.
- [ ] Investigate it for users who do not have an upgraded plan yet.
``` 

# Related

- https://github.com/Automattic/wp-calypso/pull/80353

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
