### ISSUE TITLE
Components: Improve ResponsiveToolbarGroup

### ISSUE THREAD

**Issue by Copons** [Automattic/wp-calypso#80492]
While working on https://github.com/Automattic/dotcom-forge/issues/2988, we noticed that the `ResponsiveToolbarGroup` component has several rough edges that make it unreliable.

### Ensure Selected and Hover Colors Are Not in Conflict

Repro: open `/themes`, select a category from the More menu, hover on the selected element in the More menu.

| Selected | Selected/Hovered |
|--------|--------|
| <img width="219" alt="Screenshot 2023-08-14 at 12 04 07" src="https://github.com/Automattic/wp-calypso/assets/2070010/68025a05-6a13-4585-81bc-909a7ddc84b1"> | <img width="221" alt="Screenshot 2023-08-14 at 12 04 15" src="https://github.com/Automattic/wp-calypso/assets/2070010/d70f9516-5c34-4ce2-8741-451f5b11c7b1"> | 

To stay consistent with the non-collapsed menu, the selected element should not change color and/or background on hover.

### Fix Responsive Collapsing

The component is supposed to collapse responsively, grouping all elements exceeding the available width into a More menu.
This works sometimes but not always, making the component unreliable.

This task requires more investigation, but here are some prompts:

- The component only calculates the available width on first render.
- The component only calculates the available width when resizing in a specific direction (e.g. making the window narrower or larger).
- The component does not take advantage of the whole available width.
- The component incorrectly calculates the width when there's another element in the same row.

Example: in the Design Picker, we had to force _a lot_ of space between the list and the adjacent button to ensure an appropriate collapse point. (See https://github.com/Automattic/wp-calypso/pull/80440)

<img width="1331" alt="Screenshot 2023-08-14 at 13 16 32" src="https://github.com/Automattic/wp-calypso/assets/2070010/c52b3ec6-89a1-4165-9b5c-810485ccb09a">

### Extract the Selected Element From the More Menu

| Before | After |
|--------|--------|
| <img width="643" alt="Screenshot 2023-08-14 at 12 09 24" src="https://github.com/Automattic/wp-calypso/assets/2070010/bbae574f-e887-4b90-8355-eea96e7d0fa4"> | <img width="696" alt="Screenshot 2023-08-14 at 12 09 30" src="https://github.com/Automattic/wp-calypso/assets/2070010/4663c60a-a83e-427c-a129-086803901993"> | 

When the selected item is inside the collapsed More menu, we simply highlight the More element. This is not a particularly compelling UX, as the user can't immediately tell which element is selected.

It would be amazing if, assuming we have enough space, we could extract the selected element from the More menu, and display it before the More item, even if it gets out of order compared to the rest of the More menu.

### Update the Documentation

In the [component's docs](https://github.com/Automattic/wp-calypso/blob/53e16ca5b8e09c7d13e0d5e461f093b6c6ccf272/packages/components/src/responsive-toolbar-group/README.md), the most important props of the component are basically just links to the [Intersection Observer API on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

They are not particularly helpful unless the reader is already familiar with the API.

The docs should be improved so that these props become usable regardless of the knowledge of the underlying technology.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/80745
- [ ] https://github.com/Automattic/wp-calypso/pull/80746
- [ ] https://github.com/Automattic/wp-calypso/pull/80744
```
_Please replace the tasks in the tasklist with PRs._

**Comment by rcrdortiz** [comment]
I'm going to split this issue in two. In the first one, I'll be handling all except extracting the selected element from the `More Menu` since these items aren't dependent on each other and we can deliver the other tasks while I work on the last one that  I couldn't find a clear solution yet.

**Edit**: nevermind, I'll just add each individual PR to the task list as specified.

**Comment by rcrdortiz** [comment]
Implementing `Extract the Selected Element From the More Menu` is technically very complex for the reward it's going to provide. We can't move from the more menu to the main bar without either triggering a redraw of the menu bar (which can be confusing) and then we would also need to remove at least one element from the menu (and in some cases 2 elements) so that we can accommodate the selected element. Given that our users already need to click on more and select a subject, it makes sense to leave the subject where the user found it.

Since this is also a temporary design, I'm going to remove the task from the list.

**Comment by rcrdortiz** [comment]
All tasks are now completed and have been deployed.
