### ISSUE TITLE
Stats: Subscriber page improvements

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80532]
P2: pejTkB-Mn-p2

![Image](https://user-images.githubusercontent.com/1425433/260331967-4c74ed3a-a686-4c91-9aa1-1d1966704fcb.png)

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/80646
- [ ] https://github.com/Automattic/wp-calypso/issues/80609
- [ ] https://github.com/Automattic/wp-calypso/issues/80643
- [ ] https://github.com/Automattic/wp-calypso/issues/80610
- [ ] https://github.com/Automattic/wp-calypso/issues/80660
- [ ] https://github.com/Automattic/wp-calypso/issues/80591
- [ ] https://github.com/Automattic/wp-calypso/issues/80590
```

**Comment by kangzj** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/80591

**Comment by simison** [comment]
I'll close as all are done! :-)
