### ISSUE TITLE
Odyssey Stats: Upsell section should respect bundles

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80536]
For example if a site has Complete plan, the Search, Backup etc should NOT be shown in the upsell section.

![Image](https://user-images.githubusercontent.com/1425433/260342896-07b2bf60-12bb-45df-a5c0-b816eda010c1.png)

```[tasklist]
### Tasks
- [x] Hide upsell section for sites with a Complete bundle
- [x] Update upsell section for sites with a Security bundle
- [x] Investigate refactor of usePurchasedProducts hook
- [x] Update to test available upsells against site features
- [x] Update feature slugs for the Security upsell
- [x] Remove `JetpackUpsellCard` from components lib
- [ ] Review TODOs and wrap up this issue
- [ ] Remove duplicate SVG assets
```

**Comment by kangzj** [comment]
We might want to leverage the plan checks:

https://github.com/Automattic/jetpack/blob/trunk/projects/packages/plans/src/class-current-plan.php

However, I guess it will require both Jetpack and Calypso changes - not really a problem tho.

**Comment by a8ck3n** [comment]
For the `usePurchasedProducts` hook, see comments here:

https://github.com/Automattic/wp-calypso/pull/93318#pullrequestreview-2228551161

**Comment by a8ck3n** [comment]
A couple notes on possible refactorings:

1. The `usePurchaseProducts` hook uses an API call that returns incomplete plan data. It doesn't know about Business or Complete plans. If we update it to call `getSitePurchases` it should get the full set of plan/purchase data.
2. The hook will need its config data (the key slugs values) to be updated to include Business & Complete plans.
3. The data for the upsell section is configured in two separate places. In the caller (setting up the URLs) and in the component (hard-coded upsell options). We could improve this by putting config together in one place.

**Comment by a8ck3n** [comment]
The main body of work here has shipped. Updated this Issue with some follow-up tasks.

1. Update feature slugs on Security upsell. As it's currently configured, a basic Scan plan will cause the Security upsell to be hidden. Per Dognose's feedback [here](https://github.com/Automattic/wp-calypso/pull/99048#discussion_r1943111035).
2. Remove the `JetpackUpsellCard` component from the components lib.
3. Remove unused plan-related hooks and review any remaining TODOs in the `JetpackUpsellSection` component.

**Comment by a8ck3n** [comment]
Per [this comment](https://github.com/Automattic/wp-calypso/pull/99582#pullrequestreview-2608427116), we have duplicate SVG assets to clean up.
