### ISSUE TITLE
Live Preview: the "Back" button points to the Theme Showcase page with the Classic View

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#80595]
# Description

While testing the Live Preview feature, we noticed that the "Back" button points to the Theme Showcase page with the Classic View. So after live-previewing a theme, when the user goes back by clicking this button, the feature is gone. 

![Screen Shot 2023-08-14 at 14 37 22](https://github.com/Automattic/wp-calypso/assets/5287479/6bb4ac48-f40a-4899-b66a-6ec14c94edc2)

Note that the browser back button is correct; it takes us to the previous page, the Theme Showcase with the Default view.

This can be fixed by adding `Slot/Fill` on the Gutenberg side or changing the behavior dynamically by "hijacking". See https://github.com/Automattic/dotcom-forge/issues/2806.

Project Thread: pbxlJb-3Uv-p2

# Acceptance Criteria
- [x] The Back button correctly takes users back to the previous page.

# Dev Tasks

```[tasklist]
### Tasks
- [x] Decide how to implement
- [x] Implement the behavior above
- [ ] https://github.com/Automattic/wp-calypso/pull/81387
- [ ] https://github.com/WordPress/gutenberg/pull/54174
- [ ] https://github.com/WordPress/gutenberg/pull/54242
- [ ] https://github.com/Automattic/jetpack/pull/32913
- [ ] https://github.com/Automattic/jetpack/pull/33024
```

# Testing 
* Go to the Live Preview
* Click the Back button and see if it works

# Related

**Comment by autumnfjeld** [comment]
@okmttdhr @taipeicoder  I'm curious: what was the reasoning that this doesn't need to be part of the MVP?

**Comment by taipeicoder** [comment]
There are two items in the "Known issues to be addressed shortly" from pdtkmj-1JP-p2 that will require contributing to Gutenberg: https://github.com/WordPress/gutenberg/issues/53284 and this one. We want them fixed asap, but unfortunately we don't have a good idea of the ETA.

With that in mind, and considering that this issue didn't break the Live Preview functionality, it didn't seem a blocker for the MVP. That said, @okmttdhr we should be looking at proposing fixes to Gutenberg soon.

**Comment by autumnfjeld** [comment]
> With that in mind, and considering that this issue didn't break the Live Preview functionality, it didn't seem a blocker for the MVP. That said, @okmttdhr we should be looking at proposing fixes to Gutenberg soon.

@taipeicoder & @okmttdhr  We'll need to file this  issue as "blocker for MVP", I say that because Jacopo & T-Rex are actively discussing disabling access to the wp-admin view and the general view from @ianstewart  is also that we don't want users there in the wp-admin view.     That is on top of the general confusion of leaving on Showcase UI and returning to a different Showcase UI.   

Let us know if Ian or I can help gather devpower for reviews or help to work on this issue.  I'd suggest pulling in a T-Rexer, but they only have a few days before heading out for their team meetup & support rotation.

**Comment by okmttdhr** [comment]
I'm done with the implementation. We just need to wait for Jetpack and Gutenberg release.
