### ISSUE TITLE
Assembler: Remove styles from the initial step

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#80725]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
## Description

As proposed in [pekYwv-2Fn-p2](https://href.li/?https://wp.me/pekYwv-2Fn), we are splitting the selection of patterns and styles into two separate steps. This is done in order to prevent users selecting styles without having any patterns selected. See Figma file: [Tv3pYqA3EcRfiXC31IxrXE-fi-1660_50192](https://href.li/?https://www.figma.com/file/Tv3pYqA3EcRfiXC31IxrXE/?node-id=1660-50192).

| Before | After | After |
| --- | --- | --- |
| ![Image](https://user-images.githubusercontent.com/797888/260973320-e7d2def8-e9ac-4280-9626-c55847ed2bf3.png)| ![Image](https://user-images.githubusercontent.com/797888/260973371-7e664563-ab98-4533-8aa3-e35c008ec80c.png)|![Image](https://user-images.githubusercontent.com/797888/260973387-60b1dd28-e044-40d2-9069-b33c842177f5.png)|

This issue focuses on the Design your Own step (pattern selection). The step behavior is as follows:

- The Header drawer is opened by default.
- Users cannot continue to the next step unless they have selected any pattern.

The Pick your Style step is tracked in https://github.com/Automattic/wp-calypso/issues/80687

## Acceptance Criteria 

- [x] Implement the Design your Own step as described above.
- [x] Ensure that the new interactive elements have Tracks events.

**Comment by taipeicoder** [comment]
Closing via https://github.com/Automattic/wp-calypso/pull/80924.
