### ISSUE TITLE
Headstart: Only run headstart for the block-based theme with the static homepage

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#80732]
As we discussed before, we want to get rid of the headstart process as much as possible.

Here are the current usages:
* Pick the virtual theme during the onboarding, e.g.: Design Picker, Link in Bio flow
* Pick the theme via Design Picker

Hence, we have to avoid running the headstart based on the above situations.

## Tasks

- [x] Get rid of the headstart when selecting a virtual theme
- [x] Get rid of the headstart when selecting a theme during the onboarding.

## PRs

- [x] https://github.com/Automattic/wp-calypso/pull/80734
- [x] https://github.com/Automattic/wp-calypso/pull/80741
- [x] D119160-code
- [x] D119166-code

**Comment by fushar** [comment]
Looping @autumnfjeld & @taipeicoder . I remember we somehow still want to "headstart" some posts during onboarding, so that the resulting new site looks as similar to the demo site as possible.

With these changes, this won't be possible as we won't call Headstart anymore.

Or do we want to stop calling Headstart first, then discuss the above as separate initiatives?

cc: @Automattic/lego

**Comment by arthur791004** [comment]
Currently, the following themes might still need the headstart if we want to copy the pages/posts from the demo site to the newly created site:
* arbutus (2 posts)
* byrne (1 blog page + 6 posts)
* geologist (3 posts)

I'm still curious about whether we need to insert these initial pages/posts for the above themes as we won't do that for other themes 🤔

**Comment by arthur791004** [comment]
I made changes on https://github.com/Automattic/wp-calypso/pull/80741 to keep the headstart process for the themes mentioned above. We can decide whether to get rid of the headstart for those themes later 🙂

**Comment by arthur791004** [comment]
Closing it as it's completed!

**Comment by autumnfjeld** [comment]
> Looping @autumnfjeld & @taipeicoder . I remember we somehow still want to "headstart" some posts during onboarding, so that the resulting new site looks as similar to the demo site as possible.

@fushar  There is ongoing discussion about blog themes needing posts to look good in the starter site and Launchpad views:
p1692138639184199/1691558129.855869-slack-CRWCHQGUB
