### ISSUE TITLE
Paid Stats: Use the new commercial flag in components

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#80846]
Once https://github.com/Automattic/jetpack/pull/32595 is merged, we will have access to `is_commercial` flag.
Add a feature flag and pass this property to the Purchase page.

```[tasklist]
### Tasks
- [x] Add new feature flag
- [x] Check if new property is already available on the Stats page
- [x] Pass the property to the Purchase page
```
