### ISSUE TITLE
WPCOM Paid Stats: Purchase page adjustments to suit WPCOM sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#80888]
```[tasklist]
### Tasks
- [x] Adjustment Commercial purchase page styling
- [x] Adjustment Free & PWYW purchase page styling
- [ ] https://github.com/Automattic/wp-calypso/pull/81616
```
