### ISSUE TITLE
Newsletter Categories: Extend subscribe endpoint with opt-out newsletter categories param

### ISSUE THREAD

**Issue by mashikag** [Automattic/wp-calypso#80903]
### Details

Extend subscribe endpoint to allow for specifying opt-out newsletter categories

### Tasks

- [ ] Pass the array of newsletter categories to exclude/opt-out from in the iframe URL
- [ ] For Free plan, pass the array of newsletter categories to exclude/opt-out from in the `Blog_Subscription::add_subscriber` function.
- [ ] For Paid plan, pass the array of the newsletter categories to exclude/opt-out from in the `Memberships_Subscribers::subscription_success` function and then consequently the `wpcom_subs_subscribe` function.

### Checklist

- [ ] Ensure it is still possible to subscribe without passing the opt-outs
- [ ] Ensure subscribing to newsletter categories is not possible when the newsletter categories site setting is disabled

**Comment by TimBroddin** [comment]
It seems that with the subscription overlay, this happens on WPCOM (even for self-hosted Jetpack sites): fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Szrzorefuvcf%2Spynff.zrzorefuvcf%2Qpurpxbhg%2Qsbez.cuc%2337%2Q37-og

When submitting the form of the Subscribe block, an iframe with this source is overlaid on top of the page: `https://subscribe.wordpress.com/memberships/?blog=211832419&plan=newsletter&source=jetpack_subscribe&post_access_level=everybody&display=alternate&email=tim%2Bkkk%40broddin.be&`

**Comment by TimBroddin** [comment]
The title of this issue can use some slight tweaking. Even though we have an endpoint to include/exclude newsletter categories for a subscription (D117823-code), all of the subscribing magic for the subscription blog happens server-side.

Digging a bit deeper, the best approach is probably to pass the opted-out categories to the iframe src URL. Then upon registration of the subscriber, we need to opt them out for those categories.

For free plans, this would mean extending Blog_Subscription::add_subscriber (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Srznvy%2Qfhofpevcgvbaf%2Sfhofpevcgvbaf.cuc%3Se%3Qoq795r31%231030-og), with an extra argument for the excluded categories.

For paid plans, the actual subscription happens in a webhook that's called by Stripe: fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qzrzorefuvcf.cuc%3Se%3Qs51sn818%23979-og

---

Instead of hooking into these two places, we could try to somehow call the API endpoint (D117823-code) to exclude the categories. However, this would be hard to do for non-WPCOM users, since we'd need to retrieve the subkey somehow.

**Comment by mashikag** [comment]
> The title of this issue can use some slight tweaking. 

I am not sure what would you like the title to be renamed to. 😅 However, feel free to do so. 🙂 

> Even though we have an endpoint to include/exclude newsletter categories for a subscription D117823-code, all of the subscribing magic for the subscription blog happens server-side.

Yes, I did not mean to create new endpoints. I meant to extend the current subscribe action endpoint, which seems to be: `https://subscribe.wordpress.com/memberships/`, as per your previous comment.

> Digging a bit deeper, the best approach is probably to pass the opted-out categories to the iframe src URL. Then upon registration of the subscriber, we need to opt them out for those categories.

Yes, this sounds good to me. 

> Instead of hooking into these two places, we could try to somehow call the API endpoint D117823-code to exclude the categories. However, this would be hard to do for non-WPCOM users, since we'd need to retrieve the subkey somehow.

In my opinion, the opt-outs are so closely related to the subscribe action in this case that they should not be decoupled into a separate call.

**Comment by yansern** [comment]
All caught up with the discussion. Yes, so in short:
- Pass the array of newsletter categories to exclude/opt-out from in the iframe URL
- For Free plan, pass the array of newsletter categories to exclude/opt-out from in the `Blog_Subscription::add_subscriber` function.
- For Paid plan, pass the array of the newsletter categories to exclude/opt-out from in the `Memberships_Subscribers::subscription_success` function and then consequently the `wpcom_subs_subscribe` function.

Updating the PR description with a task list.

**Comment by TimBroddin** [comment]
This endpoint gets called on success: `https://public-api.wordpress.com/rest/v1/sites/<siteid>/memberships/subscribe`containing these fields:

```
email: "tim+ddddddffd@broddin.be"
newsletter: "auto", 
plan_id: "123"
stripe_payment_method: "xxx"
tracks: "123"
```
 
The subscription itself gets created when Stripe calls the webhook (upon the issue of a receipt). 

Stripe => Webhook URL ( fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Sjcpbz%2Qwfba%2Qraqcbvagf%2Spynff.jcpbz%2Qwfba%2Qncv%2Qzrzorefuvcf.cuc%23805%2Q805-og ) => Memberships_Subscribers::subscription_success

I'm still digging, but I don't see an easy way to get our excluded_newsletter_categories parameter in.

**Comment by TimBroddin** [comment]
Asked on Slack: p1693401719229009-slack-C01B6KEJ5GE

**Comment by TimBroddin** [comment]
PR for reference: D120476-code
