### ISSUE TITLE
Paid Stats: Create traffic page banner for commercial sites

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#81058]
Update the copy for the banner according to the design.

![Image](https://user-images.githubusercontent.com/112354940/263174355-8585627c-9266-4b91-9de4-2def6ff0c403.png)

```[tasklist]
### Tasks
- [x] Apply commercial site detection https://github.com/Automattic/wp-calypso/pull/81254
- [x] Create new banner https://github.com/Automattic/wp-calypso/pull/81160
- [x] Verify that non-commecial sites are not affected
- [ ] https://github.com/Automattic/wp-calypso/issues/81485
- [x] D120306-code: Stats: add commercial_site_upgrade to allowed list
- [ ] Address code duplication https://github.com/Automattic/wp-calypso/issues/81362
```

**Comment by kangzj** [comment]
Hey @grzegorz-cp & @annacmc, just want to point out, this looks like a new banner to me - the notice is intended for commercial sites with personal / free plan. Please ignore me if the task is about creating a new banner. Thanks 😄

**Comment by annacmc** [comment]
> Hey @grzegorz-cp & @annacmc, just want to point out, this looks like a new banner to me - the notice is intended for commercial sites with personal / free plan. Please ignore me if the task is about creating a new banner. Thanks 😄

Thanks @kangzj you are correct - after working on this it's appeared like creating a new banner is the best option so I've begun work on that in https://github.com/Automattic/wp-calypso/pull/81160

**Comment by kangzj** [comment]
Closing as there's only a maintenance task left and tracked.
