### ISSUE TITLE
Storage Add-ons: Refactor data layer

### ISSUE THREAD

**Issue by jeyip** [Automattic/wp-calypso#81374]
## Details

[There is an existing data layer](https://href.li/?https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/add-ons) for add-ons and their definitions in Calypso. It was, however, designed for a particular context — https://wordpress.com/add-ons. 

The 2023 plans pricing grid has migrated into an npm package so it can be reused in environments within Calypso and outside of Calypso  ( Logged out home page, landing pages). With the introduction of add-ons into the plans pricing grid, add-ons will also be implemented in different environments as well https://github.com/Automattic/martech/issues/1533.

In preparation for the migration, we'll want to, at the very least, move the [existing add-on hooks](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/add-ons/hooks) into a npm-released package ( data-stores seems like a good candidate ). We'll also want to do our best to introduce only the minimum amount of add-ons data necessary to support the storage add-ons feature. More discussion is unfolding p4TIVU-aKR-p2

## Related

Related to pdvytD-iS-p2 and p4TIVU-aKR-p2

## Tasks

Below is a list of tasks that we've extracted to guide the migration/refactor. We have put up a parent PR (https://github.com/Automattic/wp-calypso/pull/85465) where explorations happened and which will close this issue once merged. It includes various marks in the code where the tasks below stem from.

```[tasklist]
### Tasklist
- [ ] https://github.com/Automattic/wp-calypso/issues/87492
- [ ] https://github.com/Automattic/wp-calypso/issues/87494
- [ ] https://github.com/Automattic/wp-calypso/issues/87500
- [ ] https://github.com/Automattic/wp-calypso/issues/87527
- [ ] https://github.com/Automattic/wp-calypso/issues/87529
- [ ] https://github.com/Automattic/wp-calypso/issues/87530
- [ ] https://github.com/Automattic/wp-calypso/pull/88141
```

**Comment by chriskmnds** [comment]
@jeyip I have put up a PR with a list of TODOs that will need to happen in order to migrate the data layer to packages / `data-stores`. There are a few.

However, I'm looking now and realizing that we don't render storage add-ons in the plans-grid outside of Calypso. Is this indeed the case so far, and is there an intention to do so going forward e.g. to add storage add-ons to `/pricing` or other logged-out pages? I think until that becomes the case, then this work can be under-prioritised and just keep feeding the plans-grid with add-ons as a prop. Otherwise, we can carry on with the refactor.

**Comment by jeyip** [comment]
> However, I'm looking now and realizing that we don't render storage add-ons in the plans-grid outside of Calypso.

Yes this is correct 👍 

> Is this indeed the case so far, and is there an intention to do so going forward e.g. to add storage add-ons to /pricing or other logged-out pages?

Good question! There was an intention to reuse the storage add-ons in the logged out home page and landing pages. After the shuffling of priorities though, @niranjan-uma-shankar took over that work several weeks ago. I'm unsure where progress is at now 🤔 

> I think until that becomes the case, then this work can be under-prioritised and just keep feeding the plans-grid with add-ons as a prop.

I've pinged Niranjan. We can touch base with him to see if it's still on a roadmap

**Comment by jeyip** [comment]
@niranjan-uma-shankar sending a gentle nudge 🙂 We're wondering where work is at for the storage add-ons dropdown in landing pages and the logged out homepage. It'll inform our decision of whether or not to prioritize work on a refactoring effort https://github.com/Automattic/wp-calypso/issues/81374#issuecomment-1863370494

**Comment by niranjan-uma-shankar** [comment]
>  We're wondering where work is at for the storage add-ons dropdown in landing pages and the logged out homepage

In D128661-code, the dropdown changes were implemented but it'll need a rebase now since some of the pricing grid has gone through a few refactors for the intro offer work. Once that's complete, the major pending work is on the Calypso side - the selected addon needs to be carried over in the signup dependency over to the plans step and then checkout. I hope to pick this back up next week.
