### ISSUE TITLE
Launchpad: Quick Audit

### ISSUE THREAD

**Issue by nuriapenya** [Automattic/wp-calypso#81394]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/81395
- [ ] https://github.com/Automattic/wp-calypso/issues/81404
- [ ] https://github.com/Automattic/wp-calypso/issues/81405
```

**Comment by nuriapenya** [comment]
P2: p9Jlb4-8Tq-p2
