### ISSUE TITLE
Adjustment based on Feedback from Ali

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#81488]
```[tasklist]
### Tasks
- [x] Would What type of site is [site-name]? be a better phrasing? https://github.com/Automattic/wp-calypso/pull/81572
- [x] The design might come across as too Jetpack, which might seem a bit inconsistent in a flow for WordPress.com users. Adjust the colors for WPCOM users ONLY. Not Jetpack. As per designs in p1HpG7-orS-p2#comment-65837 https://github.com/Automattic/wp-calypso/pull/81608
- [x] A tiny revision suggestion for the body: Upgrade to get priority support and access to upcoming advanced features. see comment: https://github.com/Automattic/wp-calypso/issues/81488#issuecomment-1712382554
- [x] Remove the second step when a type hasn’t been selected yet. It makes sense to not show it until it is needed. https://github.com/Automattic/wp-calypso/pull/81600
- [x] Adjust title of first step to be "Select your site type" instead of "Personal/Commercial site" https://github.com/Automattic/wp-calypso/pull/81602
```

p1HpG7-orS-p2#comment-65816 & p1HpG7-orS-p2#comment-65837

cc @augurlu

**Comment by annacmc** [comment]
> A tiny revision suggestion for the body: Upgrade to get priority support and access to upcoming advanced features.

I've searched through all of our notices & source code and am not seeing this original phrasing ( `Upgrade to keep using Jetpack Stats and get early access to new upcoming advanced features`)  used anywhere currently. Has this perhaps been already updated? cc @kangzj

**Comment by kangzj** [comment]
@annacmc yes this one was updated yesterday 🙂️
