### ISSUE TITLE
Live Preview: Add the sticky notice when editing

### ISSUE THREAD

**Issue by okmttdhr** [Automattic/wp-calypso#82218]
# Description

Add the following non-dismissible, sticky notice to help the user be aware that they are live-previewing.

<img width="940" alt="Screenshot 2023-09-27 at 12 45 58" src="https://github.com/Automattic/wp-calypso/assets/5287479/c34a2953-798d-4f52-94f6-0cf26e3b04c9">

Suggested in pbxlJb-4rX-p2#comment-2987
Project Thread: pbxlJb-3Uv-p2

# Acceptance Criteria
- [x] The user can be aware that they are live-previewing while editing.

# Dev Tasks

```[tasklist]
### Tasks
- [x] Implement the sticker notice
- [ ] https://github.com/Automattic/jetpack/pull/33459
- [ ] https://github.com/Automattic/jetpack/pull/33461
- [ ] https://github.com/Automattic/wp-calypso/pull/82629
- [x] Deploy to wpcom
```

# Testing 
* go to site
* instruction 1

# Related

We still need to inform users that any new posts / pages, edits to existing posts / pages etc are actually reflected in their live site (if they save the edits). But I still don’t know how. Maybe add this information as well in the above sticky notice (ugly but works).
