### ISSUE TITLE
☂️ Jetpack Google Fonts module with the new Font Library

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#82226]
Referring to https://github.com/Automattic/wp-calypso/issues/81875, we finished the spike and are familiar with the new Font Library and how to integrate the Jetpack Google Fonts module with it now (pbxlJb-4yR-p2). We'll continue to finish the integration and support the new Font Library.

## Tasks

- [x] The Jetpack Google Fonts module can display the Google Fonts in the Site Editor correctly with the Gutenberg v16.7 above.
- [x] The Jetpack Google Fonts module still works well when the Gutenberg plugin is inactive
- [x] The homepage can render the text using Google Fonts correctly
- [x] The Font Library UI in the Editor keeps invisible on simple sites. 
- [x] https://github.com/Automattic/dotcom-forge/issues/4535
- [x] Enable the Font Library on simple sites
- [x] Enable the Font Library on atomic sites

## Advance

- [x] Load the Google Fonts on demand instead of all. As the discussion, this would be handled by Core. See pbxlJb-4yR-p2#comment-3049.

## PRs

- [x] https://github.com/Automattic/wpcomsh/pull/1740
- [x] https://github.com/Automattic/jetpack/pull/33203
- [x] D124361-code
- [x] D124144-code
- [x] https://github.com/Automattic/jetpack/pull/34157
- [x] https://github.com/Automattic/wpcomsh/pull/1576
- [x] https://github.com/Automattic/jetpack/pull/34306
- [x] [https://github.com/Automattic/jetpack/pull/34355](https://github.com/Automattic/jetpack/pull/34355)
- [x] [https://github.com/Automattic/jetpack/pull/34388](https://github.com/Automattic/jetpack/pull/34388)
- [x] [https://github.com/Automattic/wpcomsh/pull/1587](https://github.com/Automattic/wpcomsh/pull/1587)
- [x] [https://github.com/Automattic/wpcomsh/pull/1590](https://github.com/Automattic/wpcomsh/pull/1590)
- [x] D127182-code
- [x] https://github.com/Automattic/wpcomsh/pull/1544
- [x] https://github.com/Automattic/jetpack/pull/34608
- [x] D131649-code

## References

- https://github.com/WordPress/gutenberg/pull/54888
- https://github.com/WordPress/gutenberg/issues/55011#issuecomment-1748198200

**Comment by autumnfjeld** [comment]
Waiting for Font Library on core to be released.  Next release of Jetpack Nov 3 or 4.

**Comment by simison** [comment]
@autumnfjeld @arthur791004  I enabled font module yesterday for Atomic sites as otherwise we saw fatals across few themes.

https://github.com/Automattic/wpcomsh/pull/1544

Atomic sites got Jetpack, WP 6.4 and Gutenberg 16.9 upgrades before this so should be safe from what I gather.

**Comment by simison** [comment]
@autumnfjeld @arthur791004 folks reverted the [new font library enable PR](https://github.com/Automattic/wpcomsh/pull/1544), and [applied](https://github.com/Automattic/wpcomsh/pull/1560) another (temporary!) fix I suggested.

**Comment by autumnfjeld** [comment]
Arthur has been AFK this week.  I was in transit to Munich. Sorry we missed this.

**Comment by arthur791004** [comment]
There is an issue related to enabling the new Font Library on the existing atomic sites. However, we cannot reproduce the issue, and we guess the issue might be the dirty data that is stored in the user's global styles... See https://github.com/Automattic/dotcom-forge/issues/4535#issuecomment-1809766836.

**Comment by arthur791004** [comment]
Closing it as it's completed 🎉
