### ISSUE TITLE
Plans 2023: Revise and split the grid component props

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#82335]
> This we ought to address in a bit of immediate follow-up. We may consider splitting these props across several pieces, and updating the respective READMEs while at it, possibly:
> 
> 1. `ContextProps` (not exported) all the props that pertain to things added to the context
> 2. `SharedPlansGridProps` (not exported) all the props that are shared between the FeaturesGrid and ComparisonGrid (et al)
> 3. `ComparisonGridProps`
> 4. `FeaturesGridProps`

_Originally posted by @chriskmnds in https://github.com/Automattic/wp-calypso/pull/82249#discussion_r1339879089_
          
### Additional Notes
  
As of https://github.com/Automattic/wp-calypso/pull/82112 , and later https://github.com/Automattic/wp-calypso/pull/82249 we have a single `PlansGridProp` type that encloses all the types used in the grid components. This has only been done this way to address a more holistic props refactor separately, and to also ship the split PR (https://github.com/Automattic/wp-calypso/pull/82249) while leaving less room for conflicts in the interim. 

The TODO comment left there should guide this refactor more:

```
/*
 *	TODO clk: On PlansGridProps:
 *	1.	These props need to be split into what's needed separately for the internal grids and what's needed for the exported wrappers.
 *		This is currently also used as the internal type for the FeaturesGrid (wrongly).
 *			- onUpgradeClick is only needed for the wrappers exported from here. Internally the grids take a transformed
 *			handleUpgradeClick/onUpgradeClick function (force renamed to handleUpgradeClick in FeaturesGrid)
 *			- allFeaturesList is only relevant for the ComparisonGrid
 *			- gridPlanForSpotlight is only relevant for the FeaturesGrid
 *			- etc.
 *	2.	Explicitly set optional props and default values. Only absolutely vital props should be required.
 */
```

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/82894
- [ ] https://github.com/Automattic/wp-calypso/pull/83443
- [ ] https://github.com/Automattic/wp-calypso/pull/83473
- [ ] https://github.com/Automattic/wp-calypso/pull/83728
- [ ] https://github.com/Automattic/wp-calypso/pull/83976
- [ ] https://github.com/Automattic/wp-calypso/pull/84486
```

**Comment by ddc22** [comment]
@chriskmnds I am starting work on this :)

**Comment by ddc22** [comment]
Working on related cleanup of props in following branches. Review PRs in the following order.

<pre>
----o Trunk
&nbsp;&nbsp;&nbsp;&nbsp;| #82894 Refactor: Cleanup pro plan related dead code. 
&nbsp;&nbsp;&nbsp;&nbsp;| #83443 ( refactor/remove-dead-step-code )
&nbsp;&nbsp;&nbsp;&nbsp;| #83473 ( refactor/remove-is-reskinned-parameter )
&nbsp;&nbsp;&nbsp;&nbsp;| #83728 ( refactor/remove-is-in-vertical-scrolling-experiment-prop )
&nbsp;&nbsp;&nbsp;&nbsp;o---o 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| #83728 ( refactor/remove-is-in-vertical-scrolling-experiment-prop )
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| #84486 ( add/remove-plan-actions-for-wvip-woo-and-flowname )
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o
</pre>

1. https://github.com/Automattic/wp-calypso/pull/82894
2. https://github.com/Automattic/wp-calypso/pull/83443
3. https://github.com/Automattic/wp-calypso/pull/83473
4. https://github.com/Automattic/wp-calypso/pull/83976
5. https://github.com/Automattic/wp-calypso/pull/83728
6. https://github.com/Automattic/wp-calypso/pull/84486

**Comment by ddc22** [comment]
Started a manual audit of the props on a spreadsheet.
https://docs.google.com/spreadsheets/d/1IAkWaxbKOMgD2GH3TITTK-5bY5Z8heuYg6jtxdwaBZE/edit#gid=0
