### ISSUE TITLE
Reader/New Blogs: Tracking issue.

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#82426]
This task is tracking all of the individual pieces we need to implement the new blogs sidebar on the first posts tab.

## Details

Currently, the new First-Posts UI doesn't have a right-sidebar (because we removed the recommended-sites sidebar because it didn't make as much sense in this context).

Let's create a new stream which surfaces new blogs instead.

The stream should locate blogs that:

* Have the "green" flag.
* Were created within the last 3-5 days (_we adjust the timeframe as needed_).
* Have at least one post.

The easiest thing may be to do a query similar to the current first-posts query (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Ssvefg%2Qcbfgf%2Spynff.svefg%2Qcbfgf.cuc%3Se%3Qppps4396%2312-og) but just return the blog details.

## Individual Tracking Issues

- [x]  https://github.com/Automattic/wp-calypso/issues/82470
- [x] https://github.com/Automattic/wp-calypso/issues/82472
- [x] https://github.com/Automattic/wp-calypso/issues/82473
- [x] https://github.com/Automattic/wp-calypso/issues/82474

**Comment by sixhours** [comment]
@markbiek Can we consider this compelted?

**Comment by markbiek** [comment]
Yes!
