### ISSUE TITLE
Live Preview: the Activate button needs a loading state

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#82882]
# Description

p1697021447739469-slack-CRWCHQGUB
There is this issue where when activating a previewed theme from the Site Editor, the "Activate" button has no loading state and it can get awkward during the duration of the theme activation.
This is also happening in Core, so it should be a Core issue. I checked the CFT pdtkmj-1JP-p2 and several people had mentioned the issue, so I just wanted to confirm that it's deliberate that we won't fix this for MVP. 

https://github.com/Automattic/wp-calypso/assets/5665959/d7a6cc62-ac51-4f2a-a33a-1121b688aadf

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/33004451-8b25-46e6-afb2-1f3a55d651b5)

U02DWV9HXED/F060NBSA2LB-slack-file

# Tasks
- [x] Check in core or with Ignite team or Ben Dwyer if there is already an issue for this
- [x] If no issue, please create one
- [x] Contribute fix to core

@Automattic/lego

**Comment by scruffian** [comment]
Issue created here: https://github.com/WordPress/gutenberg/issues/55273

**Comment by arthur791004** [comment]
Closing it via https://github.com/WordPress/gutenberg/pull/55658
