### ISSUE TITLE
Stats: Update chart handling to support custom ranges

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#83039]
The chart currently uses today's date and the interval to determine what to draw. It is not set up to handle custom ranges. To support custom ranges I'm looking at adding URL parameters to drive the chart updates. This should make it more straight-forward to update the chart from the date range picker as well.
```[tasklist]
### Tasks
- [x] Add support for URL params to top-level Stats page
- [x] Update shortcut logic to use new params to drive the chart
- [x] Update date picker logic to use new params to drive the chart
- [x] Update date picker to set period value correctly
- [x] Update top-level to set quantity based on period value
```

**Comment by a8ck3n** [comment]
This is almost done. We still need to update the logic that determines the quantity for the chart to take into account the period value from the URL.

**Comment by grzegorz-cp** [comment]
@a8ck3n, the period/interval from the URL is reflected in the data and the interval selector. With the changes you picked from #83072, the period is also adjusted based on the number of days the users select in the text inputs. 

What logic did you have in mind in your last comment?

**Comment by a8ck3n** [comment]
@grzegorz-cp — While that properly updates the route with the period that is only half of the equation. We still need to take that route into account when determining the quantity (number of slices) for the chart.

The changes have been added here:

https://github.com/Automattic/wp-calypso/pull/83103

…and have since been merged by @kangzj so we should be good on this one.
