### ISSUE TITLE
Reader Nudges: Add a "First Posts" nudge to Customer Home

### ISSUE THREAD

**Issue by sixhours** [Automattic/wp-calypso#83105]
- [x] Add the card constant to the backend API, hidden behind `is_automattician()` for the time being. D125476-code
- [x] Create the frontend card with the same constant as used in the API. #83106
- [x] Add Tracks events to the card #83121
- [x] Finalize card design/layout. #83186 and #83361
- [ ] ~~Figure out backend logic for showing the card to only (new?) users who haven't published a post recently.~~ We've decided to show it to everyone for now.
- [x] Launch! Remove the `is_automattician()` gate on the backend. D126321-code

Related: paYKcK-3rd-p2

**Comment by sixhours** [comment]
Backend patch is started here: D125476-code

**Comment by nuriapenya** [comment]
Hey @sixhours 👋🏽 I have a couple of suggestions/tweaks to ensure the card UI is aligned with the other cards on the page:

* border-radius: 3px;
* {h1} font-weight: 500;

Essentially, the same as we have on the Launchpad component. Could we add those? 🙏🏽

**Comment by sixhours** [comment]
This has shipped in D126321-code
