### ISSUE TITLE
Design Picker in update-design flow doesn't offer styles selection

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#83216]
## Description
In the design-first flow, when the user it's redirected to the update-design flow, its design picker is missing style variations and colors+fonts styles. This is a deliberate choice introduced in https://github.com/Automattic/wp-calypso/pull/77568

![Image](https://github.com/Automattic/wp-calypso/assets/797888/a1d8b2ec-38b5-44ce-abd3-67b619563800)

# Tasks
- [ ] Update logic to support style selection in the update-design flow
- [ ] disable upsell modal
- [ ] Ensure launchpad displays the correct plan upsell item

**Comment by autumnfjeld** [comment]
> This is a deliberate choice introduced in https://github.com/Automattic/wp-calypso/pull/77568

 @taipeicoder If this is a deliberate decision, what is to be done?  Or rather what is the issue to be fixed?

**Comment by taipeicoder** [comment]
We'll need to update the logic to support style selection but probably will need to disable the upsell modal, and let Launchpad handle the upsell.

**Comment by arthur791004** [comment]
> We'll need to update the logic to support style selection but probably will need to disable the upsell modal, and let Launchpad handle the upsell.

Yes, that's true!
