### ISSUE TITLE
Stats Date Picker: Tweaks based on Noam's feedback

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#83269]
```[tasklist]
### Tasks
- [x] For the shortcuts, we’ll want to add aria-labels: aria-label={`Time range ${shortcutName}. Click to select and close filter options`}
- [x] Could we make the shortcuts first in the tab order instead of the fields?
- [ ] Sometimes there is flashing UI if I click Cancel (it seems to not repro when I try to record it :slightly_smiling_face: )
- [x] Could we add 4px rounded corners on the popover https://github.com/Automattic/wp-calypso/pull/83336
- [x] How about we make the shortcuts all be the max width (30 days) and then use space-between for the check and label instead of flush left.
- [x] There is a .32 letterspacing on the closed state button. We could get rid of it, as it looks to open. https://github.com/Automattic/wp-calypso/pull/83336
```

Source: p1697706248478599/1697698441.520379-slack-C04UE0ANHDY

**Comment by grzegorz-cp** [comment]
The tooltip issue looks more complex and I split it to #82305
