### ISSUE TITLE
☂️ Assembler from LOTS: moving Assembler before domains & plans

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#83390]
## Description
Remove friction to "get the fun stuff fast".   Similar to Explorers blog onboarding:
* Let’s update the “Blog” link on WordPress.com – Explorers Team P2 pb5gDS-38f-p2
* Closing Post: Blog Onboarding – Explorers Team P2 pb5gDS-3cB-p2

Here are two possible flows:
**Flow 1**
 LOTS→Build your own→ Account → Assembler → Domains

**Flow 2**
 LOTS→Build your own→ Account → Assembler → Launchpad

## Tasks

- [x] Add the assembler-first flow
- [x] Setup the tasks for the assembler-first flow in the launchpad
- [x] Add the “Personalize your site“ step to the assembler-first flow
- [x] Connect the assembler-first flow with the launchpad when the user updates their homepage
- [x] Support the checkout & launch
- [x] Don't complete the task, “Personalize your site”, at the beginning
- [x] Complete the task, “Choose a plan”, if people finish the checkout inside the Assembler
- [x] Enable the feature flag on horizon for testing
- [x] Enable the feature flag on production

## Enhancement

- [x] The “Back” button for the existing sites. See https://github.com/Automattic/wp-calypso/pull/84688#issuecomment-1839816363
- [ ] The progress bar texts seem way too large than usual (?) also, sometimes I see progress bar, sometimes I see three-dots. See https://github.com/Automattic/wp-calypso/pull/84688#issuecomment-1838236729
- [x] Clean up the “Query param support”. See https://github.com/Automattic/wp-calypso/pull/84688#discussion_r1414963183

## PRs

- [x] https://github.com/Automattic/wp-calypso/pull/84688
- [x] https://github.com/Automattic/jetpack/pull/34415
- [x] https://github.com/Automattic/jetpack/pull/34449
- [x] https://github.com/Automattic/wp-calypso/pull/84853
- [x] https://github.com/Automattic/wp-calypso/pull/84854
- [x] https://github.com/Automattic/jetpack/pull/34451
- [x] https://github.com/Automattic/wp-calypso/pull/84896
- [x] https://github.com/Automattic/wp-calypso/pull/84901
- [x] https://github.com/Automattic/wp-calypso/pull/84903
- [x] https://github.com/Automattic/jetpack/pull/34480
- [x] https://github.com/Automattic/jetpack/pull/34511
- [x] https://github.com/Automattic/wp-calypso/pull/85017
- [x] https://github.com/Automattic/wp-calypso/pull/85062

**Comment by autumnfjeld** [comment]
For reference:  See the recording of this "design first flow" https://cftp2.wordpress.com/2023/06/16/blog-onboarding-june-23rd/#design-first-flow

**Comment by arthur791004** [comment]
Closing it as it's completed! See p7DVsv-jyd-p2.
