### ISSUE TITLE
Assembler Add Pages: Implement the screen

### ISSUE THREAD

**Issue by fushar** [Automattic/wp-calypso#83450]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/83407
- [ ] https://github.com/Automattic/wp-calypso/pull/83501
- [ ] https://github.com/Automattic/wp-calypso/pull/83579
- [ ] https://github.com/Automattic/wp-calypso/pull/83622
- [ ] https://github.com/Automattic/wp-calypso/pull/83649
- [ ] https://github.com/Automattic/wp-calypso/pull/83639
- [ ] https://github.com/Automattic/wp-calypso/pull/83742
- [ ] https://github.com/Automattic/wp-calypso/pull/83748
- [ ] https://github.com/Automattic/wp-calypso/pull/83789
- [ ] https://github.com/Automattic/wp-calypso/pull/83766
- [ ] https://github.com/Automattic/wp-calypso/pull/83938
- [ ] https://github.com/Automattic/wp-calypso/pull/83902
- [ ] https://github.com/Automattic/wp-calypso/pull/83946
- [ ] https://github.com/Automattic/wp-calypso/pull/83987
- [ ] https://github.com/Automattic/wp-calypso/pull/84026
- [ ] https://github.com/Automattic/wp-calypso/pull/84033
- [ ] https://github.com/Automattic/wp-calypso/pull/84437
```

**Comment by taipeicoder** [comment]
Closing as this task is MVP-ready.
