### ISSUE TITLE
Stats: Date picker - arrows don't update URL

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#83570]
Clicking on arrows doesn't update the start and end dates for the new control and prevents showing proper data if you navigate past the currently visible period.

https://wordpress.com/forums/topic/jetpack-summary-stats-not-working/?view=all#post-3999030
```[tasklist]
### Tasks
- [x] Review click handling for navigation arrows
- [x] Add checks for chart boundries
- [x] Add calculations for new prev/next periods
- [x] Update chart range when navigating past bounds
```
