### ISSUE TITLE
Stats: Add steps to the slider

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#83898]
```[tasklist]
### Tasks
- [ ] Create a new slider component specific to the upgrade flow
- [x] Put the new component behind a feature flag
- [x] Move the new component to the Commercial upgrade page
- [x] Expose marks-related props from underlying slider
- [x] Update new slider to use marks-related props
- [x] Initial styling of marks, track, and thumbnail
```

```[tasklist]
### Feedback from 84160
- [x] Inline translation calls (update to useTranslate)
- [x] Move type definitions to separate file as needed.
```

**Comment by a8ck3n** [comment]
I've got some initial work started in #84160.

As far as adding steps to the slider goes, we can use the built in "marks" props to do that. We'll need to expose those props in our TypeScript wrapper component. If we set the `marks` prop to true we'll get a span set up for each point along the slider. We can use that to target our styles.

**Comment by a8ck3n** [comment]
Added a task list and some tasks as a starting point to this issue. I think that covers the basics based on my tinkering with the slider and the marks-related props so far.

**Comment by a8ck3n** [comment]
Noting this feedback regarding `translate` vs `useTranslate`.

https://github.com/Automattic/wp-calypso/pull/84160#discussion_r1401136540

**Comment by a8ck3n** [comment]
Noting this discussion regarding the layout of the slider track.

https://github.com/Automattic/wp-calypso/pull/84547#discussion_r1408708681

We might want to investigate expanding the track to full width but that means special-casing the CSS for the marks when either of the end-caps are selected. Tracking as a potential future improvement.

**Comment by kangzj** [comment]
Awesome work. I'm marking this as complete.
