### ISSUE TITLE
Stats: Create new API endpoint for tiered billing

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#84077]
Similar to Jetpack AI add an endpoint that returns data needed by the UI.
Start with creating a mock.

```[tasklist]
### Tasks
- [x] Create the mock API endpoint with properties that we might need to show usage and current tier D128671-code
- [x] Overwrite the `get_daily` function of class `Metered_Usage` to calculate the views count of the given day D129234-code
- [x] Calculate period usages for `is_over_limit`: D130734-code
```

**Comment by kangzj** [comment]
Closing as it's complete
