### ISSUE TITLE
Tracking Task: Remaining Monetize Tasks

### ISSUE THREAD

**Issue by edanzer** [Automattic/wp-calypso#84390]
### Details

- [x] General: Update background color of pages
   - https://github.com/Automattic/wp-calypso/pull/84392
- [x] General: Update tab menu to newer component
   - Requires discussion + updating SectionNav component: p1701196116039759-slack-CKZHG0QCR
   - https://github.com/Automattic/wp-calypso/pull/84719
   - With variation: https://github.com/Automattic/wp-calypso/pull/85312
   - [ ] Update docs for SectionNav component
- [x] Home: Update feature card component/markup/styles
   - https://github.com/Automattic/wp-calypso/pull/85252
   - [ ] Update docs for PromoCard component
- [x] Payment: Move plans list to main page rather than nested
   - https://github.com/Automattic/wp-calypso/pull/84574
   - https://github.com/Automattic/jetpack/pull/34316
- [x] Supporters: Update Supporters list
   - https://github.com/Automattic/wp-calypso/pull/84358
- [x] Supporters: Add single supporters screen (may require design input)
   - https://github.com/Automattic/wp-calypso/pull/85002
- [x] Ads: Improve styling/layout, esp around double navigation
   - https://github.com/Automattic/wp-calypso/pull/81852
- [x] Launchpad: https://github.com/Automattic/wp-calypso/issues/84197
   - [x] Update for Earn Launchpad
     - D130879-code (deployed)
     - https://github.com/Automattic/jetpack/pull/34448
   - [x] Update for Full Screen Launchpad
      - D130854-code (deployed)
      - [ ] Remove unneeded esc_url_raw()?
   - [x] Update My Home Launchpad
      - Additional convo on slack: p1701885893167609-slack-C0Q664T29
      - D131162-code (deployed)
      - https://github.com/Automattic/jetpack/pull/34498
      - https://github.com/Automattic/wp-calypso/pull/84929
      - [x] Fix/improve doc blocks for launchpad_context param? (ie, string | null)?
- [x] Launchpad: Have 'create plan' task directly open plan modal
   - https://github.com/Automattic/jetpack/pull/34413

### Other
- [x] Test syncing of launchpad tasks between Launchpad
- [x] Fix small list key issue: https://github.com/Automattic/wp-calypso/pull/84620
- [ ] Docs updated

### Updated Walkthrough (Dec 19)
- [x] Supporters: Learn link should open inline docs
   - https://github.com/Automattic/wp-calypso/pull/85518
- [x] Supporter screen: add cancel button at bottom
   - https://github.com/Automattic/wp-calypso/pull/85507
   - [ ] Add cancel button per plan?
- [x] Modal: Update subscriber cancel modal
   - https://github.com/Automattic/wp-calypso/pull/85517
   - https://github.com/Automattic/wp-calypso/pull/85568
- [x] Modal: Update plan delete modal to match figma (exclude checkbox)
   - https://github.com/Automattic/wp-calypso/pull/85576
- [x] Modal: Update stripe disconnect modal to match others
   - https://github.com/Automattic/wp-calypso/pull/85598
- [x] Modals: Make action buttons for destructive actions red/scary
   - https://github.com/Automattic/wp-calypso/pull/85602
- [x] Setup: Do not require stripe connection first
   - https://github.com/Automattic/wp-calypso/pull/85593
- [x] Create issue for Gold about subscribers api
   - https://github.com/Automattic/gold/issues/266
- [x] Add commission fee notice to Stripe settings
   - https://github.com/Automattic/wp-calypso/pull/85602
- [ ] Launchpad: customize text based on situation and state
   - https://github.com/Automattic/wp-calypso/pull/85911

**Maybe**
   - For newsletter sites, when creating plan, newsletter should be pre-toggled
   - ON HOLD Supporters: Add search box to Supporters list (on hold due to api limitations)
