### ISSUE TITLE
Tracking issue: font discrepancies post-WordPress 6.4

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#84611]
There have been multiple reports of missing fonts, font style differences between frontend and backend, and other font-related weirdness on WordPress.com after the WordPress 6.4 merge. This seems to affect mostly Atomic sites.

The reports have been spread out through different channels and threads, so this GH issue purpose is to centralize all reports so we can more easily identify patterns and estimate support impact.

## How add a new report
Copy the template below and fill in the info as in the example

### Template
```
- Issue: [brief description]
- Site: 
- Atomic/Simple
- Theme: 
- GB version, active/inactive:
- Font families:
- Original report: 
- [ ] Support interaction ID
```

**Example**
- Issue: custom font family not loading on the frontend
- Site: https://themarquecollective.com/
- Atomic
- Theme: builtbyexpress (child), TT3 (parent)
- GB version, active/inative: 17.0.2, active
- Font families: Jost
- Original report: p7DVsv-jib-p2#comment-48374
- [x] 7317086-zd-a8c

## Workaround

If the user is on a Atomic site, you can manually import the font using CSS:

```
/* fix missing font bug - XXXXXXX-ZD */
@import url('[LINK_TO_FONT_URL_FROM_GOOGLE_FONTS]');
 ```

Just make sure to change `[LINK_TO_FONT_URL_FROM_GOOGLE_FONTS]` with the correct link from https://fonts.google.com/

## Related/Dupliated GH issues
https://github.com/Automattic/jetpack/issues/34288
https://github.com/Automattic/themes/issues/7507 
https://github.com/Automattic/dotcom-forge/issues/4535
https://github.com/Automattic/wp-calypso/issues/84590
https://github.com/Automattic/wp-calypso/issues/83986
https://github.com/Automattic/themes/issues/7152
https://github.com/Automattic/wp-calypso/issues/71641

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: [https://consentbands.com](https://href.li/?https://consentbands.com)
- Atomic
- Theme: TT3 (Eventual on the original report)
- GB version, active/inative: 17.0.2, active
- Font families: Source Sans Pro
- Original report: p7DVsv-jib-p2#comment-48379
- [ ] 7304388-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: https://theitaliaguide.com/
- Atomic
- Theme: Aldente
- GB version, active/inative: 17.0.2, active
- Font families: Poppins
- Original report: p7DVsv-jib-p2#comment-48382
- [ ] 7325463-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: https://nightowl.business/
- Atomic
- Theme: Creatio
- GB version, active/inactive: 17.0.2, active
- Font families: Poppins
- Original report: p7DVsv-jib-p2#comment-48384
- [ ] 7294379-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: https://graceautospa.com/
- Atomic
- Theme: Vetro
- GB version, active/inactive: 17.0.2 active
- Font families: Inter
- Original report: p7DVsv-jib-p2#comment-48386
- [ ] 7317725-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: https://miltonskatingclub.com/
- Atomic
- Theme: Munchies
- GB version, active/inactive: 17.02, active
- Font families: Poppins
- Original report: p7DVsv-jib-p2#comment-48401
- [ ] 7352539-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: https://garretthoag.com/
- **Simple**
- Theme: Bute
- GB version, active/inactive: 
- Font families: Albert Sans
- Original report: p2EDhh-27B-p2
- [ ] 7371036-zd-a8c

First case I've seen of the issue happening on a Simple Site, @arthur791004

**Comment by liviopv** [comment]
- Issue: custom font family not loading italic variation on frontend
- Site: https://councilonstrategicrisks.org/
- Atomic
- Theme: Montagna
- GB version, active/inactive: 17.0.2, active
- Font families: Poppins 
- [ ] https://wordpress.com/forums/topic/italic-google-fonts-not-rendering/

First case where the font loads on the frontend (Poppins) but the variation (Italic) does not, @arthur791004

**Comment by liviopv** [comment]
* Issue: font weight loading differently on the frontend
* Site: http://campbellhallschoolforgirls.org/
* Simple
* Theme: Adventurer
* GB version: 17.0.2
* Font family: 
* [ ] https://github.com/Automattic/wp-calypso/issues/84590

**Comment by liviopv** [comment]
Possibly not related, but reporting here for the sake of completion

- Issue: default font family not loading on the frontend
- Site: https://ebybakehouse.com/
- Atomic
- Theme: Beleco (Marketplace)
- GB version, active/inactive: 17.0.2, active
- Font families: Merchant (not from Google Fonts)
- Original report: p1700681395986609-slack-C03TY6J1A
- [ ]

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: imageearthtravel.com
- Atomic
- Theme: TT3
- GB version, active/inactive: 17.0.2
- Font families: Poppins
- Original report: p9F6qB-dMa-p2
- [ ] 7313402-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font not loading on the frontend
- Site: [https://cabel.com/](https://href.li/?https://cabel.com/)
- Atomic
- Theme: Vivre 
- GB version, active/inactive: 17.0.2, active
- Font families: Space Mono
- Original report: p9F6qB-dMa-p2#comment-56659
- [ ] 7337833-zd-a8c

**Comment by liviopv** [comment]
- Issue: custom font family not loading on the frontend
- Site: https://arborealis.ca/
- Atomic
- Theme: Bitacora 
- GB version, active/inactive: 17.0.2, active
- Font families: Cormorant or Texturina
- Original report: https://github.com/Automattic/jetpack/issues/34288
- [ ] 7349464-zd-a8c

**Comment by kathrynwp** [comment]
- Issue: User has selected Raleway or Poppins in the Styles area of the Site Editor, but the selected fonts are not displayed on the front end
- Site: https://miteshoswal.com/
- Atomic/Simple: Atomic
- Theme: Pendant
- GB version, active/inactive: same result with GB active or inactive
- Font families: Raleway, Poppins
- Support interaction ID: 7375368-zd-a8c 

I will suggest that user try a Google Fonts plugin as a workaround in the meantime

Edit: I just noticed the `@import` option for Atomic sites so I sent that over as well!

**Comment by kathrynwp** [comment]
- Issue: _One_ of user's selected fonts is not displaying on the front end (Poppins) while the other one does appear to work (Domine)
- Site: https://katiestains.com/
- Simple
- Theme: Creatio
- GB version, active/inactive: n/a because Simple
- Font families: Poppins 
- Support interaction ID: 7376075-zd-a8c

**Comment by supernovia** [comment]
- Issue: Poppins displays, but not in italics as needed
- Site: [councilonstrategicrisks.org](http://councilonstrategicrisks.org/)
- Atomic
- Theme: Montagna
- GB Active, Version 17.0.3
- Font Family: Poppins
- Interaction: https://wordpress.com/forums/topic/italic-google-fonts-not-rendering/

Also @liviopv , noting this person added their own @import line but it's not flying. Is there something else they need to do?

Here's what they have in style:
`
@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
`

**Comment by galakhyati** [comment]
- Issue: custom font family not loading on the frontend
- Site: [momirzamkt.com](https://momirzamkt.com/)
- Simple
- Theme: Creatio
- GB version, active/inactive: N/A since it is a Simple site
- Font families: Figtree
- Chat: 7377419-zd-a8c
- [ ] Support interaction ID(Follow up): 7377472-zd-a8c

**Comment by arthur791004** [comment]
> Site: https://garretthoag.com/
> First case I've seen of the issue happening on a Simple Site, @arthur791004

It's the same issue that we're addressing now. The old font data has been stored in the user's global styles in some way...

![image](https://github.com/Automattic/wp-calypso/assets/13596067/249c6737-d87d-42e1-a515-7a4f53b5246b)

Same for the following simple sites
* https://momirzamkt.com/
* https://katiestains.com/

> Site: https://katiestains.com/
> Issue: One of user's selected fonts is not displaying on the front end (Poppins) while the other one does appear to work (Domine)

The issue is the same as the above. The Domine works as it's provided by the theme JSON as well so we will try to load fonts from the theme JSON first, and then the jetpack google fonts. That's why the Poppins doesn't work.

> Site: http://campbellhallschoolforgirls.org/

It's related to https://github.com/Automattic/wp-calypso/issues/84590. The theme provides the Rubik font but it only supports `font-weight: 900`, so that's the reason why the `font-weight: 300` (light) cannot be displayed correctly on frontend.

**Comment by suyogyashukla** [comment]
- Issue: Custom font family (Rubik) not loading on the front-end
- Site: https://heysheblogs.com/
- Atomic/Simple: Atomic
- Theme: Twenty Twenty Three
- GB version, active/inactive: Active, 17.0.3
- Font families: Rubik
- Original report: 7347065-zd
- [x] Support interaction ID: 7347065-zd

**Comment by suyogyashukla** [comment]
- Issue: Custom font family not loading
- Site: theadventuremanual.com
- Atomic/Simple: Atomic
- Theme: Adventurer
- GB version, active/inactive:
- Font families: Commissioner and Montserrat
- Original report: 7361495-zd-a8c
- [x] Support interaction ID (follow-up): 7361540-zd-a8c

**Comment by dragstor** [comment]
- Issue: Custom font family not loading on live site, but shows fine in the editor
- Site: elanenery.com
- Atomic/Simple: Simple
- Theme: Creatio
- GB version, active/inactive: It's a simple site
- Font families: Albert Sans (for the entire site) + Source Sans Pro (which works fine)
- Original report: 7378797-zen
- [ ] 7378797-zen

**Comment by jorpdesigns** [comment]
> * Issue: custom font family not loading on the frontend
> * Site: https://graceautospa.com/
> * Atomic
> * Theme: Vetro
> * GB version, active/inactive: 17.0.2 active
> * Font families: Inter
> * Original report: p7DVsv-jib-p2#comment-48386
> * [ ]  [7317725-zd-a8c](https://href.li/?7317725-zen)

Added suggested workaround and user confirms the font now loads correctly. They want to be informed when a permanent fix is released.

**Comment by arthur791004** [comment]
We merged https://github.com/Automattic/jetpack/pull/34306 and it will be included in the next release of Jetpack. In addition, we also synced the changes to https://github.com/Automattic/wpcomsh/pull/1587 so the issue should be resolved now 🎉

Here are the remaining issues
* The font family dropdown in the Editor may display the same fonts twice as dirty data is stored in the user's global styles. https://github.com/Automattic/jetpack/pull/34352 should address it, and we'll continue to think about how to provide a tool to clean up dirty data on atomic sites.
* The “Source Sans Pro“ and “Source Serif Pro“ may not be rendered correctly as they are renamed to “[Source Sans 3](https://fonts.google.com/specimen/Source+Sans+3?query=Source+Sans)” and “[Source Serif 4](https://fonts.google.com/specimen/Source+Serif+4?query=Source+Serif)“. So, if the user encounters this issue, we can simply change the setting to the new name in the Editor.
* The fonts provided by the theme may not support ALL font weights. See https://github.com/Automattic/wp-calypso/issues/84590#issuecomment-1831225247

**Comment by liviopv** [comment]
@arthur791004 Thanks!

> The “Source Sans Pro“ and “Source Serif Pro“ may not be rendered correctly as they are renamed to “[Source Sans 3](https://fonts.google.com/specimen/Source+Sans+3?query=Source+Sans)” and “[Source Serif 4](https://fonts.google.com/specimen/Source+Serif+4?query=Source+Serif)“. So, if the user encounters this issue, we can simply change the setting to the new name in the Editor.

While trying to fix this on the user's site by switching to Source Sans 3, I noticed that the font choices available in Global Styles in Styles > Typography > Headings are different than the ones found in Styles > Blocks > Heading > Typography, where the old font list with Source Sans Pro is still loaded. Is this due to the dirty data?

**Comment by arthur791004** [comment]
> While trying to fix this on the user's site by switching to Source Sans 3, I noticed that the font choices available in Global Styles in Styles > Typography > Headings are different than the ones found in Styles > Blocks > Heading > Typography, where the old font list with Source Sans Pro is still loaded. Is this due to the dirty data?

YES! If there is dirty data on the user's site, both the old font list and the new font list will be shown in the font selection dropdown. We're working on https://github.com/Automattic/wpcomsh/pull/1592 to allow us to clean up the dirty data on the user's site.

**Comment by jerrysarcastic** [comment]
- Issue: headings on published pages use a different font weight that what is shown in Gutenberg
- Site: https://meganrosefreelance.com/
- Simple
- Theme: Adventurer
- GB version: Gutenberg: v17.1.3 
- Font families: Rubik
- Original report: https://wordpress.com/forums/topic/front-end-body-copy-font-has-suddenly-changed/

**Comment by Imran92** [comment]
I've added a possible fix (https://github.com/Automattic/jetpack/pull/34776) for an issue we've faced here (https://github.com/Automattic/jetpack/issues/34777). Probably this can also be relevant for this thread.

**Comment by Jaykame** [comment]
- Issue: Custom font (Raleway) not displaying on the front end but shows fine in editor. 
- Site: chasety.com
- Atomic/Simple: Atomic
- Theme: Al Dente
- GB version, active/inactive: Version 17.7.0 active
- Font families: Raleway
- [ ] Support interaction ID 7799014-zd-a8c

The @import workaround did not work.

**Comment by liviopv** [comment]
With 6.5 now running on WordPress.com, it seems that all issues tracked in this thread have been resolved.
