### ISSUE TITLE
☂️ Assembler Level-up on horizon

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84733]
## Description
This issue tracks the tasks needed to get the "leveled up" version of the Assembler onto horizon.  Coordinate with Ola, Saxon, and Rich Tabor.

* Leveling up Assembled Sites – Designomattic puPv3-hc5-p2
* Assembler Leveling-up Call: Making it Real – Team Lego pbxlJb-52o-p2
* p1701400445742889-slack-C048CUFRGFQ

Autumn also needs to create a Project Thread for this.

```[tasklist]
## Tasks
- [ ] https://github.com/Automattic/dotcom-forge/issues/4778
- [ ] https://github.com/Automattic/wp-calypso/issues/84893
- [ ] https://github.com/Automattic/wp-calypso/issues/84948
- [ ] https://github.com/Automattic/dotcom-forge/issues/4783
```

@Automattic/lego

**Comment by miksansegundo** [comment]
> Add patterns to source site with special meta tag

Let's also add patterns from TT4 into the Dotcom library. https://github.com/Automattic/wp-calypso/issues/84842

**Comment by richtabor** [comment]
> Let's also add patterns from TT4 into the Dotcom library. #84842

That's fine, but I'd consider that a separate project and those patterns not to be tagged as these others are.

**Comment by fushar** [comment]
All tasks in this issue are done. We can already test the whole Assembler v2 experience on Horizon, so closing this issue!
