### ISSUE TITLE
Year-in-review: Tracking Issue

### ISSUE THREAD

**Issue by markbiek** [Automattic/wp-calypso#84757]
This issue is track all of the individual 2023 year-in-review issues:

- [x] https://github.com/Automattic/wp-calypso/issues/84758
- [x] https://github.com/Automattic/wp-calypso/issues/84759
- [x] https://github.com/Automattic/wp-calypso/issues/84765
- [x] https://github.com/Automattic/wp-calypso/issues/84766
- [x] https://github.com/Automattic/wp-calypso/issues/84876

**Comment by markbiek** [comment]
Closing this in favor of just having the individual issues in the YIR project column.
