### ISSUE TITLE
Stats: release the prorated flow

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#84838]
```[tasklist]
### Tasks
- [x] Ship product support - D129634-code
- [x] Sync new billing plan to production
- [x] Round the $requested_quantity to match tier's maximum_unit - D129634-code
- [x] Remove feature flags `stats/plan-usage` and `stats/tier-upgrade-slider` - https://github.com/Automattic/wp-calypso/pull/85948
```
