### ISSUE TITLE
☂️ Assembler AI: create a testable onboarding flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#84839]
# Description

Lego will help make the AI prototype from @artpi  testable in an oboarding flow.  This will be for internal testing only.   Unless there are any techincal blockers, this will be a "Fun First Flow" and the AI screen will show up right after user account.

**Flow:**
`User Account -> AI prompt screen -> Assembler -> Editor -> Launchpad with domain and plans items`

* Assembler AI Meeting – Dotcom Marvel pekYwv-3o8-p2
*  Assembler and AI analysis p9Jlb4-a0a-p2 - by Lucas
* AI + Patterns + Styles = Fun – Designomattic puPv3-hud-p2 - vision post by Saxon
* AI-generated theme variations – Themes pNEWy-gvy-p2#comment-55928 exploratory deisgn post

# Tasks

```[tasklist]
### Tasks
- [ ] #84956
- [ ] https://github.com/Automattic/wp-calypso/pull/85189
- [ ] https://github.com/Automattic/wp-calypso/pull/85607
- [ ] https://github.com/Automattic/jetpack/pull/34532
- [ ] https://github.com/Automattic/wp-calypso/pull/85215
- [ ] https://github.com/Automattic/wp-calypso/pull/85426
- [ ] https://github.com/Automattic/wp-calypso/pull/85485
- [ ] https://github.com/Automattic/wp-calypso/pull/85580
- [ ] https://github.com/Automattic/jetpack/pull/34709
- [x] D132645-code
```

@Automattic/lego

**Comment by taipeicoder** [comment]
Closing since the PT is maked as done. See pbxlJb-573-p2#comment-3427
