### ISSUE TITLE
Stats: Update PWYW flow with new slider

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/wp-calypso#84859]
```[tasklist]
### Tasks
- [ ] Revisit emoji thresholds
- [ ] Expose initialValue on slider
- [ ] Move thumb SVG to it's own file
```

**Comment by kangzj** [comment]
Closed as it's complete.
