### ISSUE TITLE
Stats: add support for higher tiers

### ISSUE THREAD

**Issue by kangzj** [Automattic/wp-calypso#85246]
The highest tier is not really one tier - it is a series of tiers, and billed by every million records per month.

```[tasklist]
### Tasks
- [x] For new purchase, we show up to 6 tiers - let's see if it'll be too tight, if so we could show less, for example to 4M - optional
- [x] For tier upgrade flow, we show 6 tiers in total - We want the number of tiers to be the same as of less than new purchase
- [x] Update tooltip wording
```

p1702499950288929-slack-C0438NHCLSY
