### ISSUE TITLE
☂️ PT: Templates in the Calypso Pages page

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#85686]
# Description
Project thread: pbxlJb-5mS-p2

Currently in /pages we show the home template.   We'd like to explore adding additional common templates, like 404. These would link out to the Site Editor, just like the home template does.  See p1702954523624609/1702952293.495479-slack-C048CUFRGFQ

![Image](https://github.com/Automattic/wp-calypso/assets/5665959/b9e4c0a8-656c-4db3-bee6-4726a26aee4d)

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/85963
- [ ] D133687-code
```

Dev work can be started on this as a protype:
- [ ] Duplicate the UI of the pages box and place it below the pages box, we can temporariily title it "Tempaltes"
- [ ] Add 404 template
- [ ] Add Search template

**Comment by taipeicoder** [comment]
@autumnfjeld do you mean that we want to a new "Templates" section below the Pages? Does that include moving the Homepage to the Templates section?

One consideration is that the Pages infinite scrolls, so for a user with looooots of pages (edge case), it'd be easy for them to miss the section. How about placing the templates above the Pages section? I guess it depends on the degree of discoverability we want to give to the templates section.

Also, do we want to put this behind a feature flag?

**Comment by autumnfjeld** [comment]
Great questions @taipeicoder .   As you've already discovered, there are some UI and design choices we need settle on.  @matt-west  is working on the design, and with your initial investigation he can address this in his design.   We'll make a PT for this, so actually that can be your next step of work if you don't mind.  :)   In the design section of the PT we can list "Open questions". 

As far as feature flag: we could get away with testing via a calypso live link ya?   I'll leave that decision to you.    I think we'd probably want a CfT on cftp2,  not necessarily because of complexity, but because it is a big change to the UI that should be flagged with HEs.

**Comment by taipeicoder** [comment]
I'll spend today working on a PoC and write the PT by end of week with the design questions I have 🙂

**Comment by taipeicoder** [comment]
Closing due to the issue being stale, and no current plans to take further action on it.
