### ISSUE TITLE
☂️ Stepper: Remove the deprecated progress bar

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#85768]
There is a significant amount of unused code related to the progress bar, and the attempt to track the flow progress in Stepper. Since the feature has been deprecated, this code is unnecessarily executed, many of them in every step of every flow. Furthermore, sometimes this code is also copied over when creating new steps or flows. 

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/85749
- [ ] https://github.com/Automattic/wp-calypso/pull/85769
- [ ] https://github.com/Automattic/wp-calypso/pull/85812
```
