### ISSUE TITLE
☂️ PT: Assembler Choice Step in Onboarding

### ISSUE THREAD

**Issue by arthur791004** [Automattic/wp-calypso#86035]
## Description

This is a project to promote the Assembler in the onboarding flow. It involves creating a "Design Choices" step after the Goals step, which will give users the option to either design their own theme or pick an existing theme.

## Tasks

- [x] Introduce a new step, Design Choices, to give users the option to either design their own theme or pick an existing theme.
- [x] Add a track event to record the user's choice

## PRs

- [x] https://github.com/Automattic/wp-calypso/pull/85979
