### ISSUE TITLE
Stats: Update illustration on purchase pages

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#86129]
Using the new feature flag, replace the existing SVG with the new illustration.

- If possible, use an SVG, but check with the designers if you need to use a PNG.
- Test with Odyssey because it had some issues with some SVG in the past.
- Don't place the SVG code in the component.

Relevant discussion: p7H4VZ-4JT-p2 — Covers some limitations around using SVG in Calypso.

```[tasklist]
### Tasks
- [x] Changes behind a feature flag
- [x] New illustration applied to the commercial purchase flow
- [x] New illustration applied to the personal purchase flow
- [x] Tested with Odyssey
```

**Comment by a8ck3n** [comment]
Hello @ederrengifo. 👋 

Would it be possible to get the image assets for the updated purchase pages referenced here? — p1HpG7-q6R-p2

I tried exporting from the linked Figma as an SVG but I end up with a large (1.2 MB) image file. Exporting as PNG gives me a much smaller file at 100 KB but the image size is a bit too small and the quality suffers.

Edit: We got 2 PNG files via the design team in Slack. Moving forward with a two-PNG (supporting HiDPI) approach.

**Comment by a8ck3n** [comment]
The illustartion updates are complete. Just need to test this out with Odyssey to confirm there aren't any issues there.

**Comment by grzegorz-cp** [comment]
I noticed that there is still an old background behind the new PNG, and it sometimes shows up depending on the screen size. To reproduce, resize your screen until the background shows up on the left side.
This may be happening because something is not moved to the feature flag.
Could you please fix it as part of this issue?

![Image](https://github.com/Automattic/wp-calypso/assets/112354940/4abc23b2-3000-4511-aad6-1e0a9b769646)

**Comment by a8ck3n** [comment]
Fixed the background SVG that I had previously overlooked. Also tested in Odyssey and confirmed everything is working correctly there too so this Issue should be DONE.

cc: @grzegorz-cp 👍 ⚡
