### ISSUE TITLE
Stats: Add a feature flag for improving the purchase flow for new users

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#86128]
Start the new project by adding a feature flag, applying it, and updating the copy for the purchase pages (commercial and personal) according to the design.

- Feature flag docs are [here](https://github.com/Automattic/wp-calypso/blob/trunk/config/README.md#feature-flags).
- Design wrap up is here: p1HpG7-q6R-p2

```[tasklist]
### Tasks
- [x] Feature flag added
- [x] Text on the commercial purchase page updated
- [x] Text on the personal purchase page updated
- [x] Update (and expand) Benefits listing
- [x] Move Benefits listing higher up the page
```

**Comment by a8ck3n** [comment]
For the text-related tasks, I'm seeing the following. On the commercial purchase page:

1. Updated header text: "Welcome to Jetpack Stats"
2. Updated button text: "Upgrade and continue"

On the PWYW page:

1. Updated header text: "Name your price for Jetpack ~your~ Stats"
2. Updated notice text (which has a typo and grammatical issues).

I'm wondering if I should also tackle the benefits list as part of this issue or open a new PR for that. It would involve:

1. Moving the benefits higher in the page to match the updated design.
2. Updating the list from the current 2 items to the 6 items shown in the design.

I'll start with just the copy updates here and follow up with the benefits pending some feedback. @grzegorz-cp

**Comment by a8ck3n** [comment]
This Issue is a wrap.
