### ISSUE TITLE
Stats: Add skip button interaction

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#86136]
Finalise the implementation of the "I will do it later" button. After finishing #86131 and #86132, we can make sure that this button redirects users to the Stats page and updates a proper API flag marking that the users went through this flow (instead of always showing the purchase flow to this new user).

```[tasklist]
### Tasks
- [x] Button links to the Stats page
- [x] Before interacting with the button or purchasing a plan new users see the purchase page
- [x] After interacting with the button or purchasing a plan users see the Stats page
```

**Comment by grzegorz-cp** [comment]
Use the notice mutation hook to add skip button functionality.
