### ISSUE TITLE
Tracking: "Updating failed. Could not update the meta value of jetpack_seo_noindex in database"

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#86412]
### Quick summary

_Moving reports from https://github.com/Automattic/wp-calypso/issues/84639 into its own issue._
**Escalation thread: p1705329182812459/1702028916.130899-slack-C02FMH4G8**

Users are experiencing failures when attempting to save posts and other settings on Simple (most cases) and Atomic Sites, with an error message of `Updating failed. Could not update the meta value of jetpack_seo_noindex in database`, which is the same that happened while https://github.com/Automattic/wp-calypso/issues/84639 (see video in the issue) was still active when using the `noindex` tag.

There's no easy way to reproduce it yet, but there are several reports in the wild:

- [ ] 7473253-zd-a8c
Simple site, affected post: https://oscarwildeinamerica.wordpress.com/wp-admin/post.php?post=12860&action=edit
A lot of content on the post, with the [Footnotes Block](https://wordpress.com/support/how-to-add-footnotes/)

- [ ] 7497553-zd-a8c
Simple site, https://yourportionintorah.blog
Error occurred when saving My Site > Settings > General

- [ ] 7497918-zd-a8c
Atomic site, https://aimind.marketing waiting to hear back on where the error is occurring

- [ ] 7413957-zd-a8c
simple site, https://nofacilities.com/, affecting multiple posts and pages. Also experienced the issue reported in p2EDhh-28A-p2 and being fixed on https://github.com/Automattic/jetpack/pull/34958

### Steps to reproduce

TBD

### What you expected to happen

Posts and Pages should update regardless of the content

### What actually happened

`Updating failed. Could not update the meta value of jetpack_seo_noindex in database`

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by liviopv** [comment]
Forum threads:

- [ ] https://wordpress.com/forums/topic/seo-tab-on-jetpack-panel-disappeared/?view=all
- [ ] https://wordpress.com/forums/topic/grandfathered-account-i-pay-for-custom-domain-suddenly-cant-save-posts/
- [ ] https://wordpress.com/forums/topic/jetpack-213/?view=all

Lots of variability in the threads, lots mentions of issues with the Footnotes Block.

**Comment by csonnek** [comment]
Reported in https://wordpress.com/forums/topic/jetpack-213/?view=all

**Comment by liviopv** [comment]
- [ ] 7549704-zd-a8c
Simple site, 777doe.wordpress.com

**Comment by Aurorum** [comment]
> There's no easy way to reproduce it yet, but there are several reports in the wild

My hunch, and I might be totally wrong here, is that this affects posts where the SEO settings were edited while they were accidentally available for non-Creator plan sites, but where they can’t be accessed now.

I’m basing this off a support ticket that I encountered previously, but can’t seem to find now.

**Comment by jp-imagines** [comment]
Reported in 7566211-zd-a8c as well. Simple site, using Footnotes too.

The `jetpack_seo_noindex` message comes about after saving changes to a draft post, and the user says it may have started in December. I was able to replicate the error on a test site on a brand new post as well.

The user also noted some oddities with footnotes, though it's unclear yet if this is related. I was able to reproduce some weirdness too:

* User noted that, despite the error, changes to the post _are_ being saved. The exception is footnotes – content added in footnotes _is not_ saved. Style changes to the Footnotes block _are_ saved. (I replicated all of this as well.)
* The user noticed that after 40 footnotes, footnotes stop appearing on the post preview/published post, though they do remain in the editor. (I replicated this, though in my test post I think I encountered the `jetpack_seo_noindex` error sooner, so only one footnote actually displays on the post preview, despite there clearly being more footnotes added in the text.)
* After refreshing (or exiting & re-entering) the editor, footnotes 41+ show no content in the Footnotes block in the editor. (On my test post, all footnotes after the first disappeared in the Footnotes block, though the numbers remain in the post content. Adding a new footnote brought all the numbers back in the Footnotes block, though all footnote text was removed.)

**Comment by pauloeaquino** [comment]
7607578-zen
simple site; user's content was also working with footnotes

**Comment by SRiley-007** [comment]
I am one of the users affected.  I have never touched my SEO and this is happening on new posts.  The first occurrence was Jan. 7th on a post that was new that day. It has happened to me after publishing and when trying to save changes in draft form. 
 
 I found a forum post that suggested the workaround of deleting and reposting so have been doing that.  It does seem to be related to footnotes.  I tried to update a citation on an old post and all the footnotes disappeared.   Although tonight I got the message when I was just trying to update to fix a spelling error.

**Comment by Aurorum** [comment]
7611027-zen 

User's case on when this popped up: 

> I was trying to see how the paid subscriber access works but I'm unable to change the access to one of my blog posts back to 'everyone'

**Comment by anthcodes** [comment]
7612930-zen

**Comment by anthcodes** [comment]
7614974-zen

**Comment by staproehl** [comment]
7615425-zen

User reported receiving error when updating and publishing post. 

Awaiting confirmation on if any content changed in the post editor after the error, and if the user added footnotes.

**Comment by csonnek** [comment]
Reported in https://wordpress.com/forums/topic/posts-not-updating-3/?view=all

Asking if they're using footnotes - will update when we hear back.

**Comment by csonnek** [comment]
Reported in: https://wordpress.com/forums/topic/how-to-fix-the-wordpress-updating-failed-and-publishing-failed-errors/?view=all

Asking if they're using footnotes - will update when we hear back.

**Comment by darssen** [comment]
Merged diff D136270-code that should take care of the issue. I tested on https://jpimaginestesting.wordpress.com/wp-admin/post.php?post=2800&action=edit that was failing before and I was able to save the post.
Please check with users if they can save posts now so we can close the issue.

**Comment by khristiansnyder** [comment]
New report (I can replicate) when updating a published post. Depending on what plugins are active, the message changes but all start with `Updating failed. Could not update the meta value of`

Example: `Updating failed. Could not update the meta value of _jetpack_post_was_ever_published in database.`

The user is trying to change the subscriber access level from "anyone subscribed" to "everyone" 

Console Errors has some clues: `index.js:102  POST https://picanteysaborfood.blog/wp-json/wp/v2/posts/323?_locale=user 500 (Internal Server Error)`

#7664442-zen

**Comment by jp-imagines** [comment]
User from 7566211-zd (https://github.com/Automattic/wp-calypso/issues/86412#issuecomment-1892407366) confirmed things are working properly for them now. Definitely seems like the diff helped, though I'm not sure about the report above. 🤔

**Comment by fgiannar** [comment]
> New report (I can replicate) when updating a published post. Depending on what plugins are active, the message changes but all start with `Updating failed. Could not update the meta value of`
> 
> Example: `Updating failed. Could not update the meta value of _jetpack_post_was_ever_published in database.`
> 
> The user is trying to change the subscriber access level from "anyone subscribed" to "everyone"
> 
> Console Errors has some clues: `index.js:102 POST https://picanteysaborfood.blog/wp-json/wp/v2/posts/323?_locale=user 500 (Internal Server Error)`
> 
> #7664442-zd-a8c

@khristiansnyder Could you please check if you can still replicate the issue after @darssen 's fix above? Many thanks!

**Comment by darssen** [comment]
After trying to reproduce without luck the last report, @fgiannar smartly pointed out that the initial issue we were able to replicate and investigate should only happen in Simple and not in Atomic. And that was the one the fix was aiming for.

Since most of the cases were in Simple and there is a fix already in place for it I think it would be best to track the Atomic issue separately. Hopefully we will get some examples that we can reproduce and help with.

**Comment by darssen** [comment]
Closing this one as per above comment and the fact there has been no mentions in last 2 weeks
