### ISSUE TITLE
Theme Tiers: Rename the tiers from old to new plan names

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#86482]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/86478
- [ ] https://github.com/Automattic/wp-calypso/pull/86587
- [ ] https://github.com/Automattic/wp-calypso/pull/86528
- [ ] https://github.com/Automattic/wp-calypso/pull/86752
```
