### ISSUE TITLE
Spike: Try different drag-and-drop libraries for the Assembler large preview

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#86509]
Try different third-party libraries to implement drag-and-reorder in the Assembler large preview. 

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/86145
- [ ] https://github.com/Automattic/wp-calypso/pull/86442
- [x] react-draggable
- [x] react-beautiful-dnd
```

**Comment by taipeicoder** [comment]
Closing via pbxlJb-5s0-p2.
