### ISSUE TITLE
Refactor Task Helper > getEnhancedTask

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#86647]
# Context
The current GetEnhancedTask is very important to the onboarding process and the current state is very hard to maintain, mixing view logic with business and data logic and tracking.

So, the idea is start to improve it splitting into small parts, as part of the task Launchpad: Instrument the fullscreen Launchpad #85694.

## Migration Strategy
Since we don't have testing covering this function we are implementing it gradually migrating the tasks based on the existent flow to ensure we are not breaking them.  For now we are using feature flags by flow to enable us to smooth deploy the changes and test the approach gradually.

### Phases
Phase 1 - Migrate all flows to use the new structure
Phase 2 - Clean up the original getEnhancedTask, removing the big switch case.

```[tasklist]
## List of task definition that we need to move
- [x] setup_free #86432
- [x] setup_blog #86584
- [x] setup_newsletter #86852
- [x] design_edited  #86487
- [x] plan_selected #86494
- [x] plan_completed #86584
- [x] subscribers_added #86852
- [x] migrate_content #86852
- [x] first_post_published  #86490
- [x] first_post_publiished_newsletter #86852
- [x] design_selected #86487
- [x] design_completed #86487
- [x] setup_general  #86753
- [x] setup_link_in_bio #86667
- [x] links_added #86667
- [x] links_in_bio_launched #86667
- [x] site_launched #86491
- [x] blog_launched #86584
- [x] videopress_upload #86795
- [x] videopress_launched #86795
- [x] domain_upsell  #86490
- [x] verify_email #86852
- [x] set_up_payments #86852
- [x] newsletter_plan_created #86852
- [x] videopress_setup #86795
- [x] Clean up task-helper code #86960
```
