### ISSUE TITLE
Command Palette: PoC

### ISSUE THREAD

**Issue by dsas** [Automattic/wp-calypso#87325]
PoC testing instructions: paYJgx-4CN-p2#comment-4658

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/87193
- [ ] https://github.com/Automattic/wp-calypso/issues/87330
- [ ] https://github.com/Automattic/wp-calypso/issues/87329
- [ ] https://github.com/Automattic/wp-calypso/issues/87327
- [ ] https://github.com/Automattic/wp-calypso/issues/87328
- [ ] https://github.com/Automattic/wp-calypso/issues/87461
```
