### ISSUE TITLE
Stats: Add a query fetching UTM data

### ISSUE THREAD

**Issue by grzegorz-cp** [Automattic/wp-calypso#87567]
Following the details prepared by the Data team here panfyZ-37z-p2, create a react-query query fetching the data and passing them to the horizontal bars.

If you estimate this task taking more than two days, create new issues splitting the work.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/87810
- [ ] https://github.com/Automattic/wp-calypso/pull/87908
- [ ] https://github.com/Automattic/wp-calypso/pull/88042
- [ ] https://github.com/Automattic/wp-calypso/pull/88144
```

**Comment by a8ck3n** [comment]
Just a heads up @dognose24. The query doesn't yet work with Odyssey stats and instead results in an endless progress spinner and a 404 error. Ideally we'd handle the error too.

**Comment by dognose24** [comment]
Thanks for the reminder, @a8ck3n! The PR https://github.com/Automattic/wp-calypso/pull/87889 aims to handle the error.
