### ISSUE TITLE
Trail Map: The features grid can render categorized content while maintaining current functionality

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89682]
_Project thread: pau2Xa-5Ol-p2_

## Summary

Implements the proposed features grid of the Trail Map project. We can think of it consists of data and the required UI changes. This task will be only about the required UI changes for the features grid, while the required data change is tracked separately in #89785. 

* The feature grids will be able to render the categorized feature list. It can be a mock list here.
* The feature grids will still be able to render the current feature list.

The responsive design can be found in the following two Figma files:

* Desktop design: Uzd0AYiDAV4eFq1V35T9Ef-fi-800%3A18230
* Mobile design: Uzd0AYiDAV4eFq1V35T9Ef-fi-673_7146

For a quick reference, here is the screenshot of the proposed design:

![Image](https://github.com/Automattic/wp-calypso/assets/1842898/39214208-b779-4009-b0cf-c6a9125d5c64)

Please note that this task is **for the features grid specifically**. Any UI changes outside of the grid will be defined separately.
```[tasklist]
### Tasks
- [x] The features grid can render data in the form of `FeatureGroupMap`, as in https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/feature-group-plan-map.ts#L126
- [x] The features grid can render the same feature list as is now without being affected by the new rendering functionality.
- [x] The features grid can render a sublist, e.g. the one under "25+ pre-installed ecommerce plugins".
- [x] Move the storage section to right below the CTA button
- [x] The domain descriptor for the Free plan is simplified as "WordPress.com subdomain"
- [x] On the mobile version, all the extra space in a feature column should be removed comparing to the desktop version.
- [x] Remove the descriptor of "Everything in X plan, plus:" .
- [x] Remove the feature tooltips from the categorized features grid.
- [x] Replace the paid custom domain description as always "Free domain for one year" for the yearly paid plans in the categorized features grid and remove the boldness.
- [x] Replace the free domain description or strike-out custom domain description as always "WordPress.com subdomain" for the free plan in the categorized features grid and remove the boldness.
- [ ] https://github.com/Automattic/wp-calypso/issues/90301
```

**Comment by chriskmnds** [comment]
@southp Can you create a list of specific changes introduced in the new design? It might help to do a 1:1 comparison with the current grid and add these as requirements in a `tasklist`.

**Comment by southp** [comment]
Great call, @chriskmnds . I've added a task list above. Does it look good to you? :)

**Comment by chriskmnds** [comment]
> Great call, @chriskmnds . I've added a task list above. Does it look good to you? :)

Thanks. I think a few more that need clarity:

1. The paid/custom domain mentioned when selecting a domain and going to plans page. They are also no longer **bold**. see this PR already that makes it optional: https://github.com/Automattic/wp-calypso/pull/89800
2. The feature tooltips are meant to be removed from what I read in the P2 post. So we make those optional too.
3. The text in the term dropdown also changed
4. There's a new label above the "Enterprise" plan?
5. I would maybe also add a separate task: "Feature-group maps created and point to the updated features" (so someone can grab and start working on it)
6. We are doing a bit more with transaction fees (merging two features). This may deserve its own task to be handled separately. Maybe, but worth looking a little closer at the logic for all that.

p.s. I think tasks 2 & 3 (from your list) can be merged (they refer to same thing?)

**Comment by southp** [comment]
Great catches, @chriskmnds . Thanks for your attention to details 🙇🏼 

> 1. The paid/custom domain mentioned when selecting a domain and going to plans page. They are also no longer bold. see this PR already that makes it optional: https://github.com/Automattic/wp-calypso/pull/89800

Correct. I'll add it to the task list.

> The feature tooltips are meant to be removed from what I read in the P2 post. So we make those optional too.

You are right. @davidnerling has pointed it out here: pau2Xa-5Nw-p2#comment-15269 . I'll add it to the task list.

> The text in the term dropdown also changed

@ritagarg @vinimotaa Could we skip this change? I feel it's not relevant to this experiment. 
Here are the screenshots of the differences for a quick reference:

| Production | Figma |
| ------------|-------|
|<img width="355" alt="CleanShot 2024-04-24 at 18 40 45@2x" src="https://github.com/Automattic/wp-calypso/assets/1842898/5ccaaa3e-4d64-4ec9-bd40-bf5db2ea3f27">|<img width="485" alt="CleanShot 2024-04-24 at 18 41 26@2x" src="https://github.com/Automattic/wp-calypso/assets/1842898/cfee6053-23c6-4f87-8c0e-531533daba0f">|

> There's a new label above the "Enterprise" plan?

Could you help me point out the new label that you meant? I checked the production version and the one in Figma but can't see the difference. I might overlook something :) 

| Production | Figma |
| ----------- | ------ |
|<img width="364" alt="CleanShot 2024-04-24 at 18 37 49@2x" src="https://github.com/Automattic/wp-calypso/assets/1842898/b848ee3f-faa7-4968-98fd-816702e500fc"> |<img width="326" alt="CleanShot 2024-04-24 at 18 43 32@2x" src="https://github.com/Automattic/wp-calypso/assets/1842898/a76ef00e-e19f-42a1-8fe8-3e1883399e8e"> |

> I would maybe also add a separate task: "Feature-group maps created and point to the updated features" (so someone can grab and start working on it)

I think that's #89785 and what @ddc22 is working on right now and #89790 when it's time to really feed the data. Does the two combined match the task in your mind?  

> We are doing a bit more with transaction fees (merging two features). This may deserve its own task to be handled separately. Maybe, but worth looking a little closer at the logic for all that.

Indeed. I'm wondering if we should just create a new feature and then point to that in the new feature map, so the new feature constant can match the merged meaning better and we also won't really need to merge the two existing features. @ddc22 what do you think? looping you in here since you are now curating the new feature list :) 

> p.s. I think tasks 2 & 3 (from your list) can be merged (they refer to same thing?)

Correct. I've removed the 3rd and kept the original 2nd.

**Comment by chriskmnds** [comment]
> Could you help me point out the new label that you meant? I checked the production version and the one in Figma but can't see the difference. I might overlook something :)

@southp I was referring to the highlight label on top:

<img width="500" alt="Screenshot 2024-04-25 at 1 41 19 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/54499361-d79b-4766-98c3-0905ffc28db4">

oooh "Entrepreneur", not "Enterprise" - sorry 😬

**Comment by southp** [comment]
> oooh "Entrepreneur", not "Enterprise" - sorry 😬

Great catch. I've added one checklist item for it.

**Comment by southp** [comment]
I'm closing this issue since all the main tasks have been completed, and the one remaining is now tracked as a follow-up issue here: https://github.com/Automattic/wp-calypso/issues/90301
