### ISSUE TITLE
Trail Map: Call for Test

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89687]
Project thread: pau2Xa-5Ol-p2

## Summary
Once all the development tasks within the 1st milestone are completed, do an internal call for test among the primary stakeholders and address any feedback from it. Since this feature is at the experimenting stage, we won't follow the official CFT process, but only do a smaller scale CFT to make sure the feature is implemented as expected and to identify if there is any issue we don't know at the planning stage.

Note that we should start working on the 2nd milestone https://github.com/Automattic/wp-calypso/milestone/477 while running this internal test.

```[tasklist]
### Tasks
- [x] Publish a call-for-test post in the martech p2, citing the stakeholders listed in the project thread linked above.
- [x] Triage the received issues
- [x] Address only the critical ones within the 1-week time frame.
```

**Comment by southp** [comment]
The internal test has been completed, so I'm closing this.
