### ISSUE TITLE
Trail Map: The ExPlat experiment design is completed

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89688]
Project thread: pau2Xa-5Ol-p2

## Summary

The ExPlat experiment design is completed, i.e. the ExPlat instance is completed, and the accompanied a8cexperiment design post is published. Per decision made in pau2Xa-5Nw-p2#comment-15362, we will need two ExPlat instances, one for the desktop experiment, and one for the mobile experiment.
```[tasklist]
### Tasks
- [ ] The ExPlat instance for the desktop experiment is created on Abacus
- [ ] The ExPlat instance for the mobile experiment is created on Abacus
- [ ] The a8cexperiment post is published
```

**Comment by southp** [comment]
The experiment has been published here: pbxNRc-3ET-p2
