### ISSUE TITLE
Trail Map: code clean-up

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89692]
Project thread: pau2Xa-5Ol-p2

## Summary

This task is in general the execution phase of what we conclude from #89691 . It should consist of the following, but not restrict to:

- [ ] Implement the deploying plan concluded in #89691.
- [ ] Clean up the A/B test code introduced in #89689.
- [ ] Clean up the feature flag introduced in #89686.
