### ISSUE TITLE
Trail Map: Launch the A/B test

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89690]
Project thread: pau2Xa-5Ol-p2

## Summary

Launch the completed A/B test. Make sure to double confirm the end date with the stakeholders. This task will depend on #89688 and #89689 to complete.
```[tasklist]
### Tasks
- [x] Decide on the end date
- [x] Launch the desktop experiment from Abacus
- [x] Launch the mobile experiment from Abacus
```

**Comment by southp** [comment]
It's been launched per pbxNRc-3ET-p2#comment-5520 so I'm closing this issue.
