### ISSUE TITLE
Remove processing step: Create a new instructions step

### ISSUE THREAD

**Issue by andres-blanco** [Automattic/wp-calypso#89760]
# Goal
Show the pre-migration steps progress directly on the site migration instructions.

The overall idea is to show a list of processes we are running as part of the site instructions, and only make the site migration key available when all of them are done.

## Context
After we launched the new site migration flow, we noticed users were dropping off the flow, on loading screens before seeing the instructions page. We want to remove the loading steps and show them directly on the instruction page the -pre-migration progress. 

More details on paYKcK-4qU-p2
The initial idea is to have something like this, but it is still totally open to other suggestions.

![image](https://github.com/Automattic/wp-calypso/assets/38718/8b3b54ed-6f65-44b9-bc02-a6307458d9c4)

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/90086
- [ ] https://github.com/Automattic/wp-calypso/pull/90092
- [ ] https://github.com/Automattic/wp-calypso/pull/90097
- [x] Implement hook to manage the plugin installation, site transfer
- [x] #90143
```

**Comment by javierarce** [comment]
Here's a proposal for the step based on the wireframe above:


https://github.com/Automattic/wp-calypso/assets/4933/da0c3d6d-60e8-4b45-b6ce-96387aff5ffb


Figma file: 5yhaC6umexdQLlLpCrCyEe-fi-2982_3021
