### ISSUE TITLE
Trail Map: Create the feature categorization and update the feature list according to the design.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#89785]
### Details

Project thread: pau2Xa-5Ol-p2

## Summary

In the proposed design: Uzd0AYiDAV4eFq1V35T9Ef-fi-800%3A18230, there are new features added and we need to 
This task is for 

Once https://github.com/Automattic/wp-calypso/issues/89682 is completed, we should be able to feed the data defined here  directly into the feature grids.

## Caveats

* The `$1,500` copy will be just static: pau2Xa-5Om-p2#comment-15329
* There is a sublist under `25+ pre-installed plugins`. If it adds much complexity, we can leave it as a follow-up and starts with a flattened map.
* We don't have to send all the new strings for translation for now since we are aiming at an en-only group. However, it's still required to wrap all the string by localization functions properly.

### Checklist

- [ ] Add all the new features to the feature list, i.e. https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/features-list.tsx
- [ ] Create the new feature groups like: https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/feature-group-plan-map.ts#L126
- [ ] The original feature list that the current plans grid is using should be intact.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/pull/89927
- [ ] https://github.com/Automattic/wp-calypso/pull/89999
- [ ] https://github.com/Automattic/wp-calypso/pull/90077
- [ ] https://github.com/Automattic/wp-calypso/pull/90135
- [ ] https://github.com/Automattic/wp-calypso/pull/90195
```

**Comment by ddc22** [comment]
Created an audit of feature variables as it exists in our current feature code

https://github.com/Automattic/wp-calypso/blob/221022601ce19963cd7ec37e4a827633005a2a02/packages/calypso-products/src/features-list.tsx

https://docs.google.com/spreadsheets/d/1Bz8W76rR-_q_osFIhx9Lsc5n_BJN5FIQ/edit#gid=1929114643

**Comment by chriskmnds** [comment]
> There is a sublist under 25+ pre-installed plugins. If it adds much complexity, we can leave it as a follow-up and starts with a flattened map.

It doesn't sound like an issue. We can introduce a new generic property to `FeatureObject` -> `getSubtitle` (or something more specific - but not "experiment specific") and call it from the grid where we render feature cells. It should be of a generic nature that the grid can hopefully just call unconditionally.

p.s. left some thoughs/impressions in the related PR: https://github.com/Automattic/wp-calypso/pull/89883#pullrequestreview-2022062162 . Quoting here for reference:

> I am concerned about redefining feature structures and selectors this way. We shouldn't be creating these weird maps for standard things like titles/slugs/descriptions/etc every time something needs to be experimented.
> 
> This is the plan/direction I'd have expected (in this order):
> 
> 1. Use existing feature slugs/definitions
> 2. Update existing feature definitions to match where it makes sense
> 3. Set the experiment flag in `calypso-products` (there is provision for that) and conditionally return titles/descriptions if you need to
> 4. Create new feature slugs/definitions for new things
> 5. Any new property added to `FeatureObject` should be strictly generic (not experiment-specific), unless there is absolutely no other way

**Comment by southp** [comment]
I'm closing this as all the tasks have been closed by respective PRs :)
