### ISSUE TITLE
Tracking: Refactor my-sites/sidebar & remove reference to sitesList.getSelectedSite

### ISSUE THREAD

**Issue by spen** [Automattic/wp-calypso#9054]
The 'my-sites/sidebar' component uses `sitesList.getSelectedSite()` after it has been descended from it's parent component, #8726 looks to remove all references of this method throughout the project.  

While looking to make the change needed for #8726 I noticed that some general updates would be worth while so I've started by first cleaning up the 'my-sites/sidebar'.
I'll then make the actual change needed (the removal of `sitesList.getSelectedSite`)

- [ ] Rename all jsx rendering methods to renderThing [naming convention](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#react-method-names) ( #9032 )
- [ ] Transition `requires` to `imports` & `var`s to `const`s & `let`s ( #9032 )
- [ ] Add better test coverage of existing component (To make changes with confidence)
- [ ] Create new methods that check whether sidebar menus are to be rendered
- [ ] Add test coverage for the new methods
- [x] Refactor to use ES6 class, extending React.Component (#9177)
- [ ] Rename sidebar.jsx (main component) to index.jsx
- [ ] Remove sitesList.getSelectedSite()

I'm also keen to explore the 2 remaining lint warnings...
- Use localize( ReactComponent ) instead of this.translate (`i18n-no-this-translate`)
- className should follow CSS namespace guidelines (`jsx-classname-namespace`)

As well as breaking out some of the jsx partials in to SFCs, but those changes would be much more involved and out of the scope of this change I think :)

**Comment by spen** [comment]
A note-to-self to make sure I address @gwwar 's comment here: https://github.com/Automattic/wp-calypso/pull/9177/files#r87854987

**Comment by spen** [comment]
Closing as work on #13196 Seems to supersede this :)
