### ISSUE TITLE
Plans Next [Storybook]

### ISSUE THREAD

**Issue by oswian** [Automattic/wp-calypso#90824]
This issue serves as a centralised location for tasks & discussion related to Storybook for the plans components:

ie. `PlansFeaturesMain`, `FeaturesGrid`, `ComparisonGrid`, `SpotlightPlan`, etc

![CleanShot 2024-05-17 at 12 16 18@2x](https://github.com/Automattic/wp-calypso/assets/69198925/ebcf5131-d0f1-4462-98a8-6ef6aece8de2)

When creating a new issue:
  - Apply the label `Plan Next [Storybook]`
  - Add a link to the task list below

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/wp-calypso/issues/90826
- [ ] https://github.com/Automattic/wp-calypso/issues/90828
- [ ] https://github.com/Automattic/wp-calypso/issues/90825
- [ ] https://github.com/Automattic/wp-calypso/issues/88988
- [ ] https://github.com/Automattic/wp-calypso/issues/88987
- [ ] https://github.com/Automattic/wp-calypso/issues/88936
- [ ] https://github.com/Automattic/wp-calypso/issues/88935
- [ ] https://github.com/Automattic/wp-calypso/issues/88934
```

**Comment by chriskmnds** [comment]
@oswian I think there may be a bug with the sticky headers in Storybook. Something to do with background/indexing I guess. Can you confirm and add an issue to the list? (img below)

<img width="600" alt="Screenshot 2024-05-17 at 1 08 44 PM" src="https://github.com/Automattic/wp-calypso/assets/1705499/699aa35e-4f59-4e22-8fa2-bb8603b95962">
