### ISSUE TITLE
Stepper: move step navigation tracking into the framework

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wp-calypso#91755]
### Details

At present, every Stepper flow needs to add its own logic to send step submission events to Tracks inside the `submit()` function that is returned from the `useStepNavigation()` hook.

This means that the events are not 100% consistent, and are completely missing for some flows because the developers didn't know this was something they needed to implement.

Edit: @alshakero, fire events on all the events that are Stepper is aware of (`submit`, `goBack`, enter flow, leave flow, etc..).

### Checklist

- [x] Add step navigation-controls tracking to the Stepper framework and ensure all current/future flows opt-in
  - [x] `submit` handled at framework
  - [x] `goBack` handled at framework
  - [x] `goNext` handled at framework
  - [x] `exitFlow` handled at framework

**Comment by daledupreez** [comment]
FYI, @alshakero - this may be something Vertex can pick up before Serenity can get to it.

**Comment by chriskmnds** [comment]
I'll be looking into this

**Comment by alshakero** [comment]
Thank you so much for taking care of this, Christos. It's educational to review your PRs.

I think we should fire an event, even if a new event, on `goBack` and even the deprecated `goNext` functions. I think it's all upside and ensure consistency. WDYT? 

I dislike that we rely on `NavigationLink` for events and not something more centralized, but as you said, it's not worth the refactor. Having redundant events on all `useStepNavigation` outcomes sounds like a good deal.

**Comment by chriskmnds** [comment]
Done as of https://github.com/Automattic/wp-calypso/pull/93854
