### ISSUE TITLE
Map Plans:  Map unmapped plans from Stripe to Site plans

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93155]
We want the user to map the current Stripe Subscription Plans to the ones that we show users on the site. 

<img width="1138" alt="Screenshot 2024-07-31 at 6 04 29 PM" src="https://github.com/user-attachments/assets/88179b72-dd8b-4d5f-a379-bfbf226d1b2f">

### Tasks 

- [x] Display the user the current Stripe Subscription Plans 
- [x] Allows them to skip this step 
- [x] Allow the user to create new Plans that match the Stripe Subscription Plans

Design: p9Jlb4-dhi-p2
Figma: [ZdugJ99VXJszZRSBfMNre4-fi-5017_32894](https://href.li/?https://www.figma.com/file/ZdugJ99VXJszZRSBfMNre4/?node-id=5017-32894)
