### ISSUE TITLE
Stripe Connection

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93154]
We want the user to be able to connect to Stripe in the Paid Importer flow. 

![Image](https://github.com/user-attachments/assets/399b3920-cc9b-4260-bcbc-ed6788f29e3c)

### Tasks

- [x] We should show the user the stripe connection if they are not connected already. 
- [x] We should allow them to skip this step but show them a warning that we can't import paid subscribers. 
- [x] We should show them a progress bar or an indicator if the connection is not valid or complete. 

Design: p9Jlb4-dhi-p2 
Figma: ZdugJ99VXJszZRSBfMNre4-fi-5017_32894
