### ISSUE TITLE
Migrate Current Stripe Subscriptions to Site Subscriptions

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93157]
This part is a bit of a hidden step and doesn't have much UX. Since a lot of the work happens on the backend. 

![Image](https://github.com/user-attachments/assets/40058648-c6f7-48c3-8bb7-dfdf04e52f32)

### Tasks
- [x] We should shows the user after they have added the correct plans and have imported a list of subscribers (csv file) that they can. The task that we will do. 
- [x] We should only allows them to continue after we have confirmed that will disconnected substack. 
- [x] Show them a progress bar and the completed step. 

Design: [p9Jlb4-dhi-p2](https://href.li/?https://wp.me/p9Jlb4-dhi)
Figma: [ZdugJ99VXJszZRSBfMNre4-fi-5017_32894](https://href.li/?https://www.figma.com/file/ZdugJ99VXJszZRSBfMNre4/?node-id=5017-32894)
