### ISSUE TITLE
Messaging: Update Import content email

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93166]
This is what we currently show users after they import substack content. 

![Image](https://github.com/user-attachments/assets/04da9385-474f-44b9-b809-d00eccd76f8c)

It leaves much to be desired. A nicer design, a summary of what they imported. 

We should have an idea of where the site was impoted from. We could give them links to inspect the content that they just imported. 

### Task 
- [ ] Design a new import email. 
- [ ] Implement the new design. 
- [ ] Include things to help support if someone replies to from this email. So that we can debug things more.

**Comment by simison** [comment]
These now have new templates for both Jetpack and WP.com.
