### ISSUE TITLE
Docs: Update the documentation around the stripe importer

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93169]
This is the current documentation 
https://wordpress.com/support/import-from-substack/

### Tasks 

- [x] Update it so that it matches the new paid importer.
- [ ] Add single button from so it can be a new entry point. 
- [ ] Improve the SEO of that page so when you google Import Substack to WordPress it shows up at the top? ( This seems to currently be the place?
- [ ] Create a quick video of the new import flow. With good reasons for folks to switch.  
1. You own the platform. 
2. Monitize it at your reduced rate. 
3. Monitize it though other ways. ( Ads ) 

- [ ] Add an announce post to .en blog 
- [ ] Post about it on other communities for substack such as reddit or substack itself

**Comment by simison** [comment]
Internal reference to docs issues, tracked in:

- 2991-gh-Automattic/en.support-docs-content
- 2990-gh-Automattic/en.support-docs-content
- 2978-gh-Automattic/en.support-docs-content

Internal announcement p7DVsv-lJy-p2
