### ISSUE TITLE
Backend: Keep track of state of the flow in a new state machine endpoint

### ISSUE THREAD

**Issue by enejb** [Automattic/wp-calypso#93170]
We need to create a couple of new endpoint that will can use to work as a state machine for this importer. 

Then we can use to display the progress of it. 

The state machine would include the current content importer state machine as well as the any state of the subscription importing. 

### Tasks

- [x] Investigate if this is the right approach. 
- [x] Add an endpoint that returns the state of the importer flow. 
- [x] Add an endpoint to update the state of the flow based on what happends in the jobs as well as when the user clicks around (skips steps) this should be reflected in the state machine. 
 the main idea is that we can use the endpoint to display all the different state of the importer.

**Comment by enejb** [comment]
We started work on this in D158054-code
