### ISSUE TITLE
Review if the steps tracking are working properly

### ISSUE THREAD

**Issue by renatho** [Automattic/wp-calypso#93527]
### Details

Review if the steps tracking are working properly. It should have the expected behavior in `/setup/migration` and in `/setup/hosted-site-migration` when the [feature flag](https://github.com/Automattic/wp-calypso/issues/93345) is enabled.

As part of this issue, we can also review the core signup events. pfuQfP-GU-p2#comment-1148

### Checklist

- [ ] Tracking events working properly on `/setup/migration`.
- [ ] Tracking events working properly on `/setup/hosted-site-migration`.
- [ ] Review core signup events and ask for help if needed.

**Comment by gabrielcaires** [comment]
We need to implement the  #93531

**Comment by gabrielcaires** [comment]
> Review core signup events and ask for help if needed.

It was already solved by #93484 

> Tracking events working properly on /setup/hosted-site-migration.

It depends on the feature flag solution.

**Comment by gabrielcaires** [comment]
| Event | Status |
|--------|--------|
| calypso_signup_step_start | ✅ |
| calypso_signup_actions_submit_step | #93771 |
| calypso_signup_start | ✅  |

**Comment by renatho** [comment]
https://github.com/Automattic/wp-calypso/pull/93771
