### ISSUE TITLE
Cancel Subscription: UI components need polish and consistency

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#93601]
## Description

![Image](https://github.com/user-attachments/assets/153102eb-a0a7-4846-9c85-e7eb6266b9f8)

* The active state of the checkbox is black and filled, which is inconsistent with the rest of Calypso.

![Image](https://github.com/user-attachments/assets/4423f633-12ac-45e6-902c-b0242efb1bee)

* The active state of the button doesn't have the top/button outline.

```[tasklist]
### Tasks
- [ ] Fix checkbox active state
- [ ] Update outline for active state of button
- [ ] Left align everything on the page
```

**Comment by davemart-in** [comment]
It also feels odd that half of this page is center aligned and half of it is left aligned.

Related PR: https://github.com/Automattic/dotcom-forge/issues/8751

**Comment by BogdanUngureanu** [comment]
Are we sure we want to align the items on the left? Looking at the other pages the text is centered
https://github.com/user-attachments/assets/bb56295c-6062-4b46-932f-fc421662899d

**Comment by javierarce** [comment]
> @javierarce any thoughts? :)

@BogdanUngureanu We should center the content, that's the approach we follow in these types of pages, but I'll review this screen and add a complete proposal.

**Comment by javierarce** [comment]
Ok, I've reviewed the cancellation flow and have some suggestions for aligning the steps with the style of our onboarding pages. 

Please let me know what you think and if they are within the scope of this issue or if you would prefer me to create a new one.

I'll describe the most important changes here, but the full proposal is in this Figma file: wCm5Tzb7JBaG4WNowWbjES-fi-5155_34706.

![image](https://github.com/user-attachments/assets/eeb4b153-1de7-45ec-a175-610e9f50463d)

1. The link is underlined, and the icon has been removed.
2. The style of the header matches that of other onboardings.
3. The label and dropdown style is similar to the onboardings.
4. The submit button is enabled to follow the same pattern as on the login page, where we always show its primary state and display a message if the user submits an empty form.
5. The content width has been reduced.

![image](https://github.com/user-attachments/assets/e1a6542e-cfba-4463-9ba4-d85baa0f0aca)

6. Error state for the form

![image](https://github.com/user-attachments/assets/6d6c0392-586a-4988-855c-b8355092216a)

7. The header style matches other onboardings; the badges use the new style.
8. The cards don't have a shadow and look similar to the ones in the goals screen.
9. We use a notice with a shorter text so it fits one line.
10. Since this action is destructive and critical, in this case, we display the disabled button state.
11. To accommodate more text, the width of this step is wider than the previous ones.

**Comment by BogdanUngureanu** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/95991
