### ISSUE TITLE
Reader Stream Refresh: post-launch code cleanup

### ISSUE THREAD

**Issue by bluefuton** [Automattic/wp-calypso#9364]
This is a list of old functionality that can be moved or removed after the new Reader Stream Refresh launches to everyone.

- [x] Remove `reader/daily-post` (now in blocks) #10103 
- [x] Remove create-better-excerpt-refresh rule in post normalizer (https://github.com/Automattic/wp-calypso/pull/10486)
- [x] Remove old post card from `reader/stream`
- [x] Remove any 'Refresh' naming from `reader-post-card` block #10171
- [x] Remove any 'Refresh' naming from Devdocs (e.g. http://calypso.localhost:3000/devdocs/blocks/refresh-cards) #10171
- [x] Delete `client/reader/search-stream/blank.jsx` and associated logic #10214 
- [x] Remove `reader/stream-header` #10152
