### ISSUE TITLE
Stepper: Allow flows to extend the props passed to all the framework Tracks events

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/wp-calypso#94108]
### Details

This is one of the improvements outlined in the PT (pdDR7T-1BF-p2) as agreed on by several folks -> a provision for flows to centrally override or include more properties for all the framework-level Tracks events. These include step-navigation, `calypso_signup_start`, `calypso_signup_step_start`, `calypso_stepper_flow_start`, and `calypso_page_view`.

### Tasks

```[tasklist]
### Provision for flows to extend the events handled by Stepper.
- [ ] https://github.com/Automattic/wp-calypso/pull/93273
- [ ] https://github.com/Automattic/wp-calypso/pull/93854
- [ ] https://github.com/Automattic/wp-calypso/pull/93941
- [ ] https://github.com/Automattic/wp-calypso/pull/93983
- [ ] https://github.com/Automattic/wp-calypso/pull/94131
- [ ] https://github.com/Automattic/wp-calypso/pull/94229
```

```[tasklist]
### Ensure consistency with use of provision (`useTracksEventProps`)
- [ ] https://github.com/Automattic/wp-calypso/issues/93808
- [ ] https://github.com/Automattic/wp-calypso/issues/94175
```

**Comment by chriskmnds** [comment]
I think we are all wrapped up here. The direction to restrict the various events from being recorded more than once, makes this "extension mechanism" a lot less viable for introducing either state or async properties into the loggers (as any such dependencies would need to be ignored). A different mechanism could have worked better, but we haven't come up with anything worth pursuing. 

See discussions in https://github.com/Automattic/wp-calypso/issues/95106, https://github.com/Automattic/wp-calypso/issues/94175, https://github.com/Automattic/wp-calypso/pull/94248#discussion_r1745992249, or https://github.com/Automattic/wp-calypso/pull/93983, or ping me for a summary.
