### ISSUE TITLE
Top-level dashboard: Headings are not aligned/inconsistent

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/wp-calypso#94950]
While browsing between Sites, Domains, Plugins and Themes menus in the Sites Dashboard, you'll notice that the heading margins and size are not consistent

https://github.com/user-attachments/assets/38996be6-76fe-413f-8827-68bcee620dce

```[tasklist]
### Tasks
- [ ] Update the Domains page to look more like sites
- [ ] Update Plugins page to look more like sites
- [ ] Update Themes page to look more like sites
```

**Comment by m1r0** [comment]
Hey @BogdanUngureanu! I saw your issue and decided to jump in after doing a related [fix](https://github.com/Automattic/wp-calypso/pull/99415) as part of the domains revamp project. I hope you don't mind.

**Comment by BogdanUngureanu** [comment]
hey @m1r0! No worries, go ahead. :) I'm not sure how up to date is this issue anymore. There were a lot of changes made to the dashboard lately. :)
