### ISSUE TITLE
Signup: Deprecate the concept of reskinned flows.

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#95419]
### Details

The reskinned flow was introduced several years ago by the "Reskinned Signup Flow" project led by @niranjan-uma-shankar : pbxNRc-IO-p2. Now that it's basically the new default, we should deprecate that concept in code and make it the default behavior.

### Checklist

- [x] Deprecate `isReskinned` property, making the related behavior when it's true the default
- [x] Deprecate the reskinned flow configuration, i.e. `reskinned_flows` in `_shared.json`
- [x] Deprecate the overall usage of the terminology, e.g. in CSS and component names.

### P2 discussions
- pdvytD-Yh-p2
- pdvytD-Yw-p2

### Tasks
- #98561
- #99112
- #99264
- #99440
- #99506
- #99354
- #98513
- #99572
- #99690

**Comment by southp** [comment]
With the deployment of https://github.com/Automattic/wp-calypso/pull/99690, I believe we can close this now. Thanks for the amazing janitorial effort, @ddc22 :)
