### ISSUE TITLE
Task: implement new tracks events

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#95644]
### Details

Ensure events and props are set up to make the best use of tracks tools.

Slugs of the new goals are in  https://github.com/Automattic/wp-calypso/blob/4ddc094d2bc2649831886e5bcb2e02d18575bed0/packages/data-stores/src/onboard/constants.ts. We can use these for the prop values.

We should check in with other teams who know the most up to date info on signup/stepper events.

### Existing Events

`calypso_signup_goals_select` captures both goals and intent and we can continue to use this tracks event.

Signup and stepper flows have a number of tracks events conventions that we will (or may) want to respect. For example:
* `calypso_signup_step_nav_next`
* `calypso_signup_skip_step`
* `calypso_stepper_flow_start`

### Tasks
- [ ] All new goals should be tracked.
- [ ] Understand the current state/usage of `calyspo_signup_*` and `calypso_stepper_*` with other teams (Lego, Letero, others?) who have worked on tracks events in onboarding.
- [ ] Import, DIFM should be tracked. This may need a new event. TBD
- [ ] Skip to WP admin
- [ ] Skip in top right should be tracked
- [ ] New event that captures goals selected as single props (not an array) `calypso_signup_goal_individual_select` (is there a better name? Naming things is hard.)   This will need to run in a loop to capture the goal as a prop for every goal the user selected on _exit from the screen_.  The purpose of this is to making viewing most popular goals easy via tracks trends tools.

**Comment by zaguiini** [comment]
## Existing behavior

### ✅ "Next" button fires the submit step - `calypso_signup_actions_submit_step` gets fired

![Image](https://github.com/user-attachments/assets/9dab6352-dfe0-4dbb-8f41-45214778fccf)

### ✅ Skip in the top right should be tracked - `calypso_signup_skip_step` gets fired

![Image](https://github.com/user-attachments/assets/af5abf25-9dd9-4cbb-bef2-5378282d78a5)

### ✅ Import should be tracked - `calypso_signup_intent_select` gets fired with `intent: import` as a property

![Image](https://github.com/user-attachments/assets/99400a5d-8be1-4c85-90e4-f396dcd9da9e)

### ✅ DIFM should be tracked - `calypso_signup_intent_select` gets fired with `intent: difm` as a property

![Image](https://github.com/user-attachments/assets/309995a6-9bd8-47c0-9bb2-a896e75ebe49)

### ✅ Skip to dashboard should be tracked - `calypso_signup_intent_select` gets fired with `intent: build` as a property

![Image](https://github.com/user-attachments/assets/dde3f997-b13e-4d22-b776-89bf8805e7e4)

## Missing behavior

### ❌ All new goals should be tracked

Some instances fail because property names must be alphanumeric:

![Image](https://github.com/user-attachments/assets/858e859d-f6b5-41ac-8eff-840a5fb12280)

🤔 But the failing thing being "property names" indicates that we are already saving the individual selections as asked in the "New event that captures goals selected as single props" task. In fact, looking on [Tracks](https://mc.a8c.com/tracks/events/event.php?eventname=calypso_signup_goals_select) we can see just that:

![Image](https://github.com/user-attachments/assets/db9ecd50-bb33-490d-9e6b-3699bd6ae1f3)

QUESTION: Do we still want to create a separate event that orders the goal nicely?

---

## Other considerations

### ❓ Do we want to record both "goals" AND "intent" in Next/Skip click?

[In our PR](https://github.com/Automattic/wp-calypso/pull/95707/files#diff-2764afbe5d4ae56ee33a59c3305eaefe05f2732bea27a6447812b7cdf3798083R97-R123), we're firing both the `goals_select` and `intent_select` if the user clicks Next or Skip.

But that doesn't feel right to me, based on my current knowledge: 
- we want to treat "DIFM" (`difm`), "Import" (`import`) and "Skip to dashboard" (`build`) as _intents_, not goals. Thus, picking one of these options should register the _intent_select_ Tracks event exclusively
- selecting goals and clicking "Next" should register, exclusively, the _goals_select_ Tracks event
- clicking the top-right "Skip" button should register _neither_, as the user did not select anything (and even if they did select and clicked "Skip", they're signalizing they're not interested in the goals, so why record it? Might lead to false positives.

Is that right? Is that wrong?

cc @p-jackson @wongasy

**Comment by wongasy** [comment]
>Do we still want to create a separate event that orders the most popular goals nicely?

As you had correctly pointed out, the goals is being tracked tracked as individual properties of the `calypso_signup_goals_select` event, there's no need to create a separate event for individual goal tracking. In fact, the existing logic is quite smart that it records the order of goal selection! For example, If I selected “Promote myself or business” as my second goal, the property will reports as `promote: 2`.

>Do we want to record both "goals" [`calypso_signup_goals_select` event] AND "intent" [`calypso_signup_intents_select` event] in Next/Skip click?

There's certainly redundancies in reporting both `calypso_signup_goals_select` and `calypso_signup_intent_select` events. It looks like `calypso_signup_goals_select` has already given us all the information we need, including intent.

Unless I'm missing something here, the only difference is that `calypso_signup_intent_select` includes an `import` property, which is set to `true`, if the intent is `import` and `false` otherwise. 

Given we can derive `import` from the `intent`, the `import` property isn't really needed, unless there's _some_ combination or order of goal selection that sets `import` to `true` even when the intent is _not_ `import`. @daledupreez Do you have any insights to the rationale for reporting both `calypso_signup_goals_select` and `calypso_signup_intent_select` from a migrations perspective?

All that said, I'm inclined to tolerate the redundancy and keep both events for now, since we don't know which event is being used to drive existing dashboards or looker data. There might be use cases that we're not aware of.

>clicking the top-right "Skip" button should register neither, as the user did not select anything. 

I would suggest reporting `calypso_signup_goals_select` with goals (empty if none were selected) and intent `unknown`. It'll be easier to set up funnels if we keep event reporting consistent.

**Comment by zaguiini** [comment]
>Given we can derive import from the intent, the import property isn't needed, unless there's some combination or order of goal selection that sets import to true even when the purpose is not import. @daledupreez Do you have any insights to the rationale for reporting both calypso_signup_goals_select and calypso_signup_intent_select from a migrations perspective?

@wongasy with our new changes, it won't be possible to derive the `Import` or `DIFM` intent from the selected goals, now that we're separating goals and intents and DIFM and Import aren't selectable options in the goals grid:

![Image](https://github.com/user-attachments/assets/2a4488be-aa5e-455f-895d-a6a50bf290d2)

That's why I'm confused, because within our code changes, `handleNext` which accounts for Next/Skip, is also recording the calculated intent, while the other three buttons at the bottom of the page (screenshot above) are exclusively reported as intents, not recording the goals (see empty array):

![Image](https://github.com/user-attachments/assets/beff2e7b-3022-4e39-b370-e1f73ea8032f)

The thing that makes it not only redundant but (mostly importantly) ambiguous is that the `handleDashboardClick` function is setting the intent as `Build`, which is also a possible derived result from the `goalsToIntent` function. So we might be missing a way to differentiate a "Skip to dashboard" click vs. goals selection that might result in the `Build` intent.

Is that clearer now?

**Comment by wongasy** [comment]
Ah, thanks @zaguiini for reminding me of the important fact that the new screen doesn't allow DIFM / Import to be part of the multi-goal selection! 

If I'm not mistaken, is this your proposal? 

|Button clicked|Track `calypso_signup_goals_select`|Track `calypso_signup_intents_select`|`goals`|`intent`|
|--------------|-------|-------|-------|--------|
| Next | Yes | No | selected goals | calculated from selected goals |
| Import or migrate an existing site | No | Yes  | empty | `import` |
| Let us build a custom site for you | No | Yes | empty | `difm` |
| Skip to dashboard | No | Yes | empty | `build` |
| Skip | No | Yes | empty | `build` |

**Comment by zaguiini** [comment]
Almost, @wongasy! The only thing that isn't aligned with my proposal is that `Skip` will behave the same as `Next`. `Skip` and `Next` fire the same `handleNext` callback, so it will record the same goals and calculate the same intents.

From a usability perspective, it doesn't make sense to pick goals and click "Skip," but that can happen. That part is a bit confusing to me, as we can see above 😅 I like your proposal, too, with the difference that "Skip" wouldn't fire the `calypso_signup_intents_select` event either (as they've skipped the screen, therefore we don't know anything about their preferences.)

**Comment by wongasy** [comment]
>I like your proposal, too, with the difference that "Skip" wouldn't fire the `calypso_signup_intents_select` event either

@zaguiini Actually, there's a flow in the table where there's no way to differentiate between "Skip" and "Skip to Dashboard".  Based on your [previous comment](https://github.com/Automattic/wp-calypso/issues/95644#issuecomment-2449934820), we can't report an `unknown` intent due to restrictions from the intent resolver. Can we report empty intent though? If so, then we can adjust the setup as follows (changes italicized in bold):

|Button clicked|Track `calypso_signup_goals_select`|Track `calypso_signup_intents_select`|`goals`|`intent`|
|--------------|-------|-------|-------|--------|
| Next | Yes | _**Yes**_ | selected goals | calculated from selected goals |
| Import or migrate an existing site | No | Yes  | not applicable | `import` |
| Let us build a custom site for you | No | Yes | not applicable | `difm` |
| Skip to dashboard | No | Yes | not applicable | `build` (assumed based on user's desire to go to the dashboard) |
| Skip | No | Yes | not applicable | _**empty**_ |

The above set up should allow us to perform data analysis as follows:
* **A breakdown of user intents** - Segment `calypso_signup_intents_select` events by `intent` property. Note: This is made possible by tracking `calypso_signup_intents_select` when users click on "Next".
* **A breakdown of user goals** - Segment `calypso_signup_goals_select` events by `goals` or individual goal properties.
* **Users with no interest in sharing goals/intent** - Users associated with `calypso_signup_intents_select` events with empty `intent`.
* **Isolate users who clicked on "Skip to dashboard"** - Users associated with `calypso_signup_intents_select` events with `build` intent, and _not_ associated with any `calypso_signup_goals_select` event in the same onboarding session.

**Comment by autumnfjeld** [comment]
>  That's why I'm questioning the record intent if clicking Skip/Next. 

Historically we have treated "skip" as going to the standard build flow (as opposed to the sell or write flow).  That is why intent=build has been recorded with skip. 

Intent has evolved to represent "flow", yes it is confusing,....it just evolved that way.

**Comment by autumnfjeld** [comment]
@zaguiini @p-jackson    

This event calypso_signup_actions_submit_step needs values for the `action` prop. 
Here I think we can interpret `action` to mean the button/link (not flow or intent or goal), although we can use similar slugs as intent or goal on import and difm links.

Here are my suggestions:

Next (previously Continue) click -> `action: next`
Import/migrate click  -> `action: import`
DIFM click  -> `action: difm`
Skip to dashboard click ->  -> `action: dashboard`
Skip (top right) click ->  -> `action: skip-goals`


Later when we change `Skip to dashboard to "Skip to wp-admin" we can use `action: wp-admin` if that makes sense (TBD).

**Comment by zaguiini** [comment]
Do we need that change @autumnfjeld? We already have the Tracks events to infer these actions as pointed out in the [test instructions of the PR](https://github.com/Automattic/wp-calypso/pull/95707).

**Comment by autumnfjeld** [comment]
Just to follow up and summarize from a call @zaguiini  and I had:  it is useful to plan events and props in a way that suits the functionality of our tracks tools.   So adding the `action` prop (which already exists for `calypso_signup_actions_submit_step`) makes it easy to get an at-a-glance view of all the click actions on the Goals screen via tracks trends or sample values for the property `action`.   For this event, the `step` prop must be `goals`.

This also solves for what @wongasy caught: not being able to differentiate between "Skip" and "Skip to Dashboard"

![Image](https://github.com/user-attachments/assets/52fbd0c4-eeb3-4520-a6ad-0cde231b7cbc)


Note that the second graph view is possible due to a new tracks feature (or new to me)! Trends can now be filtered by one prop, and then segmented by a second prop.   Which I just now learned how to use. 

Unfortunately currently in production  `calypso_signup_actions_submit_step` wasn't set up on the goals screen to use the action prop.   Maybe because there were only two clicks possible (Continue and Skip) and skip has its own event `calypso_signup_skip_step`.
