### ISSUE TITLE
Auditing Upsells: Removing Low-Performers

### ISSUE THREAD

**Issue by taipeicoder** [Automattic/wp-calypso#95738]
P2: pbxlJb-6wX-p2

### Tasks
- [x] https://github.com/Automattic/wp-calypso/pull/95737
- [x] https://github.com/Automattic/wp-calypso/pull/95743
- [x] https://github.com/Automattic/wp-calypso/pull/95741
- [ ] https://github.com/Automattic/wp-calypso/pull/95745
- [x] https://github.com/Automattic/wp-calypso/pull/95742
