### ISSUE TITLE
Deploy the simplified pricing grid

### ISSUE THREAD

**Issue by southp** [Automattic/wp-calypso#95846]
## Tasks

- [ ] Deploy the simplified version as the new default to calypso
- [ ] Clean up the experiment code
- [ ] Implement the simplified pricing grid of the landing pages

**Comment by aneeshd16** [comment]
The Landpack diff is ready for review: D165563-code

**Comment by peterschimke** [comment]
@aneeshd16 and @southp I wanted to make you aware of [this conversation](https://a8c.slack.com/archives/C04DZ8M0GHW/p1730231842193199). Team T-Rex is implementing global styles for the Personal Plan. They are aiming for Nov 18th. For the pricing grid, this means that we will need to move ‘Custom fonts and colors’ from premium to personal once you are ready - see [this image](https://d.pr/i/eR7tJ3).
I think we can still move forward as is now. But may need to make this mentioned change in 2 weeks. Is this something you can accommodate? 
cc @rcrdortiz

**Comment by aneeshd16** [comment]
Thanks @peterschimke, this is already live with the new simplified grid:
![Image](https://github.com/user-attachments/assets/cf452c4a-9d0a-4896-b4d9-640543580c7f)
