### ISSUE TITLE
Ensure starter patterns are available for all new page flows

### ISSUE THREAD

**Issue by annezazu** [Automattic/wp-calypso#97534]
When creating a new page from Pages > Add New, you are presented with a set of starter patterns. If you try to create a page from the Site Editor, no starter patterns are visible:

https://github.com/user-attachments/assets/9acfdbcf-df69-49df-9c25-f8ea5cfc878f

In Core WordPress, starter patterns are available in both flows (Pages > Add new, Site Editor > Pages > Add New). Of note, work is underway to [bring zoom out to the add new page flow](https://github.com/WordPress/gutenberg/pull/66836) but, either way, we need to ensure these starter pattern options are available for folks to choose from, whether in a modal or in the Inserter with a zoomed out view.

**Tasks**

- [ ] Ensure patterns on DotCom are categorized appropriately as starter patterns so it works with this new zoom out option.
- [ ] Ensure the new zoom out to build pages options will appear in the Pages > Add new flow.
- [ ] Ensure the new zoom out to build pages options will appear in the Site Editor > Pages > Add New. This is currently missing with the DotCom pattern modal.
- [ ] Deprecate current DotCom pattern modal in favor of [zoom out powered flow](https://github.com/WordPress/gutenberg/pull/66836) when it lands.

**Comment by richtabor** [comment]
Are these patterns available in the Site Editor > Inserter > Patterns tab? As starter content patterns?

If so, we should not bring over the custom dotCom modal for selecting patterns when adding new pages. Instead we should push forward the assembling pages with patterns effort, which the Site Editor inherits, and then deprecate this existing modal in the post editor.

**Comment by annezazu** [comment]
> If so, we should not bring over the custom dotCom modal for selecting patterns when adding new pages. Instead we should push forward the assembling pages with patterns effort, which the Site Editor inherits, and then deprecate this existing modal in the post editor.

Agreed. I don't think we should use the custom modal either. I'm saying we need to have the same experience across both flows, whether it's from the modal _for now_ and for zoom out in the future.

**Comment by richtabor** [comment]
I don't think we should bring the dotCom modal over to the site editor, just to disable it in the near future.

**Comment by annezazu** [comment]
@Copons flagging this for you as a new [add new page flow powered by zoom out is coming to Gutenberg](https://github.com/WordPress/gutenberg/pull/66836). I've added a list of tasks that are needed for this and I think it aligns nicely with a Marvel focus. At this point, I expect this new option to land for Gutenberg version 20.0 in the new year.

**Comment by Copons** [comment]
Thanks @annezazu. I'll add this to the Marvel roadmap, but of course we won't explore it until January. 🙂

**Comment by Robertght** [comment]
Marking this as Triaged on the One Board as things are already being looked into.

**Comment by annezazu** [comment]
Great! Noting that this will land in GB 20.0 after being merged today: https://github.com/WordPress/gutenberg/pull/66836
