### ISSUE TITLE
Metrics for the Goals-first flow

### ISSUE THREAD

**Issue by autumnfjeld** [Automattic/wp-calypso#97576]
This parent issue captures all metrics we need in place for [Move the Goals & Design Picker to the front of the onboarding flow](https://github.com/Automattic/wp-calypso/issues/95488)

## Prior Discussions & Important Info:
* Logged-out Tracking, Spam/Abuse & Retargeting After Moving Goals Before Account Creation:  p8AJCL-Yd-p2
* Tracks Events for Goals First Flow: pfYzsZ-16M-p2
* Onboarding flow events audit: pfYzsZ-16M-p2#comment-1113
------
## ToDo Items (before launch)

- [x] Alignment and understanding of anonymous tracks events [Tracks Events for Goals First Flow]   pfYzsZ-16M-p2
- [x]  Tracks event or prop for Goals screen to differentiate Goals-first flow (treatment) vs Account-first flow (control) selection pre-account screen
- [x] New events for the "Free plan" modal https://github.com/Automattic/wp-calypso/issues/97300#issuecomment-2540143715
- [x] https://github.com/Automattic/wp-calypso/issues/98062 @candy02058912 
- [x] `calypso_signup_start` :  add prop `is_logged_out`  .  See pfYzsZ-16M-p2#comment-994
- [x] Publish metrics post pfYzsZ-163-p2 @autumnfjeld 

#### Nice to have or unsure
These are less critical, based on Isa's comment pfYzsZ-16M-p2#comment-1123
- [x]  [Tracks event: in goals-first flow domain events should not fire on the account step #98059](https://github.com/Automattic/wp-calypso/issues/98059)  Discussing is this a feature or a bug? Does it need to be fixed?
- [x]  [1. Tracks Event calypso_signup_step_start : add props goals and is_goals_first](https://github.com/Automattic/wp-calypso/issues/98058#top)
-------

## Proposed improvements for discussion
Please discuss if these suggestions are needed.  To me (Autumn) these will add clarity to usage of these events  in the new Goals-first flow.

| Existing event | Suggested change |
|--------|--------|
| calypso_signup_start | Add props  `flow: onboarding`,   `step: goals`  , `is_goals_first`|
| calypso_plan_upsell_modal_view | Add prop `flow: onboarding` |
| calypso_signup_free_plan_select | Add prop  `flow: onboarding` |
| calypso_signup_complete | Add prop: `goals: {list}`, ` theme: {theme}` |
| Cell | Cell | 

## Problems I found

* `calypso_stepper_flow_start` is firing on the domains step
  <img width="677" alt="Image" src="https://github.com/user-attachments/assets/9657a5dd-db51-4177-bd8c-489ca28a7710" />

* `calypso_stepper_flow_start` is also firing here, after a processing step and before the LP
  <img width="839" alt="Image" src="https://github.com/user-attachments/assets/a439967e-901a-41db-a33f-8ddaa634b9f7" />

* `calypso_launchpad_tasklist_viewed`   is marked as flow: build and context: onboarding. Should the flow be `onboarding`
  <img width="834" alt="Image" src="https://github.com/user-attachments/assets/6700888e-e462-4ef7-9173-9d18e103de35" />

**Comment by autumnfjeld** [comment]
See conversation with @isatuncman-auto  pfYzsZ-16M-p2#comment-994

**Comment by vykes-mac** [comment]
Started looking on these issues

**Comment by autumnfjeld** [comment]
@vykes-mac  I updated the issue description per your comment here pfYzsZ-16M-p2#comment-1004

**Comment by vykes-mac** [comment]
> calypso_launchpad_tasklist_viewed is marked as flow: build and context: onboarding. Should the flow be onboarding

@autumnfjeld This event is indeed apart of the `build` flow in the `onboarding` context. There are different flows that exist that is linked to the `site_intent` eg `write`, `link-in-bio`. Depending on the goals that were selected the `onboarding` flow will trigger another flow that is linked to the `intent`. The launchpad is a step in this other flow and not the `onboarding` flow and so it record the tracks with the name of the flow that the `onboarding` passed off to in order to show the launchpad for the intent. 

This [PR](https://github.com/Automattic/wp-calypso/pull/72520) shows more information.

**Comment by vykes-mac** [comment]
calypso_plan_upsell_modal_view | Add prop flow: onboarding
-- | --

@autumnfjeld  I don't think we need to add a prop to this one, at least not at the moment. This dialog is only accessible in the onboarding flow currently, so the flow will always be onboarding

**Comment by autumnfjeld** [comment]
@vykes-mac  Following up https://github.com/Automattic/wp-calypso/issues/97576#issuecomment-2557632352

What I'm hearing is that the mixing of `flow` `intent` and `context` is messy.   And I should add a section to the metrics post   that makes this clear, since none of this is intuitive.    I'll get your input after I think this though.

**Comment by vykes-mac** [comment]
Adding this here for discussion, will also add to the P2, however `calypso_signup_step_start (flow:onboarding; step:domains)` domain events being tracked even though we redirect to account creation is a feature see the discussion on this PR https://github.com/Automattic/wp-calypso/issues/94715

**Comment by candy02058912** [comment]
Checking 
Fire calypso_signup_actions_submit_step with goals empty when skipping goals step.

**Comment by autumnfjeld** [comment]
>  `calypso_signup_step_start (flow:onboarding; step:domains)` domain events being tracked even though we redirect to account creation is a feature see the discussion on this PR https://github.com/Automattic/wp-calypso/issues/94715

Maybe I'm missing something, but isn't it a bug in the goals first flow?   The user is _supposed_ to go Account before Domains or Plans, there isn't a "redirect" in the way this issues means redirect https://github.com/Automattic/wp-calypso/issues/94715#issue-2536176610. 

I've opened an own issue for this [Tracks event: in goals-first flow domain events should not fire on the account step #98059](https://github.com/Automattic/wp-calypso/issues/98059)

I'm in the process of organizing all the items from @skim1220 : [Tracks events audit & follow-up tracks cleanup](https://github.com/Automattic/wp-calypso/issues/98053#top)

**Comment by vykes-mac** [comment]
> >  `calypso_signup_step_start (flow:onboarding; step:domains)` domain events being tracked even though we redirect to account creation is a feature see the discussion on this PR https://github.com/Automattic/wp-calypso/issues/94715
> 
> Maybe I'm missing something, but isn't it a bug in the goals first flow?   The user is _supposed_ to go Account before Domains or Plans, there isn't a "redirect" in the way this issues means redirect https://github.com/Automattic/wp-calypso/issues/94715#issue-2536176610. 
> 
> I've opened an own issue for this [Tracks event: in goals-first flow domain events should not fire on the account step #98059](https://github.com/Automattic/wp-calypso/issues/98059)
> 
> I'm in the process of organizing all the items from @skim1220 : [Tracks events audit & follow-up tracks cleanup](https://github.com/Automattic/wp-calypso/issues/98053#top)

It actually goes to the domains step and redirects to the account creation screen, just that the redirect is not visible to the user so it appears as if it goes straight to the account creation page.

**Comment by autumnfjeld** [comment]
Yes, I see what you mean.  It just feels odd to track something the user isn't experiencing.

**Comment by alshakero** [comment]
I'm working on this. I think I found the problem.
