### ISSUE TITLE
Site Migration: Update all `/setup/migration` entrypoints to use the new experiment name

### ISSUE THREAD

**Issue by gabrielcaires** [Automattic/wp-calypso#97665]
# Goal
We want to enable users to be part of the new [2] migration flow experiment, so we need to update all entry points pointing to `/setup/migration` to use the new experiment name.

Entry points:
```[tasklist]
### Tasks
- [x] `/move` managed by our experiment blog
- [x] `/hosting`  managed by our experiment blog
- [x] `/sites >` "Add new site` > "Import"  https://github.com/Automattic/wp-calypso/blob/036325c629545ffd62b8f86399699a5fd89c4182/client/sites/hooks/use-sites-dashboard-import-site-url.ts#L18
```

**Comment by gabrielcaires** [comment]
I update directly on the wp-admin the `/move` and `/hosting`  to use the experiment name `calypso_signup_onboarding_site_migration_flow_202501_v1`
